import type { QuizQuestion } from '../../../types';

const test7Questions: QuizQuestion[] = [
  {
    question_en: "The objective of establishing a socialist society in the Second Five-Year Plan was based on what?",
    question_hi: "दूसरी पंचवर्षीय योजना में समाजवादी समाज की स्थापना का उद्देश्य किस पर आधारित था?",
    options_en: ["Poverty alleviation (Garibi Hatao)", "Boosting heavy and basic industries", "Increasing agricultural production", "Achieving self-reliance"],
    options_hi: ["गरीबी हटाओ पर", "भारी और आधारभूत उद्योगों को बढ़ाना", "कृषि उत्पादन बढ़ाना", "आत्मनिर्भरता प्राप्त करना"],
    correct_option_index: 1,
    explanation_en: "The Second Five-Year Plan (1956-61) aimed at establishing a socialist society by boosting heavy and basic industries.",
    explanation_hi: "दूसरी पंचवर्षीय योजना (1956-61) का उद्देश्य समाजवादी समाज की स्थापना के साथ भारी और आधारभूत उद्योगों को बढ़ाना था।",
  },
  {
    question_en: "Which country's cooperation was received for the establishment of Bhilai Iron and Steel Industry (Chhattisgarh)?",
    question_hi: "भिलाई लौह इस्पात उद्योग (छत्तीसगढ़) की स्थापना में किस देश का सहयोग मिला था?",
    options_en: ["Germany", "Britain", "USA", "Russia (USSR)"],
    options_hi: ["जर्मनी", "ब्रिटेन", "USA", "रूस (USSR)"],
    correct_option_index: 3,
    explanation_en: "Cooperation from Russia (USSR) was received for the establishment of Bhilai (Chhattisgarh) during the Second Five-Year Plan.",
    explanation_hi: "दूसरी पंचवर्षीय योजना में भिलाई (छत्तीसगढ़) की स्थापना के लिए रूस (USSR) का सहयोग मिला था।",
  },
  {
    question_en: "Plan Holiday came after the failure of which plan?",
    question_hi: "योजना अवकाश (Plan Holiday) किस योजना की असफलता के बाद आया?",
    options_en: ["First FYP", "Second FYP", "Third FYP", "Fourth FYP"],
    options_hi: ["पहली FYP", "दूसरी FYP", "तीसरी FYP", "चौथी FYP"],
    correct_option_index: 2,
    explanation_en: "Plan Holiday came after the failure of the Third Five-Year Plan (1961-66) due to the 1962 China War and the 1965 Pak War.",
    explanation_hi: "तीसरी पंचवर्षीय योजना (1961-66) की असफलता (1962 चीन युद्ध, 1965 पाक युद्ध) के कारण योजना अवकाश आया।",
  },
  {
    question_en: "The Fourth Five-Year Plan (1969-74) model was based on what?",
    question_hi: "चौथी पंचवर्षीय योजना (1969-74) का मॉडल किस पर आधारित था?",
    options_en: ["Harrod-Domar Model", "Gadgil Formula/Ashok Rudra Model", "Mahalanobis Model", "D.P. Dhar Model"],
    options_hi: ["हैरोड-डोमर मॉडल", "गाडगिल फॉर्मूला/अशोक रुद्र मॉडल", "महालनोबिस मॉडल", "डी.पी. धर मॉडल"],
    correct_option_index: 1,
    explanation_en: "The Fourth Plan was based on the Gadgil Formula and the Ashok Rudra and Alan Manne Model.",
    explanation_hi: "चौथी योजना गाडगिल फॉर्मूला और अशोक रुद्र एवं एलन मात्रे मॉडल पर आधारित थी।",
  },
  {
    question_en: "The operation of Tarapur Atomic Power Plant (Maharashtra) started during which plan?",
    question_hi: "तारापुर परमाणु ऊर्जा संयंत्र (महाराष्ट्र) का संचालन किस योजना के दौरान शुरू हुआ था?",
    options_en: ["Third FYP", "Fourth FYP (1969-74)", "Fifth FYP", "Plan Holiday"],
    options_hi: ["तीसरी FYP", "चौथी FYP (1969-74)", "पाँचवीं FYP", "योजना अवकाश"],
    correct_option_index: 1,
    explanation_en: "The operation of Tarapur Atomic Power Plant started during the Fourth Five-Year Plan.",
    explanation_hi: "तारापुर परमाणु ऊर्जा संयंत्र का संचालन चौथी पंचवर्षीय योजना के दौरान शुरू हुआ।",
  },
  {
    question_en: "In which plan and when was the Minimum Needs Programme started?",
    question_hi: "न्यूनतम आवश्यकता कार्यक्रम (Minimum Needs Programme) किस योजना में और कब शुरू हुआ?",
    options_en: ["Fourth Plan, 1970", "Fifth Plan, 1974-75", "Sixth Plan, 1980", "Seventh Plan, 1985"],
    options_hi: ["चौथी योजना, 1970", "पाँचवीं योजना, 1974-75", "छठी योजना, 1980", "सातवीं योजना, 1985"],
    correct_option_index: 1,
    explanation_en: "The Minimum Needs Programme started in the Fifth Plan in 1974-75.",
    explanation_hi: "न्यूनतम आवश्यकता कार्यक्रम पाँचवीं योजना में 1974-75 में शुरू हुआ।",
  },
  {
    question_en: "The Fifth Five-Year Plan (1974-78) was based on which model?",
    question_hi: "पाँचवीं पंचवर्षीय योजना (1974-78) किस मॉडल पर आधारित थी?",
    options_en: ["Gadgil Model", "D.P. Dhar Model", "Gunnar Myrdal Model", "Nehru-Mahalanobis Model"],
    options_hi: ["गाडगिल मॉडल", "डी.पी. धर मॉडल", "गुन्नार मिर्डल मॉडल", "नेहरू-महालनोबिस मॉडल"],
    correct_option_index: 1,
    explanation_en: "The model of the Fifth Plan was the D.P. Dhar Model.",
    explanation_hi: "पाँचवीं योजना का मॉडल डी.पी. धर मॉडल था।",
  },
  {
    question_en: "What was the achievement rate of the Sixth Five-Year Plan (1980-85)?",
    question_hi: "छठी पंचवर्षीय योजना (1980-85) की प्राप्ति (Achievement) दर क्या थी?",
    options_en: ["5.2%", "5.74%", "6.0%", "4.4%"],
    options_hi: ["5.2%", "5.74%", "6.0%", "4.4%"],
    correct_option_index: 1,
    explanation_en: "The achievement rate of the Sixth Plan was 5.74%.",
    explanation_hi: "छठी योजना की प्राप्ति दर 5.74% थी।",
  },
  {
    question_en: "Rolling Plan was based on the model of which economist?",
    question_hi: "रोलिंग प्लान (अनवरत योजना) किस अर्थशास्त्री के मॉडल पर आधारित थी?",
    options_en: ["D.P. Dhar", "P.C. Mahalanobis", "Gunnar Myrdal", "K.N. Rao"],
    options_hi: ["डी.पी. धर", "पी.सी. महालनोबिस", "गुन्नार मिर्डल", "के.एन. राव"],
    correct_option_index: 2,
    explanation_en: "The Rolling Plan (1978-80) was based on the Gunnar Myrdal Model.",
    explanation_hi: "रोलिंग प्लान (1978-80) गुन्नार मिर्डल मॉडल पर आधारित था।",
  },
  {
    question_en: "The establishment of NHB (National Housing Bank) took place during which plan?",
    question_hi: "NHB (नेशनल हाउसिंग बैंक) की स्थापना किस योजना के दौरान हुई?",
    options_en: ["Sixth FYP", "Seventh FYP (1985-90)", "Eighth FYP", "Annual Plan (1990-92)"],
    options_hi: ["छठी FYP", "सातवीं FYP (1985-90)", "आठवीं FYP", "वार्षिक योजना (1990-92)"],
    correct_option_index: 1,
    explanation_en: "NHB was established on July 9, 1988, during the Seventh Five-Year Plan.",
    explanation_hi: "NHB की स्थापना 9 जुलाई 1988 को सातवीं पंचवर्षीय योजना के दौरान हुई।",
  },
  {
    question_en: "The establishment of WTO (World Trade Organization) (1995) took place during which Five-Year Plan?",
    question_hi: "WTO (विश्व व्यापार संगठन) की स्थापना (1995) किस पंचवर्षीय योजना के दौरान हुई?",
    options_en: ["Seventh FYP", "Eighth FYP (1992-97)", "Ninth FYP", "Annual Plan (1990-92)"],
    options_hi: ["सातवीं FYP", "आठवीं FYP (1992-97)", "नौवीं FYP", "वार्षिक योजना (1990-92)"],
    correct_option_index: 1,
    explanation_en: "The establishment of WTO took place in 1995, which falls during the Eighth Plan.",
    explanation_hi: "WTO की स्थापना 1995 में हुई, जो आठवीं योजना के दौरान आता है।",
  },
  {
    question_en: "New Economic Policy (NEP) 1991 was first implemented in which plan?",
    question_hi: "नई आर्थिक नीति (NEP) 1991 पहली बार किस योजना में लागू हुई?",
    options_en: ["Seventh Plan", "Eighth Plan", "Ninth Plan", "Annual Plan"],
    options_hi: ["सातवीं योजना", "आठवीं योजना", "नौवीं योजना", "वार्षिक योजना"],
    correct_option_index: 1,
    explanation_en: "The Eighth Five-Year Plan was the first to be implemented after the NEP 1991.",
    explanation_hi: "NEP 1991 के बाद आठवीं पंचवर्षीय योजना पहली बार लागू हुई।",
  },
  {
    question_en: "In which year was Sarva Shiksha Abhiyan (SSA) implemented?",
    question_hi: "सर्व शिक्षा अभियान (SSA) किस वर्ष लागू हुआ?",
    options_en: ["1998", "1999", "2001", "2004"],
    options_hi: ["1998", "1999", "2001", "2004"],
    correct_option_index: 2,
    explanation_en: "Sarva Shiksha Abhiyan was implemented in 2001.",
    explanation_hi: "सर्व शिक्षा अभियान 2001 में लागू हुआ।",
  },
  {
    question_en: "What was the main objective of the 11th Five-Year Plan (2007-12)?",
    question_hi: "11वीं पंचवर्षीय योजना (2007-12) का मुख्य उद्देश्य क्या था?",
    options_en: ["Social justice and economic growth", "Inclusive Sustainable Growth", "Poverty alleviation (Garibi Hatao)", "Faster and Sustainable Growth"],
    options_hi: ["सामाजिक न्याय और आर्थिक संवृद्धि", "समावेशी सतत विकास (Inclusive Sustainable Growth)", "गरीबी हटाओ", "तीव्रतर और सतत विकास"],
    correct_option_index: 1,
    explanation_en: "The objective of the 11th Plan was Inclusive Sustainable Growth.",
    explanation_hi: "11वीं योजना का उद्देश्य समावेशी सतत विकास था।",
  },
  {
    question_en: "What was the main objective of the 12th Five-Year Plan (2012-17)?",
    question_hi: "12वीं पंचवर्षीय योजना (2012-17) का मुख्य उद्देश्य क्या था?",
    options_en: ["Only Faster Development", "Only Social Development", "Faster, Sustainable and Inclusive Growth", "Only Self-Reliance"],
    options_hi: ["केवल तीव्र विकास", "केवल सामाजिक विकास", "तीव्रतर, सतत एवं समावेशी विकास", "केवल आत्मनिर्भरता"],
    correct_option_index: 2,
    explanation_en: "The objective of the 12th Plan was Faster, Sustainable and Inclusive Growth.",
    explanation_hi: "12वीं योजना का उद्देश्य तीव्रतर, सतत एवं समावेशी विकास था।",
  },
  {
    question_en: "Dr. V.K.R.V. Rao, who made the scientific estimate of National Income (1931), measured it in what form?",
    question_hi: "राष्ट्रीय आय का वैज्ञानिक अनुमान (1931) लगाने वाले डॉ. वी.के.आर.वी. राव ने इसे किस रूप में मापा था?",
    options_en: ["Only in the form of goods", "In the form of Money (मुद्रा)", "Only in the form of services", "In the form of gold"],
    options_hi: ["केवल वस्तुओं के रूप में", "मुद्रा (Money) के रूप में", "केवल सेवाओं के रूप में", "सोने के रूप में"],
    correct_option_index: 1,
    explanation_en: "National income is measured in the form of Money.",
    explanation_hi: "राष्ट्रीय आय को मुद्रा (Money) के रूप में मापा जाता है।",
  },
  {
    question_en: "In the Factor Income Method, what is received in exchange for Capital?",
    question_hi: "कारक आय विधि (Factor Income Method) में पूंजी (Capital) के बदले क्या प्राप्त होता है?",
    options_en: ["Rent", "Profit", "Interest (ब्याज)", "Wages"],
    options_hi: ["किराया", "लाभ", "ब्याज (Interest)", "वेतन"],
    correct_option_index: 2,
    explanation_en: "Interest is received in exchange for the factor of production, Capital.",
    explanation_hi: "उत्पादन के कारक पूंजी के बदले ब्याज (Interest) प्राप्त होता है।",
  },
  {
    question_en: "What is the correct formula for Gross National Product (GNP)?",
    question_hi: "सकल राष्ट्रीय उत्पाद (GNP) का सही सूत्र क्या है?",
    options_en: ["GDP + Depreciation", "NDP + Net income from abroad", "GDP + Net Factor Income from Abroad", "Production within the country's border only"],
    options_hi: ["GDP + मूल्य ह्रास", "NDP + विदेश से शुद्ध आय", "GDP + विदेशों से प्राप्त शुद्ध कारक आय", "केवल देश की सीमा में उत्पादन"],
    correct_option_index: 2,
    explanation_en: "GNP = GDP + Net Factor Income from Abroad.",
    explanation_hi: "GNP = GDP + विदेशों से प्राप्त शुद्ध कारक आय।",
  },
  {
    question_en: "To obtain NDP (Net Domestic Product), what is done to the depreciation in GDP?",
    question_hi: "NDP (शुद्ध घरेलू उत्पाद) की प्राप्ति के लिए GDP में से मूल्य ह्रास को क्या किया जाता है?",
    options_en: ["Added", "Subtracted", "Multiplied", "Kept unchanged"],
    options_hi: ["जोड़ा जाता है", "घटाया जाता है", "गुणा किया जाता है", "अपरिवर्तित रखा जाता है"],
    correct_option_index: 1,
    explanation_en: "To obtain NDP, depreciation is subtracted from GDP.",
    explanation_hi: "NDP की प्राप्ति के लिए GDP में से मूल्य ह्रास को घटाया जाता है।",
  },
  {
    question_en: "What is the correct formula for the GDP Deflator?",
    question_hi: "GDP अपस्फीतिकारक (Deflator) का सही सूत्र क्या है?",
    options_en: ["(Real GDP / Nominal GDP) x 100", "(GNP / GDP) x 100", "(Nominal GDP / Real GDP) x 100", "(NDP / GDP) x 100"],
    options_hi: ["(Real GDP / Nominal GDP) x 100", "(GNP / GDP) x 100", "(Nominal GDP / Real GDP) x 100", "(NDP / GDP) x 100"],
    correct_option_index: 2,
    explanation_en: "The formula for the GDP Deflator is: (Nominal GDP / Real GDP) x 100.",
    explanation_hi: "GDP अपस्फीतिकारक का सूत्र है: (Nominal GDP / Real GDP) x 100।",
  },
  {
    question_en: "Hindu Growth Rate (HGIR) was related to which rate?",
    question_hi: "Hindu Growth Rate (HGIR) का संबंध किस दर से था?",
    options_en: ["Inflation rate", "Population rate", "National Income (GDP) growth rate (3.5%)", "Agricultural growth rate"],
    options_hi: ["मुद्रास्फीति दर", "जनसंख्या दर", "राष्ट्रीय आय (GDP) विकास दर (3.5%)", "कृषि विकास दर"],
    correct_option_index: 2,
    explanation_en: "HGIR was related to the 3.5% National Income (GDP) growth rate during the 1950s-80s.",
    explanation_hi: "HGIR का संबंध 1950-80 के दशक की 3.5% की राष्ट्रीय आय (GDP) विकास दर से है।",
  },
  {
    question_en: "Which of the following items is not included in the calculation of National Income?",
    question_hi: "निम्नलिखित में से कौन सी मद राष्ट्रीय आय की गणना में शामिल नहीं की जाती है?",
    options_en: ["Purchase and sale of shares", "Domestic work (e.g., washing dishes)", "Transfer payments (pension, lottery)", "All of the above"],
    options_hi: ["शेयरों का क्रय-विक्रय", "घरेलू कार्य (जैसे बर्तन धोना)", "हस्तांतरण भुगतान (पेंशन, लॉटरी)", "उपरोक्त सभी"],
    correct_option_index: 3,
    explanation_en: "Purchase and sale of shares, domestic work, and transfer payments are not included in National Income.",
    explanation_hi: "शेयरों का क्रय-विक्रय, घरेलू कार्य और हस्तांतरण भुगतान राष्ट्रीय आय में शामिल नहीं होते हैं।",
  },
  {
    question_en: "Which two institutions were merged to form NSO (National Statistical Office)?",
    question_hi: "NSO (राष्ट्रीय सांख्यिकी कार्यालय) की स्थापना में किन दो संस्थाओं का विलय किया गया?",
    options_en: ["NITI Aayog + CSO", "CSO + NSSO", "CSO + Finance Ministry", "NSSO + Planning Commission"],
    options_hi: ["NITI Aayog + CSO", "CSO + NSSO", "CSO + Finance Ministry", "NSSO + Planning Commission"],
    correct_option_index: 1,
    explanation_en: "NSO was established on May 23, 2019, by merging CSO and NSSO.",
    explanation_hi: "NSO की स्थापना CSO और NSSO को मिलाकर 23 मई 2019 को हुई थी।",
  },
  {
    question_en: "In the Indian Constitution, the term 'Budget' is mentioned as what?",
    question_hi: "भारतीय संविधान में 'बजट' शब्द का उल्लेख किस रूप में किया गया है?",
    options_en: ["Budget", "Financial Year", "Annual Financial Statement (Article 112)", "Subject of Concurrent List"],
    options_hi: ["बजट", "वित्तीय वर्ष", "वार्षिक वित्तीय विवरण (Article 112)", "समवर्ती सूची का विषय"],
    correct_option_index: 2,
    explanation_en: "The Central Budget is mentioned as the 'Annual Financial Statement' (Article 112).",
    explanation_hi: "केंद्रीय बजट का उल्लेख 'वार्षिक वित्तीय विवरण' (Article 112) के रूप में है।",
  },
  {
    question_en: "Who presented the first budget of Republican India?",
    question_hi: "गणतंत्र भारत (Republic India) का पहला बजट किसने प्रस्तुत किया?",
    options_en: ["R.K. Shanmukham Chetty (1947)", "John Mathai (1950)", "James Wilson (1860)", "Manmohan Singh (1991)"],
    options_hi: ["आर.के. षणमुखम चेट्टी (1947)", "जॉन मथाई (1950)", "जेम्स विल्सन (1860)", "मनमोहन सिंह (1991)"],
    correct_option_index: 1,
    explanation_en: "The first budget of Republican India was presented by John Mathai in 1950.",
    explanation_hi: "गणतंत्र भारत का पहला बजट जॉन मथाई ने 1950 में प्रस्तुत किया।",
  },
  {
    question_en: "Who prepares and drafts the Economic Survey?",
    question_hi: "आर्थिक सर्वेक्षण (Economic Survey) का निर्माण और तैयारी कौन करता है?",
    options_en: ["RBI", "Finance Minister", "Department of Economic Affairs under the direction of Chief Economic Advisor (CEA)", "NITI Aayog"],
    options_hi: ["RBI", "वित्त मंत्री", "मुख्य आर्थिक सलाहकार (CEA) के निर्देशन में आर्थिक कार्य विभाग", "NITI Aayog"],
    correct_option_index: 2,
    explanation_en: "The Economic Survey is prepared by the Department of Economic Affairs (Ministry of Finance) under the direction of the Chief Economic Advisor (CEA).",
    explanation_hi: "आर्थिक सर्वेक्षण का निर्माण मुख्य आर्थिक सलाहकार (CEA) के निर्देशन में आर्थिक कार्य विभाग (वित्त मंत्रालय) द्वारा होता है।",
  },
  {
    question_en: "What is the government income called that neither reduces assets nor increases liability (debt)?",
    question_hi: "सरकार की वह आय जिससे न तो संपत्ति में कमी होती है और न ही कर्ज (Liability) में वृद्धि, क्या कहलाती है?",
    options_en: ["Capital Receipt", "Revenue Receipt", "Capital Expenditure", "Revenue Expenditure"],
    options_hi: ["पूंजीगत आय", "राजस्व आय", "पूंजीगत व्यय", "राजस्व व्यय"],
    correct_option_index: 1,
    explanation_en: "Taxes, penalties, fees, and profits from PSUs are examples of Revenue Receipts.",
    explanation_hi: "कर, पेनल्टी, फीस और PSU से प्राप्त लाभ राजस्व आय के उदाहरण हैं।",
  },
  {
    question_en: "Which item is included under Capital Receipt?",
    question_hi: "पूंजीगत आय (Capital Receipt) के तहत कौन सा मद शामिल है?",
    options_en: ["Salary", "Penalty", "Disinvestment of PSU (Government Undertaking)", "Interest payment"],
    options_hi: ["वेतन", "जुर्माना", "PSU (सरकारी उपक्रम) का विनिवेश", "ब्याज भुगतान"],
    correct_option_index: 2,
    explanation_en: "Capital Receipt is one that reduces assets (disinvestment) or increases debt (borrowing).",
    explanation_hi: "पूंजीगत आय वह है जिससे संपत्ति कम हो (विनिवेश) या कर्ज बढ़े (उधार)।",
  },
  {
    question_en: "What is the government expenditure called that neither increases assets nor reduces debt?",
    question_hi: "सरकार का ऐसा खर्च जिससे न तो संपत्ति में वृद्धि हो और न कर्ज में कमी, क्या कहलाता है?",
    options_en: ["Capital Expenditure", "Capital Receipt", "Revenue Expenditure", "Revenue Receipt"],
    options_hi: ["पूंजीगत व्यय", "पूंजीगत आय", "राजस्व व्यय", "राजस्व आय"],
    correct_option_index: 2,
    explanation_en: "Salaries, pensions, subsidies, and interest payments are Revenue Expenditures.",
    explanation_hi: "वेतन, पेंशन, सब्सिडी, ब्याज अदायगी राजस्व व्यय हैं।",
  },
  {
    question_en: "What is the primary objective of Capital Expenditure?",
    question_hi: "पूंजीगत व्यय (Capital Expenditure) का प्राथमिक उद्देश्य क्या है?",
    options_en: ["Providing subsidy", "Increasing assets (e.g., construction of roads, buildings)", "Making interest payments", "Reducing revenue deficit"],
    options_hi: ["सब्सिडी प्रदान करना", "संपत्ति में वृद्धि करना (जैसे सड़क, भवन का निर्माण)", "ब्याज भुगतान करना", "राजस्व घाटा कम करना"],
    correct_option_index: 1,
    explanation_en: "Capital expenditure leads to an increase in assets or a reduction in debt.",
    explanation_hi: "पूंजीगत व्यय से संपत्ति में वृद्धि या कर्ज में कमी होती है।",
  },
  {
    question_en: "When does the situation of Budget Surplus occur?",
    question_hi: "बजट अधिशेष (Surplus Budget) की स्थिति कब होती है?",
    options_en: ["When total expenditure is greater than total income", "When total income (Total Income) is greater than total expenditure (Total Expenditure)", "When total income = total expenditure", "When Revenue Expenditure > Revenue Receipt"],
    options_hi: ["जब कुल व्यय कुल आय से अधिक हो", "जब कुल आय (Total Income) कुल व्यय (Total Expenditure) से ज्यादा हो", "जब कुल आय = कुल व्यय हो", "जब राजस्व व्यय > राजस्व आय हो"],
    correct_option_index: 1,
    explanation_en: "Budget surplus occurs when total income (receipt) is greater than total expenditure.",
    explanation_hi: "बजट अधिशेष तब होता है जब कुल आय (प्राप्ति) कुल व्यय से ज्यादा होती है।",
  },
  {
    question_en: "When does the situation of Revenue Deficit occur?",
    question_hi: "राजस्व घाटा (Revenue Deficit) की स्थिति कब उत्पन्न होती है?",
    options_en: ["When RE = RI", "When Revenue Expenditure (RE) is greater than Revenue Income (RI) (RE > RI)", "When FD > PD", "When Total Expenditure > Total Income"],
    options_hi: ["जब RE = RI हो", "जब राजस्व व्यय (RE) राजस्व आय (RI) से ज्यादा हो (RE > RI)", "जब FD > PD हो", "जब कुल व्यय > कुल आय हो"],
    correct_option_index: 1,
    explanation_en: "Revenue Deficit occurs when Revenue Expenditure is greater than Revenue Income.",
    explanation_hi: "राजस्व घाटा तब होता है जब राजस्व व्यय, राजस्व आय से ज्यादा होता है।",
  },
  {
    question_en: "What is the formula for Primary Deficit?",
    question_hi: "प्राथमिक घाटा (Primary Deficit) का सूत्र क्या है?",
    options_en: ["FD + Interest Payment", "RD - Interest Payment", "Fiscal Deficit (FD) - Interest Payment (IP)", "Revenue Deficit + Interest Payment"],
    options_hi: ["FD + ब्याज भुगतान", "RD - ब्याज भुगतान", "राजकोषीय घाटा (FD) - ब्याज भुगतान (IP)", "राजस्व घाटा + ब्याज भुगतान"],
    correct_option_index: 2,
    explanation_en: "Primary Deficit = Fiscal Deficit - Interest Payment.",
    explanation_hi: "प्राथमिक घाटा = राजकोषीय घाटा - ब्याज भुगतान।",
  },
  {
    question_en: "What does Monetary Deficit indicate?",
    question_hi: "मौद्रिक घाटा (Monetary Deficit) क्या दर्शाता है?",
    options_en: ["Total internal borrowing", "Borrowing from RBI", "Borrowing from foreign organizations", "Adding interest to Primary Deficit"],
    options_hi: ["कुल आंतरिक उधारी", "RBI से लिया गया उधार", "विदेशी संगठनों से लिया गया उधार", "प्राथमिक घाटे में ब्याज जोड़ना"],
    correct_option_index: 1,
    explanation_en: "Monetary Deficit is the borrowing from RBI.",
    explanation_hi: "मौद्रिक घाटा RBI से लिया गया उधार होता है।",
  },
  {
    question_en: "Who regulates the Money Market?",
    question_hi: "मुद्रा बाजार (Money Market) का विनियमन कौन करता है?",
    options_en: ["SEBI", "Ministry of Finance", "RBI", "NSE"],
    options_hi: ["SEBI", "वित्त मंत्रालय", "RBI", "NSE"],
    correct_option_index: 2,
    explanation_en: "The Money Market is regulated by the RBI.",
    explanation_hi: "मुद्रा बाजार का विनियमन RBI द्वारा किया जाता है।",
  },
  {
    question_en: "For how long is the finance traded in the Money Market at maximum?",
    question_hi: "मुद्रा बाजार में वित्त का लेन-देन अधिकतम कितनी अवधि के लिए होता है?",
    options_en: ["More than 1 year", "2 years", "365 days or less", "5 years"],
    options_hi: ["1 वर्ष से अधिक", "2 वर्ष", "365 दिन या उससे कम", "5 वर्ष"],
    correct_option_index: 2,
    explanation_en: "Finance is traded in the Money Market for a period of 365 days or less.",
    explanation_hi: "मुद्रा बाजार में वित्त का लेन-देन 365 दिन या उससे कम अवधि के लिए होता है।",
  },
  {
    question_en: "For how long is the finance traded in the Capital Market?",
    question_hi: "पूंजी बाजार (Capital Market) में वित्त का लेन-देन कितनी अवधि के लिए होता है?",
    options_en: ["365 days or less", "More than one year", "Only one night", "90 days"],
    options_hi: ["365 दिन या उससे कम", "एक वर्ष से अधिक", "केवल एक रात", "90 दिन"],
    correct_option_index: 1,
    explanation_en: "Finance is traded in the Capital Market for a period of more than one year.",
    explanation_hi: "पूंजी बाजार में वित्त का लेन-देन एक वर्ष से अधिक समय के लिए होता है।",
  },
  {
    question_en: "What is the main feature of the Primary Capital Market?",
    question_hi: "प्राथमिक पूंजी बाजार (Primary Capital Market) की मुख्य विशेषता क्या है?",
    options_en: ["Transaction between investors", "Direct relationship between the company and the investor", "Transaction of bonds only", "Transaction of FPO only"],
    options_hi: ["निवेशकों के मध्य लेन-देन", "कंपनी और निवेशक के मध्य सीधा संबंध", "केवल बॉन्ड का लेन-देन", "केवल FPO का लेन-देन"],
    correct_option_index: 1,
    explanation_en: "In the Primary Capital Market, there is a direct relationship between the company and the investor.",
    explanation_hi: "प्राथमिक पूंजी बाजार में कंपनी और निवेशक के मध्य सीधा संबंध होता है।",
  },
  {
    question_en: "What is FPO (Follow-on Public Offer)?",
    question_hi: "FPO (Follow-on Public Offer) क्या है?",
    options_en: ["Issuing shares for the first time (IPO)", "Issuing additional shares to those already issued for the purpose of additional finance collection", "Selling government securities", "Share transaction between investors"],
    options_hi: ["पहली बार शेयर जारी करना (IPO)", "अतिरिक्त वित्त संग्रहण के उद्देश्य से पहले से जारी शेयरों के अतिरिक्त शेयर जारी करना", "सरकारी प्रतिभूतियां बेचना", "शेयर का लेन-देन निवेशकों के मध्य होना"],
    correct_option_index: 1,
    explanation_en: "FPO is issued when a company issues additional shares for the purpose of collecting additional finance.",
    explanation_hi: "FPO तब जारी होता है जब कंपनी अतिरिक्त वित्त संग्रहण के उद्देश्य से अतिरिक्त शेयर जारी करती है।",
  },
  {
    question_en: "What is the use of a Demat Account?",
    question_hi: "Demat Account का क्या उपयोग है?",
    options_en: ["Only depositing currency", "Only foreign exchange transaction", "For buying and selling shares (in Electronic form)", "Taking a loan from the bank"],
    options_hi: ["केवल मुद्रा जमा करना", "केवल विदेशी मुद्रा का लेन-देन", "शेयरों की खरीद-बिक्री के लिए (Electronic form में)", "बैंक से ऋण लेना"],
    correct_option_index: 2,
    explanation_en: "Demat account is used for buying and selling shares.",
    explanation_hi: "डीमैट खाता शेयरों की खरीद-बिक्री के लिए उपयोग किया जाता है।",
  },
  {
    question_en: "When was SEBI (Securities and Exchange Board of India) established?",
    question_hi: "SEBI (सिक्योरिटीज एंड एक्सचेंज बोर्ड ऑफ इंडिया) की स्थापना कब हुई थी?",
    options_en: ["January 30, 1992", "April 12, 1988", "1875", "1995"],
    options_hi: ["30 जनवरी 1992", "12 अप्रैल 1988", "1875", "1995"],
    correct_option_index: 1,
    explanation_en: "SEBI was established on April 12, 1988.",
    explanation_hi: "SEBI की स्थापना 12 अप्रैल 1988 को हुई थी।",
  },
  {
    question_en: "On which date did SEBI receive Statutory Status?",
    question_hi: "SEBI को किस तिथि को सांविधिक दर्जा (Statutory Status) प्राप्त हुआ था?",
    options_en: ["April 12, 1988", "January 30, 1992 (SEBI Act 1992)", "1986", "1875"],
    options_hi: ["12 अप्रैल 1988", "30 जनवरी 1992 (SEBI Act 1992)", "1986", "1875"],
    correct_option_index: 1,
    explanation_en: "SEBI received Statutory Status on January 30, 1992.",
    explanation_hi: "SEBI को 30 जनवरी 1992 को सांविधिक दर्जा प्राप्त हुआ था।",
  },
  {
    question_en: "NSE (National Stock Exchange) was established on the recommendation of which committee?",
    question_hi: "NSE (नेशनल स्टॉक एक्सचेंज) की स्थापना किस समिति की सिफारिश पर हुई थी?",
    options_en: ["Narasimham Committee", "Shivraman Committee", "Ferwani Committee (1992)", "K.C. Neogy Committee"],
    options_hi: ["नरसिम्हन समिति", "शिवरामन समिति", "फेरवनी समिति (1992)", "के.सी. नियोगी समिति"],
    correct_option_index: 2,
    explanation_en: "NSE was established on the recommendation of the Ferwani Committee in 1992.",
    explanation_hi: "NSE की स्थापना फेरवनी समिति की सिफारिश पर 1992 में हुई थी।",
  },
  {
    question_en: "What is the other name of BSE (Bombay Stock Exchange)?",
    question_hi: "BSE (बॉम्बे स्टॉक एक्सचेंज) का अन्य नाम क्या है?",
    options_en: ["NSE", "Ferwani Street", "Dalal Street", "Wall Street"],
    options_hi: ["NSE", "फेरवनी स्ट्रीट", "दलाल स्ट्रीट", "वॉल स्ट्रीट"],
    correct_option_index: 2,
    explanation_en: "The other name of BSE (1875) is Dalal Street.",
    explanation_hi: "BSE (1875) का अन्य नाम दलाल स्ट्रीट है।",
  },
  {
    question_en: "When was GST implemented in India?",
    question_hi: "GST भारत में कब लागू हुआ?",
    options_en: ["July 1, 2016", "July 1, 2017", "September 8, 2016", "August 3, 2016"],
    options_hi: ["1 जुलाई 2016", "1 जुलाई 2017", "8 सितंबर 2016", "3 अगस्त 2016"],
    correct_option_index: 1,
    explanation_en: "GST was implemented in India on July 1, 2017.",
    explanation_hi: "GST भारत में 1 जुलाई 2017 को लागू हुआ।",
  },
  {
    question_en: "Which was the last state in India to implement GST?",
    question_hi: "GST लागू करने वाला भारत का अंतिम राज्य कौन सा था?",
    options_en: ["Assam", "Bihar", "Jammu and Kashmir (J&K)", "Gujarat"],
    options_hi: ["असम", "बिहार", "जम्मू और कश्मीर (J&K)", "गुजरात"],
    correct_option_index: 2,
    explanation_en: "The last state to implement GST was Jammu and Kashmir (J&K).",
    explanation_hi: "GST लागू करने वाला अंतिम राज्य जम्मू और कश्मीर (J&K) था।",
  },
  {
    question_en: "Where was the 122nd Constitution Amendment Bill (2016) for GST first passed?",
    question_hi: "GST के लिए 122वाँ संविधान संशोधन विधेयक (2016) सर्वप्रथम कहाँ पारित हुआ था?",
    options_en: ["Lok Sabha", "Rajya Sabha (August 3, 2016)", "President's signature", "GST Council"],
    options_hi: ["लोकसभा", "राज्यसभा (3 अगस्त 2016)", "राष्ट्रपति के हस्ताक्षर", "GST परिषद"],
    correct_option_index: 1,
    explanation_en: "The 122nd Constitution Amendment Bill was first passed in the Rajya Sabha (August 3, 2016).",
    explanation_hi: "122वाँ संविधान संशोधन विधेयक सबसे पहले राज्यसभा (3 अगस्त 2016) में पारित हुआ।",
  },
  {
    question_en: "What is the total number of members in the GST Council?",
    question_hi: "GST परिषद (GST Council) में कुल कितने सदस्य होते हैं?",
    options_en: ["25", "30", "33", "35"],
    options_hi: ["25", "30", "33", "35"],
    correct_option_index: 2,
    explanation_en: "The GST Council has a total of 33 members.",
    explanation_hi: "GST परिषद में कुल 33 सदस्य होते हैं।",
  },
  {
    question_en: "Who is the chairman of the GST Council?",
    question_hi: "GST परिषद का अध्यक्ष कौन होता है?",
    options_en: ["Prime Minister", "RBI Governor", "Union Finance Minister", "State Finance Ministers"],
    options_hi: ["प्रधानमंत्री", "RBI गवर्नर", "केंद्रीय वित्त मंत्री", "राज्यों के वित्त मंत्री"],
    correct_option_index: 2,
    explanation_en: "The chairman of the GST Council is the Union Finance Minister.",
    explanation_hi: "GST परिषद का अध्यक्ष केंद्रीय वित्त मंत्री होता है।",
  },
  {
    question_en: "Which product is included in the items kept outside the purview of GST?",
    question_hi: "GST के दायरे से बाहर रखी गई वस्तुओं में कौन सा उत्पाद शामिल है?",
    options_en: ["Petroleum products", "Cloth", "Car", "Cement"],
    options_hi: ["पेट्रोलियम उत्पाद", "कपड़ा", "कार", "सीमेंट"],
    correct_option_index: 0,
    explanation_en: "Petroleum products, alcohol for human consumption, tobacco products, etc., are outside the purview of GST.",
    explanation_hi: "पेट्रोलियम उत्पाद, मानव उपभोग हेतु शराब, तंबाकू उत्पाद, आदि GST के दायरे से बाहर हैं।",
  }
];

export default test7Questions;