import type { QuizQuestion } from '../../../types';

const test5Questions: QuizQuestion[] =  [
  {
    question_en: "According to the notes, what is the value of gold fixed under the Minimum Reserve System (MRS) of RBI?",
    question_hi: "नोट्स के अनुसार, RBI के न्यूनतम आरक्षित प्रणाली (Minimum Reserve System) के तहत सोने (Gold) का मूल्य कितना निर्धारित है?",
    options_en: ["₹85 Crore", "₹200 Crore", "₹115 Crore"],
    options_hi: ["₹85 करोड़", "₹200 करोड़", "₹115 करोड़"],
    correct_option_index: 2,
    explanation_en: "Under the Minimum Reserve System (adopted in 1956), RBI must maintain a total reserve of ₹200 crore, of which ₹115 crore must be in the form of gold and the remaining ₹85 crore in foreign currency.",
    explanation_hi: "न्यूनतम आरक्षित प्रणाली (1956 में अपनाई गई) के तहत, RBI को ₹200 करोड़ का कुल आरक्षित कोष बनाए रखना होता है, जिसमें से ₹115 करोड़ सोने के रूप में और शेष ₹85 करोड़ विदेशी मुद्रा के रूप में होना चाहिए।",
  },
  {
    question_en: "What is the number of Nominated Members in the Central Board of Directors (CBD) of RBI?",
    question_hi: "RBI के सेंट्रल बोर्ड ऑफ डायरेक्टर्स (CBD) में नामांकित सदस्यों (Nominated Members) की संख्या कितनी होती है?",
    options_en: ["4 members", "6 members", "10 members"],
    options_hi: ["4 सदस्य", "6 सदस्य", "10 सदस्य"],
    correct_option_index: 2,
    explanation_en: "The Government of India nominates 10 Directors from various fields to the Central Board of RBI. In addition, 2 government officials and 4 directors (from local boards) are also nominated.",
    explanation_hi: "भारत सरकार RBI के सेंट्रल बोर्ड में विभिन्न क्षेत्रों से 10 निदेशकों को नामांकित करती है। इसके अतिरिक्त, 2 सरकारी अधिकारी और 4 निदेशक (स्थानीय बोर्डों से) भी नामांकित होते हैं।",
  },
  {
    question_en: "Which country did the first Governor of RBI (Sir Osborne Smith) belong to (who was not an Indian)?",
    question_hi: "RBI के पहले गवर्नर (सर ऑस्बोर्न स्मिथ) किस देश के थे (जो भारतीय नहीं थे)?",
    options_en: ["India", "Myanmar", "Britain (Estimated)"],
    options_hi: ["भारत", "म्यांमार", "ब्रिटेन (अनुमानित)"],
    correct_option_index: 2,
    explanation_en: "Sir Osborne Smith was a British banker and served as the first Governor of the RBI from April 1, 1935, to June 30, 1937. The first Indian Governor was C.D. Deshmukh.",
    explanation_hi: "सर ऑस्बोर्न स्मिथ एक ब्रिटिश बैंकर थे और उन्होंने 1 अप्रैल 1935 से 30 जून 1937 तक RBI के पहले गवर्नर के रूप में कार्य किया। पहले भारतीय गवर्नर सी.डी. देशमुख थे।",
  },
  {
    question_en: "If RBI increases the CRR (Cash Reserve Ratio), what will be the effect on the credit creation of commercial banks?",
    question_hi: "यदि RBI CRR (नकद आरक्षित अनुपात) को बढ़ाता है, तो वाणिज्यिक बैंकों के साख सृजन (Credit Creation) पर क्या प्रभाव पड़ेगा?",
    options_en: ["Credit creation will increase.", "Credit creation will decrease, as liquidity will reduce.", "Credit creation will remain unchanged."],
    options_hi: ["साख सृजन बढ़ेगा।", "साख सृजन घटेगा, क्योंकि तरलता कम होगी।", "साख सृजन अपरिवर्तित रहेगा।"],
    correct_option_index: 1,
    explanation_en: "When CRR is increased, banks have to keep a larger portion of their deposits with the RBI, leaving them with less money to lend. This reduces their credit creation capacity and sucks liquidity from the market.",
    explanation_hi: "जब CRR बढ़ाया जाता है, तो बैंकों को अपनी जमा राशि का एक बड़ा हिस्सा RBI के पास रखना पड़ता है, जिससे उनके पास ऋण देने के लिए कम पैसा बचता है। इससे उनकी साख सृजन क्षमता कम हो जाती है और बाजार से तरलता कम हो जाती है।",
  },
  {
    question_en: "Under which act does the RBI regulate and control the banking system in India?",
    question_hi: "RBI किस अधिनियम के तहत भारत में बैंकिंग प्रणाली का विनियमन एवं नियंत्रण करता है?",
    options_en: ["RBI Act 1934", "SEBI Act 1992", "Banking Regulation Act 1949"],
    options_hi: ["RBI Act 1934", "SEBI Act 1992", "Banking Regulation Act 1949"],
    correct_option_index: 2,
    explanation_en: "While the RBI Act 1934 established the RBI, the Banking Regulation Act 1949 gives the RBI the powers to regulate and supervise commercial banks in India.",
    explanation_hi: "हालांकि RBI अधिनियम 1934 ने RBI की स्थापना की, लेकिन बैंकिंग विनियमन अधिनियम 1949 RBI को भारत में वाणिज्यिक बैंकों को विनियमित और पर्यवेक्षित करने की शक्तियां देता है।",
  },
  {
    question_en: "Under the SDF (Standing Deposit Facility), how do commercial banks deposit their excess liquidity with the RBI?",
    question_hi: "SDF (Standing Deposit Facility) के तहत वाणिज्यिक बैंक अपनी अतिरिक्त तरलता को RBI के पास कैसे जमा करते हैं?",
    options_en: ["At a high interest rate", "Without Collateral", "Only for one day"],
    options_hi: ["उच्च ब्याज दर पर", "बिना ज़मानत (Without Collateral) के", "केवल एक दिन के लिए"],
    correct_option_index: 1,
    explanation_en: "The main feature of the SDF is that it allows RBI to absorb liquidity from banks without providing any collateral (like government securities) in return. This distinguishes it from the reverse repo rate.",
    explanation_hi: "SDF की मुख्य विशेषता यह है कि यह RBI को बैंकों से तरलता को बिना किसी ज़मानत (जैसे सरकारी प्रतिभूतियां) के अवशोषित करने की अनुमति देता है। यही इसे रिवर्स रेपो रेट से अलग करता है।",
  },
  {
    question_en: "For what duration does the RBI use the Bank Rate to lend to commercial banks?",
    question_hi: "बैंक दर (Bank Rate) का प्रयोग RBI द्वारा वाणिज्यिक बैंकों को किस अवधि के लिए ऋण देने में होता है?",
    options_en: ["Short term (max 14 days)", "90 days", "For Long Term without collateral"],
    options_hi: ["अल्पकाल (अधिकतम 14 दिन)", "90 दिन", "दीर्घकाल (Long Term) के लिए बिना ज़मानत के"],
    correct_option_index: 2,
    explanation_en: "The Bank Rate is the rate at which the RBI lends money to commercial banks for a long term, and it does not require any collateral. It is a tool for monetary control.",
    explanation_hi: "बैंक दर वह दर है जिस पर RBI वाणिज्यिक बैंकों को लंबी अवधि के लिए पैसा उधार देता है, और इसके लिए किसी ज़मानत की आवश्यकता नहीं होती है। यह मौद्रिक नियंत्रण का एक उपकरण है।",
  },
  {
    question_en: "Under Direct Action (a qualitative tool), what action can the RBI take against commercial banks?",
    question_hi: "प्रत्यक्ष कार्यवाही (Direct Action) के तहत RBI वाणिज्यिक बैंकों पर क्या कार्यवाही कर सकता है?",
    options_en: ["Only apply moral pressure.", "Set credit limits.", "Impose a penalty or cancel the license."],
    options_hi: ["केवल नैतिक दबाव डालना।", "ऋण सीमा निर्धारित करना।", "पेनल्टी लगाना या लाइसेंस रद्द करना।"],
    correct_option_index: 2,
    explanation_en: "Direct Action is a severe step where the RBI can impose penalties, restrict operations, or even cancel the banking license of a bank that does not comply with its directives.",
    explanation_hi: "प्रत्यक्ष कार्यवाही एक गंभीर कदम है, जहाँ RBI किसी बैंक द्वारा उसके निर्देशों का पालन न करने पर जुर्माना लगा सकता है, परिचालन को प्रतिबंधित कर सकता है, या उसका बैंकिंग लाइसेंस भी रद्द कर सकता है।",
  },
  {
    question_en: "In Marginal Requirement, how does the value of the collateral property relate to the loan sanctioned?",
    question_hi: "सींमात आवश्यकता (Marginal Requirement) में जमानत संपत्ति का मूल्य स्वीकृत ऋण से कैसा होता है?",
    options_en: ["Equal", "Less", "More"],
    options_hi: ["बराबर", "कम", "अधिक"],
    correct_option_index: 2,
    explanation_en: "Marginal Requirement is the difference between the market value of the collateral (e.g., ₹100) and the loan amount sanctioned (e.g., ₹80). The value of the collateral is always more than the loan.",
    explanation_hi: "सीमांत आवश्यकता, जमानत संपत्ति के बाजार मूल्य (जैसे ₹100) और स्वीकृत ऋण राशि (जैसे ₹80) के बीच का अंतर है। जमानत का मूल्य हमेशा ऋण से अधिक होता है।",
  },
  {
    question_en: "What does IBL (Inter Banking Liabilities) mean?",
    question_hi: "IBL (Inter Banking Liabilities) का क्या अर्थ है?",
    options_en: ["Inter-Governmental Liabilities", "Inter-Banking Liabilities", "Net Demand and Time Liabilities"],
    options_hi: ["अंतर-सरकारी देनदारियाँ", "अंतर-बैंकिंग देनदारियाँ", "शुद्ध मांग और समय देनदारियाँ"],
    correct_option_index: 1,
    explanation_en: "IBL stands for Inter-Banking Liabilities, which refers to the liabilities or debts that one bank owes to another bank.",
    explanation_hi: "IBL का अर्थ है अंतर-बैंकिंग देनदारियाँ (Inter-Banking Liabilities), जो उन देनदारियों या ऋणों को संदर्भित करता है जो एक बैंक का दूसरे बैंक पर बकाया होता है।",
  },
  {
    question_en: "During which RBI Governor's tenure did the first phase of nationalization of commercial banks (1969) occur?",
    question_hi: "वाणिज्यिक बैंकों के राष्ट्रीयकरण का पहला चरण (1969) किस RBI गवर्नर के कार्यकाल में हुआ था?",
    options_en: ["C.D. Deshmukh", "I.G. Patel", "Laxmikant Jha (L.K. Jha)"],
    options_hi: ["सी.डी. देशमुख", "आई.जी. पटेल", "लक्ष्मीकांत झा (Laxmikant Jha)"],
    correct_option_index: 2,
    explanation_en: "The first phase of nationalization, where 14 major commercial banks were nationalized, occurred on July 19, 1969. Laxmikant Jha (L.K. Jha) was the Governor of the RBI at that time (1967-1970).",
    explanation_hi: "राष्ट्रीयकरण का पहला चरण, जिसमें 14 प्रमुख वाणिज्यिक बैंकों का राष्ट्रीयकरण किया गया, 19 जुलाई 1969 को हुआ। उस समय लक्ष्मीकांत झा (L.K. Jha) RBI के गवर्नर थे (1967-1970)।",
  },
  {
    question_en: "When is a bank called a Nationalised Bank?",
    question_hi: "किसी बैंक को राष्ट्रीयकृत बैंक (Nationalised Bank) कब कहा जाता है?",
    options_en: ["When the Government of India holds 49% stake.", "When it only makes a profit.", "When the Government of India's stake is 51% or more."],
    options_hi: ["जब उसकी 49% हिस्सेदारी भारत सरकार के पास हो।", "जब वह केवल लाभ कमाता हो।", "जब भारत सरकार की हिस्सेदारी 51% या उससे अधिक हो।"],
    correct_option_index: 2,
    explanation_en: "A bank is considered nationalized (or a Public Sector Bank) when the majority stake, i.e., 51% or more of its total share capital, is held by the Government of India.",
    explanation_hi: "एक बैंक को राष्ट्रीयकृत (या सार्वजनिक क्षेत्र का बैंक) तब माना जाता है जब अधिकांश हिस्सेदारी, यानी उसकी कुल शेयर पूंजी का 51% या अधिक, भारत सरकार के पास होती है।",
  },
  {
    question_en: "When and where was the Bank of Baroda (BOB) established?",
    question_hi: "बैंक ऑफ बड़ौदा (BOB) की स्थापना कब और कहाँ हुई थी?",
    options_en: ["1894, New Delhi", "1906, Mumbai", "1908, Baroda"],
    options_hi: ["1894, नई दिल्ली", "1906, मुंबई", "1908, बड़ोदरा"],
    correct_option_index: 2,
    explanation_en: "Bank of Baroda was established by Maharaja Sayajirao Gaekwad III on July 20, 1908, in the city of Baroda (now Vadodara), Gujarat.",
    explanation_hi: "बैंक ऑफ बड़ौदा की स्थापना महाराजा सयाजीराव गायकवाड़ III द्वारा 20 जुलाई 1908 को गुजरात के बड़ौदा (अब वडोदरा) शहर में की गई थी।",
  },
  {
    question_en: "In which year was the Indian Overseas Bank (IOB) established?",
    question_hi: "इंडियन ओवरसीज बैंक (Indian Overseas Bank - IOB) की स्थापना किस वर्ष हुई थी?",
    options_en: ["1907", "1925", "1937"],
    options_hi: ["1907", "1925", "1937"],
    correct_option_index: 2,
    explanation_en: "The Indian Overseas Bank (IOB) was founded on February 10, 1937, by M. Ct. M. Chidambaram Chettyar.",
    explanation_hi: "इंडियन ओवरसीज बैंक (IOB) की स्थापना 10 फरवरी 1937 को एम. सीटी. एम. चिदंबरम चेट्टियार द्वारा की गई थी।",
  },
  {
    question_en: "When and where was the Union Bank of India established?",
    question_hi: "यूनियन बैंक ऑफ इंडिया (Union Bank of India) की स्थापना कब और कहाँ हुई थी?",
    options_en: ["1906, Mumbai", "1919, Mumbai", "1943, Calcutta"],
    options_hi: ["1906, मुंबई", "1919, मुंबई", "1943, कलकत्ता"],
    correct_option_index: 1,
    explanation_en: "Union Bank of India was established on November 11, 1919, in Mumbai, and its head office was inaugurated by Mahatma Gandhi.",
    explanation_hi: "यूनियन बैंक ऑफ इंडिया की स्थापना 11 नवंबर 1919 को मुंबई में हुई थी और इसके प्रधान कार्यालय का उद्घाटन महात्मा गांधी ने किया था।",
  },
  {
    question_en: "After the merger, Allahabad Bank was merged with which bank?",
    question_hi: "विलय के बाद इलाहाबाद बैंक को किस बैंक के साथ मिला दिया गया था?",
    options_en: ["Canara Bank", "Bank of Baroda", "Indian Bank"],
    options_hi: ["केनरा बैंक", "बैंक ऑफ बड़ौदा", "इंडियन बैंक"],
    correct_option_index: 2,
    explanation_en: "As part of the bank consolidation plan, Allahabad Bank was merged with Indian Bank, effective from April 1, 2020.",
    explanation_hi: "बैंक समेकन योजना के हिस्से के रूप में, इलाहाबाद बैंक का 1 अप्रैल 2020 से इंडियन बैंक में विलय कर दिया गया।",
  },
  {
    question_en: "On which date was NABARD (National Bank for Agriculture and Rural Development) established?",
    question_hi: "NABARD (नेशनल बैंक फॉर एग्रीकल्चर एंड रूरल डेवलपमेंट) की स्थापना किस तिथि को हुई?",
    options_en: ["1 January 1982", "9 July 1988", "2 April 1990"],
    options_hi: ["1 जनवरी 1982", "9 जुलाई 1988", "2 अप्रैल 1990"],
    correct_option_index: 0,
    explanation_en: "NABARD was established on 12 July 1982. Among the given options, (A) is the closest as it has the correct year (1982). Option (B) is the date for NHB, and (C) is for SIDBI.",
    explanation_hi: "नाबार्ड की स्थापना 12 जुलाई 1982 को हुई थी। दिए गए विकल्पों में, (A) 1982 को सही वर्ष के रूप में निकटतम है। विकल्प (B) एनएचबी की स्थापना तिथि है, और (C) सिडबी की स्थापना तिथि है।",
  },
  {
    question_en: "Where is the headquarters of SIDBI (Small Industries Development Bank of India) located?",
    question_hi: "SIDBI (स्मॉल इंडस्ट्रीज डेवलपमेंट बैंक ऑफ इंडिया) का मुख्यालय कहाँ स्थित है?",
    options_en: ["Mumbai", "New Delhi", "Lucknow"],
    options_hi: ["मुंबई", "नई दिल्ली", "लखनऊ"],
    correct_option_index: 2,
    explanation_en: "The headquarters of SIDBI is located in Lucknow, Uttar Pradesh. It was established on April 2, 1990.",
    explanation_hi: "सिडबी (SIDBI) का मुख्यालय लखनऊ, उत्तर प्रदेश में स्थित है। इसकी स्थापना 2 अप्रैल 1990 को हुई थी।",
  },
  {
    question_en: "In which year was the RRB Act (for the establishment of Regional Rural Banks) implemented?",
    question_hi: "RRB (क्षेत्रीय ग्रामीण बैंक) की स्थापना के लिए RRB Act किस वर्ष लागू हुआ?",
    options_en: ["1975", "1976", "1977"],
    options_hi: ["1975", "1976", "1977"],
    correct_option_index: 1,
    explanation_en: "RRBs were first established on October 2, 1975, through an ordinance. This ordinance was later replaced by the Regional Rural Banks Act, 1976.",
    explanation_hi: "RRB की स्थापना पहली बार 2 अक्टूबर 1975 को एक अध्यादेश के माध्यम से की गई थी। इस अध्यादेश को बाद में क्षेत्रीय ग्रामीण बैंक अधिनियम, 1976 द्वारा प्रतिस्थापित किया गया।",
  },
  {
    question_en: "What was the name of India's first RRB (Regional Rural Bank)?",
    question_hi: "भारत के पहले RRB (क्षेत्रीय ग्रामीण बैंक) का नाम क्या था?",
    options_en: ["Andhra Grameen Bank", "Bengal Grameen Bank", "Prathama Grameen Bank"],
    options_hi: ["आंध्र ग्रामीण बैंक", "बंगाल ग्रामीण बैंक", "प्रथमा ग्रामीण बैंक"],
    correct_option_index: 2,
    explanation_en: "The first RRB, 'Prathama Grameen Bank', was established on October 2, 1975, in Moradabad, Uttar Pradesh. It was sponsored by Syndicate Bank.",
    explanation_hi: "पहले RRB, 'प्रथमा ग्रामीण बैंक' की स्थापना 2 अक्टूबर 1975 को उत्तर प्रदेश के मुरादाबाद में की गई थी। इसे सिंडिकेट बैंक द्वारा प्रायोजित किया गया था।",
  },
  {
    question_en: "What was the main objective of the First Five-Year Plan (1951-1956)?",
    question_hi: "पहली पंचवर्षीय योजना (1951-1956) का मुख्य उद्देश्य क्या था?",
    options_en: ["Development of heavy industries", "Balanced development of the economy", "Poverty removal (Gareebi Hatao)"],
    options_hi: ["भारी उद्योगों का विकास", "अर्थव्यवस्था का संतुलित विकास", "गरीबी हटाओ"],
    correct_option_index: 1,
    explanation_en: "The main focus of the First Five-Year Plan was on agriculture, irrigation, and power projects to achieve balanced economic development, especially in the primary sector.",
    explanation_hi: "पहली पंचवर्षीय योजना का मुख्य फोकस कृषि, सिंचाई और बिजली परियोजनाओं पर था ताकि विशेष रूप से प्राथमिक क्षेत्र में, संतुलित आर्थिक विकास प्राप्त किया जा सके।",
  },
  {
    question_en: "During which Five-Year Plan was the Industrial Policy 1956 introduced?",
    question_hi: "औद्योगिक नीति 1956 किस पंचवर्षीय योजना के दौरान आई?",
    options_en: ["First Five-Year Plan", "Second Five-Year Plan", "Third Five-Year Plan"],
    options_hi: ["पहली पंचवर्षीय योजना", "दूसरी पंचवर्षीय योजना", "तीसरी पंचवर्षीय योजना"],
    correct_option_index: 1,
    explanation_en: "The Industrial Policy Resolution of 1956 was introduced during the Second Five-Year Plan (1956-1961), which focused heavily on industrialization (Mahalanobis Model).",
    explanation_hi: "औद्योगिक नीति संकल्प 1956 को दूसरी पंचवर्षीय योजना (1956-1961) के दौरान पेश किया गया था, जिसने औद्योगीकरण (महालनोबिस मॉडल) पर भारी ध्यान केंद्रित किया था।",
  },
  {
    question_en: "What was the achievement (growth) rate of the Third Five-Year Plan (1961-1966)?",
    question_hi: "तीसरी पंचवर्षीय योजना (1961-1966) की प्राप्ति (Achievement) दर क्या थी?",
    options_en: ["5.6%", "3.6%", "2.8%"],
    options_hi: ["5.6%", "3.6%", "2.8%"],
    correct_option_index: 2,
    explanation_en: "The Third Five-Year Plan was a major failure, achieving a growth rate of only 2.8% against a target of 5.6%. This was due to wars (Sino-Indian War 1962, Indo-Pak War 1965) and a severe drought.",
    explanation_hi: "तीसरी पंचवर्षीय योजना एक बड़ी विफलता थी, जिसने 5.6% के लक्ष्य के मुकाबले केवल 2.8% की वृद्धि दर हासिल की। यह युद्धों (चीन-भारत युद्ध 1962, भारत-पाक युद्ध 1965) और एक गंभीर सूखे के कारण था।",
  },
  {
    question_en: "During which plan was ISRO (Indian Space Research Organisation) established?",
    question_hi: "ISRO (भारतीय अंतरिक्ष अनुसंधान संगठन) की स्थापना किस योजना के दौरान हुई थी?",
    options_en: ["Third Five-Year Plan", "Fourth Five-Year Plan (1969-74)", "Fifth Five-Year Plan"],
    options_hi: ["तीसरी पंचवर्षीय योजना", "चौथी पंचवर्षीय योजना (1969-74)", "पांचवीं पंचवर्षीय योजना"],
    correct_option_index: 1,
    explanation_en: "ISRO was established on August 15, 1969. This date falls within the period of the Fourth Five-Year Plan (1969-1974).",
    explanation_hi: "ISRO की स्थापना 15 अगस्त 1969 को हुई थी। यह तिथि चौथी पंचवर्षीय योजना (1969-1974) की अवधि के अंतर्गत आती है।",
  },
  {
    question_en: "During which plan was the Family Planning Programme (FPP) started?",
    question_hi: "परिवार नियोजन कार्यक्रम (Family Planning Programme - FPP) किस योजना के दौरान शुरू हुआ?",
    options_en: ["Plan Holiday", "Fourth Five-Year Plan", "Fifth Five-Year Plan"],
    options_hi: ["योजना अवकाश", "चौथी पंचवर्षीय योजना", "पांचवीं पंचवर्षीय योजना"],
    correct_option_index: 1,
    explanation_en: "Although India was the first country to launch a national family planning program in 1952, it was given a high priority and integrated into the Fourth Five-Year Plan (1969-74).",
    explanation_hi: "यद्यपि भारत 1952 में एक राष्ट्रीय परिवार नियोजन कार्यक्रम शुरू करने वाला पहला देश था, लेकिन इसे चौथी पंचवर्षीय योजना (1969-74) के दौरान उच्च प्राथमिकता दी गई और एकीकृत किया गया।",
  },
  {
    question_en: "The Fifth Five-Year Plan (1974-78) was based on which model?",
    question_hi: "पाँचवीं पंचवर्षीय योजना (1974-78) किस मॉडल पर आधारित थी?",
    options_en: ["Harrod-Domar Model", "Mahalanobis Model", "D.P. Dhar Model"],
    options_hi: ["हैरोड-डोमर मॉडल", "महालनोबिस मॉडल", "डी.पी. धर मॉडल"],
    correct_option_index: 2,
    explanation_en: "The Fifth Five-Year Plan was drafted and launched by D.P. Dhar. This plan focused on 'Gareebi Hatao' (Poverty Removal) and 'Attainment of Self-Reliance'.",
    explanation_hi: "पांचवीं पंचवर्षीय योजना का मसौदा डी.पी. धर द्वारा तैयार और लॉन्च किया गया था। इस योजना ने 'गरीबी हटाओ' और 'आत्मनिर्भरता की प्राप्ति' पर ध्यान केंद्रित किया।",
  },
  {
    question_en: "During which Five-Year Plan were EXIM Bank (Jan 1, 1982) and NABARD (July 12, 1982) established?",
    question_hi: "EXIM Bank (1 जनवरी 1982) और NABARD (12 जुलाई 1982) की स्थापना किस पंचवर्षीय योजना के दौरान हुई?",
    options_en: ["Fifth Five-Year Plan", "Rolling Plan", "Sixth Five-Year Plan (1980-85)"],
    options_hi: ["पांचवीं पंचवर्षीय योजना", "रोलिंग प्लान", "छठी पंचवर्षीय योजना (1980-85)"],
    correct_option_index: 2,
    explanation_en: "Both the EXIM Bank and NABARD were established in 1982, which falls during the period of the Sixth Five-Year Plan (1980-1985).",
    explanation_hi: "EXIM बैंक और NABARD दोनों की स्थापना 1982 में हुई थी, जो छठी पंचवर्षीय योजना (1980-1985) की अवधि के दौरान आती है।",
  },
  {
    question_en: "During which plan was the NHB (National Housing Bank) established (July 9, 1988)?",
    question_hi: "NHB (नेशनल हाउसिंग बैंक) की स्थापना (9 जुलाई 1988) किस योजना के दौरान हुई?",
    options_en: ["Sixth Five-Year Plan", "Seventh Five-Year Plan (1985-90)", "Eighth Five-Year Plan"],
    options_hi: ["छठी पंचवर्षीय योजना", "सातवीं पंचवर्षीय योजना (1985-90)", "आठवीं पंचवर्षीय योजना"],
    correct_option_index: 1,
    explanation_en: "The National Housing Bank (NHB) was established on July 9, 1988. This date falls within the period of the Seventh Five-Year Plan (1985-1990).",
    explanation_hi: "नेशनल हाउसिंग बैंक (NHB) की स्थापना 9 जुलाई 1988 को हुई थी। यह तिथि सातवीं पंचवर्षीय योजना (1985-1990) की अवधि के अंतर्गत आती है।",
  },
  {
    question_en: "What was the reason for adopting Annual Plans in 1990-92?",
    question_hi: "1990-92 में वार्षिक योजनाएँ अपनाने का कारण क्या था?",
    options_en: ["Balance of Payments crisis and fall in foreign exchange reserves.", "Nationalization of banks in 1980.", "Gareebi Hatao program."],
    options_hi: ["भुगतान संतुलन की समस्या और विदेशी मुद्रा भंडार में कमी।", "1980 में बैंकों का राष्ट्रीयकरण।", "गरीबी हटाओ कार्यक्रम।"],
    correct_option_index: 0,
    explanation_en: "The Eighth Five-Year Plan was postponed due to political instability and a severe Balance of Payments (BOP) crisis. Annual Plans were implemented for 1990-91 and 1991-92, which also saw the introduction of NEP 1991.",
    explanation_hi: "राजनीतिक अस्थिरता और गंभीर भुगतान संतुलन (BOP) संकट के कारण आठवीं पंचवर्षीय योजना को स्थगित कर दिया गया था। 1990-91 और 1991-92 के लिए वार्षिक योजनाएँ लागू की गईं, जिसमें NEP 1991 की शुरुआत भी हुई।",
  },
  {
    question_en: "What was the achievement (growth) target of the Eighth Five-Year Plan (1992-97)?",
    question_hi: "आठवीं पंचवर्षीय योजना (1992-97) का प्राप्ति (Achievement) लक्ष्य क्या था?",
    options_en: ["5.6%", "6.5%", "6.8%"],
    options_hi: ["5.6%", "6.5%", "6.8%"],
    correct_option_index: 2,
    explanation_en: "The Eighth Five-Year Plan (1992-97) was highly successful. Against a target growth rate of 5.6%, it achieved an actual growth rate of 6.8%.",
    explanation_hi: "आठवीं पंचवर्षीय योजना (1992-97) अत्यधिक सफल रही। 5.6% की लक्षित वृद्धि दर के मुकाबले, इसने 6.8% की वास्तविक वृद्धि दर हासिल की।",
  },
  {
    question_en: "In which year was the KCC (Kisan Credit Card) scheme launched?",
    question_hi: "KCC (Kisan Credit Card) योजना किस वर्ष लॉन्च हुई?",
    options_en: ["1995", "March 1998", "1999"],
    options_hi: ["1995", "मार्च 1998", "1999"],
    correct_option_index: 1,
    explanation_en: "The Kisan Credit Card (KCC) scheme was introduced in August 1998 (often cited as part of the 1998-99 budget, announced earlier). Among the options, March 1998 is the closest and most plausible.",
    explanation_hi: "किसान क्रेडिट कार्ड (KCC) योजना अगस्त 1998 में शुरू की गई थी (अक्सर 1998-99 के बजट के हिस्से के रूप में उद्धृत, जिसकी घोषणा पहले की गई थी)। दिए गए विकल्पों में, मार्च 1998 सबसे निकटतम और प्रशंसनीय है।",
  },
  {
    question_en: "In which year was the NREGIA (NREGA) scheme implemented?",
    question_hi: "NREGIA (NREGA) योजना किस वर्ष लागू हुई थी?",
    options_en: ["2004", "2006", "2009"],
    options_hi: ["2004", "2006", "2009"],
    correct_option_index: 1,
    explanation_en: "The National Rural Employment Guarantee Act (NREGA) was passed in 2005 and the scheme was launched on February 2, 2006. It was renamed MGNREGA in 2009.",
    explanation_hi: "राष्ट्रीय ग्रामीण रोजगार गारंटी अधिनियम (NREGA) 2005 में पारित किया गया था और यह योजना 2 फरवरी 2006 को शुरू की गई थी। 2009 में इसका नाम बदलकर MGNREGA कर दिया गया।",
  },
  {
    question_en: "During which plan was the RTE (Right to Education) Act (2009) implemented?",
    question_hi: "RTE (शिक्षा का अधिकार) अधिनियम (2009) किस योजना के दौरान लागू हुआ था?",
    options_en: ["10th Plan", "11th Plan (2007-2012)", "12th Plan"],
    options_hi: ["10वीं योजना", "11वीं योजना (2007-2012)", "12वीं योजना"],
    correct_option_index: 1,
    explanation_en: "The Right to Education (RTE) Act was passed in August 2009. This date falls within the period of the Eleventh Five-Year Plan (2007-2012). The Act came into force on April 1, 2010.",
    explanation_hi: "शिक्षा का अधिकार (RTE) अधिनियम अगस्त 2009 में पारित किया गया था। यह तिथि ग्यारहवीं पंचवर्षीय योजना (2007-2012) की अवधि के अंतर्गत आती है। यह अधिनियम 1 अप्रैल 2010 को लागू हुआ।",
  },
  {
    question_en: "During which plan was the PM Jan Dhan Yojana (2014) launched?",
    question_hi: "PM जनधन योजना (2014) किस योजना के दौरान शुरू हुई थी?",
    options_en: ["11th Plan", "12th Five-Year Plan (2012-17)", "10th Plan"],
    options_hi: ["11वीं योजना", "12वीं पंचवर्षीय योजना (2012-17)", "10वीं योजना"],
    correct_option_index: 1,
    explanation_en: "The Pradhan Mantri Jan Dhan Yojana (PMJDY) was launched on August 28, 2014. This date falls within the period of the Twelfth Five-Year Plan (2012-2017).",
    explanation_hi: "प्रधानमंत्री जन धन योजना (PMJDY) 28 अगस्त 2014 को शुरू की गई थी। यह तिथि बारहवीं पंचवर्षीय योजना (2012-2017) की अवधि के अंतर्गत आती है।",
  },
  {
    question_en: "What is another name for the Product Method of calculating national income?",
    question_hi: "राष्ट्रीय आय की गणना में उत्पाद विधि (Product Method) का दूसरा नाम क्या है?",
    options_en: ["Expenditure Method", "Factor Income Method", "Value Added Method"],
    options_hi: ["व्यय विधि", "कारक आय विधि", "मूल्य वर्धन विधि (Value Added Method)"],
    correct_option_index: 2,
    explanation_en: "The Product Method is also called the Value Added Method (or Net Output Method). It calculates national income by summing up the value added by all firms in the economy.",
    explanation_hi: "उत्पाद विधि को मूल्य वर्धन विधि (या शुद्ध उत्पादन विधि) भी कहा जाता है। यह अर्थव्यवस्था में सभी फर्मों द्वारा जोड़े गए मूल्य को जोड़कर राष्ट्रीय आय की गणना करता है।",
  },
  {
    question_en: "In the calculation of Real GDP, data from which year is used?",
    question_hi: "वास्तविक जीडीपी (Real GDP) की गणना में किस वर्ष के आंकड़े प्रयोग होते हैं?",
    options_en: ["Current financial year", "Base Year (2011-12)", "Previous financial year"],
    options_hi: ["चालू वित्तीय वर्ष", "आधार वर्ष (Base Year) 2011-12", "पिछला वित्तीय वर्ष"],
    correct_option_index: 1,
    explanation_en: "Real GDP is calculated using the prices of a 'Base Year' to remove the effect of inflation. India's current base year is 2011-12. Nominal GDP uses current year prices.",
    explanation_hi: "वास्तविक जीडीपी की गणना मुद्रास्फीति के प्रभाव को दूर करने के लिए 'आधार वर्ष' की कीमतों का उपयोग करके की जाती है। भारत का वर्तमान आधार वर्ष 2011-12 है। नाममात्र जीडीपी चालू वर्ष की कीमतों का उपयोग करता है।",
  },
  {
    question_en: "What is added to GDP in the calculation of Gross National Product (GNP)?",
    question_hi: "सकल राष्ट्रीय उत्पाद (GNP) की गणना में GDP में क्या जोड़ा जाता है?",
    options_en: ["Depreciation", "Subsidies", "Net Factor Income from Abroad"],
    options_hi: ["मूल्य ह्रास (Depreciation)", "सब्सिडी", "विदेशों से प्राप्त शुद्ध कारक आय"],
    correct_option_index: 2,
    explanation_en: "GNP = GDP + Net Factor Income from Abroad (NFIA). NFIA is the income earned by residents from abroad minus the income paid to non-residents.",
    explanation_hi: "GNP = GDP + विदेशों से प्राप्त शुद्ध कारक आय (NFIA)। NFIA विदेशों से निवासियों द्वारा अर्जित आय में से अनिवासियों को भुगतान की गई आय को घटाकर प्राप्त होती है।",
  },
  {
    question_en: "What is the formula for national income by Expenditure Method?",
    question_hi: "व्यय विधि (Expenditure Method) द्वारा राष्ट्रीय आय का सूत्र क्या है?",
    options_en: ["C + G + I", "C + G + I + M - X", "C + G + I + X - M"],
    options_hi: ["C + G + I", "C + G + I + M - X", "C + G + I + X - M"],
    correct_option_index: 2,
    explanation_en: "The formula is Y = C + G + I + (X - M), where C=Consumption, G=Government Spending, I=Investment, X=Exports, and M=Imports. (X-M) is Net Exports.",
    explanation_hi: "सूत्र है Y = C + G + I + (X - M), जहाँ C=उपभोग, G=सरकारी व्यय, I=निवेश, X=निर्यात, और M=आयात है। (X-M) शुद्ध निर्यात है।",
  },
  {
    question_en: "Which of the following items falls under Transfer Payments?",
    question_hi: "निम्नलिखित में से कौन सी मद हस्तांतरण भुगतान (Transfer Payments) के अंतर्गत आती है?",
    options_en: ["Interest receipt", "Profit", "Pensions, unemployment allowance, lottery"],
    options_hi: ["ब्याज की प्राप्ति", "लाभ", "पेंशन, बेरोजगारी भत्ता, लॉटरी"],
    correct_option_index: 2,
    explanation_en: "Transfer payments are payments for which no goods or services are received in return (e.g., pensions, subsidies, allowances). Interest and profit are factor incomes.",
    explanation_hi: "हस्तांतरण भुगतान वे भुगतान हैं जिनके बदले में कोई वस्तु या सेवा प्राप्त नहीं होती (जैसे, पेंशन, सब्सिडी, भत्ते)। ब्याज और लाभ कारक आय हैं।",
  },
  {
    question_en: "When was the NSO (National Statistical Office) established?",
    question_hi: "NSO (राष्ट्रीय सांख्यिकी कार्यालय) की स्थापना कब हुई थी?",
    options_en: ["1950", "2005", "23 May 2019"],
    options_hi: ["1950", "2005", "23 मई 2019"],
    correct_option_index: 2,
    explanation_en: "The NSO was formed by the merger of the National Sample Survey Office (NSSO) and the Central Statistics Office (CSO) by an order dated 23 May 2019.",
    explanation_hi: "NSO का गठन 23 मई 2019 के एक आदेश द्वारा राष्ट्रीय नमूना सर्वेक्षण कार्यालय (NSSO) और केंद्रीय सांख्यिकी कार्यालय (CSO) के विलय से हुआ था।",
  },
  {
    question_en: "The word 'Budget' is derived from the French word 'Bougette', which means?",
    question_hi: "बजट शब्द फ्रांसीसी शब्द 'बुगेट' से बना है, जिसका अर्थ क्या है?",
    options_en: ["Financial Statement", "Source of Income", "Leather Bag"],
    options_hi: ["वित्तीय विवरण", "आय का स्रोत", "चमड़े का थैला (Leather Bag)"],
    correct_option_index: 2,
    explanation_en: "The term 'Budget' originates from the old French word 'Bougette', which means a small leather bag or wallet, used to carry financial papers.",
    explanation_hi: "बजट शब्द की उत्पत्ति पुराने फ्रांसीसी शब्द 'बुगेट' से हुई है, जिसका अर्थ है एक छोटा चमड़े का थैला या बटुआ, जिसका उपयोग वित्तीय कागजात ले जाने के लिए किया जाता था।",
  },
  {
    question_en: "Which article of the Constitution mentions the Annual Financial Statement for the Central Government?",
    question_hi: "केंद्र सरकार के लिए वार्षिक वित्तीय विवरण (Annual Financial Statement) का उल्लेख संविधान के किस अनुच्छेद में है?",
    options_en: ["Article 280", "Article 202", "Article 112"],
    options_hi: ["अनुच्छेद 280", "अनुच्छेद 202", "अनुच्छेद 112"],
    correct_option_index: 2,
    explanation_en: "Article 112 of the Indian Constitution mandates the Central Government to present an 'Annual Financial Statement' (the Budget) to the Parliament. Article 202 is for State Budgets.",
    explanation_hi: "भारतीय संविधान का अनुच्छेद 112 केंद्र सरकार को संसद में 'वार्षिक वित्तीय विवरण' (बजट) प्रस्तुत करने का आदेश देता है। अनुच्छेद 202 राज्य के बजट के लिए है।",
  },
  {
    question_en: "Government income that neither reduces assets nor increases liability is called?",
    question_hi: "सरकार की वह आय जिससे न संपत्ति कम हो और न कर्ज (Liability) बढ़े, क्या कहलाती है?",
    options_en: ["Capital Income", "Revenue Income", "Net Income"],
    options_hi: ["पूंजीगत आय", "राजस्व आय", "शुद्ध आय"],
    correct_option_index: 1,
    explanation_en: "Revenue Income (Revenue Receipts), like taxes and non-tax revenue (fees, fines), is regular income that does not create any liability or reduce any asset.",
    explanation_hi: "राजस्व आय (राजस्व प्राप्तियां), जैसे कर और गैर-कर राजस्व (शुल्क, जुर्माना), नियमित आय है जो कोई देनदारी नहीं बनाती या किसी संपत्ति को कम नहीं करती है।",
  },
  {
    question_en: "Which of the following items is an example of Capital Expenditure?",
    question_hi: "निम्नलिखित में से कौन सा मद पूंजीगत व्यय (Capital Expenditure) का उदाहरण है?",
    options_en: ["Salaries, Pensions", "Interest Payments", "Subsidies"],
    options_hi: ["वेतन, पेंशन", "ब्याज की अदायगी", "सब्सिडी"],
    correct_option_index: 1,
    explanation_en: "This question seems flawed, as Salaries, Pensions, Interest Payments, and Subsidies are all examples of Revenue Expenditure. An example of Capital Expenditure would be 'Construction of Roads' or 'Purchase of Machinery'. However, among the given, 'Interest Payments' are a liability payment, but are classified as Revenue Expenditure.",
    explanation_hi: "यह प्रश्न त्रुटिपूर्ण प्रतीत होता है, क्योंकि वेतन, पेंशन, ब्याज की अदायगी, और सब्सिडी सभी राजस्व व्यय के उदाहरण हैं। पूंजीगत व्यय का एक उदाहरण 'सड़कों का निर्माण' या 'मशीनरी की खरीद' होगा। हालाँकि, दिए गए विकल्पों में, 'ब्याज की अदायगी' एक देनदारी भुगतान है, लेकिन इसे राजस्व व्यय के रूप में वर्गीकृत किया गया है।",
  },
  {
    question_en: "When does a Budget Deficit situation arise?",
    question_hi: "बजट घाटा (Budget Deficit) की स्थिति कब उत्पन्न होती है?",
    options_en: ["When Total Income = Total Expenditure.", "When Total Expenditure > Total Income.", "When Total Income > Total Expenditure."],
    options_hi: ["जब कुल आय = कुल व्यय हो।", "जब कुल व्यय > कुल आय हो।", "जब कुल आय > कुल व्यय हो।"],
    correct_option_index: 1,
    explanation_en: "A budget deficit occurs when the government's total expenditure (both revenue and capital) exceeds its total income (both revenue and capital) in a financial year.",
    explanation_hi: "बजट घाटा तब होता है जब एक वित्तीय वर्ष में सरकार का कुल व्यय (राजस्व और पूंजीगत दोनों) उसकी कुल आय (राजस्व और पूंजीगत दोनों) से अधिक हो जाता है।",
  },
  {
    question_en: "What is the formula for Primary Deficit?",
    question_hi: "प्राथमिक घाटा (Primary Deficit) का सूत्र क्या है?",
    options_en: ["Revenue Deficit - Interest Payments", "Fiscal Deficit - Interest Payments (FD - IP)", "Total Expenditure - Total Income"],
    options_hi: ["राजस्व घाटा - ब्याज भुगतान", "राजकोषीय घाटा - ब्याज भुगतान (FD - IP)", "कुल व्यय - कुल आय"],
    correct_option_index: 1,
    explanation_en: "Primary Deficit is calculated by subtracting the interest payments (on previous borrowings) from the current year's Fiscal Deficit. (PD = FD - IP)",
    explanation_hi: "प्राथमिक घाटे की गणना चालू वर्ष के राजकोषीय घाटे में से (पिछले उधारों पर) ब्याज भुगतान को घटाकर की जाती है। (PD = FD - IP)",
  },
  {
    question_en: "Who regulates the Money Market?",
    question_hi: "मुद्रा बाजार (Money Market) किसके द्वारा विनियमित (Regulated) होता है?",
    options_en: ["SEBI", "Ministry of Finance", "RBI"],
    options_hi: ["SEBI", "वित्त मंत्रालय", "RBI"],
    correct_option_index: 2,
    explanation_en: "The Money Market, which deals with short-term funds (less than one year), is regulated by the Reserve Bank of India (RBI).",
    explanation_hi: "मुद्रा बाजार, जो अल्पकालिक धन (एक वर्ष से कम) से संबंधित है, भारतीय रिजर्व बैंक (RBI) द्वारा विनियमित होता है।",
  },
  {
    question_en: "Who regulates the Capital Market?",
    question_hi: "पूंजी बाजार (Capital Market) का विनियमन किसके द्वारा किया जाता है?",
    options_en: ["RBI", "Ministry of Finance", "SEBI"],
    options_hi: ["RBI", "वित्त मंत्रालय", "SEBI"],
    correct_option_index: 2,
    explanation_en: "The Capital Market, which deals with long-term funds (more than one year), including stocks and bonds, is regulated by the Securities and Exchange Board of India (SEBI).",
    explanation_hi: "पूंजी बाजार, जो स्टॉक और बॉन्ड सहित दीर्घकालिक धन (एक वर्ष से अधिक) से संबंधित है, भारतीय प्रतिभूति और विनिमय बोर्ड (SEBI) द्वारा विनियमित होता है।",
  },
  {
    question_en: "When is an FPO (Follow-on Public Offer) issued?",
    question_hi: "FPO (Follow-on Public Offer) कब जारी होता है?",
    options_en: ["When issuing shares for the first time.", "When issuing additional shares after the initial shares, to raise extra finance.", "Only for selling government securities."],
    options_hi: ["पहली बार शेयर जारी करने पर।", "अतिरिक्त वित्त संग्रहण के उद्देश्य से पहले से जारी शेयरों के अतिरिक्त शेयर जारी करने पर।", "केवल सरकारी प्रतिभूतियां बेचने पर।"],
    correct_option_index: 1,
    explanation_en: "An FPO is issued by a company that is already listed on a stock exchange to issue additional shares to the public, usually to raise more capital. The first-time issue is an IPO.",
    explanation_hi: "FPO एक ऐसी कंपनी द्वारा जारी किया जाता है जो पहले से ही स्टॉक एक्सचेंज में सूचीबद्ध है, ताकि जनता को अतिरिक्त शेयर जारी किए जा सकें, आमतौर पर अधिक पूंजी जुटाने के लिए। पहली बार जारी करने को IPO कहते हैं।",
  },
  {
    question_en: "What is a Demat Account used for?",
    question_hi: "Demat Account का उपयोग किस लिए किया जाता है?",
    options_en: ["Only for currency transactions.", "For buying and selling shares (in electronic form).", "For taking loans from RBI."],
    options_hi: ["केवल मुद्रा के लेन-देन के लिए।", "शेयरों की खरीद-बिक्री के लिए (इलेक्ट्रॉनिक रूप में)।", "RBI से ऋण लेने के लिए।"],
    correct_option_index: 1,
    explanation_en: "A Demat (Dematerialized) Account is used to hold shares, bonds, and other securities in electronic form, facilitating their trade (buying and selling) on the stock market.",
    explanation_hi: "डीमैट (डिमटेरियलाइज्ड) खाते का उपयोग शेयरों, बॉन्ड और अन्य प्रतिभूतियों को इलेक्ट्रॉनिक रूप में रखने के लिए किया जाता है, जिससे शेयर बाजार में उनका व्यापार (खरीद-बिक्री) सुविधाजनक हो जाता है।",
  },
  {
    question_en: "On which date did SEBI get statutory (legal) status?",
    question_hi: "SEBI को किस तिथि को सांविधिक (Statutory) दर्जा मिला था?",
    options_en: ["12 April 1988", "30 January 1992", "1986"],
    options_hi: ["12 अप्रैल 1988", "30 जनवरी 1992", "1986"],
    correct_option_index: 1,
    explanation_en: "SEBI was established on 12 April 1988 as a non-statutory body. It was given statutory powers on 30 January 1992 through the SEBI Act, 1992.",
    explanation_hi: "SEBI की स्थापना 12 अप्रैल 1988 को एक गैर-सांविधिक निकाय के रूप में हुई थी। इसे 30 जनवरी 1992 को SEBI अधिनियम, 1992 के माध्यम से सांविधिक शक्तियां दी गईं।",
  },
  {
    question_en: "When was the BSE (Bombay Stock Exchange) established?",
    question_hi: "BSE (बॉम्बे स्टॉक एक्सचेंज) की स्थापना कब हुई थी?",
    options_en: ["1992", "1906", "1875"],
    options_hi: ["1992", "1906", "1875"],
    correct_option_index: 2,
    explanation_en: "The BSE, formerly known as The Native Share & Stock Brokers' Association, was established in 1875. It is Asia's oldest stock exchange.",
    explanation_hi: "BSE, जिसे पहले 'द नेटिव शेयर एंड स्टॉक ब्रोकर्स एसोसिएशन' के नाम से जाना जाता था, की स्थापना 1875 में हुई थी। यह एशिया का सबसे पुराना स्टॉक एक्सचेंज है।",
  },
  {
    question_en: "When did the President sign the 101st Constitution Amendment Act (GST)?",
    question_hi: "101वाँ संविधान संशोधन अधिनियम (GST) पर राष्ट्रपति के हस्ताक्षर कब हुए?",
    options_en: ["3 August 2016", "8 September 2016", "1 July 2017"],
    options_hi: ["3 अगस्त 2016", "8 सितंबर 2016", "1 जुलाई 2017"],
    correct_option_index: 1,
    explanation_en: "The 101st Constitution Amendment Act, 2016, received the assent (signature) of the President of India on 8 September 2016. GST was implemented on 1 July 2017.",
    explanation_hi: "101वें संविधान संशोधन अधिनियम, 2016 को 8 सितंबर 2016 को भारत के राष्ट्रपति की सहमति (हस्ताक्षर) प्राप्त हुई। GST 1 जुलाई 2017 को लागू किया गया था।",
  },
  {
    question_en: "How many total members are there in the GST Council?",
    question_hi: "GST परिषद (GST Council) में कुल कितने सदस्य होते हैं?",
    options_en: ["25", "30", "33"],
    options_hi: ["25", "30", "33"],
    correct_option_index: 2,
    explanation_en: "The GST Council consists of 33 members: 2 members from the Centre (Union Finance Minister and Union Minister of State for Finance) and 31 members from States/UTs (Finance Ministers or nominated ministers).",
    explanation_hi: "GST परिषद में 33 सदस्य होते हैं: 2 सदस्य केंद्र से (केंद्रीय वित्त मंत्री और केंद्रीय वित्त राज्य मंत्री) और 31 सदस्य राज्यों/केंद्रशासित प्रदेशों से (वित्त मंत्री या नामित मंत्री)।",
  },
  {
    question_en: "Which of the following items is included among the items kept out of the GST purview?",
    question_hi: "GST के दायरे से बाहर रखी गई वस्तुओं में निम्नलिखित में से कौन शामिल है?",
    options_en: ["Aviation Fuel (ATF)", "Stamp Duty", "Real Estate"],
    options_hi: ["एयरोप्लेन का ईंधन (Aviation Fuel)", "स्टांप शुल्क", "रियल एस्टेट"],
    correct_option_index: 0,
    explanation_en: "Five petroleum products (Crude Oil, Petrol, Diesel, Natural Gas, and ATF) are currently outside the GST. Stamp Duty and Real Estate (sale of land/buildings) are also outside GST.",
    explanation_hi: "पांच पेट्रोलियम उत्पाद (कच्चा तेल, पेट्रोल, डीजल, प्राकृतिक गैस और ATF) वर्तमान में GST से बाहर हैं। स्टांप शुल्क और रियल एस्टेट (भूमि/भवन की बिक्री) भी GST से बाहर हैं। (नोट: प्रश्न के सभी विकल्प GST से बाहर हैं, लेकिन ATF मुख्य 5 वस्तुओं में से एक है)",
  },
  {
    question_en: "Which model has India adopted for GST?",
    question_hi: "भारत ने GST के लिए किस मॉडल को अपनाया है?",
    options_en: ["Dual GST system", "French Model", "Canadian Model"],
    options_hi: ["दोहरी GST प्रणाली", "फ्रेंच मॉडल", "कैनेडियन मॉडल"],
    correct_option_index: 2,
    explanation_en: "India has adopted a Dual GST model, which is based on the Canadian model. In this system, both the Centre (CGST) and the States (SGST) levy tax on the same base.",
    explanation_hi: "भारत ने दोहरी GST मॉडल को अपनाया है, जो कैनेडियन मॉडल पर आधारित है। इस प्रणाली में, केंद्र (CGST) और राज्य (SGST) दोनों एक ही आधार पर कर लगाते हैं।",
  },
  {
    question_en: "Who was the last Chairman of the Planning Commission?",
    question_hi: "योजना आयोग (Planning Commission) के अंतिम अध्यक्ष कौन थे?",
    options_en: ["Gulzari Lal Nanda", "Montek Singh Ahluwalia", "Narendra Modi (Ex-officio Chairman)"],
    options_hi: ["गुलजारी लाल नंदा", "मॉन्टेक सिंह अहलूवालिया", "नरेंद्र मोदी (पदेन अध्यक्ष)"],
    correct_option_index: 2,
    explanation_en: "The Prime Minister is the ex-officio (by virtue of office) Chairman of the Planning Commission. Narendra Modi was the last Chairman before it was dissolved and replaced by NITI Aayog in 2015.",
    explanation_hi: "प्रधानमंत्री योजना आयोग का पदेन (कार्यालय के आधार पर) अध्यक्ष होता है। 2015 में इसे भंग करने और नीति आयोग द्वारा प्रतिस्थापित किए जाने से पहले नरेंद्र मोदी इसके अंतिम अध्यक्ष थे।",
  },
  {
    question_en: "Who was the first Deputy Chairman of the Planning Commission?",
    question_hi: "योजना आयोग के पहले उपाध्यक्ष कौन थे?",
    options_en: ["P.C. Mahalanobis", "Gulzari Lal Nanda", "Jawaharlal Nehru"],
    options_hi: ["पी.सी. महालनोबिस", "गुलजारी लाल नंदा", "जवाहर लाल नेहरू"],
    correct_option_index: 1,
    explanation_en: "The first Deputy Chairman of the Planning Commission (established in 1950) was Gulzari Lal Nanda. Jawaharlal Nehru was the first Chairman.",
    explanation_hi: "योजना आयोग (1950 में स्थापित) के पहले उपाध्यक्ष गुलजारी लाल नंदा थे। जवाहर लाल नेहरू पहले अध्यक्ष थे।",
  },
  {
    question_en: "Who is the Chairman of the 16th Finance Commission?",
    question_hi: "16वें वित्त आयोग के अध्यक्ष कौन हैं?",
    options_en: ["N.K. Singh", "Y.V. Reddy", "Arvind Panagariya"],
    options_hi: ["एन.के. सिंह", "वाई.वी. रेड्डी", "अरविंद पनगड़िया"],
    correct_option_index: 2,
    explanation_en: "Dr. Arvind Panagariya, former Vice-Chairman of NITI Aayog, has been appointed as the Chairman of the 16th Finance Commission. N.K. Singh was the Chairman of the 15th FC.",
    explanation_hi: "नीति आयोग के पूर्व उपाध्यक्ष डॉ. अरविंद पनगड़िया को 16वें वित्त आयोग का अध्यक्ष नियुक्त किया गया है। एन.के. सिंह 15वें वित्त आयोग के अध्यक्ष थे।",
  },
  {
    question_en: "What is the main function of the Finance Commission (Article 280)?",
    question_hi: "वित्त आयोग (Article 280) का मुख्य कार्य क्या है?",
    options_en: ["To determine monetary policy.", "To evaluate Five-Year Plans.", "To distribute taxes between the Centre and the States."],
    options_hi: ["मौद्रिक नीति निर्धारित करना।", "पंचवर्षीय योजनाओं का मूल्यांकन करना।", "केंद्र और राज्यों के बीच करों (Taxes) का बंटवारा करना।"],
    correct_option_index: 2,
    explanation_en: "The primary function of the Finance Commission, constituted under Article 280, is to recommend the distribution of the net proceeds of taxes between the Union and the States.",
    explanation_hi: "अनुच्छेद 280 के तहत गठित वित्त आयोग का प्राथमिक कार्य संघ और राज्यों के बीच करों की शुद्ध आय के वितरण की सिफारिश करना है।",
  },
  {
    question_en: "On which date was the New Economic Policy (NEP) 1991 implemented?",
    question_hi: "नई आर्थिक नीति (NEP) 1991 किस तिथि को लागू हुई?",
    options_en: ["15 August 1995", "1 January 2015", "24 July 1991"],
    options_hi: ["15 अगस्त 1995", "1 जनवरी 2015", "24 जुलाई 1991"],
    correct_option_index: 2,
    explanation_en: "The New Economic Policy, which introduced LPG (Liberalisation, Privatisation, Globalisation), was announced on 24 July 1991 by the then Finance Minister, Dr. Manmohan Singh.",
    explanation_hi: "नई आर्थिक नीति, जिसने LPG (उदारीकरण, निजीकरण, वैश्वीकरण) की शुरुआत की, की घोषणा 24 जुलाई 1991 को तत्कालीन वित्त मंत्री डॉ. मनमोहन सिंह द्वारा की गई थी।",
  },
  {
    question_en: "Which action was taken under Liberalisation?",
    question_hi: "उदारीकरण (Liberalisation) के तहत कौन सी कार्रवाई की गई?",
    options_en: ["Government intervention was increased.", "Abolition of the licensing system.", "Disinvestment of PSUs."],
    options_hi: ["सरकारी हस्तक्षेप बढ़ाया गया।", "लाइसेंसिंग प्रणाली को समाप्त करना।", "PSU का विनिवेश करना।"],
    correct_option_index: 1,
    explanation_en: "Liberalisation involved removing government restrictions and barriers, most notably abolishing the 'License Raj' (industrial licensing system) for most industries.",
    explanation_hi: "उदारीकरण में सरकारी प्रतिबंधों और बाधाओं को हटाना शामिल था, विशेष रूप से अधिकांश उद्योगों के लिए 'लाइसेंस राज' (औद्योगिक लाइसेंसिंग प्रणाली) को समाप्त करना।",
  },
  {
    question_en: "Which action was taken under Privatization?",
    question_hi: "निजीकरण (Privatization) के तहत कौन सी कार्रवाई की गई?",
    options_en: ["Increasing foreign trade.", "Reducing government intervention.", "Simplifying rules."],
    options_hi: ["विदेशी व्यापार बढ़ाना।", "सरकारी हस्तक्षेप कम करना।", "नियमों को सरल करना।"],
    correct_option_index: 1,
    explanation_en: "Privatization refers to the transfer of ownership, management, and control of public sector enterprises (PSUs) to the private sector, thereby reducing government intervention/control.",
    explanation_hi: "निजीकरण का तात्पर्य सार्वजनिक क्षेत्र के उद्यमों (PSUs) के स्वामित्व, प्रबंधन और नियंत्रण को निजी क्षेत्र को हस्तांतरित करना है, जिससे सरकारी हस्तक्षेप/नियंत्रण कम हो जाता है।",
  },
  {
    question_en: "When does a Trade Surplus occur?",
    question_hi: "व्यापार अधिशेष (Trade Surplus) कब होता है?",
    options_en: ["When Imports > Exports.", "When Imports = Exports.", "When Exports > Imports (e.g., 120 > 100)."],
    options_hi: ["जब आयात > निर्यात हो।", "जब आयात = निर्यात हो।", "जब निर्यात > आयात हो (जैसे 120 > 100)।"],
    correct_option_index: 2,
    explanation_en: "A trade surplus (or positive balance of trade) occurs when the value of a country's exports exceeds the value of its imports.",
    explanation_hi: "व्यापार अधिशेष (या सकारात्मक व्यापार संतुलन) तब होता है जब किसी देश के निर्यात का मूल्य उसके आयात के मूल्य से अधिक हो जाता है।",
  },
  {
    question_en: "What is the main objective of a Socialistic Economy?",
    question_hi: "समाजवादी अर्थव्यवस्था (Socialistic Economy) का मुख्य उद्देश्य क्या होता है?",
    options_en: ["To earn maximum profit.", "Public Welfare.", "Control of market forces."],
    options_hi: ["अधिकतम लाभ कमाना।", "जन कल्याण (Public Welfare)।", "बाज़ार शक्तियों का नियंत्रण।"],
    correct_option_index: 1,
    explanation_en: "In a socialistic economy, the means of production are state-owned, and the primary objective is to ensure the collective good and public welfare, rather than private profit.",
    explanation_hi: "एक समाजवादी अर्थव्यवस्था में, उत्पादन के साधन राज्य के स्वामित्व में होते हैं, और प्राथमिक उद्देश्य निजी लाभ के बजाय सामूहिक भलाई और जन कल्याण सुनिश्चित करना होता है।",
  },
  {
    question_en: "What is another name for a Capitalistic Economy?",
    question_hi: "पूंजीवादी अर्थव्यवस्था (Capitalistic Economy) का अन्य नाम क्या है?",
    options_en: ["State-based economy", "Centralized economy", "Market-Based Economy"],
    options_hi: ["राज्य आधारित अर्थव्यवस्था", "केंद्रीकृत अर्थव्यवस्था", "बाज़ार आधारित अर्थव्यवस्था (Market-Based Eco.)"],
    correct_option_index: 2,
    explanation_en: "A capitalistic economy is driven by private ownership and the forces of supply and demand. Therefore, it is also known as a Market-Based Economy or Free-Market Economy.",
    explanation_hi: "एक पूंजीवादी अर्थव्यवस्था निजी स्वामित्व और आपूर्ति और मांग की शक्तियों द्वारा संचालित होती है। इसलिए, इसे बाजार-आधारित अर्थव्यवस्था या मुक्त-बाजार अर्थव्यवस्था के रूप में भी जाना जाता है।",
  },
  {
    question_en: "According to the notes, which country is not an example of a Developed Economy?",
    question_hi: "नोट्स के अनुसार, कौन सा देश विकसित अर्थव्यवस्था (Developed Economy) का उदाहरण नहीं है?",
    options_en: ["USA", "Japan", "France"],
    options_hi: ["USA", "जापान", "फ्रांस"],
    correct_option_index: 2,
    explanation_en: "This question may be flawed. Typically, the USA, Japan, and France are all considered developed, high-income economies. An example of a developing economy would be India or Brazil.",
    explanation_hi: "यह प्रश्न त्रुटिपूर्ण हो सकता है। आमतौर पर, USA, जापान और फ्रांस तीनों को विकसित, उच्च-आय वाली अर्थव्यवस्था माना जाता है। एक विकासशील अर्थव्यवस्था का उदाहरण भारत या ब्राजील होगा।",
  },
  {
    question_en: "In a perfectly competitive market, when does a firm earn normal profit in the short run?",
    question_hi: "पूर्ण प्रतिस्पर्धा बाजार में एक फर्म को अल्पकाल में सामान्य लाभ कब प्राप्त होता है?",
    options_en: ["When AR > SAC", "When Average Revenue (AR) equals Average Cost (SAC) (AR = SAC)", "When AR < SAC"],
    options_hi: ["जब AR > SAC हो।", "जब औसत आय (AR) औसत लागत (SAC) के बराबर हो (AR = SAC)।", "जब AR < SAC हो।"],
    correct_option_index: 1,
    explanation_en: "Normal profit is a situation where a firm makes just enough revenue to cover its total costs (both explicit and implicit). This occurs when Average Revenue (Price) equals Short-run Average Cost (AR = SAC).",
    explanation_hi: "सामान्य लाभ वह स्थिति है जहाँ एक फर्म अपनी कुल लागत (स्पष्ट और निहित दोनों) को कवर करने के लिए पर्याप्त राजस्व कमाती है। यह तब होता है जब औसत आय (कीमत) अल्पकालीन औसत लागत (AR = SAC) के बराबर होती है।",
  },
  {
    question_en: "When and where was the NDDB (National Dairy Development Board) started?",
    question_hi: "NDDB (नेशनल डेयरी डेवलपमेंट बोर्ड) की शुरुआत कब और कहाँ हुई थी?",
    options_en: ["1970, Anand", "1965, Karnal (Haryana)", "1980, Mumbai"],
    options_hi: ["1970, आणंद", "1965, करनाल (हरियाणा)", "1980, मुंबई"],
    correct_option_index: 0,
    explanation_en: "NDDB was founded in 1965 in Anand, Gujarat. In 1970, it launched 'Operation Flood'. Option (A) has the correct location (Anand) and the year of Operation Flood (1970), while (B) has the correct founding year (1965) but the wrong location (Karnal, which is the HQ of NDRI).",
    explanation_hi: "NDDB की स्थापना 1965 में आणंद, गुजरात में हुई थी। 1970 में इसके द्वारा 'ऑपरेशन फ्लड' शुरू किया गया था। विकल्प (A) में सही स्थान (आणंद) और ऑपरेशन फ्लड का वर्ष (1970) है, जबकि (B) में सही स्थापना वर्ष (1965) लेकिन गलत स्थान (करनाल, जो NDRI का मुख्यालय है) है।",
  },
  {
    question_en: "What is the Badami Revolution related to?",
    question_hi: "बादामी क्रांति (Badami Revolution) का संबंध किससे है?",
    options_en: ["Okra (Ladyfinger) production", "Fruits/Honey", "Milk production"],
    options_hi: ["भिंडी उत्पादन", "फल/शहद", "दूध उत्पादन"],
    correct_option_index: 1,
    explanation_en: "This question is flawed. The Badami Revolution is related to 'Spice Production'. The Parbhani Revolution is for 'Okra', the Golden Revolution is for 'Fruits/Honey', and the White Revolution is for 'Milk'.",
    explanation_hi: "यह प्रश्न त्रुटिपूर्ण है। बादामी क्रांति का संबंध 'मसाला उत्पादन' (Spice Production) से है। 'भिंडी' के लिए परभणी क्रांति, 'फल/शहद' के लिए सुनहरी क्रांति, और 'दूध' के लिए श्वेत क्रांति है।",
  }
];

export default test5Questions;
