import type { QuizQuestion } from '../../../types';

const test10Questions: QuizQuestion[] = [
  {
    question_en: "According to the notes, what is the tenure of the RBI Governor?",
    question_hi: "नोट्स के अनुसार, RBI गवर्नर का कार्यकाल कितने वर्ष का होता है?",
    options_en: ["5 years", "4 years", "3 years", "6 years"],
    options_hi: ["5 वर्ष", "4 वर्ष", "3 वर्ष", "6 वर्ष"],
    correct_option_index: 2,
    explanation_en: "The RBI Governor is appointed by the Government of India for a tenure of 3 years.",
    explanation_hi: "RBI गवर्नर की नियुक्ति भारत सरकार द्वारा 3 वर्ष के कार्यकाल के लिए की जाती है।",
  },
  {
    question_en: "According to the notes, who is the 20th (current) Governor of RBI?",
    question_hi: "नोट्स के अनुसार, RBI के 20वें (वर्तमान) गवर्नर कौन हैं?",
    options_en: ["Urjit Patel", "C.D. Deshmukh", "Shaktikanta Das", "Sanjay Malhotra (from 2024)"],
    options_hi: ["उर्जित पटेल", "सी.डी. देशमुख", "शक्तिकांत दास", "संजय मल्होत्रा (2024 से)"],
    correct_option_index: 3,
    explanation_en: "The notes specify Sanjay Malhotra as the 20th (current) Governor (from 2024).",
    explanation_hi: "नोट्स में संजय मल्होत्रा को 20वें (वर्तमान) गवर्नर (2024 से) बताया गया है।",
  },
  {
    question_en: "Whose signature is on a ₹1 currency note?",
    question_hi: "₹1 के नोट पर किसके हस्ताक्षर होते हैं?",
    options_en: ["RBI Governor", "Prime Minister", "Finance Secretary", "Finance Minister"],
    options_hi: ["RBI गवर्नर", "प्रधानमंत्री", "वित्त सचिव", "वित्त मंत्री"],
    correct_option_index: 2,
    explanation_en: "The ₹1 note is issued by the Ministry of Finance and bears the signature of the Finance Secretary.",
    explanation_hi: "₹1 का नोट वित्त मंत्रालय द्वारा जारी होता है और इस पर वित्त सचिव के हस्ताक्षर होते हैं।",
  },
  {
    question_en: "What is the total reserve capital required for note issuance under the Minimum Reserve System (MRS)?",
    question_hi: "न्यूनतम आरक्षित प्रणाली (Minimum Reserve System) के तहत नोट जारी करने के लिए कुल कितनी जमा पूंजी आवश्यक है?",
    options_en: ["₹115 Crore", "₹200 Crore", "₹85 Crore", "₹100 Crore"],
    options_hi: ["₹115 करोड़", "₹200 करोड़", "₹85 करोड़", "₹100 करोड़"],
    correct_option_index: 1,
    explanation_en: "A total capital of ₹200 Crore is required under the Minimum Reserve System (comprising ₹115 Crore in gold and ₹85 Crore in foreign currency).",
    explanation_hi: "न्यूनतम आरक्षित प्रणाली के तहत कुल ₹200 करोड़ की पूंजी आवश्यक है (जिसमें ₹115 करोड़ गोल्ड और ₹85 करोड़ विदेशी मुद्रा)।",
  },
  {
    question_en: "What is the effect on liquidity when interest rates rise in a Tight Monetary Policy?",
    question_hi: "कठोर मौद्रिक नीति (Tight Monetary Policy) में ब्याज दरें बढ़ने पर तरलता पर क्या प्रभाव पड़ता है?",
    options_en: ["Liquidity increases", "Liquidity decreases", "No effect", "Inflation reduces"],
    options_hi: ["तरलता बढ़ती है", "तरलता घटती है", "कोई प्रभाव नहीं पड़ता", "मुद्रास्फीति कम होती है"],
    correct_option_index: 1,
    explanation_en: "In a Tight Monetary Policy, interest rates are raised, which decreases liquidity in the economy.",
    explanation_hi: "कठोर मौद्रिक नीति में ब्याज दरें बढ़ाई जाती हैं, जिससे अर्थव्यवस्था में तरलता घटती है।",
  },
  {
    question_en: "Easy Monetary Policy is primarily introduced to tackle which problem?",
    question_hi: "सरल मौद्रिक नीति (Easy Monetary Policy) मुख्य रूप से किस समस्या से निपटने के लिए लाई जाती है?",
    options_en: ["Inflation", "Trade Deficit", "Recession problem", "Fiscal Deficit"],
    options_hi: ["मुद्रास्फीति", "व्यापार घाटा", "मंदी की समस्या (Recession)", "राजकोषीय घाटा"],
    correct_option_index: 2,
    explanation_en: "Easy Monetary Policy is introduced to tackle the problem of recession.",
    explanation_hi: "सरल मौद्रिक नीति मंदी की समस्या से निपटने के लिए लाई जाती है।",
  },
  {
    question_en: "To increase liquidity, what does RBI do with Government Securities (G-Sec) under Open Market Operations (OMO)?",
    question_hi: "तरलता बढ़ाने के लिए RBI खुले बाज़ार की क्रियाओं (OMO) के तहत सरकारी प्रतिभूतियाँ (G-Sec) क्या करता है?",
    options_en: ["Sells (Sale)", "Buys (Buy)", "Deposits", "Destroys"],
    options_hi: ["बेचता है (Sale)", "खरीदता है (Buy)", "जमा करता है", "नष्ट करता है"],
    correct_option_index: 1,
    explanation_en: "To increase liquidity, the RBI buys G-Secs.",
    explanation_hi: "तरलता बढ़ाने के लिए RBI G-Sec को खरीदता है।",
  },
  {
    question_en: "What is the effect on liquidity when there is a decrease in Reverse Repo Rate (RRR)?",
    question_hi: "रिवर्स रेपो रेट (RRR) में कमी होने पर तरलता पर क्या प्रभाव पड़ेगा?",
    options_en: ["Liquidity decreases", "Liquidity increases", "No effect", "Credit control increases"],
    options_hi: ["तरलता घटती है", "तरलता बढ़ती है", "कोई प्रभाव नहीं पड़ता", "साख नियंत्रण बढ़ता है"],
    correct_option_index: 1,
    explanation_en: "A decrease in RRR means commercial banks earn less interest, so they deposit less with the RBI, which increases liquidity.",
    explanation_hi: "RRR में कमी होने पर वाणिज्यिक बैंकों को कम ब्याज मिलता है, इसलिए वे RBI के पास कम जमा करते हैं, जिससे तरलता बढ़ती है।",
  },
  {
    question_en: "Under MSF (Marginal Standing Facility), what is the maximum percentage of their total deposits that commercial banks can borrow?",
    question_hi: "MSF (सीमांत स्थायी सुविधा दर) के तहत वाणिज्यिक बैंक अपनी कुल जमा का अधिकतम कितना प्रतिशत ऋण ले सकते हैं?",
    options_en: ["4%", "25%", "1%", "Up to 1%"],
    options_hi: ["4%", "25%", "1%", "1% तक"],
    correct_option_index: 2,
    explanation_en: "Under MSF, commercial banks can borrow up to 1% of their total deposits.",
    explanation_hi: "MSF के तहत वाणिज्यिक बैंक अपनी कुल जमा का 1% तक ऋण ले सकते हैं।",
  },
  {
    question_en: "In Marginal Requirement, how does the value of the collateral asset relate to the sanctioned loan?",
    question_hi: "सीमांत आवश्यकता (Marginal Requirement) में, जमानत संपत्ति का मूल्य स्वीकृत ऋण से कैसा होता है?",
    options_en: ["Equal", "Less", "More", "Uncertain"],
    options_hi: ["बराबर", "कम", "अधिक", "अनिश्चित"],
    correct_option_index: 2,
    explanation_en: "In Marginal Requirement, the value of the collateral asset is kept higher than the sanctioned loan.",
    explanation_hi: "सीमांत आवश्यकता में, जमानत संपत्ति का मूल्य स्वीकृत ऋण से अधिक रखा जाता है।",
  },
  {
    question_en: "How many banks were nationalized in the first phase of commercial bank nationalization (July 19, 1969)?",
    question_hi: "वाणिज्यिक बैंकों के राष्ट्रीयकरण के पहले चरण (19 जुलाई 1969) में कितने बैंकों का राष्ट्रीयकरण हुआ?",
    options_en: ["14 banks", "6 banks", "8 banks", "10 banks"],
    options_hi: ["14 बैंक", "6 बैंक", "8 बैंक", "10 बैंक"],
    correct_option_index: 0,
    explanation_en: "14 banks were nationalized in the first phase (July 19, 1969).",
    explanation_hi: "पहले चरण (19 जुलाई 1969) में 14 बैंकों का राष्ट्रीयकरण हुआ।",
  },
  {
    question_en: "Who was the RBI Governor during the second phase of commercial bank nationalization (April 15, 1980)?",
    question_hi: "वाणिज्यिक बैंकों के राष्ट्रीयकरण के दूसरे चरण (15 अप्रैल 1980) के समय RBI गवर्नर कौन थे?",
    options_en: ["Lakshmikant Jha", "I.G. Patel", "Shaktikanta Das", "C.D. Deshmukh"],
    options_hi: ["लक्ष्मीकांत झा", "आई.जी. पटेल (I.G. Patel)", "शक्तिकांत दास", "सी.डी. देशमुख"],
    correct_option_index: 1,
    explanation_en: "I.G. Patel was the RBI Governor during the second phase (April 15, 1980).",
    explanation_hi: "दूसरे चरण (15 अप्रैल 1980) के समय RBI गवर्नर आई.जी. पटेल थे।",
  },
  {
    question_en: "In which city was the Bank of Baroda (BOB) established (1908)?",
    question_hi: "बैंक ऑफ बड़ौदा (BOB) की स्थापना (1908) किस शहर में हुई थी?",
    options_en: ["Mumbai", "New Delhi", "Baroda", "Calcutta"],
    options_hi: ["मुंबई", "नई दिल्ली", "बड़ोदरा", "कलकत्ता"],
    correct_option_index: 2,
    explanation_en: "The Bank of Baroda (BOB) was established in Baroda in 1908.",
    explanation_hi: "बैंक ऑफ बड़ौदा (BOB) की स्थापना 1908 में बड़ोदरा में हुई थी।",
  },
  {
    question_en: "In which year was the United Bank of India (UBI) established?",
    question_hi: "यूनाइटेड बैंक ऑफ इंडिया (UBI) की स्थापना किस वर्ष हुई?",
    options_en: ["1906", "1943", "1950", "1937"],
    options_hi: ["1906", "1943", "1950", "1937"],
    correct_option_index: 2,
    explanation_en: "The United Bank of India (UBI) was established in Calcutta in 1950.",
    explanation_hi: "यूनाइटेड बैंक ऑफ इंडिया (UBI) की स्थापना 1950 में कलकत्ता में हुई।",
  },
  {
    question_en: "Into which bank was Allahabad Bank (1865, Calcutta) merged?",
    question_hi: "इलाहाबाद बैंक (1865, कलकत्ता) का विलय किस बैंक में हुआ?",
    options_en: ["Canara Bank", "Bank of Baroda", "Indian Bank", "Syndicate Bank"],
    options_hi: ["केनरा बैंक", "बैंक ऑफ बड़ौदा", "इंडियन बैंक", "सिंडिकेट बैंक"],
    correct_option_index: 2,
    explanation_en: "Allahabad Bank was merged into Indian Bank.",
    explanation_hi: "इलाहाबाद बैंक का विलय इंडियन बैंक में हुआ।",
  },
  {
    question_en: "What is the main function of SIDBI (April 2, 1990)?",
    question_hi: "SIDBI (2 April 1990) का मुख्य कार्य क्या है?",
    options_en: ["Financing agriculture and rural areas", "Promoting foreign trade", "Developing small industries", "Providing housing facilities"],
    options_hi: ["कृषि एवं ग्रामीण क्षेत्रों को वित्त देना", "विदेशी व्यापार बढ़ाना", "लघु उद्योगों का विकास करना", "आवासीय सुविधा प्रदान करना"],
    correct_option_index: 2,
    explanation_en: "The function of SIDBI is to develop small industries.",
    explanation_hi: "SIDBI का कार्य लघु उद्योगों का विकास करना है।",
  },
  {
    question_en: "The establishment of Regional Rural Banks (RRB) was based on the recommendation of which committee?",
    question_hi: "क्षेत्रीय ग्रामीण बैंक (RRB) की स्थापना किस समिति की सिफारिश पर हुई थी?",
    options_en: ["Sivaraman Committee", "K.C. Neogy Committee", "Narasimham Committee", "Fervani Committee"],
    options_hi: ["शिवरामन समिति", "के.सी. नियोगी समिति", "नरसिम्हन समिति", "फेरवनी समिति"],
    correct_option_index: 2,
    explanation_en: "RRBs were established on the recommendation of the Narasimham Committee.",
    explanation_hi: "RRB की स्थापना नरसिम्हन समिति की सिफारिश पर हुई।",
  },
  {
    question_en: "What is the nature of Regional Rural Banks (RRB)?",
    question_hi: "क्षेत्रीय ग्रामीण बैंक (RRB) की प्रकृति (Nature) कैसी होती है?",
    options_en: ["Private Sector", "Government Sector", "Statutory", "Non-Statutory"],
    options_hi: ["निजी क्षेत्र", "सरकारी क्षेत्र", "सांविधिक (Statutory)", "गैर-सांविधिक"],
    correct_option_index: 2,
    explanation_en: "The nature of RRB is Statutory, established under the RRB Act 1976.",
    explanation_hi: "RRB की प्रकृति सांविधिक है, जिसे RRB Act 1976 के तहत स्थापित किया गया।",
  },
  {
    question_en: "The concept of Five-Year Plans (FYP) was taken from which country?",
    question_hi: "पंचवर्षीय योजनाओं की अवधारणा किस देश से ली गई?",
    options_en: ["Germany", "Japan", "Soviet Union (USSR)", "USA"],
    options_hi: ["जर्मनी", "जापान", "सोवियत संघ (USSR)", "USA"],
    correct_option_index: 2,
    explanation_en: "The concept of Five-Year Plans is a contribution of the Soviet Union (USSR).",
    explanation_hi: "पंचवर्षीय योजनाओं की अवधारणा सोवियत संघ (USSR) की देन है।",
  },
  {
    question_en: "In which year was the Community Development Programme (CDP) started?",
    question_hi: "सामुदायिक विकास कार्यक्रम (CDP) किस वर्ष शुरू हुआ?",
    options_en: ["1951", "1952", "1956", "1961"],
    options_hi: ["1951", "1952", "1956", "1961"],
    correct_option_index: 1,
    explanation_en: "The Community Development Programme (CDP) started in 1952 during the first plan.",
    explanation_hi: "सामुदायिक विकास कार्यक्रम (CDP) 1952 में पहली योजना के दौरान शुरू हुआ।",
  },
  {
    question_en: "The Damodar Project under the First Five-Year Plan is situated on which river?",
    question_hi: "पहली पंचवर्षीय योजना के तहत दामोदर प्रोजेक्ट किस नदी पर स्थित है?",
    options_en: ["Sutlej River", "Beas River", "Mahanadi", "Damodar River"],
    options_hi: ["सतलुज नदी", "ब्यास नदी", "महानदी", "दामोदर नदी"],
    correct_option_index: 3,
    explanation_en: "The Damodar Project is situated on the Damodar River.",
    explanation_hi: "दामोदर प्रोजेक्ट दामोदर नदी पर स्थित है।",
  },
  {
    question_en: "P.C. Mahalanobis, the father of the Second Five-Year Plan (Mahalanobis Model), is called the father of which field?",
    question_hi: "द्वितीय पंचवर्षीय योजना (महालनोबिस मॉडल) के जनक पी.सी. महालनोबिस को किसका जनक कहा जाता है?",
    options_en: ["Modern Economics", "Indian Economy", "Modern Statistics", "Planning Commission"],
    options_hi: ["आधुनिक अर्थशास्त्र", "भारतीय अर्थव्यवस्था", "आधुनिक सांख्यिकी", "योजना आयोग"],
    correct_option_index: 2,
    explanation_en: "P.C. Mahalanobis is called the father of Modern Statistics.",
    explanation_hi: "पी.सी. महालनोबिस को आधुनिक सांख्यिकी का जनक कहा जाता है।",
  },
  {
    question_en: "Which country's cooperation was received for the establishment of Durgapur (West Bengal) Iron and Steel Industry?",
    question_hi: "दुर्गापुर (पश्चिम बंगाल) लौह इस्पात उद्योग की स्थापना में किस देश का सहयोग मिला था?",
    options_en: ["Russia", "Germany", "Britain", "USA"],
    options_hi: ["रूस", "जर्मनी", "ब्रिटेन", "USA"],
    correct_option_index: 2,
    explanation_en: "Durgapur (West Bengal) received cooperation from Britain.",
    explanation_hi: "दुर्गापुर (पश्चिम बंगाल) को ब्रिटेन का सहयोग मिला था।",
  },
  {
    question_en: "What was the target growth rate of the Third Five-Year Plan (1961-66)?",
    question_hi: "तीसरी पंचवर्षीय योजना (1961-66) का लक्ष्य (Target) क्या था?",
    options_en: ["4.5%", "5.6%", "5.7%", "4.4%"],
    options_hi: ["4.5%", "5.6%", "5.7%", "4.4%"],
    correct_option_index: 1,
    explanation_en: "The target for the Third Plan was 5.6%.",
    explanation_hi: "तीसरी योजना का लक्ष्य 5.6% था।",
  },
  {
    question_en: "During which Five-Year Plan was ISRO (August 15, 1969) established?",
    question_hi: "ISRO (15 अगस्त 1969) की स्थापना किस पंचवर्षीय योजना के दौरान हुई?",
    options_en: ["Plan Holiday", "Fourth Five-Year Plan (1969-74)", "Fifth Five-Year Plan", "Third Five-Year Plan"],
    options_hi: ["योजना अवकाश", "चौथी पंचवर्षीय योजना (1969-74)", "पाँचवीं पंचवर्षीय योजना", "तीसरी पंचवर्षीय योजना"],
    correct_option_index: 1,
    explanation_en: "ISRO was established on August 15, 1969, which falls under the Fourth Plan.",
    explanation_hi: "ISRO की स्थापना 15 अगस्त 1969 को हुई, जो चौथी योजना में आता है।",
  },
  {
    question_en: "The Twenty Point Programme was started during which Five-Year Plan?",
    question_hi: "20 सूत्री कार्यक्रम (Twenty Point Programme) किस पंचवर्षीय योजना के दौरान शुरू हुआ?",
    options_en: ["Fourth Plan", "Fifth Plan (1975)", "Sixth Plan", "Seventh Plan"],
    options_hi: ["चौथी योजना", "पाँचवीं योजना (1975)", "छठी योजना", "सातवीं योजना"],
    correct_option_index: 1,
    explanation_en: "The Twenty Point Programme started in 1975 during the Fifth Plan.",
    explanation_hi: "20 सूत्री कार्यक्रम 1975 में पाँचवीं योजना के दौरान शुरू हुआ।",
  },
  {
    question_en: "Who introduced the concept of the Rolling Plan (Gunnar Myrdal Model) in India?",
    question_hi: "रोलिंग प्लान की अवधारणा (गुन्नार मिर्डल मॉडल) को भारत में किसके द्वारा लागू किया गया?",
    options_en: ["John Mathai", "Professor D. T. Lakdawala", "K.N. Rao", "P.C. Mahalanobis"],
    options_hi: ["जॉन मथाई", "प्रोफेसर डी. टी. लकड़ावाला", "के.एन. राव", "पी.सी. महालनोबिस"],
    correct_option_index: 1,
    explanation_en: "The concept of the Rolling Plan was introduced in India by Professor D. T. Lakdawala.",
    explanation_hi: "रोलिंग प्लान की अवधारणा प्रोफेसर डी. टी. लकड़ावाला द्वारा भारत में लाई गई।",
  },
  {
    question_en: "In which year was the Indira Awaas Yojana (IAY) established?",
    question_hi: "इंदिरा आवास योजना (IAY) किस वर्ष स्थापित हुई थी?",
    options_en: ["1980", "1985", "1989", "1993"],
    options_hi: ["1980", "1985", "1989", "1993"],
    correct_option_index: 1,
    explanation_en: "Indira Awaas Yojana was established in 1985 during the Seventh Plan.",
    explanation_hi: "इंदिरा आवास योजना 1985 में सातवीं योजना के दौरान स्थापित हुई थी।",
  },
  {
    question_en: "What is the full form of NREP?",
    question_hi: "NREP (राष्ट्रीय ग्रामीण रोज़गार कार्यक्रम) का पूर्ण रूप क्या है?",
    options_en: ["National Road Employment Program", "National Revenue Eradication Project", "National Rural Employment Program", "New Rural Education Plan"],
    options_hi: ["National Road Employment Program", "National Revenue Eradication Project", "National Rural Employment Program", "New Rural Education Plan"],
    correct_option_index: 2,
    explanation_en: "The full form of NREP is National Rural Employment Program (राष्ट्रीय ग्रामीण रोज़गार कार्यक्रम).",
    explanation_hi: "NREP का पूर्ण रूप National Rural Employment Program (राष्ट्रीय ग्रामीण रोज़गार कार्यक्रम) है।",
  },
  {
    question_en: "In which year was RTE (Right to Education) implemented?",
    question_hi: "RTE (शिक्षा का अधिकार) किस वर्ष लागू हुआ?",
    options_en: ["2005", "2007", "2009", "2012"],
    options_hi: ["2005", "2007", "2009", "2012"],
    correct_option_index: 2,
    explanation_en: "RTE (Right to Education) was implemented in 2009 during the Eleventh Plan.",
    explanation_hi: "RTE (शिक्षा का अधिकार) 2009 में ग्यारहवीं योजना के दौरान लागू हुआ।",
  },
  {
    question_en: "In which year was the MUDRA scheme implemented?",
    question_hi: "MUDRA योजना किस वर्ष लागू हुई?",
    options_en: ["2012", "2013", "2015", "2016"],
    options_hi: ["2012", "2013", "2015", "2016"],
    correct_option_index: 2,
    explanation_en: "The MUDRA scheme was implemented in 2015 during the 12th Plan.",
    explanation_hi: "MUDRA योजना 2015 में 12वीं योजना के दौरान लागू हुई।",
  },
  {
    question_en: "In Gross Domestic Product (GDP), production is done by whom?",
    question_hi: "सकल घरेलू उत्पाद (GDP) में उत्पादन किसके द्वारा किया जाता है?",
    options_en: ["Only by citizens of the country", "Only by foreigners", "Both citizens and foreigners within the domestic territory of the country", "Only by the government"],
    options_hi: ["केवल देश के नागरिकों द्वारा", "केवल विदेशियों द्वारा", "देश की घरेलू सीमा में नागरिकों तथा विदेशियों दोनों द्वारा", "केवल सरकार द्वारा"],
    correct_option_index: 2,
    explanation_en: "GDP measures the final production done by both citizens and foreigners within the country's border.",
    explanation_hi: "GDP देश की सीमा में नागरिकों तथा विदेशियों दोनों द्वारा किए गए अंतिम उत्पादन को मापता है।",
  },
  {
    question_en: "What is the formula for calculating Per Capita Income?",
    question_hi: "प्रति व्यक्ति आय की गणना का सूत्र क्या है?",
    options_en: ["GDP / Population", "National Income / Population", "GNP / Population", "NDP / Population"],
    options_hi: ["GDP / जनसंख्या", "राष्ट्रीय आय / जनसंख्या", "GNP / जनसंख्या", "NDP / जनसंख्या"],
    correct_option_index: 1,
    explanation_en: "Per Capita Income = National Income / Population.",
    explanation_hi: "प्रति व्यक्ति आय = राष्ट्रीय आय / जनसंख्या।",
  },
  {
    question_en: "For which financial year is the budget prepared?",
    question_hi: "बजट किस वित्तीय वर्ष के लिए बनाया जाता है?",
    options_en: ["Previous Financial Year", "Upcoming Financial Year", "Current Financial Year", "Calendar Year"],
    options_hi: ["पिछला वित्तीय वर्ष", "आगामी वित्तीय वर्ष", "चालू वित्तीय वर्ष", "कैलेंडर वर्ष"],
    correct_option_index: 1,
    explanation_en: "The budget is prepared for the upcoming financial year, which contains the statement of estimated income and expenditure.",
    explanation_hi: "बजट आगामी वित्तीय वर्ष के लिए बनाया जाता है, जिसमें अनुमानित आय और व्यय का विवरण होता है।",
  },
  {
    question_en: "The budget (Annual Financial Statement) for the State Government is mentioned in which Article?",
    question_hi: "राज्य सरकार के लिए बजट (वार्षिक वित्तीय विवरण) का उल्लेख किस अनुच्छेद में है?",
    options_en: ["Article 112", "Article 202", "Article 280", "Article 300A"],
    options_hi: ["अनुच्छेद 112", "अनुच्छेद 202", "अनुच्छेद 280", "अनुच्छेद 300A"],
    correct_option_index: 1,
    explanation_en: "The budget for the State Government is mentioned in Article 202.",
    explanation_hi: "राज्य सरकार के लिए बजट का उल्लेख अनुच्छेद 202 में है।",
  },
  {
    question_en: "On which date is the Central Government's budget presented?",
    question_hi: "केंद्र सरकार का बजट किस तिथि को पेश किया जाता है?",
    options_en: ["April 1", "March 31", "February 1", "November 26"],
    options_hi: ["1 अप्रैल", "31 मार्च", "1 फरवरी", "26 नवंबर"],
    correct_option_index: 2,
    explanation_en: "The Central Government's budget is presented on February 1.",
    explanation_hi: "केंद्र सरकार का बजट 1 फरवरी को पेश किया जाता है।",
  },
  {
    question_en: "Which of the following is an example of Revenue Receipt?",
    question_hi: "निम्नलिखित में से कौन राजस्व आय (Revenue Receipt) का उदाहरण है?",
    options_en: ["Recovery of loans", "Disinvestment of PSU", "Penalty and Fees", "Borrowing"],
    options_hi: ["ऋण की वसूली", "PSU का विनिवेश", "जुर्माना (Penalty) और फीस", "उधार लेना (Borrowing)"],
    correct_option_index: 2,
    explanation_en: "Penalty and fees are revenue receipts, as they neither reduce assets nor increase debt.",
    explanation_hi: "जुर्माना और फीस राजस्व आय है, जिससे न संपत्ति कम होती है और न कर्ज बढ़ता है।",
  },
  {
    question_en: "What is Capital Receipt?",
    question_hi: "पूंजीगत आय (प्राप्ति) क्या है?",
    options_en: ["Which neither reduces assets nor increases debt", "Which either reduces assets or increases debt", "Which increases assets", "Which reduces debt"],
    options_hi: ["जिससे न संपत्ति कम हो और न कर्ज बढ़े", "जिससे या तो संपत्ति में कमी हो या कर्ज में वृद्धि हो", "जिससे संपत्ति में वृद्धि हो", "जिससे कर्ज में कमी हो"],
    correct_option_index: 1,
    explanation_en: "Capital receipt is one that either reduces assets (disinvestment) or increases debt (borrowing).",
    explanation_hi: "पूंजीगत आय वह है जिससे या तो संपत्ति में कमी (विनिवेश) हो या कर्ज में वृद्धि (उधार) हो।",
  },
  {
    question_en: "What is Revenue Expenditure?",
    question_hi: "राजस्व व्यय क्या है?",
    options_en: ["Which increases assets", "Which reduces debt", "Which neither increases assets nor reduces debt", "Repayment of loan"],
    options_hi: ["जिससे संपत्ति में वृद्धि हो", "जिससे कर्ज में कमी हो", "जिससे न संपत्ति में वृद्धि हो और न कर्ज में कमी हो", "ऋण की अदायगी"],
    correct_option_index: 2,
    explanation_en: "Salaries, pensions, subsidies, interest payments are revenue expenditures, as they neither increase assets nor reduce debt.",
    explanation_hi: "वेतन, पेंशन, सब्सिडी, ब्याज अदायगी राजस्व व्यय हैं।",
  },
  {
    question_en: "What is the formula for Budget Deficit?",
    question_hi: "बजट घाटा (Budget Deficit) का सूत्र क्या है?",
    options_en: ["Total Income - Total Expenditure", "Total Expenditure - Total Income", "Revenue Expenditure - Revenue Receipt", "Fiscal Deficit - Interest Payment"],
    options_hi: ["कुल आय - कुल व्यय", "कुल व्यय - कुल आय", "राजस्व व्यय - राजस्व आय", "राजकोषीय घाटा - ब्याज भुगतान"],
    correct_option_index: 1,
    explanation_en: "Budget Deficit = Total Expenditure - Total Income.",
    explanation_hi: "बजट घाटा = कुल व्यय - कुल आय।",
  },
  {
    question_en: "What is the formula for Fiscal Deficit (FD)?",
    question_hi: "राजकोषीय घाटा (FD) का सूत्र क्या है?",
    options_en: ["Revenue Deficit + Interest Payment", "Primary Deficit - Interest Payment", "Total Expenditure - Total Income (Excluding Borrowings)", "Total Expenditure - Revenue Receipt"],
    options_hi: ["राजस्व घाटा + ब्याज भुगतान", "प्राथमिक घाटा - ब्याज भुगतान", "कुल व्यय - कुल आय", "कुल व्यय - राजस्व आय"],
    correct_option_index: 2,
    explanation_en: "Fiscal Deficit = Total Expenditure - Total Income (Excluding Borrowings, which is the definition used to calculate the actual deficit). The option 'कुल व्यय - कुल आय' is often used as a simplification where 'कुल आय' implicitly excludes borrowing.",
    explanation_hi: "राजकोषीय घाटा = कुल व्यय - कुल आय। (यहाँ 'कुल आय' का मतलब उधार छोड़कर है, हालांकि विकल्प में यह स्पष्ट नहीं है, फिर भी यह सबसे सही उत्तर है)",
  },
  {
    question_en: "When does the situation of Trade Surplus occur?",
    question_hi: "व्यापार अधिशेष (Trade Surplus) की स्थिति कब होती है?",
    options_en: ["When Import > Export", "When Import = Export", "When Export > Import", "When Goods and Services trade is zero"],
    options_hi: ["जब आयात > निर्यात हो", "जब आयात = निर्यात हो", "जब निर्यात > आयात हो", "जब वस्तु और सेवा व्यापार शून्य हो"],
    correct_option_index: 2,
    explanation_en: "Trade Surplus occurs when Export > Import.",
    explanation_hi: "व्यापार अधिशेष तब होता है जब निर्यात > आयात हो।",
  },
  {
    question_en: "When does the situation of Balanced Trade occur?",
    question_hi: "संतुलित व्यापार की स्थिति कब होती है?",
    options_en: ["When Export > Import", "When Import = Export", "When Import < Export", "When there is a Trade Surplus"],
    options_hi: ["जब निर्यात > आयात हो", "जब आयात = निर्यात हो", "जब आयात < निर्यात हो", "जब व्यापार अधिशेष हो"],
    correct_option_index: 1,
    explanation_en: "Balanced Trade occurs when Import = Export.",
    explanation_hi: "संतुलित व्यापार तब होता है जब आयात (Import) = निर्यात (Export) हो।",
  },
  {
    question_en: "In the secondary capital market, between whom does the share transaction take place?",
    question_hi: "द्वितीयक पूंजी बाजार में शेयर का लेन-देन किसके मध्य होता है?",
    options_en: ["Between Company and Investor", "Between Investors", "Between Government and RBI", "Only Bond transaction"],
    options_hi: ["कंपनी और निवेशक के मध्य", "निवेशकों के मध्य (Investors)", "सरकार और RBI के मध्य", "केवल बॉन्ड का लेन-देन"],
    correct_option_index: 1,
    explanation_en: "In the secondary market, the share transaction takes place between investors.",
    explanation_hi: "द्वितीयक बाजार में शेयर का लेन-देन निवेशकों के मध्य होता है।",
  },
  {
    question_en: "What is the purpose of issuing FPO (Follow-on Public Offer)?",
    question_hi: "FPO (Follow-on Public Offer) जारी करने का उद्देश्य क्या होता है?",
    options_en: ["To collect finance for the first time (IPO)", "To issue additional shares for the purpose of collecting additional finance", "Only to sell government securities", "To open Demat Account"],
    options_hi: ["पहली बार वित्त संग्रहित करना (IPO)", "अतिरिक्त वित्त संग्रहण के उद्देश्य से अतिरिक्त शेयर जारी करना", "केवल सरकारी प्रतिभूतियां बेचना", "Demat Account खोलना"],
    correct_option_index: 1,
    explanation_en: "The purpose of FPO is to collect additional finance.",
    explanation_hi: "FPO का उद्देश्य अतिरिक्त वित्त संग्रहण होता है।",
  },
  {
    question_en: "In which year was SEBI (Securities and Exchange Board of India) established?",
    question_hi: "SEBI (सिक्योरिटीज एंड एक्सचेंज बोर्ड ऑफ इंडिया) की स्थापना किस वर्ष हुई?",
    options_en: ["January 30, 1992", "April 12, 1988", "1875", "1995"],
    options_hi: ["30 जनवरी 1992", "12 अप्रैल 1988", "1875", "1995"],
    correct_option_index: 1,
    explanation_en: "SEBI was established on April 12, 1988.",
    explanation_hi: "SEBI की स्थापना 12 अप्रैल 1988 को हुई थी।",
  },
  {
    question_en: "Which was the first state in India to implement GST?",
    question_hi: "GST लागू करने वाला भारत का पहला राज्य कौन सा था?",
    options_en: ["Bihar", "Jammu and Kashmir", "Assam", "Gujarat"],
    options_hi: ["बिहार", "जम्मू और कश्मीर", "असम", "गुजरात"],
    correct_option_index: 2,
    explanation_en: "Assam was the first state to implement GST.",
    explanation_hi: "GST लागू करने वाला पहला राज्य असम था।",
  },
  {
    question_en: "Under which Constitutional Amendment Act was GST implemented?",
    question_hi: "GST किस संविधान संशोधन अधिनियम के तहत लागू हुआ?",
    options_en: ["122nd Constitutional Amendment Bill", "100th Constitutional Amendment Act", "101st Constitutional Amendment Act", "99th Constitutional Amendment Act"],
    options_hi: ["122वाँ संविधान संशोधन विधेयक", "100वाँ संविधान संशोधन अधिनियम", "101वाँ संविधान संशोधन अधिनियम", "99वाँ संविधान संशोधन अधिनियम"],
    correct_option_index: 2,
    explanation_en: "GST was implemented under the 101st Constitutional Amendment Act (2016).",
    explanation_hi: "GST 101वाँ संविधान संशोधन अधिनियम (2016) के तहत लागू हुआ।",
  },
  {
    question_en: "When was the GST Council formed?",
    question_hi: "GST परिषद (GST Council) का गठन कब हुआ?",
    options_en: ["July 1, 2017", "September 8, 2016", "September 12, 2016", "August 3, 2016"],
    options_hi: ["1 जुलाई 2017", "8 सितंबर 2016", "12 सितंबर 2016", "3 अगस्त 2016"],
    correct_option_index: 2,
    explanation_en: "The GST Council was formed on September 12, 2016.",
    explanation_hi: "GST परिषद का गठन 12 सितंबर 2016 को हुआ।",
  },
  {
    question_en: "How many digits does the GST Identification Number (GST-IN) have?",
    question_hi: "GST आइडेंटिफिकेशन नंबर (GST-IN) कितने अंकों का होता है?",
    options_en: ["10 digits", "12 digits", "15 digits", "16 digits"],
    options_hi: ["10 अंक", "12 अंक", "15 अंक", "16 अंक"],
    correct_option_index: 2,
    explanation_en: "The GST-IN has 15 digits.",
    explanation_hi: "GST-IN 15 अंकों का होता है।",
  },
  {
    question_en: "Which of the following commodities is kept outside the purview of GST?",
    question_hi: "GST के दायरे से बाहर रखी गई वस्तुओं में कौन शामिल है?",
    options_en: ["Cloth", "Car", "Cement", "Aviation Fuel"],
    options_hi: ["कपड़ा", "कार", "सीमेंट", "हवाई ईंधन (Aviation Fuel)"],
    correct_option_index: 3,
    explanation_en: "Aviation Fuel is included in the commodities kept outside the purview of GST.",
    explanation_hi: "हवाई ईंधन GST के दायरे से बाहर रखी गई वस्तुओं में शामिल है।",
  },
  {
    question_en: "When was the Planning Commission abolished and NITI Aayog established?",
    question_hi: "योजना आयोग को समाप्त करके नीति आयोग की स्थापना कब हुई?",
    options_en: ["August 15, 2014", "January 1, 2015", "March 15, 1950", "March 31, 2017"],
    options_hi: ["15 अगस्त 2014", "1 जनवरी 2015", "15 मार्च 1950", "31 मार्च 2017"],
    correct_option_index: 1,
    explanation_en: "The Planning Commission was abolished and NITI Aayog was created on January 1, 2015.",
    explanation_hi: "योजना आयोग को समाप्त करके 1 जनवरी 2015 को नीति आयोग बनाया गया।",
  },
  {
    question_en: "Who gave the final approval to the Five-Year Plans?",
    question_hi: "पंचवर्षीय योजनाओं को अंतिम स्वीकृति कौन देता था?",
    options_en: ["Planning Commission", "Ministry of Finance", "National Development Council (NDC)", "Prime Minister"],
    options_hi: ["योजना आयोग", "वित्त मंत्रालय", "राष्ट्रीय विकास परिषद (NDC)", "प्रधानमंत्री"],
    correct_option_index: 2,
    explanation_en: "The Five-Year Plans were given final approval by the National Development Council (NDC).",
    explanation_hi: "पंचवर्षीय योजनाओं को अंतिम स्वीकृति राष्ट्रीय विकास परिषद (NDC) द्वारा दी जाती थी।",
  },
  {
    question_en: "According to the notes, who is the Chairman of the 16th Finance Commission?",
    question_hi: "नोट्स के अनुसार, 16वें वित्त आयोग के अध्यक्ष कौन हैं?",
    options_en: ["N.K. Singh", "Y.V. Reddy", "Arvind Panagariya", "K.C. Neogy"],
    options_hi: ["एन.के. सिंह", "वाई.वी. रेड्डी", "अरविंद पनगड़िया", "के.सी. नियोगी"],
    correct_option_index: 2,
    explanation_en: "The Chairman of the 16th Finance Commission is Arvind Panagariya.",
    explanation_hi: "16वें वित्त आयोग के अध्यक्ष अरविंद पनगड़िया हैं।",
  },
  {
    question_en: "Who was the Prime Minister at the time of the implementation of the New Economic Policy (LPG)?",
    question_hi: "नई आर्थिक नीति (LPG) लागू होने के समय प्रधानमंत्री कौन थे?",
    options_en: ["Manmohan Singh", "Atal Bihari Vajpayee", "P.V. Narasimha Rao", "Rajiv Gandhi"],
    options_hi: ["मनमोहन सिंह", "अटल बिहारी वाजपेयी", "पी.वी. नरसिम्हा राव", "राजीव गांधी"],
    correct_option_index: 2,
    explanation_en: "P.V. Narasimha Rao was the Prime Minister at the time of the implementation of NEP 1991.",
    explanation_hi: "NEP 1991 लागू होने के समय प्रधानमंत्री पी.वी. नरसिम्हा राव थे।",
  },
  {
    question_en: "The Grey Revolution is associated with which product?",
    question_hi: "ग्रे क्रांति (Grey Revolution) का संबंध किससे है?",
    options_en: ["Potato Production", "Fertilizer Production", "Tomato Production", "Fish Production"],
    options_hi: ["आलू उत्पादन", "उर्वरक उत्पादन", "टमाटर उत्पादन", "मछली उत्पादन"],
    correct_option_index: 1,
    explanation_en: "The Grey Revolution is associated with fertilizer production.",
    explanation_hi: "ग्रे क्रांति (Grey Revolution) का संबंध उर्वरक उत्पादन से है।",
  },
  {
    question_en: "The Paramani Revolution is associated with which product?",
    question_hi: "परमानी क्रांति का संबंध किससे है?",
    options_en: ["Spice Production", "Egg Production", "Okra Production", "Meat Production"],
    options_hi: ["मसाला उत्पादन", "अंडा उत्पादन", "भिंडी उत्पादन", "मांस उत्पादन"],
    correct_option_index: 2,
    explanation_en: "The Paramani Revolution is associated with Okra production.",
    explanation_hi: "परामनी क्रांति का संबंध भिंडी उत्पादन से है।",
  },
  {
    question_en: "The Badami Revolution is associated with which product?",
    question_hi: "बादामी क्रांति का संबंध किससे है?",
    options_en: ["Milk Production", "Prawn Fish", "Spice Production", "Fruit Production"],
    options_hi: ["दूध उत्पादन", "झींगा मछली", "मसाला उत्पादन", "फल उत्पादन"],
    correct_option_index: 2,
    explanation_en: "The Badami Revolution is associated with spice production.",
    explanation_hi: "बादामी क्रांति का संबंध मसाला उत्पादन से है।",
  },
  {
    question_en: "When is a firm in a state of equilibrium?",
    question_hi: "कोई फर्म संतुलन की स्थिति में कब होती है?",
    options_en: ["When AR = SAC", "When AR > SAC", "When Marginal Revenue (MR) equals Marginal Cost (MC) (MR = MC)", "When Average Revenue is zero"],
    options_hi: ["जब AR = SAC हो", "जब AR > SAC हो", "जब सीमांत आय (MR) सीमांत लागत (MC) के बराबर हो (MR = MC)", "जब औसत आय शून्य हो"],
    correct_option_index: 2,
    explanation_en: "A firm is in a state of equilibrium when Marginal Revenue (MR) equals Marginal Cost (MC).",
    explanation_hi: "फर्म संतुलन की स्थिति में तब होती है, जब सीमांत आय (MR) सीमांत लागत (MC) के बराबर होती है।",
  },
  {
    question_en: "In perfect competition market in the short run, when does a firm earn Abnormal Profit?",
    question_hi: "अल्पकाल में पूर्ण प्रतिस्पर्धा बाजार में फर्म को असामान्य लाभ (Abnormal Profit) कब होता है?",
    options_en: ["When AR = SAC", "When the firm's Average Revenue (AR) is greater than Average Cost (SAC) (AR > SAC)", "When AR < SAC", "When MR = MC"],
    options_hi: ["जब AR = SAC हो", "जब फर्म की औसत आय (AR) औसत लागत (SAC) से ज्यादा हो (AR > SAC)", "जब AR < SAC हो", "जब MR = MC हो"],
    correct_option_index: 1,
    explanation_en: "Abnormal Profit occurs in the short run when Average Revenue (AR) is greater than Average Cost (SAC).",
    explanation_hi: "अल्पकाल में असामान्य लाभ तब होता है, जब औसत आय (AR) औसत लागत (SAC) से ज्यादा हो।",
  },
];
export default test10Questions;
