import type { QuizQuestion } from '../../../types';

const test6Questions: QuizQuestion[] = [
  {
    question_en: "Which commission's recommendation led to the adoption of the Bengal Tiger and Palm Tree in the emblem of the RBI?",
    question_hi: "RBI के प्रतीक चिन्ह (Symbol) में शामिल बंगाल टाइगर और ताड़ का पेड़ किस आयोग की सिफारिश पर अपनाया गया था?",
    options_en: ["Narasimham Committee", "Hilton Young Commission", "Niyogi Committee", "Chakravarthy Committee"],
    options_hi: ["नरसिम्हन आयोग", "हिल्टन यंग कमीशन", "नियोगी समिति", "चक्रवर्ती समिति"],
    correct_option_index: 1,
    explanation_en: "The Reserve Bank of India (RBI) was established on the recommendation of the Royal Commission on Indian Currency and Finance, also known as the Hilton Young Commission (1926). The emblem was also adopted based on its recommendations.",
    explanation_hi: "भारतीय रिज़र्व बैंक (RBI) की स्थापना रॉयल कमीशन ऑन इंडियन करेंसी एंड फाइनेंस, जिसे हिल्टन यंग कमीशन (1926) के नाम से भी जाना जाता है, की सिफारिश पर की गई थी। इसके प्रतीक चिन्ह को भी इसी आयोग की सिफारिशों के आधार पर अपनाया गया था।",
  },
  {
    question_en: "Until which year did the RBI function as the central bank for Myanmar (Burma)?",
    question_hi: "RBI ने किस वर्ष तक म्यांमार (बर्मा) के केंद्रीय बैंक के रूप में कार्य किया था?",
    options_en: ["1935", "1947", "1949", "1951"],
    options_hi: ["1935", "1947 तक", "1949", "1951"],
    correct_option_index: 1,
    explanation_en: "The RBI acted as the central bank for Burma (now Myanmar) until April 1947, even after India's independence.",
    explanation_hi: "RBI ने भारत की स्वतंत्रता के बाद भी अप्रैल 1947 तक बर्मा (अब म्यांमार) के केंद्रीय बैंक के रूप में कार्य किया था।",
  },
  {
    question_en: "What is the number of Government officials (from the Ministry of Finance) on the Central Board of Directors (CBD) of the RBI?",
    question_hi: "RBI के सेंट्रल बोर्ड ऑफ डायरेक्टर्स (CBD) में सरकारी अधिकारी (जो वित्त मंत्रालय से होते हैं) की संख्या कितनी होती है?",
    options_en: ["1 member", "2 members", "4 members", "5 members"],
    options_hi: ["1 सदस्य", "2 सदस्य", "4 सदस्य", "5 सदस्य"],
    correct_option_index: 0,
    explanation_en: "The Central Board of Directors of the RBI includes one Government official, who is usually the Finance Secretary, nominated by the Central Government.",
    explanation_hi: "RBI के सेंट्रल बोर्ड ऑफ डायरेक्टर्स में केंद्र सरकार द्वारा नामित एक सरकारी अधिकारी शामिल होता है, जो आमतौर पर वित्त सचिव होता है।",
  },
  {
    question_en: "Why is Credit Control necessary?",
    question_hi: "साख नियंत्रण (Credit Control) की आवश्यकता क्यों होती है?",
    options_en: ["To stabilize only interest rates.", "To control demand and inflation.", "To increase RBI's stake.", "To increase money supply in the economy."],
    options_hi: ["केवल ब्याज दरों को स्थिर रखने के लिए।", "मांग और मुद्रास्फीति (Inflation) को नियंत्रित करने के लिए।", "RBI की हिस्सेदारी बढ़ाने के लिए।", "अर्थव्यवस्था में मुद्रा आपूर्ति बढ़ाने के लिए।"],
    correct_option_index: 1,
    explanation_en: "Credit control is primarily required to manage the amount of credit in the economy, which in turn helps in controlling aggregate demand and thus managing inflation and achieving economic stability.",
    explanation_hi: "साख नियंत्रण मुख्य रूप से अर्थव्यवस्था में ऋण की मात्रा को प्रबंधित करने के लिए आवश्यक है, जो बदले में कुल मांग को नियंत्रित करने में मदद करता है और इस प्रकार मुद्रास्फीति का प्रबंधन करने और आर्थिक स्थिरता प्राप्त करने में सहायता करता है।",
  },
  {
    question_en: "If the RBI wants to increase liquidity in the market, what should it do under Open Market Operations (OMO)?",
    question_hi: "यदि RBI बाज़ार में तरलता (Liquidity) बढ़ाना चाहता है, तो उसे खुले बाज़ार की क्रियाओं (OMO) के तहत क्या करना चाहिए?",
    options_en: ["Selling Government Securities (G-Sec).", "Buying Government Securities (G-Sec).", "Increasing the Repo Rate.", "Increasing the CRR."],
    options_hi: ["सरकारी प्रतिभूतियों (G-Sec) को बेचना।", "सरकारी प्रतिभूतियों (G-Sec) को खरीदना।", "रेपो रेट बढ़ाना।", "CRR बढ़ाना।"],
    correct_option_index: 1,
    explanation_en: "To increase liquidity, the RBI buys Government Securities from the market, injecting money into the system. This increases the banks' reserves and their capacity to lend.",
    explanation_hi: "तरलता बढ़ाने के लिए, RBI बाज़ार से सरकारी प्रतिभूतियों को खरीदता है, जिससे सिस्टम में पैसा आता है। इससे बैंकों के भंडार और ऋण देने की क्षमता में वृद्धि होती है।",
  },
  {
    question_en: "What does 'Repurchase Option' mean in relation to the Repo Rate?",
    question_hi: "Repo Rate (रेपो दर) के संबंध में 'Repurchase Option' का क्या अर्थ है?",
    options_en: ["The bank gives a loan without collateral.", "Loan provided by the RBI for a short-term period with an agreement to repurchase the securities.", "Facility for long-term loans.", "The bank's option to sell its assets."],
    options_hi: ["बैंक बिना ज़मानत के ऋण देता है।", "RBI द्वारा अल्पकालिक अवधि के लिए ऋण दिया जाना, प्रतिभूतियों को वापस खरीदने के समझौते के साथ।", "दीर्घकालिक ऋण की सुविधा।", "बैंक का अपनी संपत्ति बेचने का विकल्प।"],
    correct_option_index: 1,
    explanation_en: "Repo Rate is the rate at which the RBI lends money to commercial banks against government securities, with a 'repurchase option' i.e., an agreement that the bank will buy back the securities at a predetermined price and date.",
    explanation_hi: "रेपो दर वह दर है जिस पर RBI वाणिज्यिक बैंकों को सरकारी प्रतिभूतियों के बदले में 'पुनर्खरीद विकल्प' (Repurchase Option) के साथ पैसा उधार देता है, यानी एक समझौते के साथ कि बैंक एक पूर्व निर्धारित मूल्य और तिथि पर प्रतिभूतियों को वापस खरीद लेगा।",
  },
  {
    question_en: "For how long can commercial banks borrow a maximum under the MSF (Marginal Standing Facility) rate?",
    question_hi: "MSF (Marginal Standing Facility) दर पर वाणिज्यिक बैंक अधिकतम कितनी अवधि के लिए ऋण ले सकते हैं?",
    options_en: ["14 days", "90 days", "Overnight (One Night)", "3 days"],
    options_hi: ["14 दिन", "90 दिन", "एक रात (Overnight)", "3 दिन"],
    correct_option_index: 2,
    explanation_en: "MSF allows commercial banks to borrow funds from the RBI, primarily as a safety valve against unexpected liquidity shortfalls, for a very short period, which is 'overnight'.",
    explanation_hi: "MSF वाणिज्यिक बैंकों को RBI से धन उधार लेने की अनुमति देता है, मुख्य रूप से अप्रत्याशित तरलता की कमी के खिलाफ एक सुरक्षा वाल्व के रूप में, एक बहुत ही कम अवधि के लिए, जो कि 'एक रात' होती है।",
  },
  {
    question_en: "Under the SLR (Statutory Liquidity Ratio), what proportion of funds do banks keep safe with themselves?",
    question_hi: "SLR (सांविधिक तरलता अनुपात) के तहत बैंक किस अनुपात में धन को अपने पास सुरक्षित रखते हैं?",
    options_en: ["4.5% of NDTL", "1% of Total Deposits", "A certain percentage of NDTL", "Total Demand and Time Liabilities"],
    options_hi: ["NDTL का 4.5%", "कुल जमा का 1%", "NDTL का कुछ प्रतिशत", "कुल मांग और सावधि देनदारियां"],
    correct_option_index: 2,
    explanation_en: "SLR is the minimum percentage of deposits (NDTL - Net Demand and Time Liabilities) that a commercial bank has to maintain in the form of liquid assets (cash, gold, or other securities) with itself. The actual percentage is determined by the RBI from time to time.",
    explanation_hi: "SLR जमा (NDTL - नेट डिमांड एंड टाइम लायबिलिटीज) का न्यूनतम प्रतिशत है जिसे एक वाणिज्यिक बैंक को तरल संपत्ति (नकद, सोना, या अन्य प्रतिभूतियां) के रूप में अपने पास बनाए रखना होता है। वास्तविक प्रतिशत RBI द्वारा समय-समय पर निर्धारित किया जाता है।",
  },
  {
    question_en: "What steps can the RBI take under Direct Action (Qualitative Tool)?",
    question_hi: "प्रत्यक्ष कार्यवाही (Direct Action) के अंतर्गत RBI कौन से कदम उठा सकता है?",
    options_en: ["Only exerting pressure.", "Only setting credit limits.", "Imposing penalties or cancelling licenses.", "Issuing circulars."],
    options_hi: ["केवल दबाव डालना।", "केवल ऋण सीमा निर्धारित करना।", "पेनल्टी लगाना या लाइसेंस रद्द करना।", "परिपत्र जारी करना।"],
    correct_option_index: 2,
    explanation_en: "Direct Action is a stern step under the RBI's qualitative credit control measures, which can include imposing penalties on erring banks or, in extreme cases, revoking their license.",
    explanation_hi: "प्रत्यक्ष कार्यवाही RBI के गुणात्मक साख नियंत्रण उपायों के तहत एक सख्त कदम है, जिसमें गलती करने वाले बैंकों पर पेनल्टी लगाना या, अत्यधिक मामलों में, उनका लाइसेंस रद्द करना शामिल हो सकता है।",
  },
  {
    question_en: "What is the total number of Nationalised Banks in India (as per the notes/recent mergers)?",
    question_hi: "वर्तमान में (नोट्स के अनुसार) भारत में कुल कितने राष्ट्रीयकृत बैंक (Nationalised Banks) हैं?",
    options_en: ["21", "19", "12", "15"],
    options_hi: ["21", "19", "12", "15"],
    correct_option_index: 2,
    explanation_en: "Following the large-scale bank mergers in 2019 and 2020, the number of Public Sector Banks (often referred to as nationalized banks) in India was brought down to 12.",
    explanation_hi: "2019 और 2020 में बड़े पैमाने पर बैंक विलय के बाद, भारत में सार्वजनिक क्षेत्र के बैंकों (जिन्हें अक्सर राष्ट्रीयकृत बैंक कहा जाता है) की संख्या घटाकर 12 कर दी गई थी।",
  },
  {
    question_en: "In which year was the RBI nationalized?",
    question_hi: "RBI का राष्ट्रीयकरण किस वर्ष हुआ था?",
    options_en: ["April 1, 1935", "July 1, 1955", "January 1, 1949", "January 26, 1950"],
    options_hi: ["1 अप्रैल 1935", "1 जुलाई 1955", "1 जनवरी 1949", "26 जनवरी 1950"],
    correct_option_index: 2,
    explanation_en: "The Reserve Bank of India (RBI) was established on April 1, 1935, but it was nationalized on January 1, 1949.",
    explanation_hi: "भारतीय रिज़र्व बैंक (RBI) की स्थापना 1 अप्रैल 1935 को हुई थी, लेकिन इसका राष्ट्रीयकरण 1 जनवरी 1949 को किया गया था।",
  },
  {
    question_en: "Where was PNB (Punjab National Bank) established?",
    question_hi: "पीएनबी (पंजाब नेशनल बैंक) की स्थापना कहाँ हुई थी?",
    options_en: ["Mumbai", "Baroda", "Calcutta (Kolkata)", "Lahore"],
    options_hi: ["मुंबई", "बड़ोदरा", "कलकत्ता", "लाहौर"],
    correct_option_index: 3,
    explanation_en: "Punjab National Bank (PNB) was established in Lahore (now in Pakistan) in 1894.",
    explanation_hi: "पंजाब नेशनल बैंक (PNB) की स्थापना 1894 में लाहौर (अब पाकिस्तान में) में हुई थी।",
  },
  {
    question_en: "Where was Syndicate Bank established?",
    question_hi: "सिंडिकेट बैंक (Syndicate Bank) की स्थापना कहाँ हुई थी?",
    options_en: ["Mumbai", "Calcutta (Kolkata)", "Manipal, Karnataka", "Chennai"],
    options_hi: ["मुंबई", "कलकत्ता", "मणिपाल, कर्नाटक", "चेन्नई"],
    correct_option_index: 2,
    explanation_en: "Syndicate Bank was established in Manipal, Karnataka, in 1925.",
    explanation_hi: "सिंडिकेट बैंक की स्थापना 1925 में मणिपाल, कर्नाटक में हुई थी।",
  },
  {
    question_en: "Where was Bank of Maharashtra established?",
    question_hi: "बैंक ऑफ महाराष्ट्र (Bank of Maharashtra) की स्थापना कहाँ हुई थी?",
    options_en: ["Mumbai", "Chennai", "Pune", "Nagpur"],
    options_hi: ["मुंबई", "चेन्नई", "पुणे", "नागपुर"],
    correct_option_index: 2,
    explanation_en: "Bank of Maharashtra was established in Pune, Maharashtra, in 1935.",
    explanation_hi: "बैंक ऑफ महाराष्ट्र की स्थापना 1935 में पुणे, महाराष्ट्र में हुई थी।",
  },
  {
    question_en: "With which bank did Syndicate Bank merge?",
    question_hi: "सिंडिकेट बैंक का विलय किस बैंक के साथ हुआ?",
    options_en: ["Bank of Baroda (BOB)", "Indian Bank", "Canara Bank", "Union Bank of India"],
    options_hi: ["बैंक ऑफ बड़ौदा (BOB)", "इंडियन बैंक", "केनरा बैंक", "यूनियन बैंक ऑफ इंडिया"],
    correct_option_index: 2,
    explanation_en: "Syndicate Bank was merged with Canara Bank, effective from April 1, 2020, as part of the government's mega-merger plan.",
    explanation_hi: "सिंडिकेट बैंक का विलय सरकार की मेगा-विलय योजना के तहत 1 अप्रैल 2020 से केनरा बैंक के साथ कर दिया गया था।",
  },
  {
    question_en: "Which committee recommended the establishment of NABARD?",
    question_hi: "NABARD की स्थापना की सिफारिश किस समिति ने की थी?",
    options_en: ["Narasimham Committee", "K.C. Niyogi Committee", "Shivraman Committee", "Chakravarthy Committee"],
    options_hi: ["नरसिम्हन समिति", "के.सी. नियोगी समिति", "शिवरामन समिति", "चक्रवर्ती समिति"],
    correct_option_index: 2,
    explanation_en: "NABARD (National Bank for Agriculture and Rural Development) was established on the recommendation of the B. Sivaraman Committee (CRAFICARD) in 1982.",
    explanation_hi: "NABARD (राष्ट्रीय कृषि और ग्रामीण विकास बैंक) की स्थापना 1982 में बी. शिवरामन समिति (CRAFICARD) की सिफारिश पर की गई थी।",
  },
  {
    question_en: "What is the main objective of establishing NHB (National Housing Bank)?",
    question_hi: "NHB (नेशनल हाउसिंग बैंक) की स्थापना का मुख्य उद्देश्य क्या है?",
    options_en: ["To promote foreign trade", "Industrial development", "To promote housing facility", "To regulate the insurance sector"],
    options_hi: ["विदेशी व्यापार बढ़ाना", "औद्योगिक विकास", "आवासीय सुविधा (Housing Facility) बढ़ाना", "बीमा क्षेत्र को विनियमित करना"],
    correct_option_index: 2,
    explanation_en: "The National Housing Bank (NHB) is an apex financial institution for housing and its primary objective is to promote a sound, healthy, and accessible housing finance system in the country.",
    explanation_hi: "नेशनल हाउसिंग बैंक (NHB) आवास के लिए एक शीर्ष वित्तीय संस्थान है और इसका प्राथमिक उद्देश्य देश में एक सुदृढ़, स्वस्थ और सुलभ आवास वित्त प्रणाली को बढ़ावा देना है।",
  },
  {
    question_en: "In which year did the RRB Act come into force for RRBs (Regional Rural Banks)?",
    question_hi: "RRB (क्षेत्रीय ग्रामीण बैंक) के लिए RRB Act किस वर्ष लागू हुआ?",
    options_en: ["1975", "1976", "1982", "1971"],
    options_hi: ["1975", "1976", "1982", "1971"],
    correct_option_index: 1,
    explanation_en: "While the first five RRBs were established on October 2, 1975, the Regional Rural Banks Act was enacted in 1976.",
    explanation_hi: "हालांकि पहले पांच RRB की स्थापना 2 अक्टूबर 1975 को हुई थी, लेकिन क्षेत्रीय ग्रामीण बैंक अधिनियम 1976 में लागू किया गया था।",
  },
  {
    question_en: "Which of the 5 RRBs established on October 2, 1975, was set up in Uttar Pradesh (UP)?",
    question_hi: "2 अक्टूबर 1975 को स्थापित 5 RRBs में से कौन सा बैंक उत्तर प्रदेश (UP) में स्थापित हुआ था?",
    options_en: ["Prathama Gramin Bank", "Aryavart Gramin Bank", "Prathama Gramin Bank (Moradabad)", "Baroda UP Gramin Bank"],
    options_hi: ["प्रथमा ग्रामीण बैंक", "आर्यवर्त ग्रामीण बैंक", "प्रथमा ग्रामीण बैंक (मुरादाबाद)", "बड़ौदा यूपी ग्रामीण बैंक"],
    correct_option_index: 2,
    explanation_en: "The five RRBs established on Oct 2, 1975, were Prathama Grameen Bank (Moradabad, UP), Gaur Gramin Bank, Haryana Grameen Bank, Jaipur-Ajmer Grameen Bank, and Bhojpur-Rohtas Grameen Bank. The correct name is Prathama Gramin Bank (Moradabad).",
    explanation_hi: "2 अक्टूबर 1975 को स्थापित पांच RRB थे प्रथमा ग्रामीण बैंक (मुरादाबाद, यूपी), गौर ग्रामीण बैंक, हरियाणा ग्रामीण बैंक, जयपुर-अजमेर ग्रामीण बैंक और भोजपुर-रोहतास ग्रामीण बैंक। सही नाम प्रथमा ग्रामीण बैंक (मुरादाबाद) है।",
  },
  {
    question_en: "The concept of Five-Year Plans in India was adopted from which country?",
    question_hi: "भारत में पंचवर्षीय योजनाओं की अवधारणा किस देश से ली गई है?",
    options_en: ["USA", "Japan", "Soviet Union (USSR)", "Germany"],
    options_hi: ["USA", "जापान", "सोवियत संघ (USSR)", "जर्मनी"],
    correct_option_index: 2,
    explanation_en: "The concept of Five-Year Plans (FYPs) was first introduced by Joseph Stalin in the Soviet Union (USSR) in 1928, and India adopted this model after independence.",
    explanation_hi: "पंचवर्षीय योजनाओं (FYPs) की अवधारणा सबसे पहले 1928 में सोवियत संघ (USSR) में जोसेफ स्टालिन द्वारा शुरू की गई थी, और भारत ने स्वतंत्रता के बाद इस मॉडल को अपनाया।",
  },
  {
    question_en: "What was the total number of Five-Year Plans implemented in India?",
    question_hi: "भारत में कुल कितनी पंचवर्षीय योजनाएँ लागू की गईं?",
    options_en: ["11", "12 (The last one was 2012-17)", "10", "13"],
    options_hi: ["11", "12 (अंतिम 2012-17)", "10", "13"],
    correct_option_index: 1,
    explanation_en: "A total of 12 Five-Year Plans were implemented in India. The last one was the 12th Plan (2012-2017), after which the Planning Commission was replaced by NITI Aayog.",
    explanation_hi: "भारत में कुल 12 पंचवर्षीय योजनाएँ लागू की गईं। अंतिम 12वीं योजना (2012-2017) थी, जिसके बाद योजना आयोग को नीति आयोग से बदल दिया गया।",
  },
  {
    question_en: "What was the achievement rate of the First Five-Year Plan (1951-56)?",
    question_hi: "पहली पंचवर्षीय योजना (1951-56) की प्राप्ति (Achieve) दर क्या थी?",
    options_en: ["2.1%", "3.6%", "4.5%", "5.2%"],
    options_hi: ["2.1%", "3.6%", "4.5%", "5.2%"],
    correct_option_index: 1,
    explanation_en: "The First Five-Year Plan had a target growth rate of 2.1% but achieved a growth rate of 3.6%, making it a success.",
    explanation_hi: "पहली पंचवर्षीय योजना का लक्षित विकास दर 2.1% था लेकिन इसने 3.6% की विकास दर हासिल की, जिससे यह सफल रही।",
  },
  {
    question_en: "What was the main objective of the Second Five-Year Plan?",
    question_hi: "दूसरी पंचवर्षीय योजना का मुख्य उद्देश्य क्या था?",
    options_en: ["Increasing agricultural production", "Promoting heavy and basic industries", "Eradication of poverty (Garibi Hatao)", "Achieving self-reliance"],
    options_hi: ["कृषि उत्पादन बढ़ाना", "भारी और आधारभूत उद्योगों को बढ़ाना", "गरीबी हटाओ", "आत्मनिर्भरता प्राप्त करना"],
    correct_option_index: 1,
    explanation_en: "The Second Five-Year Plan (1956-61), based on the P. C. Mahalanobis Model, focused on the rapid industrialisation with emphasis on heavy and basic industries.",
    explanation_hi: "दूसरी पंचवर्षीय योजना (1956-61), पी. सी. महालनोबिस मॉडल पर आधारित थी, जिसमें भारी और आधारभूत उद्योगों पर जोर देने के साथ तीव्र औद्योगीकरण पर ध्यान केंद्रित किया गया था।",
  },
  {
    question_en: "Which country's cooperation led to the establishment of the Bhilai (Chhattisgarh) Iron and Steel Industry?",
    question_hi: "भिलाई (छत्तीसगढ़) लौह इस्पात उद्योग की स्थापना में किस देश का सहयोग मिला था?",
    options_en: ["Germany", "Britain", "Russia (USSR)", "USA"],
    options_hi: ["जर्मनी", "ब्रिटेन", "रूस (USSR)", "USA"],
    correct_option_index: 2,
    explanation_en: "The Bhilai Steel Plant was established with the technical and financial assistance of the Soviet Union (USSR) during the Second Five-Year Plan.",
    explanation_hi: "भिलाई इस्पात संयंत्र की स्थापना दूसरी पंचवर्षीय योजना के दौरान सोवियत संघ (USSR) के तकनीकी और वित्तीय सहयोग से की गई थी।",
  },
  {
    question_en: "Which was the reason for the failure of the Third Five-Year Plan (1961-66)?",
    question_hi: "तीसरी पंचवर्षीय योजना (1961-66) की असफलता का कारण कौन सा था?",
    options_en: ["Nationalization of Banks (1969)", "1962 China War", "1971 Pakistan War", "Famine in the country"],
    options_hi: ["बैंकों का राष्ट्रीयकरण (1969)", "1962 का चीन युद्ध", "1971 का पाक युद्ध", "देश में अकाल"],
    correct_option_index: 1,
    explanation_en: "The Third Five-Year Plan failed to achieve its growth target due to the India-China War (1962) and the India-Pakistan War (1965), along with severe drought in 1965-66.",
    explanation_hi: "तीसरी पंचवर्षीय योजना भारत-चीन युद्ध (1962) और भारत-पाकिस्तान युद्ध (1965) के साथ-साथ 1965-66 में पड़े गंभीर सूखे के कारण अपने विकास लक्ष्य को प्राप्त करने में विफल रही थी।",
  },
  {
    question_en: "During which plan did the Pokhran Nuclear Test (1974) take place?",
    question_hi: "पोखरन परमाणु परीक्षण (1974) किस योजना के दौरान हुआ?",
    options_en: ["Third Plan", "Fourth Plan (1969-74)", "Fifth Plan", "Sixth Plan"],
    options_hi: ["तीसरी योजना", "चौथी योजना (1969-74)", "पाँचवीं योजना", "छठी योजना"],
    correct_option_index: 1,
    explanation_en: "The Pokhran-I nuclear test (Smiling Buddha) took place in May 1974, which falls under the period of the Fourth Five-Year Plan (1969-1974).",
    explanation_hi: "पोखरन-I परमाणु परीक्षण (स्माइलिंग बुद्धा) मई 1974 में हुआ था, जो चौथी पंचवर्षीय योजना (1969-1974) की अवधि के अंतर्गत आता है।",
  },
  {
    question_en: "When was the 'Food for Work Programme' started during the Fifth Five-Year Plan (1974-78)?",
    question_hi: "पाँचवीं पंचवर्षीय योजना (1974-78) के दौरान 'काम के बदले अनाज योजना' कब शुरू हुई थी?",
    options_en: ["1974-75", "1977-78", "1975", "1976"],
    options_hi: ["1974-75", "1977-78", "1975", "1976"],
    correct_option_index: 1,
    explanation_en: "The 'Food for Work Programme' was launched in 1977-78 during the Fifth Five-Year Plan, primarily to generate employment and improve the nutritional status of rural poor.",
    explanation_hi: "'काम के बदले अनाज योजना' पांचवीं पंचवर्षीय योजना के दौरान 1977-78 में शुरू की गई थी, जिसका मुख्य उद्देश्य रोजगार सृजित करना और ग्रामीण गरीबों की पोषण स्थिति में सुधार करना था।",
  },
  {
    question_en: "On which model was the Rolling Plan based?",
    question_hi: "रोलिंग प्लान (अनवरत योजना) किस मॉडल पर आधारित था?",
    options_en: ["D.P. Dhar Model", "Mahalanobis Model", "Gunnar Myrdal Model", "Gadgil Model"],
    options_hi: ["डी.पी. धर मॉडल", "महालनोबिस मॉडल", "गुन्नार मिर्डल मॉडल", "गाडगिल मॉडल"],
    correct_option_index: 2,
    explanation_en: "The Rolling Plan (1978-80), introduced by the Janata Party government, was heavily influenced by the economic theories of Swedish economist Gunnar Myrdal.",
    explanation_hi: "जनता पार्टी सरकार द्वारा शुरू की गई रोलिंग प्लान (1978-80) स्वीडिश अर्थशास्त्री गुन्नार मिर्डल के आर्थिक सिद्धांतों से काफी प्रभावित थी।",
  },
  {
    question_en: "What was the achievement rate of the Sixth Five-Year Plan (1980-85)?",
    question_hi: "छठी पंचवर्षीय योजना (1980-85) की प्राप्ति (Achieve) दर क्या थी?",
    options_en: ["5.2%", "5.7%", "5.74%", "4.5%"],
    options_hi: ["5.2%", "5.7%", "5.74%", "4.5%"],
    correct_option_index: 2,
    explanation_en: "The Sixth Five-Year Plan had a target growth rate of 5.2% and achieved a growth rate of 5.74%, making it a success.",
    explanation_hi: "छठी पंचवर्षीय योजना का लक्षित विकास दर 5.2% था और इसने 5.74% की विकास दर हासिल की, जिससे यह सफल रही।",
  },
  {
    question_en: "In which year was the Jawahar Rozgar Yojana (JRY) launched?",
    question_hi: "जवाहर रोज़गार योजना (Jawahar Rozgar Yojana - JRY) किस वर्ष शुरू हुई थी?",
    options_en: ["1985", "1989", "1993", "1991"],
    options_hi: ["1985", "1989", "1993", "1991"],
    correct_option_index: 1,
    explanation_en: "The Jawahar Rozgar Yojana (JRY) was launched in April 1989 during the Seventh Five-Year Plan.",
    explanation_hi: "जवाहर रोज़गार योजना (JRY) सातवीं पंचवर्षीय योजना के दौरान अप्रैल 1989 में शुरू की गई थी।",
  },
  {
    question_en: "When was the PM Rozgar Program started during the Eighth Five-Year Plan?",
    question_hi: "आठवीं पंचवर्षीय योजना के दौरान PM रोज़गार कार्यक्रम कब शुरू हुआ?",
    options_en: ["1992", "1993", "1995", "1996"],
    options_hi: ["1992", "1993", "1995", "1996"],
    correct_option_index: 1,
    explanation_en: "The Prime Minister's Rozgar Yojana (PMRY) was launched on October 2, 1993, during the Eighth Five-Year Plan (1992-97).",
    explanation_hi: "प्रधानमंत्री रोज़गार योजना (PMRY) आठवीं पंचवर्षीय योजना (1992-97) के दौरान 2 अक्टूबर 1993 को शुरू की गई थी।",
  },
  {
    question_en: "In which year was the Consumer Protection Act implemented?",
    question_hi: "उपभोक्ता संरक्षण अधिनियम (Consumer Protection Act) किस वर्ष लागू हुआ?",
    options_en: ["1980", "1986", "1989", "1991"],
    options_hi: ["1980", "1986", "1989", "1991"],
    correct_option_index: 1,
    explanation_en: "The Consumer Protection Act was passed in 1986. It aims to protect the interests of consumers.",
    explanation_hi: "उपभोक्ता संरक्षण अधिनियम 1986 में पारित किया गया था। इसका उद्देश्य उपभोक्ताओं के हितों की रक्षा करना है।",
  },
  {
    question_en: "What was the main objective of the Ninth Five-Year Plan (1997-2002)?",
    question_hi: "नौवीं पंचवर्षीय योजना (1997-2002) का मुख्य उद्देश्य क्या था?",
    options_en: ["Inclusive Sustainable Development", "Social Justice and Economic Growth", "Eradication of Poverty (Garibi Hatao)", "Achieving rapid growth"],
    options_hi: ["समावेशी सतत विकास", "सामाजिक न्याय और आर्थिक संवृद्धि", "गरीबी हटाओ", "तेज वृद्धि प्राप्त करना"],
    correct_option_index: 1,
    explanation_en: "The main theme of the Ninth Five-Year Plan was 'Social Justice and Economic Growth' with a focus on 'Growth with Equity'.",
    explanation_hi: "नौवीं पंचवर्षीय योजना का मुख्य विषय 'सामाजिक न्याय और आर्थिक संवृद्धि' था, जिसमें 'समानता के साथ विकास' पर ध्यान केंद्रित किया गया था।",
  },
  {
    question_en: "In which year were the Antyodaya Anna Yojana and the National Population Policy implemented?",
    question_hi: "अंत्योदय अन्न योजना और राष्ट्रीय जनसंख्या नीति किस वर्ष लागू हुई?",
    options_en: ["1999", "2000", "2004", "2002"],
    options_hi: ["1999", "2000", "2004", "2002"],
    correct_option_index: 1,
    explanation_en: "The Antyodaya Anna Yojana (AAY) and the National Population Policy were both launched in the year 2000.",
    explanation_hi: "अंत्योदय अन्न योजना (AAY) और राष्ट्रीय जनसंख्या नीति दोनों ही वर्ष 2000 में शुरू की गई थीं।",
  },
  {
    question_en: "During which plan was the RTI (Right to Information) Act (2005) implemented?",
    question_hi: "RTI (सूचना का अधिकार) अधिनियम (2005) किस योजना के दौरान लागू हुआ?",
    options_en: ["Ninth Plan", "Tenth Plan (2002-07)", "Eleventh Plan", "Twelfth Plan"],
    options_hi: ["नौवीं योजना", "दसवीं योजना (2002-07)", "ग्यारहवीं योजना", "बारहवीं योजना"],
    correct_option_index: 1,
    explanation_en: "The Right to Information (RTI) Act was passed in 2005, which falls under the period of the Tenth Five-Year Plan (2002-2007).",
    explanation_hi: "सूचना का अधिकार (RTI) अधिनियम 2005 में पारित किया गया था, जो दसवीं पंचवर्षीय योजना (2002-2007) की अवधि के अंतर्गत आता है।",
  },
  {
    question_en: "What was the model of the 11th Five-Year Plan?",
    question_hi: "11वीं पंचवर्षीय योजना का मॉडल क्या था?",
    options_en: ["D.P. Dhar Model", "Gadgil Model", "C. Rangarajan Model", "Pranab Mukherjee Model"],
    options_hi: ["डी.पी. धर मॉडल", "गाडगिल मॉडल", "सी. रंगराजन मॉडल", "प्रणब मुखर्जी मॉडल"],
    correct_option_index: 2,
    explanation_en: "The Eleventh Five-Year Plan (2007-12) was prepared under the guidance of the then Deputy Chairman of the Planning Commission, Montek Singh Ahluwalia, but the plan was associated with C. Rangarajan, who headed the Economic Advisory Council to the PM and played a crucial role in its formulation.",
    explanation_hi: "ग्यारहवीं पंचवर्षीय योजना (2007-12) योजना आयोग के तत्कालीन उपाध्यक्ष, मोंटेक सिंह अहलूवालिया के मार्गदर्शन में तैयार की गई थी, लेकिन योजना सी. रंगराजन से जुड़ी हुई थी, जिन्होंने पीएम की आर्थिक सलाहकार परिषद का नेतृत्व किया और इसके निर्माण में महत्वपूर्ण भूमिका निभाई।",
  },
  {
    question_en: "In which year was the NFSA (National Food Security Act) implemented?",
    question_hi: "NFSA (राष्ट्रीय खाद्य सुरक्षा अधिनियम) किस वर्ष लागू हुआ?",
    options_en: ["2012", "2013", "2014", "2015"],
    options_hi: ["2012", "2013", "2014", "2015"],
    correct_option_index: 1,
    explanation_en: "The National Food Security Act (NFSA) was enacted by the Parliament in 2013, aiming to provide subsidized food grains to approximately two-thirds of India's population.",
    explanation_hi: "राष्ट्रीय खाद्य सुरक्षा अधिनियम (NFSA) संसद द्वारा 2013 में अधिनियमित किया गया था, जिसका उद्देश्य भारत की लगभग दो-तिहाई आबादी को रियायती खाद्यान्न प्रदान करना है।",
  },
  {
    question_en: "In which year were Make in India and PM Jan Dhan Yojana launched?",
    question_hi: "मेक इन इंडिया (Make in India) और PM जनधन योजना किस वर्ष शुरू हुई?",
    options_en: ["2013", "2014", "2015", "2016"],
    options_hi: ["2013", "2014", "2015", "2016"],
    correct_option_index: 1,
    explanation_en: "Both the 'Pradhan Mantri Jan Dhan Yojana' and the 'Make in India' initiative were launched in 2014.",
    explanation_hi: " 'प्रधानमंत्री जन धन योजना' और 'मेक इन इंडिया' पहल दोनों 2014 में शुरू की गई थीं।",
  },
  {
    question_en: "In what form did Dadabhai Naoroji, who first estimated the National Income (1867-68), measure it?",
    question_hi: "राष्ट्रीय आय का सर्वप्रथम अनुमान (1867-68) लगाने वाले दादा भाई नौरोजी ने इसे किस रूप में मापा था?",
    options_en: ["Only in the form of goods", "In the form of money (Money)", "Only in the form of services", "In the form of barter system"],
    options_hi: ["केवल वस्तुओं के रूप में", "मुद्रा (Money) के रूप में", "केवल सेवाओं के रूप में", "वस्तु विनिमय प्रणाली के रूप में"],
    correct_option_index: 1,
    explanation_en: "Dadabhai Naoroji's estimate of the national income (Rs. 20 per capita) for 1867-68 was measured in monetary terms.",
    explanation_hi: "दादा भाई नौरोजी द्वारा 1867-68 के लिए राष्ट्रीय आय का अनुमान (प्रति व्यक्ति ₹ 20) मौद्रिक रूप में मापा गया था।",
  },
  {
    question_en: "Data for how many financial years is taken to measure National Income?",
    question_hi: "राष्ट्रीय आय को मापने के लिए कितने वित्तीय वर्ष का आंकड़ा लिया जाता है?",
    options_en: ["5 years", "10 years", "One financial year (April 1 to March 31)", "3 years"],
    options_hi: ["5 वर्ष", "10 वर्ष", "एक वित्तीय वर्ष", "3 वर्ष"],
    correct_option_index: 2,
    explanation_en: "National Income is typically measured for a single financial year, which in India runs from April 1 to March 31.",
    explanation_hi: "राष्ट्रीय आय को आमतौर पर एक ही वित्तीय वर्ष के लिए मापा जाता है, जो भारत में 1 अप्रैल से 31 मार्च तक चलता है।",
  },
  {
    question_en: "In the Factor Income Method, what is received in exchange for Labour?",
    question_hi: "कारक आय विधि (Factor Income Method) में श्रम (Labour) के बदले क्या प्राप्त होता है?",
    options_en: ["Rent", "Profit", "Interest", "Wages/Salary"],
    options_hi: ["किराया (Rent)", "लाभ (Profit)", "ब्याज (Interest)", "मजदूरी/वेतन"],
    correct_option_index: 3,
    explanation_en: "The four factors of production (Land, Labour, Capital, Entrepreneurship) are compensated by four types of factor income: Rent (for Land), Wages/Salary (for Labour), Interest (for Capital), and Profit (for Entrepreneurship).",
    explanation_hi: "उत्पादन के चार कारकों (भूमि, श्रम, पूंजी, उद्यमिता) को चार प्रकार की कारक आय से मुआवजा दिया जाता है: किराया (भूमि के लिए), मजदूरी/वेतन (श्रम के लिए), ब्याज (पूंजी के लिए), और लाभ (उद्यमिता के लिए)।",
  },
  {
    question_en: "What is obtained by subtracting Depreciation from GDP?",
    question_hi: "GDP में से मूल्य ह्रास (Depreciation) को घटाने पर क्या प्राप्त होता है?",
    options_en: ["GNP", "NNP", "NDP (Net Domestic Product)", "NNP at Factor Cost"],
    options_hi: ["GNP", "NNP", "NDP (शुद्ध घरेलू उत्पाद)", "कारक लागत पर NNP"],
    correct_option_index: 2,
    explanation_en: "NDP (Net Domestic Product) is calculated as GDP minus Depreciation. It represents the net value of all goods and services produced within the domestic territory of a country.",
    explanation_hi: "NDP (शुद्ध घरेलू उत्पाद) की गणना GDP में से मूल्य ह्रास को घटाकर की जाती है। यह किसी देश की घरेलू सीमा के भीतर उत्पादित सभी वस्तुओं और सेवाओं के शुद्ध मूल्य का प्रतिनिधित्व करता है।",
  },
  {
    question_en: "What is the formula for the GDP Deflator?",
    question_hi: "GDP अपस्फीतिकारक (Deflator) का सूत्र क्या है?",
    options_en: ["(Real GDP / Nominal GDP) x 100", "(GNP / GDP) x 100", "(Nominal GDP / Real GDP) x 100", "(Nominal GDP - Real GDP) x 100"],
    options_hi: ["(वास्तविक GDP / सांकेतिक GDP) x 100", "(GNP / GDP) x 100", "(सांकेतिक GDP / वास्तविक GDP) x 100", "(सांकेतिक GDP - वास्तविक GDP) x 100"],
    correct_option_index: 2,
    explanation_en: "The GDP Deflator is a measure of the level of prices of all new, domestically produced, final goods and services in an economy. Formula: (Nominal GDP / Real GDP) x 100.",
    explanation_hi: "GDP अपस्फीतिकारक एक अर्थव्यवस्था में सभी नए, घरेलू स्तर पर उत्पादित, अंतिम वस्तुओं और सेवाओं के मूल्य स्तर का एक माप है। सूत्र: (सांकेतिक GDP / वास्तविक GDP) x 100।",
  },
  {
    question_en: "Which two institutions were merged to establish the NSO (National Statistical Office)?",
    question_hi: "NSO (राष्ट्रीय सांख्यिकी कार्यालय) की स्थापना में किन दो संस्थाओं का विलय किया गया?",
    options_en: ["NITI Aayog + CSO", "CSO + NSSO", "CSO + Finance Ministry", "NSSO + Ministry of Statistics"],
    options_hi: ["नीति आयोग + CSO", "CSO + NSSO", "CSO + वित्त मंत्रालय", "NSSO + सांख्यिकी मंत्रालय"],
    correct_option_index: 1,
    explanation_en: "The National Statistical Office (NSO) was formed by the merger of the Central Statistics Office (CSO) and the National Sample Survey Office (NSSO).",
    explanation_hi: "राष्ट्रीय सांख्यिकी कार्यालय (NSO) का गठन केंद्रीय सांख्यिकी कार्यालय (CSO) और राष्ट्रीय नमूना सर्वेक्षण कार्यालय (NSSO) के विलय से किया गया था।",
  },
  {
    question_en: "The Hindu Growth Rate (HGIR) was related to which rate?",
    question_hi: "Hindu Growth Rate (HGIR) किस दर से संबंधित था?",
    options_en: ["Inflation Rate", "Population Rate", "National Income (GDP) Growth Rate (3.5%)", "Poverty Rate"],
    options_hi: ["मुद्रास्फीति दर", "जनसंख्या दर", "राष्ट्रीय आय (GDP) विकास दर (3.5%)", "गरीबी दर"],
    correct_option_index: 2,
    explanation_en: "The 'Hindu Growth Rate' is a term coined by economist Raj Krishna in 1978 to describe the low annual growth rate of the Indian economy (around 3.5%) from the 1950s to the 1980s.",
    explanation_hi: "'हिंदू ग्रोथ रेट' एक शब्द है जिसे अर्थशास्त्री राज कृष्ण ने 1978 में 1950 के दशक से 1980 के दशक तक भारतीय अर्थव्यवस्था की कम वार्षिक विकास दर (लगभग 3.5%) का वर्णन करने के लिए गढ़ा था।",
  },
  {
    question_en: "Which of the following items is not included in the calculation of National Income?",
    question_hi: "निम्नलिखित में से कौन सी मद राष्ट्रीय आय की गणना में शामिल नहीं की जाती है?",
    options_en: ["Lottery/Pension (Transfer Payment)", "Profit", "Rent", "Wages"],
    options_hi: ["लॉटरी/पेंशन (हस्तांतरण भुगतान)", "लाभ", "किराया", "मजदूरी"],
    correct_option_index: 0,
    explanation_en: "Transfer payments like lottery winnings, pensions, and unemployment allowances are not included in National Income as they do not represent any productive service and are merely transfers of income.",
    explanation_hi: "लॉटरी जीत, पेंशन और बेरोजगारी भत्ते जैसे हस्तांतरण भुगतान राष्ट्रीय आय में शामिल नहीं होते हैं क्योंकि वे किसी भी उत्पादक सेवा का प्रतिनिधित्व नहीं करते हैं और केवल आय का हस्तांतरण हैं।",
  },
  {
    question_en: "The word 'Budget' is derived from the French word 'Bougette', which means what?",
    question_hi: "बजट शब्द फ्रांसीसी शब्द 'बुगेट' से बना है, जिसका अर्थ क्या है?",
    options_en: ["Estimated expenditure", "Financial statement", "Leather Bag", "Annual account"],
    options_hi: ["अनुमानित व्यय", "वित्तीय विवरण", "चमड़े का थैला (Leather Bag)", "वार्षिक लेखा"],
    correct_option_index: 2,
    explanation_en: "The word 'Budget' is derived from the French word 'Bougette' (meaning small bag or pouch/leather bag), referring to the bag in which the financial proposals were originally carried.",
    explanation_hi: "'बजट' शब्द फ्रांसीसी शब्द 'बुगेट' (छोटा बैग या थैली/चमड़े का थैला) से लिया गया है, जो उस बैग को संदर्भित करता है जिसमें मूल रूप से वित्तीय प्रस्ताव ले जाए जाते थे।",
  },
  {
    question_en: "The Annual Financial Statement is mentioned in which article of the Constitution?",
    question_hi: "वार्षिक वित्तीय विवरण (Annual Financial Statement) का उल्लेख संविधान के किस अनुच्छेद में है?",
    options_en: ["Article 280", "Article 202 (State Budget)", "Article 112 (Union Budget)", "Article 300"],
    options_hi: ["अनुच्छेद 280", "अनुच्छेद 202 (राज्य बजट)", "अनुच्छेद 112 (केंद्र सरकार)", "अनुच्छेद 300"],
    correct_option_index: 2,
    explanation_en: "Article 112 of the Constitution of India mandates the Union Government to present an 'Annual Financial Statement' (commonly known as the Union Budget) to the Parliament every year.",
    explanation_hi: "भारत के संविधान का अनुच्छेद 112 केंद्र सरकार को हर साल संसद के समक्ष एक 'वार्षिक वित्तीय विवरण' (जिसे आमतौर पर केंद्रीय बजट कहा जाता है) प्रस्तुत करने का आदेश देता है।",
  },
  {
    question_en: "Who presented the first budget of independent India (1947)?",
    question_hi: "स्वतंत्र भारत (1947) का पहला बजट किसने प्रस्तुत किया था?",
    options_en: ["John Mathai", "R.K. Shanmukham Chetty (November 26, 1947)", "James Wilson", "Morarji Desai"],
    options_hi: ["जॉन मथाई", "आर.के. षणमुखम चेट्टी (26 नवंबर 1947)", "जेम्स विल्सन", "मोरारजी देसाई"],
    correct_option_index: 1,
    explanation_en: "R.K. Shanmukham Chetty presented the first budget of independent India on November 26, 1947.",
    explanation_hi: "आर.के. षणमुखम चेट्टी ने स्वतंत्र भारत का पहला बजट 26 नवंबर 1947 को प्रस्तुत किया था।",
  },
  {
    question_en: "For which financial year is the Economic Survey prepared?",
    question_hi: "आर्थिक सर्वेक्षण (Economic Survey) किस वित्तीय वर्ष के लिए तैयार किया जाता है?",
    options_en: ["For the upcoming financial year", "For the previous financial year (April 1 to March 31)", "Only up to February 1st", "For the current financial year"],
    options_hi: ["आगामी वित्तीय वर्ष के लिए", "पिछला वित्तीय वर्ष (1 अप्रैल से 31 मार्च)", "केवल 1 फरवरी तक के लिए", "वर्तमान वित्तीय वर्ष के लिए"],
    correct_option_index: 1,
    explanation_en: "The Economic Survey is a review of the developments in the Indian economy over the previous financial year (April 1 to March 31), presented one day before the Budget.",
    explanation_hi: "आर्थिक सर्वेक्षण पिछले वित्तीय वर्ष (1 अप्रैल से 31 मार्च) के दौरान भारतीय अर्थव्यवस्था में हुए विकास की समीक्षा होती है, जिसे बजट से एक दिन पहले प्रस्तुत किया जाता है।",
  },
  {
    question_en: "What is the government's income that either reduces the government's assets or increases its liability (debt)?",
    question_hi: "सरकार की वह आय जिससे या तो सरकार की संपत्ति में कमी हो या कर्ज (Liability) में वृद्धि हो, क्या कहलाती है?",
    options_en: ["Revenue Income", "Revenue Expenditure", "Capital Receipt", "Capital Expenditure"],
    options_hi: ["राजस्व आय", "राजस्व व्यय", "पूंजीगत आय (Capital Receipt)", "पूंजीगत व्यय"],
    correct_option_index: 2,
    explanation_en: "Capital Receipts are those receipts of the government which create a liability or reduce the financial assets. Examples include loan recovery and borrowing.",
    explanation_hi: "पूंजीगत आय सरकार की वे प्राप्तियां हैं जो या तो एक देनदारी उत्पन्न करती हैं या वित्तीय परिसंपत्तियों को कम करती हैं। उदाहरणों में ऋण की वसूली और उधार लेना शामिल है।",
  },
  {
    question_en: "What is an example of Revenue Expenditure?",
    question_hi: "राजस्व व्यय (Revenue Expenditure) का उदाहरण क्या है?",
    options_en: ["Repayment of loan", "Construction of a park/road (Capital Expenditure)", "Pension, Salary, Subsidy", "Investment in shares"],
    options_hi: ["ऋण की अदायगी", "पार्क/सड़क का निर्माण", "पेंशन, वेतन, सब्सिडी", "शेयरों में निवेश"],
    correct_option_index: 2,
    explanation_en: "Revenue expenditure is that expenditure which neither creates any asset nor reduces any liability. Payments like salaries, pensions, subsidies, and interest payments are examples of Revenue Expenditure.",
    explanation_hi: "राजस्व व्यय वह व्यय है जो न तो कोई संपत्ति बनाता है और न ही कोई देनदारी कम करता है। वेतन, पेंशन, सब्सिडी और ब्याज भुगतान जैसे भुगतान राजस्व व्यय के उदाहरण हैं।",
  },
  {
    question_en: "When does a Revenue Deficit occur?",
    question_hi: "राजस्व घाटा (Revenue Deficit) कब होता है?",
    options_en: ["When Total Expenditure > Total Income.", "When Revenue Expenditure (RE) is greater than Revenue Income (RI) (RE > RI).", "When Primary Deficit is zero.", "When Capital Expenditure is greater than Capital Income."],
    options_hi: ["जब कुल व्यय > कुल आय हो।", "जब राजस्व व्यय (RE) राजस्व आय (RI) से ज्यादा हो (RE > RI)।", "जब प्राथमिक घाटा शून्य हो।", "जब पूंजीगत व्यय पूंजीगत आय से ज्यादा हो।"],
    correct_option_index: 1,
    explanation_en: "Revenue Deficit is the excess of the government's total revenue expenditure over its total revenue receipts. Formula: Revenue Deficit = Revenue Expenditure - Revenue Receipts.",
    explanation_hi: "राजस्व घाटा सरकार के कुल राजस्व व्यय का उसकी कुल राजस्व प्राप्तियों पर आधिक्य है। सूत्र: राजस्व घाटा = राजस्व व्यय - राजस्व प्राप्तियाँ।",
  },
  {
    question_en: "What does Fiscal Deficit indicate?",
    question_hi: "राजकोषीय घाटा (Fiscal Deficit) क्या दर्शाता है?",
    options_en: ["Government's Revenue Expenditure.", "Primary Deficit + Interest Payments.", "Government's Total Borrowing (Total Expenditure - Total Income).", "Total debt of the nation."],
    options_hi: ["सरकार का राजस्व व्यय।", "प्राथमिक घाटा + ब्याज भुगतान।", "सरकार की कुल उधारी (कुल व्यय - कुल आय)।", "राष्ट्र का कुल ऋण।"],
    correct_option_index: 2,
    explanation_en: "Fiscal Deficit is the difference between the government's total expenditure and its total receipts (excluding borrowing). It represents the total borrowing requirements of the government.",
    explanation_hi: "राजकोषीय घाटा सरकार के कुल व्यय और उसकी कुल प्राप्तियों (उधार को छोड़कर) के बीच का अंतर है। यह सरकार की कुल उधार आवश्यकताओं को दर्शाता है।",
  },
  {
    question_en: "What is the meaning of Monetary Deficit?",
    question_hi: "मौद्रिक घाटा (Monetary Deficit) का अर्थ क्या है?",
    options_en: ["Total internal borrowing.", "Primary Deficit.", "Borrowing from the RBI (Printing of new currency).", "Fiscal Deficit - Foreign borrowing."],
    options_hi: ["कुल आंतरिक उधारी।", "प्राथमिक घाटा।", "RBI से लिया गया उधार।", "राजकोषीय घाटा - विदेशी उधारी।"],
    correct_option_index: 2,
    explanation_en: "Monetary Deficit refers to the increase in the Net RBI Credit to the Government (borrowing from the RBI). This practice is now less common due to the FRBM Act.",
    explanation_hi: "मौद्रिक घाटा सरकार को शुद्ध RBI क्रेडिट में वृद्धि (RBI से उधार लेना) को संदर्भित करता है। FRBM अधिनियम के कारण यह अभ्यास अब कम आम है।",
  },
  {
    question_en: "Who regulates the Money Market?",
    question_hi: "मुद्रा बाजार (Money Market) किसके द्वारा विनियमित (Regulated) होता है?",
    options_en: ["SEBI", "Ministry of Finance", "RBI", "NABARD"],
    options_hi: ["SEBI", "वित्त मंत्रालय", "RBI", "NABARD"],
    correct_option_index: 2,
    explanation_en: "The Money Market deals with short-term funds (less than one year) and is regulated by the Reserve Bank of India (RBI).",
    explanation_hi: "मुद्रा बाजार अल्पकालिक निधियों (एक वर्ष से कम) से संबंधित है और यह भारतीय रिज़र्व बैंक (RBI) द्वारा विनियमित होता है।",
  },
  {
    question_en: "What is the main feature of the Secondary Capital Market?",
    question_hi: "द्वितीयक पूंजी बाजार (Secondary Capital Market) की मुख्य विशेषता क्या है?",
    options_en: ["Transaction of IPOs.", "Shares are transacted among investors.", "Finance for a period of less than one year.", "Issuance of new securities."],
    options_hi: ["IPO का लेन-देन।", "शेयर का लेन-देन निवेशकों के मध्य होता है।", "एक वर्ष से कम अवधि का वित्त।", "नई प्रतिभूतियों का निर्गमन।"],
    correct_option_index: 1,
    explanation_en: "In the Secondary Capital Market (like stock exchanges), existing securities (shares, bonds) are traded among investors, unlike the Primary Market where new securities are issued.",
    explanation_hi: "द्वितीयक पूंजी बाजार (जैसे स्टॉक एक्सचेंज) में, नई प्रतिभूतियों को जारी करने वाले प्राथमिक बाजार के विपरीत, मौजूदा प्रतिभूतियों (शेयरों, बॉन्डों) का कारोबार निवेशकों के बीच होता है।",
  },
  {
    question_en: "When is an IPO (Initial Public Offer) issued?",
    question_hi: "IPO (Initial Public Offer) कब जारी किया जाता है?",
    options_en: ["When the company collects additional finance (FPO).", "When a company issues shares for the first time to raise finance.", "When investors open a Demat Account.", "When the company buys back its shares."],
    options_hi: ["जब कंपनी अतिरिक्त वित्त संग्रहित करती है (FPO)।", "जब कोई कंपनी पहली बार वित्त संग्रहित करने के लिए शेयर जारी करती है।", "जब निवेशक Demat Account खोलते हैं।", "जब कंपनी अपने शेयर वापस खरीदती है।"],
    correct_option_index: 1,
    explanation_en: "An Initial Public Offer (IPO) is the first time a private company offers its shares to the public to raise capital.",
    explanation_hi: "एक आरंभिक सार्वजनिक पेशकश (IPO) पहली बार होता है जब कोई निजी कंपनी पूंजी जुटाने के लिए अपने शेयर जनता को पेश करती है।",
  },
  {
    question_en: "What do 'Bear' (मंदड़िया) investors anticipate in the stock market?",
    question_hi: "'बियर' (Bear/मंदड़िया) निवेशक शेयर बाजार में क्या आशा करते हैं?",
    options_en: ["Anticipation of price increase.", "Anticipation of stable prices.", "Anticipation of a decrease in share prices.", "Anticipation of high dividend."],
    options_hi: ["कीमतों में वृद्धि की आशा।", "स्थिर कीमतों की आशा।", "शेयर की कीमतों में कमी की आशा।", "उच्च लाभांश की आशा।"],
    correct_option_index: 2,
    explanation_en: "A 'Bear' investor is pessimistic and anticipates that the prices of shares will fall. They profit by selling high and buying back low (short selling).",
    explanation_hi: "एक 'बियर' निवेशक निराशावादी होता है और यह आशा करता है कि शेयरों की कीमतें गिर जाएंगी। वे ऊँचे दाम पर बेचकर और फिर कम दाम पर वापस खरीदकर (शॉर्ट सेलिंग) लाभ कमाते हैं।",
  },
  {
    question_en: "What is the other name for BSE (Bombay Stock Exchange)?",
    question_hi: "BSE (बॉम्बे स्टॉक एक्सचेंज) का अन्य नाम क्या है?",
    options_en: ["NSE", "Ferwani Street", "Dalal Street", "Mint Road"],
    options_hi: ["NSE", "फेरवानी स्ट्रीट", "दलाल स्ट्रीट", "मिंट रोड"],
    correct_option_index: 2,
    explanation_en: "The Bombay Stock Exchange (BSE) is located on Dalal Street in Mumbai, and the term 'Dalal Street' is often used synonymously with the BSE or the Indian stock market.",
    explanation_hi: "बॉम्बे स्टॉक एक्सचेंज (BSE) मुंबई में दलाल स्ट्रीट पर स्थित है, और 'दलाल स्ट्रीट' शब्द का प्रयोग अक्सर BSE या भारतीय शेयर बाजार के पर्याय के रूप में किया जाता है।",
  },
  {
    question_en: "The establishment of NSE (National Stock Exchange) was recommended by which committee?",
    question_hi: "NSE (नेशनल स्टॉक एक्सचेंज) की स्थापना किस समिति की सिफारिश पर हुई थी?",
    options_en: ["Narasimham Committee", "Shivraman Committee", "Ferwani Committee (1992)", "Chakravarthy Committee"],
    options_hi: ["नरसिम्हन समिति", "शिवरामन समिति", "फेरवानी समिति (1992)", "चक्रवर्ती समिति"],
    correct_option_index: 2,
    explanation_en: "The National Stock Exchange (NSE) was established in 1992 on the recommendation of the High Powered Study Group on the Establishment of New Stock Exchanges, headed by M.J. Ferwani (Ferwani Committee).",
    explanation_hi: "नेशनल स्टॉक एक्सचेंज (NSE) की स्थापना 1992 में एम.जे. फेरवानी (फेरवानी समिति) की अध्यक्षता में नए स्टॉक एक्सचेंज की स्थापना पर उच्चाधिकार प्राप्त अध्ययन समूह की सिफारिश पर की गई थी।",
  },
  {
    question_en: "In which country was GST first implemented?",
    question_hi: "GST सर्वप्रथम किस देश में लागू हुआ था?",
    options_en: ["India", "Canada", "France (1954)", "Germany"],
    options_hi: ["भारत", "कनाडा", "फ्रांस (1954)", "जर्मनी"],
    correct_option_index: 2,
    explanation_en: "France was the first country to introduce Goods and Services Tax (GST) in 1954.",
    explanation_hi: "GST (वस्तु एवं सेवा कर) लागू करने वाला पहला देश फ्रांस (1954) था।",
  },
  {
    question_en: "Which was the second state in India to implement GST?",
    question_hi: "GST लागू करने वाला भारत का दूसरा राज्य कौन सा था?",
    options_en: ["Assam", "Jammu and Kashmir", "Bihar", "Telangana"],
    options_hi: ["असम", "जम्मू और कश्मीर", "बिहार", "तेलंगाना"],
    correct_option_index: 2,
    explanation_en: "Assam was the first state to ratify the GST Bill, and Bihar was the second state.",
    explanation_hi: "असम GST बिल को पुष्टि (ratify) करने वाला पहला राज्य था, और बिहार दूसरा राज्य था।",
  },
  {
    question_en: "On which date did the President sign the GST, after which it became the 101st Constitutional Amendment Act?",
    question_hi: "GST पर राष्ट्रपति के हस्ताक्षर किस तिथि को हुए, जिसके बाद यह 101वाँ संविधान संशोधन अधिनियम बना?",
    options_en: ["August 3, 2016", "September 8, 2016", "July 1, 2017", "April 1, 2017"],
    options_hi: ["3 अगस्त 2016", "8 सितंबर 2016", "1 जुलाई 2017", "1 अप्रैल 2017"],
    correct_option_index: 1,
    explanation_en: "The Constitutional Amendment Bill for GST was ratified by the President on September 8, 2016, and became the 101st Constitutional Amendment Act. GST was implemented from July 1, 2017.",
    explanation_hi: "GST के लिए संवैधानिक संशोधन विधेयक पर राष्ट्रपति ने 8 सितंबर 2016 को हस्ताक्षर किए और यह 101वाँ संविधान संशोधन अधिनियम बन गया। GST 1 जुलाई 2017 से लागू हुआ था।",
  },
  {
    question_en: "Under which article was the GST Council constituted?",
    question_hi: "GST परिषद (GST Council) का गठन किस अनुच्छेद के तहत हुआ?",
    options_en: ["Article 280", "Article 112", "Article 279A", "Article 246A"],
    options_hi: ["अनुच्छेद 280", "अनुच्छेद 112", "अनुच्छेद 279A", "अनुच्छेद 246A"],
    correct_option_index: 2,
    explanation_en: "The GST Council was constituted under Article 279A of the Constitution to make recommendations to the Union and State Governments on issues related to GST.",
    explanation_hi: "GST परिषद का गठन संविधान के अनुच्छेद 279A के तहत GST से संबंधित मुद्दों पर केंद्र और राज्य सरकारों को सिफारिशें करने के लिए किया गया था।",
  },
  {
    question_en: "Who was the first chairperson of the GST Council?",
    question_hi: "GST परिषद के पहले अध्यक्ष कौन थे?",
    options_en: ["Nirmala Sitharaman", "Shaktikanta Das", "Arun Jaitley", "Piyush Goyal"],
    options_hi: ["निर्मला सीतारमण", "शक्तिकांत दास", "अरुण जेटली", "पीयूष गोयल"],
    correct_option_index: 2,
    explanation_en: "The Union Finance Minister is the chairperson of the GST Council. Since GST was implemented during the tenure of the late Arun Jaitley as Finance Minister, he was the first chairman.",
    explanation_hi: "केंद्रीय वित्त मंत्री GST परिषद के अध्यक्ष होते हैं। चूंकि GST तत्कालीन वित्त मंत्री स्वर्गीय अरुण जेटली के कार्यकाल के दौरान लागू किया गया था, इसलिए वह पहले अध्यक्ष थे।",
  },
  {
    question_en: "Which commodity is NOT excluded from the ambit of GST?",
    question_hi: "GST के दायरे से बाहर रखी गई वस्तुओं में कौन शामिल नहीं है?",
    options_en: ["Alcohol for human consumption", "Petroleum products", "Clothes/Textiles", "Electricity"],
    options_hi: ["मानव उपभोग हेतु शराब", "पेट्रोलियम उत्पाद", "कपड़े/वस्त्र", "बिजली"],
    correct_option_index: 2,
    explanation_en: "Alcohol for human consumption, petroleum products, and electricity are kept outside the purview of GST. However, clothes/textiles (depending on the price range) are generally under the GST regime.",
    explanation_hi: "मानव उपभोग हेतु शराब, पेट्रोलियम उत्पाद और बिजली को GST के दायरे से बाहर रखा गया है। हालाँकि, कपड़े/वस्त्र (कीमत सीमा के आधार पर) आम तौर पर GST व्यवस्था के अंतर्गत आते हैं।",
  },
  {
    question_en: "The Planning Commission was established on the recommendation of which committee?",
    question_hi: "योजना आयोग की स्थापना किस समिति की सिफारिश पर की गई थी?",
    options_en: ["K.C. Niyogi Committee", "Narasimham Committee", "Ferwani Committee", "Chakravarthy Committee"],
    options_hi: ["के.सी. नियोगी समिति", "नरसिम्हन समिति", "फेरवानी समिति", "चक्रवर्ती समिति"],
    correct_option_index: 0,
    explanation_en: "The Planning Commission was set up in 1950 based on the recommendations of the Advisory Planning Board constituted in 1946 under the chairmanship of K.C. Niyogi.",
    explanation_hi: "योजना आयोग की स्थापना 1950 में के.सी. नियोगी की अध्यक्षता में 1946 में गठित सलाहकार योजना बोर्ड की सिफारिशों के आधार पर की गई थी।",
  },
  {
    question_en: "Who was the last Deputy Chairperson of the Planning Commission?",
    question_hi: "योजना आयोग के अंतिम उपाध्यक्ष कौन थे?",
    options_en: ["Montek Singh Ahluwalia", "Gulzarilal Nanda", "Narendra Modi (Chairperson)", "P. Chidambaram"],
    options_hi: ["मॉन्टेक सिंह अहलूवालिया", "गुलजारी लाल नंदा", "नरेंद्र मोदी", "पी. चिदंबरम"],
    correct_option_index: 0,
    explanation_en: "Montek Singh Ahluwalia was the last Deputy Chairperson of the Planning Commission before it was replaced by NITI Aayog in 2015.",
    explanation_hi: "2015 में नीति आयोग द्वारा प्रतिस्थापित किए जाने से पहले मॉन्टेक सिंह अहलूवालिया योजना आयोग के अंतिम उपाध्यक्ष थे।",
  },
  {
    question_en: "By whom and under which article is the Finance Commission constituted?",
    question_hi: "वित्त आयोग का गठन किसके द्वारा और किस अनुच्छेद के तहत किया जाता है?",
    options_en: ["Prime Minister, Article 112", "President, Article 280", "Finance Minister, Article 280", "Parliament, Article 280"],
    options_hi: ["प्रधानमंत्री, अनुच्छेद 112", "राष्ट्रपति, अनुच्छेद 280", "वित्त मंत्री, अनुच्छेद 280", "संसद, अनुच्छेद 280"],
    correct_option_index: 1,
    explanation_en: "The Finance Commission is constituted by the President of India every five years (or earlier) under Article 280 of the Constitution.",
    explanation_hi: "वित्त आयोग का गठन संविधान के अनुच्छेद 280 के तहत भारत के राष्ट्रपति द्वारा हर पांच साल (या उससे पहले) में किया जाता है।",
  }
];

export default test6Questions;
