import type { QuizQuestion } from '../../../types';

const test9Questions: QuizQuestion[] = [
  {
    question_en: "Which commission/committee recommended the establishment of the RBI?",
    question_hi: "RBI की स्थापना के लिए किस कमीशन/आयोग की सिफारिश की गई थी?",
    options_en: ["Narasimham Committee", "Royal Commission (Hilton Young Commission)", "K.C. Neogy Committee", "Ferwani Committee"],
    options_hi: ["नरसिम्हन आयोग", "शाही आयोग (हिल्टन यंग कमीशन)", "के.सी. नियोगी समिति", "फेरवनी समिति"],
    correct_option_index: 1,
    explanation_en: "The RBI was established on April 1, 1935, based on the recommendation of the Royal Commission (Hilton Young Commission).",
    explanation_hi: "RBI की स्थापना शाही आयोग (हिल्टन यंग कमीशन) की सिफारिश पर 1 अप्रैल 1935 को हुई थी।",
  },
  {
    question_en: "On which date was the RBI nationalized?",
    question_hi: "RBI का राष्ट्रीयकरण किस तिथि को हुआ था?",
    options_en: ["April 1, 1935", "July 1, 1955", "January 1, 1949", "July 19, 1969"],
    options_hi: ["1 अप्रैल 1935", "1 जुलाई 1955", "1 जनवरी 1949", "19 जुलाई 1969"],
    correct_option_index: 2,
    explanation_en: "The nationalization of RBI took place on January 1, 1949.",
    explanation_hi: "RBI का राष्ट्रीयकरण 1 जनवरी 1949 को हुआ।",
  },
  {
    question_en: "How many government officials (from the Ministry of Finance) are included in the Central Board of Directors (CBD) of the RBI?",
    question_hi: "RBI के सेंट्रल बोर्ड ऑफ डायरेक्टर्स (CBD) में कितने सरकारी अधिकारी (वित्त मंत्रालय से) शामिल होते हैं?",
    options_en: ["1", "2", "4", "10"],
    options_hi: ["1", "2", "4", "10"],
    correct_option_index: 1,
    explanation_en: "The CBD includes 2 government officials (from the Ministry of Finance).",
    explanation_hi: "CBD में 2 सरकारी अधिकारी (वित्त मंत्रालय से) शामिल होते हैं।",
  },
  {
    question_en: "Under the Minimum Reserve System of the RBI, how much foreign currency is maintained for issuing notes?",
    question_hi: "RBI की न्यूनतम आरक्षित प्रणाली (Minimum Reserve System) के तहत नोट जारी करने के लिए कितनी विदेशी मुद्रा रखी जाती है?",
    options_en: ["₹115 crore", "₹200 crore", "₹85 crore", "₹100 crore"],
    options_hi: ["₹115 करोड़", "₹200 करोड़", "₹85 करोड़", "₹100 करोड़"],
    correct_option_index: 2,
    explanation_en: "Under the Minimum Reserve System, out of the total ₹200 crore, ₹85 crore is maintained in the form of foreign currency.",
    explanation_hi: "न्यूनतम आरक्षित प्रणाली के तहत ₹200 करोड़ की राशि में ₹85 करोड़ विदेशी मुद्रा के रूप में रखी जाती है।",
  },
  {
    question_en: "According to the notes, who was the 25th Governor of the RBI?",
    question_hi: "नोट्स के अनुसार, RBI के 25वें गवर्नर कौन थे?",
    options_en: ["Urjit Patel", "C. D. Deshmukh", "Shaktikanta Das (2018-24)", "Osborne Smith"],
    options_hi: ["उर्जित पटेल", "सी. डी. देशमुख", "शक्तिकांत दास (2018-24)", "ओसबोर्न स्मिथ"],
    correct_option_index: 2,
    explanation_en: "The 25th Governor was Shaktikanta Das.",
    explanation_hi: "25वें गवर्नर शक्तिकांत दास थे।",
  },
  {
    question_en: "What is the primary objective of the RBI's Tight Monetary Policy?",
    question_hi: "RBI की कठोर मौद्रिक नीति (Tight Monetary Policy) का प्राथमिक उद्देश्य क्या होता है?",
    options_en: ["Dealing with recession", "Increasing liquidity", "Controlling inflation", "Reducing interest rates"],
    options_hi: ["मंदी से निपटना", "तरलता बढ़ाना", "मुद्रास्फीति (Inflation) को नियंत्रित करना", "ब्याज दरें कम करना"],
    correct_option_index: 2,
    explanation_en: "Tight Monetary Policy is designed to control inflation.",
    explanation_hi: "कठोर मौद्रिक नीति मुद्रास्फीति (Inflation) के नियंत्रण के लिए बनाई जाती है।",
  },
  {
    question_en: "What is the effect on interest rates in an Easy Monetary Policy?",
    question_hi: "सरल मौद्रिक नीति (Easy Monetary Policy) में ब्याज दरों पर क्या प्रभाव पड़ता है?",
    options_en: ["Interest rates increase", "Interest rates are reduced", "Interest rates remain unchanged", "Only CRR increases"],
    options_hi: ["ब्याज दरें बढ़ती हैं", "ब्याज दरों में कमी की जाती है", "ब्याज दरें अपरिवर्तित रहती हैं", "केवल CRR बढ़ता है"],
    correct_option_index: 1,
    explanation_en: "In an Easy Monetary Policy, interest rates are reduced, which increases liquidity.",
    explanation_hi: "सरल मौद्रिक नीति में ब्याज दरों में कमी की जाती है, जिससे तरलता बढ़ती है।",
  },
  {
    question_en: "What is the maximum period for which the RBI lends to commercial banks at the Repo Rate?",
    question_hi: "Repo Rate पर RBI वाणिज्यिक बैंकों को अधिकतम कितनी अवधि के लिए ऋण देता है?",
    options_en: ["Long term", "Overnight", "Short-term period (Maximum 14 Days)", "90 days"],
    options_hi: ["दीर्घकाल", "एक रात", "अल्पकालिक अवधि (Maximum 14 Days)", "90 दिन"],
    correct_option_index: 2,
    explanation_en: "At the Repo Rate, the RBI lends to commercial banks for a short-term period (maximum 14 days).",
    explanation_hi: "रेपो रेट पर RBI वाणिज्यिक बैंकों को अल्पकालिक अवधि (अधिकतम 14 दिन) के लिए ऋण देता है।",
  },
  {
    question_en: "Under Open Market Operations (OMO), what should the RBI do with Government Securities (G-Sec) to increase liquidity?",
    question_hi: "खुले बाज़ार की क्रियाओं (OMO) के तहत, तरलता बढ़ाने के लिए RBI को सरकारी प्रतिभूतियाँ (G-Sec) क्या करनी चाहिए?",
    options_en: ["Sell (Sale)", "Buy (Buy)", "Keep unchanged", "Increase the interest rate"],
    options_hi: ["बेचनी चाहिए (Sale)", "खरीदनी चाहिए (Buy)", "अपरिवर्तित रखनी चाहिए", "ब्याज दर बढ़ानी चाहिए"],
    correct_option_index: 1,
    explanation_en: "To increase liquidity, the RBI buys G-Secs.",
    explanation_hi: "तरलता बढ़ाने के लिए RBI G-Sec को खरीदती है।",
  },
  {
    question_en: "What is the effect on the economy's liquidity when the Bank Rate increases?",
    question_hi: "बैंक दर (Bank Rate) में वृद्धि से अर्थव्यवस्था की तरलता पर क्या प्रभाव पड़ता है?",
    options_en: ["Liquidity increases", "Liquidity decreases", "No effect", "Only CRR is affected"],
    options_hi: ["तरलता बढ़ती है", "तरलता घटती है", "कोई प्रभाव नहीं पड़ता", "केवल CRR पर प्रभाव पड़ता है"],
    correct_option_index: 1,
    explanation_en: "When the Bank Rate increases, borrowing becomes expensive, which decreases liquidity.",
    explanation_hi: "बैंक दर बढ़ने पर, ऋण लेना महंगा हो जाता है, जिससे तरलता घट जाती है।",
  },
  {
    question_en: "What do commercial banks receive on the money deposited with the RBI under CRR (Cash Reserve Ratio)?",
    question_hi: "CRR (नकद आरक्षित अनुपात) पर वाणिज्यिक बैंकों को जमा किए गए धन पर क्या मिलता है?",
    options_en: ["High interest rate from RBI", "Only government interest", "No interest is received", "Interest equal to the Repo Rate"],
    options_hi: ["RBI से उच्च ब्याज दर", "केवल सरकारी ब्याज", "कोई ब्याज नहीं मिलता", "रेपो रेट के बराबर ब्याज"],
    correct_option_index: 2,
    explanation_en: "Commercial banks do not receive any interest on CRR deposits.",
    explanation_hi: "CRR जमा पर वाणिज्यिक बैंकों को कोई ब्याज नहीं मिलता है।",
  },
  {
    question_en: "For what period do commercial banks borrow from the RBI at the MSF (Marginal Standing Facility Rate)?",
    question_hi: "MSF (सीमांत स्थायी सुविधा दर) पर वाणिज्यिक बैंक किस अवधि के लिए RBI से ऋण लेते हैं?",
    options_en: ["14 days", "90 days", "Overnight", "Long term"],
    options_hi: ["14 दिन", "90 दिन", "एक रात (Overnight)", "दीर्घकाल"],
    correct_option_index: 2,
    explanation_en: "Commercial banks borrow from the RBI at the MSF rate for an overnight period.",
    explanation_hi: "MSF दर पर वाणिज्यिक बैंक एक रात की अवधि के लिए RBI से ऋण लेते हैं।",
  },
  {
    question_en: "In SDF (Standing Deposit Facility), how do commercial banks deposit their excess liquidity with the RBI?",
    question_hi: "SDF (स्थायी जमा सुविधा) में वाणिज्यिक बैंक अपनी अतिरिक्त तरलता को RBI के पास कैसे जमा करते हैं?",
    options_en: ["At a high interest rate", "Against government securities", "Without collateral", "Only for one week"],
    options_hi: ["उच्च ब्याज दर पर", "सरकारी प्रतिभूतियों के बदले", "बिना ज़मानत के", "केवल एक सप्ताह के लिए"],
    correct_option_index: 2,
    explanation_en: "In SDF, banks deposit their excess liquidity with the RBI without collateral.",
    explanation_hi: "SDF में बैंक अतिरिक्त तरलता को RBI के पास बिना ज़मानत के जमा करते हैं।",
  },
  {
    question_en: "In Marginal Requirement, what is the relation between the value of the collateral property and the sanctioned loan?",
    question_hi: "सींमात आवश्यकता (Marginal Requirement) में जमानत संपत्ति का मूल्य स्वीकृत ऋण से कैसा होता है?",
    options_en: ["Equal", "Less", "More", "Unchanged"],
    options_hi: ["बराबर", "कम", "अधिक", "अपरिवर्तित"],
    correct_option_index: 2,
    explanation_en: "In Marginal Requirement, the value of the collateral property is more than the sanctioned loan.",
    explanation_hi: "सींमात आवश्यकता में, जमानत संपत्ति का मूल्य स्वीकृत ऋण से अधिक होता है।",
  },
  {
    question_en: "Under Direct Action, what action can the RBI take against commercial banks?",
    question_hi: "प्रत्यक्ष कार्यवाही (Direct Action) के तहत RBI वाणिज्यिक बैंकों पर कौन सी कार्यवाही कर सकता है?",
    options_en: ["Only exert moral suasion", "Fixing loan limits", "Imposing penalties or revoking the license", "Only increasing the security deposit"],
    options_hi: ["केवल नैतिक दबाव डालना", "ऋण सीमा निर्धारित करना", "पेनल्टी लगाना या लाइसेंस रद्द करना", "केवल जमानत राशि बढ़ाना"],
    correct_option_index: 2,
    explanation_en: "In Direct Action, the RBI can impose penalties on commercial banks or revoke their license.",
    explanation_hi: "प्रत्यक्ष कार्यवाही में RBI वाणिज्यिक बैंकों पर पेनल्टी लगा सकता है या लाइसेंस रद्द कर सकता है।",
  },
  {
    question_en: "NDTL is obtained by subtracting IBL from GDTL. What is the full form of IBL?",
    question_hi: "GDTL से IBL को घटाने पर NDTL प्राप्त होता है। IBL का पूर्ण रूप क्या है?",
    options_en: ["Net Demand and Time Liabilities", "Gross Demand and Time Liabilities", "Inter-Banking Liabilities", "Internal Banking Loan"],
    options_hi: ["नेट डिमांड एंड टाइम लायबिलिटीज", "ग्रॉस डिमांड एंड टाइम लायबिलिटीज", "इंटर-बैंकिंग लायबिलिटीज", "इंटरनल बैंकिंग लोन"],
    correct_option_index: 2,
    explanation_en: "IBL stands for Inter-Banking Liabilities.",
    explanation_hi: "IBL का अर्थ इंटर-बैंकिंग लायबिलिटीज है।",
  },
  {
    question_en: "A bank in which the Government of India's shareholding is 51% or more is called a?",
    question_hi: "जिस बैंक में भारत सरकार की हिस्सेदारी 51% या उससे अधिक होती है, उसे क्या कहा जाता है?",
    options_en: ["Co-operative Bank", "Private Bank", "Nationalized Bank", "Foreign Bank"],
    options_hi: ["सहकारी बैंक", "निजी बैंक", "राष्ट्रीयकृत बैंक", "विदेशी बैंक"],
    correct_option_index: 2,
    explanation_en: "A bank with 51% or more shareholding of the Government of India is called a Nationalized Bank.",
    explanation_hi: "भारत सरकार की 51% या उससे अधिक हिस्सेदारी वाला बैंक राष्ट्रीयकृत बैंक कहलाता है।",
  },
  {
    question_en: "In which year was the SBI (State Bank of India) nationalized?",
    question_hi: "SBI (स्टेट बैंक ऑफ इंडिया) का राष्ट्रीयकरण किस वर्ष हुआ था?",
    options_en: ["January 1, 1949", "July 1, 1955", "July 19, 1969", "April 15, 1980"],
    options_hi: ["1 जनवरी 1949", "1 जुलाई 1955", "19 जुलाई 1969", "15 अप्रैल 1980"],
    correct_option_index: 1,
    explanation_en: "SBI was nationalized on July 1, 1955.",
    explanation_hi: "SBI का राष्ट्रीयकरण 1 जुलाई 1955 को हुआ।",
  },
  {
    question_en: "Who was the RBI Governor during the second phase of commercial bank nationalization (April 15, 1980)?",
    question_hi: "वाणिज्यिक बैंकों के राष्ट्रीयकरण के दूसरे चरण (15 अप्रैल 1980) में RBI गवर्नर कौन थे?",
    options_en: ["Lakshmikant Jha", "I.G. Patel", "C.D. Deshmukh", "Shaktikanta Das"],
    options_hi: ["लक्ष्मीकांत झा", "आई.जी. पटेल (I.G. Patel)", "सी.डी. देशमुख", "शक्तिकांत दास"],
    correct_option_index: 1,
    explanation_en: "I.G. Patel was the RBI Governor during the second phase.",
    explanation_hi: "दूसरे चरण में RBI गवर्नर आई.जी. पटेल थे।",
  },
  {
    question_en: "In which year was the Bank of India (BOI) established?",
    question_hi: "बैंक ऑफ इंडिया (BOI) की स्थापना किस वर्ष हुई थी?",
    options_en: ["1894", "1906", "1908", "1911"],
    options_hi: ["1894", "1906", "1908", "1911"],
    correct_option_index: 1,
    explanation_en: "The Bank of India was established in 1906 in Mumbai.",
    explanation_hi: "बैंक ऑफ इंडिया की स्थापना 1906 में मुंबई में हुई थी।",
  },
  {
    question_en: "In which year was the Central Bank of India established?",
    question_hi: "सेंट्रल बैंक ऑफ इंडिया की स्थापना किस वर्ष हुई थी?",
    options_en: ["1906", "1908", "1911", "1919"],
    options_hi: ["1906", "1908", "1911", "1919"],
    correct_option_index: 2,
    explanation_en: "The Central Bank of India was established in 1911 in Mumbai.",
    explanation_hi: "सेंट्रल बैंक ऑफ इंडिया की स्थापना 1911 में मुंबई में हुई थी।",
  },
  {
    question_en: "In which year and where was the Indian Overseas Bank (IOB) established?",
    question_hi: "इंडियन ओवरसीज बैंक (IOB) की स्थापना किस वर्ष और कहाँ हुई थी?",
    options_en: ["1907, Chennai", "1911, Mumbai", "1937, Chennai", "1938, Mumbai"],
    options_hi: ["1907, चेन्नई", "1911, मुंबई", "1937, चेन्नई", "1938, मुंबई"],
    correct_option_index: 2,
    explanation_en: "The Indian Overseas Bank was established in 1937 in Chennai.",
    explanation_hi: "इंडियन ओवरसीज बैंक की स्थापना 1937 में चेन्नई में हुई थी।",
  },
  {
    question_en: "In which year and where was the Bank of Maharashtra established?",
    question_hi: "बैंक ऑफ महाराष्ट्र की स्थापना किस वर्ष और कहाँ हुई थी?",
    options_en: ["1906, Bengaluru", "1937, Chennai", "1938, Mumbai", "1935, Pune"],
    options_hi: ["1906, बंगलुरु", "1937, चेन्नई", "1938, मुंबई", "1935, पुणे"],
    correct_option_index: 3,
    explanation_en: "The Bank of Maharashtra was established in 1935 in Pune.",
    explanation_hi: "बैंक ऑफ महाराष्ट्र की स्थापना 1935 में पुणे में हुई थी।",
  },
  {
    question_en: "With which bank did Allahabad Bank merge?",
    question_hi: "इलाहाबाद बैंक का विलय किस बैंक के साथ हुआ?",
    options_en: ["Canara Bank", "Bank of Baroda (BOB)", "Indian Bank", "Syndicate Bank"],
    options_hi: ["केनरा बैंक", "बैंक ऑफ बड़ौदा (BOB)", "इंडियन बैंक", "सिंडिकेट बैंक"],
    correct_option_index: 2,
    explanation_en: "Allahabad Bank merged with Indian Bank.",
    explanation_hi: "इलाहाबाद बैंक का विलय इंडियन बैंक में हुआ।",
  },
  {
    question_en: "On which date was NABARD established?",
    question_hi: "NABARD की स्थापना किस तिथि को हुई?",
    options_en: ["January 1, 1982", "July 12, 1982", "July 9, 1988", "April 2, 1990"],
    options_hi: ["1 जनवरी 1982", "12 जुलाई 1982", "9 जुलाई 1988", "2 अप्रैल 1990"],
    correct_option_index: 1,
    explanation_en: "NABARD (National Bank for Agriculture and Rural Development) was established on July 12, 1982.",
    explanation_hi: "NABARD (नेशनल बैंक फॉर एग्रीकल्चर एंड रूरल डेवलपमेंट) की स्थापना 12 जुलाई 1982 को हुई।",
  },
  {
    question_en: "What is the main function of SIDBI?",
    question_hi: "SIDBI का मुख्य कार्य क्या है?",
    options_en: ["Financing agriculture and rural areas", "Promoting foreign trade", "Developing small industries", "Providing housing facilities"],
    options_hi: ["कृषि एवं ग्रामीण क्षेत्रों को वित्त देना", "विदेशी व्यापार बढ़ाना", "लघु उद्योगों का विकास करना", "आवासीय सुविधा प्रदान करना"],
    correct_option_index: 2,
    explanation_en: "The function of SIDBI (Small Industries Development Bank of India) is the development of small industries.",
    explanation_hi: "SIDBI (स्मॉल इंडस्ट्रीज डेवलपमेंट बैंक ऑफ इंडिया) का कार्य लघु उद्योगों का विकास करना है।",
  },
  {
    question_en: "In which year was the EXIM Bank established?",
    question_hi: "EXIM Bank की स्थापना किस वर्ष हुई थी?",
    options_en: ["1964", "1988", "January 1, 1982", "April 2, 1990"],
    options_hi: ["1964", "1988", "1 जनवरी 1982", "2 अप्रैल 1990"],
    correct_option_index: 2,
    explanation_en: "EXIM Bank was established on January 1, 1982.",
    explanation_hi: "EXIM Bank की स्थापना 1 जनवरी 1982 को हुई।",
  },
  {
    question_en: "Where is the headquarters of NHB (National Housing Bank) located?",
    question_hi: "NHB (नेशनल हाउसिंग बैंक) का मुख्यालय कहाँ स्थित है?",
    options_en: ["Mumbai", "Lucknow", "New Delhi", "Chennai"],
    options_hi: ["मुंबई", "लखनऊ", "नई दिल्ली", "चेन्नई"],
    correct_option_index: 2,
    explanation_en: "The headquarters of NHB is located in New Delhi.",
    explanation_hi: "NHB का मुख्यालय नई दिल्ली में स्थित है।",
  },
  {
    question_en: "When was the Ordinance for the establishment of RRB (Regional Rural Bank) issued?",
    question_hi: "RRB (क्षेत्रीय ग्रामीण बैंक) की स्थापना के लिए अध्यादेश (Ordinance) कब जारी किया गया था?",
    options_en: ["October 2, 1975", "September 26, 1975", "RRB Act 1976", "July 12, 1982"],
    options_hi: ["2 अक्टूबर 1975", "26 सितंबर 1975", "RRB Act 1976", "12 जुलाई 1982"],
    correct_option_index: 1,
    explanation_en: "The Ordinance for the establishment of RRB was issued on September 26, 1975.",
    explanation_hi: "RRB की स्थापना के लिए अध्यादेश 26 सितंबर 1975 को जारी किया गया था।",
  },
  {
    question_en: "Which of the 5 RRBs established on October 2, 1975, was set up in Rajasthan (RJ)?",
    question_hi: "2 अक्टूबर 1975 को स्थापित 5 RRBs में से कौन सा बैंक राजस्थान (RJ) में स्थापित हुआ था?",
    options_en: ["Prathama Gramin Bank (UP)", "West Bengal - Malda", "Haryana - Bhiwani", "Jaipur Gramin Bank (RJ)"],
    options_hi: ["प्रथमा ग्रामीण बैंक (UP)", "पश्चिम बंगाल - माल्दा", "हरियाणा - भिवानी", "जयपुर ग्रामीण बैंक (RJ)"],
    correct_option_index: 3,
    explanation_en: "Jaipur Gramin Bank was established in Rajasthan on October 2, 1975.",
    explanation_hi: "राजस्थान में जयपुर ग्रामीण बैंक 2 अक्टूबर 1975 को स्थापित हुआ था।",
  },
  {
    question_en: "From which country was the concept of Five-Year Plans adopted in India?",
    question_hi: "भारत में पंचवर्षीय योजनाओं की अवधारणा किस देश से ली गई?",
    options_en: ["USA", "Germany", "Soviet Union (USSR)", "Japan"],
    options_hi: ["USA", "जर्मनी", "सोवियत संघ (USSR)", "जापान"],
    correct_option_index: 2,
    explanation_en: "The concept of Five-Year Plans originated from the Soviet Union (USSR).",
    explanation_hi: "पंचवर्षीय योजनाओं की अवधारणा सोवियत संघ (USSR) की देन है।",
  },
  {
    question_en: "What was the achievement rate of the First Five-Year Plan (1951-56)?",
    question_hi: "पहली पंचवर्षीय योजना (1951-56) का प्राप्ति (Achieve) दर क्या थी?",
    options_en: ["2.1% (Target)", "4.34%", "3.6%", "5.6%"],
    options_hi: ["2.1% (लक्ष्य)", "4.34%", "3.6%", "5.6%"],
    correct_option_index: 2,
    explanation_en: "The target of the first plan was 2.1%, while the achievement was 3.6%.",
    explanation_hi: "पहली योजना का लक्ष्य 2.1% था, जबकि प्राप्ति 3.6% हुई।",
  },
  {
    question_en: "In which year did the Industrial Policy come during the Second Five-Year Plan (1956-61)?",
    question_hi: "दूसरी पंचवर्षीय योजना (1956-61) में औद्योगिक नीति किस वर्ष आई?",
    options_en: ["1951", "1956", "1961", "1965"],
    options_hi: ["1951", "1956", "1961", "1965"],
    correct_option_index: 1,
    explanation_en: "The Industrial Policy of 1956 came during the Second Five-Year Plan.",
    explanation_hi: "औद्योगिक नीति 1956 दूसरी पंचवर्षीय योजना के दौरान आई।",
  },
  {
    question_en: "Which country cooperated in the establishment of the Rourkela (Odisha) Iron and Steel Industry?",
    question_hi: "राउरकेला (ओडिशा) लौह इस्पात उद्योग की स्थापना में किस देश का सहयोग मिला था?",
    options_en: ["Russia", "Britain", "Germany", "USA"],
    options_hi: ["रूस", "ब्रिटेन", "जर्मनी", "USA"],
    correct_option_index: 2,
    explanation_en: "Rourkela (Odisha) received cooperation from Germany.",
    explanation_hi: "राउरकेला (ओडिशा) को जर्मनी का सहयोग मिला था।",
  },
  {
    question_en: "Why was the achievement rate of the Third Five-Year Plan (1961-66) much lower than the target?",
    question_hi: "तीसरी पंचवर्षीय योजना (1961-66) की प्राप्ति दर लक्ष्य (Target) से बहुत कम क्यों थी?",
    options_en: ["1971 Indo-Pak War", "Implementation of LPG policy", "1962 China War, 1965 Pak War, Famine", "Nationalization of banks"],
    options_hi: ["1971 का पाक युद्ध", "LPG नीति का लागू होना", "1962 चीन युद्ध, 1965 पाक युद्ध, अकाल", "बैंकों का राष्ट्रीयकरण"],
    correct_option_index: 2,
    explanation_en: "The third plan failed due to the 1962 China War, 1965 Pak War, and famine.",
    explanation_hi: "तीसरी योजना 1962 चीन युद्ध और 1965 पाक युद्ध एवं अकाल के कारण असफल रही।",
  },
  {
    question_en: "In which year did Operation Flood start?",
    question_hi: "ऑपरेशन फ्लड (Operation Flood) किस वर्ष शुरू हुआ था?",
    options_en: ["1965", "1970", "1974", "1978"],
    options_hi: ["1965", "1970", "1974", "1978"],
    correct_option_index: 1,
    explanation_en: "Operation Flood started in 1970.",
    explanation_hi: "ऑपरेशन फ्लड 1970 में शुरू हुआ था।",
  },
  {
    question_en: "The Family Planning Programme (FPP) started during which plan?",
    question_hi: "परिवार नियोजन कार्यक्रम (FPP) किस योजना के दौरान शुरू हुआ?",
    options_en: ["Plan Holiday", "Fourth Five-Year Plan", "Fifth Five-Year Plan", "Sixth Five-Year Plan"],
    options_hi: ["योजना अवकाश", "चौथी पंचवर्षीय योजना", "पाँचवीं पंचवर्षीय योजना", "छठी पंचवर्षीय योजना"],
    correct_option_index: 1,
    explanation_en: "The Family Planning Programme (FPP) started during the Fourth Five-Year Plan (1969-74).",
    explanation_hi: "परिवार नियोजन कार्यक्रम (FPP) चौथी पंचवर्षीय योजना (1969-74) के दौरान शुरू हुआ।",
  },
  {
    question_en: "What was the model of the Fifth Five-Year Plan (1974-78)?",
    question_hi: "पाँचवीं पंचवर्षीय योजना (1974-78) का मॉडल क्या था?",
    options_en: ["Harrod-Domar Model", "Nehru-Mahalanobis Model", "D.P. Dhar Model", "Gadgil Model"],
    options_hi: ["हैरोड-डोमर मॉडल", "नेहरू-महालनोबिस मॉडल", "डी.पी. धर मॉडल", "गाडगिल मॉडल"],
    correct_option_index: 2,
    explanation_en: "The model of the Fifth Plan was the D.P. Dhar Model.",
    explanation_hi: "पाँचवीं योजना का मॉडल डी.पी. धर मॉडल था।",
  },
  {
    question_en: "The Rolling Plan was based on the model of which economist?",
    question_hi: "रोलिंग प्लान किस अर्थशास्त्री के मॉडल पर आधारित थी?",
    options_en: ["D.P. Dhar", "Gunnar Myrdal", "Ashok Rudra", "K.N. Rao"],
    options_hi: ["डी.पी. धर", "गुन्नार मिर्डल", "अशोक रुद्र", "के.एन. राव"],
    correct_option_index: 1,
    explanation_en: "The Rolling Plan was based on the Gunnar Myrdal Model.",
    explanation_hi: "रोलिंग प्लान गुन्नार मिर्डल मॉडल पर आधारित थी।",
  },
  {
    question_en: "What was the main objective of the Seventh Five-Year Plan (1985-90)?",
    question_hi: "सातवीं पंचवर्षीय योजना (1985-90) का मुख्य उद्देश्य क्या था?",
    options_en: ["Self-reliance", "Increase in food grain production, reduction of poverty and unemployment", "Development of heavy industries", "Only modernization"],
    options_hi: ["आत्मनिर्भरता", "खाद्यान्न उत्पादन में वृद्धि, गरीबी और बेरोजगारी कम करना", "भारी उद्योगों का विकास", "केवल आधुनिकीकरण"],
    correct_option_index: 1,
    explanation_en: "The objective of the Seventh Plan was to increase food grain production and reduce poverty and unemployment.",
    explanation_hi: "सातवीं योजना का उद्देश्य खाद्यान्न उत्पादन में वृद्धि, गरीबी और बेरोजगारी कम करना था।",
  },
  {
    question_en: "In which year was the Consumer Protection Act implemented?",
    question_hi: "उपभोक्ता संरक्षण अधिनियम (Consumer Protection Act) किस वर्ष लागू हुआ?",
    options_en: ["1980", "1986", "1989", "1991"],
    options_hi: ["1980", "1986", "1989", "1991"],
    correct_option_index: 1,
    explanation_en: "The Consumer Protection Act was implemented in 1986.",
    explanation_hi: "उपभोक्ता संरक्षण अधिनियम 1986 में लागू हुआ।",
  },
  {
    question_en: "What was the main reason for implementing the Annual Plans (1990-92)?",
    question_hi: "वार्षिक योजनाएँ (1990-92) लागू करने का मुख्य कारण क्या था?",
    options_en: ["Drought and famine", "Problem of balance of payments and decline in foreign exchange reserves", "Nationalization of banks", "Implementation of LPG policy"],
    options_hi: ["सूखा और अकाल", "भुगतान संतुलन की समस्या और विदेशी मुद्रा भंडार में कमी", "बैंकों का राष्ट्रीयकरण", "LPG नीति का लागू होना"],
    correct_option_index: 1,
    explanation_en: "The Annual Plans were adopted due to the problem of balance of payments and the decline in foreign exchange reserves.",
    explanation_hi: "वार्षिक योजनाएँ भुगतान संतुलन की समस्या और विदेशी मुद्रा भंडार में कमी के कारण अपनाई गईं।",
  },
  {
    question_en: "In which Five-Year Plan was the New Economic Policy (NEP) 1991 implemented for the first time?",
    question_hi: "नई आर्थिक नीति (NEP) 1991 पहली बार किस पंचवर्षीय योजना में लागू हुई?",
    options_en: ["Seventh Plan", "Eighth Plan (1992-97)", "Ninth Plan", "Tenth Plan"],
    options_hi: ["सातवीं योजना", "आठवीं योजना (1992-97)", "नौवीं योजना", "दसवीं योजना"],
    correct_option_index: 1,
    explanation_en: "The Eighth Five-Year Plan was implemented after the NEP 1991.",
    explanation_hi: "NEP 1991 के बाद आठवीं पंचवर्षीय योजना लागू हुई।",
  },
  {
    question_en: "In which year was the Sarva Shiksha Abhiyan (SSA) launched?",
    question_hi: "सर्व शिक्षा अभियान (SSA) किस वर्ष शुरू हुआ?",
    options_en: ["1999", "2000", "2001", "2004"],
    options_hi: ["1999", "2000", "2001", "2004"],
    correct_option_index: 2,
    explanation_en: "Sarva Shiksha Abhiyan was launched in 2001.",
    explanation_hi: "सर्व शिक्षा अभियान 2001 में शुरू हुआ।",
  },
  {
    question_en: "What was the model of the 11th Five-Year Plan (2007-2012)?",
    question_hi: "11वीं पंचवर्षीय योजना (2007-2012) का मॉडल क्या था?",
    options_en: ["D.P. Dhar Model", "Mahalanobis Model", "C. Rangarajan Model", "Ashok Rudra Model"],
    options_hi: ["डी.पी. धर मॉडल", "महालनोबिस मॉडल", "सी. रंगराजन मॉडल", "अशोक रुद्र मॉडल"],
    correct_option_index: 2,
    explanation_en: "The model of the 11th plan was the C. Rangarajan Model.",
    explanation_hi: "11वीं योजना का मॉडल सी. रंगराजन मॉडल था।",
  },
  {
    question_en: "In which year was the NFSA (National Food Security Act) implemented?",
    question_hi: "NFSA (राष्ट्रीय खाद्य सुरक्षा अधिनियम) किस वर्ष लागू हुआ?",
    options_en: ["2012", "2013", "2014", "2015"],
    options_hi: ["2012", "2013", "2014", "2015"],
    correct_option_index: 1,
    explanation_en: "NFSA was implemented in 2013 during the 12th plan.",
    explanation_hi: "NFSA 2013 में 12वीं योजना के दौरान लागू हुआ।",
  },
  {
    question_en: "What was the name of the book by Dadabhai Naoroji, who first estimated the national income (1867-68)?",
    question_hi: "राष्ट्रीय आय का सर्वप्रथम अनुमान (1867-68) लगाने वाले दादा भाई नौरोजी की पुस्तक का नाम क्या था?",
    options_en: ["Wealth of Nations", "Das Capital", "The Poverty and Un-British Rule in India", "Theory of Employment"],
    options_hi: ["वेल्थ ऑफ नेशंस", "दास कैपिटल", "द पॉवर्टी एंड अन-ब्रिटिश रूल इन इंडिया", "थ्योरी ऑफ एम्प्लॉयमेंट"],
    correct_option_index: 2,
    explanation_en: "The name of Dadabhai Naoroji's book was 'The Poverty and Un-British Rule in India'.",
    explanation_hi: "दादा भाई नौरोजी की पुस्तक का नाम 'द पॉवर्टी एंड अन-ब्रिटिश रूल इन इंडिया' था।",
  },
  {
    question_en: "What is the other name for the Product Method?",
    question_hi: "उत्पाद विधि (Product Method) का दूसरा नाम क्या है?",
    options_en: ["Expenditure Method", "Factor Income Method", "Value Added Method", "Net National Product Method"],
    options_hi: ["व्यय विधि", "कारक आय विधि", "मूल्य वर्धन विधि", "शुद्ध राष्ट्रीय उत्पाद विधि"],
    correct_option_index: 2,
    explanation_en: "The Product Method is also called the Value Added Method.",
    explanation_hi: "उत्पाद विधि को मूल्य वर्धन विधि भी कहा जाता है।",
  },
  {
    question_en: "In the Factor Income Method, what is received in return for Land?",
    question_hi: "कारक आय विधि में भूमि (Land) के बदले क्या प्राप्त होता है?",
    options_en: ["Salary", "Profit", "Interest", "Rent or Lagan"],
    options_hi: ["वेतन", "लाभ", "ब्याज", "किराया या लगान"],
    correct_option_index: 3,
    explanation_en: "In the Factor Income Method, Rent or Lagan is received in return for Land.",
    explanation_hi: "कारक आय विधि में भूमि के बदले किराया (Rent) या लगान प्राप्त होता है।",
  },
  {
    question_en: "Which year's data is used in the calculation of Real GDP?",
    question_hi: "Real GDP (वास्तविक जीडीपी) की गणना में किस वर्ष के आंकड़े प्रयोग होते हैं?",
    options_en: ["Current financial year", "Base Year (Base Year = 2011-12)", "Previous financial year", "2004-05"],
    options_hi: ["चालू वित्तीय वर्ष", "आधार वर्ष (Base Year = 2011-12)", "पिछला वित्तीय वर्ष", "2004-05"],
    correct_option_index: 1,
    explanation_en: "The Base Year (2011-12) data is used in the calculation of Real GDP.",
    explanation_hi: "वास्तविक जीडीपी की गणना में आधार वर्ष (2011-12) का प्रयोग किया जाता है।",
  },
  {
    question_en: "Which year's data is taken in the calculation of Nominal GDP?",
    question_hi: "Nominal GDP (मौद्रिक जीडीपी) की गणना में किस वर्ष का आंकड़ा लिया जाता है?",
    options_en: ["Base year", "Current Financial Year", "Previous financial year", "1999-2000"],
    options_hi: ["आधार वर्ष", "चालू वित्तीय वर्ष (Current Financial Year)", "पिछला वित्तीय वर्ष", "1999-2000"],
    correct_option_index: 1,
    explanation_en: "The current financial year's data is taken in the calculation of Nominal GDP.",
    explanation_hi: "मौद्रिक जीडीपी की गणना में चालू वित्तीय वर्ष का आंकड़ा लिया जाता है।",
  },
  {
    question_en: "Which ministry calculates Depreciation?",
    question_hi: "मूल्य ह्रास (Depreciation) की गणना कौन सा मंत्रालय करता है?",
    options_en: ["Ministry of Finance", "NSO", "Ministry of Commerce and Industry", "RBI"],
    options_hi: ["वित्त मंत्रालय", "NSO", "व्यापार वाणिज्य मंत्रालय", "RBI"],
    correct_option_index: 2,
    explanation_en: "Depreciation is calculated by the Ministry of Commerce and Industry.",
    explanation_hi: "मूल्य ह्रास की गणना व्यापार वाणिज्य मंत्रालय द्वारा की जाती है।",
  },
  {
    question_en: "What is the formula for GNP (Gross National Product)?",
    question_hi: "GNP (सकल राष्ट्रीय उत्पाद) का सूत्र क्या है?",
    options_en: ["GDP - Depreciation", "NDP + Depreciation", "GDP + Net Factor Income from Abroad", "NNP + Income from Abroad"],
    options_hi: ["GDP - मूल्य ह्रास", "NDP + मूल्य ह्रास", "GDP + विदेशों से प्राप्त शुद्ध कारक आय", "NNP + विदेशों से प्राप्त आय"],
    correct_option_index: 2,
    explanation_en: "GNP = GDP + Net Factor Income from Abroad.",
    explanation_hi: "GNP = GDP + विदेशों से प्राप्त शुद्ध कारक आय।",
  },
  {
    question_en: "Which item is not included in the calculation of National Income?",
    question_hi: "राष्ट्रीय आय की गणना में कौन सी मद शामिल नहीं होती है?",
    options_en: ["Salary", "Profit", "Rent", "Transfer Payments (pension, unemployment allowance)"],
    options_hi: ["वेतन", "लाभ", "किराया", "हस्तांतरण भुगतान (पेंशन, बेरोजगारी भत्ता)"],
    correct_option_index: 3,
    explanation_en: "Transfer Payments (like pension, unemployment allowance, lottery) are not included in the national income.",
    explanation_hi: "हस्तांतरण भुगतान (जैसे पेंशन, बेरोजगारी भत्ता, लॉटरी) राष्ट्रीय आय में शामिल नहीं होते हैं।",
  },
  {
    question_en: "When was NSO (National Statistical Office) established?",
    question_hi: "NSO (राष्ट्रीय सांख्यिकी कार्यालय) की स्थापना कब हुई थी?",
    options_en: ["March 15, 1950", "January 1, 2015", "May 23, 2019 (Merger of CSO + NSSO)", "1991"],
    options_hi: ["15 मार्च 1950", "1 जनवरी 2015", "23 मई 2019 (CSO + NSSO का विलय)", "1991"],
    correct_option_index: 2,
    explanation_en: "NSO was established on May 23, 2019, through the merger of CSO and NSSO.",
    explanation_hi: "NSO की स्थापना 23 मई 2019 को CSO और NSSO के विलय से हुई।",
  },
  {
    question_en: "The term Hindu Growth Rate (HGIR) was related to which rate?",
    question_hi: "Hindu Growth Rate (HGIR) शब्द किस दर से संबंधित था?",
    options_en: ["Inflation rate", "Population rate", "National Income (GDP) growth rate (3.5%)", "Agricultural growth rate"],
    options_hi: ["मुद्रास्फीति दर", "जनसंख्या दर", "राष्ट्रीय आय (GDP) विकास दर (3.5%)", "कृषि विकास दर"],
    correct_option_index: 2,
    explanation_en: "HGIR was related to the National Income (GDP) growth rate (3.5%).",
    explanation_hi: "HGIR का संबंध राष्ट्रीय आय (GDP) विकास दर (3.5%) से है।",
  },
  {
    question_en: "The word 'Budget' comes from the French word 'bougette', which means what?",
    question_hi: "बजट शब्द फ्रांसीसी शब्द 'बुगेट' से बना है, जिसका अर्थ क्या है?",
    options_en: ["Financial statement", "Annual expenditure", "Leather Bag", "Source of income"],
    options_hi: ["वित्तीय विवरण", "वार्षिक व्यय", "चमड़े का थैला (Leather Bag)", "आय का स्रोत"],
    correct_option_index: 2,
    explanation_en: "Budget comes from the French word 'bougette', which means 'Leather Bag'.",
    explanation_hi: "बजट फ्रांसीसी शब्द 'बुगेट' से बना है, जिसका अर्थ 'चमड़े का थैला' है।",
  },
  {
    question_en: "Who is called the Father of the Indian Budget?",
    question_hi: "भारत में भारतीय बजट का जनक किसे कहा जाता है?",
    options_en: ["R.K. Shanmukham Chetty", "John Mathai", "James Wilson (1860)", "C.D. Deshmukh"],
    options_hi: ["आर.के. षणमुखम चेट्टी", "जॉन मथाई", "जेम्स विल्सन (1860)", "सी.डी. देशमुख"],
    correct_option_index: 2,
    explanation_en: "James Wilson is called the Father of the Indian Budget.",
    explanation_hi: "भारतीय बजट का जनक जेम्स विल्सन को कहा जाता है।",
  },
  {
    question_en: "The Annual Financial Statement for the central government is mentioned in which article of the Constitution?",
    question_hi: "केंद्र सरकार के लिए वार्षिक वित्तीय विवरण का उल्लेख संविधान के किस अनुच्छेद में है?",
    options_en: ["Article 280", "Article 202", "Article 112", "Article 300A"],
    options_hi: ["अनुच्छेद 280", "अनुच्छेद 202", "अनुच्छेद 112", "अनुच्छेद 300A"],
    correct_option_index: 2,
    explanation_en: "The central budget is mentioned in Article 112.",
    explanation_hi: "केंद्रीय बजट का उल्लेख अनुच्छेद 112 में है।",
  },
  {
    question_en: "The Economic Survey is prepared for which financial year?",
    question_hi: "आर्थिक सर्वेक्षण (Economic Survey) किस वित्तीय वर्ष के लिए तैयार किया जाता है?",
    options_en: ["Forthcoming financial year", "Previous financial year", "Current financial year", "5-year period"],
    options_hi: ["आगामी वित्तीय वर्ष", "पिछला वित्तीय वर्ष", "चालू वित्तीय वर्ष", "5 वर्ष की अवधि"],
    correct_option_index: 1,
    explanation_en: "The Economic Survey is prepared for the previous financial year.",
    explanation_hi: "आर्थिक सर्वेक्षण पिछले वित्तीय वर्ष के लिए तैयार किया जाता है।",
  },
  {
    question_en: "What is the government income called that neither reduces assets nor increases liability?",
    question_hi: "सरकार की वह आय जिससे न संपत्ति कम हो और न कर्ज (Liability) बढ़े, क्या कहलाती है?",
    options_en: ["Capital receipts", "Revenue receipts", "Revenue expenditure", "Capital expenditure"],
    options_hi: ["पूंजीगत आय", "राजस्व आय", "राजस्व व्यय", "पूंजीगत व्यय"],
    correct_option_index: 1,
    explanation_en: "Tax, penalties, and profit from PSUs are examples of revenue receipts.",
    explanation_hi: "कर, पेनल्टी, और PSU से मिलने वाला लाभ राजस्व आय के उदाहरण हैं।",
  },
  {
    question_en: "What is the government expenditure called that neither increases assets nor reduces liabilities?",
    question_hi: "सरकार का वह व्यय जिससे न संपत्ति में वृद्धि हो और न कर्ज में कमी हो, क्या कहलाता है?",
    options_en: ["Capital expenditure", "Capital receipts", "Revenue expenditure", "Revenue receipts"],
    options_hi: ["पूंजीगत व्यय", "पूंजीगत आय", "राजस्व व्यय", "राजस्व आय"],
    correct_option_index: 2,
    explanation_en: "Salaries, pensions, subsidies, and interest payments are revenue expenditures.",
    explanation_hi: "वेतन, पेंशन, सब्सिडी, ब्याज अदायगी राजस्व व्यय हैं।",
  },
  {
    question_en: "What is an example of Capital Expenditure?",
    question_hi: "पूंजीगत व्यय (Capital Expenditure) का उदाहरण क्या है?",
    options_en: ["Salaries, pension", "Payment of interest", "Construction of parks, buildings, airports, roads, etc.", "Subsidy"],
    options_hi: ["वेतन, पेंशन", "ब्याज की अदायगी", "पार्क, भवन, एयरपोर्ट, सड़क आदि का निर्माण", "सब्सिडी"],
    correct_option_index: 2,
    explanation_en: "Capital expenditure leads to an increase in assets.",
    explanation_hi: "पूंजीगत व्यय से संपत्ति में वृद्धि होती है।",
  },
  {
    question_en: "What is the condition of a Balanced Budget?",
    question_hi: "संतुलित बजट की स्थिति क्या है?",
    options_en: ["When total expenditure > total receipts", "When the government's total receipts equal total expenditure", "When total receipts > total expenditure", "When revenue deficit is zero"],
    options_hi: ["जब कुल व्यय > कुल आय हो", "जब सरकार की कुल आय (प्राप्ति) कुल व्यय के बराबर हो", "जब कुल आय > कुल व्यय हो", "जब राजस्व घाटा शून्य हो"],
    correct_option_index: 1,
    explanation_en: "A Balanced Budget occurs when total receipts equal total expenditure.",
    explanation_hi: "संतुलित बजट तब होता है जब कुल आय (प्राप्ति) कुल व्यय के बराबर होती है।",
  },
  {
    question_en: "What is the condition of Revenue Deficit?",
    question_hi: "राजस्व घाटा (Revenue Deficit) की स्थिति क्या है?",
    options_en: ["When total receipts > total expenditure", "When Revenue Expenditure (RE) is greater than Revenue Receipts (RI)", "When fiscal deficit is zero", "When primary deficit is zero"],
    options_hi: ["जब कुल आय > कुल व्यय हो", "जब राजस्व व्यय (RE) राजस्व आय (RI) से ज्यादा हो", "जब राजकोषीय घाटा शून्य हो", "जब प्राथमिक घाटा शून्य हो"],
    correct_option_index: 1,
    explanation_en: "Revenue Deficit occurs when Revenue Expenditure is greater than Revenue Receipts.",
    explanation_hi: "राजस्व घाटा तब होता है जब राजस्व व्यय, राजस्व आय से ज्यादा होता है।",
  },
  {
    question_en: "What is the formula for Fiscal Deficit?",
    question_hi: "राजकोषीय घाटा (Fiscal Deficit) का सूत्र क्या है?",
    options_en: ["Revenue Deficit - Interest payments", "Total Expenditure - Revenue Receipts", "Total Expenditure - Total Receipts", "Primary Deficit - Interest payments"],
    options_hi: ["राजस्व घाटा - ब्याज भुगतान", "कुल व्यय - राजस्व आय", "कुल व्यय - कुल आय", "प्राथमिक घाटा - ब्याज भुगतान"],
    correct_option_index: 2,
    explanation_en: "Fiscal Deficit = Total Expenditure - Total Receipts.",
    explanation_hi: "राजकोषीय घाटा = कुल व्यय - कुल आय।",
  },
  {
    question_en: "What does Monetary Deficit represent?",
    question_hi: "मौद्रिक घाटा (Monetary Deficit) क्या दर्शाता है?",
    options_en: ["Total internal borrowing", "Borrowing from RBI", "Borrowing from foreign organizations", "Borrowing from the public"],
    options_hi: ["कुल आंतरिक उधारी", "RBI से लिया गया उधार", "विदेशी संगठनों से लिया गया उधार", "जनता से लिया गया उधार"],
    correct_option_index: 1,
    explanation_en: "Monetary Deficit is the borrowing taken from the RBI.",
    explanation_hi: "मौद्रिक घाटा RBI से लिया गया उधार होता है।",
  },
  {
    question_en: "The Capital Market is regulated by whom?",
    question_hi: "पूंजी बाजार (Capital Market) किसके द्वारा विनियमित होता है?",
    options_en: ["RBI", "Ministry of Finance", "SEBI", "NSE"],
    options_hi: ["RBI", "वित्त मंत्रालय", "SEBI", "NSE"],
    correct_option_index: 2,
    explanation_en: "The Capital Market is regulated by SEBI.",
    explanation_hi: "पूंजी बाजार का विनियमन SEBI द्वारा किया जाता है।",
  },
  {
    question_en: "What is the main characteristic of the Primary Capital Market?",
    question_hi: "प्राथमिक पूंजी बाजार (Primary Capital Market) की मुख्य विशेषता क्या है?",
    options_en: ["Share transactions take place between investors", "There is a direct relationship between the company and the investor", "Only FPOs are issued", "Finance transactions are for 365 days or less"],
    options_hi: ["शेयर का लेन-देन निवेशकों के मध्य होता है", "कंपनी और निवेशक के मध्य सीधा संबंध होता है", "केवल FPO जारी होते हैं", "वित्त का लेन-देन 365 दिन या उससे कम होता है"],
    correct_option_index: 1,
    explanation_en: "In the primary market, there is a direct relationship between the company and the investor (e.g., IPO).",
    explanation_hi: "प्राथमिक बाजार में कंपनी और निवेशक के मध्य सीधा संबंध होता है (जैसे IPO)।",
  },
  {
    question_en: "When is an IPO (Initial Public Offer) issued?",
    question_hi: "IPO (Initial Public Offer) कब जारी किया जाता है?",
    options_en: ["When the company collects additional finance", "When a company issues shares for the first time to collect finance", "Selling government securities", "Share transactions taking place between investors"],
    options_hi: ["जब कंपनी अतिरिक्त वित्त संग्रहित करती है", "जब कोई कंपनी पहली बार वित्त संग्रहित करने के लिए शेयर जारी करती है", "सरकारी प्रतिभूतियां बेचना", "शेयर का लेन-देन निवेशकों के मध्य होना"],
    correct_option_index: 1,
    explanation_en: "An IPO is issued when a company issues shares for the first time to collect finance.",
    explanation_hi: "IPO तब जारी होता है जब कंपनी पहली बार वित्त संग्रहित करने के लिए शेयर जारी करती है।",
  }
];


export default test9Questions;