import type { QuizQuestion } from '../../../types';

const test1Questions: QuizQuestion[] = [
  {
    question_en: "Which of the following is not an example of the Tertiary Sector, as mentioned in the notes?",
    question_hi: "तृतीयक क्षेत्र (Tertiary Sector) का उदाहरण कौन सा नहीं है, जैसा कि नोट्स में उल्लेख किया गया है?",
    options_en: ["(A) Internet Services", "(B) Education", "(C) Dairy"],
    options_hi: ["(A) इंटरनेट सेवाएँ", "(B) शिक्षा", "(C) डेयरी"],
    correct_option_index: 2,
    explanation_en: "The tertiary sector provides services. Internet services and education are services. Dairy, which involves animal husbandry, is part of the primary sector (related to natural resources).",
    explanation_hi: "तृतीयक क्षेत्र सेवाएँ प्रदान करता है। इंटरनेट सेवाएँ और शिक्षा, सेवाएँ हैं। डेयरी, जिसमें पशुपालन शामिल है, प्राथमिक क्षेत्र (प्राकृतिक संसाधनों से संबंधित) का हिस्सा है।",
  },
  {
    question_en: "In which type of economy are price and production determined by market forces, with the aim of maximizing profit?",
    question_hi: "किस प्रकार की अर्थव्यवस्था में कीमत (Price) और उत्पादन (Production) का निर्धारण बाजार शक्तियों (Market Powers) द्वारा किया जाता है, जिसका उद्देश्य अधिकतम लाभ कमाना होता है?",
    options_en: ["(A) Socialist Economy", "(B) Capitalist Economy", "(C) Mixed Economy"],
    options_hi: ["(A) समाजवादी अर्थव्यवस्था", "(B) पूंजीवादी अर्थव्यवस्था", "(C) मिश्रित अर्थव्यवस्था"],
    correct_option_index: 1,
    explanation_en: "A capitalist economy (or market economy) is characterized by private ownership of the means of production, and supply and demand (market forces) determine prices and production, driven by the profit motive.",
    explanation_hi: "एक पूंजीवादी अर्थव्यवस्था (या बाजार अर्थव्यवस्था) की विशेषता उत्पादन के साधनों का निजी स्वामित्व है, और आपूर्ति और मांग (बाजार शक्तियाँ) लाभ के उद्देश्य से कीमतों और उत्पादन को निर्धारित करती हैं।",
  },
  {
    question_en: "What is the main feature of a Mixed Economy, exemplified by India according to the notes?",
    question_hi: "मिश्रित अर्थव्यवस्था (Mixed Economy) की मुख्य विशेषता क्या है, जिसका उदाहरण नोट्स के अनुसार भारत है?",
    options_en: ["(A) Control only by the public sector", "(B) Ownership only by the private sector", "(C) Maximizing profit by the private sector"],
    options_hi: ["(A) केवल सार्वजनिक क्षेत्र का नियंत्रण", "(B) केवल निजी क्षेत्र का स्वामित्व", "(C) निजी क्षेत्र द्वारा अधिकतम लाभ कमाना"],
    correct_option_index: 2,
    explanation_en: "A mixed economy combines elements of both capitalist and socialist economies. While (A) and (B) are incorrect, (C) is a key feature of the private sector component that co-exists with the public sector in a mixed economy.",
    explanation_hi: "मिश्रित अर्थव्यवस्था में पूंजीवादी और समाजवादी दोनों अर्थव्यवस्थाओं के तत्व शामिल होते हैं। जबकि (A) और (B) गलत हैं, (C) निजी क्षेत्र का एक प्रमुख घटक है जो मिश्रित अर्थव्यवस्था में सार्वजनिक क्षेत्र के साथ सह-अस्तित्व में रहता है।",
  },
  {
    question_en: "Which commission recommended the establishment of the Reserve Bank of India (RBI)?",
    question_hi: "भारतीय रिजर्व बैंक (RBI) की स्थापना के लिए सिफारिश किस कमीशन ने की थी?",
    options_en: ["(A) Narasimham Commission", "(B) Rangarajan Commission", "(C) Royal Commission (Hilton Young Commission)"],
    options_hi: ["(A) नरसिम्हन कमीशन", "(B) रंगराजन कमीशन", "(C) रॉयल कमीशन (हिल्टन यंग कमीशन)"],
    correct_option_index: 2,
    explanation_en: "The Royal Commission on Indian Currency and Finance, also known as the Hilton Young Commission, recommended the creation of a central bank for India in 1926, which led to the establishment of the RBI in 1935.",
    explanation_hi: "रॉयल कमीशन ऑन इंडियन करेंसी एंड फाइनेंस, जिसे हिल्टन यंग कमीशन भी कहा जाता है, ने 1926 में भारत के लिए एक केंद्रीय बैंक के निर्माण की सिफारिश की, जिसके कारण 1935 में RBI की स्थापना हुई।",
  },
  {
    question_en: "Until 1947, the RBI also served as the central bank for which country?",
    question_hi: "1947 तक, RBI ने किस देश के केंद्रीय बैंक के रूप में कार्य किया था?",
    options_en: ["(A) Pakistan", "(B) Sri Lanka", "(C) Myanmar (Burma)"],
    options_hi: ["(A) पाकिस्तान", "(B) श्रीलंका", "(C) म्यांमार (बर्मा)"],
    correct_option_index: 2,
    explanation_en: "The RBI served as the central bank for Burma (now Myanmar) until April 1947. (It also served as the central bank for Pakistan until June 1948).",
    explanation_hi: "RBI ने अप्रैल 1947 तक बर्मा (अब म्यांमार) के केंद्रीय बैंक के रूप में कार्य किया। (इसने जून 1948 तक पाकिस्तान के केंद्रीय बैंक के रूप में भी कार्य किया)।",
  },
  {
    question_en: "What is the term of office for the RBI Governor?",
    question_hi: "RBI गवर्नर का कार्यकाल कितने वर्ष का होता है?",
    options_en: ["(A) 5 years", "(B) 4 years", "(C) 6 years"],
    options_hi: ["(A) 5 साल", "(B) 4 साल", "(C) 6 साल"],
    correct_option_index: 0,
    explanation_en: "The RBI Governor is typically appointed for an initial term of 3 years, which can be extended. An extension of 2 years is common, making the total term 5 years for many governors.",
    explanation_hi: "RBI गवर्नर को आमतौर पर 3 साल के प्रारंभिक कार्यकाल के लिए नियुक्त किया जाता है, जिसे बढ़ाया जा सकता है। 2 साल का विस्तार आम है, जिससे कई गवर्नरों का कुल कार्यकाल 5 साल हो जाता है।",
  },
  {
    question_en: "If the RBI adopts a Tight Monetary Policy to control inflation, what will be the result?",
    question_hi: "यदि RBI मुद्रास्फीति (Inflation) को नियंत्रित करने के लिए कठोर मौद्रिक नीति (Tight Monetary Policy) अपनाता है, तो इसका परिणाम क्या होगा?",
    options_en: ["(A) Interest rates will decrease and liquidity will increase", "(B) Interest rates will increase and liquidity will decrease", "(C) Liquidity will increase but interest rates will remain the same"],
    options_hi: ["(A) ब्याज दरें घटेंगी और तरलता बढ़ेगी", "(B) ब्याज दरें बढ़ेंगी और तरलता घटेगी", "(C) तरलता बढ़ेगी लेकिन ब्याज दरें समान रहेंगी"],
    correct_option_index: 1,
    explanation_en: "A 'tight' or 'dear' monetary policy aims to reduce the money supply (liquidity) in the economy to curb inflation. This is done by increasing interest rates (like the repo rate), which makes borrowing more expensive.",
    explanation_hi: "एक 'कठोर' या 'महंगी' मौद्रिक नीति का उद्देश्य मुद्रास्फीति को रोकने के लिए अर्थव्यवस्था में धन की आपूर्ति (तरलता) को कम करना है। यह ब्याज दरों (जैसे रेपो रेट) को बढ़ाकर किया जाता है, जिससे उधार लेना अधिक महंगा हो जाता है।",
  },
  {
    question_en: "Under Open Market Operations (OMO), if the RBI buys Government Securities (G-Sec), what will be the effect on liquidity in the market?",
    question_hi: "खुले बाज़ार की क्रियाओं (OMO) के तहत, यदि RBI सरकारी प्रतिभूतियों (G-Sec) को खरीदता (Buy) है, तो बाज़ार में तरलता पर क्या प्रभाव पड़ेगा?",
    options_en: ["(A) Liquidity will decrease and credit creation will decrease", "(B) No effect on credit creation", "(C) Liquidity will increase and credit creation will increase"],
    options_hi: ["(A) तरलता कम होगी और साख सृजन कम होगा", "(B) साख सृजन पर कोई प्रभाव नहीं पड़ेगा", "(C) तरलता बढ़ेगी और साख सृजन बढ़ेगा"],
    correct_option_index: 2,
    explanation_en: "When the RBI buys G-Secs from the market, it pays money to the sellers (banks). This injects money into the banking system, increasing liquidity and the capacity for credit creation.",
    explanation_hi: "जब RBI बाजार से G-Secs खरीदता है, तो वह विक्रेताओं (बैंकों) को पैसा देता है। यह बैंकिंग प्रणाली में पैसा डालता है, जिससे तरलता और साख सृजन की क्षमता बढ़ती है।",
  },
  {
    question_en: "What is the rate at which commercial banks deposit their excess liquidity with the RBI for a short term and earn interest?",
    question_hi: "वह दर जिस पर वाणिज्यिक बैंक अपनी अतिरिक्त तरलता को अल्पकाल के लिए RBI के पास जमा करते हैं और उस पर ब्याज प्राप्त करते हैं, क्या कहलाती है?",
    options_en: ["(A) Repo Rate", "(B) Bank Rate", "(C) Reverse Repo Rate (RRR)"],
    options_hi: ["(A) रेपो दर (Repo Rate)", "(B) बैंक दर (Bank Rate)", "(C) रिवर्स रेपो रेट (RRR)"],
    correct_option_index: 2,
    explanation_en: "The Reverse Repo Rate is the rate at which the RBI borrows money (absorbs liquidity) from commercial banks. Banks park their excess funds with RBI and earn interest at this rate.",
    explanation_hi: "रिवर्स रेपो रेट वह दर है जिस पर RBI वाणिज्यिक बैंकों से पैसा उधार लेता है (तरलता को अवशोषित करता है)। बैंक अपनी अतिरिक्त धनराशि RBI के पास जमा करते हैं और इस दर पर ब्याज कमाते हैं।",
  },
  {
    question_en: "Which of the following statements is correct regarding CRR (Cash Reserve Ratio)?",
    question_hi: "CRR (नकद आरक्षित अनुपात) के संबंध में निम्नलिखित में से कौन सा कथन सही है?",
    options_en: ["(A) Banks receive interest on it from RBI", "(B) Banks keep it with themselves as Cash, Gold, or G-Sec", "(C) It is the part of NDTL deposited with RBI and earns no interest."],
    options_hi: ["(A) बैंक इस पर RBI से ब्याज प्राप्त करते हैं", "(B) बैंक इसे अपने पास कैश, गोल्ड या G-Sec के रूप में रखते हैं", "(C) यह NDTL का वह हिस्सा है जो RBI के पास जमा किया जाता है और इस पर कोई ब्याज नहीं मिलता।"],
    correct_option_index: 2,
    explanation_en: "CRR is a percentage of a bank's Net Demand and Time Liabilities (NDTL) that it must keep with the RBI as cash. Banks do not earn any interest on this mandatory deposit.",
    explanation_hi: "CRR एक बैंक की शुद्ध मांग और सावधि देनदारियों (NDTL) का एक प्रतिशत है जिसे उसे RBI के पास नकद के रूप में रखना होता है। बैंकों को इस अनिवार्य जमा पर कोई ब्याज नहीं मिलता है।",
  },
  {
    question_en: "What is the MSF (Marginal Standing Facility) rate?",
    question_hi: "MSF (Marginal Standing Facility) दर क्या है?",
    options_en: ["(A) The rate at which RBI gives long-term loans", "(B) The rate at which commercial banks borrow from RBI overnight", "(C) The rate applicable only to government securities"],
    options_hi: ["(A) वह दर जिस पर RBI दीर्घावधि ऋण देता है", "(B) वह दर जिस पर वाणिज्यिक बैंक एक रात (Overnight) के लिए RBI से ऋण लेते हैं", "(C) वह दर जो केवल सरकारी प्रतिभूतियों पर लागू होती है"],
    correct_option_index: 1,
    explanation_en: "The MSF is a window for banks to borrow funds from the RBI in an emergency (overnight) when interbank liquidity dries up completely. The MSF rate is typically higher than the Repo rate.",
    explanation_hi: "MSF बैंकों के लिए आपातकालीन स्थिति में (एक रात के लिए) RBI से धन उधार लेने की एक सुविधा है, जब अंतर-बैंक तरलता पूरी तरह से समाप्त हो जाती है। MSF दर आमतौर पर रेपो दर से अधिक होती है।",
  },
  {
    question_en: "What is the purpose of Credit Rationing by the RBI under Qualitative Tools?",
    question_hi: "गुणात्मक उपकरण (Qualitative Tools) के अंतर्गत RBI द्वारा साख राशनिंग (Credit Rationing) का क्या उद्देश्य होता है?",
    options_en: ["(A) To increase interest rates", "(B) To sell government securities", "(C) To set the loan limit for commercial banks"],
    options_hi: ["(A) ब्याज दरें बढ़ाना", "(B) सरकारी प्रतिभूतियां बेचना", "(C) वाणिज्यिक बैंकों की ऋण सीमा निर्धारित करना (Loan limit set करना)"],
    correct_option_index: 2,
    explanation_en: "Credit Rationing is a qualitative (selective) tool where the RBI fixes a maximum limit or ceiling on the amount of loans that commercial banks can grant, either for specific sectors or overall.",
    explanation_hi: "साख राशनिंग एक गुणात्मक (चयनात्मक) उपकरण है, जहाँ RBI वाणिज्यिक बैंकों द्वारा दिए जाने वाले ऋण की राशि पर, या तो विशिष्ट क्षेत्रों के लिए या समग्र रूप से, एक अधिकतम सीमा निर्धारित करता है।",
  },
  {
    question_en: "On what date and with how many banks did the first phase of commercial bank nationalization occur?",
    question_hi: "वाणिज्यिक बैंकों के राष्ट्रीयकरण का पहला चरण किस तिथि को और कितने बैंकों के साथ हुआ था?",
    options_en: ["(A) 15 April 1980, 6 banks", "(B) 1 July 1955, SBI", "(C) 19 July 1969, 14 banks"],
    options_hi: ["(A) 15 अप्रैल 1980, 6 बैंक", "(B) 1 जुलाई 1955, SBI", "(C) 19 जुलाई 1969, 14 बैंक"],
    correct_option_index: 2,
    explanation_en: "The first phase of nationalization took place on 19 July 1969, under Prime Minister Indira Gandhi. 14 major commercial banks with deposits over ₹50 crore were nationalized.",
    explanation_hi: "राष्ट्रीयकरण का पहला चरण 19 जुलाई 1969 को प्रधानमंत्री इंदिरा गांधी के अधीन हुआ। ₹50 करोड़ से अधिक जमा वाले 14 प्रमुख वाणिज्यिक बैंकों का राष्ट्रीयकरण किया गया।",
  },
  {
    question_en: "Who was the RBI Governor during the second phase of commercial bank nationalization (1980)?",
    question_hi: "वाणिज्यिक बैंकों के राष्ट्रीयकरण के दूसरे चरण (1980) के दौरान RBI के गवर्नर कौन थे?",
    options_en: ["(A) C.D. Deshmukh", "(B) L.K. Jha", "(C) I.G. Patel"],
    options_hi: ["(A) सी.डी. देशमुख", "(B) लक्ष्मीकांत झा", "(C) आई.जी. पटेल"],
    correct_option_index: 2,
    explanation_en: "The second phase of nationalization, where 6 more banks were nationalized, occurred on 15 April 1980. Dr. I.G. Patel was the Governor of the RBI during this period (1977-1982).",
    explanation_hi: "राष्ट्रीयकरण का दूसरा चरण, जिसमें 6 और बैंकों का राष्ट्रीयकरण किया गया, 15 अप्रैल 1980 को हुआ। डॉ. आई.जी. पटेल इस अवधि (1977-1982) के दौरान RBI के गवर्नर थे।",
  },
  {
    question_en: "On the recommendation of which committee was NABARD (National Bank for Agriculture and Rural Development) established?",
    question_hi: "NABARD (नेशनल बैंक फॉर एग्रीकल्चर एंड रूरल डेवलपमेंट) की स्थापना किस समिति की सिफारिश पर की गई थी?",
    options_en: ["(A) Narasimham Committee", "(B) K.C. Neogy Committee", "(C) Shivaraman Committee"],
    options_hi: ["(A) नरसिम्हन समिति", "(B) के.सी. नियोगी समिति", "(C) शिवरामन समिति"],
    correct_option_index: 2,
    explanation_en: "NABARD was established on 12 July 1982, based on the recommendations of the B. Sivaraman Committee (Committee to Review Arrangements for Institutional Credit for Agriculture and Rural Development - CRAFICARD).",
    explanation_hi: "NABARD की स्थापना 12 जुलाई 1982 को बी. शिवरामन समिति (कृषि और ग्रामीण विकास के लिए संस्थागत ऋण की व्यवस्था की समीक्षा के लिए समिति - CRAFICARD) की सिफारिशों के आधार पर की गई थी।",
  },
  {
    question_en: "Where is the headquarters of NHB (National Housing Bank) located?",
    question_hi: "NHB (नेशनल हाउसिंग बैंक) का मुख्यालय कहाँ स्थित है?",
    options_en: ["(A) Mumbai", "(B) Lucknow", "(C) New Delhi"],
    options_hi: ["(A) मुंबई", "(B) लखनऊ", "(C) नई दिल्ली"],
    correct_option_index: 2,
    explanation_en: "The National Housing Bank (NHB), the apex financial institution for housing, has its headquarters in New Delhi.",
    explanation_hi: "नेशनल हाउसिंग बैंक (NHB), जो आवास के लिए शीर्ष वित्तीय संस्थान है, का मुख्यालय नई दिल्ली में स्थित है।",
  },
  {
    question_en: "What was the model of the First Five-Year Plan (1951-1956) and what was its priority?",
    question_hi: "पहली पंचवर्षीय योजना (1951-1956) का मॉडल क्या था और इसकी प्राथमिकता क्या थी?",
    options_en: ["(A) Mahalanobis Model, Heavy Industry", "(B) Harrod-Domar Model, Agricultural Production Growth", "(C) Gadgil Model, Poverty Eradication"],
    options_hi: ["(A) महालनोबिस मॉडल, भारी उद्योग", "(B) हैरोड-डोमर मॉडल, कृषि उत्पादन वृद्धि", "(C) गाडगिल मॉडल, गरीबी उन्मूलन"],
    correct_option_index: 1,
    explanation_en: "The First Five-Year Plan was based on the Harrod-Domar model. Its primary focus was on the development of the primary sector, especially agriculture and irrigation, to make India self-sufficient in food grains.",
    explanation_hi: "पहली पंचवर्षीय योजना हैरोड-डोमर मॉडल पर आधारित थी। इसका मुख्य ध्यान प्राथमिक क्षेत्र, विशेष रूप से कृषि और सिंचाई, के विकास पर था, ताकि भारत को खाद्यान्न में आत्मनिर्भर बनाया जा सके।",
  },
  {
    question_en: "What was the main reason for the failure of the Third Five-Year Plan (1961-1966)?",
    question_hi: "तीसरी पंचवर्षीय योजना (1961-1966) की विफलता का मुख्य कारण क्या था?",
    options_en: ["(A) 1971 Indo-Pak War", "(B) 1962 China War, 1964 Nehru's death, and 1965 Pak War & drought", "(C) Implementation of Rolling Plan"],
    options_hi: ["(A) 1971 का भारत-पाक युद्ध", "(B) 1962 का चीन युद्ध, 1964 में नेहरू की मृत्यु, और 1965 का पाक युद्ध एवं सूखा", "(C) रोलिंग प्लान लागू होना"],
    correct_option_index: 1,
    explanation_en: "The Third Plan failed to achieve its targets due to multiple unforeseen events: the Sino-Indian War (1962), the death of PM Nehru (1964), the Indo-Pakistani War (1965), and a severe drought (1965-66).",
    explanation_hi: "तीसरी योजना कई अप्रत्याशित घटनाओं के कारण अपने लक्ष्यों को प्राप्त करने में विफल रही: भारत-चीन युद्ध (1962), पीएम नेहरू की मृत्यु (1964), भारत-पाकिस्तान युद्ध (1965), और एक गंभीर सूखा (1965-66)।",
  },
  {
    question_en: "During which Five-Year Plan were the steel plants at Durgapur, Rourkela, and Bhilai established, and which countries assisted them, respectively?",
    question_hi: "दुर्गापुर, राउरकेला और भिलाई में इस्पात संयंत्रों की स्थापना किस पंचवर्षीय योजना के दौरान की गई थी और उन्हें क्रमशः किन देशों का सहयोग मिला था?",
    options_en: ["(A) First Plan", "(B) Second Five-Year Plan (1956-61)", "(C) Third Five-Year Plan"],
    options_hi: ["(A) पहली योजना", "(B) दूसरी पंचवर्षीय योजना (1956-61)", "(C) तीसरी पंचवर्षीय योजना"],
    correct_option_index: 1,
    explanation_en: "The Second Five-Year Plan (1956-61), based on the Mahalanobis model, focused on heavy industrialization. Bhilai (USSR), Durgapur (UK), and Rourkela (West Germany) steel plants were set up during this plan.",
    explanation_hi: "दूसरी पंचवर्षीय योजना (1956-61), जो महालनोबिस मॉडल पर आधारित थी, भारी औद्योगिकीकरण पर केंद्रित थी। भिलाई (USSR), दुर्गापुर (UK), और राउरकेला (पश्चिम जर्मनी) इस्पात संयंत्र इसी योजना के दौरान स्थापित किए गए थे।",
  },
  {
    question_en: "Which major event occurred during the Fourth Five-Year Plan (1969-1974)?",
    question_hi: "चौथी पंचवर्षीय योजना (1969-1974) के दौरान कौन सी प्रमुख घटना घटी थी?",
    options_en: ["(A) Nationalization of 6 banks", "(B) Establishment of ISRO", "(C) Launch of MUDRA scheme"],
    options_hi: ["(A) 6 बैंकों का राष्ट्रीयकरण", "(B) ISRO की स्थापना", "(C) MUDRA योजना लॉन्च"],
    correct_option_index: 1,
    explanation_en: "ISRO (Indian Space Research Organisation) was established on 15 August 1969, which falls within the Fourth Plan period (1969-1974). The nationalization of 6 banks occurred in 1980 (Sixth Plan), and MUDRA was launched in 2015.",
    explanation_hi: "ISRO (भारतीय अंतरिक्ष अनुसंधान संगठन) की स्थापना 15 अगस्त 1969 को हुई थी, जो चौथी योजना अवधि (1969-1974) के अंतर्गत आती है। 6 बैंकों का राष्ट्रीयकरण 1980 में (छठी योजना) हुआ, और MUDRA योजना 2015 में शुरू की गई थी।",
  },
  {
    question_en: "During which Five-Year Plan was the 'Food for Work Programme' launched?",
    question_hi: "'काम के बदले अनाज योजना' किस पंचवर्षीय योजना के दौरान शुरू की गई थी?",
    options_en: ["(A) Fourth Five-Year Plan", "(B) Fifth Five-Year Plan (1974-78)", "(C) Sixth Five-Year Plan (1980-85)"],
    options_hi: ["(A) चौथी पंचवर्षीय योजना", "(B) पाँचवीं पंचवर्षीय योजना (1974-78)", "(C) छठी पंचवर्षीय योजना (1980-85)"],
    correct_option_index: 1,
    explanation_en: "The Food for Work Programme was launched in 1977-78, during the Fifth Five-Year Plan. This plan was terminated one year early (in 1978) by the Janata Party government.",
    explanation_hi: "काम के बदले अनाज कार्यक्रम 1977-78 में, पाँचवीं पंचवर्षीय योजना के दौरान शुरू किया गया था। इस योजना को जनता पार्टी सरकार द्वारा एक साल पहले (1978 में) समाप्त कर दिया गया था।",
  },
  {
    question_en: "For which period was the Rolling Plan implemented?",
    question_hi: "रोलिंग प्लान (अनवरत योजना) किस समयावधि के लिए लागू की गई थी?",
    options_en: ["(A) 1966-69", "(B) 1978-80", "(C) 1990-92"],
    options_hi: ["(A) 1966-69", "(B) 1978-80", "(C) 1990-92"],
    correct_option_index: 1,
    explanation_en: "The Rolling Plan was introduced by the Janata Party government after terminating the Fifth Plan. It was implemented for the period 1978-1980, before the Congress government returned and started the Sixth Plan.",
    explanation_hi: "रोलिंग प्लान को जनता पार्टी सरकार द्वारा पाँचवीं योजना को समाप्त करने के बाद पेश किया गया था। यह 1978-1980 की अवधि के लिए लागू किया गया था, इससे पहले कि कांग्रेस सरकार वापस आई और छठी योजना शुरू की।",
  },
  {
    question_en: "In which plan were the National Rural Employment Programme (NREP) and Integrated Rural Development Programme (IRDP) launched?",
    question_hi: "राष्ट्रीय ग्रामीण रोजगार कार्यक्रम (NREP) और एकीकृत ग्रामीण विकास कार्यक्रम (IRDP) किस योजना में लॉन्च किए गए थे?",
    options_en: ["(A) Fifth Five-Year Plan", "(B) Seventh Five-Year Plan", "(C) Sixth Five-Year Plan (1980-85)"],
    options_hi: ["(A) पाँचवीं पंचवर्षीय योजना", "(B) सातवीं पंचवर्षीय योजना", "(C) छठी पंचवर्षीय योजना (1980-85)"],
    correct_option_index: 2,
    explanation_en: "Both the IRDP (Integrated Rural Development Programme) and NREP (National Rural Employment Programme) were launched in 1980, marking the beginning of the Sixth Five-Year Plan.",
    explanation_hi: "IRDP (एकीकृत ग्रामीण विकास कार्यक्रम) और NREP (राष्ट्रीय ग्रामीण रोजगार कार्यक्रम) दोनों को 1980 में छठी पंचवर्षीय योजना की शुरुआत में लॉन्च किया गया था।",
  },
  {
    question_en: "Which plan could not be started on time due to the balance of payments crisis and low foreign exchange reserves, leading to Annual Plans (1990-92)?",
    question_hi: "कौन सी योजना भुगतान संतुलन की समस्या और विदेशी मुद्रा भंडार में कमी के कारण समय पर शुरू नहीं हो सकी, जिसके कारण वार्षिक योजनाएँ (1990-92) अपनानी पड़ीं?",
    options_en: ["(A) Sixth Plan", "(B) Seventh Plan", "(C) Eighth Five-Year Plan (1992-97)"],
    options_hi: ["(A) छठी योजना", "(B) सातवीं योजना", "(C) आठवीं पंचवर्षीय योजना (1992-97)"],
    correct_option_index: 2,
    explanation_en: "The Eighth Five-Year Plan was scheduled to start in 1990 but was delayed due to severe economic instability and a BoP crisis. Instead, two Annual Plans were implemented for 1990-91 and 1991-92. The Eighth Plan finally began in 1992 after the 1991 economic reforms.",
    explanation_hi: "आठवीं पंचवर्षीय योजना 1990 में शुरू होने वाली थी, लेकिन गंभीर आर्थिक अस्थिरता और भुगतान संतुलन संकट के कारण इसमें देरी हुई। इसके बजाय, 1990-91 और 1991-92 के लिए दो वार्षिक योजनाएँ लागू की गईं। 1991 के आर्थिक सुधारों के बाद अंततः आठवीं योजना 1992 में शुरू हुई।",
  },
  {
    question_en: "What was the model of the 11th Five-Year Plan (2007-2012) and what was its main objective?",
    question_hi: "11वीं पंचवर्षीय योजना (2007-2012) का मॉडल क्या था और इसका मुख्य उद्देश्य क्या था?",
    options_en: ["(A) Harrod-Domar Model, Economic Growth", "(B) Mahalanobis Model, Heavy Industry", "(C) C. Rangarajan Model, Inclusive Sustainable Development"],
    options_hi: ["(A) हैरोड-डोमर मॉडल, आर्थिक विकास", "(B) महालनोबिस मॉडल, भारी उद्योग", "(C) सी. रंगराजन मॉडल, समावेशी सतत विकास"],
    correct_option_index: 2,
    explanation_en: "The 11th Plan was prepared under the leadership of C. Rangarajan. Its main theme was 'Towards Faster and More Inclusive Growth,' which aligns with inclusive sustainable development.",
    explanation_hi: "11वीं योजना सी. रंगराजन के नेतृत्व में तैयार की गई थी। इसका मुख्य विषय 'तीव्र और अधिक समावेशी विकास की ओर' था, जो समावेशी सतत विकास के साथ संरेखित है।",
  },
  {
    question_en: "What was the final year of the 12th Five-Year Plan (2012-2017), which is also called the last Five-Year Plan?",
    question_hi: "12वीं पंचवर्षीय योजना (2012-2017) का अंतिम वर्ष कौन सा था, जिसे अंतिम पंचवर्षीय योजना भी कहा जाता है?",
    options_en: ["(A) 2016", "(B) 2017", "(C) 2018"],
    options_hi: ["(A) 2016", "(B) 2017", "(C) 2018"],
    correct_option_index: 1,
    explanation_en: "The 12th Five-Year Plan ran from 2012 to 2017. It was the last plan, as the Planning Commission was replaced by NITI Aayog in 2015, which discontinued the five-year planning process.",
    explanation_hi: "12वीं पंचवर्षीय योजना 2012 से 2017 तक चली। यह अंतिम योजना थी, क्योंकि 2015 में योजना आयोग को NITI आयोग द्वारा प्रतिस्थापित कर दिया गया, जिसने पंचवर्षीय योजना प्रक्रिया को बंद कर दिया।",
  },
  {
    question_en: "Who was the first person to estimate the national income of India (1867-68)?",
    question_hi: "भारत में राष्ट्रीय आय का सर्वप्रथम अनुमान (1867-68) किसने लगाया था?",
    options_en: ["(A) Dr. V.K.R.V. Rao", "(B) P.C. Mahalanobis", "(C) Dadabhai Naoroji"],
    options_hi: ["(A) डॉ. वी.के.आर.वी. राव", "(B) पी.सी. महालनोबिस", "(C) दादा भाई नौरोजी"],
    correct_option_index: 2,
    explanation_en: "Dadabhai Naoroji was the first to estimate India's national income in his book 'Poverty and Un-British Rule in India' (1867-68). Dr. V.K.R.V. Rao was the first to do it scientifically.",
    explanation_hi: "दादा भाई नौरोजी ने अपनी पुस्तक 'पॉवर्टी एंड अन-ब्रिटिश रूल इन इंडिया' (1867-68) में भारत की राष्ट्रीय आय का अनुमान लगाने वाले पहले व्यक्ति थे। डॉ. वी.के.आर.वी. राव ने इसे वैज्ञानिक रूप से करने वाले पहले व्यक्ति थे।",
  },
  {
    question_en: "Which one is NOT among the three methods of calculating National Income?",
    question_hi: "राष्ट्रीय आय की गणना के लिए तीन विधियों में से कौन सी एक विधि नहीं है?",
    options_en: ["(A) Product Method", "(B) Income Method", "(C) Expenditure Method"],
    options_hi: ["(A) उत्पाद विधि (Product Method)", "(B) आय विधि (Income Method)", "(C) व्यय विधि (Expenditure Method)"],
    correct_option_index: 0,
    explanation_en: "This question is flawed as all three options listed (Product Method, Income Method, and Expenditure Method) ARE the standard methods for calculating National Income. There is no correct option provided.",
    explanation_hi: "यह प्रश्न त्रुटिपूर्ण है क्योंकि सूचीबद्ध तीनों विकल्प (उत्पाद विधि, आय विधि और व्यय विधि) राष्ट्रीय आय की गणना के लिए मानक तरीके हैं। कोई सही विकल्प प्रदान नहीं किया गया है।",
  },
  {
    question_en: "Which year's prices are used in the calculation of Real GDP?",
    question_hi: "Real GDP (वास्तविक जीडीपी) की गणना में किस वर्ष के मूल्य का प्रयोग किया जाता है?",
    options_en: ["(A) Current Financial Year", "(B) Year of production", "(C) Base Year (2011-12)"],
    options_hi: ["(A) चालू वित्तीय वर्ष (Current Financial Year)", "(B) उत्पादन का वर्ष", "(C) आधार वर्ष (Base Year) 2011-12"],
    correct_option_index: 2,
    explanation_en: "Real GDP is calculated using constant prices, which are the prices from a selected Base Year (currently 2011-12 for India). This removes the effect of inflation. Nominal GDP uses current year prices.",
    explanation_hi: "वास्तविक GDP की गणना स्थिर कीमतों का उपयोग करके की जाती है, जो एक चयनित आधार वर्ष (वर्तमान में भारत के लिए 2011-12) की कीमतें होती हैं। यह मुद्रास्फीति के प्रभाव को हटा देता है। नॉमिनल GDP चालू वर्ष की कीमतों का उपयोग करती है।",
  },
  {
    question_en: "What is the correct formula for Gross National Product (GNP)?",
    question_hi: "सकल राष्ट्रीय उत्पाद (GNP) का सही सूत्र क्या है?",
    options_en: ["(A) GDP + Depreciation", "(B) NDP + Net Factor Income from Abroad", "(C) GDP + Net Factor Income from Abroad"],
    options_hi: ["(A) GDP + मूल्य ह्रास (Depreciation)", "(B) NDP + विदेशियों से प्राप्त शुद्ध कारक आय", "(C) GDP + विदेशों से प्राप्त शुद्ध कारक आय (Net Factor Income from Abroad)"],
    correct_option_index: 2,
    explanation_en: "GNP measures the total income of a country's residents. It is calculated by taking the GDP (income produced *within* the country) and adding the Net Factor Income from Abroad (income earned by residents from abroad minus income earned by non-residents in the country).",
    explanation_hi: "GNP एक देश के निवासियों की कुल आय को मापता है। इसकी गणना GDP (देश *के भीतर* उत्पादित आय) लेकर और उसमें विदेशों से प्राप्त शुद्ध कारक आय (निवासियों द्वारा विदेशों से अर्जित आय घटा देश में गैर-निवासियों द्वारा अर्जित आय) को जोड़कर की जाती है।",
  },
  {
    question_en: "Which of the following items is not included in the calculation of National Income?",
    question_hi: "निम्नलिखित में से कौन सी मद राष्ट्रीय आय की गणना में शामिल नहीं की जाती है?",
    options_en: ["(A) Income from rent", "(B) Profit", "(C) Transfer Payments"],
    options_hi: ["(A) किराए (Rent) से प्राप्त आय", "(B) लाभ (Profit)", "(C) हस्तांतरण भुगतान (Transfer Payments)"],
    correct_option_index: 2,
    explanation_en: "Transfer payments (like pensions, subsidies, scholarships) are not included in national income because they are unilateral payments for which no productive service or good is exchanged in return.",
    explanation_hi: "हस्तांतरण भुगतान (जैसे पेंशन, सब्सिडी, छात्रवृत्ति) को राष्ट्रीय आय में शामिल नहीं किया जाता है क्योंकि वे एकतरफा भुगतान होते हैं जिनके बदले में कोई उत्पादक सेवा या वस्तु का आदान-प्रदान नहीं होता है।",
  },
  {
    question_en: "The term 'Hindu Growth Rate' is related to what?",
    question_hi: "Hindu Growth Rate शब्द का संबंध किससे है?",
    options_en: ["(A) Inflation rate", "(B) Per capita income", "(C) Trade balance"],
    options_hi: ["(A) मुद्रास्फीति दर", "(B) प्रति व्यक्ति आय", "(C) व्यापार संतुलन"],
    correct_option_index: 1,
    explanation_en: "The term 'Hindu Growth Rate' was coined by Prof. Raj Krishna to describe the slow annual growth rate of India's economy (around 3.5%) from the 1950s to 1980s. This slow GDP growth directly impacted (kept low) the per capita income growth.",
    explanation_hi: "'हिंदू विकास दर' शब्द प्रोफेसर राज कृष्ण द्वारा 1950 से 1980 के दशक तक भारत की अर्थव्यवस्था की धीमी वार्षिक वृद्धि दर (लगभग 3.5%) का वर्णन करने के लिए गढ़ा गया था। इस धीमी GDP वृद्धि ने प्रति व्यक्ति आय वृद्धि को सीधे प्रभावित किया (कम रखा)।",
  },
  {
    question_en: "The word 'Budget' is derived from which French word, meaning 'leather bag'?",
    question_hi: "बजट शब्द किस फ्रांसीसी शब्द से बना है, जिसका अर्थ 'चमड़े का थैला' है?",
    options_en: ["(A) Fiscal", "(B) Surplus", "(C) Deficit"],
    options_hi: ["(A) फिस्कल", "(B) सरप्लस", "(C) डेफिसिट"],
    correct_option_index: 0,
    explanation_en: "This question is flawed as none of the options are correct. The word 'Budget' originates from the Middle French word 'bougette', which means a 'little bag' or 'pouch'.",
    explanation_hi: "यह प्रश्न त्रुटिपूर्ण है क्योंकि कोई भी विकल्प सही नहीं है। 'बजट' शब्द की उत्पत्ति मध्य फ्रांसीसी शब्द 'bougette' से हुई है, जिसका अर्थ है 'छोटा बैग' या 'थैली'।",
  },
  {
    question_en: "Which article of the Indian Constitution mentions the 'Annual Financial Statement'?",
    question_hi: "भारतीय संविधान के किस अनुच्छेद में 'वार्षिक वित्तीय विवरण' (Annual Financial Statement) का उल्लेख है?",
    options_en: ["(A) Article 202", "(B) Article 280", "(C) Article 112"],
    options_hi: ["(A) अनुच्छेद 202", "(B) अनुच्छेद 280", "(C) अनुच्छेद 112"],
    correct_option_index: 2,
    explanation_en: "Article 112 of the Indian Constitution requires the Union Government to present a statement of its estimated receipts and expenditures for the financial year, known as the Annual Financial Statement (or Budget). (Article 202 relates to State Budgets).",
    explanation_hi: "भारतीय संविधान का अनुच्छेद 112 केंद्र सरकार को वित्तीय वर्ष के लिए अपनी अनुमानित प्राप्तियों और व्यय का एक विवरण प्रस्तुत करने की आवश्यकता होती है, जिसे वार्षिक वित्तीय विवरण (या बजट) कहा जाता है। (अनुच्छेद 202 राज्य के बजट से संबंधित है)।",
  },
  {
    question_en: "Who prepares the Economic Survey and when is it presented?",
    question_hi: "आर्थिक सर्वेक्षण (Economic Survey) कौन तैयार करता है और इसे कब प्रस्तुत किया जाता है?",
    options_en: ["(A) RBI Governor, with the Budget", "(B) Finance Minister, one day after the Budget", "(C) Chief Economic Adviser (CEA), one day before the Budget"],
    options_hi: ["(A) RBI गवर्नर, बजट के साथ", "(B) वित्त मंत्री, बजट के एक दिन बाद", "(C) मुख्य आर्थिक सलाहकार (CEA), बजट पेश होने से एक दिन पूर्व"],
    correct_option_index: 2,
    explanation_en: "The Economic Survey is prepared by the Department of Economic Affairs under the guidance of the Chief Economic Adviser (CEA). Traditionally, it is presented in Parliament one day before the Union Budget.",
    explanation_hi: "आर्थिक सर्वेक्षण मुख्य आर्थिक सलाहकार (CEA) के मार्गदर्शन में आर्थिक मामलों के विभाग द्वारा तैयार किया जाता है। परंपरागत रूप से, इसे केंद्रीय बजट से एक दिन पहले संसद में प्रस्तुत किया जाता है।",
  },
  {
    question_en: "Which of the following items comes under the government's Revenue Receipt?",
    question_hi: "निम्नलिखित में से कौन सा मद सरकार की राजस्व आय (Revenue Receipt) के अंतर्गत आता है?",
    options_en: ["(A) Recovery of loans", "(B) Income from disinvestment", "(C) Borrowing (debt)"],
    options_hi: ["(A) ऋण की वसूली", "(B) विनिवेश से प्राप्त आय", "(C) ऋण लेना (उधार)"],
    correct_option_index: 0,
    explanation_en: "This question is flawed. All three options (Recovery of loans, Disinvestment, Borrowing) are examples of Capital Receipts, as they either create a liability (debt) or reduce an asset (disinvestment, loan recovery). Revenue receipts are non-redeemable, like taxes or interest income.",
    explanation_hi: "यह प्रश्न त्रुटिपूर्ण है। तीनों विकल्प (ऋण की वसूली, विनिवेश, उधार लेना) पूंजीगत प्राप्तियों (Capital Receipts) के उदाहरण हैं, क्योंकि वे या तो एक देयता (ऋण) बनाते हैं या एक संपत्ति (विनिवेश, ऋण वसूली) को कम करते हैं। राजस्व प्राप्तियां गैर-प्रतिदेय होती हैं, जैसे कर या ब्याज आय।",
  },
  {
    question_en: "What is the most appropriate example of Capital Expenditure?",
    question_hi: "पूंजीगत व्यय (Capital Expenditure) का सबसे उपयुक्त उदाहरण क्या है?",
    options_en: ["(A) Salaries, pensions", "(B) Interest payments", "(C) Construction of roads, buildings, or airports"],
    options_hi: ["(A) वेतन, पेंशन", "(B) ब्याज की अदायगी", "(C) सड़क, भवन, या एयरपोर्ट का निर्माण"],
    correct_option_index: 2,
    explanation_en: "Capital Expenditure (CapEx) is spending that creates future assets (like roads, bridges, machinery) or reduces liabilities. Salaries, pensions, and interest payments are Revenue Expenditures as they are recurring and do not create assets.",
    explanation_hi: "पूंजीगत व्यय (CapEx) वह खर्च है जो भविष्य की संपत्ति (जैसे सड़क, पुल, मशीनरी) बनाता है या देनदारियों को कम करता है। वेतन, पेंशन और ब्याज भुगतान राजस्व व्यय हैं क्योंकि वे आवर्ती होते हैं और संपत्ति नहीं बनाते हैं।",
  },
  {
    question_en: "When the government's total expenditure exceeds its total income, what is it called?",
    question_hi: "जब सरकार का कुल व्यय उसकी कुल आय से अधिक होता है, तो उसे क्या कहते हैं?",
    options_en: ["(A) Balanced Budget", "(B) Budget Deficit", "(C) Revenue Deficit"],
    options_hi: ["(A) संतुलित बजट", "(B) बजट घाटा (Budget Deficit)", "(C) राजस्व घाटा"],
    correct_option_index: 1,
    explanation_en: "A budget deficit occurs when total expenditure (both revenue and capital) is greater than total income (both revenue and capital receipts).",
    explanation_hi: "बजट घाटा तब होता है जब कुल व्यय (राजस्व और पूंजी दोनों) कुल आय (राजस्व और पूंजीगत प्राप्तियां दोनों) से अधिक होता है।",
  },
  {
    question_en: "What is the relationship between Fiscal Deficit and Primary Deficit?",
    question_hi: "राजकोषीय घाटा (Fiscal Deficit) और प्राथमिक घाटा (Primary Deficit) के बीच क्या संबंध होता है?",
    options_en: ["(A) Primary Deficit = Fiscal Deficit + Interest Payments", "(B) Primary Deficit (PD) = Fiscal Deficit (FD) - Interest Payments (IP)", "(C) Fiscal Deficit = Revenue Deficit + Interest Payments"],
    options_hi: ["(A) प्राथमिक घाटा = राजकोषीय घाटा + ब्याज भुगतान", "(B) प्राथमिक घाटा (PD) = राजकोषीय घाटा (FD) - ब्याज भुगतान (IP)", "(C) राजकोषीय घाटा = राजस्व घाटा + ब्याज भुगतान"],
    correct_option_index: 1,
    explanation_en: "The Primary Deficit shows the government's borrowing needs *excluding* interest payments on past debts. It is calculated by subtracting interest payments (IP) from the Fiscal Deficit (FD).",
    explanation_hi: "प्राथमिक घाटा सरकार की उधार आवश्यकताओं को दिखाता है, जिसमें पिछले ऋणों पर ब्याज भुगतान *शामिल नहीं* होता है। इसकी गणना राजकोषीय घाटे (FD) से ब्याज भुगतान (IP) को घटाकर की जाती है।",
  },
  {
    question_en: "In the Financial Market, where do transactions for finance longer than one year take place?",
    question_hi: "वित्तीय बाजार (Financial Market) में एक वर्ष से अधिक समय के लिए वित्त का लेन-देन कहाँ होता है?",
    options_en: ["(A) Money Market", "(B) Capital Market", "(C) Organized Money Market"],
    options_hi: ["(A) मुद्रा बाजार (Money Market)", "(B) पूंजी बाजार (Capital Market)", "(C) संगठित मुद्रा बाजार"],
    correct_option_index: 1,
    explanation_en: "The Capital Market is the market for long-term (more than one year) debt and equity. The Money Market deals with short-term instruments (less than one year).",
    explanation_hi: "पूंजी बाजार दीर्घकालिक (एक वर्ष से अधिक) ऋण और इक्विटी के लिए बाजार है। मुद्रा बाजार अल्पकालिक (एक वर्ष से कम) लिखतों से संबंधित है।",
  },
  {
    question_en: "What is an FPO (Follow-on Public Offer)?",
    question_hi: "FPO (Follow-on Public Offer) क्या होता है?",
    options_en: ["(A) When a company issues shares for the first time", "(B) When shares are transacted between investors", "(C) When a company issues additional shares after already being listed to raise more funds"],
    options_hi: ["(A) जब कंपनी पहली बार शेयर जारी करती है", "(B) जब शेयर निवेशकों के बीच लेन-देन होते हैं", "(C) जब कोई कंपनी अतिरिक्त वित्त संग्रहण के लिए पहले से जारी शेयरों के अतिरिक्त और शेयर जारी करती है"],
    correct_option_index: 2,
    explanation_en: "An FPO (Follow-on Public Offer) occurs when an already publicly listed company issues new shares to the public to raise additional capital. (A) is an IPO, and (B) is secondary market trading.",
    explanation_hi: "FPO (फॉलो-ऑन पब्लिक ऑफर) तब होता है जब एक पहले से ही सार्वजनिक रूप से सूचीबद्ध कंपनी अतिरिक्त पूंजी जुटाने के लिए जनता को नए शेयर जारी करती है। (A) एक IPO है, और (B) द्वितीयक बाजार ट्रेडिंग है।",
  },
  {
    question_en: "In which year was SEBI established, and in which year was it given statutory status?",
    question_hi: "SEBI की स्थापना किस वर्ष हुई थी और इसे किस वर्ष सांविधिक दर्जा (Statutory Status) मिला?",
    options_en: ["(A) Established 1992, Statutory 1988", "(B) Established 1988, Statutory 1990", "(C) Established 12 April 1988, Statutory 30 January 1992 (SEBI Act 1992)"],
    options_hi: ["(A) स्थापना 1992, सांविधिक दर्जा 1988", "(B) स्थापना 1988, सांविधिक दर्जा 1990", "(C) स्थापना 12 अप्रैल 1988, सांविधिक दर्जा 30 जनवरी 1992 (SEBI Act 1992)"],
    correct_option_index: 2,
    explanation_en: "SEBI (Securities and Exchange Board of India) was established as a non-statutory body on 12 April 1988. It was given statutory powers (legal authority) on 30 January 1992, through the SEBI Act, 1992.",
    explanation_hi: "SEBI (भारतीय प्रतिभूति और विनिमय बोर्ड) की स्थापना 12 अप्रैल 1988 को एक गैर-सांविधिक निकाय के रूप में हुई थी। इसे SEBI अधिनियम, 1992 के माध्यम से 30 जनवरी 1992 को सांविधिक शक्तियाँ (कानूनी अधिकार) दी गईं।",
  },
  {
    question_en: "On what date was GST (Goods and Services Tax) implemented in India, and by which Constitutional Amendment Act?",
    question_hi: "GST (वस्तु एवं सेवा कर) भारत में किस तिथि को लागू हुआ था, और इसे किस संविधान संशोधन अधिनियम द्वारा लागू किया गया?",
    options_en: ["(A) 8 September 2016, 122nd Amendment Bill", "(B) 1 July 2017, 122nd Amendment Bill", "(C) 1 July 2017, 101st Constitutional Amendment Act 2016"],
    options_hi: ["(A) 8 सितंबर 2016, 122वाँ संशोधन विधेयक", "(B) 1 जुलाई 2017, 122वाँ संशोधन विधेयक", "(C) 1 जुलाई 2017, 101वाँ संविधान संशोधन अधिनियम 2016"],
    correct_option_index: 2,
    explanation_en: "GST was implemented across India on 1 July 2017. It was introduced via the 101st Constitutional Amendment Act, 2016 (which was passed as the 122nd Amendment Bill).",
    explanation_hi: "GST पूरे भारत में 1 जुलाई 2017 को लागू किया गया था। इसे 101वें संविधान संशोधन अधिनियम, 2016 (जो 122वें संशोधन विधेयक के रूप में पारित हुआ था) के माध्यम से पेश किया गया था।",
  },
  {
    question_en: "Which article of the Indian Constitution mentions the GST Council, and what type of body is it?",
    question_hi: "GST परिषद (GST Council) का उल्लेख भारतीय संविधान के किस अनुच्छेद में है, और यह किस प्रकार की संस्था है?",
    options_en: ["(A) Article 280, Non-constitutional", "(B) Article 279A, Constitutional body", "(C) Article 112, Statutory body"],
    options_hi: ["(A) अनुच्छेद 280, गैर-संवैधानिक", "(B) अनुच्छेद 279A, संवैधानिक संस्था", "(C) अनुच्छेद 112, वैधानिक संस्था"],
    correct_option_index: 1,
    explanation_en: "The GST Council was established by inserting Article 279A into the Constitution via the 101st Amendment. Because it is mentioned in the Constitution itself, it is a Constitutional body.",
    explanation_hi: "GST परिषद की स्थापना 101वें संशोधन के माध्यम से संविधान में अनुच्छेद 279A को शामिल करके की गई थी। क्योंकि इसका उल्लेख स्वयं संविधान में है, यह एक संवैधानिक संस्था है।",
  },
  {
    question_en: "Which of the following items is kept outside the purview of GST?",
    question_hi: "निम्नलिखित में से कौन सी वस्तु GST के दायरे से बाहर रखी गई है?",
    options_en: ["(A) Tobacco products", "(B) Aviation Fuel", "(C) Petroleum products"],
    options_hi: ["(A) तम्बाकू उत्पाद", "(B) एयरोप्लेन का ईंधन (Aviation Fuel)", "(C) पेट्रोलियम उत्पाद"],
    correct_option_index: 2,
    explanation_en: "Petroleum products (like crude oil, petrol, diesel, ATF, natural gas) and alcohol for human consumption are currently kept outside the GST framework. Tobacco is under GST, but also attracts high central excise duty.",
    explanation_hi: "पेट्रोलियम उत्पाद (जैसे कच्चा तेल, पेट्रोल, डीजल, ATF, प्राकृतिक गैस) और मानव उपभोग के लिए शराब को वर्तमान में GST के दायरे से बाहर रखा गया है। तम्बाकू GST के अधीन है, लेकिन इस पर उच्च केंद्रीय उत्पाद शुल्क भी लगता है।",
  },
  {
    question_en: "On the recommendation of which committee was the Planning Commission established?",
    question_hi: "योजना आयोग (Planning Commission) की स्थापना किस समिति की सिफारिश पर की गई थी?",
    options_en: ["(A) Narasimham Committee", "(B) K.C. Neogy Committee", "(C) Shivaraman Committee"],
    options_hi: ["(A) नरसिम्हन समिति", "(B) के.सी. नियोगी समिति", "(C) शिवरामन समिति"],
    correct_option_index: 1,
    explanation_en: "The Planning Commission was established in March 1950 by a resolution of the Government of India, based on the recommendation of the Advisory Planning Board chaired by K.C. Neogy.",
    explanation_hi: "योजना आयोग की स्थापना मार्च 1950 में भारत सरकार के एक प्रस्ताव द्वारा, के.सी. नियोगी की अध्यक्षता वाले सलाहकार योजना बोर्ड की सिफारिश के आधार पर की गई थी।",
  },
  {
    question_en: "Who is the Chairman of the 16th Finance Commission?",
    question_hi: "16वें वित्त आयोग के अध्यक्ष कौन हैं?",
    options_en: ["(A) N.K. Singh", "(B) K.C. Neogy", "(C) Arvind Panagariya"],
    options_hi: ["(A) एन.के. सिंह", "(B) के.सी. नियोगी", "(C) अरविंद पनगड़िया"],
    correct_option_index: 2,
    explanation_en: "Dr. Arvind Panagariya has been appointed as the Chairman of the 16th Finance Commission. N.K. Singh was the chairman of the 15th Finance Commission, and K.C. Neogy was the chairman of the 1st Finance Commission.",
    explanation_hi: "डॉ. अरविंद पनगड़िया को 16वें वित्त आयोग का अध्यक्ष नियुक्त किया गया है। एन.के. सिंह 15वें वित्त आयोग के अध्यक्ष थे, और के.सी. नियोगी पहले वित्त आयोग के अध्यक्ष थे।",
  },
  {
    question_en: "What was the main objective of the New Economic Policy (NEP) 1991?",
    question_hi: "नई आर्थिक नीति (New Economic Policy) 1991 का मुख्य उद्देश्य क्या था?",
    options_en: ["(A) To increase imports", "(B) To promote only privatization", "(C) To only simplify foreign trade"],
    options_hi: ["(A) आयात को बढ़ाना", "(B) केवल निजीकरण को बढ़ावा देना", "(C) केवल विदेशी व्यापार को सरल बनाना"],
    correct_option_index: 1,
    explanation_en: "The NEP 1991 was based on Liberalization, Privatization, and Globalization (LPG). While all options are poorly phrased ('only'), promoting privatization was a central pillar of the reforms to move away from a state-dominated economy.",
    explanation_hi: "नई आर्थिक नीति 1991 उदारीकरण, निजीकरण और वैश्वीकरण (LPG) पर आधारित थी। जबकि सभी विकल्प खराब तरीके से ('केवल') लिखे गए हैं, राज्य-वर्चस्व वाली अर्थव्यवस्था से दूर जाने के लिए निजीकरण को बढ़ावा देना सुधारों का एक केंद्रीय स्तंभ था।",
  },
  {
    question_en: "When a country's imports (Import) are greater than its exports (Export) (e.g., 120 > 100), what is this situation called?",
    question_hi: "जब किसी देश का आयात (Import) निर्यात (Export) से अधिक होता है (जैसे 120 > 100), तो इस स्थिति को क्या कहा जाता है?",
    options_en: ["(A) Trade Surplus", "(B) Balanced Trade", "(C) Trade Deficit"],
    options_hi: ["(A) व्यापार अधिशेष (Trade Surplus)", "(B) संतुलित व्यापार (Balanced Trade)", "(C) व्यापार घाटा (Trade Deficit)"],
    correct_option_index: 2,
    explanation_en: "A trade deficit (or an unfavorable balance of trade) occurs when the value of a country's imports exceeds the value of its exports. A trade surplus is the opposite.",
    explanation_hi: "व्यापार घाटा (या एक प्रतिकूल व्यापार संतुलन) तब होता है जब किसी देश के आयात का मूल्य उसके निर्यात के मूल्य से अधिक हो जाता है। व्यापार अधिशेष इसका विपरीत है।",
  },
  {
    question_en: "In how many phases was 'Operation Flood' (White Revolution) implemented?",
    question_hi: "'ऑपरेशन फ्लड' (श्वेत क्रांति) को कितने चरणों में लागू किया गया था?",
    options_en: ["(A) 2 phases", "(B) 3 phases", "(C) 4 phases"],
    options_hi: ["(A) 2 चरण", "(B) 3 चरण", "(C) 4 चरण"],
    correct_option_index: 1,
    explanation_en: "Operation Flood, the world's largest dairy development program, was implemented in three phases: Phase I (1970–1980), Phase II (1981–1985), and Phase III (1985–1996).",
    explanation_hi: "ऑपरेशन फ्लड, दुनिया का सबसे बड़ा डेयरी विकास कार्यक्रम, तीन चरणों में लागू किया गया था: चरण I (1970-1980), चरण II (1981-1985), और चरण III (1985-1996)।",
  }
];

export default test1Questions;
