import type { QuizQuestion } from '../../../types';

const test8Questions: QuizQuestion[] =[
  {
    question_en: "Who is known as the Father of Economics?",
    question_hi: "अर्थशास्त्र का जनक (Father of Economics) किसे कहा जाता है?",
    options_en: ["John Maynard Keynes", "Adam Smith", "Karl Marx", "Amartya Sen"],
    options_hi: ["जॉन मेनार्ड कीन्स", "एडम स्मिथ", "कार्ल मार्क्स", "अमर्त्य सेन"],
    correct_option_index: 1,
    explanation_en: "Adam Smith, with his work 'The Wealth of Nations', is widely considered the Father of Economics.",
    explanation_hi: "एडम स्मिथ को, उनकी कृति 'द वेल्थ ऑफ नेशंस' के साथ, व्यापक रूप से अर्थशास्त्र का जनक माना जाता है।",
  },
  {
    question_en: "What is the primary sector of the economy mainly associated with?",
    question_hi: "अर्थव्यवस्था का प्राथमिक क्षेत्र मुख्य रूप से किससे संबंधित है?",
    options_en: ["Manufacturing", "Services", "Agriculture and allied activities", "Banking"],
    options_hi: ["विनिर्माण", "सेवाएँ", "कृषि और संबद्ध गतिविधियाँ", "बैंकिंग"],
    correct_option_index: 2,
    explanation_en: "The primary sector deals with the extraction and production of raw materials, such as agriculture, forestry, fishing, and mining.",
    explanation_hi: "प्राथमिक क्षेत्र कच्चे माल के निष्कर्षण और उत्पादन से संबंधित है, जैसे कृषि, वानिकी, मत्स्य पालन और खनन।",
  },
  {
    question_en: "Which type of economy is characterized by a blend of both private and public sectors?",
    question_hi: "किस प्रकार की अर्थव्यवस्था निजी और सार्वजनिक दोनों क्षेत्रों के मिश्रण की विशेषता है?",
    options_en: ["Capitalist Economy", "Socialist Economy", "Mixed Economy", "Closed Economy"],
    options_hi: ["पूंजीवादी अर्थव्यवस्था", "समाजवादी अर्थव्यवस्था", "मिश्रित अर्थव्यवस्था", "बंद अर्थव्यवस्था"],
    correct_option_index: 2,
    explanation_en: "A Mixed Economy combines elements of both capitalism and socialism, where both the market and the government play a role.",
    explanation_hi: "मिश्रित अर्थव्यवस्था पूंजीवाद और समाजवाद दोनों के तत्वों को मिलाती है, जहाँ बाज़ार और सरकार दोनों की भूमिका होती है।",
  },
  {
    question_en: "What does GDP (Gross Domestic Product) measure?",
    question_hi: "जीडीपी (सकल घरेलू उत्पाद) क्या मापता है?",
    options_en: ["Total income of citizens living abroad", "Total value of goods and services produced within a country's borders in a specific time period", "Total money supply in the economy", "Government's total expenditure"],
    options_hi: ["विदेशों में रहने वाले नागरिकों की कुल आय", "एक निश्चित समयावधि में देश की सीमाओं के भीतर उत्पादित वस्तुओं और सेवाओं का कुल मूल्य", "अर्थव्यवस्था में कुल मुद्रा आपूर्ति", "सरकार का कुल व्यय"],
    correct_option_index: 1,
    explanation_en: "GDP is the total monetary or market value of all the finished goods and services produced within a country's borders in a specific time period.",
    explanation_hi: "जीडीपी एक निश्चित समयावधि में देश की सीमाओं के भीतर उत्पादित सभी अंतिम वस्तुओं और सेवाओं का कुल मौद्रिक या बाजार मूल्य है।",
  },
  {
    question_en: "Which economic indicator is used to measure the rate of price increase over a period of time?",
    question_hi: "किस आर्थिक संकेतक का उपयोग समय की अवधि में मूल्य वृद्धि की दर को मापने के लिए किया जाता है?",
    options_en: ["Unemployment Rate", "Inflation", "GDP Growth Rate", "Balance of Payments"],
    options_hi: ["बेरोजगारी दर", "मुद्रास्फीति (Inflation)", "जीडीपी विकास दर", "भुगतान संतुलन"],
    correct_option_index: 1,
    explanation_en: "Inflation is the rate at which the general level of prices for goods and services is rising, and, consequently, the purchasing power of currency is falling.",
    explanation_hi: "मुद्रास्फीति वह दर है जिस पर वस्तुओं और सेवाओं के लिए कीमतों का सामान्य स्तर बढ़ रहा है, और परिणामस्वरूप, मुद्रा की क्रय शक्ति गिर रही है।",
  },
  {
    question_en: "What is the situation called when an economy experiences slow economic growth and high unemployment simultaneously?",
    question_hi: "जब किसी अर्थव्यवस्था में धीमी आर्थिक वृद्धि और उच्च बेरोजगारी एक साथ होती है, तो उस स्थिति को क्या कहते हैं?",
    options_en: ["Deflation", "Hyperinflation", "Stagflation", "Boom"],
    options_hi: ["अपस्फीति", "अति मुद्रास्फीति", "मुद्रास्फीतिजनित मंदी (Stagflation)", "तेजी"],
    correct_option_index: 2,
    explanation_en: "Stagflation is characterized by high inflation and high unemployment, combined with stagnant demand and slow economic growth.",
    explanation_hi: "मुद्रास्फीतिजनित मंदी उच्च मुद्रास्फीति और उच्च बेरोजगारी, ठहरी हुई मांग और धीमी आर्थिक वृद्धि के संयोजन की विशेषता है।",
  },
  {
    question_en: "Who controls the money supply in India?",
    question_hi: "भारत में मुद्रा आपूर्ति को कौन नियंत्रित करता है?",
    options_en: ["Ministry of Finance", "Securities and Exchange Board of India (SEBI)", "Reserve Bank of India (RBI)", "NITI Aayog"],
    options_hi: ["वित्त मंत्रालय", "भारतीय प्रतिभूति और विनिमय बोर्ड (SEBI)", "भारतीय रिजर्व बैंक (RBI)", "नीति आयोग"],
    correct_option_index: 2,
    explanation_en: "The Reserve Bank of India (RBI) is the central bank of India and is responsible for managing and controlling the money supply and monetary policy.",
    explanation_hi: "भारतीय रिजर्व बैंक (RBI) भारत का केंद्रीय बैंक है और मुद्रा आपूर्ति तथा मौद्रिक नीति के प्रबंधन और नियंत्रण के लिए जिम्मेदार है।",
  },
  {
    question_en: "Which of the following is an example of a direct tax?",
    question_hi: "निम्नलिखित में से कौन सा प्रत्यक्ष कर (Direct Tax) का एक उदाहरण है?",
    options_en: ["Goods and Services Tax (GST)", "Customs Duty", "Income Tax", "Sales Tax"],
    options_hi: ["वस्तु एवं सेवा कर (GST)", "सीमा शुल्क", "आय कर (Income Tax)", "बिक्री कर"],
    correct_option_index: 2,
    explanation_en: "Income Tax is a direct tax as its burden falls directly on the person who pays it.",
    explanation_hi: "आय कर एक प्रत्यक्ष कर है क्योंकि इसका भार सीधे उस व्यक्ति पर पड़ता है जो इसका भुगतान करता है।",
  },
  {
    question_en: "What is the term for the policy adopted by the government to manage its revenue and expenditure?",
    question_hi: "सरकार द्वारा अपने राजस्व और व्यय के प्रबंधन के लिए अपनाई गई नीति के लिए क्या शब्द है?",
    options_en: ["Monetary Policy", "Fiscal Policy", "Trade Policy", "Industrial Policy"],
    options_hi: ["मौद्रिक नीति", "राजकोषीय नीति (Fiscal Policy)", "व्यापार नीति", "औद्योगिक नीति"],
    correct_option_index: 1,
    explanation_en: "Fiscal Policy refers to the use of government spending and taxation to influence the economy.",
    explanation_hi: "राजकोषीय नीति अर्थव्यवस्था को प्रभावित करने के लिए सरकारी खर्च और कराधान के उपयोग को संदर्भित करती है।",
  },
  {
    question_en: "Which sector is also known as the 'Service Sector'?",
    question_hi: "किस क्षेत्र को 'सेवा क्षेत्र' (Service Sector) के रूप में भी जाना जाता है?",
    options_en: ["Primary Sector", "Secondary Sector", "Tertiary Sector", "Quaternary Sector"],
    options_hi: ["प्राथमिक क्षेत्र", "द्वितीयक क्षेत्र", "तृतीयक क्षेत्र", "चतुर्थक क्षेत्र"],
    correct_option_index: 2,
    explanation_en: "The Tertiary Sector includes the provision of services, such as transportation, banking, insurance, and communication.",
    explanation_hi: "तृतीयक क्षेत्र में परिवहन, बैंकिंग, बीमा और संचार जैसी सेवाओं का प्रावधान शामिल है।",
  },
  {
    question_en: "What is 'Disguised Unemployment'?",
    question_hi: "'प्रच्छन्न बेरोजगारी' (Disguised Unemployment) क्या है?",
    options_en: ["When a person does not find a job during a particular season", "When more people are employed than actually required", "When people are employed in factories", "When people voluntarily do not work"],
    options_hi: ["जब किसी व्यक्ति को किसी विशेष मौसम में नौकरी नहीं मिलती", "जब आवश्यकता से अधिक लोग कार्यरत होते हैं", "जब लोग कारखानों में कार्यरत होते हैं", "जब लोग स्वेच्छा से काम नहीं करते"],
    correct_option_index: 1,
    explanation_en: "Disguised unemployment occurs when marginal productivity of labor is zero, meaning removing some workers will not affect the total output. It is common in the agriculture sector.",
    explanation_hi: "प्रच्छन्न बेरोजगारी तब होती है जब श्रम की सीमांत उत्पादकता शून्य होती है, जिसका अर्थ है कि कुछ श्रमिकों को हटाने से कुल उत्पादन प्रभावित नहीं होगा। यह कृषि क्षेत्र में आम है।",
  },
  {
    question_en: "The 'Poverty Line' in India is primarily based on:",
    question_hi: "भारत में 'गरीबी रेखा' मुख्य रूप से किस पर आधारित है?",
    options_en: ["Standard of housing", "Educational achievements", "Minimum calorie requirement and monthly per capita expenditure", "Ownership of luxury goods"],
    options_hi: ["आवास का स्तर", "शैक्षिक उपलब्धियां", "न्यूनतम कैलोरी आवश्यकता और मासिक प्रति व्यक्ति व्यय", "विलासिता के सामान का स्वामित्व"],
    correct_option_index: 2,
    explanation_en: "The poverty line is generally estimated based on the minimum monetary value of the food and non-food items necessary for survival, primarily focusing on calorie intake and expenditure.",
    explanation_hi: "गरीबी रेखा का अनुमान आम तौर पर जीवित रहने के लिए आवश्यक खाद्य और गैर-खाद्य वस्तुओं के न्यूनतम मौद्रिक मूल्य के आधार पर लगाया जाता है, जो मुख्य रूप से कैलोरी सेवन और व्यय पर केंद्रित होता है।",
  },
  {
    question_en: "What is the meaning of 'National Income'?",
    question_hi: "'राष्ट्रीय आय' (National Income) का क्या अर्थ है?",
    options_en: ["Total revenue of the government", "Total value of money in circulation", "The sum total of factor incomes earned by normal residents of a country in a financial year", "Total capital of the nation"],
    options_hi: ["सरकार का कुल राजस्व", "चलन में धन का कुल मूल्य", "एक वित्तीय वर्ष में एक देश के सामान्य निवासियों द्वारा अर्जित कारक आय (Factor Income) का कुल योग", "राष्ट्र की कुल पूंजी"],
    correct_option_index: 2,
    explanation_en: "National Income is the sum of all factor incomes (rent, wages, interest, profit) earned by the normal residents of a country in a financial year.",
    explanation_hi: "राष्ट्रीय आय एक वित्तीय वर्ष में देश के सामान्य निवासियों द्वारा अर्जित सभी कारक आय (किराया, मजदूरी, ब्याज, लाभ) का कुल योग है।",
  },
  {
    question_en: "What is 'Repo Rate' in the context of RBI's Monetary Policy?",
    question_hi: "भारतीय रिज़र्व बैंक की मौद्रिक नीति के संदर्भ में 'रेपो दर' (Repo Rate) क्या है?",
    options_en: ["The rate at which commercial banks borrow money from the RBI for the long term", "The rate at which the RBI borrows money from commercial banks", "The rate at which commercial banks borrow money from the RBI for the short term", "The rate at which banks lend to customers"],
    options_hi: ["वह दर जिस पर वाणिज्यिक बैंक लंबी अवधि के लिए RBI से पैसा उधार लेते हैं", "वह दर जिस पर RBI वाणिज्यिक बैंकों से पैसा उधार लेता है", "वह दर जिस पर वाणिज्यिक बैंक अल्पकालिक अवधि के लिए RBI से पैसा उधार लेते हैं", "वह दर जिस पर बैंक ग्राहकों को उधार देते हैं"],
    correct_option_index: 2,
    explanation_en: "Repo rate is the rate at which the RBI lends money to commercial banks, generally against government securities, for a short period.",
    explanation_hi: "रेपो दर वह दर है जिस पर RBI वाणिज्यिक बैंकों को, आमतौर पर सरकारी प्रतिभूतियों के बदले, अल्पकालिक अवधि के लिए पैसा उधार देता है।",
  },
  {
    question_en: "Who is the current Governor of the Reserve Bank of India (as of Oct 2025)?",
    question_hi: "भारतीय रिजर्व बैंक (अक्टूबर 2025 तक) के वर्तमान गवर्नर कौन हैं?",
    options_en: ["Raghuram Rajan", "Urjit Patel", "Shaktikanta Das", "Y. V. Reddy"],
    options_hi: ["रघुराम राजन", "उर्जित पटेल", "शक्तिकांत दास", "वाई. वी. रेड्डी"],
    correct_option_index: 2,
    explanation_en: "Shaktikanta Das is the current (25th) Governor of the Reserve Bank of India.",
    explanation_hi: "शक्तिकांत दास भारतीय रिजर्व बैंक के वर्तमान (25वें) गवर्नर हैं।",
  },
  {
    question_en: "What is the full form of SEBI?",
    question_hi: "SEBI का पूर्ण रूप क्या है?",
    options_en: ["Savings and Exchange Bank of India", "Securities and Exchange Board of India", "State Exchange Bank of India", "Systematic Enforcement Bureau of India"],
    options_hi: ["सेविंग्स एंड एक्सचेंज बैंक ऑफ इंडिया", "सिक्योरिटीज एंड एक्सचेंज बोर्ड ऑफ इंडिया (Securities and Exchange Board of India)", "स्टेट एक्सचेंज बैंक ऑफ इंडिया", "सिस्टमैटिक एन्फोर्समेंट ब्यूरो ऑफ इंडिया"],
    correct_option_index: 1,
    explanation_en: "SEBI stands for Securities and Exchange Board of India, which regulates the securities market.",
    explanation_hi: "SEBI का अर्थ सिक्योरिटीज एंड एक्सचेंज बोर्ड ऑफ इंडिया है, जो प्रतिभूति बाजार को विनियमित करता है।",
  },
  {
    question_en: "Which term describes a tax whose rate increases as the payer's income increases?",
    question_hi: "कौन सा शब्द एक ऐसे कर (Tax) का वर्णन करता है जिसकी दर करदाता की आय बढ़ने पर बढ़ती है?",
    options_en: ["Proportional Tax", "Regressive Tax", "Progressive Tax", "Indirect Tax"],
    options_hi: ["आनुपातिक कर", "प्रतिगामी कर", "प्रगतिशील कर (Progressive Tax)", "अप्रत्यक्ष कर"],
    correct_option_index: 2,
    explanation_en: "A progressive tax system imposes a higher tax rate on high-income earners.",
    explanation_hi: "एक प्रगतिशील कर प्रणाली उच्च आय अर्जकों पर उच्च कर दर लगाती है।",
  },
  {
    question_en: "What is 'Deflation'?",
    question_hi: "'अपस्फीति' (Deflation) क्या है?",
    options_en: ["A period of rising prices and falling unemployment", "A persistent fall in the general price level of goods and services", "High inflation with low growth", "A rise in the general price level"],
    options_hi: ["बढ़ती कीमतों और गिरती बेरोजगारी की अवधि", "वस्तुओं और सेवाओं के सामान्य मूल्य स्तर में लगातार गिरावट", "कम वृद्धि के साथ उच्च मुद्रास्फीति", "सामान्य मूल्य स्तर में वृद्धि"],
    correct_option_index: 1,
    explanation_en: "Deflation is a decrease in the general price level of goods and services, which increases the purchasing power of money.",
    explanation_hi: "अपस्फीति वस्तुओं और सेवाओं के सामान्य मूल्य स्तर में कमी है, जो धन की क्रय शक्ति को बढ़ाती है।",
  },
  {
    question_en: "Which of the following is not a component of the Balance of Payments (BoP)?",
    question_hi: "निम्नलिखित में से कौन सा भुगतान संतुलन (BoP) का घटक नहीं है?",
    options_en: ["Current Account", "Capital Account", "Financial Account", "Revenue Account"],
    options_hi: ["चालू खाता (Current Account)", "पूंजी खाता (Capital Account)", "वित्तीय खाता", "राजस्व खाता"],
    correct_option_index: 3,
    explanation_en: "Balance of Payments has three main accounts: Current Account, Capital Account, and Financial Account. Revenue Account is part of the government's budget.",
    explanation_hi: "भुगतान संतुलन के तीन मुख्य खाते हैं: चालू खाता, पूंजी खाता और वित्तीय खाता। राजस्व खाता सरकार के बजट का हिस्सा है।",
  },
  {
    question_en: "What is the full form of GST in the Indian context?",
    question_hi: "भारतीय संदर्भ में GST का पूर्ण रूप क्या है?",
    options_en: ["Government Sales Tax", "General Services Tax", "Goods and Services Tax", "Gross State Tax"],
    options_hi: ["गवर्नमेंट सेल्स टैक्स", "जनरल सर्विसेज टैक्स", "वस्तु एवं सेवा कर (Goods and Services Tax)", "ग्रॉस स्टेट टैक्स"],
    correct_option_index: 2,
    explanation_en: "GST stands for Goods and Services Tax, an indirect tax implemented in India in 2017.",
    explanation_hi: "GST का अर्थ वस्तु एवं सेवा कर है, जो भारत में 2017 में लागू किया गया एक अप्रत्यक्ष कर है।",
  },
  {
    question_en: "Which plan is also known as the 'Rolling Plan'?",
    question_hi: "किस योजना को 'रोलिंग प्लान' (Rolling Plan) के नाम से भी जाना जाता है?",
    options_en: ["Fifth Five-Year Plan", "Sixth Five-Year Plan", "Annual Plans 1978-80", "Eighth Five-Year Plan"],
    options_hi: ["पाँचवीं पंचवर्षीय योजना", "छठी पंचवर्षीय योजना", "वार्षिक योजनाएँ 1978-80", "आठवीं पंचवर्षीय योजना"],
    correct_option_index: 2,
    explanation_en: "The Rolling Plan concept was introduced in 1978 and covered the period from 1978 to 1980, abandoning the Fifth Five-Year Plan.",
    explanation_hi: "रोलिंग प्लान की अवधारणा 1978 में शुरू की गई थी और पाँचवीं पंचवर्षीय योजना को त्यागते हुए 1978 से 1980 तक की अवधि को कवर किया।",
  },
  {
    question_en: "In which year did India adopt the 'New Economic Policy' (LPG Reforms)?",
    question_hi: "भारत ने किस वर्ष 'नई आर्थिक नीति' (LPG सुधार) को अपनाया?",
    options_en: ["1985", "1991", "2000", "1995"],
    options_hi: ["1985", "1991", "2000", "1995"],
    correct_option_index: 1,
    explanation_en: "The New Economic Policy of 1991, which included Liberalization, Privatization, and Globalization (LPG), was launched under the Narasimha Rao government.",
    explanation_hi: "1991 की नई आर्थिक नीति, जिसमें उदारीकरण, निजीकरण और वैश्वीकरण (LPG) शामिल थे, नरसिम्हा राव सरकार के तहत शुरू की गई थी।",
  },
  {
    question_en: "Who propounded the concept of the 'Human Development Index' (HDI)?",
    question_hi: "'मानव विकास सूचकांक' (HDI) की अवधारणा किसने प्रतिपादित की?",
    options_en: ["Amartya Sen", "Mahbub ul Haq", "Jagdish Bhagwati", "Milton Friedman"],
    options_hi: ["अमर्त्य सेन", "महबूब उल हक", "जगदीश भगवती", "मिल्टन फ्रीडमैन"],
    correct_option_index: 1,
    explanation_en: "The HDI was created to emphasize that people and their capabilities should be the ultimate criteria for assessing the development of a country, not just economic growth. It was developed by Pakistani economist Mahbub ul Haq and Indian Nobel laureate Amartya Sen.",
    explanation_hi: "HDI को इस बात पर ज़ोर देने के लिए बनाया गया था कि लोगों और उनकी क्षमताओं को किसी देश के विकास का आकलन करने का अंतिम मानदंड होना चाहिए, न कि केवल आर्थिक विकास। इसे पाकिस्तानी अर्थशास्त्री महबूब उल हक और भारतीय नोबेल पुरस्कार विजेता अमर्त्य सेन द्वारा विकसित किया गया था।",
  },
  {
    question_en: "What is the main objective of the 'Minimum Support Price' (MSP) in India?",
    question_hi: "भारत में 'न्यूनतम समर्थन मूल्य' (MSP) का मुख्य उद्देश्य क्या है?",
    options_en: ["To maximize government revenue", "To ensure farmers get a minimum profit for their crops", "To promote export of agricultural goods", "To control the prices in the retail market"],
    options_hi: ["सरकारी राजस्व को अधिकतम करना", "यह सुनिश्चित करना कि किसानों को उनकी फसलों के लिए न्यूनतम लाभ मिले", "कृषि वस्तुओं के निर्यात को बढ़ावा देना", "खुदरा बाजार में कीमतों को नियंत्रित करना"],
    correct_option_index: 1,
    explanation_en: "MSP is a form of market intervention by the Government of India to ensure agricultural producers are protected against sharp falls in farm prices.",
    explanation_hi: "MSP भारत सरकार द्वारा एक प्रकार का बाज़ार हस्तक्षेप है ताकि यह सुनिश्चित किया जा सके कि कृषि उत्पादकों को कृषि कीमतों में भारी गिरावट से बचाया जा सके।",
  },
  {
    question_en: "What is the term for the total value of final goods and services produced by the residents of a country, both within and outside the country's border, in a financial year?",
    question_hi: "एक वित्तीय वर्ष में किसी देश के निवासियों द्वारा, देश की सीमा के अंदर और बाहर दोनों जगह, उत्पादित अंतिम वस्तुओं और सेवाओं के कुल मूल्य को क्या कहते हैं?",
    options_en: ["Gross Domestic Product (GDP)", "Net Domestic Product (NDP)", "Gross National Product (GNP)", "Net National Product (NNP)"],
    options_hi: ["सकल घरेलू उत्पाद (GDP)", "शुद्ध घरेलू उत्पाद (NDP)", "सकल राष्ट्रीय उत्पाद (GNP)", "शुद्ध राष्ट्रीय उत्पाद (NNP)"],
    correct_option_index: 2,
    explanation_en: "GNP measures the output produced by a country's residents, regardless of where the production takes place.",
    explanation_hi: "GNP किसी देश के निवासियों द्वारा उत्पादित उत्पादन को मापता है, भले ही उत्पादन कहीं भी होता हो।",
  },
  {
    question_en: "What is the full form of FERA, which was replaced by FEMA?",
    question_hi: "FERA का पूर्ण रूप क्या है, जिसे FEMA द्वारा प्रतिस्थापित किया गया था?",
    options_en: ["Foreign Exchange Revenue Act", "Fiscal Exchange Regulation Act", "Foreign Exchange Regulation Act", "Financial Emergency Regulation Act"],
    options_hi: ["फॉरेन एक्सचेंज रेवेन्यू एक्ट", "राजकोषीय विनिमय विनियमन अधिनियम", "विदेशी मुद्रा विनियमन अधिनियम (Foreign Exchange Regulation Act)", "वित्तीय आपातकालीन विनियमन अधिनियम"],
    correct_option_index: 2,
    explanation_en: "FERA (Foreign Exchange Regulation Act, 1973) was replaced by FEMA (Foreign Exchange Management Act, 1999) to liberalize foreign exchange controls.",
    explanation_hi: "विदेशी मुद्रा नियंत्रण को उदार बनाने के लिए FERA (विदेशी मुद्रा विनियमन अधिनियम, 1973) को FEMA (विदेशी मुद्रा प्रबंधन अधिनियम, 1999) द्वारा प्रतिस्थापित किया गया था।",
  },
  {
    question_en: "Which one of the following is NOT an indirect tax?",
    question_hi: "निम्नलिखित में से कौन सा एक अप्रत्यक्ष कर (Indirect Tax) नहीं है?",
    options_en: ["Sales Tax", "Excise Duty", "Corporation Tax", "Goods and Services Tax (GST)"],
    options_hi: ["बिक्री कर", "उत्पाद शुल्क", "निगम कर (Corporation Tax)", "वस्तु एवं सेवा कर (GST)"],
    correct_option_index: 2,
    explanation_en: "Corporation Tax is a direct tax on the income of a company, unlike the others which are indirect taxes on goods and services.",
    explanation_hi: "निगम कर एक कंपनी की आय पर एक प्रत्यक्ष कर है, जबकि अन्य वस्तुओं और सेवाओं पर अप्रत्यक्ष कर हैं।",
  },
  {
    question_en: "The concept of 'Inclusive Growth' was introduced in which Five-Year Plan?",
    question_hi: "'समावेशी विकास' (Inclusive Growth) की अवधारणा किस पंचवर्षीय योजना में शुरू की गई थी?",
    options_en: ["Ninth Five-Year Plan", "Tenth Five-Year Plan", "Eleventh Five-Year Plan", "Twelfth Five-Year Plan"],
    options_hi: ["नौवीं पंचवर्षीय योजना", "दसवीं पंचवर्षीय योजना", "ग्यारहवीं पंचवर्षीय योजना", "बारहवीं पंचवर्षीय योजना"],
    correct_option_index: 2,
    explanation_en: "The Eleventh Five-Year Plan (2007-2012) had the theme 'Towards Faster and More Inclusive Growth'.",
    explanation_hi: "ग्यारहवीं पंचवर्षीय योजना (2007-2012) का विषय 'तेज़ और अधिक समावेशी विकास की ओर' था।",
  },
  {
    question_en: "What does the term 'Fiscal Deficit' represent?",
    question_hi: "'राजकोषीय घाटा' (Fiscal Deficit) शब्द क्या दर्शाता है?",
    options_en: ["The difference between total revenue and total expenditure of the government", "The difference between total expenditure and total receipts excluding borrowings", "The difference between total tax revenue and total non-tax revenue", "Total loans taken by the government"],
    options_hi: ["सरकार के कुल राजस्व और कुल व्यय के बीच का अंतर", "उधार को छोड़कर कुल व्यय और कुल प्राप्तियों के बीच का अंतर", "कुल कर राजस्व और कुल गैर-कर राजस्व के बीच का अंतर", "सरकार द्वारा लिए गए कुल ऋण"],
    correct_option_index: 1,
    explanation_en: "Fiscal Deficit is the excess of total expenditure over total receipts excluding borrowings. It represents the total borrowing requirements of the government.",
    explanation_hi: "राजकोषीय घाटा उधार को छोड़कर कुल व्यय और कुल प्राप्तियों का अंतर है। यह सरकार की कुल उधार आवश्यकताओं को दर्शाता है।",
  },
  {
    question_en: "The period of the 'Plan Holiday' (1966-1969) in India was due to:",
    question_hi: "भारत में 'योजना अवकाश' (1966-1969) की अवधि किसके कारण थी?",
    options_en: ["Political instability", "Failure of the Second Five-Year Plan", "War, severe drought, and resulting resource scarcity", "Formation of the NITI Aayog"],
    options_hi: ["राजनीतिक अस्थिरता", "दूसरी पंचवर्षीय योजना की विफलता", "युद्ध, गंभीर सूखा और परिणामस्वरूप संसाधन की कमी", "नीति आयोग का गठन"],
    correct_option_index: 2,
    explanation_en: "The Plan Holiday (1966-1969) was declared due to the failure of the Third Plan, which was triggered by the Indo-China War (1962), Indo-Pak War (1965), and severe drought (1965-66).",
    explanation_hi: "योजना अवकाश (1966-1969) तीसरी योजना की विफलता के कारण घोषित किया गया था, जो भारत-चीन युद्ध (1962), भारत-पाक युद्ध (1965), और गंभीर सूखे (1965-66) के कारण हुआ था।",
  },
  {
    question_en: "What is the full form of NITI Aayog?",
    question_hi: "नीति आयोग (NITI Aayog) का पूर्ण रूप क्या है?",
    options_en: ["National Institution for Transforming India", "National Institute of Technological Innovation", "New India Tax Initiative", "National Institute of Training and Instruction"],
    options_hi: ["नेशनल इंस्टीट्यूशन फॉर ट्रांसफॉर्मिंग इंडिया (National Institution for Transforming India)", "नेशनल इंस्टीट्यूट ऑफ टेक्नोलॉजिकल इनोवेशन", "न्यू इंडिया टैक्स इनिशिएटिव", "नेशनल इंस्टीट्यूट ऑफ ट्रेनिंग एंड इंस्ट्रक्शन"],
    correct_option_index: 0,
    explanation_en: "NITI Aayog, established in 2015, replaced the Planning Commission.",
    explanation_hi: "नीति आयोग, जिसकी स्थापना 2015 में हुई थी, ने योजना आयोग का स्थान लिया।",
  },
  {
    question_en: "What does the term 'Bank Rate' mean?",
    question_hi: "'बैंक दर' (Bank Rate) शब्द का क्या अर्थ है?",
    options_en: ["The rate at which banks give loans to customers", "The rate at which the RBI provides long-term loans to commercial banks without collateral", "The rate at which banks borrow from each other", "The minimum rate of interest fixed by the government"],
    options_hi: ["वह दर जिस पर बैंक ग्राहकों को ऋण देते हैं", "वह दर जिस पर RBI वाणिज्यिक बैंकों को बिना किसी संपार्श्विक के दीर्घकालिक ऋण प्रदान करता है", "वह दर जिस पर बैंक एक-दूसरे से उधार लेते हैं", "सरकार द्वारा निर्धारित ब्याज की न्यूनतम दर"],
    correct_option_index: 1,
    explanation_en: "Bank Rate is the rate at which the RBI gives long-term credit to commercial banks and is used for long-term policy signals.",
    explanation_hi: "बैंक दर वह दर है जिस पर RBI वाणिज्यिक बैंकों को दीर्घकालिक ऋण देता है और इसका उपयोग दीर्घकालिक नीति संकेतों के लिए किया जाता है।",
  },
  {
    question_en: "Which committee recommended the setting up of the National Bank for Agriculture and Rural Development (NABARD)?",
    question_hi: "किस समिति ने राष्ट्रीय कृषि और ग्रामीण विकास बैंक (NABARD) की स्थापना की सिफारिश की थी?",
    options_en: ["Narasimham Committee", "Shivraman Committee", "K.C. Neogy Committee", "Chelliah Committee"],
    options_hi: ["नरसिम्हन समिति", "शिवरामन समिति", "के.सी. नियोगी समिति", "चेलैया समिति"],
    correct_option_index: 1,
    explanation_en: "NABARD was established in 1982 based on the recommendations of the B. Sivaraman Committee.",
    explanation_hi: "NABARD की स्थापना 1982 में बी. शिवरामन समिति की सिफारिशों के आधार पर की गई थी।",
  },
  {
    question_en: "The term 'Crowding Out' effect relates to:",
    question_hi: "'क्राउडिंग आउट' (Crowding Out) प्रभाव किससे संबंधित है?",
    options_en: ["Increased private investment due to government spending", "Decrease in private investment due to government borrowing", "Increase in foreign direct investment", "Decrease in inflation due to tax cuts"],
    options_hi: ["सरकारी खर्च के कारण निजी निवेश में वृद्धि", "सरकारी उधार के कारण निजी निवेश में कमी", "प्रत्यक्ष विदेशी निवेश में वृद्धि", "कर कटौती के कारण मुद्रास्फीति में कमी"],
    correct_option_index: 1,
    explanation_en: "Crowding Out occurs when the government's borrowing needs increase the demand for credit, driving up interest rates and thus reducing (crowding out) private investment.",
    explanation_hi: "क्राउडिंग आउट तब होता है जब सरकार की उधार लेने की ज़रूरतें ऋण की मांग को बढ़ाती हैं, जिससे ब्याज दरें बढ़ जाती हैं और इस प्रकार निजी निवेश कम हो जाता है।",
  },
  {
    question_en: "In the context of the secondary sector, what is the full form of MSME?",
    question_hi: "द्वितीयक क्षेत्र के संदर्भ में, MSME का पूर्ण रूप क्या है?",
    options_en: ["Minimum Standard Manufacturing Enterprise", "Micro, Small and Medium Enterprises", "Major State Mining Enterprises", "Maximum Sustainable Manufacturing Efficiency"],
    options_hi: ["न्यूनतम मानक विनिर्माण उद्यम", "सूक्ष्म, लघु और मध्यम उद्यम (Micro, Small and Medium Enterprises)", "प्रमुख राज्य खनन उद्यम", "अधिकतम सतत विनिर्माण दक्षता"],
    correct_option_index: 1,
    explanation_en: "MSMEs are vital for industrial growth and employment generation in India.",
    explanation_hi: "MSME भारत में औद्योगिक विकास और रोजगार सृजन के लिए महत्वपूर्ण हैं।",
  },
  {
    question_en: "What does the 'L' stand for in the LPG model of economic reforms?",
    question_hi: "आर्थिक सुधारों के LPG मॉडल में 'L' का क्या अर्थ है?",
    options_en: ["Labour", "Legislation", "Liberalization", "Loan"],
    options_hi: ["श्रम", "कानून", "उदारीकरण (Liberalization)", "ऋण"],
    correct_option_index: 2,
    explanation_en: "LPG stands for Liberalization, Privatization, and Globalization, the pillars of the 1991 economic reforms.",
    explanation_hi: "LPG का अर्थ उदारीकरण, निजीकरण और वैश्वीकरण है, जो 1991 के आर्थिक सुधारों के स्तंभ हैं।",
  },
  {
    question_en: "Which of the following is a quantitative tool of Monetary Policy?",
    question_hi: "निम्नलिखित में से कौन सा मौद्रिक नीति का एक मात्रात्मक उपकरण (Quantitative Tool) है?",
    options_en: ["Moral Suasion", "Repo Rate", "Credit Rationing", "Margin Requirement"],
    options_hi: ["नैतिक अनुनय", "रेपो दर (Repo Rate)", "साख राशनिंग", "मार्जिन आवश्यकता"],
    correct_option_index: 1,
    explanation_en: "Quantitative tools like Repo Rate (and CRR, SLR, Bank Rate) influence the total volume of money and credit in the economy.",
    explanation_hi: "रेपो दर (और CRR, SLR, बैंक दर) जैसे मात्रात्मक उपकरण अर्थव्यवस्था में धन और ऋण की कुल मात्रा को प्रभावित करते हैं।",
  },
  {
    question_en: "The Headquarters of the World Bank is located in:",
    question_hi: "विश्व बैंक (World Bank) का मुख्यालय कहाँ स्थित है?",
    options_en: ["New York", "Geneva", "Washington D.C.", "London"],
    options_hi: ["न्यूयॉर्क", "जिनेवा", "वाशिंगटन डी.सी.", "लंदन"],
    correct_option_index: 2,
    explanation_en: "The World Bank and the International Monetary Fund (IMF) both have their headquarters in Washington D.C., USA.",
    explanation_hi: "विश्व बैंक और अंतर्राष्ट्रीय मुद्रा कोष (IMF) दोनों का मुख्यालय वाशिंगटन डी.सी., संयुक्त राज्य अमेरिका में है।",
  },
  {
    question_en: "Which body approves the Five-Year Plans in India?",
    question_hi: "भारत में पंचवर्षीय योजनाओं को कौन सा निकाय अनुमोदित करता था?",
    options_en: ["Planning Commission", "Ministry of Finance", "National Development Council (NDC)", "Parliament"],
    options_hi: ["योजना आयोग", "वित्त मंत्रालय", "राष्ट्रीय विकास परिषद (NDC)", "संसद"],
    correct_option_index: 2,
    explanation_en: "The National Development Council (NDC) was the apex body that took final decisions on the Five-Year Plans.",
    explanation_hi: "राष्ट्रीय विकास परिषद (NDC) सर्वोच्च निकाय थी जो पंचवर्षीय योजनाओं पर अंतिम निर्णय लेती थी।",
  },
  {
    question_en: "What is 'Demonetisation'?",
    question_hi: "'विमुद्रीकरण' (Demonetisation) क्या है?",
    options_en: ["A process where a country joins a monetary union", "The act of stripping a currency unit of its status as legal tender", "The printing of new currency notes", "The conversion of black money into white money"],
    options_hi: ["एक प्रक्रिया जहाँ कोई देश एक मौद्रिक संघ में शामिल होता है", "एक मुद्रा इकाई को कानूनी निविदा (Legal Tender) के रूप में उसकी स्थिति से हटाना", "नए करेंसी नोटों की छपाई", "काले धन को सफेद धन में बदलना"],
    correct_option_index: 1,
    explanation_en: "Demonetisation is the act of officially declaring that a currency unit is no longer a legal tender, as happened in India in 2016.",
    explanation_hi: "विमुद्रीकरण आधिकारिक तौर पर यह घोषणा करने का कार्य है कि एक मुद्रा इकाई अब कानूनी निविदा नहीं है, जैसा कि 2016 में भारत में हुआ था।",
  },
  {
    question_en: "The term 'SEZ' stands for:",
    question_hi: "शब्द 'SEZ' का अर्थ है:",
    options_en: ["Special Economic Zone", "State Employment Zone", "Social Equality Zone", "Securities Exchange Zone"],
    options_hi: ["विशेष आर्थिक क्षेत्र (Special Economic Zone)", "राज्य रोजगार क्षेत्र", "सामाजिक समानता क्षेत्र", "प्रतिभूति विनिमय क्षेत्र"],
    correct_option_index: 0,
    explanation_en: "SEZ is an area in a country that is subject to different economic regulations than other regions, typically designed to encourage foreign investment.",
    explanation_hi: "SEZ किसी देश में एक ऐसा क्षेत्र है जो अन्य क्षेत्रों की तुलना में अलग आर्थिक नियमों के अधीन है, जिसे आमतौर पर विदेशी निवेश को प्रोत्साहित करने के लिए डिज़ाइन किया गया है।",
  },
  {
    question_en: "Which of the following is the largest source of non-tax revenue for the Indian Government?",
    question_hi: "निम्नलिखित में से कौन सा भारतीय सरकार के लिए गैर-कर राजस्व (Non-Tax Revenue) का सबसे बड़ा स्रोत है?",
    options_en: ["Customs Duty", "Interest Receipts", "Fees and Penalties", "Dividends and Profits from PSUs"],
    options_hi: ["सीमा शुल्क", "ब्याज प्राप्तियां", "शुल्क और जुर्माना", "सार्वजनिक क्षेत्र के उपक्रमों (PSUs) से लाभांश और लाभ"],
    correct_option_index: 3,
    explanation_en: "Dividends and Profits from Public Sector Undertakings (PSUs) often form the largest component of non-tax revenue.",
    explanation_hi: "सार्वजनिक क्षेत्र के उपक्रमों (PSUs) से लाभांश और लाभ अक्सर गैर-कर राजस्व का सबसे बड़ा घटक बनाते हैं।",
  },
  {
    question_en: "What is the primary indicator of economic health in a developed country?",
    question_hi: "एक विकसित देश में आर्थिक स्वास्थ्य का प्राथमिक संकेतक क्या है?",
    options_en: ["High agricultural output", "High Gross National Product (GNP) and high per capita income", "Low industrial output", "High unemployment"],
    options_hi: ["उच्च कृषि उत्पादन", "उच्च सकल राष्ट्रीय उत्पाद (GNP) और उच्च प्रति व्यक्ति आय", "कम औद्योगिक उत्पादन", "उच्च बेरोजगारी"],
    correct_option_index: 1,
    explanation_en: "A developed country is typically characterized by a high GNP and a high per capita income, indicating a higher standard of living.",
    explanation_hi: "एक विकसित देश की विशेषता आमतौर पर उच्च GNP और उच्च प्रति व्यक्ति आय होती है, जो जीवन स्तर के उच्च होने का संकेत देती है।",
  },
  {
    question_en: "The headquarters of SIDBI (Small Industries Development Bank of India) is located in:",
    question_hi: "सिडबी (भारतीय लघु उद्योग विकास बैंक) का मुख्यालय कहाँ स्थित है?",
    options_en: ["Mumbai", "New Delhi", "Lucknow", "Chennai"],
    options_hi: ["मुंबई", "नई दिल्ली", "लखनऊ", "चेन्नई"],
    correct_option_index: 2,
    explanation_en: "SIDBI was established in 1990 and its headquarters is in Lucknow, Uttar Pradesh.",
    explanation_hi: "सिडबी की स्थापना 1990 में हुई थी और इसका मुख्यालय लखनऊ, उत्तर प्रदेश में है।",
  },
  {
    question_en: "What is the main function of the 'Capital Market'?",
    question_hi: "'पूंजी बाज़ार' (Capital Market) का मुख्य कार्य क्या है?",
    options_en: ["Trading of short-term debt instruments", "Providing short-term loans to banks", "Facilitating the trading of long-term debt and equity-backed securities", "Regulating the money supply"],
    options_hi: ["अल्पकालिक ऋण साधनों का व्यापार", "बैंकों को अल्पकालिक ऋण प्रदान करना", "दीर्घकालिक ऋण और इक्विटी-समर्थित प्रतिभूतियों के व्यापार की सुविधा प्रदान करना", "मुद्रा आपूर्ति को विनियमित करना"],
    correct_option_index: 2,
    explanation_en: "The Capital Market is where buyers and sellers engage in trade of financial securities like stocks and bonds, generally for long-term periods.",
    explanation_hi: "पूंजी बाज़ार वह जगह है जहाँ खरीदार और विक्रेता स्टॉक और बॉन्ड जैसी वित्तीय प्रतिभूतियों का व्यापार करते हैं, आमतौर पर लंबी अवधि के लिए।",
  },
  {
    question_en: "The term 'P' in PPF (Public Provident Fund) stands for:",
    question_hi: "PPF (लोक भविष्य निधि) में 'P' का अर्थ क्या है?",
    options_en: ["Private", "Poverty", "Public", "Pension"],
    options_hi: ["निजी", "गरीबी", "सार्वजनिक (Public)", "पेंशन"],
    correct_option_index: 2,
    explanation_en: "PPF stands for Public Provident Fund, a long-term investment scheme by the Government of India.",
    explanation_hi: "PPF का अर्थ पब्लिक प्रोविडेंट फंड (लोक भविष्य निधि) है, जो भारत सरकार द्वारा एक दीर्घकालिक निवेश योजना है।",
  },
  {
    question_en: "Who is the chairman of NITI Aayog?",
    question_hi: "नीति आयोग का अध्यक्ष कौन होता है?",
    options_en: ["President of India", "Finance Minister", "Prime Minister", "Vice Chairman of NITI Aayog"],
    options_hi: ["भारत के राष्ट्रपति", "वित्त मंत्री", "प्रधानमंत्री", "नीति आयोग के उपाध्यक्ष"],
    correct_option_index: 2,
    explanation_en: "The Prime Minister of India is the ex-officio Chairman of NITI Aayog.",
    explanation_hi: "भारत के प्रधान मंत्री नीति आयोग के पदेन अध्यक्ष होते हैं।",
  },
  {
    question_en: "Which of the following describes 'Circular Flow of Income'?",
    question_hi: "निम्नलिखित में से कौन 'आय के चक्रीय प्रवाह' (Circular Flow of Income) का वर्णन करता है?",
    options_en: ["The flow of goods and services between India and other countries", "The movement of money between government, firms, and households", "The process of a budget being passed in the Parliament", "The cycle of poverty in a developing nation"],
    options_hi: ["भारत और अन्य देशों के बीच वस्तुओं और सेवाओं का प्रवाह", "सरकार, फर्मों और घरों के बीच धन की आवाजाही", "संसद में बजट पारित होने की प्रक्रिया", "एक विकासशील राष्ट्र में गरीबी का चक्र"],
    correct_option_index: 1,
    explanation_en: "The circular flow of income is a model of the economy in which the major exchanges are represented as flows of money, goods, and services, and factor payments between economic agents.",
    explanation_hi: "आय का चक्रीय प्रवाह अर्थव्यवस्था का एक मॉडल है जिसमें प्रमुख विनिमयों को आर्थिक एजेंटों के बीच धन, वस्तुओं और सेवाओं, और कारक भुगतानों के प्रवाह के रूप में दर्शाया जाता है।",
  },
  {
    question_en: "The primary function of the International Monetary Fund (IMF) is:",
    question_hi: "अंतर्राष्ट्रीय मुद्रा कोष (IMF) का प्राथमिक कार्य क्या है?",
    options_en: ["Providing long-term loans for infrastructure projects", "Promoting international monetary cooperation and financial stability", "Regulating international trade", "Providing grants for educational programs"],
    options_hi: ["बुनियादी ढांचा परियोजनाओं के लिए दीर्घकालिक ऋण प्रदान करना", "अंतर्राष्ट्रीय मौद्रिक सहयोग और वित्तीय स्थिरता को बढ़ावा देना", "अंतर्राष्ट्रीय व्यापार को विनियमित करना", "शैक्षिक कार्यक्रमों के लिए अनुदान प्रदान करना"],
    correct_option_index: 1,
    explanation_en: "The IMF's primary purpose is to ensure the stability of the international monetary system, which includes the system of exchange rates and international payments.",
    explanation_hi: "IMF का प्राथमिक उद्देश्य अंतर्राष्ट्रीय मौद्रिक प्रणाली की स्थिरता सुनिश्चित करना है, जिसमें विनिमय दरों और अंतर्राष्ट्रीय भुगतानों की प्रणाली शामिल है।",
  },
  {
    question_en: "What is the meaning of 'Gini Coefficient'?",
    question_hi: "'गिनी गुणांक' (Gini Coefficient) का क्या अर्थ है?",
    options_en: ["A measure of a country's economic growth rate", "A measure of income or wealth inequality", "A measure of trade balance", "A measure of unemployment rate"],
    options_hi: ["किसी देश की आर्थिक विकास दर का एक माप", "आय या धन की असमानता का एक माप", "व्यापार संतुलन का एक माप", "बेरोजगारी दर का एक माप"],
    correct_option_index: 1,
    explanation_en: "The Gini coefficient is a measure of statistical dispersion intended to represent the income or wealth distribution of a nation's residents, and is the most commonly used measure of inequality.",
    explanation_hi: "गिनी गुणांक सांख्यिकीय फैलाव का एक माप है जिसका उद्देश्य किसी राष्ट्र के निवासियों के आय या धन वितरण का प्रतिनिधित्व करना है, और यह असमानता का सबसे अधिक इस्तेमाल किया जाने वाला माप है।",
  },
  {
    question_en: "The phenomenon of 'Dollarisation' means:",
    question_hi: "'डॉलरीकरण' (Dollarisation) की घटना का क्या अर्थ है?",
    options_en: ["A fall in the value of the dollar", "The increase in the use of a foreign currency (usually the US dollar) in a country, in addition to or instead of the domestic currency", "The process of getting US visa easily", "The practice of fixing the exchange rate"],
    options_hi: ["डॉलर के मूल्य में गिरावट", "किसी देश में घरेलू मुद्रा के अतिरिक्त या उसके स्थान पर विदेशी मुद्रा (आमतौर पर अमेरिकी डॉलर) के उपयोग में वृद्धि", "अमेरिकी वीजा आसानी से प्राप्त करने की प्रक्रिया", "विनिमय दर को ठीक करने की प्रथा"],
    correct_option_index: 1,
    explanation_en: "Dollarisation is the process of aligning a country's currency or economy with the US dollar.",
    explanation_hi: "डॉलरीकरण किसी देश की मुद्रा या अर्थव्यवस्था को अमेरिकी डॉलर के साथ संरेखित करने की प्रक्रिया है।",
  },
  {
    question_en: "What is the key difference between Revenue Expenditure and Capital Expenditure for the government?",
    question_hi: "सरकार के लिए राजस्व व्यय (Revenue Expenditure) और पूंजीगत व्यय (Capital Expenditure) के बीच मुख्य अंतर क्या है?",
    options_en: ["Capital Expenditure is always higher", "Revenue Expenditure does not create assets or reduce liabilities, while Capital Expenditure does", "Revenue Expenditure creates assets, while Capital Expenditure creates liabilities", "There is no significant difference"],
    options_hi: ["पूंजीगत व्यय हमेशा अधिक होता है", "राजस्व व्यय संपत्ति नहीं बनाता या देनदारियों को कम नहीं करता है, जबकि पूंजीगत व्यय करता है", "राजस्व व्यय संपत्ति बनाता है, जबकि पूंजीगत व्यय देनदारियां बनाता है", "कोई महत्वपूर्ण अंतर नहीं है"],
    correct_option_index: 1,
    explanation_en: "Capital expenditure leads to the creation of assets or reduction of liabilities, while revenue expenditure (like salaries, interest payments) does neither.",
    explanation_hi: "पूंजीगत व्यय से संपत्ति का निर्माण होता है या देनदारियों में कमी आती है, जबकि राजस्व व्यय (जैसे वेतन, ब्याज भुगतान) दोनों में से कोई भी नहीं करता है।",
  }
];


export default test8Questions;