import type { QuizQuestion } from '../../../types';

const test2Questions: QuizQuestion[] = [
  {
    question_en: "Who appoints the Prime Minister?",
    question_hi: "प्रधानमंत्री की नियुक्ति कौन करता है?",
    options_en: ["Speaker of Lok Sabha", "Chief Justice", "President", "Leader of the Majority Party"],
    options_hi: ["लोकसभा अध्यक्ष", "मुख्य न्यायाधीश", "राष्ट्रपति", "बहुमत दल का नेता"],
    correct_option_index: 2,
    explanation_en: "As per Article 75, the Prime Minister shall be appointed by the President.",
    explanation_hi: "अनुच्छेद 75 के तहत प्रधानमंत्री की नियुक्ति राष्ट्रपति द्वारा की जाएगी।",
  },
  {
    question_en: "The Council of Ministers is collectively responsible to which body?",
    question_hi: "मंत्रिपरिषद (Council of Ministers) सामूहिक रूप से किसके प्रति उत्तरदायी होती है?",
    options_en: ["President", "Rajya Sabha", "Prime Minister", "Lok Sabha"],
    options_hi: ["राष्ट्रपति", "राज्यसभा", "प्रधानमंत्री", "लोकसभा"],
    correct_option_index: 3,
    explanation_en: "According to Article 75(3), the Council of Ministers is collectively responsible to the Lok Sabha.",
    explanation_hi: "अनुच्छेद 75(3) के अनुसार, मंत्रिपरिषद सामूहिक रूप से लोकसभा के प्रति उत्तरदायी होगी।",
  },
  {
    question_en: "Which Prime Minister did not attend the Parliament during his tenure?",
    question_hi: "कौन से प्रधानमंत्री ऐसे थे जो संसद नहीं गए?",
    options_en: ["Indira Gandhi", "Morarji Desai", "Chaudhary Charan Singh", "Vishwanath Pratap Singh"],
    options_hi: ["इंदिरा गांधी", "मोरारजी देसाई", "चौधरी चरण सिंह", "विश्वनाथ प्रताप सिंह"],
    correct_option_index: 2,
    explanation_en: "Chaudhary Charan Singh was the only Prime Minister who did not attend the Parliament.",
    explanation_hi: "चौधरी चरण सिंह एकमात्र प्रधानमंत्री थे जो संसद नहीं गए।",
  },
  {
    question_en: "Which Prime Minister had the shortest tenure?",
    question_hi: "कौन से प्रधानमंत्री सबसे कम कार्यकाल तक प्रधानमंत्री रहे?",
    options_en: ["Atal Bihari Vajpayee", "Inder Kumar Gujral", "Rajiv Gandhi", "Chandra Shekhar"],
    options_hi: ["अटल बिहारी वाजपेयी", "इंद्र कुमार गुजराल", "राजीव गांधी", "चंद्रशेखर"],
    correct_option_index: 0,
    explanation_en: "Atal Bihari Vajpayee had the shortest tenure as Prime Minister (initially for 13 days in 1996).",
    explanation_hi: "अटल बिहारी वाजपेयी सबसे कम कार्यकाल के प्रधानमंत्री थे।",
  },
  {
    question_en: "Under which article of the Indian Constitution is the Formation of Parliament structured?",
    question_hi: "भारतीय संविधान के किस अनुच्छेद के तहत संसद का गठन (Formation of Parliament) होता है?",
    options_en: ["Article 79", "Article 80", "Article 81", "Article 82"],
    options_hi: ["अनुच्छेद 79", "अनुच्छेद 80", "अनुच्छेद 81", "अनुच्छेद 82"],
    correct_option_index: 0,
    explanation_en: "Article 79 provides for the formation of Parliament (President, Lok Sabha, and Rajya Sabha).",
    explanation_hi: "अनुच्छेद 79 संसद के गठन (राष्ट्रपति, लोकसभा और राज्यसभा) का प्रावधान करता है।",
  },
  {
    question_en: "In which year was the old Parliament House inaugurated?",
    question_hi: "पुराने संसद भवन का उद्घाटन किस वर्ष हुआ था?",
    options_en: ["1921", "1927", "2020", "2023"],
    options_hi: ["1921", "1927", "2020", "2023"],
    correct_option_index: 1,
    explanation_en: "The old Parliament House was inaugurated on January 18, 1927.",
    explanation_hi: "पुराने संसद भवन का उद्घाटन 18 जनवरी 1927 को हुआ था।",
  },
  {
    question_en: "On which date was the Rajya Sabha formed?",
    question_hi: "राज्यसभा का गठन (Formation) किस तिथि को हुआ था?",
    options_en: ["August 23, 1954", "May 13, 1952", "April 3, 1952", "April 17, 1952"],
    options_hi: ["23 अगस्त 1954", "13 मई 1952", "3 अप्रैल 1952", "17 अप्रैल 1952"],
    correct_option_index: 2,
    explanation_en: "The Rajya Sabha was formed on April 3, 1952.",
    explanation_hi: "राज्यसभा का गठन (Formation) 3 अप्रैल 1952 को हुआ था।",
  },
  {
    question_en: "What is the maximum number of members nominated by the President to the Rajya Sabha?",
    question_hi: "राज्यसभा में राष्ट्रपति द्वारा मनोनीत सदस्यों की अधिकतम संख्या कितनी है?",
    options_en: ["10", "12", "20", "245"],
    options_hi: ["10", "12", "20", "245"],
    correct_option_index: 1,
    explanation_en: "12 members are nominated by the President from the fields of art, science, social service, and literature.",
    explanation_hi: "राष्ट्रपति द्वारा कला, विज्ञान, समाजसेवा, साहित्य के क्षेत्र से 12 सदस्य मनोनीत किए जाते हैं।",
  },
  {
    question_en: "How many seats are allocated to Maharashtra in the Rajya Sabha?",
    question_hi: "राज्यसभा में महाराष्ट्र के लिए कितनी सीटें निर्धारित हैं?",
    options_en: ["31", "19", "18", "10"],
    options_hi: ["31", "19", "18", "10"],
    correct_option_index: 1,
    explanation_en: "There are 19 seats allocated to Maharashtra in the Rajya Sabha.",
    explanation_hi: "राज्यसभा में महाराष्ट्र के लिए 19 सीटें हैं।",
  },
  {
    question_en: "When was the first sitting of the Lok Sabha held?",
    question_hi: "लोकसभा की प्रथम बैठक कब हुई थी?",
    options_en: ["April 3, 1952", "April 17, 1952", "May 13, 1952", "August 23, 1954"],
    options_hi: ["3 अप्रैल 1952", "17 अप्रैल 1952", "13 मई 1952", "23 अगस्त 1954"],
    correct_option_index: 2,
    explanation_en: "The first sitting of the Lok Sabha was held on May 13, 1952.",
    explanation_hi: "लोकसभा की प्रथम बैठक 13 मई 1952 को हुई थी।",
  },
  {
    question_en: "Who was the First Woman Speaker of the Lok Sabha?",
    question_hi: "लोकसभा की प्रथम महिला अध्यक्ष (First Women Speaker) कौन थीं?",
    options_en: ["Sumitra Mahajan", "Meira Kumar", "Pratibha Patil", "Sushma Swaraj"],
    options_hi: ["सुमित्रा महाजन", "मीरा कुमार", "प्रतिभा पाटिल", "सुषमा स्वराज"],
    correct_option_index: 1,
    explanation_en: "Meira Kumar was the first woman Speaker of the Lok Sabha.",
    explanation_hi: "लोकसभा की पहली महिला अध्यक्ष मीरा कुमार थीं।",
  },
  {
    question_en: "Which Article was abolished by the 104th Constitutional Amendment Act, 2019, ending the nomination of Anglo-Indians?",
    question_hi: "104वें संविधान संशोधन अधिनियम, 2019 द्वारा किस अनुच्छेद को समाप्त कर दिया गया, जिससे एंग्लो-इंडियन का मनोनयन समाप्त हुआ?",
    options_en: ["Article 80", "Article 330", "Article 331", "Article 332"],
    options_hi: ["अनुच्छेद 80", "अनुच्छेद 330", "अनुच्छेद 331", "अनुच्छेद 332"],
    correct_option_index: 2,
    explanation_en: "Article 331 was abolished by the 104th Constitutional Amendment Act, 2019, which ended the nomination of 2 Anglo-Indians to the Lok Sabha.",
    explanation_hi: "104वें संविधान संशोधन अधिनियम, 2019 द्वारा अनुच्छेद 331 को समाप्त कर दिया गया, जिससे लोकसभा में 2 एंग्लो-इंडियन का मनोनयन समाप्त हुआ।",
  },
  {
    question_en: "What is the term of office for members of the Lok Sabha?",
    question_hi: "लोकसभा सदस्यों का कार्यकाल कितने वर्ष का होता है?",
    options_en: ["6 years", "5 years", "4 years", "7 years"],
    options_hi: ["6 वर्ष", "5 वर्ष", "4 वर्ष", "7 वर्ष"],
    correct_option_index: 1,
    explanation_en: "The term of office for members of the Lok Sabha is 5 years.",
    explanation_hi: "लोकसभा के सदस्यों का कार्यकाल 5 वर्ष का होता है।",
  },
  {
    question_en: "After how many years do one-third of the members of the Rajya Sabha retire?",
    question_hi: "राज्यसभा के एक-तिहाई सदस्य कितने वर्ष बाद सेवानिवृत्त (Retire) हो जाते हैं?",
    options_en: ["6 years", "5 years", "2 years", "3 years"],
    options_hi: ["6 वर्ष", "5 वर्ष", "2 वर्ष", "3 वर्ष"],
    correct_option_index: 2,
    explanation_en: "One-third (1/3) of the members retire every two years.",
    explanation_hi: "हर दूसरे वर्ष (Every 2 year) बाद 1/3 सदस्य सेवानिवृत्त हो जाते हैं।",
  },
  {
    question_en: "What is the minimum age required to become a member of the Lok Sabha?",
    question_hi: "लोकसभा का सदस्य बनने के लिए न्यूनतम आयु कितनी होनी चाहिए?",
    options_en: ["35 years", "30 years", "25 years", "21 years"],
    options_hi: ["35 वर्ष", "30 वर्ष", "25 वर्ष", "21 वर्ष"],
    correct_option_index: 2,
    explanation_en: "The minimum age to become a Lok Sabha member is 25 years, while it is 30 years for Rajya Sabha.",
    explanation_hi: "लोकसभा सदस्य बनने की न्यूनतम आयु 25 वर्ष है, जबकि राज्यसभा सदस्य बनने के लिए 30 वर्ष चाहिए।",
  },
  {
    question_en: "To whom do the Speaker and Deputy Speaker of the Lok Sabha submit their resignation to vacate their post?",
    question_hi: "लोकसभा अध्यक्ष और उपाध्यक्ष को अपने पद से हटने के लिए अपना त्यागपत्र (Resignation) किसे देना होता है?",
    options_en: ["Speaker to Deputy Speaker", "Deputy Speaker to Speaker", "Both to each other", "To the President"],
    options_hi: ["अध्यक्ष उपाध्यक्ष को", "उपाध्यक्ष अध्यक्ष को", "दोनों एक दूसरे को", "राष्ट्रपति को"],
    correct_option_index: 2,
    explanation_en: "The Lok Sabha Speaker submits his resignation to the Deputy Speaker, and the Deputy Speaker submits his resignation to the Speaker (i.e., both to each other).",
    explanation_hi: "लोकसभा अध्यक्ष अपना त्यागपत्र उपाध्यक्ष को और उपाध्यक्ष अपना त्यागपत्र अध्यक्ष को देता है।",
  },
  {
    question_en: "What is the minimum number of members (Quorum) required for the proceedings of the Parliament to run?",
    question_hi: "संसद के सदस्यों की न्यूनतम संख्या (गणपूर्ति/Quorum) कितनी होनी चाहिए ताकि सदन की कार्यवाही चल सके?",
    options_en: ["1/3 of the total members", "1/5 of the total members", "1/10 of the total members", "2/3 of the total members"],
    options_hi: ["कुल सदस्यों का 1/3 भाग", "कुल सदस्यों का 1/5 भाग", "कुल सदस्यों का 1/10 भाग", "कुल सदस्यों का 2/3 भाग"],
    correct_option_index: 2,
    explanation_en: "The quorum of members is 1/10 of the total membership.",
    explanation_hi: "सदस्यों की गणपूर्ति (Quorum) कुल सदस्यों का 1/10 भाग होती है।",
  },
  {
    question_en: "In which article is the definition of a Money Bill given?",
    question_hi: "धन विधेयक (Money Bill) की परिभाषा किस अनुच्छेद में दी गई है?",
    options_en: ["Article 109", "Article 110", "Article 112", "Article 117"],
    options_hi: ["अनुच्छेद 109", "अनुच्छेद 110", "अनुच्छेद 112", "अनुच्छेद 117"],
    correct_option_index: 1,
    explanation_en: "The definition of a Money Bill is given in Article 110.",
    explanation_hi: "धन विधेयक की परिभाषा (Definition) अनुच्छेद 110 में दी गई है।",
  },
  {
    question_en: "By what alias is the Annual Financial Statement known?",
    question_hi: "वार्षिक वित्तीय विवरण (Annual Financial Statement) को किस उपनाम से जाना जाता है?",
    options_en: ["Finance Bill", "Budget", "Appropriation Bill", "Economic Survey"],
    options_hi: ["वित्त विधेयक", "बजट", "विनियोग विधेयक", "आर्थिक सर्वेक्षण"],
    correct_option_index: 1,
    explanation_en: "The Annual Financial Statement is commonly known as the Budget.",
    explanation_hi: "वार्षिक वित्तीय विवरण का उपनाम बजट है।",
  },
  {
    question_en: "Who presented the first budget of independent India?",
    question_hi: "स्वतंत्र भारत का पहला बजट किसने पेश किया था?",
    options_en: ["John Mathai", "R.K. Shanmukham Chetty", "Indira Gandhi", "James Wilson"],
    options_hi: ["जॉन मथाई", "आर.के. षणमुखम चेट्टी", "इंदिरा गांधी", "जेम्स विल्सन"],
    correct_option_index: 1,
    explanation_en: "The first budget of independent India was presented by R.K. Shanmukham Chetty.",
    explanation_hi: "स्वतंत्र भारत का पहला बजट आर.के. षणमुखम चेट्टी ने पेश किया था।",
  },
  {
    question_en: "Who is considered the father of India's first budget (1860)?",
    question_hi: "भारत के प्रथम बजट (1860) के जनक कौन थे?",
    options_en: ["John Mathai", "R.K. Shanmukham Chetty", "James Wilson", "Nirmala Sitharaman"],
    options_hi: ["जॉन मथाई", "आर.के. षणमुखम चेट्टी", "जेम्स विल्सन", "निर्मला सीतारमण"],
    correct_option_index: 2,
    explanation_en: "India's first budget was presented by James Wilson in 1860. He is called the Father of the Indian Budget System.",
    explanation_hi: "भारत का प्रथम बजट 1860 में जेम्स विल्सन द्वारा पेश किया गया। उन्हें भारतीय बजट प्रणाली के जनक कहा जाता है।",
  },
  {
    question_en: "When was the Supreme Court established in independent India?",
    question_hi: "स्वतंत्र भारत में सर्वोच्च न्यायालय (Supreme Court) की स्थापना कब हुई?",
    options_en: ["January 26, 1950", "January 28, 1950", "October 1, 1937", "1774"],
    options_hi: ["26 जनवरी 1950", "28 जनवरी 1950", "1 अक्टूबर 1937", "1774"],
    correct_option_index: 1,
    explanation_en: "The Supreme Court was inaugurated in Delhi on January 28, 1950.",
    explanation_hi: "स्वतंत्र भारत में सुप्रीम कोर्ट का उद्घाटन 28 जनवरी 1950 को दिल्ली में हुआ।",
  },
  {
    question_en: "What was the total number of judges (including the Chief Justice) in the Supreme Court in the original Constitution?",
    question_hi: "मूल संविधान में सुप्रीम कोर्ट में कुल न्यायाधीशों की संख्या (मुख्य न्यायाधीश सहित) कितनी थी?",
    options_en: ["1+6 = 7", "1+7 = 8", "1+3 = 4", "1+30 = 31"],
    options_hi: ["1+6 = 7", "1+7 = 8", "1+3 = 4", "1+30 = 31"],
    correct_option_index: 1,
    explanation_en: "The original Constitution had 1 Chief Justice and 7 other judges (total 8).",
    explanation_hi: "मूल संविधान में 1 मुख्य न्यायाधीश और 7 अन्य न्यायाधीश (कुल 8) थे।",
  },
  {
    question_en: "Who was the first Chief Justice of the Supreme Court?",
    question_hi: "सुप्रीम कोर्ट के प्रथम मुख्य न्यायाधीश कौन थे?",
    options_en: ["Sir Maurice Gwyer", "M. R. Jacob", "H. J. Kania", "V. Ramaswami"],
    options_hi: ["सर मॉरिस ग्वेयर", "एम. आर. जैकब", "हरि लाल जे. कानिया", "वी. रामस्वामी"],
    correct_option_index: 2,
    explanation_en: "The first Chief Justice of the Supreme Court was Hari Lal J. Kania.",
    explanation_hi: "सुप्रीम कोर्ट के प्रथम मुख्य न्यायाधीश हरि लाल जे. कानिया थे।",
  },
  {
    question_en: "What is the process of removing Supreme Court judges from their office called?",
    question_hi: "सुप्रीम कोर्ट के न्यायाधीशों को उनके पद से हटाने की प्रक्रिया को क्या कहा जाता है?",
    options_en: ["Disqualification", "Proved Misbehaviour or Incapacity", "Impeachment", "Judicial Review"],
    options_hi: ["अयोग्यता", "सिद्ध कदाचार या अक्षमता", "महाभियोग (Impeachment)", "न्यायिक समीक्षा"],
    correct_option_index: 1,
    explanation_en: "The process of removal of judges is based on Proved Misbehaviour or Incapacity under Article 124(4).",
    explanation_hi: "न्यायाधीशों को हटाने की प्रक्रिया सिद्ध कदाचार या असमर्थता (Proved Misbehaviour or Incapacity) के आधार पर अनुच्छेद 124(4) के तहत होती है।",
  },
  {
    question_en: "What is the monthly salary of the Chief Justice of the Supreme Court?",
    question_hi: "सुप्रीम कोर्ट के मुख्य न्यायाधीश का मासिक वेतन (Salary) कितना है?",
    options_en: ["₹2,50,000/-", "₹2,80,000/-", "₹3,00,000/-", "₹3,50,000/-"],
    options_hi: ["₹2,50,000/-", "₹2,80,000/-", "₹3,00,000/-", "₹3,50,000/-"],
    correct_option_index: 1,
    explanation_en: "The salary of the Chief Justice of the Supreme Court is ₹2,80,000/-.",
    explanation_hi: "सुप्रीम कोर्ट के मुख्य न्यायाधीश का वेतन ₹2,80,000/- है।",
  },
  {
    question_en: "In which article is it mentioned that the Supreme Court shall be a Court of Record?",
    question_hi: "सुप्रीम कोर्ट एक अभिलेख न्यायालय (Court of Record) होगा, यह किस अनुच्छेद में वर्णित है?",
    options_en: ["Article 124", "Article 127", "Article 129", "Article 131"],
    options_hi: ["अनुच्छेद 124", "अनुच्छेद 127", "अनुच्छेद 129", "अनुच्छेद 131"],
    correct_option_index: 2,
    explanation_en: "Article 129 states that the Supreme Court shall be a Court of Record.",
    explanation_hi: "अनुच्छेद 129 कहता है कि सुप्रीम कोर्ट एक अभिलेख न्यायालय (Court of Record) होगा।",
  },
  {
    question_en: "In which article is the power of Judicial Review of the Supreme Court given?",
    question_hi: "सुप्रीम कोर्ट की न्यायिक पुनर्विलोकन (Judicial Review) की शक्ति किस अनुच्छेद में दी गई है?",
    options_en: ["Article 132", "Article 136", "Article 137", "Article 139"],
    options_hi: ["अनुच्छेद 132", "अनुच्छेद 136", "अनुच्छेद 137", "अनुच्छेद 139"],
    correct_option_index: 2,
    explanation_en: "The power of Judicial Review of the Supreme Court is in Article 137.",
    explanation_hi: "सुप्रीम कोर्ट की न्यायिक पुनर्विलोकन की शक्ति अनुच्छेद 137 में है।",
  },
  {
    question_en: "In which part of the Constitution is the High Court described?",
    question_hi: "उच्च न्यायालय (High Court) का वर्णन संविधान के किस भाग में है?",
    options_en: ["Part V", "Part VI", "Part VII", "Part VIII"],
    options_hi: ["भाग V", "भाग VI", "भाग VII", "भाग VIII"],
    correct_option_index: 1,
    explanation_en: "High Courts are described in Part VI (Articles 214-232).",
    explanation_hi: "उच्च न्यायालय भाग VI (अनुच्छेद 214-232) में वर्णित है।",
  },
  {
    question_en: "In which year were 3 High Courts established in Calcutta, Bombay, and Madras under the Indian High Court Act?",
    question_hi: "किस वर्ष भारतीय उच्च न्यायालय अधिनियम (Indian High Court Act) के तहत कलकत्ता, बंबई और मद्रास में 3 उच्च न्यायालय स्थापित किए गए थे?",
    options_en: ["1858", "1861", "1866", "1919"],
    options_hi: ["1858", "1861", "1866", "1919"],
    correct_option_index: 1,
    explanation_en: "3 High Courts were established under the Indian High Court Act of 1861.",
    explanation_hi: "भारतीय उच्च न्यायालय अधिनियम 1861 के तहत 3 हाई कोर्ट स्थापित किए गए।",
  },
  {
    question_en: "When was the 25th High Court of India established?",
    question_hi: "भारत का 25वां उच्च न्यायालय (25th High Court) कब स्थापित किया गया?",
    options_en: ["2013", "2016", "January 1, 2019", "January 26, 2019"],
    options_hi: ["2013", "2016", "1 जनवरी 2019", "26 जनवरी 2019"],
    correct_option_index: 2,
    explanation_en: "The 25th High Court was established in Andhra Pradesh, Amaravati, on January 1, 2019.",
    explanation_hi: "25वां हाई कोर्ट 1 जनवरी 2019 को आंध्र प्रदेश, अमरावती में बना।",
  },
  {
    question_en: "Who appoints the judges of the High Court?",
    question_hi: "उच्च न्यायालय के न्यायाधीशों की नियुक्ति कौन करता है?",
    options_en: ["Governor", "Chief Minister", "President", "Chief Justice of the Supreme Court"],
    options_hi: ["राज्यपाल", "मुख्यमंत्री", "राष्ट्रपति", "सर्वोच्च न्यायालय का मुख्य न्यायाधीश"],
    correct_option_index: 2,
    explanation_en: "Judges of the High Court are appointed by the President under Article 217(1).",
    explanation_hi: "उच्च न्यायालय में न्यायाधीशों की नियुक्ति राष्ट्रपति द्वारा अनुच्छेद 217(1) के तहत की जाती है।",
  },
  {
    question_en: "By which amendment was the retirement age of High Court judges increased from 60 to 62 years?",
    question_hi: "उच्च न्यायालय के न्यायाधीशों की सेवानिवृत्ति (Retirement) की आयु 60 वर्ष से बढ़ाकर 62 वर्ष किस संशोधन द्वारा की गई?",
    options_en: ["7th CA, 1956", "15th CA, 1963", "42nd CA, 1976", "61st CA, 1988"],
    options_hi: ["7वां CA, 1956", "15वां CA, 1963", "42वां CA, 1976", "61वां CA, 1988"],
    correct_option_index: 1,
    explanation_en: "The retirement age of HC judges was increased from 60 to 62 years by the 15th Constitutional Amendment, 1963.",
    explanation_hi: "15वें संविधान संशोधन, 1963 द्वारा HC के जजों की रिटायरमेंट आयु 60 वर्ष से बढ़ाकर 62 वर्ष कर दी गई थी।",
  },
  {
    question_en: "From where are the salaries/allowances of High Court judges given?",
    question_hi: "उच्च न्यायालय के न्यायाधीशों का वेतन/भत्ते (Salary/Allowances) कहाँ से दिए जाते हैं?",
    options_en: ["Consolidated Fund of India", "Consolidated Fund of the State", "Contingency Fund", "Finance Commission"],
    options_hi: ["भारत की संचित निधि", "राज्य की संचित निधि", "आकस्मिक निधि", "वित्त आयोग"],
    correct_option_index: 1,
    explanation_en: "The salary/allowances of High Court judges are given by the Consolidated Fund of the State.",
    explanation_hi: "High Court के न्यायाधीशों का वेतन/भत्ते राज्य की संचित निधि (Consolidated fund of State) द्वारा दिए जाते हैं।",
  },
  {
    question_en: "In which part and article of the Constitution is the Attorney General described?",
    question_hi: "महान्यायवादी (Attorney General) का वर्णन संविधान के किस भाग और अनुच्छेद में है?",
    options_en: ["Part 5, Article 76", "Part 6, Article 165", "Part 4, Article 51A", "Part 5, Article 148"],
    options_hi: ["भाग 5, अनुच्छेद 76", "भाग 6, अनुच्छेद 165", "भाग 4, अनुच्छेद 51A", "भाग 5, अनुच्छेद 148"],
    correct_option_index: 0,
    explanation_en: "The Attorney General is described in Part 5, Article 76.",
    explanation_hi: "महान्यायवादी (Attorney General) का वर्णन भाग 5, अनुच्छेद 76 में है।",
  },
  {
    question_en: "Who appoints the Attorney General?",
    question_hi: "महान्यायवादी की नियुक्ति किसके द्वारा की जाती है?",
    options_en: ["On the advice of the Prime Minister", "By the Chief Justice", "By the President", "On the recommendation of the Parliament"],
    options_hi: ["प्रधानमंत्री की सलाह पर", "मुख्य न्यायाधीश द्वारा", "राष्ट्रपति द्वारा", "संसद की सिफारिश पर"],
    correct_option_index: 2,
    explanation_en: "The Attorney General is appointed by the President on the recommendation of the Union Council of Ministers.",
    explanation_hi: "महान्यायवादी की नियुक्ति राष्ट्रपति द्वारा संघीय मंत्रिपरिषद की सिफारिश पर की जाती है।",
  },
  {
    question_en: "What special privilege does the Attorney General have?",
    question_hi: "महान्यायवादी के पास क्या विशेष अधिकार होता है?",
    options_en: ["He can vote in the Lok Sabha and Rajya Sabha.", "He can participate and speak in the proceedings of Parliament, but cannot vote.", "He cannot appear in any court.", "His salary is decided by the Parliament."],
    options_hi: ["वह लोकसभा और राज्यसभा में मतदान कर सकता है।", "वह संसद की कार्यवाही में भाग ले सकता है और बोल सकता है, लेकिन वोट नहीं दे सकता।", "वह किसी भी न्यायालय में उपस्थित नहीं हो सकता।", "उसे वेतन संसद द्वारा तय किया जाता है।"],
    correct_option_index: 1,
    explanation_en: "The Attorney General can take part in the proceedings of Parliament and speak, but cannot vote.",
    explanation_hi: "महान्यायवादी संसद की कार्यवाही (Proceeding of Parliament) में हिस्सा ले सकता है, विचार-विमर्श कर सकता है, लेकिन वोट नहीं दे सकता।",
  },
  {
    question_en: "The post of Comptroller and Auditor General (CAG) is inspired by the Constitution of which country?",
    question_hi: "नियंत्रक एवं महालेखा परीक्षक (CAG) का पद किस देश के संविधान से प्रेरित है?",
    options_en: ["USA", "Ireland", "Britain", "Canada"],
    options_hi: ["अमेरिका", "आयरलैंड", "ब्रिटेन", "कनाडा"],
    correct_option_index: 2,
    explanation_en: "The post of CAG is inspired by Britain.",
    explanation_hi: "CAG का पद ब्रिटेन (Britain) से प्रेरित है।",
  },
  {
    question_en: "What is the term of office for the CAG?",
    question_hi: "CAG के कार्यकाल की अवधि कितनी होती है?",
    options_en: ["5 years or 65 years of age", "6 years or 65 years of age", "6 years or 62 years of age", "During the pleasure of the President"],
    options_hi: ["5 वर्ष या 65 वर्ष की आयु", "6 वर्ष या 65 वर्ष की आयु", "6 वर्ष या 62 वर्ष की आयु", "राष्ट्रपति के प्रसाद पर्यंत"],
    correct_option_index: 1,
    explanation_en: "The term of office for the CAG is 6 years or 65 years of age (whichever is earlier).",
    explanation_hi: "CAG का कार्यकाल 6 वर्ष या 65 वर्ष की आयु (जो भी पहले हो) तक होता है।",
  },
  {
    question_en: "Why was a new post called CGA (Controller General of Accounts) created in 1976?",
    question_hi: "1976 में CGA (Controller General of the Accounts) नामक एक नया पद क्यों बनाया गया था?",
    options_en: ["CGA handles the accounting work of CAG.", "CGA handles the auditing work of CAG.", "It was created for coordination between the two.", "It was created only on the advice of the President."],
    options_hi: ["CGA, CAG के लेखांकन कार्य को करता है।", "CGA, CAG के ऑडिटिंग कार्य को करता है।", "यह दोनों के बीच तालमेल के लिए बनाया गया।", "यह केवल राष्ट्रपति की सलाह पर बना।"],
    correct_option_index: 0,
    explanation_en: "In 1976, the CAG was relieved of the accounting work, after which the CGA began to perform this function.",
    explanation_hi: "1976 में CAG को लेखांकन (Accounting) के कार्य से मुक्त (Free) कर दिया गया, जिसके बाद CGA यह कार्य करने लगा।",
  },
  {
    question_en: "To whom does the CAG submit his report?",
    question_hi: "CAG अपनी रिपोर्ट (Report) किसे सौंपता है?",
    options_en: ["Prime Minister", "Speaker of Lok Sabha", "President", "Finance Minister"],
    options_hi: ["प्रधानमंत्री", "लोकसभा अध्यक्ष", "राष्ट्रपति", "वित्त मंत्री"],
    correct_option_index: 2,
    explanation_en: "The CAG submits his report to the President.",
    explanation_hi: "CAG अपनी रिपोर्ट राष्ट्रपति को देता है।",
  },
  {
    question_en: "In which part of the Constitution is the Election Commission described?",
    question_hi: "निर्वाचन आयोग (Election Commission) का वर्णन संविधान के किस भाग में है?",
    options_en: ["Part 14", "Part 15", "Part 16", "Part 17"],
    options_hi: ["भाग 14", "भाग 15", "भाग 16", "भाग 17"],
    correct_option_index: 1,
    explanation_en: "The Election Commission is in Part 15 (Articles 324-329).",
    explanation_hi: "चुनाव आयोग भाग 15 (अनुच्छेद 324-329) में है।",
  },
  {
    question_en: "When was the Election Commission established?",
    question_hi: "निर्वाचन आयोग की स्थापना कब हुई थी?",
    options_en: ["January 26, 1950", "January 25, 1950", "November 26, 1949", "October 1, 1993"],
    options_hi: ["26 जनवरी 1950", "25 जनवरी 1950", "26 नवंबर 1949", "1 अक्टूबर 1993"],
    correct_option_index: 1,
    explanation_en: "The Election Commission was established on January 25, 1950.",
    explanation_hi: "चुनाव आयोग की स्थापना (Establishment) 25 जनवरी 1950 को हुई थी।",
  },
  {
    question_en: "When is National Voter's Day celebrated?",
    question_hi: "राष्ट्रीय मतदाता दिवस (National Voter's Day) कब मनाया जाता है?",
    options_en: ["January 10", "September 14", "January 25", "November 26"],
    options_hi: ["10 जनवरी", "14 सितंबर", "25 जनवरी", "26 नवंबर"],
    correct_option_index: 2,
    explanation_en: "National Voter's Day is celebrated on January 25.",
    explanation_hi: "25 जनवरी को राष्ट्रीय मतदाता दिवस मनाया जाता है।",
  },
  {
    question_en: "What is the tenure of the Chief Election Commissioner?",
    question_hi: "मुख्य चुनाव आयुक्त (Chief Election Commissioner) का कार्यकाल कितना होता है?",
    options_en: ["5 years or 65 years of age", "6 years or 65 years of age", "6 years or 62 years of age", "During the pleasure of the President"],
    options_hi: ["5 वर्ष या 65 वर्ष की आयु", "6 वर्ष या 65 वर्ष की आयु", "6 वर्ष या 62 वर्ष की आयु", "राष्ट्रपति के प्रसाद पर्यंत"],
    correct_option_index: 1,
    explanation_en: "The tenure of the Chief Election Commissioner is 6 years or 65 years of age (whichever is earlier).",
    explanation_hi: "मुख्य चुनाव आयुक्त का कार्यकाल 6 वर्ष या 65 वर्ष की आयु (जो भी पहले हो) होता है।",
  },
  {
    question_en: "On the recommendation of which committee was the voter age reduced from 21 years to 18 years?",
    question_hi: "किस समिति की सिफारिश पर मतदाता आयु (Voter Age) 21 वर्ष से घटाकर 18 वर्ष की गई थी?",
    options_en: ["Dinesh Goswami Committee", "Tarkunde Committee", "K. Santhanam Committee", "Balwant Rai Mehta Committee"],
    options_hi: ["दिनेश गोस्वामी समिति", "तारकुंडे समिति", "के. संथानम समिति", "बलवंत राय मेहता समिति"],
    correct_option_index: 1,
    explanation_en: "On the recommendation of the V.M. Tarkunde Committee (1980), the voting age was reduced from 21 years to 18 years (implemented by 61st CA, 1988, in 1989).",
    explanation_hi: "वी.एम. तारकुंडे समिति (1980) की सिफारिश पर मतदाता आयु 21 वर्ष से घटाकर 18 वर्ष कर दी गई (61वां CA, 1988 द्वारा लागू, 1989 में)।",
  },
  {
    question_en: "Under which article is the Official Language Commission constituted?",
    question_hi: "राजभाषा आयोग (Official Language Commission) का गठन किस अनुच्छेद के तहत किया जाता है?",
    options_en: ["Article 343", "Article 344", "Article 345", "Article 348"],
    options_hi: ["अनुच्छेद 343", "अनुच्छेद 344", "अनुच्छेद 345", "अनुच्छेद 348"],
    correct_option_index: 1,
    explanation_en: "The Official Language Commission is constituted under Article 344.",
    explanation_hi: "राजभाषा आयोग का गठन अनुच्छेद 344 के तहत किया जाता है।",
  },
  {
    question_en: "When was the first Official Language Commission constituted, and who was its first chairman?",
    question_hi: "प्रथम राजभाषा आयोग का गठन कब हुआ और उसके प्रथम अध्यक्ष कौन थे?",
    options_en: ["1955, B.G. Kher", "1957, G.B. Pant", "1961, B.G. Kher", "1955, G.B. Pant"],
    options_hi: ["1955, बी.जी. खेर", "1957, जी.बी. पंत", "1961, बी.जी. खेर", "1955, जी.बी. पंत"],
    correct_option_index: 0,
    explanation_en: "The first Official Language Commission was established in 1955, with B.G. Kher (Bal Gangadhar Kher) as its first chairman.",
    explanation_hi: "प्रथम राजभाषा आयोग की स्थापना 1955 में हुई, जिसके प्रथम अध्यक्ष बी.जी. खेर (बाल गंगाधर खेर) थे।",
  },
  {
    question_en: "Which states have granted English the status of their official language?",
    question_hi: "किन राज्यों ने अंग्रेजी को अपनी आधिकारिक भाषा का दर्जा दिया है?",
    options_en: ["Meghalaya, Manipur, Tripura", "Nagaland, Meghalaya, Mizoram", "Assam, Manipur, Mizoram", "Tripura, Meghalaya, Assam"],
    options_hi: ["मेघालय, मणिपुर, त्रिपुरा", "नागालैंड, मेघालय, मिजोरम", "असम, मणिपुर, मिजोरम", "त्रिपुरा, मेघालय, असम"],
    correct_option_index: 1,
    explanation_en: "Nagaland, Meghalaya, and Mizoram have given English the status of an official language.",
    explanation_hi: "नागालैंड, मेघालय एवं मिजोरम ने अंग्रेजी को आधिकारिक भाषा का दर्जा दिया है।",
  },
  {
    question_en: "What does Article 350(A), added by the 7th Constitutional Amendment 1956, relate to?",
    question_hi: "अनुच्छेद 350(A) किससे संबंधित है, जिसे 7वें संविधान संशोधन 1956 द्वारा जोड़ा गया था?",
    options_en: ["Development of Hindi language", "Education in Mother Tongue", "Language for Redressal of Grievances", "Language of SC/HC"],
    options_hi: ["हिन्दी भाषा का विकास", "मातृभाषा में शिक्षा", "शिकायतों के निवारण की भाषा", "SC/HC की भाषा"],
    correct_option_index: 1,
    explanation_en: "Article 350(A) relates to Education in Mother Tongue.",
    explanation_hi: "अनुच्छेद 350(A) मातृभाषा में शिक्षा (Education in Mother Tongue) से संबंधित है।",
  },
  {
    question_en: "What is the proposal/bill of 'Local Self-Government' introduced by Lord Ripon in 1882 called?",
    question_hi: "1882 में लॉर्ड रिपन द्वारा पेश किए गए 'स्थानीय स्वशासन' के प्रस्ताव/बिल को क्या कहा जाता है?",
    options_en: ["Magnacarta of Constitution", "Magnacarta of LSG in India", "Bill of Local Self-Government", "Document of Local Administration"],
    options_hi: ["मैग्नाकार्टा ऑफ कॉन्स्टिट्यूशन", "भारत में LSG का मैग्नाकार्टा", "स्थानीय स्वशासन का बिल", "स्थानीय प्रशासन का दस्तावेज"],
    correct_option_index: 1,
    explanation_en: "This proposal/bill introduced by Ripon in 1882 is called the 'Magnacarta' of Local Self-Government in India.",
    explanation_hi: "1882 में रिपन द्वारा पेश इस प्रस्ताव/बिल को स्थानीय स्वशासन का \"मैग्नाकार्टा\" (Megnacarta) कहते हैं।",
  },
  {
    question_en: "In which year was the Community Development Programme launched?",
    question_hi: "सामुदायिक विकास कार्यक्रम (Community Development Programm) किस वर्ष शुरू किया गया था?",
    options_en: ["1950", "1952", "1953", "1957"],
    options_hi: ["1950", "1952", "1953", "1957"],
    correct_option_index: 1,
    explanation_en: "The Community Development Programme was launched by the Government of India on October 2, 1952.",
    explanation_hi: "भारत सरकार द्वारा 2 अक्टूबर, 1952 को सामुदायिक विकास कार्यक्रम (Community Development Programm) चलाया गया था।",
  },
  {
    question_en: "The Balwant Rai Mehta Committee (1957) recommended dividing the Panchayati Raj into how many tiers?",
    question_hi: "बलवंत राय मेहता समिति (1957) ने पंचायती राज को कितने स्तरों में बांटने की सिफारिश की थी?",
    options_en: ["Two", "Three", "Four", "Five"],
    options_hi: ["दो", "तीन", "चार", "पाँच"],
    correct_option_index: 1,
    explanation_en: "The Balwant Rai Mehta Committee recommended dividing the Panchayati Raj into 3 tiers (Block/Village/District).",
    explanation_hi: "बलवंत राय मेहता समिति ने पंचायती राज को 3 भागों (ब्लॉक/ग्राम/जिला) में बांटने की सिफारिश की थी।",
  },
  {
    question_en: "In which state was the Panchayati Raj system first implemented on a trial basis in some areas in 1958?",
    question_hi: "पंचायती राज व्यवस्था सर्वप्रथम प्रायोगिक तौर पर किस राज्य के कुछ क्षेत्रों में 1958 में लागू हुई?",
    options_en: ["Rajasthan", "Maharashtra", "Andhra Pradesh", "Karnataka"],
    options_hi: ["राजस्थान", "महाराष्ट्र", "आंध्र प्रदेश", "कर्नाटक"],
    correct_option_index: 2,
    explanation_en: "The report of the Balwant Rai Mehta Committee was accepted in 1958. Its first trial use was in some areas of Andhra Pradesh in 1958.",
    explanation_hi: "बलवंत राय मेहता समिति की रिपोर्ट 1958 में स्वीकार हुई। इसका सर्वप्रथम प्रयोग आंध्र प्रदेश के कुछ क्षेत्रों में 1958 में हुआ।",
  },
  {
    question_en: "The Ashok Mehta Committee (1977) recommended dividing the Panchayati Raj into how many tiers?",
    question_hi: "अशोक मेहता समिति (1977) ने पंचायती राज को कितने भागों में बांटने की सिफारिश की थी?",
    options_en: ["Three", "Four", "Two", "One"],
    options_hi: ["तीन", "चार", "दो", "एक"],
    correct_option_index: 2,
    explanation_en: "The Ashok Mehta Committee recommended dividing the Panchayati Raj into 2 tiers (Zila Parishad, Mandal Panchayat).",
    explanation_hi: "अशोक मेहता समिति ने पंचायती राज को 2 भागों (जिला परिषद, मंडल पंचायत) में बांटने की सिफारिश की थी।",
  },
  {
    question_en: "When is Panchayati Raj Day celebrated?",
    question_hi: "पंचायती राज दिवस कब मनाया जाता है?",
    options_en: ["December 22", "December 23", "April 20", "April 24"],
    options_hi: ["22 दिसंबर", "23 दिसंबर", "20 अप्रैल", "24 अप्रैल"],
    correct_option_index: 3,
    explanation_en: "The Panchayati Raj Act was implemented on April 24, 1993, which is why April 24 is celebrated as Panchayati Raj Day.",
    explanation_hi: "पंचायती राज अधिनियम 24 अप्रैल 1993 को लागू हुआ था, इसलिए 24 अप्रैल को पंचायती राज दिवस मनाया जाता है।",
  },
  {
    question_en: "Which Part was added to the Constitution by the 73rd Constitutional Amendment Act, 1992?",
    question_hi: "73वें संविधान संशोधन अधिनियम, 1992 द्वारा संविधान में कौन सा भाग जोड़ा गया?",
    options_en: ["Part 9", "Part 9A", "Part 9B", "Part 8"],
    options_hi: ["भाग 9", "भाग 9A", "भाग 9B", "भाग 8"],
    correct_option_index: 0,
    explanation_en: "Part 9 (Panchayat Raj) was added by the 73rd CA 1992, which includes Articles 243-243[O] and Schedule 11.",
    explanation_hi: "73वें CA 1992 द्वारा भाग 9 (पंचायत राज) जोड़ा गया, जिसमें अनुच्छेद 243-243[O] और अनुसूची 11 है।",
  },
  {
    question_en: "Under which article is there a provision for 1/3 reservation (33%) for women in Panchayats?",
    question_hi: "किस अनुच्छेद के तहत पंचायतों में महिलाओं के लिए 1/3 भाग (33%) आरक्षण का प्रावधान है?",
    options_en: ["Article 243(B)", "Article 243(D)", "Article 243(I)", "Article 243(K)"],
    options_hi: ["अनुच्छेद 243(B)", "अनुच्छेद 243(D)", "अनुच्छेद 243(I)", "अनुच्छेद 243(K)"],
    correct_option_index: 1,
    explanation_en: "Article 243[D] relates to reservation in Panchayats, such as 1/3 share for women.",
    explanation_hi: "अनुच्छेद 243[D] पंचायतों में आरक्षण (Reservation), जैसे महिलाओं के लिए 1/3 भाग, से संबंधित है।",
  },
  {
    question_en: "Under which article is the State Finance Commission constituted by the Governor?",
    question_hi: "किस अनुच्छेद के तहत राज्य वित्त आयोग (State Finance Commission) का गठन राज्यपाल द्वारा किया जाता है?",
    options_en: ["Article 243(I)", "Article 243(K)", "Article 243(T)", "Article 243(W)"],
    options_hi: ["अनुच्छेद 243(I)", "अनुच्छेद 243(K)", "अनुच्छेद 243(T)", "अनुच्छेद 243(W)"],
    correct_option_index: 0,
    explanation_en: "Article 243[I] relates to the State Finance Commission (by the Governor).",
    explanation_hi: "अनुच्छेद 243[I] राज्य वित्त आयोग (राज्यपाल द्वारा) से संबंधित है।",
  },
  {
    question_en: "Where and when was the First Nagar Nigam (Municipal Corporation) established?",
    question_hi: "प्रथम नगर निगम (First Nagar Nigam) की स्थापना कहाँ और कब हुई थी?",
    options_en: ["Calcutta, 1793", "Madras, 1688", "Bombay, 1688", "Allahabad, 1924"],
    options_hi: ["कलकत्ता, 1793", "मद्रास, 1688", "बंबई, 1688", "इलाहाबाद, 1924"],
    correct_option_index: 1,
    explanation_en: "The first Nagar Nigam was established in Madras in 1688.",
    explanation_hi: "प्रथम नगर निगम 1688 में मद्रास में स्थापित किया गया।",
  },
  {
    question_en: "Which schedule was added to the Constitution by the 74th Constitutional Amendment (1992)?",
    question_hi: "74वें संविधान संशोधन (1992) द्वारा संविधान में कौन सी अनुसूची जोड़ी गई?",
    options_en: ["9th", "10th", "11th", "12th"],
    options_hi: ["9वीं", "10वीं", "11वीं", "12वीं"],
    correct_option_index: 3,
    explanation_en: "The 12th Schedule, relating to Municipalities, was added by the 74th CA 1992.",
    explanation_hi: "74वें CA 1992 द्वारा 12वीं अनुसूची जोड़ी गई, जो नगर पालिकाओं से संबंधित है।",
  },
  {
    question_en: "The First Constitutional Amendment Act, 1951, was primarily related to which subject?",
    question_hi: "पहला संविधान संशोधन अधिनियम, 1951 मुख्य रूप से किससे संबंधित था?",
    options_en: ["Citizenship", "Fundamental Rights", "Land Reform Laws", "Reorganisation of States"],
    options_hi: ["नागरिकता", "मौलिक अधिकार", "भूमि सुधार कानून", "राज्यों का पुनर्गठन"],
    correct_option_index: 2,
    explanation_en: "The First Constitutional Amendment Act, 1951, added the 9th Schedule, which relates to Land Reform Laws.",
    explanation_hi: "प्रथम संविधान संशोधन अधिनियम 1951 द्वारा अनुसूची 9 जोड़ी गई, जो भूमि सुधार कानून (Land Reform) से संबंधित है।",
  },
  {
    question_en: "Which Constitutional Amendment is called the 'Mini Constitution'?",
    question_hi: "किस संविधान संशोधन को 'लघु संविधान' (Mini Constitution) कहा जाता है?",
    options_en: ["7th CA, 1956", "42nd CA, 1976", "44th CA, 1978", "61st CA, 1988"],
    options_hi: ["7वां CA, 1956", "42वां CA, 1976", "44वां CA, 1978", "61वां CA, 1988"],
    correct_option_index: 1,
    explanation_en: "The 42nd Constitutional Amendment, 1976, is called the 'Mini Constitution'.",
    explanation_hi: "42वां संविधान संशोधन, 1976 'लघु संविधान' (Mini Constitution) कहलाता है।",
  },
  {
    question_en: "The ban on defection (Anti Defection Law) is related to which constitutional amendment?",
    question_hi: "दलबदल पर रोक (Anti Defection Law) किस संविधान संशोधन से संबंधित है?",
    options_en: ["42nd CA", "52nd CA", "61st CA", "69th CA"],
    options_hi: ["42वां CA", "52वां CA", "61वां CA", "69वां CA"],
    correct_option_index: 1,
    explanation_en: "The 52nd Constitutional Amendment, 1985, added the 10th Schedule, which relates to the ban on defection.",
    explanation_hi: "52वां संविधान संशोधन, 1985 द्वारा अनुसूची 10 जोड़ी गई, जो दल-बदल पर रोक से संबंधित है।",
  },
  {
    question_en: "By which constitutional amendment was Delhi given the status of National Capital Region (NCR)?",
    question_hi: "दिल्ली को राष्ट्रीय राजधानी क्षेत्र (NCR) का दर्जा किस संविधान संशोधन द्वारा दिया गया?",
    options_en: ["61st CA", "69th CA", "70th CA", "71st CA"],
    options_hi: ["61वां CA", "69वां CA", "70वां CA", "71वां CA"],
    correct_option_index: 1,
    explanation_en: "The 69th Constitutional Amendment, 1991, gave special status to Delhi and created the National Capital Region (NCR).",
    explanation_hi: "69वें संविधान संशोधन, 1991 द्वारा दिल्ली को विशेष दर्जा दिया गया और राष्ट्रीय राजधानी क्षेत्र (NCR) बनाया गया।",
  },
  {
    question_en: "The provision for GST (Goods and Services Tax) was made by which constitutional amendment?",
    question_hi: "GST (वस्तु एवं सेवा कर) का प्रावधान किस संविधान संशोधन द्वारा किया गया?",
    options_en: ["92nd CA", "95th CA", "101st CA", "103rd CA"],
    options_hi: ["92वां CA", "95वां CA", "101वां CA", "103वां CA"],
    correct_option_index: 2,
    explanation_en: "The provision for GST was made by the 101st Constitutional Amendment, 2016.",
    explanation_hi: "101वां संविधान संशोधन, 2016 द्वारा GST का प्रावधान किया गया।",
  },
  {
    question_en: "In which article is the GST Council described, and who is its chairman?",
    question_hi: "GST परिषद (GST Council) का वर्णन किस अनुच्छेद में है और इसके अध्यक्ष कौन होते हैं?",
    options_en: ["Article 279, Finance Minister", "Article 269, Prime Minister", "Article 246, Finance Minister", "Article 279, Prime Minister"],
    options_hi: ["अनुच्छेद 279, वित्त मंत्री", "अनुच्छेद 269, प्रधानमंत्री", "अनुच्छेद 246, वित्त मंत्री", "अनुच्छेद 279, प्रधानमंत्री"],
    correct_option_index: 0,
    explanation_en: "Article 279 relates to the constitution of the GST Council, whose chairman is the Finance Minister.",
    explanation_hi: "अनुच्छेद 279 GST परिषद के गठन से संबंधित है, जिसके अध्यक्ष वित्त मंत्री होते हैं।",
  },
  {
    question_en: "What is the tenure of the Chairman and members of the UPSC?",
    question_hi: "यूपीएससी (UPSC) के अध्यक्ष एवं सदस्यों का कार्यकाल कितना होता है?",
    options_en: ["6 years or 62 years", "6 years or 65 years", "5 years or 65 years", "5 years or 62 years"],
    options_hi: ["6 वर्ष या 62 वर्ष", "6 वर्ष या 65 वर्ष", "5 वर्ष या 65 वर्ष", "5 वर्ष या 62 वर्ष"],
    correct_option_index: 1,
    explanation_en: "The tenure of the Chairman and members of UPSC is 6 years or 65 years of age (whichever is earlier).",
    explanation_hi: "यूपीएससी के अध्यक्ष एवं सदस्यों का कार्यकाल 6 वर्ष या 65 वर्ष (जो भी पहले हो) होता है।",
  },
  {
    question_en: "Under which article can the members of the State Public Service Commission (SPSC) be removed by the President?",
    question_hi: "किस अनुच्छेद के तहत राज्य लोक सेवा आयोग (SPSC) के सदस्यों को राष्ट्रपति द्वारा हटाया जा सकता है?",
    options_en: ["Article 315", "Article 316", "Article 317", "Article 318"],
    options_hi: ["अनुच्छेद 315", "अनुच्छेद 316", "अनुच्छेद 317", "अनुच्छेद 318"],
    correct_option_index: 2,
    explanation_en: "Under Article 317, the members of UPSC and SPSC are removed by the President.",
    explanation_hi: "अनुच्छेद 317 के तहत UPSC और SPSC के सदस्यों को राष्ट्रपति द्वारा हटाया जाता है।",
  },
  {
    question_en: "Who was the First Chairman of UPSC?",
    question_hi: "UPSC के प्रथम अध्यक्ष (First Chairman) कौन थे?",
    options_en: ["Ajay Kumar", "Sir Ross Barker", "B.N. Rao", "Sachchidananda Sinha"],
    options_hi: ["अजय कुमार", "राज वाकर", "बी.एन. राव", "सच्चिदानंद सिन्हा"],
    correct_option_index: 1,
    explanation_en: "The first chairman of UPSC was 'Sir Ross Barker'. (Note: The Hindi option 'राज वाकर' likely refers to 'Ross Barker').",
    explanation_hi: "UPSC के प्रथम अध्यक्ष \"राज वाकर\" (Sir Ross Barker) थे।",
  }
];

export default test2Questions;