import type { QuizQuestion } from '../../../types';

const test6Questions: QuizQuestion[] = [

  {
    question_en: "What was the total expenditure amount of the East India Company under the Charter Act of 1600 AD?",
    question_hi: "1600 ई. के राजलेख (Charter Act of 1600 AD) के तहत ईस्ट इंडिया कंपनी के कुल खर्च की राशि कितनी थी?",
    options_en: ["217 Pounds", "30,133 Pounds", "12,000 Pounds", "64 Lakh Rupees"],
    options_hi: ["217 पाउंड", "30,133 पाउंड", "12,000 पाउंड", "64 लाख रुपये"],
    correct_option_index: 1,
    explanation_en: "Under the Charter Act of 1600, the total expenditure was 30,133 Pounds.",
    explanation_hi: "1600 ई. के राजलेख के तहत कुल खर्च 30,133 पाउंड था।",
  },
  {
    question_en: "By which Act were the salaries of the members of the Board of Control started to be paid from the Indian Revenue?",
    question_hi: "किस अधिनियम द्वारा नियंत्रक मंडल (Board of Control) के सदस्यों का वेतन भारतीय राजस्व (Indian Revenue) से दिया जाने लगा?",
    options_en: ["Pitts India Act of 1784", "Charter Act of 1793", "Charter Act of 1813", "Charter Act of 1833"],
    options_hi: ["1784 का पिट्स इंडिया एक्ट", "1793 का चार्टर एक्ट", "1813 का राजलेख", "1833 का राजलेख"],
    correct_option_index: 1,
    explanation_en: "Under the Charter Act of 1793, the salaries of the members of the Board of Control began to be paid from the Indian Revenue.",
    explanation_hi: "1793 के चार्टर एक्ट के तहत नियंत्रक मंडल के सदस्यों को वेतन भारतीय राजस्व (Indian Revenue) से दिया जाने लगा।",
  },
  {
    question_en: "Under which Act was slavery (Das Pratha) abolished by the Governor-General in 1843?",
    question_hi: "किस अधिनियम के तहत दास प्रथा (Slavery) को 1843 में गवर्नर जनरल द्वारा समाप्त कर दिया गया?",
    options_en: ["Charter Act of 1813", "Charter Act of 1833", "Charter Act of 1853", "Act of 1858"],
    options_hi: ["1813 का राजलेख", "1833 का राजलेख", "1853 का राजलेख", "1858 का अधिनियम"],
    correct_option_index: 1,
    explanation_en: "By the Charter Act of 1833, slavery was abolished in 1843 by Governor-General Ellenborough.",
    explanation_hi: "1833 के राजलेख द्वारा 1843 में गवर्नर जनरल एलनबरो द्वारा दास प्रथा समाप्त कर दी गई।",
  },
  {
    question_en: "In which year did the separation in Sindh (Sindh) occur during the provincial elections held in 1937?",
    question_hi: "1937 में हुए प्रांतीय चुनाव में सिंध (Sindh) में किस वर्ष पृथक्करण हुआ था?",
    options_en: ["1935", "1939", "1943", "1947"],
    options_hi: ["1935", "1939", "1943", "1947"],
    correct_option_index: 2,
    explanation_en: "The separation of cooperative cooperation in Sindh occurred in 1943.",
    explanation_hi: "सिंध में सहकारी सहयोग का पृथक्करण 1943 में हुआ था।",
  },
  {
    question_en: "Who was the first Indian member to join the Viceroy's Executive Council under the Act of 1909?",
    question_hi: "1909 के अधिनियम के तहत वायसराय की कार्यकारिणी में शामिल होने वाले प्रथम भारतीय सदस्य कौन थे?",
    options_en: ["K.C. Gupta", "S.P. Sinha", "Syed Hussain Bilgrami", "Vallabh Bhai Patel"],
    options_hi: ["के.सी. गुप्ता", "एस.पी. सिन्हा", "सैयद हुसैन बिलग्रामी", "वल्लभ भाई पटेल"],
    correct_option_index: 1,
    explanation_en: "S.P. Sinha was included in the Viceroy's Executive Council.",
    explanation_hi: "एस.पी. सिन्हा को वायसराय की कार्यकारिणी में शामिल किया गया।",
  },
  {
    question_en: "What is the correct fact related to Tej Bahadur Sapru and Jayaprakash Narayan in the Constituent Assembly?",
    question_hi: "संविधान सभा में तेज बहादुर सप्रू एवं जयप्रकाश नारायण से संबंधित सही तथ्य क्या है?",
    options_en: ["They were members of the Drafting Committee.", "They did not accept the membership of the Constituent Assembly.", "They were nominated members of the Constituent Assembly.", "They represented SC & ST."],
    options_hi: ["वे प्रारूप समिति के सदस्य थे।", "उन्होंने संविधान सभा की सदस्यता स्वीकार नहीं की।", "वे संविधान सभा के मनोनीत सदस्य थे।", "वे SC एवं ST का प्रतिनिधित्व करते थे।"],
    correct_option_index: 1,
    explanation_en: "Tej Bahadur Sapru and Jayaprakash Narayan had not accepted the membership of the Constituent Assembly.",
    explanation_hi: "तेज बहादुर सप्रू एवं जयप्रकाश नारायण ने संविधान सभा की सदस्यता स्वीकार नहीं की थी।",
  },
  {
    question_en: "Who wrote the original draft (Draft) of the Constitution?",
    question_hi: "संविधान का मूल प्रारूप (Draft) किसके द्वारा लिखा गया था?",
    options_en: ["Dr. B.R. Ambedkar", "B.N. Rau", "S.N. Mukherjee", "Sachchidananda Sinha"],
    options_hi: ["डॉ. बी.आर. अम्बेडकर", "बी.एन. राव", "एस.एन. मुखर्जी", "सच्चिदानंद सिन्हा"],
    correct_option_index: 2,
    explanation_en: "The chief draftsman of the Constituent Assembly was S.N. Mukharji.",
    explanation_hi: "संविधान सभा के मुख्य प्रारूपकार/Draftsman एस.एन. बनर्जी (S.N. Mukharji) थे।",
  },
  {
    question_en: "Who did the Hindi Calligraphy for the Constituent Assembly?",
    question_hi: "संविधान सभा के लिए हिंदी सुलेखन (Hindi Calligraphy) किसने किया था?",
    options_en: ["Nandalal Bose", "Prem Behari Narain Raizada", "Vasant Krishan Vaidya", "B.N. Rau"],
    options_hi: ["नंदलाल बोस", "प्रेम बिहारी नारायण रायजादा", "वसंत कृष्ण वैद्य", "बी.एन. राव"],
    correct_option_index: 2,
    explanation_en: "The calligraphy of the Hindi version was done by Vasant Krishan Vaidya.",
    explanation_hi: "हिंदी संस्करण का सुलेखन वसंत कृष्ण वैद्य द्वारा किया गया था।",
  },
  {
    question_en: "Which region/state did Annie Mascarene, one of the prominent women members of the Constituent Assembly, represent?",
    question_hi: "संविधान सभा की प्रमुख महिला सदस्यों में से एनी मस्केरिनी किस क्षेत्र/राज्य का प्रतिनिधित्व करती थीं?",
    options_en: ["United Provinces", "Madras", "Central Provinces", "Travancore"],
    options_hi: ["उत्तर प्रदेश", "मद्रास", "मध्य प्रांत", "त्रावणकोर"],
    correct_option_index: 3,
    explanation_en: "Annie Mascarene was from Travancore.",
    explanation_hi: "एनी मस्केरिनी त्रावणकोर से थीं।",
  },
  {
    question_en: "Who called the Preamble the \"Key of Constitution\"?",
    question_hi: "प्रस्तावना को \"संविधान की कुंजी\" (Key of Constitution) किसने कहा था?",
    options_en: ["Nani Palkhivala", "Dr. Rajendra Prasad", "K.M. Munshi", "Thakur Das Bhargava"],
    options_hi: ["नाना साहेब पालखीवाला", "डॉ. राजेंद्र प्रसाद", "के.एम. मुंशी", "ठाकुर दास भार्गव"],
    correct_option_index: 1,
    explanation_en: "Rajendra Prasad called the Preamble the \"Key of Constitution\".",
    explanation_hi: "राजेंद्र प्रसाद ने प्रस्तावना को \"संविधान की कुंजी है/Key of Constitution\" कहा था।",
  },
  {
    question_en: "From which country's constitution was the idea of 'Fraternity' in the Preamble taken?",
    question_hi: "प्रस्तावना में 'बंधुत्व' (Fraternity) का विचार किस देश के संविधान से लिया गया है?",
    options_en: ["America", "Russia", "France", "Australia"],
    options_hi: ["अमेरिका", "रूस", "फ्रांस", "ऑस्ट्रेलिया"],
    correct_option_index: 2,
    explanation_en: "The words Equality, Liberty, and Fraternity are inspired by France.",
    explanation_hi: "समानता, स्वतंत्रता, बंधुत्व शब्द फ्रांस से प्रेरित हैं।",
  },
  {
    question_en: "From which country is the principle of 'Procedure established by Law' in the Indian Constitution taken?",
    question_hi: "भारतीय संविधान में 'विधि द्वारा स्थापित प्रक्रिया' (Procedure established by Law) का सिद्धांत किस देश से लिया गया है?",
    options_en: ["USA", "Germany", "Japan", "South Africa"],
    options_hi: ["USA", "जर्मनी", "जापान", "दक्षिण अफ्रीका"],
    correct_option_index: 2,
    explanation_en: "The 'Procedure established by Law' mentioned in Article-21 is taken from Japan.",
    explanation_hi: "अनुच्छेद-21 में वर्णित 'विधि द्वारा स्थापित प्रक्रिया' जापान से ली गई है।",
  },
  {
    question_en: "How many seats are allotted to Kerala under the Fourth Schedule (Allocation of Rajya Sabha seats)?",
    question_hi: "चौथी अनुसूची (राज्यसभा सीटों का बंटवारा) के तहत केरल को कितनी सीटें आवंटित हैं?",
    options_en: ["7", "9", "10", "12"],
    options_hi: ["7", "9", "10", "12"],
    correct_option_index: 1,
    explanation_en: "9 seats are allotted to Kerala in the Rajya Sabha.",
    explanation_hi: "केरल को राज्यसभा में 9 सीटें आवंटित हैं।",
  },
  {
    question_en: "How many Rajya Sabha seats are allotted to Punjab under the Fourth Schedule?",
    question_hi: "चौथी अनुसूची के तहत पंजाब को कितनी राज्यसभा सीटें आवंटित हैं?",
    options_en: ["11", "9", "7", "6"],
    options_hi: ["11", "9", "7", "6"],
    correct_option_index: 2,
    explanation_en: "7 seats are allotted to Punjab in the Rajya Sabha.",
    explanation_hi: "पंजाब को राज्यसभा में 7 सीटें आवंटित हैं।",
  },
  {
    question_en: "From which country has the provision of Division of Powers between the Center and States and the Concurrent List been taken?",
    question_hi: "केंद्र और राज्यों के बीच शक्तियों का विभाजन (Division of Powers) तथा समवर्ती सूची का प्रावधान किस देश से लिया गया है?",
    options_en: ["Ireland", "Canada", "Germany", "Australia"],
    options_hi: ["आयरलैंड", "कनाडा", "जर्मनी", "ऑस्ट्रेलिया"],
    correct_option_index: 3,
    explanation_en: "The division of powers and the Concurrent List are taken from Australia.",
    explanation_hi: "शक्तियों का विभाजन और समवर्ती सूची ऑस्ट्रेलिया से लिया गया है।",
  },
  {
    question_en: "How many subjects were originally included in the Union List in the original Constitution?",
    question_hi: "मूल संविधान में संघ सूची (Union List) के अंतर्गत कुल कितने विषय (Subjects) शामिल थे?",
    options_en: ["66", "97", "47", "100"],
    options_hi: ["66", "97", "47", "100"],
    correct_option_index: 1,
    explanation_en: "The Union List originally had 97 subjects (currently 100).",
    explanation_hi: "संघ सूची में पहले 97 विषय थे (वर्तमान में 100)।",
  },
  {
    question_en: "Under the Citizenship Act 1955, where is it necessary to register within 1 year of obtaining citizenship By Descent?",
    question_hi: "नागरिकता अधिनियम 1955 के तहत वंश परंपरा (By Descent) द्वारा नागरिकता प्राप्त करने पर 1 वर्ष के भीतर कहाँ पंजीकरण कराना आवश्यक है?",
    options_en: ["Ministry of Home Affairs", "Indian Consulate", "District Magistrate", "Ministry of External Affairs"],
    options_hi: ["गृह मंत्रालय", "भारतीय वाणिज्य दूतावास/Indian Consulate", "जिला मजिस्ट्रेट", "विदेश मंत्रालय"],
    correct_option_index: 1,
    explanation_en: "It is necessary to register at the Indian Consulate within 1 year of birth.",
    explanation_hi: "जन्म के 1 वर्ष के भीतर भारतीय वाणिज्य दूतावास (Indian Consulate) में पंजीकरण कराना आवश्यक है।",
  },
  {
    question_en: "Among the three ways of terminating citizenship, under 'Deprivation', if a person is sentenced by another country within 5 years of naturalization, what is the duration of the sentence that can lead to deprivation of citizenship?",
    question_hi: "नागरिकता समाप्त होने के तीन प्रकारों में से 'वंचित किया जाना' (Deprivation) के तहत यदि किसी व्यक्ति को देशीयकरण के 5 वर्ष के भीतर किसी अन्य देश द्वारा कितनी सज़ा दी जाती है, तो उसकी नागरिकता छीनी जा सकती है?",
    options_en: ["1 year sentence", "2 years sentence", "5 years sentence", "7 years sentence"],
    options_hi: ["1 वर्ष की सज़ा", "2 वर्ष की सज़ा", "5 वर्ष की सज़ा", "7 वर्ष की सज़ा"],
    correct_option_index: 1,
    explanation_en: "A person can be deprived of citizenship if they are sentenced to 2 years by another country within 5 years of obtaining citizenship by registration or naturalization.",
    explanation_hi: "पंजीकरण या देशीयकरण द्वारा नागरिकता प्राप्त करने के 5 वर्ष के भीतर किसी अन्य देश द्वारा 2 वर्ष की सज़ा पाने पर वंचित किया जा सकता है।",
  },
  {
    question_en: "Which institution/authority is not included in the definition of 'State' under Article 12?",
    question_hi: "अनुच्छेद 12 के तहत 'राज्य' (State) की परिभाषा में कौन सी संस्था/प्राधिकारी शामिल नहीं है?",
    options_en: ["Government of India", "Local Authorities", "Parliament", "Government of any other country"],
    options_hi: ["भारत सरकार", "स्थानीय निकाय (Local Authorities)", "संसद", "किसी अन्य देश की सरकार"],
    correct_option_index: 3,
    explanation_en: "The definition of State includes the Government of India, Parliament, State Government, State Legislature, local bodies, and other bodies, but there is no mention of the government of any other country.",
    explanation_hi: "राज्य की परिभाषा में भारत सरकार, संसद, राज्य सरकार, राज्य विधानमंडल, स्थानीय निकाय और अन्य निकाय शामिल हैं, लेकिन किसी अन्य देश की सरकार का उल्लेख नहीं है।",
  },
  {
    question_en: "Under which fundamental right is the Protection of Women from Domestic Violence Act 2005 provided?",
    question_hi: "किस मौलिक अधिकार के तहत महिलाओं को घरेलू हिंसा से संरक्षण अधिनियम 2005 दिया गया है?",
    options_en: ["Article 14", "Article 15(3)", "Article 16(4)", "Article 19(1)(A)"],
    options_hi: ["अनुच्छेद 14", "अनुच्छेद 15(3)", "अनुच्छेद 16(4)", "अनुच्छेद 19(1)(A)"],
    correct_option_index: 1,
    explanation_en: "The note of Article 15(3) mentions the Protection of Women from Domestic Violence Act 2005.",
    explanation_hi: "अनुच्छेद 15(3) के नोट में महिलाओं के घरेलू हिंसा से संरक्षण अधिनियम 2005 का उल्लेख है।",
  },
  {
    question_en: "Which freedom is not included under Article 19(1)(A)?",
    question_hi: "अनुच्छेद 19(1)(A) के तहत कौन सी स्वतंत्रता शामिल नहीं है?",
    options_en: ["Right to Know", "Right to hoist the National Flag", "Freedom of the Press", "Freedom of peaceful and unarmed assembly"],
    options_hi: ["जानने का अधिकार (Right to Know)", "राष्ट्रीय ध्वज फहराने का अधिकार", "प्रेस की स्वतंत्रता", "शांतिपूर्वक एवं निरायुध सम्मेलन की स्वतंत्रता"],
    correct_option_index: 3,
    explanation_en: "Freedom of peaceful and unarmed assembly is under Article 19(1)(B).",
    explanation_hi: "शांतिपूर्वक एवं निरायुध सम्मेलन की स्वतंत्रता अनुच्छेद 19(1)(B) के अंतर्गत है।",
  },
  {
    question_en: "Which writ (Writ) literally means \"What is your authority?\"",
    question_hi: "किस रिट (Writ) का शाब्दिक अर्थ है \"आपका प्राधिकार क्या है?\"",
    options_en: ["Habeas Corpus", "Mandamus", "Quo Warranto", "Certiorari"],
    options_hi: ["बंदी प्रत्यक्षीकरण (Habeas Corpus)", "परमादेश (Mandamus)", "अधिकार पृच्छा (Quo Warranto)", "उत्प्रेषण (Certiorari)"],
    correct_option_index: 2,
    explanation_en: "Quo Warranto literally means \"What is your authority?\".",
    explanation_hi: "अधिकार पृच्छा (Quo Warranto) का शाब्दिक अर्थ है \"आपका प्राधिकार क्या है?\"।",
  },
  {
    question_en: "Under the exceptions to Fundamental Rights, Article 33 gives Parliament the power to make special provisions for persons related to which institutions?",
    question_hi: "मौलिक अधिकारों के अपवाद के तहत, अनुच्छेद 33 में किन संस्थाओं से संबंधित व्यक्तियों के लिए विशेष प्रावधान बनाने का अधिकार संसद को है?",
    options_en: ["Only Armed Forces", "Forces charged with the maintenance of public order", "Intelligence Bureau", "All of the above"],
    options_hi: ["केवल सशस्त्र बलों", "लोक व्यवस्था के दायित्वधीन बल", "आसूचना ब्यूरो", "उपरोक्त सभी"],
    correct_option_index: 3,
    explanation_en: "Article 33 provides for modifying/restricting the fundamental rights of persons related to the Armed Forces, forces charged with the maintenance of public order, and the Intelligence Bureau.",
    explanation_hi: "अनुच्छेद 33 सशस्त्र बलों, लोक व्यवस्था के दायित्वधीन बल, और आसूचना ब्यूरो (Intelligence Bureau) से संबंधित व्यक्तियों के मौलिक अधिकारों में संशोधन/सीमित करने का प्रावधान करता है।",
  },
  {
    question_en: "Who called DPSP \"A cheque that pays at the bank's convenience\"?",
    question_hi: "DPSP को \"एक ऐसा चेक जो बैंक की सुविधा अनुसार अदा किया जाता है\" (A cheque that pays at the bank's convenience) किसने कहा था?",
    options_en: ["Dr. B.R. Ambedkar", "G. Austin", "K.T. Shah", "T.T. Krishnamachari"],
    options_hi: ["डॉ. बी.आर. अम्बेडकर", "जी. ऑस्टिन", "के.टी. शाह", "टी.टी. कृष्णामाचारी"],
    correct_option_index: 2,
    explanation_en: "This statement is by K.T. Shah.",
    explanation_hi: "यह कथन के.टी. शाह का है।",
  },
  {
    question_en: "Which article under DPSP comes under the Liberal-Intellectual Principles?",
    question_hi: "DPSP के तहत कौन सा अनुच्छेद उदार-बौद्धिक सिद्धांतों (Liberal-Intellectual Principles) के अंतर्गत आता है?",
    options_en: ["Article 40", "Article 43B", "Article 44", "Article 39"],
    options_hi: ["अनुच्छेद 40", "अनुच्छेद 43B", "अनुच्छेद 44", "अनुच्छेद 39"],
    correct_option_index: 2,
    explanation_en: "Articles 44, 45, 48A, 49, 50, and 51 come under the Liberal-Intellectual Principles.",
    explanation_hi: "उदार-बौद्धिक सिद्धांतों के अंतर्गत अनुच्छेद 44, 45, 48A, 49, 50 तथा 51 आते हैं।",
  },
  {
    question_en: "Which was the first state after independence to implement the Uniform Civil Code (UCC)?",
    question_hi: "समान नागरिक संहिता (UCC) को लागू करने वाला आजादी के बाद प्रथम राज्य कौन सा था?",
    options_en: ["Goa", "Uttarakhand", "Maharashtra", "Gujarat"],
    options_hi: ["गोवा", "उत्तराखंड", "महाराष्ट्र", "गुजरात"],
    correct_option_index: 1,
    explanation_en: "The first state to implement UCC after independence was Uttarakhand (the source mentions Goa as the first state).",
    explanation_hi: "आजादी के बाद UCC लागू करने वाला प्रथम राज्य उत्तराखंड था (स्रोत में गोवा को प्रथम राज्य बताया गया है)।",
  },
  {
    question_en: "What is Article 46 related to?",
    question_hi: "अनुच्छेद 46 किससे संबंधित है?",
    options_en: ["Just and humane conditions of work", "Primary care for children below 6 years of age", "Provision for economic and educational development of SC/ST", "International peace and security"],
    options_hi: ["काम की न्यायसंगत दशाएं", "6 वर्ष से कम आयु के बच्चों के लिए प्राथमिक देखभाल", "SC/ST के आर्थिक एवं शैक्षणिक विकास का प्रावधान", "अंतर्राष्ट्रीय शांति एवं सुरक्षा"],
    correct_option_index: 2,
    explanation_en: "Article 46 is related to the provision for the economic and educational development of SC and ST.",
    explanation_hi: "अनुच्छेद 46 SC तथा ST के आर्थिक एवं शैक्षणिक विकास के प्रावधान से संबंधित है।",
  },
  {
    question_en: "Under which article does the state government conduct (Regulation) the business of the state?",
    question_hi: "किस अनुच्छेद के तहत राज्य सरकार राज्य के कार्यों का संचालन (Regulation) करती है?",
    options_en: ["Article 164", "Article 166", "Article 167", "Article 177"],
    options_hi: ["अनुच्छेद 164", "अनुच्छेद 166", "अनुच्छेद 167", "अनुच्छेद 177"],
    correct_option_index: 1,
    explanation_en: "Article 166 is related to the Conduct of business of the Government of a State (Regulation).",
    explanation_hi: "अनुच्छेद 166 राज्य सरकार का संचालन (Regulate the State Government) से संबंधित है।",
  },
  {
    question_en: "Which article contains the provision for the Governor to give Assent to a bill passed by the state legislature?",
    question_hi: "राज्य विधानमंडल द्वारा पारित विधेयक को राज्यपाल द्वारा स्वीकृति (Assent) देने का प्रावधान किस अनुच्छेद में है?",
    options_en: ["Article 170", "Article 174", "Article 200", "Article 213"],
    options_hi: ["अनुच्छेद 170", "अनुच्छेद 174", "अनुच्छेद 200", "अनुच्छेद 213"],
    correct_option_index: 2,
    explanation_en: "Article 200 is related to the Assent (Permission) of the Governor to a bill passed by the state legislature.",
    explanation_hi: "अनुच्छेद 200 राज्य विधानमंडल द्वारा पारित विधेयक को राज्यपाल की स्वीकृति (Permission) से संबंधित है।",
  },
  {
    question_en: "In which article is it mentioned that the oath of office to the Supreme Court judges is administered by the President?",
    question_hi: "सुप्रीम कोर्ट के न्यायाधीशों को उनके पद की शपथ राष्ट्रपति द्वारा दिलाई जाती है, यह किस अनुच्छेद में वर्णित है?",
    options_en: ["Article 124(4)", "Article 124(5)", "Article 124(6)", "Article 124(7)"],
    options_hi: ["अनुच्छेद 124(4)", "अनुच्छेद 124(5)", "अनुच्छेद 124(6)", "अनुच्छेद 124(7)"],
    correct_option_index: 2,
    explanation_en: "Article 124(6) is related to the administration of the Oath to SC judges by the President.",
    explanation_hi: "अनुच्छेद 124(6) SC के न्यायाधीशों को राष्ट्रपति द्वारा शपथ (Oath) दिलाए जाने से संबंधित है।",
  },
  {
    question_en: "The salary of High Court (High Court) judges is paid from the Consolidated Fund of the State, but from which fund is their pension paid?",
    question_hi: "उच्च न्यायालय (High Court) के न्यायाधीशों का वेतन राज्य की संचित निधि से दिया जाता है, लेकिन उनकी पेंशन किस निधि से दी जाती है?",
    options_en: ["Consolidated Fund of the State", "Consolidated Fund of India", "Contingency Fund of India", "Public Account Fund"],
    options_hi: ["राज्य की संचित निधि", "भारत की संचित निधि", "भारत की आकस्मिक निधि", "लोक लेखा निधि"],
    correct_option_index: 1,
    explanation_en: "The salary of High Court judges is paid from the Consolidated Fund of the State, while the pension is paid from the Consolidated Fund of India.",
    explanation_hi: "हाई कोर्ट के न्यायाधीशों का वेतन राज्य की संचित निधि से, जबकि पेंशन भारत की संचित निधि (Consolidated fund of India) से दी जाती है।",
  },
  {
    question_en: "After 2014, what was the maximum expenditure for candidates in Lok Sabha elections increased to, from 30 lakhs for smaller states?",
    question_hi: "लोकसभा के निर्वाचन में 2014 के बाद सरकार द्वारा उम्मीदवारों के अधिकतम खर्च को छोटे राज्यों के लिए 30 लाख से बढ़ाकर कितना किया गया था?",
    options_en: ["40 Lakhs", "54 Lakhs", "70 Lakhs", "77 Lakhs"],
    options_hi: ["40 लाख", "54 लाख", "70 लाख", "77 लाख"],
    correct_option_index: 1,
    explanation_en: "The expenditure for smaller states was increased from 30 lakh to 54 lakh rupees.",
    explanation_hi: "छोटे राज्यों के लिए खर्च को 30 लाख से बढ़ाकर 54 लाख रुपये किया गया था।",
  },
  {
    question_en: "In which state's Tharur assembly constituency were EVMs (Electronic Voting Machines) first used in 1982 at some polling stations?",
    question_hi: "EVM (इलेक्ट्रॉनिक वोटिंग मशीन) का सर्वप्रथम प्रयोग 1982 में किस राज्य के थरूर विधान सभा क्षेत्र के कुछ polling stations पर किया गया था?",
    options_en: ["Tamil Nadu", "Goa", "Kerala", "Madhya Pradesh"],
    options_hi: ["तमिलनाडु", "गोवा", "केरल", "मध्य प्रदेश"],
    correct_option_index: 2,
    explanation_en: "EVMs were first used in 1982 in parts of the Tharur assembly constituency during the Kerala assembly elections.",
    explanation_hi: "EVM का सर्वप्रथम प्रयोग 1982 में केरल विधान सभा चुनाव में थरूर विधान सभा क्षेत्र के कुछ हिस्सों पर किया गया था।",
  },
  {
    question_en: "What was the main provision of the 95th Constitutional Amendment, 2009?",
    question_hi: "95वें संविधान संशोधन, 2009 का मुख्य प्रावधान क्या था?",
    options_en: ["Provision for GST", "Cooperative Societies", "Extending reservation for SC/ST for 10 years", "Restricting defection"],
    options_hi: ["GST का प्रावधान", "सहकारी समितियाँ", "SC/ST के लिए आरक्षण को 10 वर्ष तक बढ़ाना", "दलबदल पर रोक लगाना"],
    correct_option_index: 2,
    explanation_en: "Under the 95th Constitutional Amendment, 2009, the reservation for SC/ST was extended for 10 years (from 26 January 2010 to 26 January 2020).",
    explanation_hi: "95वें संविधान संशोधन, 2009 के तहत SC/ST के लिए आरक्षण को 10 वर्ष (26 जनवरी 2010 से 26 जनवरी 2020 तक) के लिए बढ़ा दिया गया था।",
  },
  {
    question_en: "How many members are there in the GST Council (GST Council)?",
    question_hi: "GST परिषद (GST Council) में कुल कितने सदस्य होते हैं?",
    options_en: ["31", "33", "25", "40"],
    options_hi: ["31", "33", "25", "40"],
    correct_option_index: 1,
    explanation_en: "The GST Council is constituted under Article 279, and it has a total of 33 members.",
    explanation_hi: "अनुच्छेद 279 के तहत GST परिषद का गठन किया जाता है, जिसमें कुल 33 सदस्य होते हैं।",
  }

];

export default test6Questions;