import type { QuizQuestion } from '../../../types';

const test3Questions: QuizQuestion[] = [
  {
    question_en: "Under which article can the Governor be appointed as the Governor of two or more states?",
    question_hi: "किस अनुच्छेद के तहत राज्यपाल दो या दो से अधिक राज्यों का राज्यपाल बनाया जा सकता है?",
    options_en: ["Article 153", "Article 154", "Article 155", "Article 157"],
    options_hi: ["अनुच्छेद 153", "अनुच्छेद 154", "अनुच्छेद 155", "अनुच्छेद 157"],
    correct_option_index: 0,
    explanation_en: "The note under Article 153 mentions the 7th CA 1956, under which one person can be appointed as the Governor of two or more states.",
    explanation_hi: "अनुच्छेद 153 के नोट में 7वें CA 1956 का उल्लेख है, जिसके तहत एक राज्यपाल को 2 या 2 से अधिक राज्यों का राज्यपाल बनाया जा सकता है।",
  },
  {
    question_en: "Who appoints the Governor?",
    question_hi: "राज्यपाल की नियुक्ति कौन करता है?",
    options_en: ["Chief Minister", "Chief Justice of the Supreme Court", "President", "Chief Justice of the High Court"],
    options_hi: ["मुख्यमंत्री", "सर्वोच्च न्यायालय का मुख्य न्यायाधीश", "राष्ट्रपति", "उच्च न्यायालय का मुख्य न्यायाधीश"],
    correct_option_index: 2,
    explanation_en: "Under Article 155, the Governor is appointed by the President on the advice of the Union Council of Ministers.",
    explanation_hi: "अनुच्छेद 155 के तहत राज्यपाल की नियुक्ति राष्ट्रपति द्वारा संघीय मंत्रिपरिषद की सलाह पर की जाती है।",
  },
  {
    question_en: "The Governor's normal tenure is 5 years, but under whose pleasure does he hold office?",
    question_hi: "राज्यपाल का सामान्य कार्यकाल 5 वर्ष होता है, लेकिन वह किसके प्रसाद पर्यंत (Pleasure) पद धारण करता है?",
    options_en: ["Prime Minister", "Chief Minister", "President", "Chief Justice of India"],
    options_hi: ["प्रधानमंत्री", "मुख्यमंत्री", "राष्ट्रपति", "भारत का मुख्य न्यायाधीश"],
    correct_option_index: 2,
    explanation_en: "Under Article 156, the Governor holds office during the pleasure of the President.",
    explanation_hi: "अनुच्छेद 156 के तहत राज्यपाल का कार्यकाल राष्ट्रपति के प्रसाद पर्यंत होता है।",
  },
  {
    question_en: "Who administers the oath of office to the Governor?",
    question_hi: "राज्यपाल को उनके पद की शपथ कौन दिलाता है?",
    options_en: ["President", "Chief Justice of the Supreme Court", "Chief Justice of the High Court", "Chief Minister"],
    options_hi: ["राष्ट्रपति", "सर्वोच्च न्यायालय का मुख्य न्यायाधीश", "उच्च न्यायालय का मुख्य न्यायाधीश", "मुख्यमंत्री"],
    correct_option_index: 2,
    explanation_en: "Under Article 159, the oath is administered to the Governor by the Chief Justice of the High Court.",
    explanation_hi: "अनुच्छेद 159 के तहत राज्यपाल को शपथ उच्च न्यायालय के मुख्य न्यायाधीश द्वारा दिलाई जाती है।",
  },
  {
    question_en: "In which article are the Governor's Powers of Pardon mentioned?",
    question_hi: "राज्यपाल की क्षमादान (Powers of Pardon) शक्तियां किस अनुच्छेद में वर्णित हैं?",
    options_en: ["Article 155", "Article 161", "Article 163", "Article 164"],
    options_hi: ["अनुच्छेद 155", "अनुच्छेद 161", "अनुच्छेद 163", "अनुच्छेद 164"],
    correct_option_index: 1,
    explanation_en: "Article 161 relates to the Governor's powers of pardon (but he cannot pardon death sentences and court-martial sentences).",
    explanation_hi: "अनुच्छेद 161 राज्यपाल की क्षमादान की शक्तियों से संबंधित है (लेकिन वह फाँसी एवं कोर्ट मार्शल की सज़ा माफ नहीं कर सकता)।",
  },
  {
    question_en: "Who appoints the Chief Minister and other ministers?",
    question_hi: "मुख्यमंत्री एवं अन्य मंत्रियों की नियुक्ति कौन करता है?",
    options_en: ["President", "Prime Minister", "Governor", "Speaker of the Legislative Assembly"],
    options_hi: ["राष्ट्रपति", "प्रधानमंत्री", "राज्यपाल", "विधान सभा अध्यक्ष"],
    correct_option_index: 2,
    explanation_en: "Under Article 164, the Chief Minister and other ministers are appointed by the Governor on the advice of the CM.",
    explanation_hi: "अनुच्छेद 164 के तहत मुख्यमंत्री एवं अन्य मंत्रियों की नियुक्ति राज्यपाल द्वारा CM की सलाह पर की जाती है।",
  },
  {
    question_en: "Under which article does the Governor have the power to issue an Ordinance?",
    question_hi: "राज्यपाल किस अनुच्छेद के तहत अध्यादेश (Ordinance) जारी करने की शक्ति रखता है?",
    options_en: ["Article 200", "Article 213", "Article 167", "Article 170"],
    options_hi: ["अनुच्छेद 200", "अनुच्छेद 213", "अनुच्छेद 167", "अनुच्छेद 170"],
    correct_option_index: 1,
    explanation_en: "The power of the Governor to issue an ordinance is in Article 213.",
    explanation_hi: "राज्यपाल को अध्यादेश जारी करने की शक्ति अनुच्छेद 213 में है।",
  },
  {
    question_en: "Who is the Biggest Law Officer of the state?",
    question_hi: "राज्य का सबसे बड़ा विधि अधिकारी (Biggest Law Officer) कौन होता है?",
    options_en: ["Attorney General", "Advocate General", "Governor", "Chief Minister"],
    options_hi: ["महान्यायवादी", "महाधिवक्ता", "राज्यपाल", "मुख्यमंत्री"],
    correct_option_index: 1,
    explanation_en: "The State Advocate General is the biggest Law Officer of the state, described in Article 165.",
    explanation_hi: "राज्य महाधिवक्ता (State Advocate General) राज्य का सबसे बड़ा विधि अधिकारी (Law Officer) होता है, जिसका वर्णन अनुच्छेद 165 में है।",
  },
  {
    question_en: "The Advocate General has the right to participate and speak in the proceedings of the State Legislature, but what right does he not have?",
    question_hi: "राज्य महाधिवक्ता को राज्य विधानमंडल की कार्यवाही में भाग लेने और बोलने का अधिकार होता है, लेकिन वह किस चीज का अधिकार नहीं रखता?",
    options_en: ["Deliberation", "Giving suggestions", "Debating", "Voting"],
    options_hi: ["विचार-विमर्श", "सुझाव देना", "बहस करना", "वोट देना"],
    correct_option_index: 3,
    explanation_en: "Under Article 177, the Advocate General can participate and debate in the Legislature, but cannot vote.",
    explanation_hi: "अनुच्छेद 177 के तहत महाधिवक्ता विधानमंडल में हिस्सा ले सकता है, डिबेट कर सकता है, लेकिन वोट नहीं दे सकता।",
  },
  {
    question_en: "What is the maximum number of seats a Legislative Assembly can have?",
    question_hi: "विधानसभा (Legislative Assembly) में अधिकतम सीटों की संख्या कितनी हो सकती है?",
    options_en: ["60", "500", "550", "403"],
    options_hi: ["60", "500", "550", "403"],
    correct_option_index: 1,
    explanation_en: "The maximum number of seats in the Legislative Assembly can be up to 500.",
    explanation_hi: "विधानसभा में अधिकतम सीट (Max. Seats) 500 तक हो सकती हैं।",
  },
  {
    question_en: "What is the minimum number of seats a Legislative Assembly can have, with some exceptions?",
    question_hi: "विधानसभा में न्यूनतम सीटों की संख्या कितनी हो सकती है, जिसके कुछ अपवाद भी हैं?",
    options_en: ["40", "60", "32", "30"],
    options_hi: ["40", "60", "32", "30"],
    correct_option_index: 1,
    explanation_en: "The minimum number of seats in the Legislative Assembly can be 60 (Exceptions: Sikkim 32, Goa 40, Mizoram 40, Puducherry 30).",
    explanation_hi: "विधानसभा में कम से कम सीट (Min. Seats) 60 हो सकती हैं (अपवाद: सिक्किम 32, गोवा 40, मिजोरम 40, पुडुचेरी 30)।",
  },
  {
    question_en: "Currently, how many states have a Legislative Council?",
    question_hi: "वर्तमान में कुल कितने राज्यों में विधान परिषद (Legislative Council) मौजूद है?",
    options_en: ["5", "6", "7", "8"],
    options_hi: ["5", "6", "7", "8"],
    correct_option_index: 1,
    explanation_en: "Currently, the Legislative Council exists in 6 states (Uttar Pradesh, Karnataka, Maharashtra, Bihar, Andhra Pradesh, Telangana).",
    explanation_hi: "वर्तमान में 6 राज्यों (उत्तर प्रदेश, कर्नाटक, महाराष्ट्र, बिहार, आंध्र प्रदेश, तेलंगाना) में विधान परिषद मौजूद है।",
  },
  {
    question_en: "Who has the power to create or abolish the Legislative Council?",
    question_hi: "विधान परिषद को बनाने या समाप्त करने का अधिकार किसे दिया गया है?",
    options_en: ["Governor", "Parliament", "Legislative Assembly", "President"],
    options_hi: ["राज्यपाल", "संसद", "विधान सभा", "राष्ट्रपति"],
    correct_option_index: 1,
    explanation_en: "Under Article 169, the Parliament has the power to create or abolish the Legislative Council in a state.",
    explanation_hi: "अनुच्छेद 169 के तहत संसद को किसी राज्य में विधान परिषद बनाने या समाप्त करने का अधिकार दिया गया है।",
  },
  {
    question_en: "What is the term of office for the members of the Legislative Council?",
    question_hi: "विधान परिषद के सदस्यों का कार्यकाल कितने वर्ष का होता है?",
    options_en: ["5 years", "6 years", "3 years", "Indefinite"],
    options_hi: ["5 वर्ष", "6 वर्ष", "3 वर्ष", "अनिश्चित"],
    correct_option_index: 1,
    explanation_en: "The Legislative Council is a permanent house, and the term of its members is 6 years.",
    explanation_hi: "विधान परिषद एक स्थायी सदन है, और इसके सदस्यों का कार्यकाल 6 वर्ष होता है।",
  },
  {
    question_en: "Who nominates 1/6 of the total members of the Legislative Council?",
    question_hi: "विधान परिषद के कुल सदस्यों के 1/6 भाग सदस्यों को कौन मनोनीत करता है?",
    options_en: ["Chief Minister", "Speaker of the Legislative Assembly", "Governor", "President"],
    options_hi: ["मुख्यमंत्री", "विधानसभा अध्यक्ष", "राज्यपाल", "राष्ट्रपति"],
    correct_option_index: 2,
    explanation_en: "1/6 of the total members of the Legislative Council are nominated by the Governor.",
    explanation_hi: "राज्यपाल द्वारा विधान परिषद के कुल सदस्यों का 1/6 भाग मनोनीत किया जाता है।",
  },
  {
    question_en: "Which article contains the provision for 'Equal Opportunity in public employment'?",
    question_hi: "किस अनुच्छेद में 'सार्वजनिक रोजगार में अवसर की समानता' (Equal Opportunity) का प्रावधान है?",
    options_en: ["Article 15", "Article 16", "Article 17", "Article 18"],
    options_hi: ["अनुच्छेद 15", "अनुच्छेद 16", "अनुच्छेद 17", "अनुच्छेद 18"],
    correct_option_index: 1,
    explanation_en: "Article 16 relates to Equal Opportunity in public employment (government jobs).",
    explanation_hi: "अनुच्छेद 16 लोक नियोजन (सरकारी नौकरी) की समानता (Equal Opportunity) से संबंधित है।",
  },
  {
    question_en: "Which article provides for 'Equality before Law' and 'Equal protection of laws'?",
    question_hi: "किस अनुच्छेद में 'विधि के समक्ष समानता' (Equality before Law) और 'कानूनों का समान संरक्षण' (Equal protection of laws) का प्रावधान है?",
    options_en: ["Article 12", "Article 13", "Article 14", "Article 15"],
    options_hi: ["अनुच्छेद 12", "अनुच्छेद 13", "अनुच्छेद 14", "अनुच्छेद 15"],
    correct_option_index: 2,
    explanation_en: "Article 14 includes Equality before Law (from Britain) and Equal protection of laws (from USA).",
    explanation_hi: "अनुच्छेद 14 में विधि के समक्ष समानता (ब्रिटेन) और कानूनों का समान संरक्षण (USA) शामिल है।",
  },
  {
    question_en: "Under which article is the 'Freedom to manage religious affairs' granted?",
    question_hi: "किस अनुच्छेद के तहत धार्मिक कार्यों के प्रबंधन की स्वतंत्रता (Freedom to manage religious affairs) प्रदान की गई है?",
    options_en: ["Article 25", "Article 26", "Article 27", "Article 28"],
    options_hi: ["अनुच्छेद 25", "अनुच्छेद 26", "अनुच्छेद 27", "अनुच्छेद 28"],
    correct_option_index: 1,
    explanation_en: "Article 26 relates to the Freedom to manage religious affairs.",
    explanation_hi: "अनुच्छेद 26 धार्मिक कार्यों के प्रबंधन (Freedom to manage religious affairs) की स्वतंत्रता से संबंधित है।",
  },
  {
    question_en: "The provision for the 'Protection of Interests of minorities' is in which article?",
    question_hi: "अल्पसंख्यकों के हितों के संरक्षण (Protection of Interests of minorities) का प्रावधान किस अनुच्छेद में है?",
    options_en: ["Article 28", "Article 29", "Article 30", "Article 32"],
    options_hi: ["अनुच्छेद 28", "अनुच्छेद 29", "अनुच्छेद 30", "अनुच्छेद 32"],
    correct_option_index: 1,
    explanation_en: "Article 29 relates to the protection of interests of minorities (language/script/culture).",
    explanation_hi: "अनुच्छेद 29 अल्पसंख्यकों के हितों के संरक्षण (भाषा/लिपि/संस्कृति) से संबंधित है।",
  },
  {
    question_en: "Which article grants the right of minority groups to establish and administer educational institutions?",
    question_hi: "शिक्षा संस्थाओं की स्थापना और प्रशासन करने का अल्पसंख्यक वर्गों का अधिकार किस अनुच्छेद में है?",
    options_en: ["Article 29", "Article 30", "Article 32", "Article 33"],
    options_hi: ["अनुच्छेद 29", "अनुच्छेद 30", "अनुच्छेद 32", "अनुच्छेद 33"],
    correct_option_index: 1,
    explanation_en: "Article 30 relates to the right to Establishment of Educational Institutions.",
    explanation_hi: "अनुच्छेद 30 शिक्षण संस्थाओं की स्थापना (Establishment of Educational Institutions) के अधिकार से संबंधित है।",
  },
  {
    question_en: "Which article falls under the Gandhian Principles of DPSP?",
    question_hi: "डीपीएस गांधीवादी सिद्धांत के अंतर्गत कौन सा अनुच्छेद आता है?",
    options_en: ["Article 39A", "Article 44", "Article 48", "Article 49"],
    options_hi: ["अनुच्छेद 39A", "अनुच्छेद 44", "अनुच्छेद 48", "अनुच्छेद 49"],
    correct_option_index: 2,
    explanation_en: "Articles 40, 43, 43B, 46, 47, 48 come under the Gandhian Principles. Article 48 relates to the protection of agriculture and animals.",
    explanation_hi: "गांधीवादी सिद्धांतों के तहत अनुच्छेद 40, 43, 43B, 46, 47, 48 आते हैं। अनुच्छेद 48 कृषि एवं पशुओं की सुरक्षा से संबंधित है।",
  },
  {
    question_en: "The provision for 'Protection of Environment and safety of forests and wildlife' is in which article?",
    question_hi: "\"पर्यावरण संरक्षण तथा वन और वन्यजीवों की सुरक्षा\" का प्रावधान किस अनुच्छेद में है?",
    options_en: ["Article 48", "Article 48(A)", "Article 49", "Article 51"],
    options_hi: ["अनुच्छेद 48", "अनुच्छेद 48(क)", "अनुच्छेद 49", "अनुच्छेद 51"],
    correct_option_index: 1,
    explanation_en: "Article 48(A) relates to the Protection of Environment and safety of forests and wildlife.",
    explanation_hi: "अनुच्छेद 48(क) पर्यावरण संरक्षण तथा वन और वन्यजीवों की सुरक्षा (Environment protection) से संबंधित है।",
  },
  {
    question_en: "Developing 'Scientific Temper' and 'spirit of inquiry' is related to which Fundamental Duty?",
    question_hi: "'वैज्ञानिक भावना' (Scientific Temper) और 'सीखने की इच्छा' का विकास करना किस मौलिक कर्तव्य से संबंधित है?",
    options_en: ["51A(a)", "51A(g)", "51A(h)", "51A(i)"],
    options_hi: ["51A(a)", "51A(g)", "51A(h)", "51A(i)"],
    correct_option_index: 2,
    explanation_en: "Art 51A(h) relates to developing scientific temper and the spirit of inquiry.",
    explanation_hi: "Art 51A(h) वैज्ञानिक भावना (Scientific temper) और जानने की इच्छा का विकास करने से संबंधित है।",
  },
  {
    question_en: "By what method is the President elected?",
    question_hi: "राष्ट्रपति का चुनाव किस रीति (Method) से होता है?",
    options_en: ["Single Transferable Vote System (Direct Election)", "Single Transferable Vote System (Indirect Election)", "Secret Ballot", "Direct and Secret Ballot"],
    options_hi: ["एकल संक्रमणीय मत पद्धति (प्रत्यक्ष निर्वाचन)", "एकल संक्रमणीय मत पद्धति (अप्रत्यक्ष निर्वाचन)", "गुप्त मतदान", "प्रत्यक्ष और गुप्त मतदान"],
    correct_option_index: 1,
    explanation_en: "The President is elected by Single Transferable Vote System through an Indirect Election.",
    explanation_hi: "राष्ट्रपति का निर्वाचन एकल संक्रमणीय मत पद्धति द्वारा अप्रत्यक्ष चुनाव (Indirect Election) से होता है।",
  },
  {
    question_en: "Which members do not participate in the Presidential election?",
    question_hi: "राष्ट्रपति चुनाव में कौन से सदस्य भाग नहीं लेते हैं?",
    options_en: ["Elected members of Rajya Sabha", "Elected members of Lok Sabha", "Members of Legislative Council", "Elected members of State Legislative Assemblies"],
    options_hi: ["राज्यसभा के निर्वाचित सदस्य", "लोकसभा के निर्वाचित सदस्य", "विधान परिषद् के सदस्य", "राज्य विधानसभाओं के निर्वाचित सदस्य"],
    correct_option_index: 2,
    explanation_en: "Nominated members and members of the Legislative Council do not participate in the Presidential election.",
    explanation_hi: "राष्ट्रपति के चुनाव में मनोनीत सदस्य और विधान परिषद के सदस्य भाग नहीं लेते हैं।",
  },
  {
    question_en: "Under which article can the President seek advice from the Supreme Court?",
    question_hi: "राष्ट्रपति द्वारा किस अनुच्छेद के तहत उच्चतम न्यायालय से सलाह ली जा सकती है?",
    options_en: ["Article 72", "Article 85", "Article 123", "Article 143"],
    options_hi: ["अनुच्छेद 72", "अनुच्छेद 85", "अनुच्छेद 123", "अनुच्छेद 143"],
    correct_option_index: 3,
    explanation_en: "The President can seek advice from the Chief Justice of the Supreme Court under Article 143.",
    explanation_hi: "राष्ट्रपति उच्चतम न्यायालय के मुख्य न्यायाधीश से सलाह अनुच्छेद 143 के तहत ले सकते हैं।",
  },
  {
    question_en: "Who declares the Prorogation/Dissolution of the Parliament session?",
    question_hi: "संसद सत्र का सत्रावसान/विलयन (Prorogation/Dissolution) की घोषणा कौन करता है?",
    options_en: ["Prime Minister", "Speaker of Lok Sabha", "President", "Vice President"],
    options_hi: ["प्रधानमंत्री", "लोकसभा अध्यक्ष", "राष्ट्रपति", "उपराष्ट्रपति"],
    correct_option_index: 2,
    explanation_en: "The President declares Prorogation and Dissolution under Article 85 on the advice of the PM.",
    explanation_hi: "सत्रावसान और विलयन की घोषणा राष्ट्रपति द्वारा PM की सलाह पर अनुच्छेद 85 के तहत की जाती है।",
  },
  {
    question_en: "In which article is the right of the Attorney General (AG) and Ministers to speak and participate in Parliament mentioned?",
    question_hi: "महान्यायवादी (AG) एवं मंत्रियों को संसद में बोलने और भाग लेने का अधिकार किस अनुच्छेद में है?",
    options_en: ["Article 83", "Article 85", "Article 87", "Article 88"],
    options_hi: ["अनुच्छेद 83", "अनुच्छेद 85", "अनुच्छेद 87", "अनुच्छेद 88"],
    correct_option_index: 3,
    explanation_en: "Article 88 gives the Ministers and the Attorney General of India the right to speak and participate in Parliament.",
    explanation_hi: "अनुच्छेद 88 भारत के मंत्रियों और महान्यायवादी को संसद में बोलने और भाग लेने का अधिकार देता है।",
  },
  {
    question_en: "What is the total number of Lok Sabha seats (fixed till 2026)?",
    question_hi: "वर्तमान में लोकसभा की कुल सीटें (2026 तक निर्धारित) कितनी हैं?",
    options_en: ["545", "550", "552", "543"],
    options_hi: ["545", "550", "552", "543"],
    correct_option_index: 1,
    explanation_en: "The maximum seats in the Lok Sabha can be 552, but after the removal of Anglo-Indian seats by the 104th CA 2019, it can now be up to 550. (Current seats are 543).",
    explanation_hi: "लोकसभा में अधिकतम सीट 552 हो सकती हैं, लेकिन 104वें CA 2019 द्वारा एंग्लो-इंडियन सीटों को हटाए जाने के बाद अब यह 550 तक हो सकती हैं। (वर्तमान सीट 543 है)।",
  },
  {
    question_en: "Under which article are SC judges prohibited from practicing law in any court in India after retirement?",
    question_hi: "किस अनुच्छेद के तहत SC के न्यायाधीशों को सेवानिवृत्ति के बाद भारत के किसी भी कोर्ट में वकालत करने पर प्रतिबंध है?",
    options_en: ["Article 124(3)", "Article 124(6)", "Article 124(7)", "Article 126"],
    options_hi: ["अनुच्छेद 124(3)", "अनुच्छेद 124(6)", "अनुच्छेद 124(7)", "अनुच्छेद 126"],
    correct_option_index: 2,
    explanation_en: "Article 124(7) imposes restrictions on SC judges after retirement.",
    explanation_hi: "अनुच्छेद 124(7) सेवानिवृत्ति के बाद SC के न्यायाधीशों पर प्रतिबंध (Restrictions) लगाता है।",
  },
  // --- New Batch 171-210 ---
  {
    question_en: "Which Part of the Indian Constitution contains the provision for Trade, Commerce and Intercourse?",
    question_hi: "भारतीय संविधान के किस भाग में व्यापार, वाणिज्य एवं समागम (Trade, Commerce and Intercourse) का प्रावधान है?",
    options_en: ["Part 11", "Part 12", "Part 13", "Part 14"],
    options_hi: ["भाग 11", "भाग 12", "भाग 13", "भाग 14"],
    correct_option_index: 2,
    explanation_en: "Part 13 (Articles 301-307) relates to Trade, Commerce, and Intercourse.",
    explanation_hi: "भाग 13 (अनुच्छेद 301-307) व्यापार, वाणिज्य एवं समागम (Trade, Business, Commerce) से संबंधित है।",
  },
  {
    question_en: "Part 18 of the Constitution is related to which subject?",
    question_hi: "संविधान का भाग 18 किससे संबंधित है?",
    options_en: ["Constitutional Amendment", "Official Language", "Emergency Provisions", "Elections"],
    options_hi: ["संविधान संशोधन", "राजभाषा", "आपात उपबंध (Emergency Provisions)", "निर्वाचन"],
    correct_option_index: 2,
    explanation_en: "Part 18 (Articles 352-360) relates to Emergency Provisions.",
    explanation_hi: "भाग 18 (अनुच्छेद 352-360) आपात उपबंध (Emergency provisions) से संबंधित है।",
  },
  {
    question_en: "The idea of Fundamental Duties was inspired by the constitution of which country?",
    question_hi: "मौलिक कर्तव्यों का विचार (Inspired) किस देश से लिया गया है?",
    options_en: ["USA", "France", "Russia", "South Africa"],
    options_hi: ["USA", "फ्रांस", "रूस", "दक्षिण अफ्रीका"],
    correct_option_index: 2,
    explanation_en: "Fundamental Duties are inspired by the Constitution of Russia (erstwhile USSR).",
    explanation_hi: "मौलिक कर्तव्य रूस के संविधान से प्रेरित हैं।",
  },
  {
    question_en: "By which constitutional amendment was the number of Lok Sabha seats increased from 525 to 545?",
    question_hi: "किस संविधान संशोधन द्वारा लोकसभा सीटों की संख्या 525 से बढ़ाकर 545 कर दी गई थी?",
    options_en: ["7th CA, 1956", "31st CA, 1973", "42nd CA, 1976", "44th CA, 1978"],
    options_hi: ["7वां CA, 1956", "31वां CA, 1973", "42वां CA, 1976", "44वां CA, 1978"],
    correct_option_index: 1,
    explanation_en: "The number of Lok Sabha seats was increased from 525 to 545 by the 31st Constitutional Amendment, 1973.",
    explanation_hi: "31वें संविधान संशोधन, 1973 द्वारा लोकसभा सीटें 525 से बढ़ाकर 545 कर दी गईं।",
  },
  {
    question_en: "The number of Lok Sabha seats has been fixed until which year?",
    question_hi: "लोकसभा में सीटों की संख्या किस वर्ष तक के लिए निश्चित कर दी गई है?",
    options_en: ["2021", "2024", "2026", "2030"],
    options_hi: ["2021", "2024", "2026", "2030"],
    correct_option_index: 2,
    explanation_en: "The number of Lok Sabha seats has been fixed until 2026 by the Goa-Daman Diu Act 2001 (based on the 84th CA 2001).",
    explanation_hi: "गोवा-दमन दीव अधिनियम 2001 द्वारा लोकसभा सीटों की संख्या 2026 तक निश्चित कर दी गई है।",
  },
  {
    question_en: "From which fund of India is the salary of the Chief Justice of the Supreme Court paid?",
    question_hi: "उच्चतम न्यायालय (SC) के मुख्य न्यायाधीश का वेतन भारत की किस निधि से दिया जाता है?",
    options_en: ["Contingency Fund of India", "Consolidated Fund of India", "Public Account of India", "Recommendation of the Finance Commission"],
    options_hi: ["भारत की आकस्मिक निधि", "भारत की संचित निधि", "भारत की लोक लेखा निधि", "वित्त आयोग की सिफारिश"],
    correct_option_index: 1,
    explanation_en: "The salary of Supreme Court judges is paid from the Consolidated Fund of India.",
    explanation_hi: "सुप्रीम कोर्ट के न्यायाधीशों का वेतन भारत की संचित निधि (Consolidated fund of India) से दिया जाता है।",
  },
  {
    question_en: "Who appoints Adhoc Judges when there is no Quorum in the Supreme Court?",
    question_hi: "जब SC में गणपूर्ति (Quorum) न हो, तब तदर्थ न्यायाधीशों (Adhoc Justice) की नियुक्ति कौन करता है?",
    options_en: ["Chief Justice on the advice of the President", "President on the advice of the Chief Justice", "Parliament", "President"],
    options_hi: ["राष्ट्रपति की सलाह से मुख्य न्यायाधीश", "मुख्य न्यायाधीश की सलाह से राष्ट्रपति", "संसद", "राष्ट्रपति"],
    correct_option_index: 0,
    explanation_en: "Adhoc Judges are appointed by the Chief Justice on the advice of the President when there is no Quorum.",
    explanation_hi: "गणपूर्ति (Quorum) न होने पर, मुख्य न्यायाधीश द्वारा राष्ट्रपति की सलाह से तदर्थ न्यायाधीशों (Adhoc Justice) की नियुक्ति की जाती है।",
  },
  {
    question_en: "In which article is the Original Jurisdiction of the Supreme Court, related to disputes between the Center and States, mentioned?",
    question_hi: "सुप्रीम कोर्ट का मूल क्षेत्राधिकार (Original Jurisdiction) किस अनुच्छेद में है, जो केंद्र और राज्यों के बीच विवाद से संबंधित है?",
    options_en: ["Article 130", "Article 131", "Article 132", "Article 134"],
    options_hi: ["अनुच्छेद 130", "अनुच्छेद 131", "अनुच्छेद 132", "अनुच्छेद 134"],
    correct_option_index: 1,
    explanation_en: "Article 131 relates to the Original Jurisdiction of the Supreme Court.",
    explanation_hi: "अनुच्छेद 131 सुप्रीम कोर्ट के आरंभिक/मूल क्षेत्राधिकार (Original Jurisdiction) से संबंधित है।",
  },
  {
    question_en: "Under which article is the High Court a Court of Record?",
    question_hi: "उच्च न्यायालय (High Court) किस अनुच्छेद के तहत एक अभिलेख न्यायालय (Court of Record) होता है?",
    options_en: ["Article 214", "Article 215", "Article 217", "Article 226"],
    options_hi: ["अनुच्छेद 214", "अनुच्छेद 215", "अनुच्छेद 217", "अनुच्छेद 226"],
    correct_option_index: 1,
    explanation_en: "Article 215 states that the High Court is a Court of Record.",
    explanation_hi: "अनुच्छेद 215 कहता है कि High Court एक अभिलेख न्यायालय (Court of Record) है।",
  },
  {
    question_en: "In which article is it mentioned that the Governor administers the oath to the High Court judges?",
    question_hi: "राज्यपाल हाई कोर्ट के न्यायाधीशों को शपथ दिलाता है, यह किस अनुच्छेद में वर्णित है?",
    options_en: ["Article 217", "Article 219", "Article 220", "Article 221"],
    options_hi: ["अनुच्छेद 217", "अनुच्छेद 219", "अनुच्छेद 220", "अनुच्छेद 221"],
    correct_option_index: 1,
    explanation_en: "Article 219 relates to the Oath of High Court judges being administered by the Governor.",
    explanation_hi: "अनुच्छेद 219 High Court के जजों की शपथ (Oath) राज्यपाल द्वारा दिलाए जाने से संबंधित है।",
  },
  {
    question_en: "Which committee recommended the State Finance Commission?",
    question_hi: "राज्य वित्त आयोग (State Finance Commission) की सिफारिश किस समिति ने की थी?",
    options_en: ["Balwant Rai Mehta", "P.V.K. Rao", "L.M. Singhvi", "P.K. Thungan"],
    options_hi: ["बलवंत राय मेहता", "पी.वी.के. राव", "एल.एम. सिंघवी", "पी.के. थुंगन"],
    correct_option_index: 1,
    explanation_en: "The P.V.K. Rao Committee (1985) demanded the State Finance Commission in its recommendations.",
    explanation_hi: "पी.वी.के. राव समिति (1985) ने अपनी सिफारिशों में राज्य वित्त आयोग (State Finance Comm.) की मांग की थी।",
  },
  {
    question_en: "The formation of 'Gram Sabha' is mentioned in which article?",
    question_hi: "\"ग्राम सभा\" (Gram Sabha) का गठन किस अनुच्छेद में वर्णित है?",
    options_en: ["Article 243", "Article 243A", "Article 243B", "Article 243C"],
    options_hi: ["अनुच्छेद 243", "अनुच्छेद 243A", "अनुच्छेद 243B", "अनुच्छेद 243C"],
    correct_option_index: 1,
    explanation_en: "Article 243A relates to the Gram Sabha.",
    explanation_hi: "अनुच्छेद 243A ग्राम सभा से संबंधित है।",
  },
  {
    question_en: "What is the tenure of the members of the Municipalities?",
    question_hi: "नगर पालिकाओं (Municipalities) के सदस्यों का कार्यकाल (Tenure) कितने वर्ष का होता है?",
    options_en: ["5 years", "2 years", "6 years", "3 years"],
    options_hi: ["5 वर्ष", "2 वर्ष", "6 वर्ष", "3 वर्ष"],
    correct_option_index: 0,
    explanation_en: "The tenure of the members of the Municipalities is 5 years.",
    explanation_hi: "नगर पालिकाओं के सदस्यों का कार्यकाल 5 वर्ष होता है।",
  },
  {
    question_en: "During the tenure of which Prime Minister did Panchayati Raj get constitutional status?",
    question_hi: "किस प्रधानमंत्री के कार्यकाल में पंचायती राज को संवैधानिक दर्जा मिला?",
    options_en: ["Rajiv Gandhi", "V.P. Singh", "P.V. Narasimha Rao", "Atal Bihari Vajpayee"],
    options_hi: ["राजीव गांधी", "वी.पी. सिंह", "पी.वी. नरसिम्हा राव", "अटल बिहारी वाजपेयी"],
    correct_option_index: 2,
    explanation_en: "The 73rd and 74th Constitutional Amendments, which granted constitutional status to Panchayati Raj, took place during the P.V. Narasimha Rao government.",
    explanation_hi: "पी.वी. नरसिम्हा राव सरकार (P.V. Narsimha Rao Sarkar) के समय 73वां और 74वां संविधान संशोधन हुआ, जिसने पंचायती राज को संवैधानिक दर्जा दिया।",
  },
  {
    question_en: "What provision was made by the Seventh Constitutional Amendment, 1956?",
    question_hi: "सातवें संविधान संशोधन, 1956 द्वारा क्या प्रावधान किया गया था?",
    options_en: ["9th Schedule was added.", "Number of Lok Sabha seats was increased from 500 to 522.", "One person can be appointed as the Governor of 2 or more states.", "42nd Amendment was called Mini Constitution."],
    options_hi: ["9वीं अनुसूची जोड़ी गई।", "लोकसभा सीटों की संख्या 500 से बढ़ाकर 522 की गई।", "एक व्यक्ति को 2 या 2 से अधिक राज्यों का राज्यपाल बनाया जा सकता है।", "42वें संशोधन को मिनी संविधान कहा गया।"],
    correct_option_index: 2,
    explanation_en: "The 7th CA 1956 provided that one person can be appointed as the Governor of 2 or more states (and also abolished Group A, B, C, D states).",
    explanation_hi: "7वें CA 1956 के द्वारा एक व्यक्ति को 2 या 2 से अधिक राज्यों का राज्यपाल बनाया जा सकता है (साथ ही Group A, B, C, D राज्य समाप्त किए गए)।",
  },
  {
    question_en: "What was the total number of languages after Sindhi language was added to the Eighth Schedule?",
    question_hi: "सिंधी भाषा को आठवीं अनुसूची में जोड़ने के बाद भाषाओं की कुल संख्या कितनी हो गई थी?",
    options_en: ["15", "16", "18", "22"],
    options_hi: ["15", "16", "18", "22"],
    correct_option_index: 0,
    explanation_en: "The original Constitution had 14 languages. After adding Sindhi by the 21st CA 1967, the total became 15.",
    explanation_hi: "मूल संविधान में 14 भाषाएँ थीं। 21वें CA 1967 द्वारा सिंधी जोड़ने के बाद कुल संख्या 15वीं भाषा हो गई।",
  },
  {
    question_en: "Reducing the voting age from 21 years to 18 years was done by an amendment to which article?",
    question_hi: "वोट देने की आयु 21 वर्ष से घटाकर 18 वर्ष किस अनुच्छेद में संशोधन द्वारा किया गया?",
    options_en: ["Article 324", "Article 326", "Article 327", "Article 328"],
    options_hi: ["अनुच्छेद 324", "अनुच्छेद 326", "अनुच्छेद 327", "अनुच्छेद 328"],
    correct_option_index: 1,
    explanation_en: "The voter age was reduced from 21 years to 18 years by amending Article 326 through the 61st CA 1988.",
    explanation_hi: "61वें CA 1988 द्वारा अनुच्छेद 326 में संशोधन करके मतदाता आयु 21 वर्ष से 18 वर्ष की गई।",
  },
  {
    question_en: "By the 70th Constitutional Amendment, 1992, which bodies were given the right to participate in the Presidential election?",
    question_hi: "70वें संविधान संशोधन, 1992 द्वारा किसे राष्ट्रपति के चुनाव में हिस्सा लेने का अधिकार दिया गया?",
    options_en: ["Jammu and Kashmir Legislative Assembly", "Delhi and Puducherry Legislative Assembly", "All Union Territories", "Only Delhi Legislative Assembly"],
    options_hi: ["जम्मू-कश्मीर विधान सभा", "दिल्ली एवं पुडुचेरी विधान सभा", "सभी केंद्र शासित प्रदेश", "केवल दिल्ली विधान सभा"],
    correct_option_index: 1,
    explanation_en: "The 70th CA 1992 granted the members of Delhi and Puducherry Legislative Assemblies the right to participate in the Presidential election.",
    explanation_hi: "70वें CA 1992 द्वारा दिल्ली एवं पुडुचेरी विधान सभाओं के सदस्यों को राष्ट्रपति के चुनाव में भाग लेने का अधिकार मिला।",
  },
  {
    question_en: "In which year was the Joint Parliamentary Committee on Official Language constituted?",
    question_hi: "राजभाषा पर संयुक्त संसदीय समिति का गठन किस वर्ष हुआ था?",
    options_en: ["1955", "1957", "1961", "1967"],
    options_hi: ["1955", "1957", "1961", "1967"],
    correct_option_index: 1,
    explanation_en: "The Joint Parliamentary Committee on Official Language was constituted in 1957.",
    explanation_hi: "राजभाषा पर संयुक्त संसदीय समिति (Joint Parliamentary Committee) का गठन 1957 में हुआ था।",
  },
  {
    question_en: "The salary of High Court (HC) judges is paid from the Consolidated Fund of the State, but from where is their pension paid?",
    question_hi: "उच्च न्यायालय (HC) के न्यायाधीशों का वेतन राज्य की संचित निधि से दिया जाता है, लेकिन उनकी पेंशन कहाँ से दी जाती है?",
    options_en: ["Consolidated Fund of the State", "Consolidated Fund of India", "Contingency Fund of the State", "At the discretion of the President"],
    options_hi: ["राज्य की संचित निधि", "भारत की संचित निधि", "राज्य की आकस्मिक निधि", "राष्ट्रपति की मर्जी पर"],
    correct_option_index: 1,
    explanation_en: "The pension of HC judges is paid from the Consolidated Fund of India.",
    explanation_hi: "HC के जजों की पेंशन भारत की संचित निधि (Consolidated fund of India) द्वारा दी जाती है।",
  },
  {
    question_en: "The provisions of the Citizenship Amendment Act 2019 (CAA) will not apply to which areas?",
    question_hi: "नागरिकता संशोधन अधिनियम 2019 (CAA) के प्रावधान किन क्षेत्रों पर लागू नहीं होंगे?",
    options_en: ["Northeast and plain states", "Tribal areas of Assam, Meghalaya, Mizoram, Tripura", "Nagaland and Delhi", "All Union Territories"],
    options_hi: ["पूर्वोत्तर एवं मैदानी राज्य", "असम, मेघालय, मिजोरम, त्रिपुरा के आदिवासी क्षेत्र", "नागालैंड और दिल्ली", "सभी केंद्र शासित प्रदेश"],
    correct_option_index: 1,
    explanation_en: "The provisions of the CAA will not apply to the tribal areas of Assam, Meghalaya, Mizoram, Tripura, and illegal immigrants coming within the eastern boundary of Bengal.",
    explanation_hi: "CAA के प्रावधान असम, मेघालय, मिजोरम, त्रिपुरा के आदिवासी क्षेत्रों तथा बंगाल की पूर्वी सीमांत में आने वाले अवैध प्रवासियों पर लागू नहीं होंगे।",
  },
  {
    question_en: "Which committee recommended that EVMs (Electronic Voting Machines) should be used?",
    question_hi: "किस समिति ने सिफारिश की थी कि EVM (इलेक्ट्रॉनिक वोटिंग मशीन) का प्रयोग किया जाना चाहिए?",
    options_en: ["Balwant Rai Mehta Committee", "Tarkunde Committee", "Dinesh Goswami Committee", "K. Santhanam Committee"],
    options_hi: ["बलवंत राय मेहता समिति", "तारकुंडे समिति", "दिनेश गोस्वामी समिति", "के. संथानम समिति"],
    correct_option_index: 2,
    explanation_en: "The Dinesh Goswami Committee (1990) recommended the use of EVMs.",
    explanation_hi: "दिनेश गोस्वामी समिति (1990) ने EVM के प्रयोग की सिफारिश की थी।",
  },
  {
    question_en: "Who invented the EVM?",
    question_hi: "EVM का आविष्कार किसके द्वारा किया गया था?",
    options_en: ["V.S. Ramadevi", "T.N. Seshan", "M.V. Hanifa", "Dinesh Goswami"],
    options_hi: ["वी.एस. रमादेवी", "टी.एन. शेषन", "एम.वी. हनीफा", "दिनेश गोस्वामी"],
    correct_option_index: 2,
    explanation_en: "The EVM was invented by M.V. Hanifa.",
    explanation_hi: "EVM का आविष्कार एम.वी. हनीफा द्वारा किया गया।",
  },
  {
    question_en: "Under which article does the State Government have the right to make laws related to state elections?",
    question_hi: "किस अनुच्छेद के तहत राज्य सरकार कानून बनाकर राज्यों के चुनावों से संबंधित अधिकार रखती है?",
    options_en: ["Article 326", "Article 327", "Article 328", "Article 329"],
    options_hi: ["अनुच्छेद 326", "अनुच्छेद 327", "अनुच्छेद 328", "अनुच्छेद 329"],
    correct_option_index: 2,
    explanation_en: "Article 328 gives the Legislature the right to make laws related to elections in the state.",
    explanation_hi: "अनुच्छेद 328 विधानमंडल/Legislature को राज्य में चुनाव से संबंधित कानून बनाने का अधिकार देता है।",
  },
  {
    question_en: "Fundamental Duty 51A(K) is related to which subject?",
    question_hi: "मौलिक कर्तव्य 51A(K) किससे संबंधित है?",
    options_en: ["Respect for the National Flag", "Duty of parent or guardian", "Promotion of the country's culture", "Encouraging the spirit of nationality"],
    options_hi: ["राष्ट्रीय ध्वज का सम्मान", "माता-पिता या अभिभावक का कर्तव्य", "देश की संस्कृति को बढ़ावा देना", "राष्ट्रीयता की भावना को प्रोत्साहित करना"],
    correct_option_index: 1,
    explanation_en: "Art 51A(K) is the duty of the parent or guardian to provide opportunities for primary education to children between the age of 6 and 14 years.",
    explanation_hi: "Art 51A(K) माता-पिता या अभिभावक का कर्तव्य है कि वह 6 से 14 वर्ष की आयु के बच्चों को प्राथमिक शिक्षा के अवसर प्रदान करे।",
  },
  {
    question_en: "Article 45 is related to which subject?",
    question_hi: "अनुच्छेद 45 किससे संबंधित है?",
    options_en: ["Just and humane conditions of work", "Early childhood care for children under 6 years of age", "Economic development of SC/ST", "Organization of agriculture and animal husbandry"],
    options_hi: ["काम करने की न्यायसंगत दशाएं", "6 वर्ष से कम आयु के बच्चों के लिए प्राथमिक देखभाल", "SC/ST का आर्थिक विकास", "कृषि एवं पशुपालन का संगठन"],
    correct_option_index: 1,
    explanation_en: "Article 45 relates to the right to early childhood care and education for children below 6 years of age.",
    explanation_hi: "अनुच्छेद 45 6 वर्ष से कम आयु के बच्चों के लिए प्रारंभिक बाल्यावस्था देखभाल और शिक्षा के अधिकार से संबंधित है।",
  },
  {
    question_en: "Which principle of DPSP falls under the Socialist Principles?",
    question_hi: "डीपीएस का कौन सा सिद्धांत समाजवादी सिद्धांतों (Socialist Principles) के अंतर्गत आता है?",
    options_en: ["Organization of Gram Panchayats (Art 40)", "Equal pay for equal work (Art 39(d))", "Uniform Civil Code (Art 44)", "Environmental Protection (Art 48A)"],
    options_hi: ["ग्राम पंचायतों का गठन (Art 40)", "समान कार्य के लिए समान वेतन (Art 39(घ))", "समान नागरिक संहिता (Art 44)", "पर्यावरण संरक्षण (Art 48A)"],
    correct_option_index: 1,
    explanation_en: "Equal pay for equal work (Art 39(d)) comes under the Socialist Principles.",
    explanation_hi: "समान कार्य के लिए समान वेतन (Art 39(घ)) समाजवादी सिद्धांतों (Socialist Principles) के अंतर्गत आता है।",
  },
  {
    question_en: "Under which article do the Governor or President have Special Rights, under which they are exempted from arrest?",
    question_hi: "किस अनुच्छेद के तहत राज्यपाल या राष्ट्रपति के विशेषाधिकार (Special Rights) हैं, जिसके तहत उन्हें गिरफ्तारी से छूट मिलती है?",
    options_en: ["Article 352", "Article 360", "Article 361", "Article 368"],
    options_hi: ["अनुच्छेद 352", "अनुच्छेद 360", "अनुच्छेद 361", "अनुच्छेद 368"],
    correct_option_index: 2,
    explanation_en: "Article 361 grants certain special privileges to the President/Governor, such as exemption from arrest (an exception to Article 14).",
    explanation_hi: "अनुच्छेद 361 राष्ट्रपति/राज्यपाल को कुछ विशेषाधिकार प्रदान करता है, जैसे गिरफ्तारी से छूट (अनुच्छेद 14 का अपवाद)।",
  },
  {
    question_en: "In which article is the language to be used in Parliament, Hindi or English, mentioned?",
    question_hi: "संसद में प्रयोग की जाने वाली भाषा हिंदी या अंग्रेजी का उल्लेख किस अनुच्छेद में है?",
    options_en: ["Article 343", "Article 344", "Article 120", "Article 210"],
    options_hi: ["अनुच्छेद 343", "अनुच्छेद 344", "अनुच्छेद 120", "अनुच्छेद 210"],
    correct_option_index: 2,
    explanation_en: "Article 120 relates to the language to be used in Parliament (Hindi/English).",
    explanation_hi: "अनुच्छेद 120 संसद में प्रयोग की जाने वाली भाषा (हिंदी/अंग्रेजी) से संबंधित है।",
  },
  {
    question_en: "Which new article was NOT added to DPSP by the 42nd Constitutional Amendment?",
    question_hi: "42वें संविधान संशोधन द्वारा DPSP में कौन सा नया अनुच्छेद नहीं जोड़ा गया था?",
    options_en: ["39A", "43A", "48A", "45"],
    options_hi: ["39A", "43A", "48A", "45"],
    correct_option_index: 3,
    explanation_en: "39A, 43A, 48A were added by the 42nd CA 1976. Article 45, which relates to the care of children below 6 years of age, was already existing.",
    explanation_hi: "42वें CA 1976 द्वारा 39A, 43A, 48A जोड़े गए थे। अनुच्छेद 45 6 वर्ष से कम आयु के बच्चों की देखभाल से संबंधित है, जो पहले से मौजूद था।",
  },
  {
    question_en: "Which languages belong to the Dravidian family, as mentioned in the source?",
    question_hi: "द्रविड़ परिवार की भाषाएं कौन-कौन सी हैं, जैसा कि स्रोत में उल्लेख है?",
    options_en: ["Tamil, Telugu, Kannada, Malayalam, Odia", "Marathi, Tamil, Telugu, Kannada, Malayalam", "Sanskrit, Hindi, Kannada, Malayalam", "Marathi, Tamil, Telugu, Odia, Bengali"],
    options_hi: ["तमिल, तेलुगु, कन्नड़, मलयालम, ओडिया", "मराठी, तमिल, तेलुगु, कन्नड़, मलयालम", "संस्कृत, हिंदी, कन्नड़, मलयालम", "मराठी, तमिल, तेलुगु, ओडिया, बंगाली"],
    correct_option_index: 1,
    explanation_en: "The Dravidian family of languages includes Marathi, Tamil, Telugu, Kannada, and Malayalam.",
    explanation_hi: "द्रविड़ परिवार की भाषाओं में मराठी, तमिल, तेलुगु, कन्नड़, मलयालम का उल्लेख है।",
  },
  {
    question_en: "Who became the presidents of the Allahabad and Madras Municipal Corporations under the Government of India Act 1919?",
    question_hi: "भारत सरकार अधिनियम 1919 (GOI Act 1919) के तहत इलाहाबाद और मद्रास नगर निगमों के अध्यक्ष कौन बने थे?",
    options_en: ["Pt. Jawaharlal Nehru, Vallabh Bhai Patel", "Vallabh Bhai Patel, Purushottam Das Tandon", "Pt. Jawaharlal Nehru, Purushottam Das Tandon", "Purushottam Das Tandon, Vallabh Bhai Patel"],
    options_hi: ["पं. जवाहरलाल नेहरू, वल्लभ भाई पटेल", "वल्लभ भाई पटेल, पुरुषोत्तम दास टंडन", "पं. जवाहरलाल नेहरू, पुरुषोत्तम दास टंडन", "पुरुषोत्तम दास टंडन, वल्लभ भाई पटेल"],
    correct_option_index: 0,
    explanation_en: "In 1924-25, Pt. Jawaharlal Nehru became the president of the Allahabad Municipal Corporation, and Vallabh Bhai Patel became the president of the Madras Municipal Corporation.",
    explanation_hi: "1924-25 में इलाहाबाद नगर निगम के अध्यक्ष पं. जवाहरलाल नेहरू बने, और वल्लभ भाई पटेल मद्रास नगर निगम के अध्यक्ष बने। (हालांकि, स्रोत में मद्रास का उल्लेख नहीं, सिर्फ वल्लभ भाई पटेल का नाम है)।",
  },
  {
    question_en: "What was the total number of articles and schedules in the draft of the Constitution presented by B.N. Rao in October 1947?",
    question_hi: "बी.एन. राव (BN Rao) द्वारा अक्टूबर 1947 में प्रस्तुत संविधान के प्रारूप (Draft) में कुल कितने अनुच्छेद और अनुसूचियां थीं?",
    options_en: ["395 Articles, 8 Schedules", "243 Articles, 13 Schedules", "211 Articles, 13 Schedules", "243 Articles, 8 Schedules"],
    options_hi: ["395 अनुच्छेद, 8 अनुसूचियां", "243 अनुच्छेद, 13 अनुसूचियां", "211 अनुच्छेद, 13 अनुसूचियां", "243 अनुच्छेद, 8 अनुसूचियां"],
    correct_option_index: 1,
    explanation_en: "The draft of the Constitution presented by B.N. Rao had a total of 243 articles and 13 schedules.",
    explanation_hi: "बी.एन. राव द्वारा प्रस्तुत संविधान के प्रारूप में कुल 243 अनुच्छेद एवं 13 अनुसूचियाँ थीं।",
  },
  {
    question_en: "The language of the Preamble of the Indian Constitution was taken from which country?",
    question_hi: "भारतीय संविधान की प्रस्तावना की भाषा (Language of Preamble) किस देश से ली गई है?",
    options_en: ["USA", "Australia", "Ireland", "France"],
    options_hi: ["USA", "ऑस्ट्रेलिया", "आयरलैंड", "फ्रांस"],
    correct_option_index: 1,
    explanation_en: "The idea of the Preamble is from the USA, but the language of the Preamble is from Australia.",
    explanation_hi: "प्रस्तावना का विचार USA से, लेकिन प्रस्तावना की भाषा ऑस्ट्रेलिया से ली गई है।",
  },
  {
    question_en: "What was the total number of members who attended the first meeting of the Constituent Assembly?",
    question_hi: "संविधान सभा की प्रथम बैठक में कुल कितने सदस्यों ने भाग लिया था?",
    options_en: ["389", "296", "211", "284"],
    options_hi: ["389", "296", "211", "284"],
    correct_option_index: 2,
    explanation_en: "A total of 211 members attended the first meeting (December 9, 1946).",
    explanation_hi: "प्रथम बैठक (9 Dec, 1946) में कुल सदस्य (Total Members) 211 थे।",
  },
  {
    question_en: "Who was the First Deputy Chairman of the Constituent Assembly?",
    question_hi: "प्रथम उप सभापति (First Deputy Chairman) कौन थे?",
    options_en: ["V.T. Krishnamachari", "H.C. Mukherjee", "Sachchidananda Sinha", "B.N. Rao"],
    options_hi: ["वी.टी. कृष्णामाचारी", "एच.सी. मुखर्जी", "सच्चिदानंद सिन्हा", "बी.एन. राव"],
    correct_option_index: 1,
    explanation_en: "The first Deputy Chairman of the Constituent Assembly was H.C. Mukherjee.",
    explanation_hi: "संविधान सभा के प्रथम उप सभापति एच.सी. मुखर्जी थे।",
  },
  {
    question_en: "By what other name is the Indian Councils Act of 1909 known?",
    question_hi: "भारत परिषद अधिनियम-1909 को अन्य किस नाम से जाना जाता है?",
    options_en: ["Diarchy System", "Montagu-Chelmsford Reforms", "Morley-Minto Reforms", "Policy of Cooperation"],
    options_hi: ["द्वैध शासन प्रणाली", "मांटेग्यू-चेम्सफोर्ड सुधार", "मार्ले-मिंटो सुधार", "सहयोग की नीति"],
    correct_option_index: 2,
    explanation_en: "The Indian Councils Act of 1909 is called the Morley-Minto Reforms.",
    explanation_hi: "भारत परिषद अधिनियम-1909 को मार्ले-मिंटो सुधार कानून कहते हैं।",
  },
  {
    question_en: "Which Act introduced the basis of competitive examination for the appointment of employees in the Company?",
    question_hi: "किस अधिनियम ने कंपनी में कर्मचारियों की नियुक्ति के लिए प्रतियोगी परीक्षा (Competitive Exam) के आधार की शुरुआत की?",
    options_en: ["Charter Act of 1833", "Charter Act of 1853", "Act of 1858", "Act of 1861"],
    options_hi: ["1833 का राजलेख", "1853 का राजलेख", "1858 का अधिनियम", "1861 का अधिनियम"],
    correct_option_index: 1,
    explanation_en: "Under the Charter Act of 1853, the appointment of employees in the Company would be based on competitive examination.",
    explanation_hi: "1853 के राजलेख के तहत कंपनी में कर्मचारियों की नियुक्ति प्रतियोगी परीक्षा के आधार पर होगी।",
  },
  {
    question_en: "Who presented the First Republican Budget of independent India?",
    question_hi: "स्वतंत्र भारत का पहला गणतंत्र बजट (First Budget of Republic India) किसने पेश किया था?",
    options_en: ["R.K. Shanmukham Chetty", "John Mathai", "Indira Gandhi", "Nirmala Sitharaman"],
    options_hi: ["आर.के. षणमुखम चेट्टी", "जॉन मथाई", "इंदिरा गांधी", "निर्मला सीतारमण"],
    correct_option_index: 1,
    explanation_en: "The first budget of Republican India was presented by John Mathai.",
    explanation_hi: "गणतंत्र भारत का पहला बजट जॉन मथाई ने पेश किया।",
  },
  {
    question_en: "The provision for Emergency was taken from the Constitution of which country?",
    question_hi: "आपातकाल (Emergency) का प्रावधान किस देश के संविधान से लिया गया है?",
    options_en: ["Russia", "South Africa", "Germany", "Canada"],
    options_hi: ["रूस", "दक्षिण अफ्रीका", "जर्मनी", "कनाडा"],
    correct_option_index: 2,
    explanation_en: "The provision for Emergency was taken from Germany.",
    explanation_hi: "आपातकाल (Emergency) का प्रावधान जर्मनी से लिया गया है।",
  },
];

export default test3Questions;