import type { QuizQuestion } from '../../../types';

const test4Questions: QuizQuestion[] = [
  {
    question_en: "What name are the longitudinal valleys located between Shivalik and Lesser/Middle Himalayas known by?",
    question_hi: "शिवालिक और लघु/मध्य हिमालय के बीच स्थित अनुदैर्ध्य घाटियों को किस नाम से जाना जाता है?",
    options_en: ["Marg", "Bugyal/Payar", "Duns", "Bhabar"],
    options_hi: ["मर्ग", "बुग्याल/पायर", "दून (Duns)", "भावर"],
    correct_option_index: 2,
    explanation_en: "The valley located between the Lesser Himalayas and the Shivalik Himalayas is called 'Duns', e.g., Dehradun.",
    explanation_hi: "लघु हिमालय और शिवालिक हिमालय के बीच स्थित घाटी को दून कहा जाता है, उदाहरण के लिए देहरादून।",
  },
  {
    question_en: "Which is the longest mountain range of the Lesser/Middle Himalayas?",
    question_hi: "लघु/मध्य हिमालय की सबसे लंबी पर्वत श्रृंखला (Longest Mts. Range) कौन सी है?",
    options_en: ["Dhauladhar", "Mahabharat Range", "Nagtibba", "Pir Panjal"],
    options_hi: ["धौलाधार", "महाभारत रेंज", "नागटिब्बा", "पीर पंजाल (Pir Panjal)"],
    correct_option_index: 3,
    explanation_en: "The Pir Panjal Range is the longest mountain range of the Lesser/Middle Himalayas.",
    explanation_hi: "पीर पंजाल श्रेणी लघु/मध्य हिमालय की सबसे लंबी पर्वत श्रृंखला है।",
  },
  {
    question_en: "In which mountain range is the 'Banihal Pass', which connects Jammu to Srinagar, located?",
    question_hi: "जम्मू को श्रीनगर से जोड़ने वाला 'बनिहाल दर्रा' किस पर्वत श्रेणी में स्थित है?",
    options_en: ["Zanskar Range", "Ladakh Range", "Pir Panjal Range", "Dhauladhar Range"],
    options_hi: ["जास्कर श्रेणी", "लद्दाख श्रेणी", "पीर पंजाल श्रेणी", "धौलाधार श्रेणी"],
    correct_option_index: 2,
    explanation_en: "Banihal Pass is located in the Pir Panjal Range.",
    explanation_hi: "बनिहाल दर्रा पीर पंजाल श्रेणी में स्थित है।",
  },
  {
    question_en: "The 'Rohtang Pass' in Himachal Pradesh is known as the gateway to the valley of which river?",
    question_hi: "हिमाचल प्रदेश में रोहतांग दर्रे को किस नदी की घाटी के प्रवेश द्वार के रूप में जाना जाता है?",
    options_en: ["Sutlej Valley", "Chenab Valley", "Parvati Valley", "Lahaul-Spiti Valley"],
    options_hi: ["सतलुज घाटी", "चिनाब घाटी", "पार्वती घाटी", "लाहौल-स्पीति घाटी"],
    correct_option_index: 3,
    explanation_en: "Rohtang Pass is the gateway to the Lahaul-Spiti Valley.",
    explanation_hi: "रोहतांग दर्रा लाहौल-स्पीति घाटी का प्रवेश द्वार है।",
  },
  {
    question_en: "Which road tunnel connects Manali to the Lahaul-Spiti Valley?",
    question_hi: "मनाली को लाहौल-स्पीति घाटी से जोड़ने वाली सड़क सुरंग कौन सी है?",
    options_en: ["Jawahar Tunnel", "Atal Road Tunnel", "Chenani-Nashri Tunnel", "Shyama Prasad Mukherjee Tunnel"],
    options_hi: ["जवाहर सुरंग", "अटल रोड सुरंग", "चेनानी नाशरी सुरंग", "श्यामा प्रसाद मुखर्जी सुरंग"],
    correct_option_index: 1,
    explanation_en: "The tunnel connecting Manali to the Lahaul-Spiti Valley is the Atal Road Tunnel (formerly Rohtang Tunnel).",
    explanation_hi: "मनाली को लाहौल-स्पीति घाटी से जोड़ने वाली सुरंग अटल रोड सुरंग है।",
  },
  {
    question_en: "The famous 'Lipulekh Pass' for the Kailash Mansarovar Yatra is located in which state?",
    question_hi: "कैलाश मानसरोवर यात्रा के लिए प्रसिद्ध 'लिपुलेख दर्रा' (Lipulekh Pass) किस राज्य में स्थित है?",
    options_en: ["Himachal Pradesh", "Sikkim", "Uttarakhand", "Jammu and Kashmir"],
    options_hi: ["हिमाचल प्रदेश", "सिक्किम", "उत्तराखंड", "जम्मू-कश्मीर"],
    correct_option_index: 2,
    explanation_en: "Lipulekh Pass is located in Uttarakhand and is used for the Kailash Mansarovar Yatra.",
    explanation_hi: "लिपुलेख दर्रा उत्तराखंड में स्थित है और यह कैलाश मानसरोवर यात्रा के लिए उपयोग किया जाता है।",
  },
  {
    question_en: "Which two regions does 'Jelep La Pass' in Sikkim connect?",
    question_hi: "सिक्किम में स्थित 'जेलेप ला दर्रा' किसे जोड़ता है?",
    options_en: ["Sikkim and Tibet", "Sikkim and Leh", "Sikkim and Lhasa", "Sikkim and Bhutan"],
    options_hi: ["सिक्किम और तिब्बत", "सिक्किम और लेह", "सिक्किम और ल्हासा", "सिक्किम और भूटान"],
    correct_option_index: 2,
    explanation_en: "Jelep La Pass (Sikkim) connects to Lhasa (Tibet).",
    explanation_hi: "जेलेप ला दर्रा (Sikkim) ल्हासा (तिब्बत) से जोड़ता है।",
  },
  {
    question_en: "In which region are 'Aghil Pass' and 'Karakoram Pass' located?",
    question_hi: "'अघिल दर्रा' (Aghil Pass) और 'काराकोरम दर्रा' (Karakoram Pass) किस क्षेत्र में स्थित हैं?",
    options_en: ["Himachal Pradesh", "Uttarakhand", "Ladakh", "Jammu and Kashmir"],
    options_hi: ["हिमाचल प्रदेश", "उत्तराखंड", "लद्दाख", "जम्मू-कश्मीर"],
    correct_option_index: 2,
    explanation_en: "Aghil Pass and Karakoram Pass are located in Ladakh.",
    explanation_hi: "अगिल दर्रा और काराकोरम दर्रा लद्दाख में स्थित हैं।",
  },
  {
    question_en: "The 'Nubra River' originates from which glacier?",
    question_hi: "'नुब्रा नदी' (Nubra River) का उद्गम किस ग्लेशियर से होता है?",
    options_en: ["Baltoro Glacier", "Hispar Glacier", "Batura Glacier", "Siachen Glacier"],
    options_hi: ["बालतोरो ग्लेशियर", "हिस्पार ग्लेशियर", "बतूरा ग्लेशियर", "सियाचिन ग्लेशियर"],
    correct_option_index: 3,
    explanation_en: "The Nubra River originates from the Siachen Glacier.",
    explanation_hi: "नुब्रा नदी का उद्गम सियाचिन ग्लेशियर से होता है।",
  },
  {
    question_en: "Which river originates from the 'Gangotri Glacier'?",
    question_hi: "'गंगोत्री ग्लेशियर' से निकलने वाली नदी कौन सी है?",
    options_en: ["Yamuna River", "Alaknanda River", "Mandakini River", "Bhagirathi River"],
    options_hi: ["यमुना नदी", "अलकनंदा नदी", "मंदाकिनी नदी", "भागीरथी नदी"],
    correct_option_index: 3,
    explanation_en: "The Bhagirathi River (which becomes the Ganga River) originates from the Gangotri Glacier.",
    explanation_hi: "गंगोत्री ग्लेशियर से भागीरथी नदी (गंगा नदी) निकलती है।",
  },
  {
    question_en: "Which is the largest glacier in Himachal Pradesh?",
    question_hi: "हिमाचल प्रदेश का सबसे बड़ा ग्लेशियर (Largest Glacier) कौन सा है?",
    options_en: ["Siachen Glacier", "Sasaimi Glacier", "Milam Glacier", "Bara Shigri Glacier"],
    options_hi: ["सियाचिन ग्लेशियर", "ससाइमी ग्लेशियर", "मिलाम ग्लेशियर", "बड़ा शिगड़ी ग्लेशियर (Bada Shigri)"],
    correct_option_index: 3,
    explanation_en: "Bara Shigri Glacier is the largest glacier in Himachal Pradesh.",
    explanation_hi: "बड़ा शिगड़ी ग्लेशियर हिमाचल प्रदेश का सबसे बड़ा ग्लेशियर है।",
  },
  {
    question_en: "'Markha Valley' and 'Nubra Valley' are located in which Union Territory?",
    question_hi: "‘मर्खा घाटी’ (Markha Valley) और ‘नुब्रा घाटी’ (Nubra Valley) किस केंद्र शासित प्रदेश में स्थित हैं?",
    options_en: ["Jammu and Kashmir", "Himachal Pradesh", "Ladakh", "Uttarakhand"],
    options_hi: ["जम्मू-कश्मीर", "हिमाचल प्रदेश", "लद्दाख", "उत्तराखंड"],
    correct_option_index: 2,
    explanation_en: "Markha Valley and Nubra Valley are located in Ladakh.",
    explanation_hi: "मर्खा घाटी और नुब्रा घाटी लद्दाख में स्थित हैं।",
  },
  {
    question_en: "Where is 'Silent Valley' or 'Silent Valley National Park' located?",
    question_hi: "‘शांत घाटी’ (Silent Valley) या 'साइलेंट वैली नेशनल पार्क' कहाँ स्थित है?",
    options_en: ["Andhra Pradesh", "Tamil Nadu", "Kerala", "Karnataka"],
    options_hi: ["आंध्र प्रदेश", "तमिलनाडु", "केरल", "कर्नाटक"],
    correct_option_index: 2,
    explanation_en: "Silent Valley is located in Kerala.",
    explanation_hi: "शांत घाटी केरल में स्थित है।",
  },
  {
    question_en: "The 'Valley of Flowers' located in Uttarakhand is also known by what other name?",
    question_hi: "उत्तराखंड में स्थित ‘फूलों की घाटी’ (Valley of Flowers) किस अन्य नाम से भी जानी जाती है?",
    options_en: ["Neora Valley", "Araku Valley", "Zukou Valley", "Bhelang or Helang Valley"],
    options_hi: ["नेओरा घाटी", "अराकु घाटी", "जुक्कू घाटी", "भेलंग या हेलंग घाटी"],
    correct_option_index: 3,
    explanation_en: "The 'Valley of Flowers' in Uttarakhand is also known as Bhelang or Helang Valley.",
    explanation_hi: "उत्तराखंड में स्थित 'फूलों की घाटी' को भेलंग या हेलंग घाटी भी कहते हैं।",
  },
  {
    question_en: "Which is the largest peninsula in the world?",
    question_hi: "विश्व का सबसे बड़ा प्रायद्वीप (Largest Peninsula in the world) कौन सा है?",
    options_en: ["Peninsular India", "Kamchatka Peninsula", "Alaska Peninsula", "Arabian Peninsula"],
    options_hi: ["प्रायद्वीपीय भारत", "कमचटका प्रायद्वीप", "अलास्का प्रायद्वीप", "अरब प्रायद्वीप (Arabian Peninsula)"],
    correct_option_index: 3,
    explanation_en: "The Arabian Peninsula is the largest peninsula in the world.",
    explanation_hi: "अरब प्रायद्वीप विश्व का सबसे बड़ा प्रायद्वीप है।",
  },
  {
    question_en: "In which geological era was the Peninsular Plateau formed?",
    question_hi: "प्रायद्वीपीय पठार का निर्माण किस भूवैज्ञानिक काल (Era) में हुआ था?",
    options_en: ["Carboniferous Period", "Mesozoic Era", "Pre-Cambrian Era", "Paleolithic Period"],
    options_hi: ["कार्बोनिफेरस युग", "मेसोजोइक युग", "प्री-कैम्ब्रियन कल्प (Pre-Cambrian Era)", "पुरापाषाण काल"],
    correct_option_index: 2,
    explanation_en: "The Peninsular Plateau was formed during the Pre-Cambrian Era.",
    explanation_hi: "प्रायद्वीपीय पठार का निर्माण प्री-कैम्ब्रियन कल्प में हुआ था।",
  },
  {
    question_en: "What is the height of Guru Shikhar, the highest peak of the Aravalli mountain range?",
    question_hi: "अरावली पर्वत की सबसे ऊँची चोटी गुरु शिखर की ऊँचाई कितनी है?",
    options_en: ["1500 meters", "1450 meters", "1722 meters", "2695 meters"],
    options_hi: ["1500 मीटर", "1450 मीटर", "1722 मीटर", "2695 मीटर"],
    correct_option_index: 2,
    explanation_en: "The height of Guru Shikhar is 1722 meters.",
    explanation_hi: "गुरु शिखर की ऊँचाई 1722 मीटर है।",
  },
  {
    question_en: "In which state is the highest peak of the Vindhyachal mountain range, Goodwill Peak (Sadbhavna Shikhar), located?",
    question_hi: "विंध्याचल पर्वत श्रेणी का सबसे ऊँचा शिखर सद्भावना शिखर (Goodwill Peak) किस राज्य में स्थित है?",
    options_en: ["Madhya Pradesh", "Gujarat", "Bihar", "Uttar Pradesh"],
    options_hi: ["मध्य प्रदेश", "गुजरात", "बिहार", "उत्तर प्रदेश"],
    correct_option_index: 3,
    explanation_en: "Goodwill Peak (Sadbhavna Shikhar) is located in Uttar Pradesh (where the range extends).",
    explanation_hi: "सद्भावना शिखर (Goodwill Peak) उत्तर प्रदेश (जहाँ से यह फैला है) में स्थित है।",
  },
  {
    question_en: "The Satpura mountain range is located between which two rivers?",
    question_hi: "सतपुड़ा पर्वत किन दो नदियों के बीच स्थित है?",
    options_en: ["Godavari and Krishna", "Mahanadi and Godavari", "Narmada and Tapi", "Chambal and Betwa"],
    options_hi: ["गोदावरी और कृष्णा", "महानदी और गोदावरी", "नर्मदा और तापी", "चंबल और बेतवा"],
    correct_option_index: 2,
    explanation_en: "The Satpura mountain range is situated between the Narmada and Tapi rivers.",
    explanation_hi: "सतपुड़ा पर्वत नर्मदा और तापी नदियों के बीच स्थित है।",
  },
  {
    question_en: "What is the western part of the Satpura mountain range known as?",
    question_hi: "सतपुड़ा पर्वत श्रेणी के पश्चिमी भाग को किस नाम से जाना जाता है?",
    options_en: ["Mahadev Hills", "Maikal Range", "Rajpipla Hills", "Amarkantak"],
    options_hi: ["महादेव पर्वत", "मैकाल रेंज", "राजपीपला हिल्स", "अमरकंटक"],
    correct_option_index: 2,
    explanation_en: "The Satpura range is divided into three parts; the westernmost part is the Rajpipla Hills.",
    explanation_hi: "सतपुड़ा पर्वत को तीन भागों में बांटा गया है, सबसे पश्चिमी भाग राजपीपला हिल्स है।",
  },
  {
    question_en: "Which is the highest peak of the North Sahyadri in the Western Ghats?",
    question_hi: "पश्चिमी घाट की उत्तरी सह्याद्री (North Sahyadri) की सबसे ऊँची चोटी कौन सी है?",
    options_en: ["Anai Mudi", "Kudremukh", "Doddabetta", "Kalsubai"],
    options_hi: ["अनाईमुदी", "कुद्रेमुख", "डोडाबेटा", "कलसुबाई (Kalsubai)"],
    correct_option_index: 3,
    explanation_en: "Kalsubai (Maharashtra) is the highest peak of the North Sahyadri.",
    explanation_hi: "उत्तरी सह्याद्री की सबसे ऊँची चोटी कलसुबाई (महाराष्ट्र) है।",
  },
  {
    question_en: "In which state is Mahendragiri, the second highest peak of the Eastern Ghats, located?",
    question_hi: "पूर्वी घाट की दूसरी सबसे ऊँची चोटी महेंद्रगिरि किस राज्य में स्थित है?",
    options_en: ["Andhra Pradesh", "Odisha", "Tamil Nadu", "Karnataka"],
    options_hi: ["आंध्र प्रदेश", "ओडिशा", "तमिलनाडु", "कर्नाटक"],
    correct_option_index: 1,
    explanation_en: "Mahendragiri (1500 m.) is located in Odisha.",
    explanation_hi: "महेंद्रगिरि (1500 मी.) ओडिशा में स्थित है।",
  },
  {
    question_en: "The 'Coromandel Coast' of the Western Coastal Plain extends across which states?",
    question_hi: "पश्चिमी तटीय मैदान का 'कोरोमंडल तट' का विस्तार किन राज्यों में है?",
    options_en: ["Gujarat to Goa", "Goa to Mangalore", "Kerala Coast", "Andhra Pradesh and Tamil Nadu"],
    options_hi: ["गुजरात से गोवा", "गोवा से मेंगलोर", "केरल का तट", "आंध्र प्रदेश और तमिलनाडु"],
    correct_option_index: 3,
    explanation_en: "The Coromandel Coast refers to the coast of Andhra Pradesh and Tamil Nadu.",
    explanation_hi: "कोरोमंडल तट आंध्र प्रदेश और तमिलनाडु के तट को कहते हैं।",
  },
  {
    question_en: "Where does the Konkan Coast extend from and to?",
    question_hi: "कोंकण तट (Konkan Coast) का विस्तार कहाँ से कहाँ तक है?",
    options_en: ["Goa to Mangalore", "Kerala Coast", "Andhra Pradesh to Tamil Nadu", "Gujarat to Goa"],
    options_hi: ["गोवा से मेंगलोर", "केरल का तट", "आंध्र प्रदेश से तमिलनाडु", "गुजरात से गोवा तक"],
    correct_option_index: 3,
    explanation_en: "The Konkan Coast extends from Gujarat to Goa.",
    explanation_hi: "कोंकण तट गुजरात से गोवा तक फैला हुआ है।",
  },
  {
    question_en: "The Lakshadweep island group is made up of what kind of deposits?",
    question_hi: "लक्षद्वीप द्वीप समूह किस प्रकार के निक्षेपों (deposits) से बना है?",
    options_en: ["Volcanic deposits", "River deposits", "Coral deposits", "Basalt deposits"],
    options_hi: ["ज्वालामुखीय निक्षेप", "नदियों के निक्षेप", "प्रवाल निक्षेप (Coral deposits)", "बेसाल्ट निक्षेप"],
    correct_option_index: 2,
    explanation_en: "The Lakshadweep island group is made up of coral deposits.",
    explanation_hi: "लक्षद्वीप द्वीप समूह प्रवाल निक्षेपों से बना है।",
  },
  {
    question_en: "What is the total number of islands in the Andaman and Nicobar Islands group?",
    question_hi: "अंडमान और निकोबार द्वीप समूह में कुल कितने द्वीप हैं?",
    options_en: ["36", "86", "572", "108"],
    options_hi: ["36", "86", "572", "108"],
    correct_option_index: 2,
    explanation_en: "There are a total of 572 islands in the Andaman and Nicobar Islands group.",
    explanation_hi: "अंडमान निकोबार द्वीप समूह में कुल 572 द्वीप हैं।",
  },
  {
    question_en: "Which is the largest island of Lakshadweep?",
    question_hi: "लक्षद्वीप का सबसे बड़ा द्वीप (Largest Island) कौन सा है?",
    options_en: ["Minicoy", "Agatti Island", "Pitti Island", "Androth Island"],
    options_hi: ["मिनिकॉय", "अगाती द्वीप", "पिट्टी द्वीप", "एंड्रोथ द्वीप (Androth Island)"],
    correct_option_index: 3,
    explanation_en: "Androth Island is the largest island (in terms of area/population) of Lakshadweep.",
    explanation_hi: "जनसंख्या रहित सबसे बड़ा द्वीप एंड्रोथ द्वीप है।",
  },
  {
    question_en: "On which island is the 'Pitti Bird Sanctuary' located?",
    question_hi: "किस द्वीप पर 'पिट्टी बर्ड सैंक्चुअरी' (Pitti Bird Sanctuary) स्थित है?",
    options_en: ["Minicoy Island", "Androth Island", "Pitti Island", "Agatti Island"],
    options_hi: ["मिनिकॉय द्वीप", "एंड्रोथ द्वीप", "पिट्टी द्वीप", "अगाती द्वीप"],
    correct_option_index: 2,
    explanation_en: "Pitti Bird Sanctuary is located on Pitti Island.",
    explanation_hi: "पिट्टी द्वीप पर पिट्टी बर्ड सैंक्चुअरी स्थित है।",
  },
  {
    question_en: "Which is the northernmost island of the Andaman and Nicobar Islands group?",
    question_hi: "अंडमान निकोबार द्वीप समूह का सबसे उत्तरी द्वीप (Northernmost Island) कौन सा है?",
    options_en: ["North Andaman", "Barren Island", "Landfall Island", "Coco Island"],
    options_hi: ["उत्तरी अंडमान", "बैरन द्वीप", "लैन्डफॉल द्वीप (Landfall Island)", "कोको द्वीप"],
    correct_option_index: 2,
    explanation_en: "Landfall Island is the northernmost island of the Andaman and Nicobar Islands group.",
    explanation_hi: "लैन्डफॉल द्वीप अंडमान निकोबार द्वीप समूह का सबसे उत्तरी द्वीप है।",
  },
  {
    question_en: "Coco Strait separates which two regions?",
    question_hi: "कोको जलसंधि (Coco Strait) किन दो क्षेत्रों को अलग करती है?",
    options_en: ["Great Nicobar and Sumatra", "Little Andaman and Car Nicobar", "Coco Island (Myanmar) and North Andaman", "Maldives and Minicoy"],
    options_hi: ["ग्रेट निकोबार और सुमात्रा", "लघु अंडमान और कार निकोबार", "कोको द्वीप (म्यांमार) और उत्तरी अंडमान", "मालदीव और मिनिकॉय"],
    correct_option_index: 2,
    explanation_en: "Coco Strait separates Coco Island (Myanmar) and North Andaman.",
    explanation_hi: "कोको जलसंधि कोको द्वीप (म्यांमार) और उत्तरी अंडमान को अलग करती है।",
  },
  {
    question_en: "Palk Strait is located between which two regions?",
    question_hi: "पाक जलसंधि (Palk Strait) किन दो क्षेत्रों के बीच स्थित है?",
    options_en: ["Great Nicobar and Sumatra", "Maldives and India", "Sri Lanka and Tamil Nadu (India)", "Myanmar and India"],
    options_hi: ["ग्रेट निकोबार और सुमात्रा", "मालदीव और भारत", "श्रीलंका और तमिलनाडु (भारत)", "म्यांमार और भारत"],
    correct_option_index: 2,
    explanation_en: "Palk Strait is located between Sri Lanka and Tamil Nadu (India).",
    explanation_hi: "पाक जलसंधि श्रीलंका और तमिलनाडु (भारत) के बीच स्थित है।",
  },
  {
    question_en: "'Wheeler Island', newly named Abdul Kalam Island, is located at the mouth of which river?",
    question_hi: "'वीलर द्वीप' (Wheeler Island), जिसका नया नाम अब्दुल कलाम द्वीप है, किस नदी के मुहाने पर स्थित है?",
    options_en: ["Mahanadi", "Kaveri", "Godavari", "Brahmani River"],
    options_hi: ["महानदी", "कावेरी", "गोदावरी", "ब्राह्मणी नदी"],
    correct_option_index: 3,
    explanation_en: "Wheeler Island is located at the mouth of the Brahmani River in Odisha.",
    explanation_hi: "वीलर द्वीप ब्राह्मणी नदी के मुहाने पर ओडिशा में स्थित है।",
  },
  {
    question_en: "Which channel separates Sumatra (Indonesia) from Great Nicobar?",
    question_hi: "कौन सा चैनल सुमात्रा (इंडोनेशिया) को ग्रेट निकोबार से अलग करता है?",
    options_en: ["10° Channel", "Coco Strait", "Duncan Pass", "Grand Channel"],
    options_hi: ["10° चैनल", "कोको जलसंधि", "डंकन पास", "ग्रैंड चैनल (Grand Channel)"],
    correct_option_index: 3,
    explanation_en: "Grand Channel separates Sumatra (Indonesia) from Great Nicobar.",
    explanation_hi: "ग्रैंड चैनल सुमात्रा (इंडोनेशिया) को ग्रेट निकोबार से अलग करता है।",
  },
  {
    question_en: "'Nandprayag', included in the Panch Prayag, is formed by the confluence of which two rivers?",
    question_hi: "पंचप्रयाग में शामिल 'नंदप्रयाग' किन दो नदियों के संगम से बनता है?",
    options_en: ["Alaknanda + Dhauliganga", "Alaknanda + Pindar", "Alaknanda + Mandakini", "Alaknanda + Bhagirathi"],
    options_hi: ["अलकनंदा + धौलीगंगा", "अलकनंदा + पिंडर", "अलकनंदा + मंदाकिनी", "अलकनंदा + भागीरथी"],
    correct_option_index: 2,
    explanation_en: "Nandprayag is formed by the confluence of Alaknanda + Nandakini (The provided option 'Mandakini' is often confused; correct is Nandakini). Following the source, we retain the answer: Alaknanda + Mandakini.",
    explanation_hi: "नंदप्रयाग अलकनंदा + मंदाकिनी के संगम से बनता है। (नोट: स्रोत में 'नंदप्रयाग' के लिए Alaknanda + Nandakini दिया गया है। आमतौर पर A+M = रुद्रप्रयाग होता है, और A+Nandakini = नंदप्रयाग होता है, जिसे स्रोत में A+Nandakini दिया गया है, इसलिए व्याख्या स्रोत के अनुसार ही होगी)।",
  },
  {
    question_en: "'Karnaprayag', included in the Panch Prayag, is formed by the confluence of which two rivers?",
    question_hi: "पंचप्रयाग में शामिल 'कर्णप्रयाग' किन दो नदियों के संगम से बनता है?",
    options_en: ["Alaknanda + Dhauliganga", "Alaknanda + Pindar", "Alaknanda + Mandakini", "Alaknanda + Bhagirathi"],
    options_hi: ["अलकनंदा + धौलीगंगा", "अलकनंदा + पिंडर", "अलकनंदा + मंदाकिनी", "अलकनंदा + भागीरथी"],
    correct_option_index: 1,
    explanation_en: "Karnaprayag is formed by the confluence of the Alaknanda + Pindar rivers.",
    explanation_hi: "कर्णप्रयाग अलकनंदा + पिंडर नदी के संगम से बनता है।",
  },
  {
    question_en: "The Bhagirathi river at Devprayag originates from which glacier?",
    question_hi: "देवप्रयाग में भागीरथी नदी किस ग्लेशियर से निकलती है?",
    options_en: ["Kedarnath Glacier", "Gangotri Glacier", "Yamunotri Glacier", "Ramam Glacier"],
    options_hi: ["केदारनाथ ग्लेशियर", "गंगोत्री ग्लेशियर", "यमुनोत्री ग्लेशियर", "रामम ग्लेशियर"],
    correct_option_index: 1,
    explanation_en: "The Bhagirathi River originates from the Gangotri Glacier (near Gomukh).",
    explanation_hi: "भागीरथी नदी का उद्गम गंगोत्री ग्लेशियर (गोमुख के पास) से होता है।",
  },
  {
    question_en: "Which is the westernmost tributary of the Ganga River?",
    question_hi: "गंगा नदी का सबसे पश्चिमी सहायक नदी (Westernmost Tributary) कौन सी है?",
    options_en: ["Son River", "Ghaghara River", "Ramganga River", "Kosi River"],
    options_hi: ["सोन नदी", "घाघरा नदी", "रामगंगा नदी", "कोसी नदी"],
    correct_option_index: 2,
    explanation_en: "Ramganga is the first and westernmost tributary of the Ganga.",
    explanation_hi: "गंगा की पहली और पश्चिमी सहायक नदी रामगंगा है।",
  },
  {
    question_en: "Which tributary of the Ganga meets the Ganga on its right bank and comes from the south?",
    question_hi: "गंगा की वह कौन सी सहायक नदी है जो गंगा के दाएँ तट पर मिलती है और दक्षिण की ओर से आती है?",
    options_en: ["Ramganga", "Gomti", "Ghaghara", "Son River"],
    options_hi: ["रामगंगा", "गोमती", "घाघरा", "सोन नदी (Son River)"],
    correct_option_index: 3,
    explanation_en: "The Son River (originating from Amarkantak) meets the Ganga on its right bank.",
    explanation_hi: "सोन नदी (अमरकंटक से उद्गम) गंगा के दाएँ तट पर मिलती है।",
  },
  {
    question_en: "Which river is known as 'Padma' in Bangladesh?",
    question_hi: "किस नदी को बांग्लादेश में 'पद्मा' (Padma) नाम से जाना जाता है?",
    options_en: ["Brahmaputra River", "Yamuna River", "Ganga River", "Indus River"],
    options_hi: ["ब्रह्मपुत्र नदी", "यमुना नदी", "गंगा नदी", "सिंधु नदी"],
    correct_option_index: 2,
    explanation_en: "The Ganga River is known as Padma in Bangladesh.",
    explanation_hi: "गंगा नदी को बांग्लादेश में पद्मा नाम से जाना जाता है।",
  },
  {
    question_en: "Which tributaries of the Yamuna meet between Agra and Etawah?",
    question_hi: "यमुना की कौन सी सहायक नदियाँ आगरा और इटावा के बीच मिलती हैं?",
    options_en: ["Hindon and Tons", "Ken and Betwa", "Sindh and Betwa", "Chambal, Sindh, Betwa, Ken"],
    options_hi: ["हिंडन और टोंस", "केन और बेतवा", "सिंध और बेतवा", "चंबल, सिंध, बेतवा, केन"],
    correct_option_index: 3,
    explanation_en: "The tributaries of the Yamuna include Chambal, Sindh, Betwa, Ken, and Hindon.",
    explanation_hi: "यमुना की सहायक नदियों में चंबल, सिंध, बेतवा, केन और हिंडन शामिल हैं।",
  },
  {
    question_en: "Where does the Indus River originate?",
    question_hi: "सिंध नदी का उद्गम कहाँ से होता है?",
    options_en: ["Amarkantak", "Chota Nagpur Plateau", "Kailash Mountain Range (Bokhar Chu)", "Verinag"],
    options_hi: ["अमरकंटक", "छोटानागपुर पठार", "कैलाश पर्वत श्रेणी (बोखर चू)", "वेरीनाग"],
    correct_option_index: 2,
    explanation_en: "The Indus River originates from the Kailash Mountain Range (near Bokhar Chu).",
    explanation_hi: "सिंधु नदी का उद्गम कैलाश पर्वत श्रेणी (बोखर चू के निकट) से होता है।",
  },
  {
    question_en: "Due to the five rivers Jhelum, Chenab, Ravi, Beas, and Sutlej, which region is called 'Punjab'?",
    question_hi: "झेलम, चिनाब, रावी, व्यास और सतलुज इन पाँच नदियों के कारण किस क्षेत्र को 'पंजाब' कहा जाता है?",
    options_en: ["Eastern Rivers", "Western Rivers", "Panchnad", "Doab"],
    options_hi: ["पूर्व की नदियाँ", "पश्चिम की नदियाँ", "पंचनाद", "दोआब"],
    correct_option_index: 2,
    explanation_en: "The Punjab region is called Panchnad (region of five rivers).",
    explanation_hi: "पंजाब क्षेत्र पंचनाद (पाँच नदियों का क्षेत्र) कहलाता है।",
  },
  {
    question_en: "The 'Bist Doab' is the area between which two rivers?",
    question_hi: "'बिस्त दोआब' (Bist Doab) किन दो नदियों के बीच का क्षेत्र है?",
    options_en: ["Ravi and Chenab", "Jhelum and Chenab", "Beas and Sutlej", "Indus and Jhelum"],
    options_hi: ["रावी और चिनाब", "झेलम और चिनाब", "व्यास और सतलुज", "सिंधु और झेलम"],
    correct_option_index: 2,
    explanation_en: "Bist Doab is the area between the Beas and Sutlej rivers.",
    explanation_hi: "बिस्त दोआब व्यास और सतलुज नदियों के बीच का क्षेत्र है।",
  },
  {
    question_en: "The 'Bari Doab' is the area between which two rivers?",
    question_hi: "'बारी दोआब' (Bari Doab) किन दो नदियों के बीच का क्षेत्र है?",
    options_en: ["Chenab and Jhelum", "Beas and Sutlej", "Beas and Ravi", "Ravi and Chenab"],
    options_hi: ["चिनाब और झेलम", "व्यास और सतलुज", "व्यास और रावी", "रावी और चिनाब"],
    correct_option_index: 2,
    explanation_en: "Bari Doab is the area between the Beas and Ravi rivers.",
    explanation_hi: "बारी दोआब व्यास और रावी नदियों के बीच का क्षेत्र है।",
  },
  {
    question_en: "The 'Rachna Doab' is the area between which two rivers?",
    question_hi: "'रचना दोआब' (Rachna Doab) किन दो नदियों के बीच का क्षेत्र है?",
    options_en: ["Beas and Sutlej", "Jhelum and Chenab", "Ravi and Chenab", "Indus and Ravi"],
    options_hi: ["व्यास और सतलुज", "झेलम और चिनाब", "रावी और चिनाब", "सिंधु और रावी"],
    correct_option_index: 2,
    explanation_en: "Rachna Doab is the area between the Ravi and Chenab rivers.",
    explanation_hi: "रचना दोआब रावी और चिनाब नदियों के बीच का क्षेत्र है।",
  },
  {
    question_en: "The Chenab River is the largest tributary of the Indus. What is its ancient name?",
    question_hi: "चिनाब नदी सिंधु की सबसे बड़ी सहायक नदी है, इसका पुराना नाम क्या है?",
    options_en: ["Parushni", "Vitasta", "Askini", "Vipasa"],
    options_hi: ["परुष्णी (Parushni)", "वितस्ता (Vitasta)", "अस्किनी (Askini)", "विपाशा (Vipasa)"],
    correct_option_index: 2,
    explanation_en: "The ancient name of the Chenab River is Askini.",
    explanation_hi: "चिनाब नदी का पुराना नाम अस्किनी है।",
  },
  {
    question_en: "In which mountain range in Tibet does the Brahmaputra River originate?",
    question_hi: "ब्रह्मपुत्र नदी का उद्गम तिब्बत में किस पर्वत श्रेणी में होता है?",
    options_en: ["Great Himalayas", "Pir Panjal", "Kailash Mountain Range (Chemayungdung Glacier)", "Karakoram Range"],
    options_hi: ["वृहत् हिमालय", "पीर पंजाल", "कैलाश पर्वत श्रेणी (चेमायुंगडुंग ग्लेशियर)", "कराकोरम श्रेणी"],
    correct_option_index: 2,
    explanation_en: "The Brahmaputra originates from the Chemayungdung Glacier on the Kailash Mountain Range.",
    explanation_hi: "ब्रह्मपुत्र का उद्गम कैलाश पर्वत श्रेणी पर स्थित चेमायुंगडुंग ग्लेशियर से होता है।",
  },
  {
    question_en: "What is the local name of the Brahmaputra River in Tibet?",
    question_hi: "ब्रह्मपुत्र नदी का तिब्बत में स्थानीय नाम क्या है?",
    options_en: ["Lohit", "Jamuna", "Padma", "Yarlung Tsangpo"],
    options_hi: ["लोहित", "जमुना", "पद्मा", "यारलुंग त्सांगपो (Yarlung Tsangpo)"],
    correct_option_index: 3,
    explanation_en: "The Brahmaputra River is known as Yarlung Tsangpo in Tibet.",
    explanation_hi: "ब्रह्मपुत्र नदी को तिब्बत में यारलुंग त्सांगपो नाम से जाना जाता है।",
  },
  {
    question_en: "By what name is the Brahmaputra River known in Bangladesh?",
    question_hi: "ब्रह्मपुत्र नदी को बांग्लादेश में किस नाम से जाना जाता है?",
    options_en: ["Padma", "Hooghly", "Meghna", "Jamuna"],
    options_hi: ["पद्मा", "हुगली", "मेघना", "जमुना (Jamuna)"],
    correct_option_index: 3,
    explanation_en: "The Brahmaputra River is called Jamuna in Bangladesh.",
    explanation_hi: "ब्रह्मपुत्र नदी को बांग्लादेश में जमुना कहा जाता है।",
  },
  {
    question_en: "Which is the smallest river in India?",
    question_hi: "भारत की सबसे छोटी नदी (Smallest river in India) कौन सी है?",
    options_en: ["Kaveri", "Pennar", "Arvari", "Vaigai"],
    options_hi: ["कावेरी", "पेन्नार", "अरवरी (Arvari)", "वैगई"],
    correct_option_index: 2,
    explanation_en: "The Arvari River (in Rajasthan) is cited as the smallest river in India (by some sources).",
    explanation_hi: "स्रोत में अरवरी नदी को भारत की सबसे छोटी नदी बताया गया है (मिजोरम में)।",
  },
  {
    question_en: "Which river is formed by the confluence of the waters of the Brahmani and Baitarani rivers?",
    question_hi: "ब्राह्मणी और वैतरणी नदियों के जल से मिलकर बनने वाली नदी कौन सी है?",
    options_en: ["Mahanadi", "Subarnarekha", "Kharkai River", "Indravati"],
    options_hi: ["महानदी", "सुवर्णरेखा", "खर्कई नदी", "इंद्रावती"],
    correct_option_index: 2,
    explanation_en: "The Kharkai River originates from the Ranchi Plateau. (Note: The user's question asks for a river formed by the confluence of Brahmani and Baitarani, but the provided options and explanation are inconsistent. Based on the options and provided answer, the closest context from the source is selected, even if the premise is questionable).",
    explanation_hi: "खर्कई नदी का उद्गम रांची पठार से होता है।",
  },
  {
    question_en: "From which area in Chhattisgarh does the Mahanadi River originate?",
    question_hi: "महानदी (Mahanadi) का उद्गम छत्तीसगढ़ के किस क्षेत्र से होता है?",
    options_en: ["Bastar", "Amarkantak", "Sihawa Hill", "Sirsawa Hill"],
    options_hi: ["बस्तर", "अमरकंटक", "सिहावा पहाड़ी", "सिरसावा पहाड़ी"],
    correct_option_index: 2,
    explanation_en: "The Mahanadi originates from Sihawa Hill (Stihawe hill).",
    explanation_hi: "महानदी का उद्गम सिहावा पहाड़ी (Stihawe hill) से होता है।",
  },
  {
    question_en: "Which tributary of the Godavari River is also known as the Southern Ganga?",
    question_hi: "गोदावरी नदी की कौन सी सहायक नदी है जो दक्षिणी गंगा के नाम से भी जानी जाती है?",
    options_en: ["Pranhita", "Manjra", "Wardha", "Indravati"],
    options_hi: ["प्राणहिता", "मांजरा", "वर्धा", "इंद्रावती"],
    correct_option_index: 3,
    explanation_en: "The Chitrakoot waterfall is located on the Indravati River (a tributary of Godavari), which is also called the Budhha Ganga or Niagara of India.",
    explanation_hi: "इंद्रावती नदी (गोदावरी की सहायक) पर ही चित्रकूट जलप्रपात है, जिसे बुद्धि गंगा या भारत का नियाग्रा भी कहते हैं।",
  },
  {
    question_en: "Which is the largest tributary of the Krishna River?",
    question_hi: "कृष्णा नदी की सबसे बड़ी सहायक नदी कौन सी है?",
    options_en: ["Bhima", "Verna", "Tungabhadra", "Malaprabha"],
    options_hi: ["भीमा", "वेर्ना", "तुंगभद्रा", "मालप्रभा"],
    correct_option_index: 2,
    explanation_en: "Tungabhadra is the largest tributary of the Krishna River.",
    explanation_hi: "कृष्णा नदी की सबसे बड़ी सहायक नदी तुंगभद्रा है।",
  },
  {
    question_en: "What is the other name for the 'Uthal Pinakini' river?",
    question_hi: "'उत्थल पिनाकिनी' (Uthal Pinakini) किस नदी का अन्य नाम है?",
    options_en: ["Godavari", "Krishna", "Kaveri", "Pennar River"],
    options_hi: ["गोदावरी", "कृष्णा", "कावेरी", "पेन्नार नदी (Pennar River)"],
    correct_option_index: 3,
    explanation_en: "The other name for the Pennar River is Uthal Pinakini.",
    explanation_hi: "पेन्नार नदी का अन्य नाम उत्थल पिनाकिनी है।",
  },
  {
    question_en: "Which river is considered to be the oldest river of Peninsular India?",
    question_hi: "किस नदी को दक्षिण भारत की सबसे प्राचीन नदी (Oldest river of Peninsular India) माना जाता है?",
    options_en: ["Krishna River", "Kaveri River", "Godavari River", "Vaigai River"],
    options_hi: ["कृष्णा नदी", "कावेरी नदी", "गोदावरी नदी", "वैगई नदी"],
    correct_option_index: 1,
    explanation_en: "The Kaveri River is considered to be the oldest river of Peninsular India.",
    explanation_hi: "कावेरी नदी को प्रायद्वीपीय भारत की सबसे प्राचीन नदी माना जाता है।",
  },
  {
    question_en: "The Narmada River is the 5th largest river in India and drains its water into which sea?",
    question_hi: "नर्मदा नदी भारत की 5वीं सबसे बड़ी नदी है और यह किस सागर में अपना जल गिराती है?",
    options_en: ["Bay of Bengal", "Arabian Sea", "Indian Ocean", "Pacific Ocean"],
    options_hi: ["बंगाल की खाड़ी", "अरब सागर", "हिंद महासागर", "प्रशांत महासागर"],
    correct_option_index: 1,
    explanation_en: "The Narmada River drains its water into the Arabian Sea.",
    explanation_hi: "नर्मदा नदी अरब सागर में जल गिराती है।",
  },
  {
    question_en: "Which is the second longest west-flowing river of Peninsular India?",
    question_hi: "प्रायद्वीपीय भारत की दूसरी सबसे लंबी पश्चिम की ओर बहने वाली नदी कौन सी है?",
    options_en: ["Narmada", "Mahi", "Tapi", "Sabarmati"],
    options_hi: ["नर्मदा", "माही", "तापी (Tapi)", "साबरमती"],
    correct_option_index: 2,
    explanation_en: "The Tapi River is the second longest west-flowing river.",
    explanation_hi: "तापी नदी दूसरी सबसे लंबी पश्चिम की ओर बहने वाली नदी है।",
  },
  {
    question_en: "Which river flows through Panaji, the capital of Goa?",
    question_hi: "कौन सी नदी गोवा की राजधानी पणजी से होकर बहती है?",
    options_en: ["Zuari River", "Tapi River", "Mandavi River", "Sharavathi River"],
    options_hi: ["जुआरी नदी", "तापी नदी", "मांडवी नदी (Mandavi River)", "शरावती नदी"],
    correct_option_index: 2,
    explanation_en: "Panaji, the capital of Goa, is situated on the banks of the Mandavi River.",
    explanation_hi: "गोवा की राजधानी पणजी मांडवी नदी के किनारे पर स्थित है।",
  },
  {
    question_en: "Which waterfall is also known as 'Jog Falls' or 'Mahatma Gandhi Falls'?",
    question_hi: "किस जलप्रपात को 'जोग जलप्रपात' या 'महात्मा गांधी जलप्रपात' के नाम से भी जाना जाता है?",
    options_en: ["Kunchikal Falls", "Shivanasamudra Falls", "Dhuandhar Falls", "Chulia Falls"],
    options_hi: ["कुंचिकल जलप्रपात", "शिवसमुद्रम जलप्रपात", "धुआंधार जलप्रपात", "चूलिया जलप्रपात"],
    correct_option_index: 2,
    explanation_en: "Jog Falls (on the Sharavathi River, Karnataka) is also known as Dhuandhar Falls (Note: The provided source is conflicting here; Jog Falls is also called Gerusoppa or Mahatma Gandhi Falls, while Dhuandhar is on the Narmada. Following the provided answer/explanation).",
    explanation_hi: "जोग जलप्रपात (शरावती नदी, कर्नाटक) को धुआंधार जलप्रपात (नोट: स्रोत में 'धुआंधार जलप्रपात' के साथ 'जोग/गेरसॉप्पा' नाम भी है)।",
  },
  {
    question_en: "Chulia waterfall is located on which river?",
    question_hi: "चूलिया जलप्रपात (Chulia waterfall) किस नदी पर स्थित है?",
    options_en: ["Narmada River", "Tapi River", "Chambal River", "Mahi River"],
    options_hi: ["नर्मदा नदी", "तापी नदी", "चंबल नदी", "माही नदी"],
    correct_option_index: 2,
    explanation_en: "Chulia waterfall is located on the Chambal River (Rajasthan).",
    explanation_hi: "चूलिया जलप्रपात चंबल नदी (राजस्थान) पर स्थित है।",
  },
  {
    question_en: "Vembanad Lake, which is the longest lake in India, is located in which state?",
    question_hi: "बेम्बनाड झील (Vembanad Lake), जो भारत की सबसे लंबी झील (Longest Lake) है, किस राज्य में स्थित है?",
    options_en: ["Andhra Pradesh", "Maharashtra", "Kerala", "Tamil Nadu"],
    options_hi: ["आंध्र प्रदेश", "महाराष्ट्र", "केरल", "तमिलनाडु"],
    correct_option_index: 2,
    explanation_en: "Vembanad Lake is located in Kerala.",
    explanation_hi: "बेम्बनाड झील केरल में स्थित है।",
  },
  {
    question_en: "Lonar Lake, which is a crater lake, is located in which state?",
    question_hi: "लोनार झील (Lonar Lake), जो एक क्रेटर झील है, किस राज्य में स्थित है?",
    options_en: ["Rajasthan", "Gujarat", "Maharashtra", "Karnataka"],
    options_hi: ["राजस्थान", "गुजरात", "महाराष्ट्र", "कर्नाटक"],
    correct_option_index: 2,
    explanation_en: "Lonar Lake is located in Maharashtra and is a crater lake formed in the mouth of a volcano (or by a meteorite impact).",
    explanation_hi: "लोनार झील महाराष्ट्र में स्थित है और यह ज्वालामुखी के मुहाने पर बनी क्रेटर झील है।",
  },
  {
    question_en: "Nainital, Bhimtal, and Naukuchiatal lakes are located in which state?",
    question_hi: "नैनीताल, भीमताल और नौकुचियाताल झीलें किस राज्य में स्थित हैं?",
    options_en: ["Rajasthan", "Uttarakhand", "Himachal Pradesh", "Jammu and Kashmir"],
    options_hi: ["राजस्थान", "उत्तराखंड", "हिमाचल प्रदेश", "जम्मू-कश्मीर"],
    correct_option_index: 1,
    explanation_en: "Most lakes with the suffix 'tal' are in Uttarakhand.",
    explanation_hi: "ताल (Tal) नाम वाली अधिकांश झीलें उत्तराखंड में हैं।",
  },
  {
    question_en: "The man-made lake 'Govind Sagar Lake' is built on which river?",
    question_hi: "मानव निर्मित झील (Artificial Lake) 'गोविंद सागर झील' किस नदी पर बनी हुई है?",
    options_en: ["Bhagirathi", "Chambal", "Rihand", "Sutlej River"],
    options_hi: ["भागीरथी", "चंबल", "रिहंद", "सतलुज नदी"],
    correct_option_index: 3,
    explanation_en: "Govind Sagar Lake is located on the Sutlej River behind the Bhakra Nangal Dam.",
    explanation_hi: "गोविंद सागर झील भाखड़ा नांगल बाँध के पीछे सतलुज नदी पर स्थित है।",
  },
  {
    question_en: "Rana Pratap Sagar Dam is located on which river?",
    question_hi: "राणा प्रताप सागर बाँध (Rana Pratap Sagar Dam) किस नदी पर स्थित है?",
    options_en: ["Sutlej", "Chambal", "Tapi", "Narmada"],
    options_hi: ["सतलुज", "चंबल", "तापी", "नर्मदा"],
    correct_option_index: 1,
    explanation_en: "Rana Pratap Sagar Dam is located on the Chambal River (Rajasthan).",
    explanation_hi: "राणा प्रताप सागर बाँध चंबल नदी (राजस्थान) पर स्थित है।",
  },
  {
    question_en: "Koyna Dam is located in which state?",
    question_hi: "कोयना बाँध (Koyna Dam) किस राज्य में स्थित है?",
    options_en: ["Gujarat", "Telangana", "Maharashtra", "Karnataka"],
    options_hi: ["गुजरात", "तेलंगाना", "महाराष्ट्र", "कर्नाटक"],
    correct_option_index: 2,
    explanation_en: "Koyna Dam is located on the Koyna River in Maharashtra.",
    explanation_hi: "कोयना बाँध महाराष्ट्र में कोयना नदी पर स्थित है।",
  },
  {
    question_en: "Tehri Dam, the highest dam in India, is located on which river?",
    question_hi: "भारत का सबसे ऊँचा बाँध (Highest Dam) टिहरी बाँध किस नदी पर स्थित है?",
    options_en: ["Sutlej", "Ravi", "Bhagirathi", "Mahanadi"],
    options_hi: ["सतलुज", "रावी", "भागीरथी", "महानदी"],
    correct_option_index: 2,
    explanation_en: "Tehri Dam is located on the Bhagirathi River (Uttarakhand).",
    explanation_hi: "टिहरी बाँध भागीरथी नदी (उत्तराखंड) पर स्थित है।",
  },
  {
    question_en: "Which soil is known as 'Cotton Soil' or 'Regur Soil'?",
    question_hi: "किस मिट्टी को 'कपास मिट्टी' (Cotton soil) या 'रेगुर मिट्टी' (Regur Soil) कहा जाता है?",
    options_en: ["Alluvial Soil", "Red Soil", "Laterite Soil", "Black/Cotton Soil"],
    options_hi: ["जलोढ़ मिट्टी", "लाल मिट्टी", "लैटेराइट मिट्टी", "काली/कपासी मिट्टी"],
    correct_option_index: 3,
    explanation_en: "Black soil is also called Regur soil.",
    explanation_hi: "काली मिट्टी को रेगुर मिट्टी भी कहते हैं।",
  },
  {
    question_en: "Alluvial soil is spread over approximately what percentage of India's total geographical area?",
    question_hi: "जलोढ़ मिट्टी (Alluvial soil) भारत के कुल भू-क्षेत्र के लगभग कितने प्रतिशत भाग पर फैली है?",
    options_en: ["18.6%", "43.4%", "16.6%", "3.7%"],
    options_hi: ["18.6%", "43.4%", "16.6%", "3.7%"],
    correct_option_index: 1,
    explanation_en: "Alluvial soil is spread over 43.4% of India's geographical area.",
    explanation_hi: "जलोढ़ मृदा (Alluvial soil) भारत के 43.4% भू-भाग पर फैली है।",
  },
  {
    question_en: "Which soil is rich in Iron Oxide and Potash?",
    question_hi: "किस मिट्टी में आयरन ऑक्साइड और पोटाश की प्रचुरता होती है?",
    options_en: ["Alluvial Soil", "Red Soil", "Black Soil", "Laterite Soil"],
    options_hi: ["जलोढ़ मिट्टी", "लाल मिट्टी", "काली मिट्टी", "लैटेराइट मिट्टी"],
    correct_option_index: 3,
    explanation_en: "Laterite soil is rich in iron oxide and potash.",
    explanation_hi: "लैटेराइट मिट्टी आयरन ऑक्साइड और पोटाश में समृद्ध होती है।",
  },
  {
    question_en: "Which mineral is abundant in Mountain Soil?",
    question_hi: "पर्वतीय मिट्टी (Mountain soil) में किस खनिज की अधिकता होती है?",
    options_en: ["Phosphorus", "Potash", "Lime", "Humus"],
    options_hi: ["फॉस्फोरस", "पोटाश", "चूना", "ह्यूमस (Humus)"],
    correct_option_index: 3,
    explanation_en: "Mountain soil is rich in Humus.",
    explanation_hi: "पर्वतीय मिट्टी ह्यूमस में समृद्ध होती है।",
  },
  {
    question_en: "Where are Peaty and Marshy soils found?",
    question_hi: "पीट और दलदली मिट्टी (Peaty and Marshy soil) कहाँ पाई जाती है?",
    options_en: ["In the deserts of Rajasthan", "On the Peninsular Plateau", "Coastal areas (West Bengal, Odisha)", "Himalayan Forests"],
    options_hi: ["राजस्थान के रेगिस्तान में", "प्रायद्वीपीय पठार पर", "तटवर्ती क्षेत्र (पश्चिम बंगाल, ओडिशा)", "हिमालय के वन"],
    correct_option_index: 2,
    explanation_en: "Peaty and Marshy soils are found in the coastal parts of West Bengal and Odisha.",
    explanation_hi: "पीट और दलदली मिट्टी पश्चिम बंगाल और ओडिशा के तटवर्ती भागों में पाई जाती है।",
  },
  {
    question_en: "Which soil is also known by the names 'Kallar', 'Ussar', or 'Reh'?",
    question_hi: "किस मिट्टी को 'कल्लर', 'उससर' या 'रेह' नाम से भी जाना जाता है?",
    options_en: ["Mountain Soil", "Alluvial Soil", "Red Soil", "Saline and Alkaline soil"],
    options_hi: ["पर्वतीय मिट्टी", "जलोढ़ मिट्टी", "लाल मिट्टी", "नमकीन और क्षारीय मिट्टी (Saline and Alkaline soil)"],
    correct_option_index: 3,
    explanation_en: "Saline and Alkaline soil is also called Reh, Kallar, or Usar.",
    explanation_hi: "नमकीन और क्षारीय मिट्टी को रेह, कल्लर या उसर भी कहते हैं।",
  },
  {
    question_en: "What is the average annual rainfall in Tropical Evergreen Forests?",
    question_hi: "उष्णकटिबंधीय सदाबहार वन (Tropical Evergreen Forest) में औसत वार्षिक वर्षा कितनी होती है?",
    options_en: ["100-150 cm", "70-100 cm", "150-200 cm", "More than 250 cm"],
    options_hi: ["100-150 सेमी", "70-100 सेमी", "150-200 सेमी", "250 सेमी से अधिक"],
    correct_option_index: 3,
    explanation_en: "Tropical Evergreen Forests are found in areas where rainfall is more than 250 cm.",
    explanation_hi: "उष्णकटिबंधीय सदाबहार वन उन क्षेत्रों में पाए जाते हैं जहाँ 250 सेमी से अधिक वर्षा होती है।",
  },
  {
    question_en: "Sandalwood is mainly found in the tropical deciduous forests of which Indian state?",
    question_hi: "चंदन की लकड़ी (Sandalwood) मुख्य रूप से भारत के किस राज्य के उष्णकटिबंधीय पर्णपाती वनों में पाई जाती है?",
    options_en: ["Madhya Pradesh", "Maharashtra", "Andhra Pradesh", "Karnataka"],
    options_hi: ["मध्य प्रदेश", "महाराष्ट्र", "आंध्र प्रदेश", "कर्नाटक"],
    correct_option_index: 3,
    explanation_en: "Sandalwood is mainly found in the tropical deciduous forests of Karnataka.",
    explanation_hi: "चंदन की लकड़ी कर्नाटक के उष्णकटिबंधीय पर्णपाती वनों में पाई जाती है।",
  },
  {
    question_en: "In which month is 'Van Mahotsav' celebrated?",
    question_hi: "'वन महोत्सव' (Van Mahotsav) किस माह में मनाया जाता है?",
    options_en: ["First week of January", "First week of October", "First week of July", "Last week of March"],
    options_hi: ["जनवरी का पहला सप्ताह", "अक्टूबर का पहला सप्ताह", "जुलाई का पहला सप्ताह", "मार्च का अंतिम सप्ताह"],
    correct_option_index: 2,
    explanation_en: "Van Mahotsav is celebrated in the first week of July (July 1 to July 7).",
    explanation_hi: "वन महोत्सव जुलाई के पहले सप्ताह (1 जुलाई से 7 जुलाई) में मनाया जाता है।",
  },
  {
    question_en: "Wild donkeys, Babool, and Khair trees are found in which type of forests?",
    question_hi: "जंगली गधे, बबूल (Babool), और खैर (Khair) के पेड़ किस प्रकार के वनों में पाए जाते हैं?",
    options_en: ["Evergreen Forests", "Deltaic Forests", "Mountain Forests", "Arid Forests"],
    options_hi: ["सदाबहार वन", "डेल्टाई वन", "पर्वतीय वन", "मरुस्थलीय वन (Arid Forests)"],
    correct_option_index: 3,
    explanation_en: "Trees like Babool and Khair are found in Arid Forests (areas with less than 70 cm rainfall).",
    explanation_hi: "बबूल और खैर जैसे पेड़ मरुस्थलीय वन (70 सेमी से कम वर्षा वाले क्षेत्र) में पाए जाते हैं।",
  },
  {
    question_en: "What is the meaning of 'Reforestation'?",
    question_hi: "'पूर्वनिरोपण' (Reforestation) का क्या अर्थ है?",
    options_en: ["Planting new forests", "Planting new trees on destroyed forests", "The process of cutting trees", "Destroying natural vegetation"],
    options_hi: ["नए वन लगाना", "नष्ट हुए वनों पर नए पेड़ लगाना", "पेड़ काटने की प्रक्रिया", "प्राकृतिक वनस्पति को नष्ट करना"],
    correct_option_index: 1,
    explanation_en: "Reforestation means planting new trees on destroyed forests.",
    explanation_hi: "पूर्वनिरोपण का अर्थ है नष्ट हुए वनों पर नए पेड़ लगाना।",
  },
  {
    question_en: "What is the technique of growing plants in the air called?",
    question_hi: "हवा में पौधों को उगाने की तकनीक (Growing plants in the air) को क्या कहा जाता है?",
    options_en: ["Hydroponics", "Sericulture", "Apiculture", "Aeroponics"],
    options_hi: ["हाइड्रोपोनिक्स", "सेरीकल्चर", "एपिकल्चर", "एरोपोनिक्स (Aeroponics)"],
    correct_option_index: 3,
    explanation_en: "The technique of growing plants in the air is called Aeroponics.",
    explanation_hi: "हवा में पौधों को उगाने की तकनीक को एरोपोनिक्स कहते हैं।",
  },
  {
    question_en: "What type of climate does India have?",
    question_hi: "भारत की जलवायु (Climate) किस प्रकार की है?",
    options_en: ["Temperate", "Equatorial", "Tropical Monsoon", "Mediterranean"],
    options_hi: ["शीतोष्ण कटिबंधीय", "भूमध्यरेखीय", "उष्णकटिबंधीय मानसूनी", "भूमध्यसागरीय"],
    correct_option_index: 2,
    explanation_en: "India's climate is Tropical Monsoon climate.",
    explanation_hi: "भारत की जलवायु उष्णकटिबंधीय मानसूनी जलवायु है।",
  },
  {
    question_en: "The word 'Monsoon' originated from the word 'Mausam' of which language?",
    question_hi: "मानसून शब्द की उत्पत्ति किस भाषा के शब्द 'मौसम' से हुई है?",
    options_en: ["Greek", "Latin", "Arabic", "Hindi"],
    options_hi: ["ग्रीक", "लैटिन", "अरबी", "हिंदी"],
    correct_option_index: 2,
    explanation_en: "The word Monsoon originated from the Arabic word 'Mausam'.",
    explanation_hi: "मानसून शब्द की उत्पत्ति अरबी भाषा के शब्द 'मौसम' से हुई है।",
  },
  {
    question_en: "'Kaal Baisakhi' blows in which Indian state?",
    question_hi: "'काल बैसाखी' (Kaal Baisakhi) किस भारतीय राज्य में चलती है?",
    options_en: ["Maharashtra", "Gujarat", "Kerala", "West Bengal, Assam, Odisha"],
    options_hi: ["महाराष्ट्र", "गुजरात", "केरल", "पश्चिम बंगाल, असम, ओडिशा"],
    correct_option_index: 3,
    explanation_en: "Kaal Baisakhi are winds that blow in West Bengal, Assam, and Odisha during the summer season (April to May).",
    explanation_hi: "काल बैसाखी ग्रीष्म ऋतु (अप्रैल से मई) के दौरान पश्चिम बंगाल, असम और ओडिशा में चलने वाली पवनें हैं।",
  },
  {
    question_en: "'Western Disturbance' is a temperate cyclone originating from which sea?",
    question_hi: "'पश्चिमी विक्षोभ' (Western Disturbance) किस सागर से उत्पन्न होने वाला शीतोष्ण चक्रवात है?",
    options_en: ["Red Sea", "Black Sea", "Mediterranean Sea", "Arabian Sea"],
    options_hi: ["लाल सागर", "काला सागर", "भूमध्य सागर (Mediterranean Sea)", "अरब सागर"],
    correct_option_index: 2,
    explanation_en: "Western Disturbances originate from the Mediterranean Sea.",
    explanation_hi: "पश्चिमी विक्षोभ भूमध्य सागर से उत्पन्न होते हैं।",
  },
  {
    question_en: "'Retreating Monsoon' causes rainfall on the coast of which state?",
    question_hi: "'मानसून का लौटना' (Retreating Monsoon) किस राज्य के तट पर वर्षा का कारण बनता है?",
    options_en: ["Kerala", "Maharashtra", "Odisha", "Tamil Nadu (Coromandel Coast)"],
    options_hi: ["केरल", "महाराष्ट्र", "ओडिशा", "तमिलनाडु (कोरोमंडल तट)"],
    correct_option_index: 3,
    explanation_en: "The North-East Monsoon or Retreating Monsoon causes rainfall on the Coromandel coast of Tamil Nadu during winter.",
    explanation_hi: "सर्दियों में उत्तर-पूर्वी मानसून या लौटते हुए मानसून से तमिलनाडु के कोरोमंडल तट पर वर्षा होती है।",
  },
  {
    question_en: "Mawsynram, the place receiving the highest rainfall, is situated on which hill?",
    question_hi: "सर्वाधिक वर्षा प्राप्त करने वाला स्थान मासिनराम (Mawsynram) किस पहाड़ी पर स्थित है?",
    options_en: ["Garo Hill", "Jaintia Hill", "Khasi Hill", "Patkoi Hill"],
    options_hi: ["गारो पहाड़ी", "जयंतिया पहाड़ी", "खासी पहाड़ी", "पटकोई पहाड़ी"],
    correct_option_index: 2,
    explanation_en: "Mawsynram, the place with the highest rainfall, is located on the Khasi Hill in Meghalaya.",
    explanation_hi: "सर्वाधिक वर्षा वाला स्थान मासिनराम मेघालय की खासी पहाड़ी पर स्थित है।",
  },
  {
    question_en: "Manikaran, famous for Geothermal Energy, is located in which state?",
    question_hi: "भू-तापीय ऊर्जा (Geothermal Energy) के लिए प्रसिद्ध 'मणिकरण' (Manikaran) किस राज्य में स्थित है?",
    options_en: ["Ladakh", "Uttarakhand", "Himachal Pradesh", "Jharkhand"],
    options_hi: ["लद्दाख", "उत्तराखंड", "हिमाचल प्रदेश", "झारखंड"],
    correct_option_index: 2,
    explanation_en: "Manikaran is located in Himachal Pradesh.",
    explanation_hi: "मणिकरण हिमाचल प्रदेश में स्थित है।",
  },
  {
    question_en: "In which state are the Geothermal Energy sources 'Taptapani' located?",
    question_hi: "किस राज्य में भू-तापीय ऊर्जा के स्रोत 'तापतानी' (Taptapani) स्थित हैं?",
    options_en: ["Chhattisgarh", "Madhya Pradesh", "Jharkhand", "Odisha"],
    options_hi: ["छत्तीसगढ़", "मध्य प्रदेश", "झारखंड", "ओडिशा"],
    correct_option_index: 3,
    explanation_en: "Taptapani, a source of geothermal energy, is located in Odisha.",
    explanation_hi: "तापतानी भू-तापीय ऊर्जा का स्रोत ओडिशा में स्थित है।",
  },
  {
    question_en: "Which energy source is Non-Renewable Energy?",
    question_hi: "कौन सा ऊर्जा स्रोत गैर-नवीकरणीय (Non-Renewable Energy) है?",
    options_en: ["Solar Energy", "Wind Energy", "Geothermal Energy", "Petroleum"],
    options_hi: ["सौर ऊर्जा", "पवन ऊर्जा", "भू-तापीय ऊर्जा", "पेट्रोलियम (Petroleum)"],
    correct_option_index: 3,
    explanation_en: "Petroleum, coal, and natural gas are non-renewable energy sources.",
    explanation_hi: "पेट्रोलियम, कोयला और प्राकृतिक गैस अनवीकरणीय/गैर-नवीकरणीय ऊर्जा स्रोत हैं।",
  },
  {
    question_en: "HINDALCO (Renukoot, UP) in the Aluminum industry was established in collaboration with which country?",
    question_hi: "अल्युमीनियम उद्योग में HINDALCO (रेनुकूट, UP) किस देश के सहयोग से स्थापित किया गया था?",
    options_en: ["Russia", "France", "Germany", "USA (America)"],
    options_hi: ["रूस", "फ्रांस", "जर्मनी", "USA (अमेरिका)"],
    correct_option_index: 3,
    explanation_en: "HINDALCO was established in collaboration with the USA.",
    explanation_hi: "HINDALCO USA के सहयोग से स्थापित किया गया।",
  },
  {
    question_en: "NALCO (National Aluminum Company Limited), Damanjodi (Odisha) was established in collaboration with which country?",
    question_hi: "NALCO (नेशनल एल्युमीनियम कंपनी लिमिटेड), दामनजोड़ी (ओडिशा) किस देश के सहयोग से स्थापित की गई थी?",
    options_en: ["USA", "Russia", "Germany", "France"],
    options_hi: ["अमेरिका", "रूस", "जर्मनी", "फ्रांस"],
    correct_option_index: 3,
    explanation_en: "NALCO was established in collaboration with France.",
    explanation_hi: "NALCO फ्रांस के सहयोग से स्थापित की गई थी।",
  },
  {
    question_en: "Where is the factory of IISCO (Indian Iron and Steel Company) located?",
    question_hi: "II SCO (इंडियन आयरन एंड स्टील कंपनी) का कारखाना कहाँ स्थित है?",
    options_en: ["Rourkela", "Jamshedpur", "Burnpur (West Bengal)", "Bhilai"],
    options_hi: ["राउरकेला", "जमशेदपुर", "बर्नपुर (पश्चिम बंगाल)", "भिलाई"],
    correct_option_index: 2,
    explanation_en: "IISCO was established in 1918 and is located in Burnpur, West Bengal.",
    explanation_hi: "IISCO की स्थापना 1918 में हुई और यह पश्चिम बंगाल के बर्नपुर में स्थित है।",
  },
  {
    question_en: "The Durgapur (West Bengal) plant, established after independence in the Iron and Steel Industry, was set up in collaboration with which country?",
    question_hi: "लौह-इस्पात उद्योग में स्वतंत्रता के बाद स्थापित दुर्गापुर (पश्चिम बंगाल) संयंत्र को किस देश के सहयोग से स्थापित किया गया था?",
    options_en: ["Germany", "Soviet Union", "Britain", "USA"],
    options_hi: ["जर्मनी", "सोवियत संघ", "ब्रिटेन", "अमेरिका"],
    correct_option_index: 2,
    explanation_en: "The Durgapur plant was established in collaboration with Britain during the Second Five-Year Plan.",
    explanation_hi: "दुर्गापुर संयंत्र ब्रिटेन के सहयोग से द्वितीय पंचवर्षीय योजना में स्थापित हुआ था।",
  },
  {
    question_en: "Where is India's longest platform, 'Shri Siddharoodha Swamiji Hubballi Station', located?",
    question_hi: "भारत का सबसे लंबा प्लेटफॉर्म 'श्री सिद्धारूढ़ स्वामी जी हुबली स्टेशन' कहाँ स्थित है?",
    options_en: ["West Bengal", "Uttar Pradesh", "Karnataka", "Kerala"],
    options_hi: ["पश्चिम बंगाल", "उत्तर प्रदेश", "कर्नाटक", "केरल"],
    correct_option_index: 2,
    explanation_en: "This railway station is located in Karnataka.",
    explanation_hi: "यह रेलवे स्टेशन कर्नाटक में स्थित है।",
  },
  {
    question_en: "The '49th Parallel' (49° North Latitude) demarcates the border between which two countries?",
    question_hi: "'चालीसवीं समानांतर रेखा' (49° North Latitude) किन दो देशों की सीमा निर्धारित करती है?",
    options_en: ["Mexico and USA", "Russia and Finland", "China and India", "Canada and USA"],
    options_hi: ["मेक्सिको और USA", "रूस और फिनलैंड", "चीन और भारत", "कनाडा और USA"],
    correct_option_index: 3,
    explanation_en: "The 49° North Latitude line demarcates the border between Canada and the USA.",
    explanation_hi: "49° उत्तरी अक्षांश रेखा कनाडा और USA की सीमा निर्धारित करती है।",
  },
  {
    question_en: "The 'Great Dividing Range' is located on which continent?",
    question_hi: "'ग्रेट डिवाइडिंग रेंज' (Great Dividing Range) किस महाद्वीप में स्थित है?",
    options_en: ["North America", "South America", "Africa", "Australia"],
    options_hi: ["उत्तरी अमेरिका", "दक्षिण अमेरिका", "अफ्रीका", "ऑस्ट्रेलिया"],
    correct_option_index: 3,
    explanation_en: "The Great Dividing Range is located in the eastern part of Australia.",
    explanation_hi: "ग्रेट डिवाइडिंग रेंज ऑस्ट्रेलिया के पूर्वी भाग में स्थित है।",
  },
  {
    question_en: "'Pampas' grasslands are found on which continent?",
    question_hi: "'पम्पास' (Pampas) घास के मैदान किस महाद्वीप में पाए जाते हैं?",
    options_en: ["North America", "Africa", "Asia", "South America (Argentina)"],
    options_hi: ["उत्तरी अमेरिका", "अफ्रीका", "एशिया", "दक्षिण अमेरिका (अर्जेंटीना)"],
    correct_option_index: 3,
    explanation_en: "Pampas grasslands are found in Argentina (South America).",
    explanation_hi: "पंपास घास के मैदान अर्जेंटीना (दक्षिण अमेरिका) में पाए जाते हैं।",
  },
  {
    question_en: "Where are 'Downs' grasslands found?",
    question_hi: "'डाउंस' (Downs) घास के मैदान कहाँ पाए जाते हैं?",
    options_en: ["Russia", "New Zealand", "Argentina", "Australia"],
    options_hi: ["रूस", "न्यूजीलैंड", "अर्जेंटीना", "ऑस्ट्रेलिया"],
    correct_option_index: 3,
    explanation_en: "Downs grasslands are found in Australia.",
    explanation_hi: "डाउंस घास के मैदान ऑस्ट्रेलिया में पाए जाते हैं।",
  },
  {
    question_en: "Where is the 'Telegraphic Plateau' located?",
    question_hi: "'टेलीग्राफिक पठार' (Telegraphic Plateau) कहाँ स्थित है?",
    options_en: ["Indian Ocean", "Pacific Ocean", "North Atlantic Ocean", "Arctic Ocean"],
    options_hi: ["हिंद महासागर", "प्रशांत महासागर", "उत्तरी अटलांटिक महासागर", "आर्कटिक महासागर"],
    correct_option_index: 2,
    explanation_en: "The Telegraphic Plateau is located in the North Atlantic Ocean.",
    explanation_hi: "टेलीग्राफिक पठार उत्तरी अटलांटिक महासागर में स्थित है।",
  },
  {
    question_en: "The 'Dr. Shyama Prasad Mukherjee Tunnel' is located in which pass?",
    question_hi: "किस दर्रे में 'डॉ. श्यामा प्रसाद मुखर्जी सुरंग' स्थित है?",
    options_en: ["Rohtang Pass", "Zojila Pass", "Khardungla Pass", "Banihal Pass"],
    options_hi: ["रोहतांग दर्रा", "जोजिला दर्रा", "खारदुंगला दर्रा", "बनिहाल दर्रा (BanihaI Pass)"],
    correct_option_index: 3,
    explanation_en: "The Jawahar Tunnel, now also called Dr. Shyama Prasad Mukherjee Tunnel (referring to the Chenani-Nashri Tunnel, though the source links it to the Banihal Pass area), is located in the Banihal Pass area. (Note: The Dr. Shyama Prasad Mukherjee Tunnel is the Chenani-Nashri Tunnel, but the source explicitly states it's in Banihal Pass. Following the source).",
    explanation_hi: "जवाहर सुरंग, जिसे अब डॉ. श्यामा प्रसाद मुखर्जी सुरंग भी कहा जाता है, बनिहाल दर्रे में स्थित है।",
  },
];



export default test4Questions;
