import type { QuizQuestion } from '../../../types';

const test3Questions: QuizQuestion[] =[
  {
    question_en: "The 'Toda' tribe of South India is mainly found on which mountain range?",
    question_hi: "दक्षिण भारत की 'टोडा' (Toda) जनजाति मुख्य रूप से किस पर्वत श्रेणी पर पाई जाती है?",
    options_en: ["Annamalai", "Cardamom Hills", "Nilgiri Hills", "Palani Hills"],
    options_hi: ["अन्नामलाई", "कार्डामम हिल्स", "नीलगिरि हिल्स", "पलनी हिल्स"],
    correct_option_index: 2,
    explanation_en: "The Toda tribe of Tamil Nadu is found on the Nilgiri Hills and is known for buffalo rearing.",
    explanation_hi: "तमिलनाडु की टोडा जनजाति नीलगिरि पहाड़ी पर पाई जाती है, और यह भैंसें पालती है।",
  },
  {
    question_en: "Which tribe is primarily associated with sheep rearing?",
    question_hi: "किस जनजाति का संबंध मुख्य रूप से भेड़ पालने से है?",
    options_en: ["Bhil", "Santhal", "Gaddi", "Munda"],
    options_hi: ["भील", "संथाल", "गद्दी (Gaddi)", "मुंडा"],
    correct_option_index: 2,
    explanation_en: "The Gaddi tribe rears sheep in the Dhauladhar mountain range (Himachal Pradesh).",
    explanation_hi: "गद्दी जनजाति धौलाधार पर्वत श्रेणी (हिमाचल प्रदेश) में भेड़ पालती है।",
  },
  {
    question_en: "The 'Garo', 'Khasi', and 'Jaintia' hills and tribes are located in which state?",
    question_hi: "'गारो', 'खासी' और 'जयंतिया' पहाड़ियाँ और जनजातियाँ किस राज्य में स्थित हैं?",
    options_en: ["Nagaland", "Manipur", "Meghalaya", "Tripura"],
    options_hi: ["नागालैंड", "मणिपुर", "मेघालय", "त्रिपुरा"],
    correct_option_index: 2,
    explanation_en: "Garo, Khasi, and Jaintia are the major tribes of Meghalaya.",
    explanation_hi: "गारो, खासी और जयंतिया मेघालय की प्रमुख जनजातियाँ हैं।",
  },
  {
    question_en: "The 'Shompen', 'Onge', and 'Jarawa' tribes are found in which location?",
    question_hi: "'शोंपेन' (Shompen), 'ओंगे' (Onge) और 'जारवा' (Jarawa) जनजातियाँ कहाँ पाई जाती हैं?",
    options_en: ["Lakshadweep Islands", "Dadra and Nagar Haveli", "Andaman and Nicobar Islands", "Puducherry"],
    options_hi: ["लक्षद्वीप समूह", "दादरा और नगर हवेली", "अंडमान और निकोबार", "पुडुचेरी"],
    correct_option_index: 2,
    explanation_en: "Sentinelese, Onge, Jarawa, and Shompen are tribes of the Andaman and Nicobar Islands.",
    explanation_hi: "सेंटिनलीज़, ओंगे, जारवा, और शोंपेन अंडमान और निकोबार द्वीप समूह की जनजातियाँ हैं।",
  },
  {
    question_en: "The major tribes of Jharkhand, 'Santhal' and 'Munda', belong to which race?",
    question_hi: "झारखंड की प्रमुख जनजातियाँ 'संथाल' और 'मुंडा' का संबंध किस प्रजाति से है?",
    options_en: ["Mongoloid", "Negrito", "Proto-Australoid", "Nordic"],
    options_hi: ["मंगोलायड", "निग्रिटो", "प्रोटो-ऑस्ट्रोलायड", "नॉर्डिक"],
    correct_option_index: 2,
    explanation_en: "The Santhal tribe of India belongs to the Proto-Australoid race.",
    explanation_hi: "भारत की संथाल जनजाति का संबंध प्रोटो-ऑस्ट्रोलायड प्रजाति से है।",
  },
  {
    question_en: "The 'Lepcha' and 'Bhutia' tribes mainly reside in which state?",
    question_hi: "'लेपचा' और 'भूटिया' जनजातियाँ मुख्य रूप से किस राज्य में निवास करती हैं?",
    options_en: ["Arunachal Pradesh", "Himachal Pradesh", "Sikkim", "Mizoram"],
    options_hi: ["अरुणाचल प्रदेश", "हिमाचल प्रदेश", "सिक्किम", "मिजोरम"],
    correct_option_index: 2,
    explanation_en: "Lepcha and Bhutia are the main tribes of Sikkim.",
    explanation_hi: "सिक्किम की मुख्य जनजातियाँ लेपचा और भूटिया हैं।",
  },
  {
    question_en: "Which tribe of Kerala was associated with the Moplah Revolt?",
    question_hi: "केरल की कौन सी जनजाति मोपला विद्रोह (Moplah Revolt) से संबंधित थी?",
    options_en: ["Toda", "Ullada", "Nair", "Moplah"],
    options_hi: ["टोडा", "उल्लाडा", "नायर", "मोपला (Moplah)"],
    correct_option_index: 3,
    explanation_en: "The Moplah tribe is a major tribe of Kerala, and the Moplah Revolt (1921) was a peasant uprising by them.",
    explanation_hi: "मोपला जनजाति केरल की एक प्रमुख जनजाति है।",
  },
  {
    question_en: "The 'Dafala', 'Mishmi', and 'Aka' tribes are found in which state?",
    question_hi: "'डफला', 'मिश्मी' और 'अका' जनजातियाँ किस राज्य में पाई जाती हैं?",
    options_en: ["Nagaland", "Manipur", "Meghalaya", "Arunachal Pradesh"],
    options_hi: ["नागालैंड", "मणिपुर", "मेघालय", "अरुणाचल प्रदेश"],
    correct_option_index: 3,
    explanation_en: "Apatani, Dafala, Mishmi, Abor are tribes of Arunachal Pradesh.",
    explanation_hi: "अपातानी, डफला, मिश्मी, अबोर अरुणाचल प्रदेश की जनजातियाँ हैं।",
  },
  {
    question_en: "The 'Pomlu' and 'Kuki' tribes are found in which state?",
    question_hi: "'पोम्लू' और 'कुकी' (Kuki) जनजातियाँ किस राज्य में पाई जाती हैं?",
    options_en: ["Assam", "Tripura", "Manipur", "Mizoram"],
    options_hi: ["असम", "त्रिपुरा", "मणिपुर", "मिजोरम"],
    correct_option_index: 2,
    explanation_en: "Kuki, Mao, Maring tribes reside in Manipur. Pomlu is also the name of a shifting cultivation practice here.",
    explanation_hi: "कुकी, माओ, मारिंग जनजातियाँ मणिपुर में निवास करती हैं। पोम्लू यहां की स्थान्तरित कृषि का नाम भी है।",
  },
  {
    question_en: "Which tribe is considered to be associated with the Dhauladhar mountain range of Himachal Pradesh?",
    question_hi: "किस जनजाति को हिमाचल प्रदेश की धौलाधार पर्वत श्रेणी से संबंधित माना जाता है?",
    options_en: ["Kinnaur", "Gaddi", "Pangwali", "Gujjar"],
    options_hi: ["किन्नौर", "गद्दी", "पंगवाली", "गुर्जर"],
    correct_option_index: 1,
    explanation_en: "The Gaddi tribe is associated with the Dhauladhar mountain range (Himachal Pradesh).",
    explanation_hi: "गद्दी जनजाति धौलाधार पर्वत श्रेणी (हिमाचल प्रदेश) से संबंधित है।",
  },
  {
    question_en: "In which state is shifting cultivation called 'Podu' or 'Pond'?",
    question_hi: "किस राज्य में स्थान्तरित कृषि (Shifting cultivation) को 'पोडु' या 'पोंडू' कहा जाता है?",
    options_en: ["Jharkhand", "Western Ghats", "Andhra Pradesh", "Odisha"],
    options_hi: ["झारखंड", "पश्चिमी घाट", "आंध्र प्रदेश", "ओडिशा"],
    correct_option_index: 2,
    explanation_en: "Shifting cultivation is called Podu or Pondu in Andhra Pradesh.",
    explanation_hi: "स्थान्तरित कृषि को आंध्र प्रदेश में पोडु या पोंडू कहा जाता है।",
  },
  {
    question_en: "In which state is shifting cultivation called 'Kuruwal'?",
    question_hi: "किस राज्य में स्थान्तरित कृषि को 'कुरुवाल' (Kuruwal) कहा जाता है?",
    options_en: ["Assam", "Meghalaya", "Jharkhand", "Madhya Pradesh"],
    options_hi: ["असम", "मेघालय", "झारखंड", "मध्य प्रदेश"],
    correct_option_index: 2,
    explanation_en: "In Jharkhand, shifting cultivation is called Kuruwal.",
    explanation_hi: "झारखंड में स्थान्तरित कृषि को कुरुवाल कहा जाता है।",
  },
  {
    question_en: "Where is shifting cultivation known by the name 'Bewer' or 'Dahiya'?",
    question_hi: "स्थान्तरित कृषि को 'बेवर' (Bewer) या 'दहिया' (Dahiya) नाम से कहाँ जाना जाता है?",
    options_en: ["Himalayan region", "Madhya Pradesh", "Odisha", "Gujarat"],
    options_hi: ["हिमालय क्षेत्र", "मध्य प्रदेश", "ओडिशा", "गुजरात"],
    correct_option_index: 1,
    explanation_en: "In Madhya Pradesh, it is called Bewer or Dahiya.",
    explanation_hi: "मध्य प्रदेश में इसे बेवर या दहिया कहा जाता है।",
  },
  {
    question_en: "What is the largest source of irrigation in India after wells and tube wells?",
    question_hi: "भारत में कुओं और नलकूपों के बाद सिंचाई का सबसे बड़ा साधन क्या है?",
    options_en: ["Ponds", "Sprinklers", "Canals", "Rain water"],
    options_hi: ["तालाब", "स्प्रिंकलर", "नहर (Canals)", "वर्षा जल"],
    correct_option_index: 2,
    explanation_en: "After wells and tube wells, canals are the largest source of irrigation in India.",
    explanation_hi: "कुओं और नलकूपों के बाद भारत में सिंचाई का सबसे बड़ा साधन नहरें हैं।",
  },
  {
    question_en: "What is the capital of Vietnam?",
    question_hi: "वियतनाम की राजधानी क्या है?",
    options_en: ["Jakarta", "Manila", "Hanoi", "Seoul"],
    options_hi: ["जकार्ता", "मनीला", "हनोई (Hanoi)", "सिओल"],
    correct_option_index: 2,
    explanation_en: "The capital of Vietnam is Hanoi.",
    explanation_hi: "वियतनाम की राजधानी हनोई है।",
  },
  {
    question_en: "What is the capital of Turkey?",
    question_hi: "तुर्की की राजधानी क्या है?",
    options_en: ["Istanbul", "Ankara", "Tehran", "Riyadh"],
    options_hi: ["इस्तांबुल", "अंकारा", "तेहरान", "रियाद"],
    correct_option_index: 1,
    explanation_en: "The capital of Turkey is Ankara.",
    explanation_hi: "तुर्की की राजधानी अंकारा है।",
  },
  {
    question_en: "Which country's capital is 'Kuala Lumpur'?",
    question_hi: "किस देश की राजधानी 'कुआलालंपुर' है?",
    options_en: ["Thailand", "Indonesia", "Philippines", "Malaysia"],
    options_hi: ["थाईलैंड", "इंडोनेशिया", "फिलीपींस", "मलेशिया"],
    correct_option_index: 3,
    explanation_en: "The capital of Malaysia is Kuala Lumpur.",
    explanation_hi: "मलेशिया की राजधानी कुआलालंपुर है।",
  },
  {
    question_en: "Which nuclear power plant established in Tamil Nadu is in collaboration with Russia?",
    question_hi: "रूस के सहयोग से तमिलनाडु में स्थापित नाभिकीय ऊर्जा संयंत्र (Nuclear Power Plant) कौन सा है?",
    options_en: ["Tarapur", "Kalpakkam", "Kaiga", "Kudankulam"],
    options_hi: ["तारापुर", "कलपक्कम", "कैगा", "कुडनकुलम (Kudankulam)"],
    correct_option_index: 3,
    explanation_en: "The Kudankulam (Tamil Nadu) nuclear plant was established with the assistance of Russia.",
    explanation_hi: "कुडनकुलम (तमिलनाडु) नाभिकीय संयंत्र रूस की सहायता से स्थापित किया गया था।",
  },
  {
    question_en: "Where is the 'Taurus Mountain' located in the continent of Asia?",
    question_hi: "एशिया महाद्वीप में स्थित 'तोरस पर्वत' (Taurus Mt.) कहाँ स्थित है?",
    options_en: ["Iran", "Saudi Arabia", "Pakistan", "Turkey"],
    options_hi: ["ईरान", "सऊदी अरब", "पाकिस्तान", "तुर्की (Turkey)"],
    correct_option_index: 3,
    explanation_en: "The Taurus Mountain is located in Turkey.",
    explanation_hi: "तोरस पर्वत तुर्की में स्थित है।",
  },
  {
    question_en: "Which is the longest river in the continent of Asia?",
    question_hi: "एशिया महाद्वीप की सबसे लंबी नदी कौन सी है?",
    options_en: ["Helmand River", "Brahmaputra River", "Nile River", "Yangtse River"],
    options_hi: ["हेलमंद नदी", "ब्रह्मपुत्र नदी", "नील नदी", "यांग्त्सीक्यांग नदी (Yangtse River)"],
    correct_option_index: 3,
    explanation_en: "The Yangtse River in China is the longest river in Asia.",
    explanation_hi: "चीन की यांग्त्सीक्यांग नदी एशिया की सबसे लंबी नदी है।",
  },
  {
    question_en: "The 'Dasht-e-lut' located in Iran is what kind of geomorphological region?",
    question_hi: "ईरान (Iran) में स्थित 'दस्त-ए-लुत' (Dasht-e-lut) किस प्रकार का भू-आकृतिक क्षेत्र है?",
    options_en: ["Mountain range", "River valley", "Desert", "Plateau"],
    options_hi: ["पर्वत श्रृंखला", "नदी घाटी", "मरुस्थल (Desert)", "पठार"],
    correct_option_index: 2,
    explanation_en: "Dasht-e-lut is a desert in Iran.",
    explanation_hi: "दश्त-ए-लुत ईरान का एक मरुस्थल है।",
  },
  {
    question_en: "The Caspian Sea is the world's largest saltwater lake. How many countries surround it?",
    question_hi: "कैस्पियन सागर (Caspian Sea) विश्व की सबसे बड़ी खारे पानी की झील है, यह कितने देशों से घिरा है?",
    options_en: ["4", "5", "6", "7"],
    options_hi: ["4", "5", "6", "7"],
    correct_option_index: 1,
    explanation_en: "The Caspian Sea is surrounded by 5 countries (Kazakhstan, Iran, Russia, Azerbaijan, Turkmenistan).",
    explanation_hi: "कैस्पियन सागर 5 देशों (कजाकिस्तान, ईरान, रूस, अजरबैजान, तुर्कमेनिस्तान) से घिरा है।",
  },
  {
    question_en: "The highest plateau of Asia, the 'Tibet Plateau', is known as what?",
    question_hi: "एशिया का सबसे ऊँचा पठार, 'तिब्बत का पठार', किस रूप में जाना जाता है?",
    options_en: ["Storehouse of Asia", "Delta region", "Roof of the World", "Desert of the World"],
    options_hi: ["एशिया का भंडार", "डेल्टा क्षेत्र", "विश्व की छत (Roof of the World)", "विश्व का रेगिस्तान"],
    correct_option_index: 2,
    explanation_en: "The Tibet Plateau is also called the 'Roof of the World'.",
    explanation_hi: "तिब्बत के पठार को 'विश्व की छत' भी कहा जाता है।",
  },
  {
    question_en: "Where is Lake Baikal, the world's deepest lake, located?",
    question_hi: "विश्व की सबसे गहरी झील (Deepest Lake) बैकाल झील कहाँ स्थित है?",
    options_en: ["Kazakhstan", "China", "Russia", "Turkey"],
    options_hi: ["कजाकिस्तान", "चीन", "रूस (Russia)", "तुर्की"],
    correct_option_index: 2,
    explanation_en: "Lake Baikal is located in Russia.",
    explanation_hi: "बैकाल झील रूस में स्थित है।",
  },
  {
    question_en: "The Euphrates River is the longest river in which region?",
    question_hi: "यूफ्रेट्स नदी (Euphrates River) किस क्षेत्र की सबसे लंबी नदी है?",
    options_en: ["South Asia", "East Asia", "West Asia", "North Asia"],
    options_hi: ["दक्षिणी एशिया", "पूर्वी एशिया", "पश्चिमी एशिया", "उत्तरी एशिया"],
    correct_option_index: 2,
    explanation_en: "The Euphrates River is the longest river in West Asia.",
    explanation_hi: "यूफ्रेट्स नदी पश्चिमी एशिया की सबसे लंबी नदी है।",
  },
  {
    question_en: "Which of the 4 countries included in the Horn of Africa is NOT included?",
    question_hi: "हॉर्न ऑफ अफ्रीका (Horn of Africa) में शामिल 4 देशों में से कौन सा देश शामिल नहीं है?",
    options_en: ["Somalia", "Ethiopia", "Eritrea", "Tanzania"],
    options_hi: ["सोमालिया", "इथियोपिया", "एरिट्रिया", "तंज़ानिया"],
    correct_option_index: 3,
    explanation_en: "The Horn of Africa includes Somalia, Ethiopia, Eritrea, and Djibouti.",
    explanation_hi: "हॉर्न ऑफ अफ्रीका में सोमालिया, इथियोपिया, एरिट्रिया और जिबूती शामिल हैं।",
  },
  {
    question_en: "Which is the second largest continent by size?",
    question_hi: "अफ्रीका महाद्वीप का दूसरा सबसे बड़ा महाद्वीप (Second largest continent) कौन सा है?",
    options_en: ["Asia", "North America", "Africa", "South America"],
    options_hi: ["एशिया", "उत्तरी अमेरिका", "अफ्रीका", "दक्षिण अमेरिका"],
    correct_option_index: 2,
    explanation_en: "Africa is the second largest continent after Asia.",
    explanation_hi: "अफ्रीका दूसरा सबसे बड़ा महाद्वीप है।",
  },
  {
    question_en: "Which continent is crossed by the Tropic of Cancer, Tropic of Capricorn, and the Equator?",
    question_hi: "किस महाद्वीप से कर्क रेखा, मकर रेखा और विषुवत रेखा तीनों रेखाएं गुजरती हैं?",
    options_en: ["Asia", "North America", "Africa", "South America"],
    options_hi: ["एशिया", "उत्तरी अमेरिका", "अफ्रीका", "दक्षिण अमेरिका"],
    correct_option_index: 2,
    explanation_en: "All three major latitude lines pass through the continent of Africa.",
    explanation_hi: "अफ्रीका महाद्वीप से तीनों प्रमुख अक्षांश रेखाएं गुजरती हैं।",
  },
  {
    question_en: "Which is the largest lake in the continent of Africa?",
    question_hi: "अफ्रीका महाद्वीप की सबसे बड़ी झील (Largest Lake) कौन सी है?",
    options_en: ["Lake Tanganyika", "Lake Chad", "Lake Volta", "Lake Victoria"],
    options_hi: ["टांगान्यिका झील", "चाड झील", "वोल्टा झील", "विक्टोरिया झील (Lake Victoria)"],
    correct_option_index: 3,
    explanation_en: "Lake Victoria is the largest lake in Africa, through which the Equator passes.",
    explanation_hi: "विक्टोरिया झील अफ्रीका की सबसे बड़ी झील है, जिससे विषुवत रेखा गुजरती है।",
  },
  {
    question_en: "Which lake in Africa is crossed by the Tropic of Cancer?",
    question_hi: "कौन सी झील अफ्रीका में स्थित है जिससे कर्क रेखा (Tropic of Cancer) गुजरती है?",
    options_en: ["Lake Victoria", "Lake Tanganyika", "Nasser Lake", "Karachi Lake"],
    options_hi: ["विक्टोरिया झील", "टांगान्यिका झील", "नासेर झील (Nasser Lake)", "कराची झील"],
    correct_option_index: 2,
    explanation_en: "Lake Nasser is an artificial lake crossed by the Tropic of Cancer.",
    explanation_hi: "नासेर झील एक कृत्रिम झील है, जिससे कर्क रेखा गुजरती है।",
  },
  {
    question_en: "The Nile River is formed by the confluence of which two rivers?",
    question_hi: "नील नदी (Nile River) किन दो नदियों के मिलने से बनती है?",
    options_en: ["Niger and Blue Nile", "Volta and White Nile", "White Nile and Blue Nile", "Limpopo and Zambezi"],
    options_hi: ["नाइजर और ब्लू नील", "वोल्टा और व्हाइट नील", "व्हाइट नील और ब्लू नील", "लिम्पोपो और जाम्बेजी"],
    correct_option_index: 2,
    explanation_en: "The Nile River is formed by the confluence of the White Nile (from Lake Victoria) and the Blue Nile (from Lake Tana).",
    explanation_hi: "नील नदी व्हाइट नील (विक्टोरिया झील) और ब्लू नील (ताना झील) नदियों के मिलने से बनती है।",
  },
  {
    question_en: "What is the characteristic of the Congo (Zaire) River?",
    question_hi: "कांगो (जायरे) नदी की विशेषता क्या है?",
    options_en: ["It crosses the Tropic of Capricorn twice.", "It crosses the Equator once.", "It crosses the Equator twice.", "It is the longest river in the world."],
    options_hi: ["यह मकर रेखा को दो बार काटती है।", "यह विषुवत रेखा को एक बार काटती है।", "यह विषुवत रेखा को दो बार काटती है।", "यह विश्व की सबसे लंबी नदी है।"],
    correct_option_index: 2,
    explanation_en: "The Congo River crosses the Equator twice and flows into the Atlantic Ocean.",
    explanation_hi: "कांगो नदी (Congo River) विषुवत रेखा को दो बार काटती है और अटलांटिक महासागर में गिरती है।",
  },
  {
    question_en: "Which river crosses the Tropic of Capricorn twice?",
    question_hi: "कौन सी नदी मकर रेखा (Tropic of Capricorn) को दो बार काटती है?",
    options_en: ["Nile River", "Congo River", "Niger River", "Limpopo River"],
    options_hi: ["नील नदी", "कांगो नदी", "नाइजर नदी", "लिम्पोपो नदी (Limpopo River)"],
    correct_option_index: 3,
    explanation_en: "The Limpopo River crosses the Tropic of Capricorn twice.",
    explanation_hi: "लिम्पोपो नदी मकर रेखा को दो बार काटती है।",
  },
  {
    question_en: "On which river is the Aswan Dam located?",
    question_hi: "अस्वान बाँध (Aswan Dam) किस नदी पर स्थित है?",
    options_en: ["Zambezi River", "Niger River", "Nile River", "Congo River"],
    options_hi: ["जाम्बेजी नदी", "नाइजर नदी", "नील नदी", "कांगो नदी"],
    correct_option_index: 2,
    explanation_en: "The Aswan Dam is located on the Nile River in Egypt.",
    explanation_hi: "अस्वान बाँध नील नदी पर मिस्र (Egypt) में स्थित है।",
  },
  {
    question_en: "What is the rank of the North American continent by size?",
    question_hi: "उत्तरी अमेरिका महाद्वीप का आकार के अनुसार कौन सा स्थान है?",
    options_en: ["Second", "Fourth", "Third", "Fifth"],
    options_hi: ["दूसरा", "चौथा", "तीसरा", "पाँचवाँ"],
    correct_option_index: 2,
    explanation_en: "North America is the third largest continent by area.",
    explanation_hi: "उत्तरी अमेरिका क्षेत्रफल के अनुसार तीसरा सबसे बड़ा महाद्वीप है।",
  },
  {
    question_en: "Which longitude line approximately divides North America into two parts?",
    question_hi: "उत्तरी अमेरिका को लगभग दो भागों में बाँटने वाली देशांतर रेखा (Longitude line) कौन सी है?",
    options_en: ["0° Longitude", "90° East Longitude", "100° West Longitude", "180° East Longitude"],
    options_hi: ["0° देशांतर", "90° पूर्वी देशांतर", "100° पश्चिमी देशांतर", "180° पूर्वी देशांतर"],
    correct_option_index: 2,
    explanation_en: "The 100° West Longitude line approximately divides North America into two parts.",
    explanation_hi: "100° पश्चिमी देशांतर रेखा उत्तरी अमेरिका को लगभग दो भागों में बाँटती है।",
  },
  {
    question_en: "The Mexico Plateau is located in which continent?",
    question_hi: "मेक्सिको का पठार (Mexico Plateau) किस महाद्वीप में स्थित है?",
    options_en: ["South America", "Asia", "North America", "Africa"],
    options_hi: ["दक्षिण अमेरिका", "एशिया", "उत्तरी अमेरिका", "अफ्रीका"],
    correct_option_index: 2,
    explanation_en: "The Mexico Plateau is located in North America.",
    explanation_hi: "मेक्सिको का पठार उत्तरी अमेरिका में स्थित है।",
  },
  {
    question_en: "Where is the Mojave Desert located?",
    question_hi: "मोहवे या मोजेव मरुस्थल (Mojave Desert) कहाँ स्थित है?",
    options_en: ["Mexico", "Arizona", "Canada", "California, USA"],
    options_hi: ["मेक्सिको", "एरिजोना", "कनाडा", "USA के कैलिफ़ोर्निया में"],
    correct_option_index: 3,
    explanation_en: "The Mojave Desert is located in California, USA.",
    explanation_hi: "मोहवे/मोजेव मरुस्थल USA के कैलिफ़ोर्निया में स्थित है।",
  },
  {
    question_en: "The Colorado River originates from which mountain?",
    question_hi: "कोलोराडो नदी (Colorado River) का उद्गम किस पर्वत से होता है?",
    options_en: ["Sierra Madre", "Daniel Mountain", "Appalachian Mountains", "Rocky Mountains"],
    options_hi: ["सिएरा माद्रे", "डेनियल माउंटेन", "अप्लेशियन पर्वत", "रॉकी पर्वत"],
    correct_option_index: 3,
    explanation_en: "The Colorado River originates from the Rocky Mountains.",
    explanation_hi: "कोलोराडो नदी का उद्गम रॉकी पर्वत से होता है।",
  },
  {
    question_en: "Washington DC (USA) is situated on the bank of which river?",
    question_hi: "वाशिंगटन DC (USA) किस नदी के तट पर स्थित है?",
    options_en: ["Hudson River", "Mississippi River", "Rio Grande River", "Potomac River"],
    options_hi: ["हडसन नदी", "मिसिसिपी नदी", "रियो ग्रांडे नदी", "पोटोमैक नदी (Potomac River)"],
    correct_option_index: 3,
    explanation_en: "Washington DC is situated on the bank of the Potomac River.",
    explanation_hi: "वाशिंगटन DC पोटोमैक नदी के तट पर स्थित है।",
  },
  {
    question_en: "The Missouri River, a tributary of the Mississippi, meets the Mississippi River near which city?",
    question_hi: "मिसौरी नदी, जो मिसिसिपी की सहायक है, मिसिसिपी नदी से किस शहर के पास मिलती है?",
    options_en: ["New York", "Chicago", "St. Louis", "New Orleans"],
    options_hi: ["न्यूयॉर्क", "शिकागो", "सेंट लुइस (St. Louis)", "न्यू ऑरलियन्स"],
    correct_option_index: 2,
    explanation_en: "The Missouri River meets the Mississippi River near St. Louis.",
    explanation_hi: "मिसौरी नदी सेंट लुइस के पास मिसिसिपी नदी से मिलती है।",
  },
  {
    question_en: "Which of the Great Lakes is entirely located within the USA?",
    question_hi: "महान झीलों (Great Lakes) में से कौन सी झील पूरी तरह से USA में स्थित है?",
    options_en: ["Lake Superior", "Lake Huron", "Lake Erie", "Lake Michigan"],
    options_hi: ["सुपीरियर झील", "ह्यूरन झील", "ईरी झील", "मिशिगन झील (Lake Michigan)"],
    correct_option_index: 3,
    explanation_en: "Out of the 5 Great Lakes, only Lake Michigan is entirely located within the USA.",
    explanation_hi: "5 महान झीलों में से केवल मिशिगन झील पूरी तरह से USA में स्थित है।",
  },
  {
    question_en: "Which is the largest freshwater lake in the world?",
    question_hi: "विश्व की सबसे बड़ी मीठे पानी की झील (Largest fresh water lake in the world) कौन सी है?",
    options_en: ["Lake Victoria", "Lake Huron", "Lake Superior", "Lake Baikal"],
    options_hi: ["विक्टोरिया झील", "ह्यूरन झील", "सुपीरियर झील (Lake Superior)", "बैकाल झील"],
    correct_option_index: 2,
    explanation_en: "Lake Superior is the largest freshwater lake in the world.",
    explanation_hi: "सुपीरियर झील विश्व में मीठे पानी की सबसे बड़ी झील है।",
  },
  {
    question_en: "Where is North America's highest peak, Mount McKinley (Mount Denali), located?",
    question_hi: "उत्तरी अमेरिका का उच्चतम शिखर माउंट मैकिन्ले (माउंट डेनाली) कहाँ स्थित है?",
    options_en: ["Canada", "Alaska (USA)", "Mexico", "California"],
    options_hi: ["कनाडा", "अलास्का (USA)", "मेक्सिको", "कैलिफ़ोर्निया"],
    correct_option_index: 1,
    explanation_en: "Mount McKinley (Mount Denali) is located in Alaska (USA).",
    explanation_hi: "माउंट मैकिन्ले (माउंट डेनाली) अलास्का (USA) में स्थित है।",
  },
  {
    question_en: "Which is the smallest country in the continent of South America?",
    question_hi: "दक्षिण अमेरिका महाद्वीप का सबसे छोटा देश कौन सा है?",
    options_en: ["Brazil", "Chile", "Uruguay", "Suriname"],
    options_hi: ["ब्राजील", "चिली", "उरुग्वे", "सूरीनाम (Suriname)"],
    correct_option_index: 3,
    explanation_en: "Suriname is the smallest country in the continent of South America.",
    explanation_hi: "दक्षिण अमेरिका महाद्वीप का सबसे छोटा देश सूरीनाम है।",
  },
  {
    question_en: "The Panama Canal separates which two continents?",
    question_hi: "पनामा नहर (Panama Canal) किन दो महाद्वीपों को अलग करती है?",
    options_en: ["Asia and Africa", "North America and Asia", "North America and South America", "Europe and Asia"],
    options_hi: ["एशिया और अफ्रीका", "उत्तरी अमेरिका और एशिया", "उत्तरी अमेरिका और दक्षिण अमेरिका", "यूरोप और एशिया"],
    correct_option_index: 2,
    explanation_en: "The Panama Canal separates the continents of North America and South America.",
    explanation_hi: "पनामा नहर उत्तरी अमेरिका और दक्षिण अमेरिका महाद्वीपों को अलग करती है।",
  },
  {
    question_en: "The Atacama Desert is located on which latitude line?",
    question_hi: "अटाकामा मरुस्थल (Atacama Desert) किस अक्षांश रेखा पर स्थित है?",
    options_en: ["Equator", "Tropic of Cancer", "Tropic of Capricorn", "Arctic Circle"],
    options_hi: ["विषुवत रेखा", "कर्क रेखा", "मकर रेखा (Tropic of Capricorn)", "आर्कटिक वृत्त"],
    correct_option_index: 2,
    explanation_en: "The Atacama Desert is located on the Tropic of Capricorn.",
    explanation_hi: "अटाकामा मरुस्थल मकर रेखा पर स्थित है।",
  },
  {
    question_en: "What is the specialty of the Atacama Desert?",
    question_hi: "अटाकामा मरुस्थल की विशेषता क्या है?",
    options_en: ["It is the coldest desert in the world.", "It has reserves of Nitrogen.", "It is the driest place in the world.", "It is located on the eastern coast of the Pacific Ocean."],
    options_hi: ["यह विश्व का सबसे ठंडा मरुस्थल है।", "इसमें नाइट्रोजन के भंडार हैं।", "यह विश्व का सबसे शुष्कतम (driest) स्थान है।", "यह प्रशांत महासागर के पूर्वी तट पर स्थित है।"],
    correct_option_index: 2,
    explanation_en: "The Atacama Desert, located in northern Chile, is the driest desert in the world.",
    explanation_hi: "उत्तरी चिली में स्थित अटाकामा मरुस्थल विश्व का सबसे शुष्कतम मरुस्थल है।",
  },
  {
    question_en: "Where is Aconcagua, the highest peak of the Andes Mountains range, located?",
    question_hi: "एंडीज पर्वत शृंखला (Andes Mountains) की सबसे ऊँची चोटी अकांकागुआ (Aconcagua) कहाँ स्थित है?",
    options_en: ["Peru", "Chile", "Argentina", "Colombia"],
    options_hi: ["पेरू", "चिली", "अर्जेंटीना (Argentina)", "कोलंबिया"],
    correct_option_index: 2,
    explanation_en: "Aconcagua (6992 m) is located in Argentina.",
    explanation_hi: "अकांकागुआ (6992 मी.) अर्जेंटीना में स्थित है।",
  },
  {
    question_en: "Which is the highest navigable lake in the world?",
    question_hi: "विश्व की सबसे ऊँची नौगम्य झील (Highest navigable lake in the world) कौन सी है?",
    options_en: ["Lake Maracaibo", "Lake Poopó", "Lake Nicaragua", "Lake Titicaca"],
    options_hi: ["मराकाइबो झील", "पोपो झील", "निकारागुआ झील", "टिटिकाका झील (Lake Titicaca)"],
    correct_option_index: 3,
    explanation_en: "Lake Titicaca (between Bolivia and Peru) is the highest navigable lake in the world.",
    explanation_hi: "टिटिकाका झील (बोलीविया और पेरू के बीच) विश्व की सबसे ऊँची नौगम्य झील है।",
  },
  {
    question_en: "Which is the largest river in the world by discharge capacity (volume)?",
    question_hi: "अपवाह क्षमता की दृष्टि से विश्व की सबसे बड़ी नदी (Largest river by volume) कौन सी है?",
    options_en: ["Nile River", "Mississippi River", "Amazon River", "Yangtse River"],
    options_hi: ["नील नदी", "मिसिसिपी नदी", "अमेज़न नदी (Amazon River)", "यांग्त्सीक्यांग नदी"],
    correct_option_index: 2,
    explanation_en: "The Amazon River is the largest river in the world by discharge capacity.",
    explanation_hi: "अमेज़न नदी अपवाह क्षमता की दृष्टि से विश्व की सबसे बड़ी नदी है।",
  },
  {
    question_en: "Which continent is also called the 'Country of thousands lakes'?",
    question_hi: "किस महाद्वीप को 'हजारों झीलों का देश' (Country of thousands lakes) भी कहा जाता है?",
    options_en: ["North America", "Asia", "Europe", "Australia"],
    options_hi: ["उत्तरी अमेरिका", "एशिया", "यूरोप", "ऑस्ट्रेलिया"],
    correct_option_index: 2,
    explanation_en: "Finland (which is in Europe) is called the 'Land of a Thousand Lakes'.",
    explanation_hi: "फिनलैंड (जो यूरोप में है) को हजारों झीलों का देश कहा जाता है।",
  },
  {
    question_en: "Which is the longest river in the continent of Europe?",
    question_hi: "यूरोप महाद्वीप की सबसे लंबी नदी कौन सी है?",
    options_en: ["Danube River", "Rhine River", "Ural River", "Volga River"],
    options_hi: ["डेन्यूब नदी", "राइन नदी", "यूराल नदी", "वोल्गा नदी (Volga River)"],
    correct_option_index: 3,
    explanation_en: "The Volga River is the longest river in Europe.",
    explanation_hi: "वोल्गा नदी यूरोप की सबसे लंबी नदी है।",
  },
  {
    question_en: "How many countries does the Danube River pass through?",
    question_hi: "डेन्यूब नदी (Danube River) कितने देशों से होकर गुजरती है?",
    options_en: ["5", "7", "10", "12"],
    options_hi: ["5", "7", "10", "12"],
    correct_option_index: 2,
    explanation_en: "The Danube River passes through 10 countries.",
    explanation_hi: "डेन्यूब नदी 10 देशों से होकर गुजरती है।",
  },
  {
    question_en: "The Rhine and Volga rivers drain their water into which sea/lake?",
    question_hi: "राइन और वोल्गा नदियाँ अपना जल किस सागर/झील में गिराती हैं?",
    options_en: ["Black Sea", "Mediterranean Sea", "Baltic Sea", "Caspian Sea"],
    options_hi: ["काला सागर", "भूमध्य सागर", "बाल्टिक सागर", "कैस्पियन सागर"],
    correct_option_index: 3,
    explanation_en: "The Volga and Ural rivers drain their water into the Caspian Sea. The Rhine flows into the North Sea, but the question lists Caspian as the common option for Volga.",
    explanation_hi: "वोल्गा और यूराल नदियाँ अपना जल कैस्पियन सागर में गिराती हैं।",
  },
  {
    question_en: "Which is the smallest continent in the world by area?",
    question_hi: "क्षेत्रफल के अनुसार विश्व का सबसे छोटा महाद्वीप कौन सा है?",
    options_en: ["Europe", "Antarctica", "Australia", "South America"],
    options_hi: ["यूरोप", "अंटार्कटिका", "ऑस्ट्रेलिया", "दक्षिण अमेरिका"],
    correct_option_index: 2,
    explanation_en: "Australia is the smallest continent in the world by area.",
    explanation_hi: "ऑस्ट्रेलिया क्षेत्रफल में विश्व का सबसे छोटा महाद्वीप है।",
  },
  {
    question_en: "Which mountain range is located in the eastern part of Australia?",
    question_hi: "ऑस्ट्रेलिया के पूर्वी भाग में स्थित पर्वत श्रृंखला कौन सी है?",
    options_en: ["Andes Mountains", "Rocky Mountains", "Drakensberg Mountains", "Great Dividing Range"],
    options_hi: ["एंडीज पर्वत", "रॉकी पर्वत", "ड्रैकन्सबर्ग पर्वत", "ग्रेट डिवाइडिंग रेंज (Great Dividing Range)"],
    correct_option_index: 3,
    explanation_en: "The Great Dividing Range is located in the eastern part of Australia.",
    explanation_hi: "ग्रेट डिवाइडिंग रेंज ऑस्ट्रेलिया के पूर्वी भाग में स्थित है।",
  },
  {
    question_en: "Where does the 'Tropic of Capricorn' pass through in Australia?",
    question_hi: "ऑस्ट्रेलिया में 'मकर रेखा' (Tropic of Capricorn) कहाँ से होकर गुजरती है?",
    options_en: ["Northern part", "Western part", "Right through the middle", "Southern part"],
    options_hi: ["उत्तरी भाग से", "पश्चिमी भाग से", "बीचों बीच से", "दक्षिणी भाग से"],
    correct_option_index: 2,
    explanation_en: "The Tropic of Capricorn passes right through the middle of Australia.",
    explanation_hi: "मकर रेखा ऑस्ट्रेलिया के बीचों बीच से होकर गुजरती है।",
  },
  {
    question_en: "New Zealand is called the 'Britain of the South'. Which is the longest river in New Zealand?",
    question_hi: "न्यूजीलैंड को 'दक्षिण का ब्रिटेन' (Britain of the South) कहा जाता है। न्यूजीलैंड की सबसे लंबी नदी कौन सी है?",
    options_en: ["Murray River", "Victoria River", "Waikato River", "Darling River"],
    options_hi: ["मरे नदी", "विक्टोरिया नदी", "वाइकाटो नदी (Waikato River)", "डार्लिंग नदी"],
    correct_option_index: 2,
    explanation_en: "The Waikato River is the longest river in New Zealand.",
    explanation_hi: "न्यूजीलैंड की सबसे लंबी नदी वाइकाटो नदी है।",
  },
  {
    question_en: "What is the highest peak of the continent of Antarctica?",
    question_hi: "अंटार्कटिका महाद्वीप का उच्चतम शिखर (Highest Peak) कौन सा है?",
    options_en: ["Mount Elbrus", "Mount Kilimanjaro", "Mount Erebus", "Vinson Massif"],
    options_hi: ["माउंट एलब्रुस", "माउंट किलिमंजारो", "माउंट इरेबस", "विन्सन मैसिफ (Vinson Massif)"],
    correct_option_index: 3,
    explanation_en: "The highest peak of Antarctica is Vinson Massif.",
    explanation_hi: "अंटार्कटिका का उच्चतम शिखर विन्सन मैसिफ है।",
  },
  {
    question_en: "The continent of Antarctica is known as what?",
    question_hi: "अंटार्कटिका महाद्वीप को किस रूप में जाना जाता है?",
    options_en: ["Tropical Continent", "Green Continent", "White Continent", "Dynamic Continent"],
    options_hi: ["उष्ण कटिबंधीय महाद्वीप", "हरा महाद्वीप", "श्वेत महाद्वीप (White Continent)", "गतिशील महाद्वीप"],
    correct_option_index: 2,
    explanation_en: "Antarctica is also called the 'Continent dedicated to Science', 'White Continent', and 'Dynamic Continent'.",
    explanation_hi: "अंटार्कटिका को 'विग्यान के लिए समर्पित महाद्वीप', 'श्वेत महाद्वीप', और 'गतिशील महाद्वीप' भी कहते हैं।",
  },
  {
    question_en: "Where are India's three research centers 'Dakshin Gangotri', 'Maitri', and 'Bharati' located?",
    question_hi: "भारत के तीन अनुसंधान केंद्र 'दक्षिण गंगोत्री', 'मैत्री' और 'भारती' कहाँ स्थित हैं?",
    options_en: ["Himalayas", "Indian Ocean", "Antarctica", "Arctic"],
    options_hi: ["हिमालय", "हिंद महासागर", "अंटार्कटिका", "आर्कटिक"],
    correct_option_index: 2,
    explanation_en: "These three research centers are established in Antarctica.",
    explanation_hi: "ये तीनों अनुसंधान केंद्र अंटार्कटिका में स्थापित हैं।",
  },
  {
    question_en: "Where are the Tropical Grasslands 'Savanna' found?",
    question_hi: "उष्णकटिबंधीय घास के मैदान (Tropical Grasslands) 'सवाना' कहाँ पाए जाते हैं?",
    options_en: ["South America", "North America", "Asia", "Africa"],
    options_hi: ["दक्षिण अमेरिका", "उत्तरी अमेरिका", "एशिया", "अफ्रीका"],
    correct_option_index: 3,
    explanation_en: "Savanna grasslands are found in Africa.",
    explanation_hi: "सवाना घास के मैदान अफ्रीका में पाए जाते हैं।",
  },
  {
    question_en: "Where are the Temperate Grasslands 'Prairie' found?",
    question_hi: "शीतोष्ण कटिबंधीय घास के मैदान (Temperate Grasslands) 'प्रेयरी' कहाँ पाए जाते हैं?",
    options_en: ["Hungary", "Argentina", "North America", "Australia"],
    options_hi: ["हंगरी", "अर्जेंटीना", "उत्तरी अमेरिका", "ऑस्ट्रेलिया"],
    correct_option_index: 2,
    explanation_en: "Prairie grasslands are found in North America.",
    explanation_hi: "प्रेयरी घास के मैदान उत्तरी अमेरिका में पाए जाते हैं।",
  },
  {
    question_en: "What are the temperate grasslands found in Argentina called?",
    question_hi: "अर्जेंटीना में पाए जाने वाले शीतोष्ण घास के मैदानों को क्या कहा जाता है?",
    options_en: ["Veld", "Downs", "Steppes", "Pampas"],
    options_hi: ["वेल्ड", "डाउंस", "स्टेपीज", "पंपास (Pampas)"],
    correct_option_index: 3,
    explanation_en: "These grasslands are called Pampas in Argentina and Uruguay.",
    explanation_hi: "अर्जेंटीना और उरुग्वे में इन मैदानों को पंपास कहा जाता है।",
  },
  {
    question_en: "What are the temperate grasslands in Australia called?",
    question_hi: "ऑस्ट्रेलिया में शीतोष्ण घास के मैदानों को क्या कहा जाता है?",
    options_en: ["Prairie", "Veld", "Downs", "Pampas"],
    options_hi: ["प्रेयरी", "वेल्ड", "डाउंस (Downs)", "पंपास"],
    correct_option_index: 2,
    explanation_en: "Temperate grasslands in Australia are called Downs.",
    explanation_hi: "ऑस्ट्रेलिया में शीतोष्ण घास के मैदानों को डाउंस कहा जाता है।",
  },
  {
    question_en: "What is the study of the Universe called?",
    question_hi: "ब्रह्मांड (Universe) के अध्ययन को क्या कहा जाता है?",
    options_en: ["Pedology", "Geology", "Entomology", "Cosmology"],
    options_hi: ["पेडोलॉजी", "जियोलॉजी", "एटमोलॉजी", "कॉस्मोलॉजी (Cosmology)"],
    correct_option_index: 3,
    explanation_en: "The study of the Universe is called Cosmology.",
    explanation_hi: "ब्रह्मांड के अध्ययन को कॉस्मोलॉजी कहा जाता है।",
  },
  {
    question_en: "Who propounded the 'Big-Bang Theory'?",
    question_hi: "'बिग बैंग सिद्धांत' (Big-Bang Theory) का प्रतिपादन किसने किया था?",
    options_en: ["Galileo", "Edwin Hubble", "George Lemaître", "Copernicus"],
    options_hi: ["गैलीलियो", "एडविन हब्बल", "जॉर्ज लेमैत्रे (George Lemaître)", "कोपरनिकस"],
    correct_option_index: 2,
    explanation_en: "The theory of the origin of the universe was given by Georges Lemaître.",
    explanation_hi: "ब्रह्मांड की उत्पत्ति का सिद्धांत जॉर्ज लेमैत्रे ने दिया था।",
  },
  {
    question_en: "What is the approximate temperature of the Sun's outer surface?",
    question_hi: "सूर्य की बाहरी सतह (Surface) का तापमान लगभग कितना होता है?",
    options_en: ["15 million degrees Celsius", "1000°C", "4500°C", "6000°C"],
    options_hi: ["15 मिलियन डिग्री सेल्सियस", "1000°C", "4500°C", "6000°C"],
    correct_option_index: 3,
    explanation_en: "The temperature of the Sun's outer surface is approximately 6000°C.",
    explanation_hi: "सूर्य की बाहरी सतह का तापमान 6000°C होता है।",
  },
  {
    question_en: "What is the source of the Sun's energy?",
    question_hi: "सूर्य की ऊर्जा का स्रोत क्या है?",
    options_en: ["Atomic Fission", "Atomic Decay", "Nuclear Fusion", "Gravitational Pull"],
    options_hi: ["परमाणु विखंडन", "परमाणु क्षरण", "नाभिकीय संलयन (Nuclear Fusion)", "गुरुत्वाकर्षण खिंचाव"],
    correct_option_index: 2,
    explanation_en: "The Sun's energy is obtained from Nuclear Fusion.",
    explanation_hi: "सूर्य की ऊर्जा नाभिकीय संलयन से प्राप्त होती है।",
  },
  {
    question_en: "Which of the following is NOT an inner planet?",
    question_hi: "निम्नलिखित में से कौन सा आंतरिक ग्रह (Inner planet) नहीं है?",
    options_en: ["Mercury", "Venus", "Earth", "Jupiter"],
    options_hi: ["बुध", "शुक्र", "पृथ्वी", "बृहस्पति (Jupiter)"],
    correct_option_index: 3,
    explanation_en: "The inner planets are Mercury, Venus, Earth, and Mars. Jupiter is an outer/Jovian planet.",
    explanation_hi: "आंतरिक ग्रह बुध, शुक्र, पृथ्वी और मंगल हैं। बृहस्पति एक बाह्य/जोवियन ग्रह है।",
  },
  {
    question_en: "Which is the smallest planet in the solar system?",
    question_hi: "सौरमंडल का सबसे छोटा ग्रह (Smallest planet) कौन सा है?",
    options_en: ["Mars", "Venus", "Mercury", "Pluto"],
    options_hi: ["मंगल", "शुक्र", "बुध (Mercury)", "प्लूटो"],
    correct_option_index: 2,
    explanation_en: "Mercury is the smallest planet in the solar system.",
    explanation_hi: "बुध सौरमंडल का सबसे छोटा ग्रह है।",
  },
  {
    question_en: "Which planet has no satellite?",
    question_hi: "किस ग्रह का कोई उपग्रह (Satellite) नहीं है?",
    options_en: ["Mars", "Saturn", "Mercury and Venus", "Jupiter"],
    options_hi: ["मंगल", "शनि", "बुध और शुक्र", "बृहस्पति"],
    correct_option_index: 2,
    explanation_en: "Mercury and Venus have no satellites.",
    explanation_hi: "बुध और शुक्र का कोई उपग्रह नहीं है।",
  },
  {
    question_en: "Which planet is called the 'Morning Star' and 'Evening Star'?",
    question_hi: "किस ग्रह को 'भोर का तारा' (Morning Star) और 'सांझ का तारा' (Evening Star) कहा जाता है?",
    options_en: ["Mercury", "Mars", "Venus", "Earth"],
    options_hi: ["बुध", "मंगल", "शुक्र (Venus)", "पृथ्वी"],
    correct_option_index: 2,
    explanation_en: "Venus is called the 'Morning Star' and 'Evening Star'.",
    explanation_hi: "शुक्र (Venus) को 'भोर का तारा' और 'सांझ का तारा' कहते हैं।",
  },
  {
    question_en: "Which two planets rotate from east to west (clockwise)?",
    question_hi: "कौन से दो ग्रह पूर्व से पश्चिम दिशा में घूमते हैं (दक्षिणावर्त/Clockwise)?",
    options_en: ["Earth and Mars", "Jupiter and Saturn", "Venus and Uranus", "Mars and Venus"],
    options_hi: ["पृथ्वी और मंगल", "बृहस्पति और शनि", "शुक्र और अरुण (Venus and Uranus)", "मंगल और शुक्र"],
    correct_option_index: 2,
    explanation_en: "Venus and Uranus rotate from east to west.",
    explanation_hi: "शुक्र और अरुण (Uranus) पूर्व से पश्चिम दिशा में घूमते हैं।",
  },
  {
    question_en: "Due to the abundance of Iron Oxide on which planet is it called the 'Red Planet'?",
    question_hi: "किस ग्रह पर लौह ऑक्साइड (Iron Oxide) की अधिकता के कारण उसे 'लाल ग्रह' (Red Planet) कहा जाता है?",
    options_en: ["Venus", "Saturn", "Mars", "Uranus"],
    options_hi: ["शुक्र", "शनि", "मंगल (Mars)", "अरुण"],
    correct_option_index: 2,
    explanation_en: "Due to the abundance of Iron Oxide on Mars, it is called the Red Planet.",
    explanation_hi: "मंगल ग्रह पर आयरन ऑक्साइड की अधिकता के कारण इसे लाल ग्रह कहा जाता है।",
  },
  {
    question_en: "On which planet is the solar system's largest volcano 'Olympus Mons' located?",
    question_hi: "सौरमंडल का सबसे बड़ा ज्वालामुखी 'ओलम्पस मॉन्स' (Olympus Mons) किस ग्रह पर स्थित है?",
    options_en: ["Earth", "Jupiter", "Mars", "Saturn"],
    options_hi: ["पृथ्वी", "बृहस्पति", "मंगल", "शनि"],
    correct_option_index: 2,
    explanation_en: "The solar system's largest volcano, Olympus Mons, is located on Mars.",
    explanation_hi: "सौरमंडल का सबसे बड़ा ज्वालामुखी ओलम्पस मॉन्स मंगल ग्रह पर स्थित है।",
  },
  {
    question_en: "The solar system's largest satellite 'Ganymede' is the satellite of which planet?",
    question_hi: "सौरमंडल का सबसे बड़ा उपग्रह 'गैनिमीड' (Ganymede) किस ग्रह का उपग्रह है?",
    options_en: ["Saturn", "Earth", "Jupiter", "Mars"],
    options_hi: ["शनि", "पृथ्वी", "बृहस्पति (Jupiter)", "मंगल"],
    correct_option_index: 2,
    explanation_en: "Ganymede is the satellite of Jupiter and the largest satellite in the solar system.",
    explanation_hi: "गैनिमीड बृहस्पति का उपग्रह है और यह सौरमंडल का सबसे बड़ा उपग्रह है।",
  },
  {
    question_en: "Due to the abundance of methane gas in the atmosphere of which planet is it called the 'Blue-Green Planet'?",
    question_hi: "किस ग्रह के वायुमंडल में मीथेन गैस की अधिकता के कारण इसे 'नीला-हरा ग्रह' (Blue-Green Planet) कहा जाता है?",
    options_en: ["Neptune", "Earth", "Saturn", "Uranus"],
    options_hi: ["नेपच्यून", "पृथ्वी", "शनि", "अरुण (Uranus)"],
    correct_option_index: 3,
    explanation_en: "Uranus is called the 'Blue-Green Planet' due to the abundance of methane gas.",
    explanation_hi: "अरुण (Uranus) को मीथेन गैस की अधिकता के कारण 'नीला-हरा ग्रह' कहा जाता है।",
  },
  {
    question_en: "The comet 'Hale-Bopp' appears on Earth after approximately how many years?",
    question_hi: "धूमकेतु (Comet) 'हैल-बॉप' (Hale-Bopp) पृथ्वी पर लगभग कितने वर्षों बाद दिखाई देता है?",
    options_en: ["12 years", "29 years", "50 years", "76 years"],
    options_hi: ["12 वर्ष", "29 वर्ष", "50 वर्ष", "76 वर्ष"],
    correct_option_index: 3,
    explanation_en: "The Hale-Bopp comet appears every 76 years.",
    explanation_hi: "धूमकेतु (Comet) प्रत्येक 76 वर्ष बाद दिखाई देता है।",
  },
  {
    question_en: "Under which mission did Neil Armstrong, the first person to step on the moon, go?",
    question_hi: "चंद्रमा पर कदम रखने वाला पहला व्यक्ति नील आर्मस्ट्रांग किस मिशन के तहत गए थे?",
    options_en: ["Apollo-1", "Luna-2", "Apollo-11", "Luna-9"],
    options_hi: ["अपोलो-1", "लूना-2", "अपोलो-11", "लूना-9"],
    correct_option_index: 2,
    explanation_en: "Neil Armstrong was the first person to reach the moon under the Apollo-11 mission (July 20, 1969).",
    explanation_hi: "नील आर्मस्ट्रांग अपोलो-11 मिशन (20 जुलाई, 1969) के तहत चंद्रमा पर पहुँचने वाले पहले व्यक्ति थे।",
  },
  {
    question_en: "Which gas is found in the highest quantity in the atmosphere?",
    question_hi: "वायुमंडल में पायी जाने वाली सबसे अधिक मात्रा में गैस कौन सी है?",
    options_en: ["Oxygen (20.95%)", "Argon (0.93%)", "Carbon Dioxide (0.03%)", "Nitrogen (78.0%)"],
    options_hi: ["ऑक्सीजन (20.95%)", "आर्गन (0.93%)", "कार्बन डाइऑक्साइड (0.03%)", "नाइट्रोजन (78.0%)"],
    correct_option_index: 3,
    explanation_en: "Nitrogen (78.0%) is found in the highest quantity in the atmosphere.",
    explanation_hi: "वायुमंडल में नाइट्रोजन (78.0%) सर्वाधिक मात्रा में पाई जाती है।",
  },
  {
    question_en: "What is the study of the lower layer of the atmosphere called?",
    question_hi: "वायुमंडल की निचली परत के अध्ययन को क्या कहा जाता है?",
    options_en: ["Aerology", "Cosmology", "Meteorology", "Pedology"],
    options_hi: ["एयरोलॉजी", "कॉस्मोलॉजी", "मीटरोलॉजी (Meteorology)", "पेडोलॉजी"],
    correct_option_index: 2,
    explanation_en: "The study of the lower layer of the atmosphere is called Meteorology.",
    explanation_hi: "वायुमंडल की निचली परत के अध्ययन को मीटरोलॉजी कहते हैं।",
  },
  {
    question_en: "Which is the lowest layer of the atmosphere?",
    question_hi: "वायुमंडल की सबसे निचली परत कौन सी है?",
    options_en: ["Stratosphere", "Mesosphere", "Ionosphere", "Troposphere"],
    options_hi: ["समतापमंडल", "मध्यमंडल", "आयनमंडल", "क्षोभमंडल (Troposphere)"],
    correct_option_index: 3,
    explanation_en: "The Troposphere is the lowest layer of the atmosphere.",
    explanation_hi: "क्षोभमंडल वायुमंडल की सबसे निचली परत है।",
  },
  {
    question_en: "All weather phenomena (like lightning, cloud formation) occur in which layer of the atmosphere?",
    question_hi: "सभी मौसमी घटनाएँ (जैसे बिजली का कड़कना, बादल बनना) वायुमंडल की किस परत में होती हैं?",
    options_en: ["Stratosphere", "Mesosphere", "Exosphere", "Troposphere"],
    options_hi: ["समतापमंडल", "मध्यमंडल", "बहिर्मंडल", "क्षोभमंडल"],
    correct_option_index: 3,
    explanation_en: "All weather phenomena occur in the Troposphere.",
    explanation_hi: "समस्त मौसमी घटनाएँ क्षोभमंडल में होती हैं।",
  },
  {
    question_en: "The Ozone layer is located in which layer of the atmosphere?",
    question_hi: "ओजोन परत (Ozone layer) वायुमंडल की किस परत में स्थित है?",
    options_en: ["Troposphere", "Mesosphere", "Exosphere", "Stratosphere"],
    options_hi: ["क्षोभमंडल", "मध्यमंडल", "बहिर्मंडल", "समतापमंडल (Stratosphere)"],
    correct_option_index: 3,
    explanation_en: "The Ozone layer is located in the Stratosphere.",
    explanation_hi: "ओजोन परत समतापमंडल में स्थित है।",
  },
  {
    question_en: "Which unit is used to measure the thickness of the Ozone layer?",
    question_hi: "ओजोन परत की मोटाई मापने के लिए किस इकाई (Unit) का प्रयोग किया जाता है?",
    options_en: ["Sievert", "Joule", "Calorie", "Dobson Unit"],
    options_hi: ["सीवर्ट", "जूल", "कैलोरी", "डॉबसन इकाई (Dobson Unit)"],
    correct_option_index: 3,
    explanation_en: "The Dobson Unit is used to measure the thickness of the Ozone layer.",
    explanation_hi: "ओजोन परत की मोटाई मापने के लिए डॉबसन इकाई का प्रयोग होता है।",
  },
  {
    question_en: "In which layer of the atmosphere do meteorites coming from space burn up?",
    question_hi: "अंतरिक्ष से आने वाले उल्कापिंड (Meteorites) वायुमंडल की किस परत में आकर समाप्त हो जाते हैं?",
    options_en: ["Stratosphere", "Ionosphere", "Exosphere", "Mesosphere"],
    options_hi: ["समतापमंडल", "आयनमंडल", "बहिर्मंडल", "मध्यमंडल (Mesosphere)"],
    correct_option_index: 3,
    explanation_en: "Meteorites burn up in the Mesosphere.",
    explanation_hi: "उल्कापिंड मध्यमंडल में जलकर समाप्त हो जाते हैं।",
  },
  {
    question_en: "Which layer of the atmosphere reflects radio waves?",
    question_hi: "रेडियो तरंगों (Radio waves) को परावर्तित करने वाली वायुमंडल की परत कौन सी है?",
    options_en: ["Stratosphere", "Troposphere", "Ionosphere", "Exosphere"],
    options_hi: ["समतापमंडल", "क्षोभमंडल", "आयनमंडल (Ionosphere)", "बहिर्मंडल"],
    correct_option_index: 2,
    explanation_en: "The Ionosphere (80-400 km) reflects radio waves, which enables communication.",
    explanation_hi: "आयनमंडल (80-400 किमी) रेडियो तरंगों को परावर्तित करती है, जिससे संचार संभव होता है।",
  },
  {
    question_en: "What type of satellites are established in the Ionosphere?",
    question_hi: "आयनमंडल में किस प्रकार के उपग्रह स्थापित किए जाते हैं?",
    options_en: ["Weather satellites", "Spy satellites", "GPS satellites", "Communication Satellite"],
    options_hi: ["मौसम उपग्रह", "जासूसी उपग्रह", "जीपीएस उपग्रह", "संचार उपग्रह (Communication Satellite)"],
    correct_option_index: 3,
    explanation_en: "Communication satellites are established in the Ionosphere.",
    explanation_hi: "संचार उपग्रह (Communication Satellite) आयनमंडल में स्थापित किए जाते हैं।",
  },
  {
    question_en: "The Exosphere, the uppermost layer of the atmosphere, is made up of which light gases?",
    question_hi: "बहिर्मंडल (Exosphere), जो वायुमंडल की सबसे ऊपरी परत है, किन हल्की गैसों से बनी है?",
    options_en: ["Oxygen and Nitrogen", "Carbon Dioxide and Argon", "Methane and Ammonia", "Helium, Argon and Hydrogen"],
    options_hi: ["ऑक्सीजन और नाइट्रोजन", "कार्बन डाइऑक्साइड और आर्गन", "मीथेन और अमोनिया", "हीलियम, आर्गन और हाइड्रोजन"],
    correct_option_index: 3,
    explanation_en: "The Exosphere is made up of light gases like Helium, Argon, and Hydrogen.",
    explanation_hi: "बहिर्मंडल हीलियम, आर्गन और हाइड्रोजन जैसी हल्की गैसों से बनी है।",
  },
  {
    question_en: "What is the highest peak of the Maikal Mountain Range?",
    question_hi: "मैकाल पर्वत शृंखला (Maikal Range) की सबसे ऊँची चोटी कौन सी है?",
    options_en: ["Dhupgarh", "Sadbhavna Shikhar", "Kalsubai", "Amrakantak"],
    options_hi: ["धूपगढ़", "सद्भावना शिखर", "कलसुबाई", "अमरकंटक (Amrakantak)"],
    correct_option_index: 3,
    explanation_en: "The highest peak of the Maikal Range is Amrakantak (1065 m).",
    explanation_hi: "मैकाल रेंज की सबसे ऊँची चोटी अमरकंटक (1065 मी) है।",
  },
  {
    question_en: "Which is the largest peninsula in the world?",
    question_hi: "विश्व का सबसे बड़ा प्रायद्वीप (Largest Peninsula in the world) कौन सा है?",
    options_en: ["Peninsular India", "Kamchatka Peninsula", "Alaska Peninsula", "Arabian Peninsula"],
    options_hi: ["प्रायद्वीपीय भारत", "कमचटका प्रायद्वीप", "अलास्का प्रायद्वीप", "अरब प्रायद्वीप (Arabian Peninsula)"],
    correct_option_index: 3,
    explanation_en: "The Arabian Peninsula is the largest peninsula in the world.",
    explanation_hi: "अरब प्रायद्वीप विश्व का सबसे बड़ा प्रायद्वीप है।",
  },
  {
    question_en: "The Peninsular Plateau was formed during which geological era?",
    question_hi: "प्रायद्वीपीय पठार का निर्माण किस भूवैज्ञानिक काल (Era) में हुआ था?",
    options_en: ["Paleozoic", "Carboniferous", "Pre-Cambrian Era", "Mesozoic"],
    options_hi: ["पेलियोजोइक", "कार्बोनिफेरस", "प्री-कैम्ब्रियन कल्प (Pre-Cambrian Era)", "मेसोजोइक"],
    correct_option_index: 2,
    explanation_en: "The Peninsular Plateau was formed during the Pre-Cambrian Era.",
    explanation_hi: "प्रायद्वीपीय पठार का निर्माण प्री-कैम्ब्रियन कल्प में हुआ था।",
  },
  {
    question_en: "Which waterfall on the Godavari River is called 'Buddhi Ganga' or 'Niagara of India'?",
    question_hi: "गोदावरी नदी पर स्थित 'बुद्धि गंगा' या 'भारत का नियाग्रा' जलप्रपात कौन सा है?",
    options_en: ["Jog Falls", "Chulia Falls", "Kunchikal Falls", "Indravati Falls (Chitrakoot)"],
    options_hi: ["जोग जलप्रपात", "चूलिया जलप्रपात", "कुंचिकल जलप्रपात", "इंद्रावती जलप्रपात (चित्रकूट)"],
    correct_option_index: 3,
    explanation_en: "The Indravati Falls (Chitrakoot) is called the 'Niagara Falls of India'.",
    explanation_hi: "इंद्रावती जलप्रपात (चित्रकूट) को 'भारत का नियाग्रा जलप्रपात' कहा जाता है।",
  },
  {
    question_en: "The 'Tropic of Capricorn' is located at which latitude?",
    question_hi: "'मकर रेखा' (Tropic of Capricorn) किन अक्षांश पर स्थित है?",
    options_en: ["0° Latitude", "23½° North Latitude", "66½° North Latitude", "23½° South Latitude"],
    options_hi: ["0° अक्षांश", "23½° उत्तरी अक्षांश", "66½° उत्तरी अक्षांश", "23½° दक्षिणी अक्षांश"],
    correct_option_index: 3,
    explanation_en: "The Tropic of Capricorn is located at 23½° South latitude.",
    explanation_hi: "मकर रेखा 23½° दक्षिणी अक्षांश (South latitude) पर स्थित है।",
  },
  {
    question_en: "The 'Silver Fibre Revolution' is related to the production of what?",
    question_hi: "'सिल्वर फाइबर क्रांति' (Silver Fibre Revolution) का संबंध किसके उत्पादन से है?",
    options_en: ["Milk production", "Oilseed production", "Cotton production", "Jute production"],
    options_hi: ["दूध उत्पादन", "तिलहन उत्पादन", "कपास उत्पादन", "जूट उत्पादन"],
    correct_option_index: 2,
    explanation_en: "The Silver Fibre Revolution is related to cotton production.",
    explanation_hi: "सिल्वर फाइबर क्रांति कपास उत्पादन से संबंधित है।",
  },
  {
    question_en: "The 'Green Gold Revolution' is related to what?",
    question_hi: "'हरीत स्वर्ण क्रांति' (Green Gold Revolution) का संबंध किससे है?",
    options_en: ["Tea production", "Saffron production", "Fruit production", "Bamboo production"],
    options_hi: ["चाय उत्पादन", "केसर उत्पादन", "फल उत्पादन", "बाँस उत्पादन"],
    correct_option_index: 3,
    explanation_en: "The Green Gold Revolution is related to Bamboo production.",
    explanation_hi: "हरीत स्वर्ण क्रांति का संबंध बाँस (Bamboo) उत्पादन से है।",
  },
  {
    question_en: "Which lake is called the 'Largest Lagoon Lake of India'?",
    question_hi: "किस झील को 'भारत की सबसे बड़ी लैगून झील' कहा जाता है?",
    options_en: ["Wular Lake", "Loktak Lake", "Vembanad Lake", "Chilika Lake"],
    options_hi: ["वुलर झील", "लोकटक झील", "वेम्बनाड झील", "चिल्का झील"],
    correct_option_index: 3,
    explanation_en: "Chilika Lake (Odisha) is the largest lagoon lake in India.",
    explanation_hi: "चिल्का झील (ओडिशा) भारत की सबसे बड़ी लैगून झील है।",
  },
  {
    question_en: "Which country's national anthem is 'Amar Sonar Bangla'?",
    question_hi: "किस देश का राष्ट्रीय गान 'अमर सोनार बांग्ला' (Amar Sonar Bangla) है?",
    options_en: ["India", "Sri Lanka", "Nepal", "Bangladesh"],
    options_hi: ["भारत", "श्रीलंका", "नेपाल", "बांग्लादेश"],
    correct_option_index: 3,
    explanation_en: "The national anthem of Bangladesh is 'Amar Sonar Bangla'.",
    explanation_hi: "बांग्लादेश का राष्ट्रीय गान 'अमर सोनार बांग्ला' है।",
  }
];


export default test3Questions;
