import type { QuizQuestion } from '../../../types';

const test1Questions: QuizQuestion[] =[
  {
    question_en: "What is the total area of India?",
    question_hi: "भारत का कुल क्षेत्रफल कितना है?",
    options_en: ["30,87,263 sq km", "34,87,263 sq km", "32,87,263 sq km", "31,50,000 sq km"],
    options_hi: ["30,87,263 वर्ग किमी", "34,87,263 वर्ग किमी", "32,87,263 वर्ग किमी", "31,50,000 वर्ग किमी"],
    correct_option_index: 2,
    explanation_en: "The total area of India is 32,87,263 sq km.",
    explanation_hi: "भारत का क्षेत्रफल 32,87,263 वर्ग किमी है।",
  },
  {
    question_en: "What is the shape of India?",
    question_hi: "भारत का आकार (Shape) कैसा है?",
    options_en: ["Triangular", "Circular", "Rectangular", "Quadrilateral"],
    options_hi: ["त्रिभुजाकार (Triangular)", "वृत्ताकार (Circular)", "आयताकार (Rectangular)", "चतुष्कोणीय (Quadrilateral)"],
    correct_option_index: 3,
    explanation_en: "The shape of India is Quadrilateral.",
    explanation_hi: "भारत का आकार चतुष्कोणीय (Quadrilateral) है।",
  },
  {
    question_en: "What percentage of the Earth's total land area does India cover?",
    question_hi: "भारत पृथ्वी के कुल भू-क्षेत्र का लगभग कितना प्रतिशत भाग घेरता है?",
    options_en: ["1.8%", "2.4%", "3.2%", "4.1%"],
    options_hi: ["1.8%", "2.4%", "3.2%", "4.1%"],
    correct_option_index: 1,
    explanation_en: "India covers about 2.4% of the Earth's land area.",
    explanation_hi: "भारत पृथ्वी का 2.4% भाग घेरे हुए है।",
  },
  {
    question_en: "According to area, what is India's rank among the top 10 countries in the world?",
    question_hi: "क्षेत्रफल के अनुसार, विश्व के शीर्ष 10 देशों में भारत का स्थान कौन सा है?",
    options_en: ["Sixth", "Seventh", "Eighth", "Ninth"],
    options_hi: ["छठा", "सातवाँ", "आठवाँ", "नौवाँ"],
    correct_option_index: 1,
    explanation_en: "India is the 7th largest country in the world by area.",
    explanation_hi: "भारत क्षेत्रफल के हिसाब से विश्व का 7वाँ सबसे बड़ा देश है।",
  },
  {
    question_en: "At what North latitude is 'Indira Col', the northernmost point of India, located?",
    question_hi: "भारत का सबसे उत्तरी बिंदु 'इंदिरा कॉल' कितने उत्तरी अक्षांश (North latitude) पर स्थित है?",
    options_en: ["8°4′ North latitude", "6°4′ North latitude", "32°5′ North latitude", "37°6′ North latitude"],
    options_hi: ["8°4′ उत्तरी अक्षांश", "6°4′ उत्तरी अक्षांश", "32°5′ उत्तरी अक्षांश", "37°6′ उत्तरी अक्षांश"],
    correct_option_index: 3,
    explanation_en: "India's northern point Indira Col (in P.O.K.) is located at 37°6′ North latitude.",
    explanation_hi: "भारत का उत्तरी बिंदु इंदिरा कॉल (P.O.K. में) 37°6′ उत्तरी अक्षांश पर स्थित है।",
  },
  {
    question_en: "In which state is 'Kibithu', the easternmost point of India, located?",
    question_hi: "भारत का सबसे पूर्वी बिंदु 'किबिथू' किस राज्य में स्थित है?",
    options_en: ["Nagaland", "Sikkim", "Arunachal Pradesh", "Mizoram"],
    options_hi: ["नागालैंड", "सिक्किम", "अरुणाचल प्रदेश", "मिजोरम"],
    correct_option_index: 2,
    explanation_en: "India's easternmost point Kibithu (97°25' East longitude) is located in Arunachal Pradesh.",
    explanation_hi: "भारत का सबसे पूर्वी बिंदु किबिथू (97°25' पूर्वी देशांतर) अरुणाचल प्रदेश में स्थित है।",
  },
  {
    question_en: "What is the North-South extension of India?",
    question_hi: "भारत का उत्तर से दक्षिण विस्तार (North-South extension) कितना है?",
    options_en: ["2933 km", "3214 km", "3500 km", "3000 km"],
    options_hi: ["2933 किमी", "3214 किमी", "3500 किमी", "3000 किमी"],
    correct_option_index: 1,
    explanation_en: "The North-South extension of India is 3214 km.",
    explanation_hi: "भारत का उत्तर से दक्षिण विस्तार 3214 किमी है।",
  },
  {
    question_en: "What is the value of the Indian Standard Time Line (IST)?",
    question_hi: "भारतीय मानक समय रेखा (IST) का मान क्या है?",
    options_en: ["80°30′ East longitude", "81°30′ East longitude", "82°30′ East longitude", "84°30′ East longitude"],
    options_hi: ["80°30′ पूर्वी देशांतर", "81°30′ पूर्वी देशांतर", "82°30′ पूर्वी देशांतर", "84°30′ पूर्वी देशांतर"],
    correct_option_index: 2,
    explanation_en: "IST is located at 82°30′ East longitude.",
    explanation_hi: "IST 82°30′ पूर्वी देशांतर पर स्थित है।",
  },
  {
    question_en: "The Indian Standard Time Line (IST) passes through how many states?",
    question_hi: "भारतीय मानक समय रेखा (IST) कितने राज्यों से होकर गुजरती है?",
    options_en: ["4", "5", "6", "7"],
    options_hi: ["4", "5", "6", "7"],
    correct_option_index: 1,
    explanation_en: "The IST line passes through 5 states (UP, MP, Chhattisgarh, Odisha, Andhra Pradesh).",
    explanation_hi: "IST रेखा 5 राज्यों (UP, MP, छत्तीसगढ़, ओडिशा, आंध्र प्रदेश) से होकर गुजरती है।",
  },
  {
    question_en: "The Tropic of Cancer passes through how many states in India?",
    question_hi: "कर्क रेखा (Tropic of Cancer) भारत के कुल कितने राज्यों से होकर गुजरती है?",
    options_en: ["7", "8", "9", "10"],
    options_hi: ["7", "8", "9", "10"],
    correct_option_index: 1,
    explanation_en: "The Tropic of Cancer passes through 8 states of India (Mizoram, Tripura, West Bengal, Rajasthan, Gujarat, Madhya Pradesh, Chhattisgarh, Jharkhand).",
    explanation_hi: "कर्क रेखा भारत के 8 राज्यों (मिजोरम, त्रिपुरा, पश्चिम बंगाल, राजस्थान, गुजरात, मध्य प्रदेश, छत्तीसगढ़, झारखंड) से गुजरती है।",
  },
  {
    question_en: "From which state is the length of the Tropic of Cancer the smallest?",
    question_hi: "किस राज्य से कर्क रेखा की लंबाई सबसे कम (Smallest) है?",
    options_en: ["Gujarat", "Madhya Pradesh", "West Bengal", "Rajasthan"],
    options_hi: ["गुजरात", "मध्य प्रदेश", "पश्चिम बंगाल", "राजस्थान"],
    correct_option_index: 3,
    explanation_en: "The shortest length of the Tropic of Cancer passes through Rajasthan.",
    explanation_hi: "कर्क रेखा की सबसे छोटी लंबाई राजस्थान से होकर गुजरती है।",
  },
  {
    question_en: "The capital of which state is located on the Tropic of Cancer?",
    question_hi: "किस राज्य की राजधानी कर्क रेखा पर स्थित है?",
    options_en: ["Bhopal (Madhya Pradesh)", "Gandhinagar (Gujarat)", "Ranchi (Jharkhand)", "Aizawl (Mizoram)"],
    options_hi: ["भोपाल (मध्य प्रदेश)", "गाँधीनगर (गुजरात)", "राँची (झारखंड)", "आइजोल (मिजोरम)"],
    correct_option_index: 2,
    explanation_en: "The capital of Ranchi (Jharkhand) is located on the Tropic of Cancer.",
    explanation_hi: "राँची (झारखंड) की राजधानी कर्क रेखा पर स्थित है।",
  },
  {
    question_en: "What is the length of the coastline of the mainland of India (Old Data)?",
    question_hi: "भारत की मुख्य भूमि की तटीय सीमा की लंबाई (Old Data) कितनी है?",
    options_en: ["6100 km", "7516.67 km", "11098 km", "15106.7 km"],
    options_hi: ["6100 किमी", "7516.67 किमी", "11098 किमी", "15106.7 किमी"],
    correct_option_index: 0,
    explanation_en: "The length of the mainland's coastline is 6100 km.",
    explanation_hi: "मुख्यभूमि की तटीय सीमा की लंबाई 6100 किमी है।",
  },
  {
    question_en: "What is the new total length of India's coastline including island groups (New Data)?",
    question_hi: "द्वीप समूहों सहित भारत की कुल तटीय सीमा की नई लंबाई (New Data) कितनी हो गई है?",
    options_en: ["7516.67 km", "8848 km", "11098 km", "6100 km"],
    options_hi: ["7516.67 किमी", "8848 किमी", "11098 किमी", "6100 किमी"],
    correct_option_index: 2,
    explanation_en: "According to new data, the total coastline length has increased from 7516.67 km to 11098 km.",
    explanation_hi: "नई डेटा के अनुसार कुल तटीय रेखा की लंबाई 7516.67 किमी से बढ़कर 11098 किमी हो गई है।",
  },
  {
    question_en: "According to new data, which state's coastline has increased by 47.6%?",
    question_hi: "नए डेटा के अनुसार, किस राज्य की तटीय रेखा में 47.6% की वृद्धि हुई है?",
    options_en: ["Andhra Pradesh", "Tamil Nadu", "Goa", "Gujarat"],
    options_hi: ["आंध्र प्रदेश", "तमिलनाडु", "गोवा", "गुजरात"],
    correct_option_index: 3,
    explanation_en: "Gujarat's coastline has increased from 1214 km to about 2340 km.",
    explanation_hi: "गुजरात की तटीय रेखा 1214 किमी से बढ़कर लगभग 2340 किमी हो गई है।",
  },
  {
    question_en: "Which two countries share a sea border with India?",
    question_hi: "किन दो देशों के बीच जलीय सीमा (Sea Border) लगती है?",
    options_en: ["India and Myanmar", "India and Indonesia", "Maldives and Sri Lanka", "India and Pakistan"],
    options_hi: ["भारत और म्यांमार", "भारत और इंडोनेशिया", "मालदीव और श्रीलंका", "भारत और पाकिस्तान"],
    correct_option_index: 2,
    explanation_en: "Maldives and Sri Lanka are two countries that share a sea border with India.",
    explanation_hi: "मालदीव और श्रीलंका दो ऐसे देश हैं जो भारत के साथ जलीय सीमा साझा करते हैं।",
  },
  {
    question_en: "With which neighboring country does India share its longest land boundary?",
    question_hi: "भारत की सबसे लंबी स्थलीय सीमा किस पड़ोसी देश के साथ लगती है?",
    options_en: ["China (3488 km)", "Pakistan (3323 km)", "Nepal (1751 km)", "Bangladesh (4096.7 km)"],
    options_hi: ["चीन (3488 किमी)", "पाकिस्तान (3323 किमी)", "नेपाल (1751 किमी)", "बांग्लादेश (4096.7 किमी)"],
    correct_option_index: 3,
    explanation_en: "India shares its longest border with Bangladesh (4096.7 km).",
    explanation_hi: "भारत की सबसे लंबी सीमा बांग्लादेश (4096.7 किमी) के साथ लगती है।",
  },
  {
    question_en: "The Parliament of which neighboring country is called 'Jatiya Sansad'?",
    question_hi: "किस पड़ोसी देश की संसद को 'जातीय संसद' (Jatiya Sansad) कहा जाता है?",
    options_en: ["Nepal", "Pakistan", "Bangladesh", "Myanmar"],
    options_hi: ["नेपाल", "पाकिस्तान", "बांग्लादेश", "म्यांमार"],
    correct_option_index: 2,
    explanation_en: "The Parliament of Bangladesh is called Jatiya Sansad.",
    explanation_hi: "बांग्लादेश की संसद को जातीय संसद कहा जाता है।",
  },
  {
    question_en: "What is the border line between India and Pakistan known as?",
    question_hi: "भारत और पाकिस्तान के बीच की सीमा रेखा किस नाम से जानी जाती है?",
    options_en: ["Durand Line", "McMahon Line", "Radcliffe Line", "24th Parallel Line"],
    options_hi: ["डूरंड रेखा", "मैकमोहन रेखा", "रेडक्लिफ रेखा", "24वीं समांतर रेखा"],
    correct_option_index: 2,
    explanation_en: "The border between India and Pakistan is called the Radcliffe Line.",
    explanation_hi: "भारत और पाकिस्तान के बीच की सीमा रेडक्लिफ रेखा कहलाती है।",
  },
  {
    question_en: "The border of Afghanistan touches which region of India?",
    question_hi: "अफगानिस्तान की सीमा भारत के किस क्षेत्र से लगती है?",
    options_en: ["Jammu", "Himachal Pradesh", "Punjab", "Ladakh"],
    options_hi: ["जम्मू", "हिमाचल प्रदेश", "पंजाब", "लद्दाख"],
    correct_option_index: 3,
    explanation_en: "Afghanistan shares a border only with Ladakh (106 km), which is the shortest border India shares.",
    explanation_hi: "अफगानिस्तान केवल लद्दाख (106 किमी) के साथ सीमा साझा करता है, जो भारत के साथ सबसे छोटी सीमा है।",
  },
  {
    question_en: "Which state does not share a border with Bangladesh?",
    question_hi: "कौन सा राज्य बांग्लादेश के साथ सीमा साझा नहीं करता है?",
    options_en: ["Assam", "Meghalaya", "Tripura", "Manipur"],
    options_hi: ["असम", "मेघालय", "त्रिपुरा", "मणिपुर"],
    correct_option_index: 3,
    explanation_en: "It is clear from the source that Bangladesh does not share a border with Manipur.",
    explanation_hi: "स्रोत में स्पष्ट है कि बांग्लादेश मणिपुर के साथ सीमा नहीं लगाता है।",
  },
  {
    question_en: "The capital of which neighboring country is 'Naypyidaw'?",
    question_hi: "किस पड़ोसी देश की राजधानी 'नय प्यीदॉ' (Naypyidaw) है?",
    options_en: ["Nepal", "Bhutan", "Myanmar", "China"],
    options_hi: ["नेपाल", "भूटान", "म्यांमार", "चीन"],
    correct_option_index: 2,
    explanation_en: "The capital of Myanmar is Naypyidaw.",
    explanation_hi: "म्यांमार की राजधानी नय प्यीदॉ है।",
  },
  {
    question_en: "Which country's highest peak is Kekaradang peak?",
    question_hi: "किस देश का सर्वोच्च शिखर (Highest Peak) केकरादोंग चोटी (Kekaradang peak) है?",
    options_en: ["Myanmar", "Nepal", "Bangladesh", "China"],
    options_hi: ["म्यांमार", "नेपाल", "बांग्लादेश", "चीन"],
    correct_option_index: 2,
    explanation_en: "Kekaradang peak is the highest peak of Bangladesh.",
    explanation_hi: "बांग्लादेश का सर्वोच्च शिखर केकरादोंग चोटी है।",
  },
  {
    question_en: "The 8° Degree channel separates which two regions?",
    question_hi: "8° डिग्री चैनल (8° Degree channel) किन दो क्षेत्रों को अलग करता है?",
    options_en: ["Lakshadweep and Minicoy", "Maldives and Minicoy", "Little Andaman and Car Nicobar", "South Andaman and Little Andaman"],
    options_hi: ["लक्षद्वीप और मिनिकॉय", "मालदीव और मिनिकॉय", "लघु अंडमान और कार निकोबार", "दक्षिणी अंडमान और लघु अंडमान"],
    correct_option_index: 1,
    explanation_en: "The 8° Degree channel separates Minicoy Island from the Maldives.",
    explanation_hi: "8° डिग्री चैनल मिनिकॉय द्वीप को मालदीव से अलग करता है।",
  },
  {
    question_en: "Duncan Pass is located between which two Andaman Islands?",
    question_hi: "डंकन पास (Duncan Pass) किन दो अंडमान द्वीपों के बीच स्थित है?",
    options_en: ["Little Andaman and Car Nicobar", "North Andaman and Middle Andaman", "South Andaman and Little Andaman", "Great Nicobar and Sumatra"],
    options_hi: ["लघु अंडमान और कार निकोबार", "उत्तरी अंडमान और मध्य अंडमान", "दक्षिणी अंडमान और लघु अंडमान", "ग्रेट निकोबार और सुमात्रा"],
    correct_option_index: 2,
    explanation_en: "Duncan Pass is between South Andaman and Little Andaman.",
    explanation_hi: "डंकन पास दक्षिणी अंडमान और लघु अंडमान के बीच है।",
  },
  {
    question_en: "Palk Strait is located between which two regions?",
    question_hi: "पाक जलसंधि (Palk Strait) किन दो क्षेत्रों के बीच स्थित है?",
    options_en: ["India and Sri Lanka", "India and Indonesia", "Maldives and Lakshadweep", "Great Nicobar and Sumatra"],
    options_hi: ["भारत और श्रीलंका", "भारत और इंडोनेशिया", "मालदीव और लक्षद्वीप", "ग्रेट निकोबार और सुमात्रा"],
    correct_option_index: 0,
    explanation_en: "Palk Strait is located between Sri Lanka and Tamil Nadu (India).",
    explanation_hi: "पाक जलसंधि श्रीलंका और तमिलनाडु (भारत) के बीच स्थित है।",
  },
  {
    question_en: "Where is Saddle Peak, the highest peak of the Andaman Nicobar Islands, located?",
    question_hi: "अंडमान निकोबार द्वीप समूह का सबसे ऊँचा शिखर सैडल पीक (Saddle Peak) कहाँ स्थित है?",
    options_en: ["Middle Andaman", "South Andaman", "North Andaman", "Great Nicobar"],
    options_hi: ["मध्य अंडमान", "दक्षिणी अंडमान", "उत्तरी अंडमान", "ग्रेट निकोबार"],
    correct_option_index: 2,
    explanation_en: "Saddle Peak is located on North Andaman Island.",
    explanation_hi: "सैडल पीक उत्तरी अंडमान द्वीप पर स्थित है।",
  },
  {
    question_en: "Which island has been named 'Shaheed Dweep'?",
    question_hi: "किस द्वीप को 'शहीद द्वीप' (Shaheed dweep) नाम दिया गया है?",
    options_en: ["Ross Island", "Barren Island", "Neil Island", "Havelock Island"],
    options_hi: ["रॉस द्वीप", "बैरन द्वीप", "नील द्वीप", "हैवलाॅक द्वीप"],
    correct_option_index: 2,
    explanation_en: "The new name of Neil Island is Shaheed Dweep.",
    explanation_hi: "नील द्वीप का नया नाम शहीद द्वीप है।",
  },
  {
    question_en: "Which is the only active volcano in India?",
    question_hi: "भारत का एकमात्र सक्रिय ज्वालामुखी (Active Volcano) कौन सा है?",
    options_en: ["Narcondam Island", "Pamban Island", "Barren Island", "Landfall Island"],
    options_hi: ["नारकोंडम द्वीप", "पंबन द्वीप", "बैरन द्वीप", "लैन्डफॉल द्वीप"],
    correct_option_index: 2,
    explanation_en: "Barren Island (Andaman Nicobar) is the only active volcano in India.",
    explanation_hi: "बैरन द्वीप (अंडमान निकोबार) भारत का एकमात्र सक्रिय ज्वालामुखी है।",
  },
  {
    question_en: "Majuli, the world's largest riverine island, is located on which river?",
    question_hi: "विश्व का सबसे बड़ा नदी द्वीप (World's largest riverine island) माजुली (Majuli) किस नदी पर स्थित है?",
    options_en: ["Ganga", "Indus", "Brahmaputra", "Godavari"],
    options_hi: ["गंगा", "सिंधु", "ब्रह्मपुत्र", "गोदावरी"],
    correct_option_index: 2,
    explanation_en: "Majuli Island is located on the Brahmaputra River.",
    explanation_hi: "माजुली द्वीप ब्रह्मपुत्र नदी पर स्थित है।",
  },
  {
    question_en: "The Lakshadweep Islands are made up of which type of deposits?",
    question_hi: "लक्षद्वीप द्वीप समूह किस प्रकार के निक्षेपों (deposits) से बना है?",
    options_en: ["Volcanic", "Sedimentary", "River deposits", "Coral deposits"],
    options_hi: ["ज्वालामुखीय", "अवसादी", "नदियों के निक्षेप", "प्रवाल निक्षेप (Coral deposits)"],
    correct_option_index: 3,
    explanation_en: "The Lakshadweep Islands are made up of coral deposits.",
    explanation_hi: "लक्षद्वीप द्वीप समूह प्रवाल निक्षेपों (coral deposits) से बना है।",
  },
  {
    question_en: "Which island was named Netaji Subhash Chandra Bose Island?",
    question_hi: "किस द्वीप का नाम नेताजी सुभाष चंद्र बोस द्वीप (Netaji Subhash Chandra Bose Island) रखा गया है?",
    options_en: ["Havelock Island", "Neil Island", "Landfall Island", "Ross Island"],
    options_hi: ["हैवलाॅक द्वीप", "नील द्वीप", "लैंडफॉल द्वीप", "रॉस द्वीप"],
    correct_option_index: 3,
    explanation_en: "The new name of Ross Island is Netaji Subhash Chandra Bose Island.",
    explanation_hi: "रॉस द्वीप का नया नाम नेताजी सुभाष चंद्र बोस द्वीप है।",
  },
  {
    question_en: "Which island, part of the Lakshadweep group, has India's only airport?",
    question_hi: "किस द्वीप पर भारत का एकमात्र हवाई अड्डा (Airport) है जो लक्षद्वीप समूह का हिस्सा है?",
    options_en: ["Minicoy", "Pitt Island", "Agatti Island", "Androth Island"],
    options_hi: ["मिनिकॉय", "पिट्टी द्वीप", "अगाती द्वीप", "एंड्रोथ द्वीप"],
    correct_option_index: 2,
    explanation_en: "The airport is located on Agatti Island (Lakshadweep).",
    explanation_hi: "अगाती द्वीप (लक्षद्वीप) पर हवाई अड्डा स्थित है।",
  },
  {
    question_en: "What is the average height of the Great Himalaya?",
    question_hi: "महानदी (Great Himalaya) की औसत ऊँचाई (Average Height) कितनी है?",
    options_en: ["3000-4500 meters", "600-1200 meters", "1500-1800 meters", "≈ 6100 meters"],
    options_hi: ["3000-4500 मीटर", "600-1200 मीटर", "1500-1800 मीटर", "≈ 6100 मीटर"],
    correct_option_index: 3,
    explanation_en: "The average height of the Great Himalaya is approximately 6100 meters.",
    explanation_hi: "वृहत्/महान हिमालय की औसत ऊँचाई लगभग 6100 मीटर है।",
  },
  {
    question_en: "What is the Karakoram Range also known as?",
    question_hi: "कराकोरम श्रेणी को किस नाम से जाना जाता है?",
    options_en: ["Himadri", "Shivalik", "Backbone of high Asia", "Outer Himalaya"],
    options_hi: ["हिमाद्रि", "शिवालिक", "उच्च एशिया की रीढ़ (Backbone of high Asia)", "बाह्य हिमालय"],
    correct_option_index: 2,
    explanation_en: "The Karakoram Range is also known as the Backbone of high Asia.",
    explanation_hi: "कराकोरम श्रेणी को उच्च एशिया की रीढ़ कहा जाता है।",
  },
  {
    question_en: "By what name is Mount Everest known in Nepal?",
    question_hi: "माउंट एवरेस्ट को नेपाल में किस नाम से जाना जाता है?",
    options_en: ["Sagarmatha", "Nanda Devi", "K2", "Sagarmatha (Sagarmata)"],
    options_hi: ["सागरमाथा", "नंदादेवी", "के2", "सागरमाथा (Sagarmata)"],
    correct_option_index: 0,
    explanation_en: "Mount Everest is called Sagarmatha in Nepal.",
    explanation_hi: "माउंट एवरेस्ट को नेपाल में सागरमाथा कहा जाता है।",
  },
  {
    question_en: "Which is the longest mountain range of the Lesser/Middle Himalaya?",
    question_hi: "लघु/मध्य हिमालय की सबसे लंबी पर्वत श्रृंखला (Longest Mts. Range) कौन सी है?",
    options_en: ["Nagtibba", "Mussoorie", "Mahabharat Range", "Pir Panjal"],
    options_hi: ["नागटिब्बा", "मसूरी", "महाभारत रेंज", "पीर पंजाल"],
    correct_option_index: 3,
    explanation_en: "The Pir Panjal Range, located in Jammu and Kashmir, is the longest range of the Lesser/Middle Himalaya.",
    explanation_hi: "जम्मू-कश्मीर में स्थित पीर पंजाल श्रेणी लघु/मध्य हिमालय की सबसे लंबी श्रृंखला है।",
  },
  {
    question_en: "Which fault separates the Lesser Himalaya from the Shivalik Himalaya?",
    question_hi: "लघु हिमालय को शिवालिक हिमालय से कौन सा भ्रंश अलग करता है?",
    options_en: ["I.T.S.Z. (Indus-Tsangpo Suture Zone)", "Main Central Thrust (MCT)", "Main Boundary Fault (MBF)", "H.F.F. (Himalayan Frontal Fault)"],
    options_hi: ["I.T.S.Z. (सिंधु त्सांग्पो संरचना क्षेत्र)", "Main Central Thrust (MCT)", "Main Boundary Fault (MBF)", "H.F.F. (हिमालयन फ्रंटल फॉल्ट)"],
    correct_option_index: 2,
    explanation_en: "The Lesser/Middle Himalaya is separated from the Shivalik Himalaya by the Main Boundary Fault.",
    explanation_hi: "लघु/मध्य हिमालय Main Boundary Fault द्वारा शिवालिक हिमालय से अलग होता है।",
  },
  {
    question_en: "Who proposed the theory of the division of the Himalayas based on rivers?",
    question_hi: "नदियों के आधार पर हिमालय के विभाजन का सिद्धांत किसने दिया था?",
    options_en: ["Alfred Wegener", "H.R. Hay", "Sydney Burrad", "Stahler"],
    options_hi: ["अल्फ्रेड वेगनर", "एच.आर. हय", "सिडनी बुर्राड (Sydney Burrad)", "स्टालर"],
    correct_option_index: 2,
    explanation_en: "The regional division of the Himalayas was done by Sydney Burrad.",
    explanation_hi: "हिमालय का प्रादेशिक विभाजन सिडनी बुर्राड ने किया था।",
  },
  {
    question_en: "Which Himalaya extends between the Kali River and the Teesta River?",
    question_hi: "किस हिमालय का विस्तार काली नदी और तिस्ता नदी के बीच है?",
    options_en: ["Punjab Himalaya", "Kumaon Himalaya", "Nepal Himalaya", "Assam Himalaya"],
    options_hi: ["पंजाब हिमालय", "कुमायूं हिमालय", "नेपाल हिमालय", "असम हिमालय"],
    correct_option_index: 2,
    explanation_en: "The Nepal Himalaya is located between the Kali and Teesta rivers.",
    explanation_hi: "नेपाल हिमालय काली और तिस्ता नदियों के बीच स्थित है।",
  },
  {
    question_en: "Nanda Devi Peak (7817 m) is the highest peak of which Himalayan region?",
    question_hi: "नंदादेवी चोटी (7817 मी.) किस हिमालय क्षेत्र का उच्चतम शिखर है?",
    options_en: ["Punjab Himalaya", "Kumaon Himalaya", "Nepal Himalaya", "Assam Himalaya"],
    options_hi: ["पंजाब हिमालय", "कुमायूं हिमालय", "नेपाल हिमालय", "असम हिमालय"],
    correct_option_index: 1,
    explanation_en: "Nanda Devi Peak is the highest peak of the Kumaon Himalaya.",
    explanation_hi: "नंदादेवी चोटी कुमायूं हिमालय की सबसे ऊँची चोटी है।",
  },
  {
    question_en: "Which hill is not included in the hills of Arunachal Pradesh?",
    question_hi: "अरुणाचल प्रदेश की पहाड़ियों में कौन सी पहाड़ी शामिल नहीं है?",
    options_en: ["Patkai Bum", "Daphla", "Miri", "Naga Hills"],
    options_hi: ["पटकोई बूम", "डाफला", "मिरी", "नागा हिल्स"],
    correct_option_index: 3,
    explanation_en: "Naga Hills are located in Nagaland, while Daphla, Miri, Abor, Mishmi, and Patkai Bum are hills of Arunachal Pradesh.",
    explanation_hi: "नागा हिल्स (नागालैंड) में स्थित हैं, जबकि डाफला, मिरी, अबोर, मिश्मी, और पटकोई बूम अरुणाचल प्रदेश की पहाड़ियाँ हैं।",
  },
  {
    question_en: "Which pass connects Srinagar and Leh?",
    question_hi: "श्रीनगर और लेह को कौन सा दर्रा (Pass) जोड़ता है?",
    options_en: ["Banihal Pass", "Pir Panjal Pass", "Khardungla Pass", "Zojila Pass"],
    options_hi: ["बनिहाल दर्रा", "पीर पंजाल दर्रा", "खारदुंगला दर्रा", "जोजिला दर्रा"],
    correct_option_index: 3,
    explanation_en: "Zojila Pass connects Srinagar to Leh via Kargil.",
    explanation_hi: "जोजिला दर्रा (Zojila pass) श्रीनगर को कारगिल होते हुए लेह से जोड़ता है।",
  },
  {
    question_en: "Through which pass does the Sutlej River enter India?",
    question_hi: "सतलुज नदी भारत में किस दर्रे से होकर प्रवेश करती है?",
    options_en: ["Rohtang Pass", "Baralacha Pass", "Shipkila Pass", "Lipulekh Pass"],
    options_hi: ["रोहतांग दर्रा", "बारालाचा दर्रा", "शिपकीला दर्रा", "लिपुलेख दर्रा"],
    correct_option_index: 2,
    explanation_en: "The Sutlej River enters India through Shipkila Pass.",
    explanation_hi: "सतलुज नदी शिपकीला दर्रे से भारत में प्रवेश करती है।",
  },
  {
    question_en: "Jawahar Tunnel is located in which pass?",
    question_hi: "जवाहर सुरंग किस दर्रे में स्थित है?",
    options_en: ["Zojila Pass", "Banihal Pass", "Burzil Pass", "Pir Panjal Pass"],
    options_hi: ["जोजिला दर्रा", "बनिहाल दर्रा", "बुर्जिल दर्रा", "पीर पंजाल दर्रा"],
    correct_option_index: 1,
    explanation_en: "Jawahar Tunnel is located in Banihal Pass (Jammu and Kashmir).",
    explanation_hi: "जवाहर सुरंग बनिहाल दर्रे (जम्मू-कश्मीर) में स्थित है।",
  },
  {
    question_en: "Which is the country's highest motorable pass, located in Ladakh?",
    question_hi: "देश का सबसे ऊँचा मोटर योग्य दर्रा (Highest Motorable pass) कौन सा है, जो लद्दाख में स्थित है?",
    options_en: ["Khardungla Pass", "Baralacha Pass", "Niti Pass", "Umling-la Pass"],
    options_hi: ["खारदुंगला दर्रा", "बारालाचा दर्रा", "नीति दर्रा", "उमलिंग-ला दर्रा (Umling-la pass)"],
    correct_option_index: 3,
    explanation_en: "Umling-la Pass is the country's highest motorable pass.",
    explanation_hi: "उमलिंग-ला दर्रा देश का सबसे ऊँचा मोटर योग्य दर्रा है।",
  },
  {
    question_en: "Which is the oldest mountain range in India?",
    question_hi: "भारत की सबसे पुरानी पर्वत श्रृंखला कौन सी है?",
    options_en: ["Vindhyachal", "Satpura", "Himalaya", "Aravalli"],
    options_hi: ["विंध्याचल", "सतपुड़ा", "हिमालय", "अरावली"],
    correct_option_index: 3,
    explanation_en: "The Aravalli mountain range is the oldest mountain range in India.",
    explanation_hi: "अरावली पर्वत श्रृंखला भारत की सबसे प्राचीन पर्वत श्रृंखला है।",
  },
  {
    question_en: "What is the height of 'Guru Shikhar', the highest peak of Aravalli?",
    question_hi: "अरावली की सबसे ऊँची चोटी 'गुरु शिखर' की ऊँचाई कितनी है?",
    options_en: ["1500 meters", "1722 meters", "2695 meters", "1450 meters"],
    options_hi: ["1500 मीटर", "1722 मीटर", "2695 मीटर", "1450 मीटर"],
    correct_option_index: 1,
    explanation_en: "The height of Guru Shikhar (Mount Abu, Rajasthan) is 1722 meters.",
    explanation_hi: "गुरु शिखर (माउंट आबू, राजस्थान) की ऊँचाई 1722 मीटर है।",
  },
  {
    question_en: "Which is the highest peak of the Vindhyachal mountain range?",
    question_hi: "विंध्याचल पर्वत श्रेणी का सबसे ऊँचा शिखर कौन सा है?",
    options_en: ["Guru Shikhar", "Dhupgarh", "Amarkantak", "Goodwill peak"],
    options_hi: ["गुरु शिखर", "धूपगढ़", "अमरकंटक", "सद्भावना शिखर (Goodwill peak)"],
    correct_option_index: 3,
    explanation_en: "The highest peak of the Vindhyachal mountain is Goodwill Peak (Sadbhavna Shikhar).",
    explanation_hi: "विंध्याचल पर्वत का सबसे ऊँचा शिखर सद्भावना शिखर (Goodwill peak) है।",
  },
  {
    question_en: "The Satpura mountain is situated between which two rivers?",
    question_hi: "सतपुड़ा पर्वत किन दो नदियों के बीच स्थित है?",
    options_en: ["Mahanadi and Godavari", "Ganga and Yamuna", "Narmada and Tapi", "Krishna and Kaveri"],
    options_hi: ["महानदी और गोदावरी", "गंगा और यमुना", "नर्मदा और तापी", "कृष्णा और कावेरी"],
    correct_option_index: 2,
    explanation_en: "The Satpura mountain range is situated between the Narmada and Tapi rivers.",
    explanation_hi: "सतपुड़ा पर्वत श्रेणी नर्मदा और तापी नदियों के बीच स्थित है।",
  },
  {
    question_en: "Anai Mudi, the highest peak of Peninsular India, is located on which hill?",
    question_hi: "प्रायद्वीपीय भारत की सबसे ऊँची चोटी अनाईमुदी किस पहाड़ी पर स्थित है?",
    options_en: ["Nilgiri Hills", "Mahendragiri", "Annamalai Hills", "Cardamom Hills"],
    options_hi: ["नीलगिरि हिल्स", "महेंद्रगिरि", "अन्नामलाई हिल्स", "कार्डामम हिल्स"],
    correct_option_index: 2,
    explanation_en: "Anai Mudi (2695 m) is located on the Annamalai Hills.",
    explanation_hi: "अनाईमुदी (2695 मी) अन्नामलाई हिल्स पर स्थित है।",
  },
  {
    question_en: "In which state is the highest peak of the Eastern Ghats, Zindagada, located?",
    question_hi: "पूर्वी घाट की सबसे ऊँची चोटी जिंदागाढ़ा किस राज्य में स्थित है?",
    options_en: ["Tamil Nadu", "Odisha", "Andhra Pradesh", "Karnataka"],
    options_hi: ["तमिलनाडु", "ओडिशा", "आंध्र प्रदेश", "कर्नाटक"],
    correct_option_index: 2,
    explanation_en: "Zindagada (1690 m) is the highest peak of the Eastern Ghats and is located in the Araku Valley of Andhra Pradesh.",
    explanation_hi: "ज़िंदागाढ़ा (1690 मी) पूर्वी घाट की सबसे ऊँची चोटी है और आंध्र प्रदेश के अराकु घाटी में स्थित है।",
  }
];

export default test1Questions;
