import type { QuizQuestion } from '../../../types';

const test5Questions: QuizQuestion[] = [
  {
    question_en: "The Indian Standard Time (IST) line and the Tropic of Cancer intersect in which state?",
    question_hi: "भारतीय मानक समय रेखा (IST) और कर्क रेखा किस राज्य में एक दूसरे को काटती हैं?",
    options_en: ["Uttar Pradesh", "Madhya Pradesh", "Odisha", "Chhattisgarh"],
    options_hi: ["उत्तर प्रदेश", "मध्य प्रदेश", "ओडिशा", "छत्तीसगढ़"],
    correct_option_index: 3,
    explanation_en: "The Tropic of Cancer and the Indian Standard Time line intersect each other in Chhattisgarh.",
    explanation_hi: "कर्क रेखा और भारतीय मानक समय रेखा एक दूसरे को छत्तीसगढ़ में काटती हैं।",
  },
  {
    question_en: "Which district of Puducherry, located in Kerala, is the smallest district of India by area?",
    question_hi: "क्षेत्रफल के अनुसार, भारत का सबसे छोटा जिला (Smallest District by Area) केरल में स्थित पुडुचेरी का कौन सा जिला है?",
    options_en: ["Yanam", "Karaikal", "Puducherry", "Mahe"],
    options_hi: ["यनम (Yanam)", "कराईकल (Karaikal)", "पुडुचेरी (Puducherry)", "माहे (Mahe)"],
    correct_option_index: 3,
    explanation_en: "Mahe is a district of Puducherry located in Kerala, and it is the smallest district in India by area.",
    explanation_hi: "माहे पुडुचेरी का एक जिला है जो केरल में स्थित है, और यह भारत का सबसे छोटा जिला है।",
  },
  {
    question_en: "The four districts of Puducherry are spread across a total of how many states of India?",
    question_hi: "पुडुचेरी के चार जिले भारत के कुल कितने राज्यों में फैले हुए हैं?",
    options_en: ["2 states", "3 states", "4 states", "1 state"],
    options_hi: ["2 राज्यों में", "3 राज्यों में", "4 राज्यों में", "1 राज्य में"],
    correct_option_index: 1,
    explanation_en: "The districts of Puducherry are Yanam (Andhra Pradesh), Karaikal (Tamil Nadu), Puducherry (Tamil Nadu), and Mahe (Kerala), spread across 3 states.",
    explanation_hi: "पुडुचेरी के जिले यनम (आंध्र प्रदेश), कराईकल (तमिलनाडु), पुडुचेरी (तमिलनाडु) और माहे (केरल) 3 राज्यों में फैले हैं।",
  },
  {
    question_en: "Which is the largest district of India by area?",
    question_hi: "क्षेत्रफल के अनुसार भारत का सबसे बड़ा जिला कौन सा है?",
    options_en: ["Leh", "Jaisalmer", "Barmer", "Kutch"],
    options_hi: ["लेह", "जैसलमेर", "बाड़मेर", "कच्छ (Kutch)"],
    correct_option_index: 3,
    explanation_en: "Kutch (Gujarat) is at the first position among the 5 largest districts of India, followed by Leh.",
    explanation_hi: "भारत के 5 सबसे बड़े जिलों में कच्छ (गुजरात) पहले स्थान पर है, इसके बाद लेह आता है।",
  },
  {
    question_en: "In which hemisphere is India located?",
    question_hi: "भारत पृथ्वी के किस गोलार्ध (Hemisphere) में स्थित है?",
    options_en: ["Southern Hemisphere", "Western Hemisphere", "North-East Hemisphere", "North-West Hemisphere"],
    options_hi: ["दक्षिणी गोलार्ध", "पश्चिमी गोलार्ध", "उत्तरी-पूर्वी गोलार्ध (North-East Hemisphere)", "उत्तरी-पश्चिमी गोलार्ध"],
    correct_option_index: 2,
    explanation_en: "India is located in the North-East Hemisphere, north of the equator and east of Greenwich.",
    explanation_hi: "भारत विषुवत रेखा के उत्तर और ग्रीनविच के पूर्व में, उत्तरी-पूर्वी गोलार्ध में स्थित है।",
  },
  {
    question_en: "Kanyakumari, the southernmost point of the Indian mainland, is located at how many degrees North Latitude?",
    question_hi: "भारत की मुख्य भूमि का सबसे दक्षिणी बिंदु (Mainland Southernmost Point) कन्याकुमारी कितने उत्तरी अक्षांश पर स्थित है?",
    options_en: ["6°4′ North Latitude", "68°7′ East Longitude", "8°4′ North Latitude", "97°25′ East Longitude"],
    options_hi: ["6°4′ उत्तरी अक्षांश", "68°7′ पूर्वी देशांतर", "8°4′ उत्तरी अक्षांश", "97°25′ पूर्वी देशांतर"],
    correct_option_index: 2,
    explanation_en: "The mainland of India extends up to Kanyakumari (Cape Comorin), which is located at 8°4′ North Latitude.",
    explanation_hi: "भारत की मुख्य भूमि का विस्तार कन्याकुमारी (केप कोमोरिन) तक है, जो 8°4′ उत्तरी अक्षांश पर स्थित है।",
  },
  {
    question_en: "When was the national anthem of Bangladesh, 'Amar Sonar Bangla', adopted?",
    question_hi: "बांग्लादेश का राष्ट्रीय गान 'अमर सोनार बांग्ला' (Amar Sonar Bangla) कब अपनाया गया था?",
    options_en: ["August 15, 1947", "October 1, 1949", "March 26, 1971", "August 19, 1919"],
    options_hi: ["15 अगस्त 1947", "1 अक्टूबर 1949", "26 मार्च 1971", "19 अगस्त 1919"],
    correct_option_index: 2,
    explanation_en: "Bangladesh's Independence Day (and the adoption of the anthem) is March 26, 1971.",
    explanation_hi: "बांग्लादेश का स्वतंत्रता दिवस (और गान) 26 मार्च 1971 है।",
  },
  {
    question_en: "By what name is the Parliament of Pakistan known?",
    question_hi: "पाकिस्तान की संसद को किस नाम से जाना जाता है?",
    options_en: ["Jatiya Sangsad", "Senate", "Shura", "National Assembly"],
    options_hi: ["जातीय संसद", "सीनेट", "शोरा", "नेशनल असेंबली (National Assembly)"],
    correct_option_index: 3,
    explanation_en: "The Parliament of Pakistan is called the National Assembly.",
    explanation_hi: "पाकिस्तान की संसद को नेशनल असेंबली कहा जाता है।",
  },
  {
    question_en: "Which neighboring country's longest river is Irrawaddy?",
    question_hi: "किस पड़ोसी देश की सबसे लंबी नदी (Longest River) इरावदी (Irrawaddy) है?",
    options_en: ["Bhutan", "Nepal", "Myanmar", "China"],
    options_hi: ["भूटान", "नेपाल", "म्यांमार", "चीन"],
    correct_option_index: 2,
    explanation_en: "The Irrawaddy is the longest river in Myanmar.",
    explanation_hi: "म्यांमार की सबसे लंबी नदी इरावदी है।",
  },
  {
    question_en: "Which is the longest river in Bhutan?",
    question_hi: "भूटान की सबसे लंबी नदी कौन सी है?",
    options_en: ["Irrawaddy", "Karnali", "Mahaweli Ganga", "Manas River"],
    options_hi: ["इरावदी", "करनाली", "महावेली गंगा", "मानस नदी (Manas River)"],
    correct_option_index: 3,
    explanation_en: "The longest river in Bhutan is the Manas River.",
    explanation_hi: "भूटान की सबसे लंबी नदी मानस नदी है।",
  },
  {
    question_en: "Which is the longest river in Sri Lanka?",
    question_hi: "श्रीलंका की सबसे लंबी नदी कौन सी है?",
    options_en: ["Yangtze River", "Karnali", "Padma", "Mahaweli Ganga"],
    options_hi: ["यांग्त्सीक्यांग", "करनाली", "पद्मा", "महावेली गंगा (Mahaveli Ganga)"],
    correct_option_index: 3,
    explanation_en: "The longest river in Sri Lanka is the Mahaweli Ganga.",
    explanation_hi: "श्रीलंका की सबसे लंबी नदी महावेली गंगा है।",
  },
  {
    question_en: "What is the capital of Maldives?",
    question_hi: "मालदीव की राजधानी क्या है?",
    options_en: ["Sri Jayawardenepura Kotte", "Dhaka", "Thimphu", "Male"],
    options_hi: ["श्री जयवर्धनेपुरा कोट्टे", "ढाका", "थिम्पू", "माले (Male)"],
    correct_option_index: 3,
    explanation_en: "The capital of Maldives is Male.",
    explanation_hi: "मालदीव की राजधानी माले है।",
  },
  {
    question_en: "Duncan Pass is situated between which two Andaman Islands?",
    question_hi: "डंकन पास (Duncan Pass) किन दो अंडमान द्वीपों के बीच स्थित है?",
    options_en: ["North Andaman and Middle Andaman", "Car Nicobar and Little Nicobar", "South Andaman and Little Andaman", "Great Nicobar and Sumatra"],
    options_hi: ["उत्तरी अंडमान और मध्य अंडमान", "कार निकोबार और लघु निकोबार", "दक्षिणी अंडमान और लघु अंडमान", "ग्रेट निकोबार और सुमात्रा"],
    correct_option_index: 2,
    explanation_en: "Duncan Pass is situated between South Andaman and Little Andaman.",
    explanation_hi: "डंकन पास दक्षिणी अंडमान और लघु अंडमान के मध्य स्थित है।",
  },
  {
    question_en: "Narcondam Island is an example of the Andaman and Nicobar Islands. What type of volcano is it?",
    question_hi: "नारकोंडम द्वीप (Narcondam Island) अंडमान निकोबार द्वीप समूह का एक उदाहरण है, यह किस प्रकार का ज्वालामुखी है?",
    options_en: ["Active Volcano", "Dormant Volcano", "Extinct Volcano", "Shield Volcano"],
    options_hi: ["सक्रिय ज्वालामुखी (Active Volcano)", "सुषुप्त ज्वालामुखी (Dormant Volcano)", "मृत ज्वालामुखी (Extinct Volcano)", "ढाल ज्वालामुखी"],
    correct_option_index: 1,
    explanation_en: "Narcondam Island is a dormant volcano.",
    explanation_hi: "नारकोंडम द्वीप एक सुषुप्त ज्वालामुखी है।",
  },
  {
    question_en: "Which channel separates Lakshadweep and Minicoy?",
    question_hi: "लक्षद्वीप और मिनिकॉय को कौन सा चैनल अलग करता है?",
    options_en: ["8° Channel", "Duncan Pass", "Grand Channel", "9° Channel"],
    options_hi: ["8° डिग्री चैनल", "डंकन पास", "ग्रैंड चैनल", "9° डिग्री चैनल"],
    correct_option_index: 3,
    explanation_en: "The 9° Channel separates Lakshadweep and Minicoy Island.",
    explanation_hi: "9° डिग्री चैनल लक्षद्वीप और मिनिकॉय द्वीप को अलग करता है।",
  },
  {
    question_en: "What is the new name of Wheeler Island?",
    question_hi: "व्हीलर द्वीप (Wheeler Island) का नया नाम क्या है?",
    options_en: ["Havelock Island", "Neil Island", "Ross Island", "Abdul Kalam Island"],
    options_hi: ["हैवलाक द्वीप", "नील द्वीप", "रॉस द्वीप", "अब्दुल कलाम द्वीप"],
    correct_option_index: 3,
    explanation_en: "The new name of Wheeler Island is Abdul Kalam Island.",
    explanation_hi: "व्हीलर द्वीप का नया नाम अब्दुल कलाम द्वीप है।",
  },
  {
    question_en: "On which island is the city of Mumbai located?",
    question_hi: "मुंबई शहर किस द्वीप पर स्थित है?",
    options_en: ["Minicoy Island", "Wheeler Island", "Salsette Island", "Elephanta Island"],
    options_hi: ["मिनिकॉय द्वीप", "व्हीलर द्वीप", "सालसेट द्वीप (Salsette Island)", "एलिफेंटा द्वीप"],
    correct_option_index: 2,
    explanation_en: "The city of Mumbai is located on Salsette Island.",
    explanation_hi: "मुंबई शहर सालसेट द्वीप पर स्थित है।",
  },
  {
    question_en: "Pamban Island is situated between which two regions?",
    question_hi: "पंबन द्वीप (Pamban Island) किन दो क्षेत्रों के बीच स्थित है?",
    options_en: ["Lakshadweep and Minicoy", "India and Sri Lanka", "Andaman and Nicobar", "Coco Island and North Andaman"],
    options_hi: ["लक्षद्वीप और मिनिकॉय", "भारत और श्रीलंका", "अंडमान और निकोबार", "कोको द्वीप और उत्तरी अंडमान"],
    correct_option_index: 1,
    explanation_en: "Pamban Island (Rameswaram Island) is located in the Gulf of Mannar between India and Sri Lanka.",
    explanation_hi: "पंबन द्वीप (रामेश्वरम द्वीप) मन्नार की खाड़ी में भारत और श्रीलंका के बीच स्थित है।",
  },
  {
    question_en: "In which geological period did Pangaea break into two parts (Angaraland and Gondwanaland)?",
    question_hi: "पेंजिया (Pangaea) किस भूवैज्ञानिक काल (Geological period) में दो भागों (अंगारालैंड और गोंडवानालैंड) में टूट गया था?",
    options_en: ["Mesozoic Era", "Pre-Cambrian Eon", "Carboniferous Period", "Pleistocene Epoch"],
    options_hi: ["मेसोजोइक युग", "प्री-कैम्ब्रियन कल्प", "कार्बोनिफेरस युग (Carboniferous Period)", "प्लेस्टोसीन काल"],
    correct_option_index: 2,
    explanation_en: "Pangaea broke into two parts during the Carboniferous Period.",
    explanation_hi: "पेंजिया कार्बोनिफेरस युग में दो भागों में टूट गया था।",
  },
  {
    question_en: "What is the average height of the Lesser Himalaya?",
    question_hi: "लघु हिमालय (Lesser Himalaya) की औसत ऊँचाई कितनी है?",
    options_en: ["6100 meters", "600-1200 meters", "3000-4500 meters", "4500-6000 meters"],
    options_hi: ["6100 मीटर", "600-1200 मीटर", "3000-4500 मीटर", "4500-6000 मीटर"],
    correct_option_index: 2,
    explanation_en: "The average height of the Lesser/Middle Himalaya is 3000-4500 meters.",
    explanation_hi: "लघु/मध्य हिमालय की औसत ऊँचाई 3000-4500 मीटर है।",
  },
  {
    question_en: "Which is the northernmost mountain range of the Trans Himalaya?",
    question_hi: "ट्रांस हिमालय (Trans Himalaya) की सबसे उत्तरी पर्वत श्रेणी कौन सी है?",
    options_en: ["Zaskar Range", "Ladakh Range", "Kailash Range", "Karakoram Range"],
    options_hi: ["जास्कर श्रेणी", "लद्दाख श्रेणी", "कैलाश श्रेणी", "कराकोरम श्रेणी (Karakoram Range)"],
    correct_option_index: 3,
    explanation_en: "The Trans Himalaya (Tibetan Himalaya) consists of the Karakoram, Ladakh, Zaskar, and Kailash ranges.",
    explanation_hi: "ट्रांस हिमालय (तिब्बती हिमालय) कराकोरम, लद्दाख, जास्कर और कैलाश श्रेणियों से बना है।",
  },
  {
    question_en: "What is the average breadth of the Great Himalaya?",
    question_hi: "वृहत् हिमालय (Great Himalaya) की औसत चौड़ाई (Average Breadth) कितनी है?",
    options_en: ["50 km", "120 km - 190 km", "200-250 km", "300 km"],
    options_hi: ["50 किमी", "120 किमी - 190 किमी", "200-250 किमी", "300 किमी"],
    correct_option_index: 1,
    explanation_en: "The average breadth of the Great Himalaya is 120-190 km.",
    explanation_hi: "वृहत् हिमालय की औसत चौड़ाई 120-190 किमी है।",
  },
  {
    question_en: "What is the average height of the Shivalik or Outer Himalaya?",
    question_hi: "शिवालिक (Shivalik) या बाह्य हिमालय की औसत ऊँचाई कितनी है?",
    options_en: ["3000-4500 meters", "4500-6000 meters", "600-1200 meters", "1500-1800 meters"],
    options_hi: ["3000-4500 मीटर", "4500-6000 मीटर", "600-1200 मीटर", "1500-1800 मीटर"],
    correct_option_index: 2,
    explanation_en: "The average height of the Shivalik Himalaya is 600-1200 meters.",
    explanation_hi: "शिवालिक हिमालय की औसत ऊँचाई 600-1200 मीटर है।",
  },
  {
    question_en: "Which fault separates the Lesser/Middle Himalaya from the Shivalik Himalaya?",
    question_hi: "लघु/मध्य हिमालय को शिवालिक हिमालय से कौन सा भ्रंश (Fault) अलग करता है?",
    options_en: ["Indus Tsangpo Structure Zone (ITSZ)", "Main Central Thrust (MCT)", "Main Boundary Fault (MBF)", "Himalayan Frontal Fault (HFF)"],
    options_hi: ["Indus Tsangpo Structure Zone (ITSZ)", "Main Central Thrust (MCT)", "Main Boundary Fault (MBF)", "Himalayan Frontal Fault (HFF)"],
    correct_option_index: 2,
    explanation_en: "The Lesser/Middle Himalaya is separated from the Shivalik Himalaya by the Main Boundary Fault.",
    explanation_hi: "लघु/मध्य हिमालय Main Boundary Fault द्वारा शिवालिक हिमालय से अलग होता है।",
  },
  {
    question_en: "What is the height of Kanchenjunga, the highest peak of the Himalayas located in India?",
    question_hi: "भारत में स्थित हिमालय की सबसे ऊँची चोटी कंचनजंगा (Kanchenjunga) की ऊँचाई कितनी है?",
    options_en: ["8848.86 meters", "8611 meters", "8586 meters", "7817 meters"],
    options_hi: ["8848.86 मीटर", "8611 मीटर", "8586 मीटर", "7817 मीटर"],
    correct_option_index: 2,
    explanation_en: "The height of Kanchenjunga is 8586 meters.",
    explanation_hi: "कंचनजंगा की ऊँचाई 8586 मीटर है।",
  },
  {
    question_en: "Which of the following hills is not included in the hills of Arunachal Pradesh?",
    question_hi: "अरुणाचल प्रदेश की पहाड़ियों में कौन सी पहाड़ी शामिल नहीं है?",
    options_en: ["Daphla", "Miri", "Abor", "Naga Hills"],
    options_hi: ["डाफला", "मिरी", "अबोर", "नागा हिल्स"],
    correct_option_index: 3,
    explanation_en: "Naga Hills are in Nagaland, while Daphla, Miri, Abor, Mishmi, and Patkoi Bum are hills of Arunachal Pradesh.",
    explanation_hi: "नागा हिल्स (नागालैंड) में हैं, जबकि डाफला, मिरी, अबोर, मिश्मी, और पटकोई बूम अरुणाचल प्रदेश की पहाड़ियाँ हैं।",
  },
  {
    question_en: "The Kumaon Himalaya extends between which two rivers?",
    question_hi: "कुमायूं हिमालय (Kumaon Himalaya) का विस्तार किन दो नदियों के बीच है?",
    options_en: ["Indus and Sutlej", "Kali and Teesta", "Teesta and Dihang", "Sutlej and Kali River"],
    options_hi: ["सिंधु और सतलुज", "काली और तिस्ता", "तिस्ता और दिहांग", "सतलुज और काली नदी"],
    correct_option_index: 3,
    explanation_en: "The Kumaon Himalaya stretches between the Sutlej and Kali Rivers (320 km).",
    explanation_hi: "कुमायूं हिमालय सतलुज और काली नदी के बीच (320 किमी) फैला है।",
  },
  {
    question_en: "Which is the highest peak of the Kumaon Himalaya?",
    question_hi: "कुमायूं हिमालय की सबसे ऊँची चोटी कौन सी है?",
    options_en: ["Mount Everest", "Kanchenjunga", "Nandadevi", "Namcha Barwa"],
    options_hi: ["माउंट एवरेस्ट", "कंचनजंगा", "नंदादेवी (Nandadevi)", "नामचा बरवा"],
    correct_option_index: 2,
    explanation_en: "Nandadevi (7817 m) is the highest peak of the Kumaon Himalaya.",
    explanation_hi: "नंदादेवी (7817 मी) कुमायूं हिमालय की सबसे ऊँची चोटी है।",
  },
  {
    question_en: "The Assam Himalaya extends between which two rivers?",
    question_hi: "असम हिमालय (Assam Himalaya) का विस्तार किन दो नदियों के बीच है?",
    options_en: ["Sutlej and Kali River", "Kali and Teesta River", "Teesta and Dihang River", "Indus and Sutlej River"],
    options_hi: ["सतलुज और काली नदी", "काली और तिस्ता नदी", "तिस्ता और दिहांग नदी", "सिंधु और सतलुज नदी"],
    correct_option_index: 2,
    explanation_en: "The Assam Himalaya stretches between the Teesta and Dihang rivers (720 km).",
    explanation_hi: "असम हिमालय तिस्ता और दिहांग नदियों के बीच (720 किमी) फैला है।",
  },
  {
    question_en: "Which pass is also called the 'Land of Passes'?",
    question_hi: "किस दर्रे को 'लैंड ऑफ पासेस' (Land of Passes) भी कहा जाता है?",
    options_en: ["Passes of Uttarakhand", "Passes of Himachal Pradesh", "Passes of Sikkim", "Passes of Ladakh"],
    options_hi: ["उत्तराखंड के दर्रे", "हिमाचल प्रदेश के दर्रे", "सिक्किम के दर्रे", "लद्दाख के दर्रे"],
    correct_option_index: 3,
    explanation_en: "The Ladakh region is also called the 'Land of Passes'.",
    explanation_hi: "लद्दाख क्षेत्र को 'दर्रों की भूमि' (Land of Passes) भी कहा जाता है।",
  },
  {
    question_en: "Which pass connects Srinagar to Gilgit?",
    question_hi: "श्रीनगर को गिलगित से कौन सा दर्रा जोड़ता है?",
    options_en: ["Banihal Pass", "Zojila Pass", "Khardungla Pass", "Burzil Pass"],
    options_hi: ["बनिहाल दर्रा", "जोजिला दर्रा", "खारदुंगला दर्रा", "बुर्जिल दर्रा (Burzil Pass)"],
    correct_option_index: 3,
    explanation_en: "Burzil Pass connects Srinagar to Gilgit.",
    explanation_hi: "बुर्जिल दर्रा श्रीनगर को गिलगित से जोड़ता है।",
  },
  {
    question_en: "Which pass located in Arunachal Pradesh is situated between India and China?",
    question_hi: "अरुणाचल प्रदेश में स्थित वह दर्रा कौन सा है, जो भारत और चीन के बीच स्थित है?",
    options_en: ["Bomdila Pass", "Sela Pass", "Pangsau Pass", "Difu Pass"],
    options_hi: ["बोमडिला दर्रा", "सेला दर्रा", "पांगसाड दर्रा", "दिफू दर्रा (Difu Pass)"],
    correct_option_index: 3,
    explanation_en: "Difu Pass is located at the junction of India, China, and Myanmar.",
    explanation_hi: "दिफू दर्रा भारत, चीन और म्यांमार के जंक्शन पर स्थित है।",
  },
  {
    question_en: "Which pass connects Mumbai to Nashik in Maharashtra?",
    question_hi: "महाराष्ट्र में मुंबई को नासिक से कौन सा दर्रा जोड़ता है?",
    options_en: ["Bhor Ghat Pass", "Pal Ghat Pass", "Shenkotta Pass", "Thal Ghat Pass"],
    options_hi: ["भोर घाट दर्रा", "पाल घाट दर्रा", "सेनकोट्टा दर्रा", "थाल घाट दर्रा (Thal Ghat Pass)"],
    correct_option_index: 3,
    explanation_en: "Thal Ghat Pass connects Mumbai to Nashik.",
    explanation_hi: "थाल घाट दर्रा मुंबई को नासिक से जोड़ता है।",
  },
  {
    question_en: "Palghat Pass is situated between which two hills?",
    question_hi: "पाल घाट दर्रा (Palghat Pass) किन दो पहाड़ियों के बीच स्थित है?",
    options_en: ["Nilgiri and Cardamom Hills", "Palani and Anaimalai Hills", "Shenkotta and Anaimalai Hills", "Nilgiri and Anaimalai Hills"],
    options_hi: ["नीलगिरि और कार्डामम हिल्स", "पालनी और अन्नामलाई हिल्स", "शेनकोट्टा और अन्नामलाई हिल्स", "नीलगिरि और अन्नामलाई हिल्स"],
    correct_option_index: 3,
    explanation_en: "Palghat Pass is situated between the Nilgiri and Anaimalai Hills.",
    explanation_hi: "पाल घाट दर्रा नीलगिरि और अन्नामलाई हिल्स के बीच स्थित है।",
  },
  {
    question_en: "Which is the highest motorable pass in India?",
    question_hi: "भारत का सबसे ऊँचा मोटर योग्य दर्रा (Highest Motorable Pass) कौन सा है?",
    options_en: ["Khardungla Pass", "Banihal Pass", "Mana Pass", "Umling-la pass"],
    options_hi: ["खारदुंगला दर्रा", "बनिहाल दर्रा", "माना दर्रा", "उमलिंग-ला दर्रा (Umling-la pass)"],
    correct_option_index: 3,
    explanation_en: "Umling-la pass is the country's highest motorable pass, located in Ladakh.",
    explanation_hi: "उमलिंग-ला दर्रा देश का सबसे ऊँचा मोटर योग्य दर्रा है, जो लद्दाख में स्थित है।",
  },
  {
    question_en: "The Nubra River originates from which glacier?",
    question_hi: "नुब्रा नदी (Nubra River) का उद्गम किस ग्लेशियर से होता है?",
    options_en: ["Baltoro Glacier", "Rupal Glacier", "Siachen Glacier", "Milam Glacier"],
    options_hi: ["बाल्टोरो ग्लेशियर", "रूपाल ग्लेशियर", "सियाचिन ग्लेशियर", "मिलाम ग्लेशियर"],
    correct_option_index: 2,
    explanation_en: "The Nubra River originates from the Siachen Glacier.",
    explanation_hi: "नुब्रा नदी का उद्गम सियाचिन ग्लेशियर से होता है।",
  },
  {
    question_en: "What are 'Duns' located in Uttarakhand?",
    question_hi: "उत्तराखंड में स्थित ‘दून’ (Duns) क्या हैं?",
    options_en: ["A type of soil", "Longitudinal valleys between Shivalik and Lesser Himalaya", "A seasonal wind", "Mountain meadows"],
    options_hi: ["एक प्रकार की मिट्टी", "शिवालिक और लघु हिमालय के बीच की अनुदैर्ध्य घाटियाँ", "एक मौसमी हवा", "पर्वतीय घास के मैदान"],
    correct_option_index: 1,
    explanation_en: "The valley situated between Shivalik and Lesser Himalaya is called Dun (e.g., Dehradun).",
    explanation_hi: "शिवालिक और लघु हिमालय के बीच स्थित घाटी को दून (जैसे देहरादून) कहा जाता है।",
  },
  {
    question_en: "Kashmir Valley is situated between which two mountain ranges?",
    question_hi: "कश्मीर घाटी (Kashmir Valley) किन दो पर्वत श्रृंखलाओं के बीच स्थित है?",
    options_en: ["Karakoram and Pir Panjal", "Great Himalaya and Ladakh", "Shivalik and Dhauladhar", "Great Himalaya and Pir Panjal"],
    options_hi: ["कराकोरम और पीर पंजाल", "वृहत् हिमालय और लद्दाख", "शिवालिक और धौलाधार", "वृहत् हिमालय और पीर पंजाल"],
    correct_option_index: 3,
    explanation_en: "Kashmir Valley is situated between the Great Himalaya and Pir Panjal.",
    explanation_hi: "कश्मीर घाटी वृहत् हिमालय और पीर पंजाल के बीच स्थित है।",
  },
  {
    question_en: "What is the estimated age of the Aravalli mountain range?",
    question_hi: "अरावली पर्वत की आयु लगभग कितनी मानी जाती है?",
    options_en: ["150 million years", "350 million years", "600 million years", "570 million years"],
    options_hi: ["150 मिलियन वर्ष", "350 मिलियन वर्ष", "600 मिलियन वर्ष", "570 मिलियन वर्ष"],
    correct_option_index: 3,
    explanation_en: "The estimated age of the Aravalli mountain is approximately 570 million years.",
    explanation_hi: "अरावली पर्वत की अनुमानित आयु लगभग 570 मिलियन वर्ष है।",
  },
  {
    question_en: "Where is the highest peak of the Vindhyachal mountain range, Goodwill Peak, located?",
    question_hi: "विंध्याचल पर्वत श्रेणी का सबसे ऊँचा शिखर सद्भावना शिखर (Goodwill Peak) कहाँ स्थित है?",
    options_en: ["Madhya Pradesh", "Gujarat", "Rajasthan", "Uttar Pradesh"],
    options_hi: ["मध्य प्रदेश", "गुजरात", "राजस्थान", "उत्तर प्रदेश"],
    correct_option_index: 3,
    explanation_en: "Goodwill Peak is located in Uttar Pradesh.",
    explanation_hi: "सद्भावना शिखर उत्तर प्रदेश में स्थित है।",
  },
  {
    question_en: "The Satpura mountain range is an example of which type of mountain?",
    question_hi: "सतपुड़ा पर्वत श्रेणी किस प्रकार के पर्वत का उदाहरण है?",
    options_en: ["Fold Mt.", "Residual Mt.", "Block Mt.", "Volcanic Mt."],
    options_hi: ["वलित पर्वत (Fold Mt.)", "अवशिष्ट पर्वत (Residual Mt.)", "ब्लॉक पर्वत (Block Mt.)", "ज्वालामुखी पर्वत"],
    correct_option_index: 2,
    explanation_en: "The Satpura mountain range is an example of a Block mountain.",
    explanation_hi: "सतपुड़ा पर्वत श्रेणी ब्लॉक पर्वत का उदाहरण है।",
  },
  {
    question_en: "Anamudi, the highest peak of Peninsular India, is located on which mountain range?",
    question_hi: "प्रायद्वीपीय भारत का उच्चतम शिखर अनाईमुदी (Anamudi) किस पर्वत श्रेणी पर स्थित है?",
    options_en: ["Nilgiri Hills", "Cardamom Hills", "Anaimalai Hills", "Javadi Hills"],
    options_hi: ["नीलगिरि हिल्स", "कार्डामम हिल्स", "अन्नामलाई हिल्स", "जावडी हिल्स"],
    correct_option_index: 2,
    explanation_en: "Anamudi (2695 m) is located on the Anaimalai Hills.",
    explanation_hi: "अनाईमुदी (2695 मी) अन्नामलाई हिल्स पर स्थित है।",
  },
  {
    question_en: "Which parallel line divides the Western Ghats (Sahyadri) into North Sahyadri and South Sahyadri?",
    question_hi: "किस अक्षांश रेखा द्वारा पश्चिमी घाट (सह्याद्री) को उत्तरी सह्याद्री और दक्षिणी सह्याद्री में विभाजित किया जाता है?",
    options_en: ["8° North Latitude", "23½° North Latitude", "16° North Latitude", "10° North Latitude"],
    options_hi: ["8° उत्तरी अक्षांश", "23½° उत्तरी अक्षांश", "16° उत्तरी अक्षांश", "10° उत्तरी अक्षांश"],
    correct_option_index: 2,
    explanation_en: "The Western Ghats are divided by the 16° North Latitude line, which passes through Goa.",
    explanation_hi: "पश्चिमी घाट को 16° उत्तरी अक्षांश रेखा (जो गोवा से होकर गुजरती है) द्वारा विभाजित किया जाता है।",
  },
  {
    question_en: "The Western Ghats and Eastern Ghats meet at which hill?",
    question_hi: "पश्चिमी घाट और पूर्वी घाट किस पहाड़ी पर मिलते हैं?",
    options_en: ["Anaimalai Hills", "Cardamom Hills", "Palani Hills", "Nilgiri Hills"],
    options_hi: ["अन्नामलाई हिल्स", "कार्डामम हिल्स", "पलानी हिल्स", "नीलगिरि हिल्स"],
    correct_option_index: 3,
    explanation_en: "The Western Ghats and Eastern Ghats meet at the Nilgiri Hills (Tamil Nadu, Karnataka, Kerala).",
    explanation_hi: "पश्चिमी घाट और पूर्वी घाट नीलगिरि हिल्स (तमिलनाडु, कर्नाटक, केरल) पर मिलते हैं।",
  },
  {
    question_en: "In which state is the Malabar Coast located?",
    question_hi: "मालाबार तट (Malabar Coast) का विस्तार किस राज्य में है?",
    options_en: ["Gujarat", "Maharashtra", "Goa", "Kerala"],
    options_hi: ["गुजरात", "महाराष्ट्र", "गोवा", "केरल"],
    correct_option_index: 3,
    explanation_en: "The Malabar Coast runs parallel to the coast of Kerala.",
    explanation_hi: "मालाबार तट केरल के तट के समानांतर चलता है।",
  },
  {
    question_en: "Which is the smallest river in India?",
    question_hi: "भारत की सबसे छोटी नदी (Smallest River in India) कौन सी है?",
    options_en: ["Mahi", "Pennar", "Arvari", "Vaigai"],
    options_hi: ["माही", "पेन्नार", "अरवरी (Arvari)", "वैगई"],
    correct_option_index: 2,
    explanation_en: "Arvari is mentioned as the smallest river in India in the source.",
    explanation_hi: "स्रोत में अरवरी को भारत की सबसे छोटी नदी बताया गया है।",
  },
  {
    question_en: "Yamuna is the largest and western tributary of the Ganga. Where does it originate?",
    question_hi: "यमुना नदी गंगा की सबसे बड़ी और पश्चिमी सहायक नदी है, इसका उद्गम कहाँ से होता है?",
    options_en: ["Gangotri Glacier", "Kedarnath", "Milam Glacier", "Yamunotri Glacier (Bandarpunch Peak)"],
    options_hi: ["गंगोत्री ग्लेशियर", "केदारनाथ", "मिलाम ग्लेशियर", "यमुनोत्री ग्लेशियर (बंदरपूंछ चोटी)"],
    correct_option_index: 3,
    explanation_en: "The Yamuna originates from Bandarpunch peak located at Yamunotri Glacier.",
    explanation_hi: "यमुना का उद्गम यमुनोत्री ग्लेशियर पर स्थित बंदरपूंछ चोटी से होता है।",
  },
  {
    question_en: "The Chambal River originates from Mhow near which mountain range?",
    question_hi: "चंबल नदी का उद्गम किस पर्वत श्रृंखला के पास मऊ (Mhow) से होता है?",
    options_en: ["Aravalli", "Vindhyachal", "Satpura", "Janapav Hills"],
    options_hi: ["अरावली", "विंध्याचल", "सतपुड़ा", "जनापाव पहाड़ियाँ"],
    correct_option_index: 3,
    explanation_en: "The Chambal River originates from Janapav Hills (Mhow, MP).",
    explanation_hi: "चंबल नदी का उद्गम जनापाव पहाड़ियों (मऊ, MP) से होता है।",
  },
  {
    question_en: "Which river is known as 'Jamuna' in Bangladesh?",
    question_hi: "किस नदी को बांग्लादेश में 'जमुना' (Jamuna) नाम से जाना जाता है?",
    options_en: ["Ganga River", "Indus River", "Brahmaputra River", "Mahanadi"],
    options_hi: ["गंगा नदी", "सिंधु नदी", "ब्रह्मपुत्र नदी", "महानदी"],
    correct_option_index: 2,
    explanation_en: "The Brahmaputra River is known as Jamuna in Bangladesh.",
    explanation_hi: "ब्रह्मपुत्र नदी को बांग्लादेश में जमुना नाम से जाना जाता है।",
  },
  {
    question_en: "Between which mountain ranges does the Indus River flow in the north-west direction?",
    question_hi: "सिंधु नदी किन पर्वत श्रेणियों के बीच उत्तर-पश्चिम दिशा में बहती है?",
    options_en: ["Karakoram and Kailash", "Pir Panjal and Dhauladhar", "Ladakh and Zaskar", "Great Himalaya and Shivalik"],
    options_hi: ["कराकोरम और कैलाश", "पीर पंजाल और धौलाधार", "लद्दाख और जास्कर", "वृहत् हिमालय और शिवालिक"],
    correct_option_index: 2,
    explanation_en: "The Indus River flows in the north-west direction between the Ladakh and Zaskar mountain ranges.",
    explanation_hi: "सिंधु नदी लद्दाख और जास्कर पर्वत श्रेणियों के बीच उत्तर-पश्चिम दिशा में बहती है।",
  },
  {
    question_en: "What is the ancient name of the Chenab River?",
    question_hi: "चिनाब नदी (Chenab River) का प्राचीन नाम क्या है?",
    options_en: ["Vitasta", "Parushni", "Vipasha", "Askini"],
    options_hi: ["वितस्ता", "परुष्णी", "विपाशा", "अस्किनी (Askini)"],
    correct_option_index: 3,
    explanation_en: "The old name of the Chenab River is Askini.",
    explanation_hi: "चिनाब नदी का पुराना नाम अस्किनी है।",
  },
  {
    question_en: "The Ravi River originates from which pass in Himachal Pradesh?",
    question_hi: "रावी नदी (Ravi River) का उद्गम हिमाचल प्रदेश के किस दर्रे से होता है?",
    options_en: ["Shipkila Pass", "Baralacha Pass", "Lipulekh Pass", "Rohtang Pass"],
    options_hi: ["शिपकीला दर्रा", "बारालाचा दर्रा", "लिपुलेख दर्रा", "रोहतांग दर्रा"],
    correct_option_index: 3,
    explanation_en: "The Ravi River originates near the Rohtang Pass.",
    explanation_hi: "रावी नदी का उद्गम रोहतांग दर्रे के पास से होता है।",
  },
  {
    question_en: "By what name is the Doab located between the Beas and Sutlej rivers known?",
    question_hi: "व्यास और सतलुज नदियों के बीच स्थित दोआब को किस नाम से जाना जाता है?",
    options_en: ["Rachna Doab", "Chaj Doab", "Sindh Sagar Doab", "Bist Doab"],
    options_hi: ["रचना दोआब", "चज दोआब", "सिंध सागर दोआब", "बिस्त दोआब (Bist Doab)"],
    correct_option_index: 3,
    explanation_en: "The area between Beas and Sutlej is called Bist Doab.",
    explanation_hi: "व्यास और सतलुज के बीच के क्षेत्र को बिस्त दोआब कहा जाता है।",
  },
  {
    question_en: "By what name is the Doab located between the Ravi and Chenab rivers known?",
    question_hi: "रावी और चिनाब नदियों के बीच स्थित दोआब को किस नाम से जाना जाता है?",
    options_en: ["Chaj Doab", "Bari Doab", "Rachna Doab", "Bist Doab"],
    options_hi: ["चज दोआब", "बारी दोआब", "रचना दोआब (Rachna Doab)", "बिस्त दोआब"],
    correct_option_index: 2,
    explanation_en: "The area between Ravi and Chenab is called Rachna Doab.",
    explanation_hi: "रावी और चिनाब के बीच के क्षेत्र को रचना दोआब कहा जाता है।",
  },
  {
    question_en: "Where does the Godavari River originate?",
    question_hi: "गोदावरी नदी का उद्गम कहाँ से होता है?",
    options_en: ["Amarkantak", "Brahmagiri Hills", "Mahabaleshwar", "Trimbakeshwar"],
    options_hi: ["अमरकंटक", "ब्रह्मगिरि पहाड़ियाँ", "महाबलेश्वर", "त्र्यंबकेश्वर (Trimbakeshwar)"],
    correct_option_index: 3,
    explanation_en: "The Godavari River originates from Trimbakeshwar (Nashik district, Maharashtra).",
    explanation_hi: "गोदावरी नदी का उद्गम त्र्यंबकेश्वर (नासिक जिला, महाराष्ट्र) से होता है।",
  },
  {
    question_en: "Krishna River is the second longest river of Peninsular India. Where does it originate?",
    question_hi: "कृष्णा नदी प्रायद्वीपीय भारत की दूसरी सबसे लंबी नदी है, इसका उद्गम कहाँ से होता है?",
    options_en: ["Trimbakeshwar", "Brahmagiri Hills", "Mahabaleshwar", "Sihawa Hill"],
    options_hi: ["त्र्यंबकेश्वर", "ब्रह्मगिरि पहाड़ियाँ", "महाबलेश्वर", "सिहावा पहाड़ी"],
    correct_option_index: 2,
    explanation_en: "The Krishna River originates from Mahabaleshwar (Western Ghats, Maharashtra).",
    explanation_hi: "कृष्णा नदी का उद्गम महाबलेश्वर (पश्चिमी घाट, महाराष्ट्र) से होता है।",
  },
  {
    question_en: "Which river is also known as 'Uthal Pinakini'?",
    question_hi: "किस नदी को 'उत्थल पिनाकिनी' (Uthal Pinakini) नाम से भी जाना जाता है?",
    options_en: ["Vaigai River", "Kaveri River", "Krishna River", "Pennar River"],
    options_hi: ["वैगई नदी", "कावेरी नदी", "कृष्णा नदी", "पेन्नार नदी (Pennar River)"],
    correct_option_index: 3,
    explanation_en: "Another name for the Pennar River is Uthal Pinakini.",
    explanation_hi: "पेन्नार नदी का अन्य नाम उत्थल पिनाकिनी है।",
  },
  {
    question_en: "Why does the Kaveri River have water throughout the year?",
    question_hi: "कावेरी नदी में साल भर पानी क्यों रहता है?",
    options_en: ["Because it is a Himalayan river", "It is the only perennial river in Peninsular India", "It falls into the Bay of Bengal", "It is an inland river"],
    options_hi: ["हिमालयी नदी होने के कारण", "यह प्रायद्वीपीय भारत की एकमात्र बारहमासी नदी है", "यह बंगाल की खाड़ी में गिरती है", "यह एक अंतर्देशीय नदी है"],
    correct_option_index: 1,
    explanation_en: "The Kaveri River is the only perennial river in Peninsular India.",
    explanation_hi: "कावेरी नदी प्रायद्वीपीय भारत की एकमात्र बारहमासी नदी है।",
  },
  {
    question_en: "Narmada River is the 5th largest river of India. To the south of which mountain range does it flow?",
    question_hi: "नर्मदा नदी भारत की 5वीं सबसे बड़ी नदी है, यह किस पर्वत श्रेणी के दक्षिण में होकर बहती है?",
    options_en: ["Satpura", "Aravalli", "Vindhyachal", "Western Ghats"],
    options_hi: ["सतपुड़ा", "अरावली", "विंध्याचल", "पश्चिमी घाट"],
    correct_option_index: 2,
    explanation_en: "The Narmada River flows south of the Vindhyachal range and north of the Satpura range.",
    explanation_hi: "नर्मदा नदी विंध्याचल पर्वत के दक्षिण में और सतपुड़ा के उत्तर में बहती है।",
  },
  {
    question_en: "Panaji, the capital of Goa, is situated on the bank of which river?",
    question_hi: "गोवा की राजधानी पणजी किस नदी के किनारे पर स्थित है?",
    options_en: ["Zuari River", "Tapi River", "Periyar River", "Mandavi River"],
    options_hi: ["जुआरी नदी", "तापी नदी", "पेरियार नदी", "मांडवी नदी (Mandavi River)"],
    correct_option_index: 3,
    explanation_en: "Panaji, the capital of Goa, is situated on the bank of the Mandavi River.",
    explanation_hi: "गोवा की राजधानी पणजी मांडवी नदी के किनारे स्थित है।",
  },
  {
    question_en: "What is the approximate height of Kunchikal Falls, the highest waterfall in India?",
    question_hi: "भारत का सबसे ऊँचा जलप्रपात (Highest Waterfall) कुंचिकल जलप्रपात की ऊँचाई लगभग कितनी है?",
    options_en: ["253 meters", "335 meters", "455 meters", "500 meters"],
    options_hi: ["253 मीटर", "335 मीटर", "455 मीटर", "500 मीटर"],
    correct_option_index: 2,
    explanation_en: "The height of Kunchikal Falls (Karnataka) is 455 meters.",
    explanation_hi: "कुंचिकल जलप्रपात (कर्नाटक) की ऊँचाई 455 मीटर है।",
  },
  {
    question_en: "Dhuandhar Waterfall is situated on which river?",
    question_hi: "धुआंधार जलप्रपात (Dhuandhar Waterfall) किस नदी पर स्थित है?",
    options_en: ["Tapi River", "Godavari River", "Narmada River", "Chambal River"],
    options_hi: ["तापी नदी", "गोदावरी नदी", "नर्मदा नदी", "चंबल नदी"],
    correct_option_index: 2,
    explanation_en: "Dhuandhar Waterfall (Bhedaghat, MP) is situated on the Narmada River.",
    explanation_hi: "धुआंधार जलप्रपात (भेड़ाघाट, MP) नर्मदा नदी पर स्थित है।",
  },
  {
    question_en: "Vembanad Lake, located in Kerala, is another lagoon lake. What is its name?",
    question_hi: "केरल में स्थित वेम्बनाड झील (Vembanad Lake) की एक और लैगून झील है, जिसका नाम क्या है?",
    options_en: ["Chilika Lake", "Pulicat Lake", "Loktak Lake", "Ashtamudi Lake"],
    options_hi: ["चिल्का झील", "पुलिकट झील", "लोकटक झील", "अष्टमुडी झील (Ashtamudi Lake)"],
    correct_option_index: 3,
    explanation_en: "Ashtamudi Lake is located in Kerala.",
    explanation_hi: "अष्टमुडी झील केरल में स्थित है।",
  },
  {
    question_en: "What are the salt water lakes in Rajasthan locally called?",
    question_hi: "राजस्थान में खारे पानी की झीलों को स्थानीय रूप से क्या कहा जाता है?",
    options_en: ["Tal", "Kayal", "Dhebar", "Playa"],
    options_hi: ["ताल", "कयाल", "ढेबर", "प्लाया (Playa)"],
    correct_option_index: 3,
    explanation_en: "Saltwater lakes in the Jaisalmer district of Rajasthan are called Playa.",
    explanation_hi: "राजस्थान के जैसलमेर जिले में खारे पानी की झीलों को प्लाया कहा जाता है।",
  },
  {
    question_en: "Govind Ballabh Pant Sagar Lake is situated on Rihand, a tributary of which river?",
    question_hi: "गोविंद बल्लभ पंत सागर झील किस नदी की सहायक नदी रिहंद पर स्थित है?",
    options_en: ["Bhagirathi", "Chambal", "Sutlej", "Son River"],
    options_hi: ["भागीरथी", "चंबल", "सतलुज", "सोन नदी"],
    correct_option_index: 3,
    explanation_en: "Govind Ballabh Pant Sagar Lake is located on the Rihand River, a tributary of the Son River.",
    explanation_hi: "गोविंद बल्लभ पंत सागर झील सोन नदी की सहायक रिहंद नदी पर स्थित है।",
  },
  {
    question_en: "Kallanai Dam, the oldest dam in India, is situated on which river?",
    question_hi: "भारत का सबसे पुराना बाँध (Oldest Dam) कल्लनई बाँध (Kallanai Dam) किस नदी पर स्थित है?",
    options_en: ["Krishna River", "Godavari River", "Kaveri River", "Periyar River"],
    options_hi: ["कृष्णा नदी", "गोदावरी नदी", "कावेरी नदी", "पेरियार नदी"],
    correct_option_index: 2,
    explanation_en: "Kallanai Dam (Grand Anicut) is situated on the Kaveri River in Tamil Nadu.",
    explanation_hi: "कल्लनई बाँध (Grand Anicut) कावेरी नदी पर तमिलनाडु में स्थित है।",
  },
  {
    question_en: "Sardar Sarovar Dam is situated on which river, which flows northwards from the southern part of the Narmada River?",
    question_hi: "किस नदी पर स्थित सरदार सरोवर बाँध, नर्मदा नदी के दक्षिणी भाग से उत्तर दिशा की ओर बहती है?",
    options_en: ["Tapi River", "Mahi River", "Narmada River", "Sabarmati River"],
    options_hi: ["तापी नदी", "माही नदी", "नर्मदा नदी", "साबरमती नदी"],
    correct_option_index: 2,
    explanation_en: "Sardar Sarovar Dam is situated on the Narmada River in Gujarat. (Note: The question is framed in a confusing manner; the correct answer is Narmada, on which the dam is built).",
    explanation_hi: "सरदार सरोवर बाँध नर्मदा नदी पर गुजरात में स्थित है।",
  },
  {
    question_en: "'Almatti Dam', located on the Krishna River, is situated in which state?",
    question_hi: "कृष्णा नदी पर स्थित 'अलमट्टी बाँध' (Almatti Dam) किस राज्य में स्थित है?",
    options_en: ["Andhra Pradesh", "Tamil Nadu", "Karnataka", "Maharashtra"],
    options_hi: ["आंध्र प्रदेश", "तमिलनाडु", "कर्नाटक", "महाराष्ट्र"],
    correct_option_index: 2,
    explanation_en: "Almatti Dam is situated on the Krishna River in Karnataka.",
    explanation_hi: "अलमट्टी बाँध कृष्णा नदी पर कर्नाटक में स्थित है।",
  },
  {
    question_en: "Laterite Soil is spread over approximately what percentage of the total area of India?",
    question_hi: "लैटेराइट मिट्टी (Laterite Soil) भारत के कुल भू-भाग के लगभग कितने प्रतिशत पर फैली है?",
    options_en: ["43.4%", "18.6%", "3.7%", "16.6%"],
    options_hi: ["43.4%", "18.6%", "3.7%", "16.6%"],
    correct_option_index: 2,
    explanation_en: "Laterite soil is spread over 3.7% of India's total area.",
    explanation_hi: "लैटेराइट मिट्टी भारत के 3.7% भू-भाग पर फैली है।",
  },
  {
    question_en: "Mountain Soil is rich in which component?",
    question_hi: "पर्वतीय मिट्टी (Mountain Soil) किसमें समृद्ध (Rich) होती है?",
    options_en: ["Potash", "Lime", "Phosphorus", "Humus"],
    options_hi: ["पोटाश", "चूना", "फॉस्फोरस", "ह्यूमस (Humus)"],
    correct_option_index: 3,
    explanation_en: "Mountain soil is rich in Humus.",
    explanation_hi: "पर्वतीय मिट्टी ह्यूमस में समृद्ध होती है।",
  },
  {
    question_en: "Which soil is also known as 'Kallar', 'Usar', or 'Reh'?",
    question_hi: "किस मिट्टी को 'कल्लर', 'उससर' या 'रेह' नाम से भी जाना जाता है?",
    options_en: ["Mountain soil", "Alluvial soil", "Red soil", "Saline and Alkaline soil"],
    options_hi: ["पर्वतीय मिट्टी", "जलोढ़ मिट्टी", "लाल मिट्टी", "नमकीन और क्षारीय मिट्टी (Saline and Alkaline soil)"],
    correct_option_index: 3,
    explanation_en: "Saline and alkaline soil is also called Reh, Kallar, or Usar.",
    explanation_hi: "नमकीन और क्षारीय मिट्टी को रेह, कल्लर या उसर भी कहते हैं।",
  },
  {
    question_en: "Which of the following trees is not found in Tropical Evergreen Forests?",
    question_hi: "उष्णकटिबंधीय सदाबहार वन में पाए जाने वाले वृक्षों में से कौन सा नहीं है?",
    options_en: ["Cinchona", "Mahogany", "Ebony", "Sal"],
    options_hi: ["सिनकोना", "महोगनी", "आबनूस (Ebony)", "साल (Sal)"],
    correct_option_index: 3,
    explanation_en: "Trees like Sal, Teak, Shisham, etc., are found in Tropical Deciduous Forests.",
    explanation_hi: "साल, सागौन, शीशम जैसे वृक्ष उष्णकटिबंधीय पर्णपाती वन (Tropical Deciduous Forests) में पाए जाते हैं।",
  },
  {
    question_en: "Tendu leaves are primarily used to make which product?",
    question_hi: "तेंदू के पत्तों (Tendu leaves) का उपयोग मुख्य रूप से किस उत्पाद को बनाने के लिए किया जाता है?",
    options_en: ["Matches", "Paper", "Gum", "Bidis"],
    options_hi: ["माचिस", "कागज", "गोंद", "बीड़ी (Bidis)"],
    correct_option_index: 3,
    explanation_en: "Tendu leaves are used to make Bidis.",
    explanation_hi: "तेंदू के पत्ते बीड़ी बनाने के काम आते हैं।",
  },
  {
    question_en: "Tropical Dry Deciduous Forests are found in which rainfall range?",
    question_hi: "शुष्क पर्णपाती वन (Tropical Dry Deciduous Forest) किस वर्षा सीमा (Rainfall range) में पाए जाते हैं?",
    options_en: ["More than 250 cm", "150-200 cm", "70-100 cm", "Less than 50 cm"],
    options_hi: ["250 सेमी से अधिक", "150-200 सेमी", "70-100 सेमी", "50 सेमी से कम"],
    correct_option_index: 2,
    explanation_en: "Tropical Dry Deciduous Forests are found in areas with 70-100 cm of rainfall.",
    explanation_hi: "उष्णकटिबंधीय शुष्क पर्णपाती वन 70-100 सेमी वर्षा वाले क्षेत्रों में पाए जाते हैं।",
  },
  {
    question_en: "Sandalwood is mainly produced in the tropical deciduous forests of which state?",
    question_hi: "चंदन की लकड़ी (Sandalwood) का उत्पादन मुख्य रूप से किस राज्य के उष्णकटिबंधीय पर्णपाती वनों में होता है?",
    options_en: ["Madhya Pradesh", "Maharashtra", "Andhra Pradesh", "Karnataka"],
    options_hi: ["मध्य प्रदेश", "महाराष्ट्र", "आंध्र प्रदेश", "कर्नाटक"],
    correct_option_index: 3,
    explanation_en: "Sandalwood is mainly found in Karnataka.",
    explanation_hi: "चंदन की लकड़ी मुख्य रूप से कर्नाटक में पाई जाती है।",
  },
  {
    question_en: "The rainfall from 'Western Disturbance' is highly beneficial for which crops?",
    question_hi: "'पश्चिमी विक्षोभ' (Western Disturbance) से होने वाली वर्षा किन फसलों के लिए अत्यधिक लाभदायक होती है?",
    options_en: ["Kharif crops", "Zaid crops", "Rabi crops", "Cash crops"],
    options_hi: ["खरीफ फसलें", "जायद फसलें", "रबी फसलें", "नकदी फसलें"],
    correct_option_index: 2,
    explanation_en: "Western Disturbances are highly beneficial for Rabi crops (like Wheat).",
    explanation_hi: "पश्चिमी विक्षोभ रबी फसलों (जैसे गेहूं) के लिए अत्यधिक लाभकारी होती है।",
  },
  {
    question_en: "The 'North-East Monsoon' causes rainfall on the coast of which state?",
    question_hi: "'उत्तरी पूर्वी मानसून' (North-East Monsoon) से किस राज्य के तट पर वर्षा होती है?",
    options_en: ["Kerala", "Maharashtra", "Odisha", "Tamil Nadu (Coromandel Coast)"],
    options_hi: ["केरल", "महाराष्ट्र", "ओडिशा", "तमिलनाडु (कोरोमंडल तट)"],
    correct_option_index: 3,
    explanation_en: "In winter, the North-East Monsoon branch picks up moisture from the Bay of Bengal and causes rainfall on the Tamil Nadu (Coromandel Coast).",
    explanation_hi: "सर्दियों में उत्तरी पूर्वी मानसून की शाखा बंगाल की खाड़ी से नमी लेकर तमिलनाडु (कोरोमंडल तट) पर वर्षा करती है।",
  },
  {
    question_en: "Which gas is obtained from coal mines?",
    question_hi: "कोयले की खानों से कौन सी गैस प्राप्त होती है?",
    options_en: ["Carbon Dioxide", "Nitrogen", "Hydrogen", "Methane"],
    options_hi: ["कार्बन डाइऑक्साइड", "नाइट्रोजन", "हाइड्रोजन", "मीथेन (Methane)"],
    correct_option_index: 3,
    explanation_en: "Methane gas is obtained from coal mines.",
    explanation_hi: "कोयले की खानों से मीथेन गैस प्राप्त होती है।",
  },
  {
    question_en: "Which type of iron ore contains up to 72% iron metal and is of the best quality?",
    question_hi: "कौन सा लौह अयस्क का प्रकार है जिसमें 72% तक लौह धातु शामिल होती है और यह सर्वोत्तम गुणवत्ता का होता है?",
    options_en: ["Hematite", "Limonite", "Siderite", "Magnetite"],
    options_hi: ["हेमेटाइट", "लिमोनाइट", "सिडेराइट", "मैग्नेटाइट (Magnetite)"],
    correct_option_index: 3,
    explanation_en: "Magnetite (black colour) is the best quality iron ore, containing up to 72% iron metal.",
    explanation_hi: "मैग्नेटाइट (काला रंग) सर्वोत्तम गुणवत्ता वाला लौह अयस्क है, जिसमें 72% तक लौह धातु होती है।",
  },
  {
    question_en: "What is the quantity of iron metal in Hematite iron ore?",
    question_hi: "हेमेटाइट लौह अयस्क में लौह धातु की मात्रा कितनी होती है?",
    options_en: ["40-50%", "72%", "60-70%", "85-90%"],
    options_hi: ["40-50%", "72%", "60-70%", "85-90%"],
    correct_option_index: 2,
    explanation_en: "Hematite contains 60-70% iron metal and accounts for 80% of the iron ore found in India.",
    explanation_hi: "हेमेटाइट में 60-70% लौह धातु होती है और यह भारत में 80% पाया जाता है।",
  },
  {
    question_en: "Where are the Ramagiri Gold Mines, from which gold is obtained, located?",
    question_hi: "रामगिरी की खानें (Ramagiri Gold Mine) कहाँ स्थित हैं, जहाँ से सोना प्राप्त होता है?",
    options_en: ["Karnataka", "Telangana", "Andhra Pradesh", "Maharashtra"],
    options_hi: ["कर्नाटक", "तेलंगाना", "आंध्र प्रदेश", "महाराष्ट्र"],
    correct_option_index: 2,
    explanation_en: "The Ramagiri gold mine is located in the Anantapur district of Andhra Pradesh.",
    explanation_hi: "रामगिरी सोने की खान आंध्र प्रदेश के अनंतपुर जिले में स्थित है।",
  },
  {
    question_en: "The 'Zawar' mines, famous for Zinc production, are located in which state?",
    question_hi: "जस्ता (Zinc) उत्पादन के लिए प्रसिद्ध 'जावर' की खानें किस राज्य में स्थित हैं?",
    options_en: ["Chhattisgarh", "Jharkhand", "Rajasthan", "Maharashtra"],
    options_hi: ["छत्तीसगढ़", "झारखंड", "राजस्थान", "महाराष्ट्र"],
    correct_option_index: 2,
    explanation_en: "The Zawar mines (Udaipur district) are located in Rajasthan.",
    explanation_hi: "जावर की खानें (उदयपुर जिला) राजस्थान में स्थित हैं।",
  },
  {
    question_en: "Which is the only state in India that produces Tin?",
    question_hi: "भारत में टिन (Tin) का उत्पादन करने वाला एकमात्र राज्य कौन सा है?",
    options_en: ["Jharkhand", "Odisha", "Maharashtra", "Chhattisgarh"],
    options_hi: ["झारखंड", "ओडिशा", "महाराष्ट्र", "छत्तीसगढ़"],
    correct_option_index: 3,
    explanation_en: "Chhattisgarh is the only state in India that produces Tin.",
    explanation_hi: "छत्तीसगढ़ भारत में टिन का उत्पादन करने वाला एकमात्र राज्य है।",
  },
  {
    question_en: "Makrana, located in the Nagaur district of Rajasthan, is famous for which mineral?",
    question_hi: "राजस्थान में नागौर जिले में स्थित मकराना (Makrana) किस खनिज के लिए प्रसिद्ध है?",
    options_en: ["Iron Ore", "Mica", "Limestone", "Marble"],
    options_hi: ["लौह अयस्क", "अभ्रक", "चूना पत्थर", "संगमरमर (Marble)"],
    correct_option_index: 3,
    explanation_en: "Makrana is famous for high-quality marble (metamorphic rock), which was used in the Taj Mahal.",
    explanation_hi: "मकराना उच्च गुणवत्ता वाले संगमरमर (कायांतरित चट्टान) के लिए प्रसिद्ध है, जिसका उपयोग ताजमहल में हुआ है।",
  },
  {
    question_en: "The Raniganj Coal Field is located in which state?",
    question_hi: "रानीगंज कोयला क्षेत्र किस राज्य में स्थित है?",
    options_en: ["Jharkhand", "Chhattisgarh", "Odisha", "West Bengal"],
    options_hi: ["झारखंड", "छत्तीसगढ़", "ओडिशा", "पश्चिम बंगाल"],
    correct_option_index: 3,
    explanation_en: "The Raniganj Coal Field is located in West Bengal.",
    explanation_hi: "रानीगंज कोयला क्षेत्र पश्चिम बंगाल में स्थित है।",
  },
  {
    question_en: "The Singareni Coal Field is located in which state?",
    question_hi: "सिंगरेनी कोयला क्षेत्र किस राज्य में स्थित है?",
    options_en: ["Andhra Pradesh", "Telangana", "Chhattisgarh", "Odisha"],
    options_hi: ["आंध्र प्रदेश", "तेलंगाना", "छत्तीसगढ़", "ओडिशा"],
    correct_option_index: 1,
    explanation_en: "The Singareni Coal Field is located in Telangana.",
    explanation_hi: "सिंगरेनी कोयला क्षेत्र तेलंगाना में स्थित है।",
  },
  {
    question_en: "Which oil refinery is located in Bihar?",
    question_hi: "कौन सा तेल शोधक कारखाना (Oil Refinery) बिहार में स्थित है?",
    options_en: ["Digboi (Assam)", "Haldia (WB)", "Barauni", "Jamnagar (Gujarat)"],
    options_hi: ["डिगबोई (असम)", "हल्दिया (WB)", "बरौनी (Barauni)", "जामनगर (गुजरात)"],
    correct_option_index: 2,
    explanation_en: "The Barauni oil refinery is located in Bihar.",
    explanation_hi: "बरौनी तेल शोधक कारखाना बिहार में स्थित है।",
  },
  {
    question_en: "Which port is also known as 'V.O. Chidambaranar Port'?",
    question_hi: "किस बंदरगाह को 'वी.ओ. चिदंबरनार पोर्ट' (V.O. Chidambaranar Port) के नाम से भी जाना जाता है?",
    options_en: ["Chennai Port", "Kamarajar Port", "Visakhapatnam Port", "Tuticorin Port"],
    options_hi: ["चेन्नई पोर्ट", "कामराजर पोर्ट", "विशाखापत्तनम पोर्ट", "तूतीकोरिन पोर्ट (Tuticorin Port)"],
    correct_option_index: 3,
    explanation_en: "Tuticorin Port (Tamil Nadu) is called V.O. Chidambaranar Port.",
    explanation_hi: "तूतीकोरिन पोर्ट (तमिलनाडु) को वी.ओ. चिदंबरनार पोर्ट कहा जाता है।",
  },
  {
    question_en: "Which port on the western coast is called the 'Queen of Arabian Sea'?",
    question_hi: "कौन सा बंदरगाह पश्चिमी तट पर 'अरब सागर की रानी' (Queen of Arabian Sea) कहलाता है?",
    options_en: ["Mumbai Port", "Kandla Port", "Marmagao Port", "Kochi Port"],
    options_hi: ["मुंबई पोर्ट", "कांडला पोर्ट", "मुर्मूगाओ पोर्ट", "कोच्चि पोर्ट (Kochi Port)"],
    correct_option_index: 3,
    explanation_en: "Kochi Port is called the 'Queen of the Arabian Sea'.",
    explanation_hi: "कोच्चि पोर्ट को 'अरब सागर की रानी' कहा जाता है।",
  },
  {
    question_en: "What is the total length of the Golden Quadrilateral highway project?",
    question_hi: "स्वर्णिम चतुर्भुज (Golden Quadrilateral) राजमार्ग परियोजना की कुल लंबाई कितनी है?",
    options_en: ["4237 km", "3806 km", "5846 km", "6100 km"],
    options_hi: ["4237 किमी", "3806 किमी", "5846 किमी", "6100 किमी"],
    correct_option_index: 2,
    explanation_en: "The total length of the Golden Quadrilateral (connecting Delhi, Mumbai, Chennai, Kolkata) is 5846 km.",
    explanation_hi: "स्वर्णिम चतुर्भुज (दिल्ली, मुंबई, चेन्नई, कोलकाता को जोड़ता है) की कुल लंबाई 5846 किमी है।",
  },
  {
    question_en: "The East-West Corridor connects which two places?",
    question_hi: "पूर्व-पश्चिम गलियारा (East-West Corridor) किन दो स्थानों को जोड़ता है?",
    options_en: ["Srinagar and Kanyakumari", "Delhi and Mumbai", "Porbandar (Gujarat) and Silchar (Assam)", "Kolkata and Chennai"],
    options_hi: ["श्रीनगर और कन्याकुमारी", "दिल्ली और मुंबई", "पोरबंदर (गुजरात) और सिलचर (असम)", "कोलकाता और चेन्नई"],
    correct_option_index: 2,
    explanation_en: "The East-West Corridor connects Porbandar (Gujarat) and Silchar (Assam).",
    explanation_hi: "पूर्व-पश्चिम गलियारा पोरबंदर (गुजरात) और सिलचर (असम) को जोड़ता है।",
  },
  {
    question_en: "India's longest railway route goes from Dibrugarh in Assam to which place in Tamil Nadu?",
    question_hi: "भारत का सबसे लंबा रेलमार्ग (Longest Railway Route) असम के डिब्रूगढ़ से तमिलनाडु में किस स्थान तक जाता है?",
    options_en: ["Chennai", "Coimbatore", "Kanyakumari", "Port Blair"],
    options_hi: ["चेन्नई", "कोयंबटूर", "कन्याकुमारी", "पोर्ट ब्लेयर"],
    correct_option_index: 2,
    explanation_en: "India's longest railway route (4237 km) is from Dibrugarh to Kanyakumari.",
    explanation_hi: "भारत का सबसे लंबा रेलमार्ग (4237 किमी) डिब्रूगढ़ से कन्याकुमारी तक है।",
  },
  {
    question_en: "What was the old name of Rani Kamlapati Station, India's first privately managed railway station?",
    question_hi: "भारत का पहला निजी तौर पर प्रबंधित रेलवे स्टेशन रानी कमलापति स्टेशन का पुराना नाम क्या था?",
    options_en: ["Nizamuddin Railway Station", "Habibganj Railway Station (Bhopal)", "Vadodara Station", "Chhatrapati Shivaji Terminus"],
    options_hi: ["निजामुद्दीन रेलवे स्टेशन", "हबीबगंज रेलवे स्टेशन (भोपाल)", "वडोदरा स्टेशन", "छत्रपति शिवाजी टर्मिनस"],
    correct_option_index: 1,
    explanation_en: "The new name of Habibganj Railway Station (Bhopal, MP) is Rani Kamlapati Railway Station.",
    explanation_hi: "हबीबगंज रेलवे स्टेशन (भोपाल, MP) का नया नाम रानी कमलापति रेलवे स्टेशन है।",
  },
  {
    question_en: "Where is the second longest platform in India located?",
    question_hi: "भारत का दूसरा सबसे लंबा प्लेटफॉर्म (Longest Platform) कहाँ स्थित है?",
    options_en: ["Hubli Station (Karnataka)", "Kharagpur (WB)", "Gorakhpur Junction", "Mughalsarai Junction"],
    options_hi: ["हुबली स्टेशन (कर्नाटक)", "खड़गपुर (WB)", "गोरखपुर जंक्शन", "मुगलसराय जंक्शन"],
    correct_option_index: 2,
    explanation_en: "The second longest platform in India is Gorakhpur Junction (1366.33 meters).",
    explanation_hi: "भारत का दूसरा सबसे लंबा प्लेटफॉर्म गोरखपुर जंक्शन (1366.33 मीटर) है।",
  },
  {
    question_en: "In which city was 'Metro Rail' first started in India?",
    question_hi: "'मेट्रो रेल' की शुरुआत भारत में पहली बार किस शहर में हुई थी?",
    options_en: ["New Delhi (2002)", "Mumbai (2014)", "Bengaluru (2011)", "Kolkata (1984)"],
    options_hi: ["नई दिल्ली (2002)", "मुंबई (2014)", "बेंगलुरु (2011)", "कोलकाता (1984)"],
    correct_option_index: 3,
    explanation_en: "The first Metro in India started in Kolkata on October 24, 1984.",
    explanation_hi: "भारत में पहली मेट्रो 24 अक्टूबर 1984 को कोलकाता में शुरू हुई।",
  },
  {
    question_en: "According to Census 2011, what was the Decadal Growth Rate of India?",
    question_hi: "जनगणना 2011 के अनुसार भारत की दशकीय वृद्धि दर (Decadal Growth Rate) कितनी थी?",
    options_en: ["21.54%", "19.98%", "17.7%", "13.01%"],
    options_hi: ["21.54%", "19.98%", "17.7%", "13.01%"],
    correct_option_index: 2,
    explanation_en: "According to the 2011 Census, the Decadal Growth Rate was 17.7%.",
    explanation_hi: "2011 जनगणना के अनुसार दशकीय वृद्धि दर 17.7% थी।",
  },
  {
    question_en: "According to Census 2011, what was the Child Sex Ratio (0-6 years age group)?",
    question_hi: "जनगणना 2011 के अनुसार, 0-6 वर्ष के आयु वर्ग का लिंगानुपात (Child Sex Ratio) कितना था?",
    options_en: ["943", "919", "927", "950"],
    options_hi: ["943", "919", "927", "950"],
    correct_option_index: 1,
    explanation_en: "The Child Sex Ratio for the 0-6 years age group was 919.",
    explanation_hi: "0-6 वर्ष आयु वर्ग का शिशु लिंगानुपात 919 था।",
  },
  {
    question_en: "Which state is not included in the four states with the lowest percentage of rural population?",
    question_hi: "सर्वाधिक ग्रामीण जनसंख्या प्रतिशत (Lowest % of Rural Population) वाले चार राज्यों में से कौन सा राज्य शामिल नहीं है?",
    options_en: ["Goa", "Mizoram", "Tamil Nadu", "Sikkim"],
    options_hi: ["गोवा", "मिजोरम", "तमिलनाडु", "सिक्किम"],
    correct_option_index: 3,
    explanation_en: "Sikkim is one of the states with the lowest urban population. (Note: The question asks for the lowest rural population percentage. Sikkim has the lowest urban population, so its rural population percentage will be high. The states with the lowest rural percentage are Goa, Mizoram, Tamil Nadu, and Kerala).",
    explanation_hi: "सिक्किम न्यूनतम शहरी जनसंख्या वाले राज्यों में से एक है। (नोट: प्रश्न में ग्रामीण जनसंख्या प्रतिशत पूछा गया है। सिक्किम में न्यूनतम शहरी जनसंख्या है, इसलिए वहाँ ग्रामीण जनसंख्या प्रतिशत अधिक होगा। न्यूनतम ग्रामीण प्रतिशत वाले राज्य गोवा, मिजोरम, तमिलनाडु, केरल हैं)।",
  },
  {
    question_en: "Which Union Territory has the highest population density?",
    question_hi: "सर्वाधिक जनसंख्या घनत्व (Highest Population Density) वाला केंद्र शासित प्रदेश कौन सा है?",
    options_en: ["Chandigarh", "Puducherry", "Delhi", "Daman and Diu"],
    options_hi: ["चंडीगढ़", "पुडुचेरी", "दिल्ली", "दमन और दीव"],
    correct_option_index: 2,
    explanation_en: "Delhi (11320) is the Union Territory with the highest population density.",
    explanation_hi: "सर्वाधिक जनसंख्या घनत्व वाला केंद्र शासित प्रदेश दिल्ली (11320) है।",
  },
  {
    question_en: "The capital of which country is 'Phnom Penh'?",
    question_hi: "किस देश की राजधानी 'नम पेन्ह' (Phnom Penh) है?",
    options_en: ["Vietnam", "Laos", "Thailand", "Cambodia"],
    options_hi: ["वियतनाम", "लाओस", "थाईलैंड", "कंबोडिया"],
    correct_option_index: 3,
    explanation_en: "Phnom Penh is the capital of Cambodia.",
    explanation_hi: "कंबोडिया की राजधानी नम पेन्ह है।",
  }
];


export default test5Questions;
