import type { QuizQuestion } from '../../../types';

const test2Questions: QuizQuestion[] = [
  {
    question_en: "Metallic minerals are mainly found in which type of rocks?",
    question_hi: "धात्विक खनिज (Metallic minerals) मुख्य रूप से किस प्रकार की चट्टानों में पाए जाते हैं?",
    options_en: ["Sedimentary rocks", "Metamorphic rocks", "Igneous rocks", "Alluvial rocks"],
    options_hi: ["परतदार चट्टानें", "कायांतरित चट्टानें", "आग्नेय चट्टानें (Igneous rocks)", "अवसादी चट्टानें"],
    correct_option_index: 2,
    explanation_en: "Metallic minerals, including ferrous metals, are found in Igneous and Metamorphic rock formations. Here, Igneous rocks is the most appropriate option.",
    explanation_hi: "धात्विक खनिज, जिनमें लौह धातुएँ शामिल हैं, आग्नेय और कायांतरित चट्टानों की संरचनाओं में पाए जाते हैं। यहाँ, आग्नेय चट्टानें सबसे उपयुक्त विकल्प है।",
  },
  {
    question_en: "Which of the following is NOT a ferrous metal?",
    question_hi: "निम्नलिखित में से कौन सा लौह धातु (Ferrous metal) नहीं है?",
    options_en: ["Manganese", "Chromium", "Nickel", "Gold"],
    options_hi: ["मैंगनीज", "क्रोमियम", "निकेल", "सोना (Gold)"],
    correct_option_index: 3,
    explanation_en: "Gold, silver, zinc, copper, and bauxite are non-ferrous metals. Ferrous metals contain iron.",
    explanation_hi: "सोना (Gold), चाँदी, जस्ता, ताँबा और बॉक्साइट अलौह धातुएँ (Non-ferrous metals) हैं। लौह धातुएँ लोहे से युक्त होती हैं।",
  },
  {
    question_en: "Non-metallic minerals are found in which type of rocks?",
    question_hi: "अधात्विक खनिज (Non-metallic minerals) किस प्रकार की चट्टानों में पाए जाते हैं?",
    options_en: ["Igneous rocks", "Basaltic rocks", "Sedimentary rocks", "Granite rocks"],
    options_hi: ["आग्नेय चट्टानें", "बेसाल्टिक चट्टानें", "परतदार चट्टानें (Sedimentary rocks)", "ग्रेनाइट चट्टानें"],
    correct_option_index: 2,
    explanation_en: "Non-metallic minerals like limestone, mica, and coal are generally found in Sedimentary rocks.",
    explanation_hi: "अधात्विक खनिज जैसे चूना पत्थर, अभ्रक और कोयला आमतौर पर परतदार चट्टानों में पाए जाते हैं।",
  },
  {
    question_en: "Which is the best quality ore of iron, containing up to 72% iron metal?",
    question_hi: "लोहे का सबसे अच्छी गुणवत्ता वाला अयस्क कौन सा है, जिसमें 72% तक लौह धातु शामिल होती है?",
    options_en: ["Hematite", "Limonite", "Siderite", "Magnetite"],
    options_hi: ["हेमेटाइट", "लिमोनाइट", "सिडेराइट", "मैग्नेटाइट (Magnetite)"],
    correct_option_index: 3,
    explanation_en: "Magnetite (black colour) is the best quality iron ore, containing up to 72% iron metal.",
    explanation_hi: "मैग्नेटाइट (काला रंग) सर्वोत्तम गुणवत्ता वाला लौह अयस्क है, जिसमें 72% तक लौह धातु होती है।",
  },
  {
    question_en: "Which iron ore is found in the largest quantity in India?",
    question_hi: "भारत में सर्वाधिक मात्रा में पाया जाने वाला लौह अयस्क कौन सा है?",
    options_en: ["Magnetite", "Hematite", "Limonite", "Siderite"],
    options_hi: ["मैग्नेटाइट", "हेमेटाइट (Hematite)", "लिमोनाइट", "सिडेराइट"],
    correct_option_index: 1,
    explanation_en: "Hematite contains 60-70% iron metal and accounts for about 80% of iron ore found in India.",
    explanation_hi: "हेमेटाइट में 60-70% लौह धातु होती है और यह भारत में 80% पाया जाता है।",
  },
  {
    question_en: "Bailadila mine, India's largest mechanised iron ore mine, is located in which state?",
    question_hi: "भारत की सबसे बड़ी मशीनीकृत लौह अयस्क खदान (Largest Mechanised mine) बैलाडीला खदान किस राज्य में स्थित है?",
    options_en: ["Odisha", "Jharkhand", "Chhattisgarh", "Karnataka"],
    options_hi: ["ओडिशा", "झारखंड", "छत्तीसगढ़", "कर्नाटक"],
    correct_option_index: 2,
    explanation_en: "Bailadila mine (Hematite iron) is located in Dantewada district, Chhattisgarh.",
    explanation_hi: "बैलाडीला खदान (हेमेटाइट लोहा) दंतेवाड़ा जिले, छत्तीसगढ़ में स्थित है।",
  },
  {
    question_en: "Guramahisani, Badam Pahar, and Gurumahisani are famous for which mineral ore?",
    question_hi: "गुम्माहिंसानी, बादाम पहाड़, और गुरुमहिसानी किस खनिज अयस्क के लिए प्रसिद्ध हैं?",
    options_en: ["Manganese", "Bauxite", "Hematite iron", "Zinc"],
    options_hi: ["मैंगनीज", "बॉक्साइट", "हेमेटाइट लोहा", "जस्ता"],
    correct_option_index: 2,
    explanation_en: "All these mines (in Odisha) are famous for Hematite iron ore.",
    explanation_hi: "ये सभी खदानें (ओडिशा में) हेमेटाइट लोहा के लिए प्रसिद्ध हैं।",
  },
  {
    question_en: "Baba Budan Hills and Kudremukh, famous for Magnetite iron ore, are located in which state?",
    question_hi: "मैग्नेटाइट लौह अयस्क के लिए प्रसिद्ध बाबा बुदन की पहाड़ी और कुद्रेमुख किस राज्य में स्थित है?",
    options_en: ["Andhra Pradesh", "Karnataka", "Goa", "Maharashtra"],
    options_hi: ["आंध्र प्रदेश", "कर्नाटक", "गोवा", "महाराष्ट्र"],
    correct_option_index: 1,
    explanation_en: "Baba Budan Hills and Kudremukh (Karnataka) are famous for Magnetite iron ore.",
    explanation_hi: "बाबा बुदन की पहाड़ी और कुद्रेमुख (कर्नाटक) मैग्नेटाइट लोहा के लिए प्रसिद्ध हैं।",
  },
  {
    question_en: "In which area did Hindustan Zinc Limited start the production of zinc and silver with the help of Britain?",
    question_hi: "हिंदुस्तान जिंक लिमिटेड (Hindustan Zinc Limited) ने ब्रिटेन की सहायता से किस क्षेत्र में जस्ता और चाँदी का उत्पादन शुरू किया था?",
    options_en: ["Khetri", "Koderma", "Rampura Agucha", "Bailadila"],
    options_hi: ["खेतड़ी", "कोडरमा", "रामपुरा आगूचा (Rampura Agucha)", "बैलाडीला"],
    correct_option_index: 2,
    explanation_en: "Hindustan Zinc Limited was established with the help of Britain in the Rampura Agucha region of Rajasthan.",
    explanation_hi: "राजस्थान के रामपुरा आगूचा क्षेत्र में ब्रिटेन की सहायता से हिंदुस्तान जिंक लिमिटेड की स्थापना हुई।",
  },
  {
    question_en: "Khetri mines, famous for Copper, are located in which state?",
    question_hi: "ताँबा (Copper) के लिए प्रसिद्ध खेतड़ी की खदानें किस राज्य में स्थित हैं?",
    options_en: ["Madhya Pradesh", "Gujarat", "Rajasthan", "Jharkhand"],
    options_hi: ["मध्य प्रदेश", "गुजरात", "राजस्थान", "झारखंड"],
    correct_option_index: 2,
    explanation_en: "Khetri mine for copper (Rajasthan) and Malajkhand (MP) are famous in India.",
    explanation_hi: "ताँबे की खेतड़ी की खान (Rajasthan) और मलाजखंड (MP) प्रसिद्ध हैं।",
  },
  {
    question_en: "Kolar and Hutti mines, famous for gold production, are located in which state?",
    question_hi: "सोना उत्पादन के लिए प्रसिद्ध कोलार और हट्टी की खानें किस राज्य में स्थित हैं?",
    options_en: ["Andhra Pradesh", "Telangana", "Maharashtra", "Karnataka"],
    options_hi: ["आंध्र प्रदेश", "तेलंगाना", "महाराष्ट्र", "कर्नाटक"],
    correct_option_index: 3,
    explanation_en: "Kolar and Hutti gold mines are located in Karnataka.",
    explanation_hi: "कोलार और हट्टी की सोने की खदानें कर्नाटक में स्थित हैं।",
  },
  {
    question_en: "Which is the only state in India that produces Tin?",
    question_hi: "भारत में एकमात्र राज्य कौन सा है जो टिन (Tin) का उत्पादन करता है?",
    options_en: ["Odisha", "Jharkhand", "Chhattisgarh", "Maharashtra"],
    options_hi: ["ओडिशा", "झारखंड", "छत्तीसगढ़", "महाराष्ट्र"],
    correct_option_index: 2,
    explanation_en: "Chhattisgarh is the only state producing Tin in India.",
    explanation_hi: "छत्तीसगढ़ भारत में टिन का उत्पादन करने वाला एकमात्र राज्य है।",
  },
  {
    question_en: "In which districts of Jharkhand is Bauxite production highest?",
    question_hi: "बॉक्साइट (Bauxite) का सर्वाधिक उत्पादन झारखंड के किन जिलों में होता है?",
    options_en: ["Singhbhum and Dhanbad", "Lohardaga and Latehar", "Hazaribagh and Gaya", "Ranchi and Bokaro"],
    options_hi: ["सिंहभूम और धनबाद", "लोहरदगा और लातेहार", "हजारीबाग और गया", "रांची और बोकारो"],
    correct_option_index: 1,
    explanation_en: "Lohardaga and Latehar are famous for Bauxite in Jharkhand.",
    explanation_hi: "झारखंड में बॉक्साइट के लिए लोहरदगा और लातेहार प्रसिद्ध हैं।",
  },
  {
    question_en: "Which district of Jharkhand is called the 'Capital of Mica'?",
    question_hi: "झारखंड के किस जिले को 'अभ्रक नगरी' (Capital of Mica) कहा जाता है?",
    options_en: ["Jamshedpur", "Dhanbad", "Koderma", "Ranchi"],
    options_hi: ["जमशेदपुर", "धनबाद", "कोडरमा", "रांची"],
    correct_option_index: 2,
    explanation_en: "Koderma district of Jharkhand is called the Capital of Mica.",
    explanation_hi: "झारखंड के कोडरमा जिले को अभ्रक नगरी कहा जाता है।",
  },
  {
    question_en: "Tummalapalli mine, the largest Uranium mine, is located in the Cuddapah district of which state?",
    question_hi: "यूरेनियम की सबसे बड़ी खान, तुम्मालपल्ली खान (Tummalapalli mine) किस राज्य के कडप्पा जिले में स्थित है?",
    options_en: ["Jharkhand", "Telangana", "Andhra Pradesh", "Karnataka"],
    options_hi: ["झारखंड", "तेलंगाना", "आंध्र प्रदेश", "कर्नाटक"],
    correct_option_index: 2,
    explanation_en: "Tummalapalli mine, the largest uranium mine, is located in Andhra Pradesh.",
    explanation_hi: "यूरेनियम की सबसे बड़ी खान तुम्मालपल्ली (Tummalapalli mine) आंध्र प्रदेश में स्थित है।",
  },
  {
    question_en: "Where is Thorium mainly found in India?",
    question_hi: "थोरियम (Thorium) भारत में मुख्य रूप से कहाँ पाया जाता है?",
    options_en: ["In the plateaus of Jharkhand", "In the coastal areas of Odisha", "In the coastal areas of Kerala", "In the hills of Tamil Nadu"],
    options_hi: ["झारखंड के पठार में", "ओडिशा के तटवर्ती भागों में", "केरल के तटवर्ती भागों में", "तमिलनाडु की पहाड़ियों में"],
    correct_option_index: 2,
    explanation_en: "Thorium is mainly found in the coastal areas of Kerala in the form of Monazite sand.",
    explanation_hi: "थोरियम (Thorium) केरल के तटवर्ती भागों में मोनाजाइट रेत के रूप में मिलता है।",
  },
  {
    question_en: "Which type of coal has 80-95% carbon and is of the best quality?",
    question_hi: "कोयले का वह कौन सा प्रकार है जिसमें 80-95% कार्बन होता है और यह सर्वोत्तम गुणवत्ता का होता है?",
    options_en: ["Bituminous", "Lignite", "Peat", "Anthracite"],
    options_hi: ["बिटुमिनस", "लिग्नाइट", "पीट", "एन्थ्रेसाइट (Anthracite)"],
    correct_option_index: 3,
    explanation_en: "Anthracite (80-95% carbon) is the best quality coal.",
    explanation_hi: "एन्थ्रेसाइट (80-95% कार्बन) सर्वोत्तम गुणवत्ता का कोयला है।",
  },
  {
    question_en: "Which coal is found in the maximum quantity in India?",
    question_hi: "भारत में सर्वाधिक मात्रा में कौन सा कोयला पाया जाता है?",
    options_en: ["Anthracite", "Bituminous", "Lignite", "Peat"],
    options_hi: ["एन्थ्रेसाइट", "बिटुमिनस (Bituminous)", "लिग्नाइट", "पीट"],
    correct_option_index: 1,
    explanation_en: "Bituminous (55-65% carbon) is the most abundant type of coal found in India.",
    explanation_hi: "बिटुमिनस (55-65% कार्बन) भारत में सबसे ज्यादा पाया जाता है।",
  },
  {
    question_en: "Neyveli coal field, famous for the production of Lignite (brown coal), is located in which state?",
    question_hi: "नवेली (Neyveli) कोयला क्षेत्र, जो लिग्नाइट (भूरा कोयला) के उत्पादन के लिए प्रसिद्ध है, किस राज्य में स्थित है?",
    options_en: ["Odisha", "Telangana", "Kerala", "Tamil Nadu"],
    options_hi: ["ओडिशा", "तेलंगाना", "केरल", "तमिलनाडु"],
    correct_option_index: 3,
    explanation_en: "Neyveli coal field is located in Tamil Nadu.",
    explanation_hi: "नवेली कोयला क्षेत्र तमिलनाडु में स्थित है।",
  },
  {
    question_en: "The coal obtained from the Gondwana region is located in which river valley?",
    question_hi: "गोंडवाना क्षेत्र से प्राप्त कोयला किस नदी घाटी में स्थित है?",
    options_en: ["Narmada River Valley", "Godavari River Valley", "Damodar River Valley", "Son River Valley"],
    options_hi: ["नर्मदा नदी घाटी", "गोदावरी नदी घाटी", "दामोदर नदी घाटी", "सोन नदी घाटी"],
    correct_option_index: 2,
    explanation_en: "Coal is obtained from the Gondwana rock system located in the Damodar River Valley.",
    explanation_hi: "कोयला दामोदर नदी घाटी में स्थित गोंडवाना रॉक सिस्टम से प्राप्त होता है।",
  },
  {
    question_en: "Tarapur, India's first Nuclear Power Plant, was established with the help of which country?",
    question_hi: "भारत का पहला नाभिकीय ऊर्जा संयंत्र (Nuclear Power Plant) तारापुर, किस देश की सहायता से स्थापित किया गया था?",
    options_en: ["Canada", "Russia", "France", "America"],
    options_hi: ["कनाडा", "रूस", "फ्रांस", "अमेरिका (America)"],
    correct_option_index: 3,
    explanation_en: "Tarapur (Maharashtra) is India's first Nuclear Power Plant, established with the help of America.",
    explanation_hi: "तारापुर (महाराष्ट्र) भारत का पहला नाभिकीय ऊर्जा संयंत्र है, जिसे अमेरिका की सहायता से स्थापित किया गया।",
  },
  {
    question_en: "Rawatbhata (Rajasthan) Nuclear Power Plant was established in collaboration with which country?",
    question_hi: "रावतभाटा (राजस्थान) नाभिकीय ऊर्जा संयंत्र किस देश के सहयोग से स्थापित किया गया था?",
    options_en: ["America", "Russia", "Canada", "France"],
    options_hi: ["अमेरिका", "रूस", "कनाडा", "फ्रांस"],
    correct_option_index: 2,
    explanation_en: "Rawatbhata Nuclear Plant was established in collaboration with Canada.",
    explanation_hi: "रावतभाटा नाभिकीय संयंत्र कनाडा के सहयोग से स्थापित किया गया।",
  },
  {
    question_en: "Which of the following Nuclear Power Plants is located in Tamil Nadu?",
    question_hi: "निम्नलिखित में से कौन सा नाभिकीय ऊर्जा संयंत्र तमिलनाडु में स्थित है?",
    options_en: ["Narora", "Kakrapar", "Kaiga", "Kalpakkam"],
    options_hi: ["नरोरा", "काकरापारा", "कैगा", "कलपक्कम (Kalpakkam)"],
    correct_option_index: 3,
    explanation_en: "Kalpakkam (near Chennai) Nuclear Plant is located in Tamil Nadu.",
    explanation_hi: "कलपक्कम (चेन्नई) नाभिकीय संयंत्र तमिलनाडु में स्थित है।",
  },
  {
    question_en: "Digboi, India's oldest oil refinery, is located in which state?",
    question_hi: "भारत की सबसे पुरानी तेल रिफाइनरी (Oil Refinery) डिगबोई, किस राज्य में स्थित है?",
    options_en: ["Bihar", "Gujarat", "Assam", "West Bengal"],
    options_hi: ["बिहार", "गुजरात", "असम", "पश्चिम बंगाल"],
    correct_option_index: 2,
    explanation_en: "Asia and India's first oil well was discovered in Digboi, Assam in 1889.",
    explanation_hi: "एशिया और भारत का पहला तेल कुआँ डिगबोई, असम में 1889 में खोजा गया।",
  },
  {
    question_en: "Mathura, Digboi and Panipat refineries come under which Public Sector Undertaking (PSU)?",
    question_hi: "मथुरा, डिगबोई और पानीपत रिफाइनरी किस सार्वजनिक क्षेत्र के उपक्रम (PSU) के अंतर्गत आती हैं?",
    options_en: ["BPCL", "HPCL", "GAIL", "IOCL (Indian Oil Corporation Limited)"],
    options_hi: ["BPCL", "HPCL", "GAIL", "IOCL (इंडियन ऑयल कॉर्पोरेशन लिमिटेड)"],
    correct_option_index: 3,
    explanation_en: "Mathura, Digboi and Panipat refineries were established by Indian Oil Corporation Limited (IOCL).",
    explanation_hi: "मथुरा, डिगबोई और पानीपत रिफाइनरी इंडियन ऑयल कॉर्पोरेशन लिमिटेड (IOCL) द्वारा स्थापित की गई हैं।",
  },
  {
    question_en: "Puga Valley and Manikaran are famous for which type of energy?",
    question_hi: "पोंगा घाटी (Puga Valley) और मणिकरण (Manikaran) किस प्रकार की ऊर्जा के लिए प्रसिद्ध हैं?",
    options_en: ["Solar energy", "Wind energy", "Geothermal Energy", "Tidal energy"],
    options_hi: ["सौर ऊर्जा", "पवन ऊर्जा", "भू-तापीय ऊर्जा (Geothermal Energy)", "ज्वारीय ऊर्जा"],
    correct_option_index: 2,
    explanation_en: "Puga Valley (Ladakh) and Manikaran (Himachal Pradesh) are sources of Geothermal Energy.",
    explanation_hi: "पूगा घाटी (लद्दाख) और मणिकरण (हिमाचल प्रदेश) भू-तापीय ऊर्जा (Geothermal Energy) स्रोत हैं।",
  },
  {
    question_en: "Which of the following is a non-conventional energy source?",
    question_hi: "निम्नलिखित में से कौन सा गैर-परंपरागत ऊर्जा स्रोत (Non-conventional energy source) है?",
    options_en: ["Coal", "Petroleum", "Wood", "Nuclear energy"],
    options_hi: ["कोयला", "पेट्रोलियम", "लकड़ी", "परमाणु ऊर्जा (Nuclear energy)"],
    correct_option_index: 3,
    explanation_en: "Nuclear energy, solar energy, wind energy, etc., are non-conventional energy sources, as they were not traditionally used.",
    explanation_hi: "परमाणु ऊर्जा, सौर ऊर्जा, पवन ऊर्जा आदि गैर-परंपरागत ऊर्जा स्रोत हैं, जिनका उपयोग पारंपरिक रूप से नहीं किया जाता था।",
  },
  {
    question_en: "Where was the first unsuccessful cotton textile mill established in India in 1810?",
    question_hi: "भारत में प्रथम असफल सूती वस्त्र कारखाना 1810 में कहाँ स्थापित किया गया था?",
    options_en: ["Mumbai", "Ahmedabad", "Kanpur", "Fort Gloster (Calcutta)"],
    options_hi: ["मुंबई", "अहमदाबाद", "कानपुर", "फोर्ट ग्लॉस्टर (कलकत्ता)"],
    correct_option_index: 3,
    explanation_en: "India's first cotton textile mill was started at Fort Gloster (near Kolkata) in 1810, which was unsuccessful.",
    explanation_hi: "भारत का पहला सूती वस्त्र कारखाना फोर्ट ग्लॉस्टर (कोलकाता के निकट) में 1810 में शुरू किया गया, जो विफल रहा।",
  },
  {
    question_en: "Who established the first successful cotton textile mill in Mumbai in 1854?",
    question_hi: "1854 में मुंबई में प्रथम सफल सूती वस्त्र कारखाने की स्थापना किसने की थी?",
    options_en: ["Jamsetji Tata", "K.G. Dabar", "B. R. Ambedkar", "R. A. Gopalaswami"],
    options_hi: ["जमशेदजी टाटा", "कवासजी नानाभाई डाबर (K.G.Dabar)", "बी. आर. अंबेडकर", "आर. ए. गोपालास्वामी"],
    correct_option_index: 1,
    explanation_en: "The first successful cotton textile mill was established by Kawasji Nanabhai Dabar in Mumbai in 1854.",
    explanation_hi: "1854 में मुंबई में कवासजी नानाभाई डाबर द्वारा पहला सफल सूती वस्त्र कारखाना स्थापित किया गया था।",
  },
  {
    question_en: "Which city is called the 'Manchester of North India'?",
    question_hi: "उत्तर भारत का मैनचेस्टर किसे कहा जाता है?",
    options_en: ["Ahmedabad", "Mumbai", "Kanpur", "Coimbatore"],
    options_hi: ["अहमदाबाद", "मुंबई", "कानपुर", "कोयंबटूर"],
    correct_option_index: 2,
    explanation_en: "Kanpur is called the Manchester of North India.",
    explanation_hi: "कानपुर को उत्तर भारत का मैनचेस्टर कहा जाता है।",
  },
  {
    question_en: "Where was India's first Jute industry established in 1855?",
    question_hi: "भारत का सबसे पहला जूट उद्योग (Jute industry) 1855 में कहाँ स्थापित किया गया था?",
    options_en: ["Titagarh (West Bengal)", "Budge Budge (West Bengal)", "Rishra (West Bengal)", "Howrah (West Bengal)"],
    options_hi: ["टीटागढ़ (पश्चिम बंगाल)", "बजबज (पश्चिम बंगाल)", "रिसरा (पश्चिम बंगाल)", "हावड़ा (पश्चिम बंगाल)"],
    correct_option_index: 2,
    explanation_en: "The Jute industry was established at Rishra (West Bengal) in 1855.",
    explanation_hi: "जूट उद्योग की स्थापना 1855 में रिसरा (पश्चिम बंगाल) में हुई थी।",
  },
  {
    question_en: "Where was TISCO (Tata Iron and Steel Company Limited), established before independence, located?",
    question_hi: "स्वतंत्रता से पहले स्थापित TISCO (टाटा आयरन एंड स्टील कंपनी लिमिटेड) कहाँ स्थित थी?",
    options_en: ["Durgapur", "Bokaro", "Rourkela", "Sakchi (Jharkhand)"],
    options_hi: ["दुर्गापुर", "बोकारो", "राउरकेला", "साकची (झारखंड)"],
    correct_option_index: 3,
    explanation_en: "TISCO was established by Jamsetji Tata at Sakchi (Jharkhand) in 1907 (now Jamshedpur).",
    explanation_hi: "TISCO की स्थापना जमशेदजी टाटा द्वारा साकची (झारखंड) में 1907 में की गई थी (अब जमशेदपुर)।",
  },
  {
    question_en: "Bhilai Steel Plant, established during the Second Five-Year Plan (1956-1961), was set up in collaboration with which country?",
    question_hi: "द्वितीय पंचवर्षीय योजना (1956-1961) के दौरान स्थापित भिलाई स्टील प्लांट किस देश के सहयोग से स्थापित किया गया था?",
    options_en: ["Germany", "Britain", "Soviet Union (USSR)", "America"],
    options_hi: ["जर्मनी", "ब्रिटेन", "सोवियत संघ (USSR)", "अमेरिका"],
    correct_option_index: 2,
    explanation_en: "Bhilai Steel Plant (Chhattisgarh) was established with the collaboration of the Soviet Union.",
    explanation_hi: "भिलाई स्टील प्लांट (छत्तीसगढ़) सोवियत संघ के सहयोग से स्थापित हुआ।",
  },
  {
    question_en: "Rourkela Iron and Steel Plant (Odisha) was established in collaboration with which country?",
    question_hi: "राउरकेला लौह-इस्पात संयंत्र (ओडिशा) किस देश के सहयोग से स्थापित किया गया था?",
    options_en: ["Russia", "Germany", "Britain", "France"],
    options_hi: ["रूस", "जर्मनी", "ब्रिटेन", "फ्रांस"],
    correct_option_index: 1,
    explanation_en: "Rourkela plant was established in collaboration with Germany.",
    explanation_hi: "राउरकेला संयंत्र जर्मनी के सहयोग से स्थापित किया गया।",
  },
  {
    question_en: "In which plant did the production of stainless steel sheets begin in India in 1982?",
    question_hi: "भारत में स्टेनलेस स्टील शीट का उत्पादन किस संयंत्र में 1982 से शुरू हुआ था?",
    options_en: ["Bokaro Steel Plant", "Bhilai Steel Plant", "Salem Steel Plant (Tamil Nadu)", "Durgapur Steel Plant"],
    options_hi: ["बोकारो स्टील प्लांट", "भिलाई स्टील प्लांट", "सेलम स्टील प्लांट (तमिलनाडु)", "दुर्गापुर स्टील प्लांट"],
    correct_option_index: 2,
    explanation_en: "The production of stainless steel sheets started at Salem Steel Plant (Tamil Nadu) in 1982.",
    explanation_hi: "सेलम स्टील प्लांट (तमिलनाडु) में 1982 में स्टेनलेस स्टील शीट का उत्पादन शुरू हुआ।",
  },
  {
    question_en: "HINDALCO (Hindustan Aluminium Corporation) at Renukoot (UP) was established in collaboration with which country?",
    question_hi: "HINDALCO (हिन्दुस्तान एल्युमीनियम कॉर्पोरेशन), रेनुकूट (UP) में किस देश के सहयोग से स्थापित किया गया था?",
    options_en: ["Russia", "France", "Germany", "USA (America)"],
    options_hi: ["रूस", "फ्रांस", "जर्मनी", "USA (अमेरिका)"],
    correct_option_index: 3,
    explanation_en: "HINDALCO was established in collaboration with the USA.",
    explanation_hi: "HINDALCO USA (अमेरिका) के सहयोग से स्थापित हुआ।",
  },
  {
    question_en: "NALCO (National Aluminium Company Limited) at Damanjodi (Odisha) was established in collaboration with which country?",
    question_hi: "NALCO (नेशनल एल्युमीनियम कंपनी लिमिटेड), दामनजोड़ी (ओडिशा) में किस देश के सहयोग से स्थापित की गई थी?",
    options_en: ["America", "Russia", "Germany", "France"],
    options_hi: ["अमेरिका", "रूस", "जर्मनी", "फ्रांस"],
    correct_option_index: 3,
    explanation_en: "NALCO (Damanjodi, Odisha) was established in collaboration with France.",
    explanation_hi: "NALCO (दामनजोड़ी, ओडिशा) फ्रांस के सहयोग से स्थापित की गई थी।",
  },
  {
    question_en: "What is the total number of major ports in India?",
    question_hi: "भारत में कुल कितने प्रमुख (Major) बंदरगाह (Ports) हैं?",
    options_en: ["11", "12", "13", "14"],
    options_hi: ["11", "12", "13", "14"],
    correct_option_index: 2,
    explanation_en: "There are 13 major ports in India.",
    explanation_hi: "भारत में 13 प्रमुख बंदरगाह हैं।",
  },
  {
    question_en: "Which is the largest natural port in India?",
    question_hi: "भारत का सबसे बड़ा प्राकृतिक बंदरगाह (Largest Natural Port) कौन सा है?",
    options_en: ["Nhava Sheva (JNPT)", "Kandla Port", "Visakhapatnam Port", "Mumbai Port"],
    options_hi: ["न्हावा शेवा (JNPT)", "कांडला पोर्ट", "विशाखापत्तनम पोर्ट", "मुंबई पोर्ट"],
    correct_option_index: 3,
    explanation_en: "Mumbai Port is the largest natural port in India.",
    explanation_hi: "मुंबई पोर्ट भारत का सबसे बड़ा प्राकृतिक बंदरगाह है।",
  },
  {
    question_en: "Which is the deepest port of the country?",
    question_hi: "देश का सबसे गहरा बंदरगाह (Deepest port of the country) कौन सा है?",
    options_en: ["Mumbai Port", "Haldia Port", "Visakhapatnam Port", "Paradip Port"],
    options_hi: ["मुंबई पोर्ट", "हल्दिया पोर्ट", "विशाखापत्तनम पोर्ट", "पारादीप पोर्ट"],
    correct_option_index: 2,
    explanation_en: "Visakhapatnam Port (Andhra Pradesh) is the deepest port of the country.",
    explanation_hi: "विशाखापत्तनम पोर्ट (आंध्र प्रदेश) देश का सबसे गहरा बंदरगाह है।",
  },
  {
    question_en: "Which port is also known as 'Deendayal Port' and is a Tidal Port?",
    question_hi: "किस बंदरगाह को 'दीनदयाल पोर्ट' (Deendayal Port) के नाम से भी जाना जाता है, और यह एक ज्वारीय बंदरगाह (Tidal Port) है?",
    options_en: ["Mormugao Port", "Kochi Port", "Kandla Port", "Kolkata Port"],
    options_hi: ["मुर्मूगाओ पोर्ट", "कोच्चि पोर्ट", "कांडला पोर्ट", "कोलकाता पोर्ट"],
    correct_option_index: 2,
    explanation_en: "Kandla Port (Gujarat) is located on the Gulf of Kutch on the western coast and is also called Deendayal Port.",
    explanation_hi: "कांडला पोर्ट (गुजरात) पश्चिमी तट पर कच्छ की खाड़ी में स्थित है और इसे दीनदयाल पोर्ट भी कहा जाता है।",
  },
  {
    question_en: "What is the new name of Ennore Port?",
    question_hi: "एन्नौर पोर्ट (Ennore Port) का नया नाम क्या है?",
    options_en: ["Shyam Prasad Mukherjee Port", "Kamarajar Port", "V.O. Chidambaranar Port", "Deendayal Port"],
    options_hi: ["श्याम प्रसाद मुखर्जी पोर्ट", "कामराजर पोर्ट (Kamarajar Port)", "वी.ओ. चिदंबरनार पोर्ट", "दीनदयाल पोर्ट"],
    correct_option_index: 1,
    explanation_en: "The new name of Ennore Port (Tamil Nadu) is Kamarajar Port.",
    explanation_hi: "एन्नौर पोर्ट (तमिलनाडु) का नया नाम कामराजर पोर्ट है।",
  },
  {
    question_en: "Which is the longest National Waterway in India?",
    question_hi: "भारत का सबसे लंबा राष्ट्रीय जलमार्ग (National Waterway) कौन सा है?",
    options_en: ["NW-2 (Brahmaputra River)", "NW-3 (Kerala)", "NW-1 (Ganga-Bhagirathi-Hooghly)", "NW-4 (Kakinada-Puducherry)"],
    options_hi: ["NW-2 (ब्रह्मपुत्र नदी)", "NW-3 (केरल)", "NW-1 (गंगा-भागीरथी-हुगली)", "NW-4 (काकीनाडा-पुडुचेरी)"],
    correct_option_index: 2,
    explanation_en: "National Waterway-1 (from Allahabad to Haldia, 1620 km long) is the longest waterway in India.",
    explanation_hi: "राष्ट्रीय जलमार्ग-1 (इलाहाबाद से हल्दिया तक, 1620 किमी लंबा) भारत का सबसे लंबा जलमार्ग है।",
  },
  {
    question_en: "National Waterway-2 (NW-2) extends from Sadiya to Dhubri (Assam) on which river?",
    question_hi: "राष्ट्रीय जलमार्ग-2 (NW-2) किस नदी पर सदिया से धुबरी (असम) तक फैला हुआ है?",
    options_en: ["Ganga", "Brahmaputra", "Krishna", "Godavari"],
    options_hi: ["गंगा", "ब्रह्मपुत्र", "कृष्णा", "गोदावरी"],
    correct_option_index: 1,
    explanation_en: "NW-2 is located on the Brahmaputra River.",
    explanation_hi: "NW-2 ब्रह्मपुत्र नदी पर स्थित है।",
  },
  {
    question_en: "What is the total length of the Golden Quadrilateral highway project?",
    question_hi: "स्वर्णिम चतुर्भुज (Golden Quadrilateral) राजमार्ग परियोजना की कुल लंबाई कितनी है?",
    options_en: ["4237 km", "3806 km", "5846 km", "6100 km"],
    options_hi: ["4237 किमी", "3806 किमी", "5846 किमी", "6100 किमी"],
    correct_option_index: 2,
    explanation_en: "The total length of the Golden Quadrilateral (connecting Delhi, Mumbai, Chennai, Kolkata) is 5846 km.",
    explanation_hi: "स्वर्णिम चतुर्भुज (दिल्ली, मुंबई, चेन्नई, कोलकाता को जोड़ता है) की कुल लंबाई 5846 किमी है।",
  },
  {
    question_en: "Which two places are connected by the North-South Corridor?",
    question_hi: "उत्तर-दक्षिण गलियारा (North-West Corridor) किन दो स्थानों को जोड़ता है?",
    options_en: ["Porbandar (Gujarat) and Silchar (Assam)", "Srinagar (JK) and Kanyakumari (Tamil Nadu)", "Delhi and Mumbai", "Kolkata and Chennai"],
    options_hi: ["पोरबंदर (गुजरात) और सिलचर (असम)", "श्रीनगर (JK) और कन्याकुमारी (तमिलनाडु)", "दिल्ली और मुंबई", "कोलकाता और चेन्नई"],
    correct_option_index: 1,
    explanation_en: "The North-South Corridor connects Srinagar to Kanyakumari.",
    explanation_hi: "उत्तर-दक्षिण गलियारा श्रीनगर को कन्याकुमारी से जोड़ता है।",
  },
  {
    question_en: "Where is the longest railway route in India from and to?",
    question_hi: "भारत का सबसे लंबा रेलमार्ग (Longest Railway Route) कहाँ से कहाँ तक है?",
    options_en: ["Delhi to Chennai", "Mumbai to Kolkata", "Dibrugarh (Assam) to Kanyakumari", "Amritsar to Mumbai"],
    options_hi: ["दिल्ली से चेन्नई", "मुंबई से कोलकाता", "डिब्रूगढ़ (असम) से कन्याकुमारी", "अमृतसर से मुंबई"],
    correct_option_index: 2,
    explanation_en: "India's longest railway route (4237 km) is from Dibrugarh to Kanyakumari, covered by the Vivek Express.",
    explanation_hi: "भारत का सबसे लंबा रेलमार्ग (4237 किमी) डिब्रूगढ़ से कन्याकुमारी तक है, जिसे विवेक एक्सप्रेस द्वारा कवर किया जाता है।",
  },
  {
    question_en: "Which railway station, which was India's first privately managed station, has been renamed as Rani Kamlapati Railway Station?",
    question_hi: "किस रेलवे स्टेशन का नाम बदलकर रानी कमलापति रेलवे स्टेशन कर दिया गया है, जो भारत का पहला निजी तौर पर प्रबंधित स्टेशन था?",
    options_en: ["Gorakhpur Junction", "Mumbai Central", "Habibganj Railway Station (Bhopal)", "Vadodara Station"],
    options_hi: ["गोरखपुर जंक्शन", "मुंबई सेंट्रल", "हबीबगंज रेलवे स्टेशन (भोपाल)", "वडोदरा स्टेशन"],
    correct_option_index: 2,
    explanation_en: "Habibganj Railway Station (Bhopal, MP) was India's first privately managed railway station, whose new name is Rani Kamlapati Railway Station.",
    explanation_hi: "हबीबगंज रेलवे स्टेशन (भोपाल, MP) भारत का पहला निजी तौर पर प्रबंधित रेलवे स्टेशन था, जिसका नया नाम रानी कमलापति रेलवे स्टेशन है।",
  },
  {
    question_en: "Which is the cheapest means of transport?",
    question_hi: "परिवहन का सबसे सस्ता साधन (Cheapest means of transport) कौन सा है?",
    options_en: ["Roadways", "Railways", "Waterways", "Airways"],
    options_hi: ["सड़क मार्ग", "रेल मार्ग", "जलमार्ग (Waterways)", "वायुमार्ग"],
    correct_option_index: 2,
    explanation_en: "Waterways are the cheapest means of transport.",
    explanation_hi: "जलमार्ग परिवहन का सबसे सस्ता साधन है।",
  },
  {
    question_en: "What was the main objective of the 'Setu Bharatam Program'?",
    question_hi: "'सेतुभारतम कार्यक्रम' का मुख्य लक्ष्य क्या था?",
    options_en: ["To build new highways", "Modernization of ports", "To free National Highways from railway level crossings", "To improve the quality of roads"],
    options_hi: ["नए राजमार्ग बनाना", "बंदरगाहों का आधुनिकीकरण", "राष्ट्रीय राजमार्गों को रेलवे पुल क्रॉसिंग से मुक्त करना", "सड़कों की गुणवत्ता सुधारना"],
    correct_option_index: 2,
    explanation_en: "The goal of the Setu Bharatam Program (2016) was to free all National Highways from railway level crossings by 2019.",
    explanation_hi: "सेतुभारतम कार्यक्रम (2016) का लक्ष्य 2019 तक सभी राष्ट्रीय राजमार्गों को रेलवे पुल क्रॉसिंग से मुक्त करना था।",
  },
  {
    question_en: "Where is Veer Savarkar International Airport located?",
    question_hi: "वीर सावरकर अंतर्राष्ट्रीय हवाई अड्डा कहाँ स्थित है?",
    options_en: ["Mumbai", "Delhi", "Port Blair (Andaman Nicobar)", "Goa"],
    options_hi: ["मुंबई", "दिल्ली", "पोर्ट ब्लेयर (अंडमान निकोबार)", "गोवा"],
    correct_option_index: 2,
    explanation_en: "Veer Savarkar International Airport is located in Port Blair, Andaman and Nicobar Islands.",
    explanation_hi: "वीर सावरकर अंतर्राष्ट्रीय हवाई अड्डा पोर्ट ब्लेयर, अंडमान और निकोबार द्वीप समूह में स्थित है।",
  },
  {
    question_en: "Where is Kempegowda International Airport located?",
    question_hi: "केम्पेगौड़ा अंतर्राष्ट्रीय हवाई अड्डा (Kempegowda International Airport) कहाँ स्थित है?",
    options_en: ["Hyderabad", "Chennai", "Bengaluru (Karnataka)", "Mangalore"],
    options_hi: ["हैदराबाद", "चेन्नई", "बेंगलुरु (कर्नाटक)", "मंगलौर"],
    correct_option_index: 2,
    explanation_en: "Kempegowda International Airport is located in Bengaluru, Karnataka.",
    explanation_hi: "केम्पेगौड़ा अंतर्राष्ट्रीय हवाई अड्डा बेंगलुरु, कर्नाटक में स्थित है।",
  },
  {
    question_en: "Lokpriya Gopinath Bordoloi International Airport is in which city?",
    question_hi: "लोकप्रिया गोपीनाथ बोरदोलोई अंतर्राष्ट्रीय हवाई अड्डा किस शहर में है?",
    options_en: ["Imphal", "Siliguri", "Guwahati (Assam)", "Patna"],
    options_hi: ["इम्फाल", "सिलिगुड़ी", "गुवाहाटी (असम)", "पटना"],
    correct_option_index: 2,
    explanation_en: "Lokpriya Gopinath Bordoloi International Airport is located in Guwahati, Assam.",
    explanation_hi: "लोकप्रिया गोपीनाथ बोरदोलोई अंतर्राष्ट्रीय हवाई अड्डा गुवाहाटी, असम में स्थित है।",
  },
  {
    question_en: "By what name is Raja Sansi International Airport known and where is it located?",
    question_hi: "राजा सांसी अंतर्राष्ट्रीय हवाई अड्डा किस नाम से जाना जाता है और कहाँ स्थित है?",
    options_en: ["Sri Guru Ram Dass Jee International Airport, Amritsar", "Sardar Vallabh Bhai Patel International Airport, Ahmedabad", "Devi Ahilya Bai Holkar Airport, Indore", "Jay Prakash Narayan International Airport, Patna"],
    options_hi: ["गुरु रामदास जी अंतर्राष्ट्रीय हवाई अड्डा, अमृतसर", "सरदार वल्लभ भाई पटेल अंतर्राष्ट्रीय हवाई अड्डा, अहमदाबाद", "देवी अहिल्या बाई होल्कर हवाई अड्डा, इंदौर", "जय प्रकाश नारायण अंतर्राष्ट्रीय हवाई अड्डा, पटना"],
    correct_option_index: 0,
    explanation_en: "Raja Sansi International Airport is now known as Sri Guru Ram Dass Jee International Airport, located in Amritsar, Punjab.",
    explanation_hi: "राजा सांसी अंतर्राष्ट्रीय हवाई अड्डा अब श्री गुरु रामदास जी अंतर्राष्ट्रीय हवाई अड्डा, अमृतसर, पंजाब के नाम से जाना जाता है।",
  },
  {
    question_en: "What was the motto of Census 2011?",
    question_hi: "जनगणना 2011 का आदर्श वाक्य (Motto) क्या था?",
    options_en: ["One Census, One Future", "Our Census, Our Future", "Census and Development", "Population of India 2011"],
    options_hi: ["एक जनगणना, एक भविष्य", "हमारी जनगणना, हमारा भविष्य (Our Population, Our Future)", "जनगणना और विकास", "भारत की जनसंख्या 2011"],
    correct_option_index: 1,
    explanation_en: "The motto of the 2011 census was: 'Our Census, Our Future'.",
    explanation_hi: "2011 की जनगणना का आदर्श वाक्य था: 'हमारी जनगणना, हमारा भविष्य'।",
  },
  {
    question_en: "In which year did the regular census begin in India?",
    question_hi: "भारत में नियमित जनगणना (Regular Census) की शुरुआत किस वर्ष हुई थी?",
    options_en: ["1872", "1881", "1951", "1901"],
    options_hi: ["1872", "1881", "1951", "1901"],
    correct_option_index: 1,
    explanation_en: "The regular census in the country started in 1881 during the tenure of Lord Ripon.",
    explanation_hi: "देश में नियमित जनगणना की शुरुआत 1881 में लॉर्ड रिपन के कार्यकाल में हुई।",
  },
  {
    question_en: "In which year was the first census of India held after independence?",
    question_hi: "स्वतंत्रता के बाद भारत की पहली जनगणना किस वर्ष हुई थी?",
    options_en: ["1947", "1951", "1961", "1971"],
    options_hi: ["1947", "1951", "1961", "1971"],
    correct_option_index: 1,
    explanation_en: "The first census of India after independence was held in 1951.",
    explanation_hi: "स्वतंत्रता के बाद भारत की पहली जनगणना 1951 में हुई थी।",
  },
  {
    question_en: "What was the Sex Ratio of India per 1000 males according to Census 2011?",
    question_hi: "2011 की जनगणना के अनुसार भारत का लिंगानुपात (Sex Ratio) प्रति 1000 पुरुषों पर कितना था?",
    options_en: ["933", "943", "919", "950"],
    options_hi: ["933", "943", "919", "950"],
    correct_option_index: 1,
    explanation_en: "According to the 2011 census, the Sex Ratio of India was 943 per 1000 males.",
    explanation_hi: "2011 जनगणना के अनुसार भारत का लिंगानुपात 943 था।",
  },
  {
    question_en: "Which state had the lowest Sex Ratio according to Census 2011?",
    question_hi: "जनगणना 2011 के अनुसार भारत में न्यूनतम लिंगानुपात वाला राज्य कौन सा है?",
    options_en: ["Jammu and Kashmir", "Sikkim", "Haryana (879)", "Punjab"],
    options_hi: ["जम्मू-कश्मीर", "सिक्किम", "हरियाणा (879)", "पंजाब"],
    correct_option_index: 2,
    explanation_en: "The state with the lowest Sex Ratio was Haryana (879).",
    explanation_hi: "न्यूनतम लिंगानुपात वाला राज्य हरियाणा (879) था।",
  },
  {
    question_en: "What was the Literacy Rate of India according to Census 2011?",
    question_hi: "2011 जनगणना के अनुसार भारत की साक्षरता दर (Literacy Rate) कितनी थी?",
    options_en: ["64.83%", "73.0%", "80.9%", "64.6%"],
    options_hi: ["64.83%", "73.0%", "80.9%", "64.6%"],
    correct_option_index: 1,
    explanation_en: "India's literacy rate was 73.0%.",
    explanation_hi: "भारत की साक्षरता दर 73.0% थी।",
  },
  {
    question_en: "Which is the most populous state according to Census 2011?",
    question_hi: "जनगणना 2011 के अनुसार सर्वाधिक जनसंख्या वाला राज्य कौन सा है?",
    options_en: ["Maharashtra", "Bihar", "West Bengal", "Uttar Pradesh (UP)"],
    options_hi: ["महाराष्ट्र", "बिहार", "पश्चिम बंगाल", "उत्तर प्रदेश (UP)"],
    correct_option_index: 3,
    explanation_en: "The most populous state was Uttar Pradesh (19.98 crore).",
    explanation_hi: "सर्वाधिक जनसंख्या वाला राज्य उत्तर प्रदेश था (19.98 करोड़)।",
  },
  {
    question_en: "Which state had the lowest population according to Census 2011?",
    question_hi: "2011 जनगणना के अनुसार न्यूनतम जनसंख्या वाला राज्य कौन सा है?",
    options_en: ["Mizoram", "Arunachal Pradesh", "Sikkim", "Goa"],
    options_hi: ["मिजोरम", "अरुणाचल प्रदेश", "सिक्किम", "गोवा"],
    correct_option_index: 2,
    explanation_en: "The state with the lowest population was Sikkim (6.10 lakh).",
    explanation_hi: "न्यूनतम जनसंख्या वाला राज्य सिक्किम (6.10 लाख) था।",
  },
  {
    question_en: "Which Union Territory has the highest Sex Ratio?",
    question_hi: "सर्वाधिक लिंगानुपात (Highest Sex Ratio) वाला केंद्र शासित प्रदेश कौन सा है?",
    options_en: ["Lakshadweep", "Andaman and Nicobar", "Chandigarh", "Puducherry (1037)"],
    options_hi: ["लक्षद्वीप", "अंडमान और निकोबार", "चंडीगढ़", "पुडुचेरी (1037)"],
    correct_option_index: 3,
    explanation_en: "The Union Territory with the highest Sex Ratio is Puducherry (1037).",
    explanation_hi: "सर्वाधिक लिंगानुपात वाला केंद्र शासित प्रदेश पुडुचेरी (1037) है।",
  },
  {
    question_en: "Which state has the Highest Literacy Rate?",
    question_hi: "सर्वाधिक साक्षरता दर (Highest Literacy Rate) वाला राज्य कौन सा है?",
    options_en: ["Mizoram", "Goa", "Tripura", "Kerala (94%)"],
    options_hi: ["मिजोरम", "गोवा", "त्रिपुरा", "केरल (94%)"],
    correct_option_index: 3,
    explanation_en: "The state with the highest literacy rate is Kerala (94%).",
    explanation_hi: "सर्वाधिक साक्षरता दर वाला राज्य केरल (94%) है।",
  },
  {
    question_en: "Which Union Territory has the highest Literacy Rate according to Census 2011?",
    question_hi: "2011 जनगणना के अनुसार सर्वाधिक साक्षरता दर वाला केंद्र शासित प्रदेश कौन सा है?",
    options_en: ["Daman and Diu", "Andaman and Nicobar", "Chandigarh", "Lakshadweep (91.8%)"],
    options_hi: ["दमन और दीव", "अंडमान और निकोबार", "चंडीगढ़", "लक्षद्वीप (91.8%)"],
    correct_option_index: 3,
    explanation_en: "The Union Territory with the highest literacy rate is Lakshadweep (91.8%).",
    explanation_hi: "सर्वाधिक साक्षरता दर वाला केंद्र शासित प्रदेश लक्षद्वीप (91.8%) है।",
  },
  {
    question_en: "Which state has the lowest Literacy Rate?",
    question_hi: "न्यूनतम साक्षरता दर वाला राज्य कौन सा है?",
    options_en: ["Arunachal Pradesh", "Jharkhand", "Rajasthan", "Bihar (61%)"],
    options_hi: ["अरुणाचल प्रदेश", "झारखंड", "राजस्थान", "बिहार (61%)"],
    correct_option_index: 3,
    explanation_en: "The state with the lowest literacy rate is Bihar (61%).",
    explanation_hi: "न्यूनतम साक्षरता दर वाला राज्य बिहार (61%) है।",
  },
  {
    question_en: "Which state has the highest Scheduled Tribe (ST) population in India?",
    question_hi: "भारत में सर्वाधिक अनुसूचित जनजाति (ST) जनसंख्या वाला राज्य कौन सा है?",
    options_en: ["Maharashtra", "Odisha", "Chhattisgarh", "Madhya Pradesh"],
    options_hi: ["महाराष्ट्र", "ओडिशा", "छत्तीसगढ़", "मध्य प्रदेश"],
    correct_option_index: 3,
    explanation_en: "The state with the highest Scheduled Tribe (ST) population is Madhya Pradesh.",
    explanation_hi: "सर्वाधिक अनुसूचित जनजाति (ST) जनसंख्या वाला राज्य मध्य प्रदेश है।",
  },
  {
    question_en: "In which months are Rabi crops sown?",
    question_hi: "रबी की फसलों की बुवाई किस महीने में की जाती है?",
    options_en: ["July-August", "March-April", "October-November", "June-July"],
    options_hi: ["जुलाई-अगस्त", "मार्च-अप्रैल", "अक्टूबर-नवंबर", "जून-जुलाई"],
    correct_option_index: 2,
    explanation_en: "Rabi crops are sown in October-November and harvested in March-April.",
    explanation_hi: "रबी की फसलें अक्टूबर-नवंबर में बोई जाती हैं और मार्च-अप्रैल में काटी जाती हैं।",
  },
  {
    question_en: "Wheat, barley, gram, peas, and mustard are mainly crops of which season?",
    question_hi: "गेहूँ, जौ, चना, मटर, और सरसों मुख्य रूप से किस मौसम की फसलें हैं?",
    options_en: ["Kharif", "Zaid", "Rabi", "Horticulture"],
    options_hi: ["खरीफ", "जायद", "रबी", "बागवानी"],
    correct_option_index: 2,
    explanation_en: "All these are Rabi crops, sown in winter.",
    explanation_hi: "ये सभी रबी की फसलें हैं, जो सर्दियों में बोई जाती हैं।",
  },
  {
    question_en: "Kharif crops benefit from which monsoon?",
    question_hi: "खरीफ की फसलें किस मानसून से लाभान्वित होती हैं?",
    options_en: ["North-East Monsoon", "Western Disturbances", "South-West Monsoon", "Mediterranean Cyclone"],
    options_hi: ["उत्तर-पूर्वी मानसून", "पश्चिमी विक्षोभ", "दक्षिण-पश्चिम मानसून", "भूमध्यसागरीय चक्रवात"],
    correct_option_index: 2,
    explanation_en: "Kharif crops (paddy, soybean, cotton) benefit from the South-West Monsoon.",
    explanation_hi: "खरीफ की फसलें (धान, सोयाबीन, कपास) दक्षिण-पश्चिम मानसून से लाभान्वित होती हैं।",
  },
  {
    question_en: "Cucumber, gourd, watermelon, and pumpkin are examples of which type of crops?",
    question_hi: "खीरा, ककड़ी, तरबूज और कद्दू किस प्रकार की फसलों के उदाहरण हैं?",
    options_en: ["Rabi crop", "Kharif crop", "Zaid crop", "Horticulture crop"],
    options_hi: ["रबी फसल", "खरीफ फसल", "जायद फसल", "बागवानी फसल"],
    correct_option_index: 2,
    explanation_en: "All these are Zaid crops, which are sown in March (between Rabi and Kharif).",
    explanation_hi: "ये सभी जायद की फसलें हैं, जो मार्च में बोई जाती हैं (रबी और खरीफ के बीच)।",
  },
  {
    question_en: "Which of the following is a Cash Crop?",
    question_hi: "निम्नलिखित में से कौन सी नकदी फसल (Cash Crop) है?",
    options_en: ["Wheat", "Rice", "Sugarcane", "Jowar"],
    options_hi: ["गेहूँ", "चावल", "गन्ना (Sugarcane)", "ज्वार"],
    correct_option_index: 2,
    explanation_en: "Cash crops include cotton, jute, sugarcane, and tobacco.",
    explanation_hi: "नकदी फसलों में कपास, जूट, गन्ना और तंबाकू शामिल हैं।",
  },
  {
    question_en: "Where is the headquarters of the Coffee Board located?",
    question_hi: "कॉफी बोर्ड (Coffee Board) का मुख्यालय कहाँ स्थित है?",
    options_en: ["Kottayam (Kerala)", "Kolkata (WB)", "Bengaluru (Karnataka)", "Guntur (AP)"],
    options_hi: ["कोट्टायम (केरल)", "कोलकाता (WB)", "बेंगलुरु (कर्नाटक)", "गुंटूर (AP)"],
    correct_option_index: 2,
    explanation_en: "The headquarters of the Coffee Board is located in Bengaluru, Karnataka.",
    explanation_hi: "कॉफी बोर्ड का मुख्यालय बेंगलुरु, कर्नाटक में स्थित है।",
  },
  {
    question_en: "What is the rearing of silkworms called?",
    question_hi: "रेशम कीट पालन (Rearing of silkworms) को क्या कहा जाता है?",
    options_en: ["Apiculture", "Viticulture", "Floriculture", "Sericulture"],
    options_hi: ["एपीकल्चर", "विटीकल्चर", "फ्लोरीकल्चर", "सेरीकल्चर (Sericulture)"],
    correct_option_index: 3,
    explanation_en: "The rearing of silkworms for the production of raw silk is called Sericulture.",
    explanation_hi: "रेशम कीट पालन को सेरीकल्चर कहा जाता है।",
  },
  {
    question_en: "Blue Revolution is related to the production of which of the following?",
    question_hi: "नीली क्रांति (Blue Revolution) का संबंध किसके उत्पादन से है?",
    options_en: ["Petroleum", "Onion", "Horticulture", "Fish/Fisheries production"],
    options_hi: ["पेट्रोलियम", "प्याज", "बागवानी", "मछली/मत्स्य उत्पादन"],
    correct_option_index: 3,
    explanation_en: "Blue Revolution is related to the production of fish and fisheries.",
    explanation_hi: "नीली क्रांति मछली उत्पादन से संबंधित है।",
  },
  {
    question_en: "Brown Revolution is related to which of the following?",
    question_hi: "भूरी क्रांति (Brown Revolution) किससे संबंधित है?",
    options_en: ["Potatoes", "Oilseeds", "Leather / Cocoa products", "Fertilizers"],
    options_hi: ["आलू", "तिलहन", "चमड़ा / कोको उत्पाद", "उर्वरक"],
    correct_option_index: 2,
    explanation_en: "Brown Revolution is related to leather and cocoa products.",
    explanation_hi: "भूरी क्रांति चमड़ा और कोको उत्पाद से संबंधित है।",
  },
  {
    question_en: "Who is considered the father of the White Revolution in India?",
    question_hi: "भारत में श्वेत क्रांति (White Revolution) के जनक कौन माने जाते हैं?",
    options_en: ["M.S. Swaminathan", "Dr. Norman Borlaug", "Dr. Verghese Kurien", "Dr. William Gaud"],
    options_hi: ["एम.एस. स्वामीनाथन", "डॉ. नॉर्मन बोरलॉग", "डॉ. वर्गीस कुरियन (Dr. Verghese Kurien)", "डॉ. विलियम गौड"],
    correct_option_index: 2,
    explanation_en: "Dr. Verghese Kurien is the father of the White Revolution (Milk Production).",
    explanation_hi: "श्वेत क्रांति (दूध उत्पादन) के जनक डॉ. वर्गीस कुरियन हैं।",
  },
  {
    question_en: "Who is the father of the Green Revolution in the world, who received the Nobel Peace Prize in 1970?",
    question_hi: "विश्व में हरित क्रांति (Green Revolution) के जनक कौन हैं, जिन्हें 1970 में शांति का नोबेल पुरस्कार मिला था?",
    options_en: ["M.S. Swaminathan", "Dr. Verghese Kurien", "Dr. Norman Borlaug", "William Gaud"],
    options_hi: ["एम.एस. स्वामीनाथन", "डॉ. वर्गीस कुरियन", "डॉ. नॉर्मन बोरलॉग", "विलियम गौड"],
    correct_option_index: 2,
    explanation_en: "Dr. Norman Borlaug is the father of the Green Revolution in the world.",
    explanation_hi: "विश्व में हरित क्रांति के जनक डॉ. नॉर्मन बोरलॉग हैं।",
  },
  {
    question_en: "By what name is shifting cultivation known in Manipur?",
    question_hi: "स्थान्तरित कृषि (Shifting cultivation) को मणिपुर में किस नाम से जाना जाता है?",
    options_en: ["Jhum", "Kuruwal", "Bewar", "Pomlu"],
    options_hi: ["झूम", "कुरूवाल", "बेवर", "पोम्लू (Pomlu)"],
    correct_option_index: 3,
    explanation_en: "Shifting cultivation is called Pomlu in Manipur and Podu or Pondu in Andhra Pradesh.",
    explanation_hi: "स्थान्तरित कृषि को मणिपुर में पोम्लू और आंध्र प्रदेश में पोडु या पोंडू कहते हैं।",
  },
  {
    question_en: "What is the biggest source of irrigation in India after wells and tube wells?",
    question_hi: "भारत में सिंचाई का सबसे बड़ा साधन कुओं और नलकूपों के बाद कौन सा है?",
    options_en: ["Rainwater", "Ponds", "Canals", "Sprinklers"],
    options_hi: ["वर्षा जल", "तालाब", "नहर", "स्प्रिंकलर"],
    correct_option_index: 2,
    explanation_en: "After wells and tube wells, canals are the largest source of irrigation in India.",
    explanation_hi: "कुओं और नलकूपों के बाद भारत में सिंचाई का सबसे बड़ा साधन नहर है।",
  },
  {
    question_en: "In the continent of Asia, which of the following countries has 'Hanoi' as its capital?",
    question_hi: "एशिया महाद्वीप में, निम्नलिखित में से किस देश की राजधानी 'हनोई' (Hanoi) है?",
    options_en: ["Thailand", "Myanmar", "Vietnam", "Laos"],
    options_hi: ["थाईलैंड", "म्यांमार", "वियतनाम", "लाओस"],
    correct_option_index: 2,
    explanation_en: "Hanoi is the capital of Vietnam.",
    explanation_hi: "वियतनाम की राजधानी हनोई है।",
  },
  {
    question_en: "What is the new name of Kazakhstan's capital 'Nur-Sultan'?",
    question_hi: "कजाकिस्तान की राजधानी 'नूर-सुल्तान' का नया नाम क्या है?",
    options_en: ["Astana", "Tashkent", "Baku", "Nur-Sultan"],
    options_hi: ["अस्ताना", "ताशकंद", "बाकू", "नूर-सुल्तान"],
    correct_option_index: 0,
    explanation_en: "The name of the capital of Kazakhstan is Astana (previously Nur-Sultan and before that Astana). The user input is incorrect in stating the new name is Nur-Sultan. The latest name is Astana.",
    explanation_hi: "कजाकिस्तान की राजधानी का नाम अस्ताना (पहले नूर-सुल्तान और उससे पहले अस्ताना) है। उपयोगकर्ता का इनपुट गलत है, जिसमें कहा गया है कि नया नाम नूर-सुल्तान है। नवीनतम नाम अस्ताना है।",
  },
  {
    question_en: "Where is 'Taurus Mt.' located, from where many rivers of Turkey and Syria originate?",
    question_hi: "'तोरस पर्वत' (Taurus Mt.) कहाँ स्थित है, जहाँ से तुर्की और सीरिया की कई नदियों का उद्गम होता है?",
    options_en: ["Iran", "Iraq", "Turkey", "Syria"],
    options_hi: ["ईरान", "इराक", "तुर्की (Turkey)", "सीरिया"],
    correct_option_index: 2,
    explanation_en: "Taurus Mt. is located in Turkey.",
    explanation_hi: "तोरस पर्वत तुर्की में स्थित है।",
  },
  {
    question_en: "Which is the longest river in Asia?",
    question_hi: "एशिया की सबसे लंबी नदी (Longest River in Asia) कौन सी है?",
    options_en: ["Helmand River", "Brahmaputra", "Mekong River", "Yangtze River"],
    options_hi: ["हेलमंद नदी", "ब्रह्मपुत्र", "मीकांग नदी", "यांग्त्सीक्यांग नदी (Yangtse River)"],
    correct_option_index: 3,
    explanation_en: "The Yangtze River in China is the longest river in Asia and the third longest in the world.",
    explanation_hi: "चीन की यांग्त्सीक्यांग नदी एशिया की सबसे लंबी नदी है और विश्व की तीसरी सबसे लंबी नदी है।",
  },
  {
    question_en: "Where is the 'Rub' al Khali' desert located?",
    question_hi: "'रब-अल-खाली' (Rub-Al-Khali) मरुस्थल कहाँ स्थित है?",
    options_en: ["China", "Iran", "Mongolia", "Saudi Arabia"],
    options_hi: ["चीन", "ईरान", "मंगोलिया", "सऊदी अरब"],
    correct_option_index: 3,
    explanation_en: "Rub' al Khali is a hot desert located in Saudi Arabia, part of the Arabian Desert.",
    explanation_hi: "रब-अल-खाली एक गर्म मरुस्थल है जो सऊदी अरब में स्थित है, जो अरब रेगिस्तान का हिस्सा है।",
  },
  {
    question_en: "The Caspian Sea, the world's largest saltwater lake, is surrounded by how many countries?",
    question_hi: "कैस्पियन सागर (Caspian Sea) विश्व की सबसे बड़ी खारे पानी की झील है, यह कितने देशों से घिरा है?",
    options_en: ["4", "5", "6", "7"],
    options_hi: ["4", "5", "6", "7"],
    correct_option_index: 1,
    explanation_en: "The Caspian Sea is surrounded by 5 countries: Kazakhstan, Iran, Russia, Azerbaijan, and Turkmenistan (KIRAT).",
    explanation_hi: "कैस्पियन सागर 5 देशों (कजाकिस्तान, ईरान, रूस, अजरबैजान, तुर्कमेनिस्तान) से घिरा है।",
  },
  {
    question_en: "Where is Lake Baikal, the world's deepest lake, located?",
    question_hi: "विश्व की सबसे गहरी झील (Deepest Lake) बैकाल झील कहाँ स्थित है?",
    options_en: ["Kazakhstan", "Canada", "Russia", "Tanzania"],
    options_hi: ["कजाकिस्तान", "कनाडा", "रूस (Russia)", "तंजानिया"],
    correct_option_index: 2,
    explanation_en: "Lake Baikal is located in Russia, in southern Siberia.",
    explanation_hi: "बैकाल झील रूस में स्थित है।",
  },
  {
    question_en: "What is the 'Tibet Plateau' known as?",
    question_hi: "'तिब्बत का पठार' (Tibet Plateau) किस रूप में जाना जाता है?",
    options_en: ["Desert of the World", "Roof of the World", "Storehouse of Asia", "Plain of Siberia"],
    options_hi: ["दुनिया का रेगिस्तान", "विश्व की छत (Roof of the World)", "एशिया का भंडार", "साइबेरिया का मैदान"],
    correct_option_index: 1,
    explanation_en: "The Tibet Plateau is also called the 'Roof of the World'.",
    explanation_hi: "तिब्बत के पठार को 'विश्व की छत' भी कहा जाता है।",
  },
  {
    question_en: "Which is the second largest continent, through which the Tropic of Cancer, Tropic of Capricorn, and Equator all pass?",
    question_hi: "अफ्रीका का दूसरा सबसे बड़ा महाद्वीप (Second largest continent) कौन सा है, जिससे कर्क, मकर और भूमध्य तीनों रेखाएं गुजरती हैं?",
    options_en: ["Asia", "North America", "Africa", "South America"],
    options_hi: ["एशिया", "उत्तरी अमेरिका", "अफ्रीका", "दक्षिण अमेरिका"],
    correct_option_index: 2,
    explanation_en: "Africa is the second largest continent, through which the Tropic of Cancer, Tropic of Capricorn, and Equator all pass.",
    explanation_hi: "अफ्रीका दूसरा सबसे बड़ा महाद्वीप है जिससे कर्क, मकर और विषुवत तीनों रेखाएं गुजरती हैं।",
  },
  {
    question_en: "Lake Victoria is the largest lake in Africa, which major latitude line passes through it?",
    question_hi: "विक्टोरिया झील (Lake Victoria) अफ्रीका की सबसे बड़ी झील है, इससे कौन सी प्रमुख अक्षांश रेखा गुजरती है?",
    options_en: ["Tropic of Cancer", "Tropic of Capricorn", "Equator", "0° Longitude"],
    options_hi: ["कर्क रेखा", "मकर रेखा", "विषुवत रेखा (Equator)", "0° देशांतर"],
    correct_option_index: 2,
    explanation_en: "The Equator passes through Lake Victoria.",
    explanation_hi: "विक्टोरिया झील से विषुवत रेखा गुजरती है।",
  },
  {
    question_en: "What is the characteristic of the 'Congo River' (Congo/Zaire River)?",
    question_hi: "'कांगो नदी' (Congo/Zaire River) की विशेषता क्या है?",
    options_en: ["It crosses the Tropic of Capricorn twice.", "It is a tributary of the Nile River.", "It crosses the Equator twice.", "It is the longest river in the world."],
    options_hi: ["यह मकर रेखा को दो बार काटती है।", "यह नील नदी की सहायक है।", "यह विषुवत रेखा को दो बार काटती है।", "यह विश्व की सबसे लंबी नदी है।"],
    correct_option_index: 2,
    explanation_en: "The Congo (Zaire) River crosses the Equator twice.",
    explanation_hi: "कांगो (जायरे) नदी विषुवत रेखा को दो बार काटती है।",
  },
  {
    question_en: "Which river crosses the Tropic of Capricorn twice?",
    question_hi: "कौन सी नदी मकर रेखा (Tropic of Capricorn) को दो बार काटती है?",
    options_en: ["Congo River", "Niger River", "Volta River", "Limpopo River"],
    options_hi: ["कांगो नदी", "नाइजर नदी", "वोल्टा नदी", "लिम्पोपो नदी (Limpopo River)"],
    correct_option_index: 3,
    explanation_en: "The Limpopo River crosses the Tropic of Capricorn twice.",
    explanation_hi: "लिम्पोपो नदी मकर रेखा को दो बार काटती है।",
  },
  {
    question_en: "In the continent of North America, the boundary between Canada and the USA is determined by which latitude line?",
    question_hi: "उत्तरी अमेरिका महाद्वीप में कनाडा और USA की सीमा किस अक्षांश रेखा द्वारा निर्धारित होती है?",
    options_en: ["23.5° N Latitude", "38° N Latitude", "49° N Latitude", "66.5° N Latitude"],
    options_hi: ["23.5° उत्तरी अक्षांश", "38° उत्तरी अक्षांश", "49° उत्तरी अक्षांश", "66.5° उत्तरी अक्षांश"],
    correct_option_index: 2,
    explanation_en: "The 49° North Latitude line determines the boundary between Canada and the USA.",
    explanation_hi: "49° उत्तरी अक्षांश रेखा कनाडा और USA की सीमा निर्धारित करती है।",
  },
  {
    question_en: "Where is 'Death Valley' or Mojave Desert located?",
    question_hi: "'डेथ वैली' (Death Valley) या मोहवे/मोजेव मरुस्थल कहाँ स्थित है?",
    options_en: ["Mexico", "Arizona", "North America", "California, USA"],
    options_hi: ["मेक्सिको", "एरिजोना", "उत्तरी अमेरिका", "USA के कैलिफ़ोर्निया में"],
    correct_option_index: 3,
    explanation_en: "The Mojave Desert and Death Valley are located in California, USA.",
    explanation_hi: "मोहवे मरुस्थल और डेथ वैली USA के कैलिफ़ोर्निया में स्थित है।",
  },
  {
    question_en: "The Great Lakes - Lake Superior, Lake Michigan, Lake Huron, Lake Erie, and Lake Ontario - are located on the border of which two countries?",
    question_hi: "महान झीलें (Great Lakes) सुपीरियर झील, मिशिगन झील, ह्यूरन झील, ईरी झील और ओंटारियो झील किन दो देशों की सीमा पर स्थित हैं?",
    options_en: ["Canada and Mexico", "Canada and Alaska", "USA and Canada", "USA and Mexico"],
    options_hi: ["कनाडा और मैक्सिको", "कनाडा और अलास्का", "USA और कनाडा", "USA और मैक्सिको"],
    correct_option_index: 2,
    explanation_en: "The 5 Great Lakes (only Michigan is entirely in the USA) are located on the border of the USA and Canada.",
    explanation_hi: "5 महान झीलें (केवल मिशिगन USA में है) USA और कनाडा की सीमा पर स्थित हैं।",
  },
  {
    question_en: "Which is the largest fresh water lake in the world?",
    question_hi: "विश्व की सबसे बड़ी मीठे पानी की झील (Largest fresh water lake in the world) कौन सी है?",
    options_en: ["Great Slave Lake", "Lake Michigan", "Lake Superior", "Lake Victoria"],
    options_hi: ["ग्रेट स्लेव झील", "मिशिगन झील", "सुपीरियर झील (Lake Superior)", "विक्टोरिया झील"],
    correct_option_index: 2,
    explanation_en: "Lake Superior is the largest freshwater lake in the world by surface area.",
    explanation_hi: "सुपीरियर झील क्षेत्रफल के हिसाब से विश्व में मीठे पानी की सबसे बड़ी झील है।",
  },
  {
    question_en: "Which is the largest country in South America?",
    question_hi: "दक्षिण अमेरिका का सबसे बड़ा देश कौन सा है?",
    options_en: ["Argentina", "Chile", "Colombia", "Brazil"],
    options_hi: ["अर्जेंटीना", "चिली", "कोलंबिया", "ब्राजील"],
    correct_option_index: 3,
    explanation_en: "Brazil is the largest country in the continent of South America by both area and population.",
    explanation_hi: "ब्राजील क्षेत्रफल और जनसंख्या दोनों की दृष्टि से दक्षिण अमेरिका महाद्वीप का सबसे बड़ा देश है।",
  },
  {
    question_en: "Where is Aconcagua, the highest peak of the Andes Mountains, located?",
    question_hi: "एंडीज पर्वत शृंखला (Andes Mountains) की सबसे ऊँची चोटी अकांकागुआ (Aconcagua) कहाँ स्थित है?",
    options_en: ["Chile", "Ecuador", "Argentina", "Peru"],
    options_hi: ["चिली", "इक्वाडोर", "अर्जेंटीना", "पेरू"],
    correct_option_index: 2,
    explanation_en: "Aconcagua (6961 m, not 6992 m) is located in Argentina.",
    explanation_hi: "अकांकागुआ (6961 मी.) अर्जेंटीना में स्थित है।",
  },
  {
    question_en: "The Amazon River, the largest river in the world by discharge volume, drains into which body of water?",
    question_hi: "अमेज़न नदी (Amazon River), जो अपवाह क्षमता की दृष्टि से विश्व की सबसे बड़ी नदी है, कहाँ गिरती है?",
    options_en: ["Pacific Ocean", "Caribbean Sea", "Atlantic Ocean", "Gulf of Mexico"],
    options_hi: ["प्रशांत महासागर", "कैरेबियन सागर", "अटलांटिक महासागर", "मैक्सिको की खाड़ी"],
    correct_option_index: 2,
    explanation_en: "The mouth of the Amazon River is the Atlantic Ocean, and it crosses the Equator at its mouth.",
    explanation_hi: "अमेज़न नदी का मुहाना अटलांटिक महासागर है, और यह विषुवत रेखा को मुहाने पर काटती है।",
  },
  {
    question_en: "Which is the longest river in the continent of Europe?",
    question_hi: "यूरोप महाद्वीप की सबसे लंबी नदी कौन सी है?",
    options_en: ["Danube River", "Rhine River", "Ural River", "Volga River"],
    options_hi: ["डेन्यूब नदी", "राइन नदी", "यूराल नदी", "वोल्गा नदी (Volga River)"],
    correct_option_index: 3,
    explanation_en: "The Volga River is the longest river in Europe.",
    explanation_hi: "वोल्गा नदी यूरोप की सबसे लंबी नदी है।",
  },
];

export default test2Questions;
