import type { QuizQuestion } from '../../../types';

const test6Questions: QuizQuestion[] = [
  {
    question_en: "Census 2011: What was the total Literacy Rate of India?",
    question_hi: "Census 2011: भारत की कुल साक्षरता दर (Literacy Rate) कितनी थी?",
    options_en: ["80.9%", "64.6%", "75.26%", "73.0%"],
    options_hi: ["80.9%", "64.6%", "75.26%", "73.0%"],
    correct_option_index: 3,
    explanation_en: "According to the 2011 Census, the literacy rate of India was 73.0%.",
    explanation_hi: "2011 जनगणना के अनुसार भारत की साक्षरता दर 73.0% थी।",
  },
  {
    question_en: "Census 2011: Bihar is the state with the lowest literacy rate. What was this rate?",
    question_hi: "Census 2011: न्यूनतम साक्षरता दर वाला राज्य बिहार है, यह दर कितनी थी?",
    options_en: ["60%", "61%", "64.6%", "66%"],
    options_hi: ["60%", "61%", "64.6%", "66%"],
    correct_option_index: 1,
    explanation_en: "Bihar has the lowest literacy rate, which was 61%.",
    explanation_hi: "न्यूनतम साक्षरता दर वाला राज्य बिहार है, जो 61% थी।",
  },
  {
    question_en: "Census 2011: Kerala is the state with the highest literacy rate (94%). Which state is in the second position?",
    question_hi: "Census 2011: सर्वाधिक साक्षरता दर (94%) वाला राज्य केरल है, दूसरे स्थान पर कौन सा राज्य है?",
    options_en: ["Tripura (87%)", "Goa (88.7%)", "Himachal Pradesh (82.8%)", "Mizoram (91.3%)"],
    options_hi: ["त्रिपुरा (87%)", "गोवा (88.7%)", "हिमाचल प्रदेश (82.8%)", "मिजोरम (91.3%)"],
    correct_option_index: 3,
    explanation_en: "Mizoram (91.3%) is in the second position after Kerala (94%) in terms of the highest literacy rate.",
    explanation_hi: "सर्वाधिक साक्षरता दर में केरल (94%) के बाद मिजोरम (91.3%) है।",
  },
  {
    question_en: "Census 2011: Which is the Union Territory with the highest literacy rate?",
    question_hi: "Census 2011: सर्वाधिक साक्षरता दर वाला केंद्र शासित प्रदेश कौन सा है?",
    options_en: ["Daman and Diu (87.1%)", "Andaman and Nicobar (86.6%)", "Chandigarh (86%)", "Lakshadweep (91.8%)"],
    options_hi: ["दमन और दीव (87.1%)", "अंडमान निकोबार (86.6%)", "चंडीगढ़ (86%)", "लक्षद्वीप (91.8%)"],
    correct_option_index: 3,
    explanation_en: "Lakshadweep (91.8%) is the Union Territory with the highest literacy rate.",
    explanation_hi: "सर्वाधिक साक्षरता दर वाला केंद्र शासित प्रदेश लक्षद्वीप (91.8%) है।",
  },
  {
    question_en: "Census 2011: Which was the Union Territory with the lowest literacy rate?",
    question_hi: "Census 2011: न्यूनतम साक्षरता दर वाला केंद्र शासित प्रदेश कौन सा था?",
    options_en: ["Dadra and Nagar Haveli (76.2%)", "Puducherry (85.8%)", "Chandigarh (86%)", "Andaman and Nicobar (86.6%)"],
    options_hi: ["दादरा और नगर हवेली (76.2%)", "पुडुचेरी (85.8%)", "चंडीगढ़ (86%)", "अंडमान निकोबार (86.6%)"],
    correct_option_index: 0,
    explanation_en: "Dadra and Nagar Haveli (76.2%) was the Union Territory with the lowest literacy rate.",
    explanation_hi: "न्यूनतम साक्षरता दर वाला केंद्र शासित प्रदेश दादरा और नगर हवेली (76.2%) था।",
  },
  {
    question_en: "Census 2011: What was the Sex Ratio of India (number of females per 1000 males)?",
    question_hi: "Census 2011: भारत का लिंगानुपात (Sex Ratio) प्रति 1000 पुरुषों पर महिलाओं की संख्या कितनी थी?",
    options_en: ["919", "933", "943", "949"],
    options_hi: ["919", "933", "943", "949"],
    correct_option_index: 2,
    explanation_en: "The Sex Ratio of India was 943.",
    explanation_hi: "भारत का लिंगानुपात 943 था।",
  },
  {
    question_en: "Census 2011: Which is the Union Territory with the highest Sex Ratio?",
    question_hi: "Census 2011: सर्वाधिक लिंगानुपात वाला केंद्र शासित प्रदेश कौन सा है?",
    options_en: ["Lakshadweep (947)", "Andaman and Nicobar (876)", "Chandigarh (818)", "Puducherry (1037)"],
    options_hi: ["लक्षद्वीप (947)", "अंडमान निकोबार (876)", "चंडीगढ़ (818)", "पुडुचेरी (1037)"],
    correct_option_index: 3,
    explanation_en: "Puducherry (1037) is the Union Territory with the highest Sex Ratio.",
    explanation_hi: "सर्वाधिक लिंगानुपात वाला केंद्र शासित प्रदेश पुडुचेरी (1037) है।",
  },
  {
    question_en: "Census 2011: Which is the Union Territory with the lowest Sex Ratio?",
    question_hi: "Census 2011: न्यूनतम लिंगानुपात वाला केंद्र शासित प्रदेश कौन सा है?",
    options_en: ["Dadra and Nagar Haveli (774)", "Chandigarh (818)", "Lakshadweep (947)", "Daman and Diu (618)"],
    options_hi: ["दादरा और नगर हवेली (774)", "चंडीगढ़ (818)", "लक्षद्वीप (947)", "दमन और दीव (618)"],
    correct_option_index: 3,
    explanation_en: "Daman and Diu (618) was the Union Territory with the lowest Sex Ratio.",
    explanation_hi: "न्यूनतम लिंगानुपात वाला केंद्र शासित प्रदेश दमन और दीव (618) था।",
  },
  {
    question_en: "Census 2011: Which is the Union Territory with the lowest population?",
    question_hi: "Census 2011: न्यूनतम जनसंख्या वाला केंद्र शासित प्रदेश कौन सा है?",
    options_en: ["Daman and Diu (2,43,247)", "Dadra and Nagar Haveli (3,43,709)", "Chandigarh (10,55,450)", "Lakshadweep (64,473)"],
    options_hi: ["दमन और दीव (2,43,247)", "दादरा और नगर हवेली (3,43,709)", "चंडीगढ़ (10,55,450)", "लक्षद्वीप (64,473)"],
    correct_option_index: 3,
    explanation_en: "Lakshadweep (64,473) is the Union Territory with the lowest population.",
    explanation_hi: "न्यूनतम जनसंख्या वाला केंद्र शासित प्रदेश लक्षद्वीप (64,473) है।",
  },
  {
    question_en: "Census 2011: What percentage of the world's total land area is covered by India's total area?",
    question_hi: "Census 2011: भारत का कुल क्षेत्रफल विश्व के कुल भू-भाग का लगभग कितना प्रतिशत है?",
    options_en: ["3.2%", "2.4%", "4.2%", "1.8%"],
    options_hi: ["3.2%", "2.4%", "4.2%", "1.8%"],
    correct_option_index: 1,
    explanation_en: "India covers 2.4% of the Earth's total land area.",
    explanation_hi: "भारत पृथ्वी के कुल भू-भाग का 2.4% भाग घेरता है।",
  },
  {
    question_en: "Census 2011: Which state has the lowest population density?",
    question_hi: "Census 2011: न्यूनतम जनसंख्या घनत्व वाला राज्य कौन सा है?",
    options_en: ["Mizoram (52)", "Sikkim (86)", "Nagaland (119)", "Arunachal Pradesh (17)"],
    options_hi: ["मिजोरम (52)", "सिक्किम (86)", "नागालैंड (119)", "अरुणाचल प्रदेश (17)"],
    correct_option_index: 3,
    explanation_en: "Arunachal Pradesh (17) is the state with the lowest population density.",
    explanation_hi: "न्यूनतम जनसंख्या घनत्व वाला राज्य अरुणाचल प्रदेश (17) है।",
  },
  {
    question_en: "Census 2011: Which state has the highest rural population (in crores)?",
    question_hi: "Census 2011: सर्वाधिक ग्रामीण जनसंख्या (करोड़ों में) वाला राज्य कौन सा है?",
    options_en: ["Bihar (9.22 crore)", "Maharashtra (6.15 crore)", "West Bengal (6.21 crore)", "Uttar Pradesh (15.53 crore)"],
    options_hi: ["बिहार (9.22 करोड़)", "महाराष्ट्र (6.15 करोड़)", "पश्चिम बंगाल (6.21 करोड़)", "उत्तर प्रदेश (15.53 करोड़)"],
    correct_option_index: 3,
    explanation_en: "Uttar Pradesh had the highest rural population (15.53 crore).",
    explanation_hi: "सर्वाधिक ग्रामीण जनसंख्या (15.53 करोड़) वाला राज्य उत्तर प्रदेश था।",
  },
  {
    question_en: "Census 2011: What was the approximate total population of India?",
    question_hi: "Census 2011: भारत की कुल जनसंख्या लगभग कितनी थी?",
    options_en: ["102.97 crore", "115 crore", "121.05 crore", "83.37 crore"],
    options_hi: ["102.97 करोड़", "115 करोड़", "121.05 करोड़", "83.37 करोड़"],
    correct_option_index: 2,
    explanation_en: "The total population of India in 2011 was 121.05 crore.",
    explanation_hi: "भारत की कुल जनसंख्या 2011 में 121.05 करोड़ थी।",
  },
  {
    question_en: "Census 2011: Which state has the highest population in the 0-6 age group?",
    question_hi: "Census 2011: 0-6 आयु वर्ग में सर्वाधिक जनसंख्या वाला राज्य कौन सा है?",
    options_en: ["Bihar", "Maharashtra", "Rajasthan", "Uttar Pradesh"],
    options_hi: ["बिहार", "महाराष्ट्र", "राजस्थान", "उत्तर प्रदेश"],
    correct_option_index: 3,
    explanation_en: "Uttar Pradesh had the highest population in the 0-6 age group.",
    explanation_hi: "0-6 आयु वर्ग में सर्वाधिक जनसंख्या वाला राज्य उत्तर प्रदेश था।",
  },
  {
    question_en: "Census 2011: Which state is included among the top four states with the highest urban population percentage?",
    question_hi: "Census 2011: सर्वाधिक शहरी जनसंख्या प्रतिशत वाले चार राज्यों में से कौन सा राज्य शामिल है?",
    options_en: ["Uttar Pradesh", "Rajasthan", "Bihar", "Goa"],
    options_hi: ["उत्तर प्रदेश", "राजस्थान", "बिहार", "गोवा"],
    correct_option_index: 3,
    explanation_en: "Goa is included among the top four states with the highest urban population percentage (Goa, Mizoram, Tamil Nadu, Kerala).",
    explanation_hi: "सर्वाधिक शहरी जनसंख्या प्रतिशत वाले चार राज्यों में गोवा (गोवा, मिजोरम, तमिलनाडु, केरल) शामिल है।",
  },
  {
    question_en: "Census 2011: Which three states have the minimum urban population?",
    question_hi: "Census 2011: भारत में न्यूनतम शहरी जनसंख्या (Minimum Urban Population) वाले तीन राज्य कौन से हैं?",
    options_en: ["Tripura, Mizoram, Sikkim", "Mizoram, Meghalaya, Nagaland", "Sikkim, Arunachal Pradesh, Nagaland", "Goa, Mizoram, Kerala"],
    options_hi: ["त्रिपुरा, मिजोरम, सिक्किम", "मिजोरम, मेघालय, नागालैंड", "सिक्किम, अरुणाचल प्रदेश, नागालैंड", "गोवा, मिजोरम, केरल"],
    correct_option_index: 2,
    explanation_en: "The three states with the minimum urban population are Sikkim, Arunachal Pradesh, and Nagaland.",
    explanation_hi: "न्यूनतम शहरी जनसंख्या वाले तीन राज्य सिक्किम, अरुणाचल प्रदेश, और नागालैंड हैं।",
  },
  {
    question_en: "Agriculture: Rabi crops are benefited by which monsoon/wind?",
    question_hi: "कृषि: रबी की फसलें (Rabi Crops) किस मानसून/पवन से लाभान्वित होती हैं?",
    options_en: ["North-East Monsoon", "South-West Monsoon", "Western Disturbance", "Kal Baisakhi"],
    options_hi: ["उत्तर-पूर्वी मानसून", "दक्षिण-पश्चिम मानसून", "पश्चिमी विक्षोभ (Western Disturbance)", "काल बैसाखी"],
    correct_option_index: 2,
    explanation_en: "Rabi crops are benefited by the Western Disturbances.",
    explanation_hi: "रबी की फसलें पश्चिमी विक्षोभ से लाभान्वित होती हैं।",
  },
  {
    question_en: "Agriculture: Kharif crops receive water from which monsoon?",
    question_hi: "कृषि: खरीफ की फसलें (Kharif Crops) किस मानसून से पानी प्राप्त करती हैं?",
    options_en: ["Western Disturbance", "South-West Monsoon", "North-East Monsoon", "Loo"],
    options_hi: ["पश्चिमी विक्षोभ", "दक्षिण-पश्चिम मानसून", "उत्तर-पूर्वी मानसून", "लू (Loo)"],
    correct_option_index: 1,
    explanation_en: "Kharif crops are benefited by the South-West Monsoon.",
    explanation_hi: "खरीफ की फसलें दक्षिण-पश्चिम मानसून से लाभान्वित होती हैं।",
  },
  {
    question_en: "Agriculture: Zaid Crops are sown in which season?",
    question_hi: "कृषि: जायद की फसलें (Zaid Crops) किस मौसम में बोई जाती हैं?",
    options_en: ["June-July", "October-November", "Mid-March to May", "December-January"],
    options_hi: ["जून-जुलाई", "अक्टूबर-नवंबर", "मार्च-मई के मध्य", "दिसंबर-जनवरी"],
    correct_option_index: 2,
    explanation_en: "Zaid crops are sown in March and harvested in June, between Rabi and Kharif seasons.",
    explanation_hi: "जायद की फसलें रबी और खरीफ के मध्य मार्च में बोई और जून में काटी जाती हैं।",
  },
  {
    question_en: "Agriculture: Which of the following is included in Cash Crops?",
    question_hi: "कृषि: नकदी फसलों (Cash Crops) में कौन शामिल है?",
    options_en: ["Rice, Wheat", "Cucumber, Watermelon", "Cotton, Jute, Sugarcane, Tobacco", "Apple, Pear"],
    options_hi: ["चावल, गेहूँ", "खीरा, तरबूज", "कपास, जूट, गन्ना, तंबाकू", "सेब, नाशपाती"],
    correct_option_index: 2,
    explanation_en: "Cash crops include Cotton, Jute, Sugarcane, or Tobacco.",
    explanation_hi: "नकदी फसलों में कपास, जूट, गन्ना या तंबाकू शामिल हैं।",
  },
  {
    question_en: "Agriculture Boards: The headquarters of the Tobacco Board is located in Guntur (Andhra Pradesh), while where is the headquarters of the Spices Board?",
    question_hi: "कृषि बोर्ड: तंबाकू बोर्ड का मुख्यालय गुंटूर (आंध्र प्रदेश) में स्थित है, जबकि मसाला बोर्ड का मुख्यालय कहाँ है?",
    options_en: ["Bengaluru (Karnataka)", "Kolkata (West Bengal)", "Kochi (Kerala)", "Coimbatore (Tamil Nadu)"],
    options_hi: ["बेंगलुरु (कर्नाटक)", "कोलकाता (पश्चिम बंगाल)", "कोच्चि (केरल)", "कोयंबटूर (तमिलनाडु)"],
    correct_option_index: 2,
    explanation_en: "The headquarters of the Spices Board is located in Kochi (Kerala).",
    explanation_hi: "मसाला बोर्ड का मुख्यालय कोच्चि (केरल) में स्थित है।",
  },
  {
    question_en: "Agriculture Boards: The headquarters of which board is located in Bengaluru (Karnataka)?",
    question_hi: "कृषि बोर्ड: किस बोर्ड का मुख्यालय बेंगलुरु (कर्नाटक) में स्थित है?",
    options_en: ["Rubber Board", "Tea Board", "Spices Board", "Coffee Board"],
    options_hi: ["रबड़ बोर्ड", "चाय बोर्ड", "मसाला बोर्ड", "कॉफी बोर्ड"],
    correct_option_index: 3,
    explanation_en: "The headquarters of the Coffee Board is located in Bengaluru (Karnataka).",
    explanation_hi: "कॉफी बोर्ड का मुख्यालय बेंगलुरु (कर्नाटक) में स्थित है।",
  },
  {
    question_en: "Agriculture Boards: The headquarters of which board is located in Kottayam (Kerala)?",
    question_hi: "कृषि बोर्ड: किस बोर्ड का मुख्यालय कोट्टायम (केरल) में स्थित है?",
    options_en: ["Coffee Board", "Tea Board", "Spices Board", "Rubber Board"],
    options_hi: ["कॉफी बोर्ड", "चाय बोर्ड", "मसाला बोर्ड", "रबड़ बोर्ड"],
    correct_option_index: 3,
    explanation_en: "The headquarters of the Rubber Board is located in Kottayam (Kerala).",
    explanation_hi: "रबड़ बोर्ड का मुख्यालय कोट्टायम (केरल) में स्थित है।",
  },
  {
    question_en: "Agricultural Revolution: 'Black Revolution' is related to what?",
    question_hi: "कृषि क्रांति: 'ब्लैक क्रांति' (Black Revolution) का संबंध किससे है?",
    options_en: ["Egg/Poultry farming", "Petroleum Production", "Oilseeds Production", "Fish Production"],
    options_hi: ["अंडा/मुर्गी पालन", "पेट्रोलियम उत्पादन", "तिलहन उत्पादन", "मत्स्य उत्पादन"],
    correct_option_index: 1,
    explanation_en: "Black Revolution is related to Petroleum Production.",
    explanation_hi: "ब्लैक क्रांति का संबंध पेट्रोलियम उत्पादन से है।",
  },
  {
    question_en: "Agricultural Revolution: 'Blue Revolution' is related to what?",
    question_hi: "कृषि क्रांति: 'नीली क्रांति' (Blue Revolution) का संबंध किससे है?",
    options_en: ["Oilseeds Production", "Fish/Fisheries Production", "Meat/Tomato Production", "Fertilizer Production"],
    options_hi: ["तिलहन उत्पादन", "मछली/मत्स्य उत्पादन", "मांस/टमाटर उत्पादन", "उर्वरक उत्पादन"],
    correct_option_index: 1,
    explanation_en: "Blue Revolution is related to Fisheries (Fish) Production.",
    explanation_hi: "नीली क्रांति का संबंध मत्स्य (मछली) उत्पादन से है।",
  },
  {
    question_en: "Agricultural Revolution: 'Silver Revolution' is related to what?",
    question_hi: "कृषि क्रांति: 'रजत क्रांति' (Silver Revolution) का संबंध किससे है?",
    options_en: ["Tomato", "Cotton", "Egg and Poultry Farming", "Potato"],
    options_hi: ["टमाटर", "कपास", "अंडा और कुक्कुट पालन", "आलू"],
    correct_option_index: 2,
    explanation_en: "Silver Revolution is related to Egg and Poultry Farming.",
    explanation_hi: "रजत क्रांति का संबंध अंडा और कुक्कुट पालन से है।",
  },
  {
    question_en: "Agricultural Revolution: 'Silver Fibre Revolution' is related to what?",
    question_hi: "कृषि क्रांति: 'रजत फाइबर क्रांति' (Silver Fibre Revolution) का संबंध किससे है?",
    options_en: ["Jute", "Cotton", "Oilseeds", "Sugarcane"],
    options_hi: ["जूट", "कपास", "तिलहन", "गन्ना"],
    correct_option_index: 1,
    explanation_en: "Silver Fibre Revolution is related to Cotton production.",
    explanation_hi: "सिल्वर फाइबर क्रांति का संबंध कपास उत्पादन से है।",
  },
  {
    question_en: "Agricultural Revolution: 'Round Revolution' is related to the production of what?",
    question_hi: "कृषि क्रांति: 'गोल क्रांति' (Round Revolution) का संबंध किसके उत्पादन से है?",
    options_en: ["Tomato", "Milk", "Oilseeds", "Potato"],
    options_hi: ["टमाटर", "दूध", "तिलहन", "आलू"],
    correct_option_index: 3,
    explanation_en: "Round Revolution is related to Potato production.",
    explanation_hi: "गोल क्रांति का संबंध आलू उत्पादन से है।",
  },
  {
    question_en: "Agricultural Revolution: 'Green Gold Revolution' is related to the production of what?",
    question_hi: "कृषि क्रांति: 'हरित स्वर्ण क्रांति' (Green Gold Revolution) का संबंध किसके उत्पादन से है?",
    options_en: ["Honey/Horticulture", "Pulses", "Bamboo", "Saffron"],
    options_hi: ["शहद/बागवानी", "दलहन", "बाँस", "केसर"],
    correct_option_index: 2,
    explanation_en: "Green Gold Revolution is related to Bamboo production.",
    explanation_hi: "हरित स्वर्ण क्रांति का संबंध बाँस उत्पादन से है।",
  },
  {
    question_en: "Agriculture: What is the rearing of silkworms called?",
    question_hi: "कृषि: रेशम कीट पालन को क्या कहा जाता है?",
    options_en: ["Apiculture", "Vermiculture", "Horticulture", "Sericulture"],
    options_hi: ["एपिकल्चर", "वर्मीकल्चर", "हॉर्टिकल्चर", "सेरीकल्चर (Sericulture)"],
    correct_option_index: 3,
    explanation_en: "Rearing of silkworms is called Sericulture.",
    explanation_hi: "रेशम कीट पालन को सेरीकल्चर कहा जाता है।",
  },
  {
    question_en: "Agriculture: What is beekeeping called?",
    question_hi: "कृषि: मधुमक्खी पालन को क्या कहा जाता है?",
    options_en: ["Sericulture", "Viticulture", "Floriculture", "Apiculture"],
    options_hi: ["सेरीकल्चर", "विटीकल्चर", "फ्लोरीकल्चर", "एपिकल्चर (Apiculture)"],
    correct_option_index: 3,
    explanation_en: "Beekeeping is called Apiculture.",
    explanation_hi: "मधुमक्खी पालन को एपिकल्चर कहा जाता है।",
  },
  {
    question_en: "Agriculture: Which country has the maximum number of tube wells in the world?",
    question_hi: "कृषि: भारत में ट्यूबवेल (नलकूप) की सर्वाधिक संख्या किस देश में पाई जाती है?",
    options_en: ["China", "USA", "Russia", "India"],
    options_hi: ["चीन", "USA", "रूस", "भारत"],
    correct_option_index: 3,
    explanation_en: "India has the maximum number of tube wells.",
    explanation_hi: "भारत में नलकूपों की सर्वाधिक संख्या पाई जाती है।",
  },
  {
    question_en: "Irrigation: What is the largest source of irrigation in India after wells and tube wells?",
    question_hi: "सिंचाई: भारत में कुओं और नलकूपों के बाद सिंचाई का सबसे बड़ा साधन क्या है?",
    options_en: ["Ponds", "Sprinklers", "Drip Irrigation", "Canals"],
    options_hi: ["तालाब", "स्प्रिंकलर", "ड्रिप सिंचाई", "नहरें (Canals)"],
    correct_option_index: 3,
    explanation_en: "After wells and tube wells, canals are the largest source of irrigation in India.",
    explanation_hi: "कुओं और नलकूपों के बाद भारत में सिंचाई का सबसे बड़ा साधन नहरें हैं।",
  },
  {
    question_en: "Shifting Cultivation: By what name is shifting cultivation known in the Western Ghats?",
    question_hi: "स्थानांतरित कृषि: पश्चिमी घाट में स्थानांतरित कृषि को किस नाम से जाना जाता है?",
    options_en: ["Jhum", "Podu", "Kuruval", "Kumar"],
    options_hi: ["झूम", "पोडू", "कुरुवाल", "कुमार (Kumar)"],
    correct_option_index: 3,
    explanation_en: "Shifting cultivation in the Western Ghats is known as Kumar.",
    explanation_hi: "पश्चिमी घाट में स्थानांतरित कृषि को कुमार नाम से जाना जाता है।",
  },
  {
    question_en: "Shifting Cultivation: By what name is shifting cultivation known in Madhya Pradesh?",
    question_hi: "स्थानांतरित कृषि: मध्य प्रदेश में स्थानांतरित कृषि को किस नाम से जाना जाता है?",
    options_en: ["Pomlu", "Jhum", "Bewar or Dahia", "Khil"],
    options_hi: ["पोमलू", "झूम", "बेवर या दहिया", "खिल"],
    correct_option_index: 2,
    explanation_en: "In Madhya Pradesh, it is called Bewar or Dahia.",
    explanation_hi: "मध्य प्रदेश में इसे बेवर या दहिया कहा जाता है।",
  },
  {
    question_en: "Shifting Cultivation: By what name is shifting cultivation known in Odisha?",
    question_hi: "स्थानांतरित कृषि: ओडिशा में स्थानांतरित कृषि को किस नाम से जाना जाता है?",
    options_en: ["Khil", "Pomlu", "Dahia", "Damadabi, Koman or Bariga"],
    options_hi: ["खिल", "पोमलू", "दहिया", "दामादाबी, कोमन या बरीगा"],
    correct_option_index: 3,
    explanation_en: "In Odisha, it is known as Damadabi, Koman or Bariga.",
    explanation_hi: "ओडिशा में इसे दामादाबी, कोमन या बरीगा नाम से जाना जाता है।",
  },
  {
    question_en: "Neighboring Countries: Which neighboring country shares the longest border with India?",
    question_hi: "पड़ोसी देश: भारत के साथ सबसे लंबी सीमा साझा करने वाला पड़ोसी देश कौन सा है?",
    options_en: ["China", "Pakistan", "Nepal", "Bangladesh (4096.7 km)"],
    options_hi: ["चीन", "पाकिस्तान", "नेपाल", "बांग्लादेश (4096.7 किमी)"],
    correct_option_index: 3,
    explanation_en: "Bangladesh shares the longest border with India (4096.7 km).",
    explanation_hi: "बांग्लादेश भारत के साथ सबसे लंबी सीमा (4096.7 किमी) साझा करता है।",
  },
  {
    question_en: "Neighboring Countries: What is the total length (New Data) of India's land border?",
    question_hi: "पड़ोसी देश: भारत की स्थलीय सीमा की कुल लंबाई (New Data) कितनी है?",
    options_en: ["7516.67 km", "15200 km", "15106.7 km", "6100 km"],
    options_hi: ["7516.67 किमी", "15200 किमी", "15106.7 किमी", "6100 किमी"],
    correct_option_index: 2,
    explanation_en: "The total length of the Indian land border is 15106.7 km.",
    explanation_hi: "भारतीय स्थलीय सीमा की कुल लंबाई 15106.7 किमी है।",
  },
  {
    question_en: "Neighboring Countries: Which is the longest river in Bangladesh?",
    question_hi: "पड़ोसी देश: बांग्लादेश की सबसे लंबी नदी कौन सी है?",
    options_en: ["Padma", "Jamuna", "Hooghly", "Meghna"],
    options_hi: ["पद्मा", "जमुना", "हुगली", "मेघना (Meghna)"],
    correct_option_index: 3,
    explanation_en: "Meghna River is the longest river in Bangladesh.",
    explanation_hi: "मेघना नदी बांग्लादेश की सबसे लंबी नदी है।",
  },
  {
    question_en: "Neighboring Countries: By what name is the Parliament of China known?",
    question_hi: "पड़ोसी देश: चीन की संसद को किस नाम से जाना जाता है?",
    options_en: ["Jatiya Sangsad", "Shura", "National Panchayat", "National People's Congress"],
    options_hi: ["जातीय संसद", "शोरा", "राष्ट्रीय पंचायत", "नेशनल पीपुल्स कांग्रेस"],
    correct_option_index: 3,
    explanation_en: "The Parliament of China is called the National People's Congress.",
    explanation_hi: "चीन की संसद को नेशनल पीपुल्स कांग्रेस कहा जाता है।",
  },
  {
    question_en: "Neighboring Countries: What is the national anthem of Pakistan?",
    question_hi: "पड़ोसी देश: पाकिस्तान का राष्ट्रीय गान क्या है?",
    options_en: ["Amar Sonar Bangla", "Shura", "Qaumi Tarana", "Helmand"],
    options_hi: ["अमर सोनार बांग्ला", "शोरा", "कौमी तराना (Qaumi Tarana)", "हेलमंद"],
    correct_option_index: 2,
    explanation_en: "The national anthem of Pakistan is Qaumi Tarana.",
    explanation_hi: "पाकिस्तान का राष्ट्रीय गान कौमी तराना है।",
  },
  {
    question_en: "Neighboring Countries: Which is the longest river of Nepal?",
    question_hi: "पड़ोसी देश: नेपाल की सबसे लंबी नदी कौन सी है?",
    options_en: ["Kosi River", "Gandak River", "Karnali", "Padma"],
    options_hi: ["कोसी नदी", "गंडक नदी", "करनाली (Karnali)", "पद्मा"],
    correct_option_index: 2,
    explanation_en: "The longest river of Nepal is Karnali.",
    explanation_hi: "नेपाल की सबसे लंबी नदी करनाली है।",
  },
  {
    question_en: "Neighboring Countries: When is Myanmar's Independence Day celebrated?",
    question_hi: "पड़ोसी देश: म्यांमार का स्वतंत्रता दिवस कब मनाया जाता है?",
    options_en: ["August 14, 1947", "August 19, 1919", "January 4, 1948", "December 17, 1907"],
    options_hi: ["14 अगस्त 1947", "19 अगस्त 1919", "4 जनवरी 1948", "17 दिसंबर 1907"],
    correct_option_index: 2,
    explanation_en: "Myanmar's Independence Day is January 4, 1948.",
    explanation_hi: "म्यांमार का स्वतंत्रता दिवस 4 जनवरी 1948 है।",
  },
  {
    question_en: "Neighboring Countries: Which country's capital is Naypyidaw?",
    question_hi: "पड़ोसी देश: किस देश की राजधानी नेयप्यीडॉ (Naypyidaw) है?",
    options_en: ["Bhutan", "Nepal", "Myanmar", "Sri Lanka"],
    options_hi: ["भूटान", "नेपाल", "म्यांमार", "श्रीलंका"],
    correct_option_index: 2,
    explanation_en: "The capital of Myanmar is Naypyidaw.",
    explanation_hi: "म्यांमार की राजधानी नेयप्यीडॉ है।",
  },
  {
    question_en: "Tribes: Gaddi, Kinnaur, and Gujjar tribes live in which state?",
    question_hi: "जनजातियाँ: गद्दी, किन्नौर और गुज्जर जनजातियाँ किस राज्य में निवास करती हैं?",
    options_en: ["Jammu and Kashmir", "Uttarakhand", "Himachal Pradesh", "Uttar Pradesh"],
    options_hi: ["जम्मू-कश्मीर", "उत्तराखंड", "हिमाचल प्रदेश", "उत्तर प्रदेश"],
    correct_option_index: 2,
    explanation_en: "Gaddi, Kinnaur, Gujjar, and Pangwali tribes are found in Himachal Pradesh.",
    explanation_hi: "गद्दी, किन्नौर, गुज्जर, और पंगवाली जनजातियाँ हिमाचल प्रदेश में पाई जाती हैं।",
  },
  {
    question_en: "Tribes: Garo, Khasi, and Jaintia tribes are found in which state?",
    question_hi: "जनजातियाँ: गारो, खासी और जयंतिया जनजातियाँ किस राज्य में पाई जाती हैं?",
    options_en: ["Nagaland", "Assam", "Meghalaya", "Tripura"],
    options_hi: ["नागालैंड", "असम", "मेघालय", "त्रिपुरा"],
    correct_option_index: 2,
    explanation_en: "Garo, Khasi, and Jaintia tribes are found in Meghalaya.",
    explanation_hi: "गारो, खासी, और जयंतिया जनजातियाँ मेघालय में पाई जाती हैं।",
  },
  {
    question_en: "Tribes: Riang, Uchai, Jamathia, and Lusai tribes are found in which state?",
    question_hi: "जनजातियाँ: रियांग, उचाई, जमथिया और लुसाई जनजातियाँ किस राज्य में पाई जाती हैं?",
    options_en: ["Mizoram", "Meghalaya", "Assam", "Tripura"],
    options_hi: ["मिजोरम", "मेघालय", "असम", "त्रिपुरा"],
    correct_option_index: 3,
    explanation_en: "These tribes are in Tripura.",
    explanation_hi: "ये जनजातियाँ त्रिपुरा में हैं।",
  },
  {
    question_en: "Tribes: Chakma, Dimasa, and Hajong are tribes of which state?",
    question_hi: "जनजातियाँ: चक्मा, डिमासा और हाजोंग किस राज्य की जनजातियाँ हैं?",
    options_en: ["Meghalaya", "Tripura", "Assam", "Mizoram"],
    options_hi: ["मेघालय", "त्रिपुरा", "असम", "मिजोरम"],
    correct_option_index: 2,
    explanation_en: "Chakma, Dimasa, and Hajong tribes belong to Assam.",
    explanation_hi: "चक्मा, डिमासा और हाजोंग जनजातियाँ असम की हैं।",
  },
  {
    question_en: "Tribes: Dhanwar, Kawar, and Kodaku are tribes of which state?",
    question_hi: "जनजातियाँ: ढनवार, कवार और कोडाकू किस राज्य की जनजातियाँ हैं?",
    options_en: ["Madhya Pradesh", "Jharkhand", "Chhattisgarh", "Odisha"],
    options_hi: ["मध्य प्रदेश", "झारखंड", "छत्तीसगढ़", "ओडिशा"],
    correct_option_index: 2,
    explanation_en: "Dhanwar, Kawar, and Kodaku tribes belong to Chhattisgarh.",
    explanation_hi: "ढनवार, कवार और कोडाकू जनजातियाँ छत्तीसगढ़ की हैं।",
  },
  {
    question_en: "Tribes: Bhumij and Asur are tribes of which state?",
    question_hi: "जनजातियाँ: भूमिश और असुर किस राज्य की जनजातियाँ हैं?",
    options_en: ["Jharkhand", "Odisha", "West Bengal", "Bihar"],
    options_hi: ["झारखंड", "ओडिशा", "पश्चिम बंगाल", "बिहार"],
    correct_option_index: 2,
    explanation_en: "Bhumij and Asur tribes belong to West Bengal.",
    explanation_hi: "भूमिश और असुर जनजातियाँ पश्चिम बंगाल की हैं।",
  },
  {
    question_en: "Tribes: Meena, Bhil, and Banjara are tribes of which state?",
    question_hi: "जनजातियाँ: मीणा, भील और बंजारा किस राज्य की जनजातियाँ हैं?",
    options_en: ["Gujarat", "Madhya Pradesh", "Maharashtra", "Rajasthan"],
    options_hi: ["गुजरात", "मध्य प्रदेश", "महाराष्ट्र", "राजस्थान"],
    correct_option_index: 3,
    explanation_en: "Bhil, Meena, and Banjara are tribes of Rajasthan.",
    explanation_hi: "भील, मीणा और बंजारा राजस्थान की जनजातियाँ हैं।",
  },
  {
    question_en: "Tribes: Chenchu, Lambada, Pauls, and Bagata are tribes of which state?",
    question_hi: "जनजातियाँ: चेंचू, लंबाडा, पॉलस और बागाटा किस राज्य की जनजातियाँ हैं?",
    options_en: ["Karnataka", "Kerala", "Tamil Nadu", "Andhra Pradesh"],
    options_hi: ["कर्नाटक", "केरल", "तमिलनाडु", "आंध्र प्रदेश"],
    correct_option_index: 3,
    explanation_en: "These tribes belong to Andhra Pradesh.",
    explanation_hi: "ये जनजातियाँ आंध्र प्रदेश की हैं।",
  },
  {
    question_en: "Tribes: Toda and Kota tribes primarily rear buffaloes on which hill?",
    question_hi: "जनजातियाँ: टोडा और कोटा जनजातियाँ मुख्य रूप से किस पहाड़ी पर भैंसें पालती हैं?",
    options_en: ["Annamalai Hills", "Cardamom Hills", "Palani Hills", "Nilgiri Hills"],
    options_hi: ["अन्नामलाई हिल्स", "कार्डामम हिल्स", "पलनी हिल्स", "नीलगिरि हिल्स"],
    correct_option_index: 3,
    explanation_en: "Toda and Kota tribes rear buffaloes on the Nilgiri Hills.",
    explanation_hi: "टोडा और कोटा जनजातियाँ नीलगिरि हिल्स पर भैंसें पालती हैं।",
  },
  {
    question_en: "Tribes: Asur, Khand, Kher, and Oraon are tribes of which state?",
    question_hi: "जनजातियाँ: असुर, खंड, खेड़ और उरांव किस राज्य की जनजातियाँ हैं?",
    options_en: ["Jharkhand", "Odisha", "West Bengal", "Bihar"],
    options_hi: ["झारखंड", "ओडिशा", "पश्चिम बंगाल", "बिहार"],
    correct_option_index: 3,
    explanation_en: "These tribes belong to Bihar.",
    explanation_hi: "ये जनजातियाँ बिहार की हैं।",
  },
  {
    question_en: "Industry: Where was India's first unsuccessful cotton textile mill established in 1818?",
    question_hi: "उद्योग: भारत का पहला असफल सूती वस्त्र कारखाना 1818 में कहाँ स्थापित किया गया था?",
    options_en: ["Mumbai", "Ahmedabad", "Kanpur", "Fort Gloster (Kolkata)"],
    options_hi: ["मुंबई", "अहमदाबाद", "कानपुर", "फोर्ट ग्लॉस्टर (कोलकाता)"],
    correct_option_index: 3,
    explanation_en: "India's first cotton textile mill was established at Fort Gloster near Kolkata in 1818, which was unsuccessful.",
    explanation_hi: "भारत का पहला सूती वस्त्र कारखाना 1818 में कोलकाता के निकट फोर्ट ग्लॉस्टर में स्थापित किया गया था, जो असफल रहा।",
  },
  {
    question_en: "Industry: Where was the Paper Industry established in 1832?",
    question_hi: "उद्योग: कागज उद्योग (Paper Industry) की स्थापना 1832 में कहाँ हुई थी?",
    options_en: ["Mumbai", "Risra (WB)", "Nepanagar (MP)", "Srirampur (West Bengal)"],
    options_hi: ["मुंबई", "रिसरा (WB)", "नेपानगर (MP)", "श्रीरामपुर (पश्चिम बंगाल)"],
    correct_option_index: 3,
    explanation_en: "The paper industry was established in Srirampur (West Bengal) in 1832.",
    explanation_hi: "कागज उद्योग की स्थापना 1832 में श्रीरामपुर (पश्चिम बंगाल) में हुई।",
  },
  {
    question_en: "Industry: Where was the Woolen Clothes Industry established in 1876?",
    question_hi: "उद्योग: ऊनी वस्त्र उद्योग (Woolen Clothes Industry) की स्थापना 1876 में कहाँ हुई थी?",
    options_en: ["Ludhiana", "Srinagar", "Kanpur", "Mumbai"],
    options_hi: ["लुधियाना", "श्रीनगर", "कानपुर", "मुंबई"],
    correct_option_index: 2,
    explanation_en: "The Woolen Clothes Industry was established in Kanpur in 1876.",
    explanation_hi: "ऊनी वस्त्र उद्योग की स्थापना 1876 में कानपुर में हुई।",
  },
  {
    question_en: "Industry: When was the factory established in Kulti (West Bengal) for the Iron and Steel Industry?",
    question_hi: "उद्योग: लौह-इस्पात उद्योग में कुल्टी (पश्चिम बंगाल) में कारखाना कब स्थापित किया गया था?",
    options_en: ["1907", "1918", "1923", "1870"],
    options_hi: ["1907", "1918", "1923", "1870"],
    correct_option_index: 3,
    explanation_en: "The first factory of the Iron and Steel Industry was established in Kulti in 1870.",
    explanation_hi: "लौह-इस्पात उद्योग का पहला कारखाना कुल्टी में 1870 में स्थापित हुआ था।",
  },
  {
    question_en: "Industry: Nepanagar (MP) is famous for which industry?",
    question_hi: "उद्योग: नेपानगर (Nepanagar, MP) किस उद्योग के लिए प्रसिद्ध है?",
    options_en: ["Cotton Textile", "Jute Industry", "Aluminium", "Newsprint paper"],
    options_hi: ["सूती वस्त्र", "जूट उद्योग", "एल्युमीनियम", "अखबारी कागज (Newsprint paper)"],
    correct_option_index: 3,
    explanation_en: "Nepanagar (MP) is famous for its Newsprint paper mill.",
    explanation_hi: "नेपानगर (MP) अखबारी कागज मिल के लिए प्रसिद्ध है।",
  },
  {
    question_en: "Industry: By what name is Moradabad known?",
    question_hi: "उद्योग: मुरादाबाद को किस नाम से जाना जाता है?",
    options_en: ["Manchester of India", "Manchester of North India", "Brass City", "Detroit of India"],
    options_hi: ["भारत का मैनचेस्टर", "उत्तर भारत का मैनचेस्टर", "पीतल नगरी (Brass City)", "भारत का डेट्रॉइट"],
    correct_option_index: 2,
    explanation_en: "Moradabad is called the Brass City.",
    explanation_hi: "मुरादाबाद को पीतल नगरी कहा जाता है।",
  },
  {
    question_en: "Industry: Bhadohi is famous for which industry?",
    question_hi: "उद्योग: भदोही (Bhadohi) किस उद्योग के लिए प्रसिद्ध है?",
    options_en: ["Lock Industry", "Leather Industry", "Carpet industry", "Aluminium Industry"],
    options_hi: ["ताला उद्योग", "चमड़ा उद्योग", "कालीन उद्योग (Carpet industry)", "एल्युमीनियम उद्योग"],
    correct_option_index: 2,
    explanation_en: "Bhadohi is famous for the Carpet industry.",
    explanation_hi: "भदोही कालीन उद्योग के लिए प्रसिद्ध है।",
  },
  {
    question_en: "Minerals: Which type of iron ore contains 40-50% iron metal and is of low grade?",
    question_hi: "खनिज: कौन सा लौह अयस्क का प्रकार है जिसमें 40-50% लौह धातु शामिल होती है और यह निम्न कोटि का होता है?",
    options_en: ["Hematite", "Limonite", "Siderite", "Magnetite"],
    options_hi: ["हेमेटाइट", "लिमोनाइट", "सिडेराइट (Siderite)", "मैग्नेटाइट"],
    correct_option_index: 2,
    explanation_en: "Siderite contains 40-50% iron metal and is of low grade.",
    explanation_hi: "सिडेराइट में 40-50% लौह धातु होती है और यह निम्न कोटि का होता है।",
  },
  {
    question_en: "Minerals: In which rock system is iron ore found?",
    question_hi: "खनिज: लौह अयस्क किस चट्टान प्रणाली में पाया जाता है?",
    options_en: ["Godwana Rock System", "Vindhyan Rock System", "Dharwad Rock System", "Archean Rock System"],
    options_hi: ["गोडवाना रॉक सिस्टम", "विंध्यन रॉक सिस्टम", "धारवाड़ रॉक सिस्टम", "आर्कियन रॉक सिस्टम"],
    correct_option_index: 2,
    explanation_en: "Iron ore is found in the Dharwad rock system.",
    explanation_hi: "लौह अयस्क धारवाड़ चट्टान प्रणाली में पाया जाता है।",
  },
  {
    question_en: "Minerals: The Gurumahisani and Badam Pahar mines located in Odisha are famous for which type of iron ore?",
    question_hi: "खनिज: ओडिशा में स्थित गुरुमहिषानी और बादाम पहाड़ की खदानें किस प्रकार के लौह अयस्क के लिए प्रसिद्ध हैं?",
    options_en: ["Magnetite", "Limonite", "Hematite", "Siderite"],
    options_hi: ["मैग्नेटाइट", "लिमोनाइट", "हेमेटाइट", "सिडेराइट"],
    correct_option_index: 2,
    explanation_en: "Both these mines are famous for Hematite iron ore.",
    explanation_hi: "ये दोनों खदानें हेमेटाइट लौह अयस्क के लिए प्रसिद्ध हैं।",
  },
  {
    question_en: "Minerals: Jadugora of Jharkhand is famous for the mine of which mineral?",
    question_hi: "खनिज: झारखंड का जादूगोड़ा किस खनिज की खान के लिए प्रसिद्ध है?",
    options_en: ["Copper", "Gold", "Bauxite", "Uranium"],
    options_hi: ["ताँबा", "सोना", "बॉक्साइट", "यूरेनियम (Uranium)"],
    correct_option_index: 3,
    explanation_en: "Jadugoda of East Singhbhum district is famous for the Uranium mine.",
    explanation_hi: "पूर्वी सिंहभूम जिले का जादूगोड़ा यूरेनियम की खान के लिए प्रसिद्ध है।",
  },
  {
    question_en: "Minerals: Where is Thorium mainly found in India?",
    question_hi: "खनिज: थोरियम (Thorium) भारत में मुख्य रूप से कहाँ मिलता है?",
    options_en: ["Jharkhand", "On the coast of Odisha", "In the coastal areas of Kerala", "In the hills of Tamil Nadu"],
    options_hi: ["झारखंड", "ओडिशा के तट पर", "केरल के तटवर्ती भागों में", "तमिलनाडु की पहाड़ियों में"],
    correct_option_index: 2,
    explanation_en: "Thorium is mainly found in the coastal areas of Kerala.",
    explanation_hi: "थोरियम (Thorium) केरल के तटवर्ती भागों में मिलता है।",
  },
  {
    question_en: "Minerals: Which mineral comes under the category of Fossil mineral?",
    question_hi: "खनिज: कौन सा खनिज जीवाश्म खनिज (Fossil mineral) के अंतर्गत आता है?",
    options_en: ["Diamond", "Limestone", "Mica", "Coal/Petroleum/Natural Gas"],
    options_hi: ["हीरा", "चूना पत्थर", "अभ्रक", "कोयला/पेट्रोलियम/प्राकृतिक गैस"],
    correct_option_index: 3,
    explanation_en: "Coal, Petroleum, and Natural Gas are fossil minerals, which are found in sedimentary rocks.",
    explanation_hi: "कोयला, पेट्रोलियम और प्राकृतिक गैस जीवाश्म खनिज हैं, जो परतदार चट्टानों में पाए जाते हैं।",
  },
  {
    question_en: "Energy Resources: Bituminous coal, which is most commonly found in India in coal production, is found in which states?",
    question_hi: "ऊर्जा संसाधन: कोयले के उत्पादन में भारत में सर्वाधिक पाया जाने वाला कोयला बिटुमिनस किन राज्यों में मिलता है?",
    options_en: ["Jammu and Kashmir", "Tamil Nadu", "Jharkhand, West Bengal, Chhattisgarh, Odisha", "Rajasthan"],
    options_hi: ["जम्मू-कश्मीर", "तमिलनाडु", "झारखंड, पश्चिम बंगाल, छत्तीसगढ़, ओडिशा", "राजस्थान"],
    correct_option_index: 2,
    explanation_en: "Bituminous coal is found in Jharkhand, West Bengal, Chhattisgarh, and Odisha.",
    explanation_hi: "बिटुमिनस कोयला झारखंड, पश्चिम बंगाल, छत्तीसगढ़ और ओडिशा में पाया जाता है।",
  },
  {
    question_en: "Energy Resources: Coal is mainly obtained from which rock system?",
    question_hi: "ऊर्जा संसाधन: कोयला मुख्य रूप से किस रॉक सिस्टम से प्राप्त होता है?",
    options_en: ["Dharwad Rock System", "Vindhyan Rock System", "Godwana Rock System", "Tertiary Rock System"],
    options_hi: ["धारवाड़ रॉक सिस्टम", "विंध्यन रॉक सिस्टम", "गोडवाना रॉक सिस्टम", "टर्शियरी रॉक सिस्टम"],
    correct_option_index: 2,
    explanation_en: "Coal is obtained from the Godwana Rock System located in the Damodar River valley.",
    explanation_hi: "कोयला दामोदर नदी घाटी में स्थित गोडवाना रॉक सिस्टम से प्राप्त होता है।",
  },
  {
    question_en: "Energy Resources: Kakrapar Nuclear Power Plant is located in which state?",
    question_hi: "ऊर्जा संसाधन: काकरापारा नाभिकीय ऊर्जा संयंत्र किस राज्य में स्थित है?",
    options_en: ["Maharashtra", "Rajasthan", "Gujarat", "Karnataka"],
    options_hi: ["महाराष्ट्र", "राजस्थान", "गुजरात", "कर्नाटक"],
    correct_option_index: 2,
    explanation_en: "Kakrapar Nuclear Power Plant is located in Gujarat.",
    explanation_hi: "काकरापारा नाभिकीय ऊर्जा संयंत्र गुजरात में स्थित है।",
  },
  {
    question_en: "Energy Resources: Kaiga Nuclear Power Plant is located in which state?",
    question_hi: "ऊर्जा संसाधन: कैगा नाभिकीय ऊर्जा संयंत्र किस राज्य में स्थित है?",
    options_en: ["Tamil Nadu", "Maharashtra", "Gujarat", "Karnataka"],
    options_hi: ["तमिलनाडु", "महाराष्ट्र", "गुजरात", "कर्नाटक"],
    correct_option_index: 3,
    explanation_en: "Kaiga Nuclear Power Plant is located in Karnataka.",
    explanation_hi: "कैगा नाभिकीय ऊर्जा संयंत्र कर्नाटक में स्थित है।",
  },
  {
    question_en: "Energy Resources: Kalpakkam Nuclear Power Plant is located in which state?",
    question_hi: "ऊर्जा संसाधन: कलपक्कम (Kalpakkam) नाभिकीय ऊर्जा संयंत्र किस राज्य में स्थित है?",
    options_en: ["Andhra Pradesh", "Kerala", "Karnataka", "Tamil Nadu"],
    options_hi: ["आंध्र प्रदेश", "केरल", "कर्नाटक", "तमिलनाडु"],
    correct_option_index: 3,
    explanation_en: "Kalpakkam Nuclear Plant is located in Tamil Nadu (near Chennai).",
    explanation_hi: "कलपक्कम नाभिकीय संयंत्र तमिलनाडु (चेन्नई) में स्थित है।",
  },
  {
    question_en: "Oil Refineries: Digboi, the first oil well in Asia and India, is located in the Tinsukia district of which state?",
    question_hi: "तेल शोधक: एशिया और भारत का पहला तेल कुआँ डिगबोई (Digboi) किस राज्य के तिनसुकिया जिले में स्थित है?",
    options_en: ["West Bengal", "Bihar", "Assam", "Gujarat"],
    options_hi: ["पश्चिम बंगाल", "बिहार", "असम", "गुजरात"],
    correct_option_index: 2,
    explanation_en: "Digboi (discovered in 1889) is located in the Tinsukia district of Assam.",
    explanation_hi: "डिगबोई (1889 में खोजा गया) असम के तिनसुकिया जिले में स्थित है।",
  },
  {
    question_en: "Oil Refineries: Barauni Oil Refinery is located in which state?",
    question_hi: "तेल शोधक: बरौनी तेल शोधक कारखाना (Oil Refinery) किस राज्य में स्थित है?",
    options_en: ["Uttar Pradesh", "West Bengal", "Bihar", "Odisha"],
    options_hi: ["उत्तर प्रदेश", "पश्चिम बंगाल", "बिहार", "ओडिशा"],
    correct_option_index: 2,
    explanation_en: "Barauni Oil Refinery is located in Bihar.",
    explanation_hi: "बरौनी तेल शोधक कारखाना बिहार में स्थित है।",
  },
  {
    question_en: "Oil Refineries: Aishwariya Oil Field is located in which district of Rajasthan?",
    question_hi: "तेल शोधक: जागरूकता तेल क्षेत्र (Aishwariya Oil Field) राजस्थान के किस जिले में स्थित है?",
    options_en: ["Jodhpur", "Jaisalmer", "Bikaner", "Barmer"],
    options_hi: ["जोधपुर", "जैसलमेर", "बीकानेर", "बाड़मेर"],
    correct_option_index: 3,
    explanation_en: "Aishwariya Oil Field is located in the Barmer district (Rajasthan).",
    explanation_hi: "जागरूका तेल क्षेत्र बाड़मेर जिले (राजस्थान) में स्थित है।",
  },
  {
    question_en: "Oil Refineries: Mathura, Digboi, and Panipat refineries come under which company?",
    question_hi: "तेल शोधक: मथुरा, डिगबोई और पानीपत रिफाइनरी किस कंपनी के अंतर्गत आती हैं?",
    options_en: ["HPCL", "BPCL", "IOCL (Indian Oil Corporation Limited)", "ONGC"],
    options_hi: ["HPCL", "BPCL", "IOCL (Indian Oil Corporation Limited)", "ONGC"],
    correct_option_index: 2,
    explanation_en: "Mathura, Digboi, and Panipat refineries come under IOCL.",
    explanation_hi: "मथुरा, डिगबोई और पानीपत रिफाइनरी IOCL के अंतर्गत आती हैं।",
  },
  {
    question_en: "Geothermal Energy: Manikaran, a geothermal energy source, is located in which state?",
    question_hi: "भू-तापीय ऊर्जा: भू-तापीय ऊर्जा स्रोत मणिकरण किस राज्य में स्थित है?",
    options_en: ["Ladakh", "Uttarakhand", "Himachal Pradesh", "Jharkhand"],
    options_hi: ["लद्दाख", "उत्तराखंड", "हिमाचल प्रदेश", "झारखंड"],
    correct_option_index: 2,
    explanation_en: "Manikaran is located in Himachal Pradesh.",
    explanation_hi: "मणिकरण हिमाचल प्रदेश में स्थित है।",
  },
  {
    question_en: "Geothermal Energy: Tapovan, a geothermal energy source, is located in which state?",
    question_hi: "भू-तापीय ऊर्जा: भू-तापीय ऊर्जा स्रोत तपोवन किस राज्य में स्थित है?",
    options_en: ["Himachal Pradesh", "Uttarakhand", "Madhya Pradesh", "Odisha"],
    options_hi: ["हिमाचल प्रदेश", "उत्तराखंड", "मध्य प्रदेश", "ओडिशा"],
    correct_option_index: 1,
    explanation_en: "Tapovan is located in Uttarakhand.",
    explanation_hi: "तपोवन उत्तराखंड में स्थित है।",
  },
  {
    question_en: "Geothermal Energy: Surajkund, a geothermal energy source, is located in which state?",
    question_hi: "भू-तापीय ऊर्जा: भू-तापीय ऊर्जा स्रोत सूरजकुंड किस राज्य में स्थित है?",
    options_en: ["Odisha", "Madhya Pradesh", "Haryana", "Jharkhand"],
    options_hi: ["ओडिशा", "मध्य प्रदेश", "हरियाणा", "झारखंड"],
    correct_option_index: 3,
    explanation_en: "Surajkund is located in Jharkhand.",
    explanation_hi: "सूरजकुंड झारखंड में स्थित है।",
  },
  {
    question_en: "Energy Sources: Solar energy, wind energy, and tidal energy are which type of energy sources?",
    question_hi: "ऊर्जा स्रोत: सौर ऊर्जा, पवन ऊर्जा और ज्वारीय ऊर्जा किस प्रकार के ऊर्जा स्रोत हैं?",
    options_en: ["Conventional energy sources", "Non-conventional/Renewable energy sources", "Non-renewable energy sources", "Fossil energy sources"],
    options_hi: ["पारंपरिक ऊर्जा स्रोत", "गैर-परंपरागत/नवीकरणीय ऊर्जा स्रोत", "गैर-नवीकरणीय ऊर्जा स्रोत", "जीवाश्म ऊर्जा स्रोत"],
    correct_option_index: 1,
    explanation_en: "These are all non-conventional/renewable energy sources.",
    explanation_hi: "ये सभी गैर-परंपरागत/नवीकरणीय ऊर्जा स्रोत हैं।",
  },
  {
    question_en: "Energy Sources: Coal, petroleum, and natural gas are which type of energy sources?",
    question_hi: "ऊर्जा स्रोत: कोयला, पेट्रोलियम और प्राकृतिक गैस किस प्रकार के ऊर्जा स्रोत हैं?",
    options_en: ["Renewable energy", "Non-conventional energy", "Non-renewable/Conventional energy sources", "Geothermal energy"],
    options_hi: ["नवीकरणीय ऊर्जा", "गैर-परंपरागत ऊर्जा", "गैर-नवीकरणीय/परंपरागत ऊर्जा स्रोत", "भू-तापीय ऊर्जा"],
    correct_option_index: 2,
    explanation_en: "These are all non-renewable/conventional energy sources.",
    explanation_hi: "ये सभी गैर-नवीकरणीय/परंपरागत ऊर्जा स्रोत हैं।",
  },
  {
    question_en: "Dams: Tilaiya Dam is situated on which river?",
    question_hi: "दाम: तिलैया बाँध (Tilaiya Dam) किस नदी पर स्थित है?",
    options_en: ["Son River", "Damodar River", "Rihand River", "Barakar River"],
    options_hi: ["सोन नदी", "दामोदर नदी", "रिहंद नदी", "बराकर नदी (Barakar river)"],
    correct_option_index: 3,
    explanation_en: "Tilaiya Dam is situated on the Barakar River (a tributary of the Damodar).",
    explanation_hi: "तिलैया बाँध बराकर नदी (दामोदर की सहायक नदी) पर स्थित है।",
  },
  {
    question_en: "Dams: Rana Pratap Sagar Dam is situated on which river?",
    question_hi: "दाम: राणा प्रताप सागर बाँध (Rana Pratap Sagar Dam) किस नदी पर स्थित है?",
    options_en: ["Satluj River", "Narmada River", "Tapi River", "Chambal River"],
    options_hi: ["सतलुज नदी", "नर्मदा नदी", "तापी नदी", "चंबल नदी"],
    correct_option_index: 3,
    explanation_en: "Rana Pratap Sagar Dam is situated on the Chambal River (Rajasthan).",
    explanation_hi: "राणा प्रताप सागर बाँध चंबल नदी (राजस्थान) पर स्थित है।",
  },
  {
    question_en: "Dams: Idukki Dam is situated on which river?",
    question_hi: "दाम: इडुक्की बाँध (Idukki Dam) किस नदी पर स्थित है?",
    options_en: ["Kaveri River", "Tungabhadra River", "Periyar River", "Sharavathi River"],
    options_hi: ["कावेरी नदी", "तुंगभद्रा नदी", "पेरियार नदी", "शरावती नदी"],
    correct_option_index: 2,
    explanation_en: "Idukki Dam is situated on the Periyar River (Kerala).",
    explanation_hi: "इडुक्की बाँध पेरियार नदी (केरल) पर स्थित है।",
  },
  {
    question_en: "Dams: Kallanai Dam, the oldest dam in India, is located in which state?",
    question_hi: "दाम: भारत का सबसे पुराना बाँध (Oldest Dam) कल्लनई बाँध (Kallanai Dam) किस राज्य में स्थित है?",
    options_en: ["Karnataka", "Kerala", "Andhra Pradesh", "Tamil Nadu"],
    options_hi: ["कर्नाटक", "केरल", "आंध्र प्रदेश", "तमिलनाडु"],
    correct_option_index: 3,
    explanation_en: "Kallanai Dam is situated on the Kaveri River in Tamil Nadu.",
    explanation_hi: "कल्लनई बाँध कावेरी नदी पर तमिलनाडु में स्थित है।",
  },
  {
    question_en: "Dams: Krishnaraja Sagar Dam is situated on which river?",
    question_hi: "दाम: कृष्णाराज सागर बाँध (Krishnaraja Sagar Dam) किस नदी पर स्थित है?",
    options_en: ["Krishna River", "Tungabhadra River", "Kaveri River", "Pennar River"],
    options_hi: ["कृष्णा नदी", "तुंगभद्रा नदी", "कावेरी नदी", "पेन्नार नदी"],
    correct_option_index: 2,
    explanation_en: "Krishnaraja Sagar Dam is situated on the Kaveri River in Karnataka.",
    explanation_hi: "कृष्णाराज सागर बाँध कावेरी नदी पर कर्नाटक में स्थित है।",
  },
  {
    question_en: "Dams: Jawahar Sagar Dam is situated on which river?",
    question_hi: "दाम: जवाहर सागर बाँध (Jawahar Sagar Dam) किस नदी पर स्थित है?",
    options_en: ["Narmada", "Tapi", "Satluj", "Chambal River"],
    options_hi: ["नर्मदा", "तापी", "सतलुज", "चंबल नदी"],
    correct_option_index: 3,
    explanation_en: "Jawahar Sagar Dam is situated on the Chambal River.",
    explanation_hi: "जवाहर सागर बाँध चंबल नदी पर स्थित है।",
  },
  {
    question_en: "Dams: Mettur Dam is situated on which river?",
    question_hi: "दाम: मेट्टूर बाँध (Mettur Dam) किस नदी पर स्थित है?",
    options_en: ["Krishna River", "Periyar River", "Kaveri River", "Godavari River"],
    options_hi: ["कृष्णा नदी", "पेरियार नदी", "कावेरी नदी", "गोदावरी नदी"],
    correct_option_index: 2,
    explanation_en: "Mettur Dam is situated on the Kaveri River in Tamil Nadu.",
    explanation_hi: "मेट्टूर बाँध कावेरी नदी पर तमिलनाडु में स्थित है।",
  },
  {
    question_en: "Dams: Bommanagar Dam is situated on which river?",
    question_hi: "दाम: बोम्मनगर बाँध (Bommanagar Dam) किस नदी पर स्थित है?",
    options_en: ["Periyar River", "Kaveri River", "Bhavani River", "Tungabhadra River"],
    options_hi: ["पेरियार नदी", "कावेरी नदी", "भवानी नदी", "तुंगभद्रा नदी"],
    correct_option_index: 1,
    explanation_en: "Bommanagar Dam is situated on the Kaveri River.",
    explanation_hi: "बोम्मनगर बाँध कावेरी नदी पर स्थित है।",
  },
  {
    question_en: "Rivers: Which are the tributaries of the Yamuna River?",
    question_hi: "नदियाँ: यमुना की कौन सी सहायक नदियाँ हैं?",
    options_en: ["Ramganga, Gomti", "Son, Punpun", "Chambal, Sindh, Betwa, Ken, Hindon", "Damodar, Son"],
    options_hi: ["रामगंगा, गोमती", "सोन, पुनपुन", "चंबल, सिंध, बेतवा, केन, हिंडन", "दामोदर, सोन"],
    correct_option_index: 2,
    explanation_en: "The tributaries of Yamuna include Chambal, Sindh, Betwa, Ken, Hindon, and Tons.",
    explanation_hi: "यमुना की सहायक नदियों में चंबल, सिंध, बेतवा, केन, हिंडन और टोंस शामिल हैं।",
  },
  {
    question_en: "Rivers: Where does the Damodar River (Sorrow of Bengal) originate?",
    question_hi: "नदियाँ: दामोदर नदी (बंगाल का शोक) का उद्गम कहाँ से होता है?",
    options_en: ["Mahabaleshwar", "Trimbakeshwar", "Amarkantak", "Chota Nagpur Plateau"],
    options_hi: ["महाबलेश्वर", "त्र्यंबकेश्वर", "अमरकंटक", "छोटानागपुर पठार"],
    correct_option_index: 3,
    explanation_en: "The Damodar River originates from the Chota Nagpur Plateau.",
    explanation_hi: "दामोदर नदी का उद्गम छोटानागपुर पठार से होता है।",
  },
  {
    question_en: "Rivers: Which river is also known as 'Utthal Pinakini'?",
    question_hi: "नदियाँ: किस नदी को 'उत्थल पिनाकिनी' नाम से भी जाना जाता है?",
    options_en: ["Mahanadi", "Godavari", "Kaveri", "Pennar River"],
    options_hi: ["महानदी", "गोदावरी", "कावेरी", "पेन्नार नदी (Pennar River)"],
    correct_option_index: 3,
    explanation_en: "The other name of the Pennar River is Utthal Pinakini.",
    explanation_hi: "पेन्नार नदी का अन्य नाम उत्थल पिनाकिनी है।",
  },
  {
    question_en: "Rivers: The Sabarmati River originates from which mountain range?",
    question_hi: "नदियाँ: साबरमती नदी का उद्गम किस पर्वत श्रृंखला से होता है?",
    options_en: ["Vindhyachal", "Satpura", "Aravalli Hills", "Western Ghats"],
    options_hi: ["विंध्याचल", "सतपुड़ा", "अरावली पहाड़ियाँ", "पश्चिमी घाट"],
    correct_option_index: 2,
    explanation_en: "The Sabarmati River originates from the Aravalli Hills.",
    explanation_hi: "साबरमती नदी का उद्गम अरावली पहाड़ियों से होता है।",
  },
  {
    question_en: "Rivers: The Mahanadi originates from which hill of Chhattisgarh?",
    question_hi: "नदियाँ: महानदी का उद्गम छत्तीसगढ़ के किस पहाड़ी से होता है?",
    options_en: ["Amarkantak", "Maikal Range", "Bastar", "Sihawa Hill"],
    options_hi: ["अमरकंटक", "मैकाल रेंज", "बस्तर", "सिहावा पहाड़ी"],
    correct_option_index: 3,
    explanation_en: "The Mahanadi originates from Sihawa Hill (Chhattisgarh).",
    explanation_hi: "महानदी का उद्गम सिहावा पहाड़ी (छत्तीसगढ़) से होता है।",
  },
  {
    question_en: "Rivers: Which line does the Mahi River cross twice?",
    question_hi: "नदियाँ: माही नदी (Mahi River) किस रेखा को दो बार काटती है?",
    options_en: ["Equator", "Tropic of Cancer", "Tropic of Capricorn", "International Date Line"],
    options_hi: ["विषुवत रेखा", "कर्क रेखा", "मकर रेखा", "अंतर्राष्ट्रीय तिथि रेखा"],
    correct_option_index: 1,
    explanation_en: "The Mahi River crosses the Tropic of Cancer twice.",
    explanation_hi: "माही नदी कर्क रेखा को दो बार काटती है।",
  },
  {
    question_en: "Lakes: Vembanad Lake is the longest lake in India. What type of lake is it?",
    question_hi: "नदियाँ: वेम्बनाड झील (Vembanad Lake) भारत की सबसे लंबी झील है, यह किस प्रकार की झील है?",
    options_en: ["Crater Lake", "Oxbow Lake", "Lagoon/Kayal Lake", "Tectonic Lake"],
    options_hi: ["क्रेटर झील", "गोखुर झील", "लैगून/कयाल झील", "विवर्तनिक झील"],
    correct_option_index: 2,
    explanation_en: "Vembanad Lake is a Lagoon/Kayal Lake.",
    explanation_hi: "वेम्बनाड झील एक लैगून/कयाल झील है।",
  },
  {
    question_en: "Lakes: What are the saline water lakes in Rajasthan locally called?",
    question_hi: "झीलें: राजस्थान में खारे पानी की झीलों को स्थानीय रूप से क्या कहा जाता है?",
    options_en: ["Tal", "Kayal", "Dhebar", "Playa"],
    options_hi: ["ताल", "कयाल", "ढेबर", "प्लाया (Playa)"],
    correct_option_index: 3,
    explanation_en: "The saline water lakes in the Jaisalmer district of Rajasthan are called Playa.",
    explanation_hi: "राजस्थान के जैसलमेर जिले में खारे पानी की झीलों को प्लाया कहा जाता है।",
  },
  {
    question_en: "Rivers/Cities: Ludhiana city is situated on the bank of which river?",
    question_hi: "नदियाँ/शहर: लुधियाना शहर किस नदी के तट पर स्थित है?",
    options_en: ["Yamuna", "Ganga", "Beas", "Satluj River"],
    options_hi: ["यमुना", "गंगा", "व्यास", "सतलुज नदी"],
    correct_option_index: 3,
    explanation_en: "Ludhiana city is situated on the bank of the Satluj River.",
    explanation_hi: "लुधियाना शहर सतलुज नदी के तट पर स्थित है।",
  },
  {
    question_en: "Rivers/Cities: Guwahati city is situated on the bank of which river?",
    question_hi: "नदियाँ/शहर: गुवाहाटी शहर किस नदी के तट पर स्थित है?",
    options_en: ["Ganga River", "Hooghly River", "Brahmaputra River", "Mahanadi"],
    options_hi: ["गंगा नदी", "हुगली नदी", "ब्रह्मपुत्र नदी", "महानदी"],
    correct_option_index: 2,
    explanation_en: "Guwahati city is situated on the bank of the Brahmaputra River.",
    explanation_hi: "गुवाहाटी शहर ब्रह्मपुत्र नदी के तट पर स्थित है।",
  },
  {
    question_en: "Geography Definition: The word 'Geography' is made up of which two words?",
    question_hi: "भूगोल परिभाषा: भूगोल (Geography) शब्द किन दो शब्दों से मिलकर बना है?",
    options_en: ["Temperature and Pressure", "River and Lake", "Geo (Earth) + Graphy (Description)", "Sun and Mandala"],
    options_hi: ["ताप और दाब", "नदी और झील", "Geo (पृथ्वी) + Graphy (वर्णन)", "सूर्य और मंडल"],
    correct_option_index: 2,
    explanation_en: "Geo (Earth) + Graphy (Description) means the description of the Earth.",
    explanation_hi: "Geo (पृथ्वी) + Graphy (वर्णन) का अर्थ है पृथ्वी का वर्णन।",
  },
];



export default test6Questions;
